recipes/bioconductor-purecn/meta.yaml
recipes/hmftools-purple/meta.yaml

- PureCN: adds support for specifying cores on command line
- PURPLE: adds X library dependencies required for creating
plots

Update: PureCN (multicore) and PURPLE (plotting X libraries)

---

recipes/transit/meta.yaml

Add recipe for transit version 2.3.1

---

recipes/r-pctgcdata/build.sh
recipes/r-pctgcdata/meta.yaml

@bioconda/r Please review this PR, I'm not sure that it's the good timing and syntax regarding the migration steps

r-pctgcdata

---

recipes/frogs/meta.yaml

With phyloseq 1.20:
```
Quitting from lines 74-113 (r_beta_diversity.Rmd) 
Error in .C(ape:::node_depth_edgelength, PACKAGE = "ape", as.integer(Ntip),  : 
Incorrect number of arguments (7), expecting 5 for 'node_depth_edgelength'
Calls: <Anonymous> ... UniFrac -> fastUniFrac -> ape_node_depth_edge_length -> .C
Execution halted
```
With vegan 2.5:
```
Quitting from lines 74-113 (r_beta_diversity.Rmd) 
Error in .C("veg_distance", x = as.double(x), nr = N, nc = ncol(x), d = double(N *  : 
"veg_distance" not available for .C() for package "vegan"
Calls: <Anonymous> ... distance -> do.call -> do.call -> vegdist -> vegdist -> .C
Execution halted
```

Fix some dependencies

---

recipes/bioconductor-purecn/meta.yaml

Update: PureCN (1.13.1) with additional segmentation options

---

recipes/bcftools-gtc2vcf-plugin/1.9/affy2vcf.c.patch
recipes/bcftools-gtc2vcf-plugin/1.9/build.sh
recipes/bcftools-gtc2vcf-plugin/1.9/fixref.c.patch
recipes/bcftools-gtc2vcf-plugin/1.9/gtc2vcf.c.patch
recipes/bcftools-gtc2vcf-plugin/1.9/meta.yaml

Add bcftools affy2vcf version 1.9 plugin

---

recipes/meme/build.sh
recipes/meme/meta.yaml

Fix detection of python 3 in MEME build script. Also added additional commands for tests in the meta.yml file.

Fix detection of python 3 in when building MEME 5.0.2

---

recipes/prosic/build.sh
recipes/prosic/meta.yaml

Unblacklisting prosic after the conda-build 3 update.

prosic: unblacklist with prosolo setup, incl. yacrd workarounds for build.sh

---

recipes/snakemake-minimal/meta.yaml

gitpython is listed as a dependency in Snakemake’s `setup.py`, but not as a run requirement in this recipe.

Add gitpython to snakemake dependencies

---

recipes/ensembl-vep/meta.yaml

ensembl-vep: remove perl-cgi dependency (not required anymore to run ensembl-vep)

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

Update: bcbio, bcbio-vm with CWL non-human fixes 

---

recipes/snakemake-minimal/meta.yaml
recipes/snakemake/meta.yaml

Make snakemake a noarch package.

---

recipes/r-airr/build.sh
recipes/r-airr/meta.yaml

Create `r-airr` recipe using `bgruening/conda_r_skeleton_helper`

Create r-airr recipe

---

recipes/pygenometracks/meta.yaml

Python 3 support was deactivated, but we tested against 3.6 so this should not be an issue. Moreover the dependency list was outdated and not correct anymore.

pyGenomeTracks update of dependencies

---

recipes/eggnog-mapper/meta.yaml

When downloading databases the wget flags used conflict with the wget in busybox, thus the extended-base container is needed.

Use the extended-base container for eggnog-mapper

---

recipes/hicexplorer/meta.yaml

HiCExplorer update to version 2.2-beta

---

recipes/msgf_plus/meta.yaml

This is hardly definite, but the conda-forge openJDK recipe got updated from 1.8 to 11.0 3 or so days ago. This led apparently to it dropping some classes that MSGF needs for XML reading. A later version of MSGF+ works fine apparently (so I will also update the MSGF version in this recipe to a newer version later). The problem is referenced here: https://github.com/MSGFPlus/msgfplus/issues/18.
I tried to use the `--add-modules java.xml.bind` but it hasnt worked (yet).

MSGFplus does not work with newer Java

---

recipes/gvcfgenotyper/build.sh
recipes/gvcfgenotyper/meta.yaml

New: gvcfgenotyper for joint calling with Illumina strelka2

---

recipes/msgf_plus/meta.yaml

Because otherwise it picks openJDK 10 from conda-forge (in my tests without forge it apparently picked openJDK 8 from the default channel).

Apparently we need openJDK to be below 9, not below 11 as in prev PR

---

recipes/pilon/meta.yaml
recipes/pilon/pilon.py

Bump pilon

---

recipes/bioconductor-dexseq/build.sh
recipes/bioconductor-dexseq/meta.yaml

Restore dexseq python helper scripts

---

recipes/medpy/meta.yaml

added medpy recipe

---

recipes/r-mcpcounter/build.sh
recipes/r-mcpcounter/meta.yaml

This is an R package to infer immune cell contents from gene expression data.

Add r-mcpcounter recipe. 

---

recipes/arb-bio/meta.yaml

@bgruening - I hate to ask, but the previous builds need to be removed from the channel. Otherwise `conda` will install glib `2.55.1` while `2.56.1` is needed (just because it was linked to 2.56, not because of ARB).  It breaks on OSX, Linux is more tolerant I think.
I've created issue conda-forge/glib-feedstock#38 and PR conda-forge/glib-feedstock#37 at CF to add `run_exports` to `glib`.

ARB: Pin glib

---

recipes/subread/meta.yaml

Updated package requested on [Subread mailing list](https://groups.google.com/d/msg/subread/TkXD0N3vLG8/7_uwRgDDAwAJ). From the [changelog](http://subread.sourceforge.net/):
**Release 1.6.3, 9 Oct 2018**
* Fixed a bug in subread-align and subjunc that may cause incorrect reporting of mapping result when a read is mapped out of chromosome boundary.
* Fixed a bug in featureCounts that may cause incorrect counting of reads when '--byReadGroup' is specified and unmapped reads are not included in the BAM input.
* Limit on the size of header in the SAM input is removed from featureCounts.

Update Subread from 1.6.2 to 1.6.3.

---

recipes/htseq/meta.yaml

I've run into issues when attempting to use HTSeq as a dependency for other packages (specifically DEXSeq).
```
/home/lparsons/miniconda3/envs/test_dexseq/lib/python2.7/site-packages/HTSeq/__init__.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
from _HTSeq import *
```
This is my attempt to resolve this issue, at least for this and future versions of HTSeq. I'm not sure if/how to fix this for prior versions of HTSeq.

HTSeq - Pin numpy version

---

recipes/clinvar-tsv/meta.yaml

Adding recipe for clinvar-tsv.

---

recipes/pysradb/meta.yaml

New recipe: pysradb

---

recipes/htseq/0.6.1.post1/meta.yaml
recipes/htseq/0.6.1/meta.yaml
recipes/htseq/0.7.2/meta.yaml
recipes/htseq/0.9.1/build.sh
recipes/htseq/0.9.1/meta.yaml

This is required to keep older versions of HTSEQ functional

Pin compatible numpy for older HTSEQ versions

---

recipes/var-agg/meta.yaml

Adding var-agg v0.1.1.

---

recipes/ucsc-cell-browser/meta.yaml

UCSC Cell Browser 0.4.23 was missing some dependencies for reading Seurat objects.

Missing deps for ucsc-cell-browser 0.4.23

---

.circleci/config.yml

@bgruening As discussed, this should restrict `bulk` to only build CRAN/bioconductor packages.

Restrict bulk to R and bioconductor recipes

---

recipes/ddrage/meta.yaml

Updated ddRAGE to version 1.6.3

---

recipes/snver/LICENSE
recipes/snver/SNVerIndividual.py
recipes/snver/SNVerPool.py
recipes/snver/build.sh
recipes/snver/meta.yaml

Add recipe for SNVer 0.5.3

---

recipes/r-seurat-scripts/meta.yaml

This PR bumps the referenced source package version. The new package version adds missing arguments and help text to the DimPlots wrapper seurat-dim-plot.R. The updated recipe also adds a dependency on qt for OSX, without which there is an issue with libpng.

r-seurat-scripts: Fixed DimPlots() issues, addressed libpng issue for OSX

---

recipes/bwise/build.sh
recipes/bwise/meta.yaml

bwise integration to bioconda

---

recipes/t-coffee/bin/.t-coffee-pre-link.sh
recipes/t-coffee/build.sh
recipes/t-coffee/meta.yaml

t-coffee 12.00.7fb08c2

---

recipes/spectra-cluster-cli/meta.yaml
recipes/spectra-cluster-cli/spectra-cluster-cli.py

Bump spectra-cluster-cli

---

recipes/pysradb/meta.yaml

bump pysradb 0.3.0 -> 0.4.0

---

recipes/fastqc/meta.yaml

For x-ref:
https://github.com/bioconda/bioconda-recipes/issues/5026
This adds `fontconfig` and a ttf font to the recipe, to make sure that it doesn't randomly fail on systems lacking these packages in the host environment. We had several issues with this:
https://github.com/nf-core/ampliseq/issues/44
https://github.com/SciLifeLab/Sarek/issues/701
Either the recipe failed when doing local testing with pipelines and/or the CI builds of our pipelines broke by stalling forever due to an error causing the JAR file to hang in and endless loop.

Add fontconfig / ttf-dejavu to fastqc recipe

---

recipes/concoct/meta.yaml

Updated concoct to version 1.0.0

---

recipes/comet/build.sh
recipes/comet/meta.yaml

Update comet-ms to 2018013

---

recipes/busco/meta.yaml

BUSCO does not parallelise correctly with BLAST+ version >= 2.4 (see [the code](https://gitlab.com/ezlab/busco/blob/master/src/busco/BuscoAnalysis.py#L891)). This update ensures that a suitable BLAST+ version is used.

BUSCO: Pin BLAST+ version to >= 2.2, < 2.4

---

recipes/popdel/build.sh
recipes/popdel/meta.yaml

* [yes] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [no] This PR adds a new recipe.
* [yes] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [yes] This PR updates an existing recipe.
* [no] This PR does something else (explain below).

Update PopDel to version 1.0.6

---

recipes/deepvariant/dv_make_examples.py
recipes/deepvariant/meta.yaml
recipes/deepvariant/post-link.sh

- Requires tensorflow 1.12
- Update model data for 0.7.2
- Remove requirement for --regions in dv_make_examples.py wrapper. Fixes #12560

Update: deepvariant 0.7.2 model and dependencies

---

.circleci/setup.sh
recipes/r-biodb/meta.yaml

Correct PATH definition, when extending it for miniconda.
When extending PATH env var, use quotes in order to handle potential space characters in PATH.

Use quotes when extending PATH.

---

build-fail-blacklist
recipes/r-gap/build.sh
recipes/r-gap/meta.yaml
recipes/r-grain/bld.bat
recipes/r-isogene/bld.bat
recipes/r-jackstraw/bld.bat
recipes/r-orqa/bld.bat
recipes/r-pcalg/bld.bat
recipes/r-rapidr/meta.yaml

[BULK] A few fixes

---

build-fail-blacklist
recipes/bioconductor-cicero/meta.yaml

a few updates, modify blacklist

---

recipes/bioconductor-rgraphviz/build.sh
recipes/bioconductor-rgraphviz/meta.yaml
recipes/r-clvalid/meta.yaml
recipes/r-dnet/meta.yaml
recipes/r-hardyweinberg/meta.yaml
recipes/r-wgcna/meta.yaml

Last updates for the year

---

build-fail-blacklist
recipes/r-diffcorr/build.sh
recipes/r-diffcorr/meta.yaml

add r-diffcorr and update blacklist

---

recipes/stacks/2.2/at.patch
recipes/stacks/2.2/build.sh
recipes/stacks/2.2/meta.yaml

really sorry, but the last fix did not work. I guess that in the constructed package there is no `@`, but only placeholders. Hence I guess this needs to be fixed during runtime.

stacks: another try for a fix for @ in exe_path

---

recipes/fermi2/meta.yaml

fermi2 generates a Makefile, so to run fermi2 we need make.

Add make to fermi2 runtime dependencies

---

build-fail-blacklist
recipes/bioconductor-champ/meta.yaml
recipes/r-bc3net/bld.bat
recipes/r-cp4p/bld.bat
recipes/r-enrichr/bld.bat
recipes/r-imp4p/bld.bat
recipes/r-mess/bld.bat
recipes/r-mess/build.sh
recipes/r-mess/meta.yaml
recipes/r-plsgenomics/bld.bat
recipes/r-rismed/bld.bat
recipes/r-tcr/bld.bat

a few updates

---

recipes/bioconductor-chromstar/meta.yaml
recipes/bioconductor-chromvar/meta.yaml
recipes/bioconductor-methimpute/meta.yaml
recipes/bioconductor-outrider/meta.yaml
recipes/r-fateid/meta.yaml
recipes/r-poppr/meta.yaml

@dpryan79 this brings us to a nearly complete OSX build on bulk. 3 recipes will still fail with gsl errors.
Will not merge it now as builds are running fine at the moment.

Bunch of OSX fixes for bulk

---

recipes/smhasher/meta.yaml

Otherwise it fails in a container with:
```
File "/data/users/mvandenb/gx124/data/shed_tools/toolshed.g2.bx.psu.edu/repos/mvdbeek/dedup_hash/f33e9e6a6c88/dedup_hash/dedup_hash/dedup_hash.py", line 161, in <module>
main()
File "/data/users/mvandenb/gx124/data/shed_tools/toolshed.g2.bx.psu.edu/repos/mvdbeek/dedup_hash/f33e9e6a6c88/dedup_hash/dedup_hash/dedup_hash.py", line 157, in main
hash_module=args.algo)
File "/data/users/mvandenb/gx124/data/shed_tools/toolshed.g2.bx.psu.edu/repos/mvdbeek/dedup_hash/f33e9e6a6c88/dedup_hash/dedup_hash/dedup_hash.py", line 26, in __init__
self.hash_module = self.import_hash_module(hash_module)
File "/data/users/mvandenb/gx124/data/shed_tools/toolshed.g2.bx.psu.edu/repos/mvdbeek/dedup_hash/f33e9e6a6c88/dedup_hash/dedup_has …
```

Fix smhasher

---

build-fail-blacklist
recipes/bioconductor-dexseq/meta.yaml
recipes/bioconductor-isolde/meta.yaml
recipes/bioconductor-process/meta.yaml
recipes/bioconductor-sparsedossa/meta.yaml
recipes/bioconductor-sparsenetgls/meta.yaml
recipes/bioconductor-specl/meta.yaml

Bulk update 090119b

---

recipes/rust-ncbitaxonomy/build.sh
recipes/rust-ncbitaxonomy/meta.yaml

This recipe builds the binaries from the ncbitaxonomy Rust crate - at the moment that only means `taxonomy_filter_refseq` but it might be more tools in the future.

Recipe for rust-ncbitaxonomy / taxonomy_filter_refseq

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

- Fixes docker errors with bcbio-vm on current Travis runs
- Fixes pinning of pytest-cov causing test errors with bcbio
- Adds support for running on Seven Bridges with CWL
- python 3 package for bcbio-vm

Update: bcbio, bcbio-vm with python3, docker SBG support

---

build-fail-blacklist
recipes/bioconductor-pga/meta.yaml
recipes/bioconductor-proteoqc/meta.yaml
recipes/bioconductor-sapfinder/meta.yaml
recipes/bioconductor-shinytandem/meta.yaml

A few version updates

---

build-fail-blacklist

This is waiting for r-fda to get a `gcc7` label and for r-compquadform to be rerun on circleci.

Update blacklist for packages that needed r-fda and r-compquadform

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/mirtop/meta.yaml
recipes/seqcluster/meta.yaml

- Adds latest development versions of mirtop and seqcluster with
python 3 support.
- Update bcbio-vm to avoid some dependencies and hopefully prevent
timeouts on travis tests.

Update: mirtop, seqcluster (py3); bcbio-vm (dependencies)

---

recipes/arvados-cwl-runner/meta.yaml
recipes/arvados-python-client/meta.yaml

Bring Arvados CWL integration up to date with latest cwltool and
dependencies. Fixed pycurl/curl incompatibilities with 1.8+
htslib/bcftools/samtools

Update: arvados-cwl-runner, arvados-python-client

---

recipes/unifrac/build.sh
recipes/unifrac/conda_build_config.yaml
recipes/unifrac/meta.yaml

This is a recipe for a fast Strided State UniFrac implementation (cc @wasade).
https://github.com/biocore/unifrac
I was able to build locally via:
```
bioconda-utils build recipes config.yml --docker --mulled-test --git-range master
```
so hopefully this works on CircleCI as well.

Add unifrac (strided state unifrac)

---

recipes/igv/build.sh
recipes/igv/meta.yaml

And pin openjdk to 8 (As mentioned on
https://software.broadinstitute.org/software/igv/download, the 2.4
series is Java 8 compatible only).

Update IGV to 2.4.16

---

recipes/kwip/build.sh
recipes/kwip/meta.yaml

By default, kWIP is built with -march=native, which will produce
binaries that only work on architectures similar to the TravisCI CPUs.
This defeats the purpose of conda, and should be disabled.
(I am upstream, and the above is deliberate, as most folks install from source, and will get a performance boost with `-march=native`)

kWIP: Hopefully fix incompatible instruction set

---

recipes/ataqv/meta.yaml

`ataqv` should now be built with both Python 2.7 and Python 3.x.

ataqv - Removed Python version dependency

---

recipes/graphaligner/meta.yaml
recipes/graphaligner/version.patch

@bioconda/core I'm using "version.patch" to set the version in my makefile. I previously tried to set the version using the environment variable PKG_BUILD_STRING (https://conda.io/docs/user-guide/tasks/build-packages/environment-variables.html#environment-variables-set-during-the-build-process), but instead of the version number it was getting replaced with the text "placeholder", leading to the version displayed in the program being "bioconda placeholder" instead of "bioconda 1.0.1". I'm now trying to replace this with PKG_VERSION and PKG_BUILD_NUMBER. Is this an appropriate way of inserting the version or is there a best practice way of setting the version during building?

GraphAligner versioning

---

recipes/plek/build.sh

PLEK.py throws error because of missing PLEK.range file. This commit fixes it.

Fixed missing file PLEK.range for PLEK receipe.

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

Update: bcbio (1.1.3 release), bcbio-vm (AWS support)

---

build-fail-blacklist
recipes/r-bcbiobase/meta.yaml

Build r-bcbiobase for R 3.5

---

recipes/cnvkit/meta.yaml

Previous build, which fixes CNVkit with recent pandas, failed when
building on CircleCI so doesn't have a new package. Bump build number
and re-build.
https://circleci.com/gh/bioconda/bioconda-recipes/40931

Update: CNVkit bump for failed linux build

---

build-fail-blacklist
recipes/r-bcbiornaseq/meta.yaml

Build r-bcbiornaseq for R 3.5.1

---

recipes/rust-bio-tools/meta.yaml

rust-bio-tools 0.2.8

---

recipes/perl-html-form/build.sh
recipes/perl-html-form/meta.yaml
recipes/perl-www-mechanize/build.sh
recipes/perl-www-mechanize/meta.yaml

Perl www mechanize and dependancies

---

recipes/percolator/meta.yaml

Trying to bump to 3.2.1 for percolator, using the same kind of boost library that openMS uses to be able to use both recipes in a single conda environment here.

Percolator 3.2.1 Bump

---

recipes/samtools/meta.yaml

See #13448
Simply rebuilding samtools did not grab the more recent openssl.
(See previous commit.)

samtools w/ openssl >= 1.1.1

---

recipes/chado-tools/meta.yaml

chado-tools 0.2.5

---

recipes/pb-assembly/meta.yaml

This does not solve our problem in all cases, and it may
hinder bioconda-wide changes to the openssl version.
See https://github.com/bioconda/bioconda-recipes/pull/13448

pb-assembly: Do not specify openssl version (#13464)

---

recipes/biobb_analysis/build.sh
recipes/biobb_analysis/meta.yaml

Feb 2019 Release

---

recipes/samtools/meta.yaml

Maybe the whole problem was that it was being built against
system openssl. I do not see where openssl-1.1.1 is being
specified in Bioconda. In theory, we should be using 1.0.2
everywhere already.
https://github.com/conda-forge/conda-forge.github.io/issues/701

Maybe this should depend on openssl explicitly

---

recipes/sumaclust/build.sh
recipes/sumaclust/meta.yaml

sumaclust breaks nightly builds

---

recipes/stream/meta.yaml

update stream to 0.3.5

---

recipes/stacks/2.3b/at.patch
recipes/stacks/2.3b/build.sh
recipes/stacks/2.3b/conda_build_config.yaml
recipes/stacks/2.3b/meta.yaml

see https://groups.google.com/d/msg/stacks-users/QYW8Pd15FI8/eALNz1gqEgAJ

stacks: adds version 2.3b

---

recipes/arvados-cwl-runner/meta.yaml
recipes/arvados-python-client/meta.yaml

Update: arvados-cwl-runner, arvados-python-client; py3k

---

.github/PULL_REQUEST_TEMPLATE.md

Adding new to the PR template

---

recipes/tango/build.sh
recipes/tango/meta.yaml

[TANGO](https://github.com/johnne/tango) (**T**axonomic cl**A**ssificatio**N** of meta**G**enomic c**O**ntigs) is a tool that assigns taxonomy to (metagenomic) contigs.

Initial commit for package tango

---

recipes/tximport-scripts/build.sh
recipes/tximport-scripts/meta.yaml

This is another R package CLI along the lines of e.g. [r-seurat-scripts](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/r-seurat-scripts). This is basically a single rich wrapper script for the central tximport() function of the Bioconductor tximport package. It uses DropletUtils to provide optional sparse matrix output. Source package at https://github.com/ebi-gene-expression-group/tximport-scripts. I've dropped the 'r-' prefix convention to prevent interference with build systems recognising r packages (to be remedied in r-seurat-scripts in the future).

Added tximport-scripts recipe

---

recipes/bwa/Makefile.patch
recipes/bwa/meta.yaml

This PR adds makefile flags necessary to force BWA compilation to use the conda GCC compilers, rather than those inherited from the docker image.  

[WIP] Add makefile patch, bump BWA.

---

recipes/bwa/0.7.3a/Makefile.patch
recipes/bwa/0.7.3a/meta.yaml

Note: the patch is necessary to avoid hard-coding GCC to the container / OS version.

Rebuild BWA 0.7.3a for GCC7

---

recipes/arvados-cwl-runner/meta.yaml
recipes/arvados-python-client/meta.yaml

Original noarch approach didn't work properly on py3k due to
subprocess32 conditional selector. It doesn't get applied on
noarch so will be a dependency and make it incompatible with py3.
Trying a new approach to restrict to avoid py37 errors.

Update: arvados-cwl-runner, arvados-python-client; second py3k attempt

---

recipes/npinv/meta.yaml

This PR changes the dependency to openjdk >=8,<9. Using openjdk11 caused errors, but not in the CI test case.

trying to fix the openjdk java version

---

recipes/r-brio/build.sh
recipes/r-brio/meta.yaml

As for https://github.com/bioconda/bioconda-recipes/pull/13596, https://github.com/bioconda/bioconda-recipes/pull/13614 and https://github.com/bioconda/bioconda-recipes/pull/13592, this package provides a dependency for updating the r-basejump package.

Added r-brio

---

recipes/ucsc-cell-browser/build.sh
recipes/ucsc-cell-browser/meta.yaml

Switches installation to `python -m pip` mode to avoid egg based installation and move to latest released version.

Move to ucsc-cell-browser 0.4.38

---

recipes/isocor/meta.yaml

Isocor recipe

---

recipes/r-bcbiobase/meta.yaml

The recipe needs to be updated to pin [`r-basejump`](https://github.com/steinbaugh/basejump) 0.7.2 specifically, because the current release (0.9.9) isn't yet fully backward compatible with `r-bcbiobase` 0.4.1 and/or `r-bcbiornaseq` 0.2.8. An updated version of `r-basejump` has …

Update r-bcbiobase recipe to pin r-basejump 0.7.2

---

recipes/r-basejump/meta.yaml

This is an update to the basejump package, having added newly factored-out dependencies. WIP until @mjsteinbaugh has sorted pinning for downstream dependents.

Update r-basejump to v0.9.9 with additional package dependencies

---

recipes/arb-bio/meta.yaml

Fix ARB run_exports

---

recipes/gromacs/2019/meta.yaml

Update for Gromacs 2019.1

---

recipes/compare-reads/build.sh
recipes/compare-reads/meta.yaml

Add compare-reads

---

recipes/ataqv/build.sh
recipes/ataqv/meta.yaml

This is a rebuild of:
https://github.com/bioconda/bioconda-recipes/pull/13374
https://github.com/bioconda/bioconda-recipes/pull/13160
`ataqv` requires the `web/` directory in `${PREFIX}/` to run one of its commands.
https://github.com/ParkerLab/ataqv/tree/master/src/web
`build.sh` has been …

Amend build for ataqv

---

recipes/whatshap/meta.yaml

WhatsHap 0.18

---

recipes/kaiju/meta.yaml

python is required to run `makeDB.sh` script so I have added it to the run requirements and bumped the build number.  
fixes https://github.com/bioinformatics-centre/kaiju/issues/104

kaiju - add python to run requirements

---

recipes/fusioncatcher/build.sh
recipes/fusioncatcher/download-db.sh
recipes/fusioncatcher/meta.yaml
recipes/fusioncatcher/paths.patch
recipes/fusioncatcher/post-link.sh

Add recipe for fusioncatcher

---

recipes/bioconductor-flowtype/meta.yaml

Bump build number to trigger the build again, as the recipe [was merged](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bioconductor-flowtype) a month ago but no package shows up on the channel.

Re-build for `bioconductor-flowtype`

---

recipes/fastqpuri/build.sh
recipes/fastqpuri/meta.yaml

Changes to be committed:
new file:   recipes/fastqpuri/build.sh
new file:   recipes/fastqpuri/meta.yaml

add a recipe for FastqPuri

---

build-fail-blacklist
recipes/bioconductor-arrayexpresshts/meta.yaml
recipes/bioconductor-esatac/meta.yaml

It looks like rJava has now been rebuilt.

---

build-fail-blacklist

Remove more rJava packages from the blacklist

---

build-fail-blacklist
recipes/bioconductor-rmassbank/meta.yaml

Remove the remainder of the rJava bioc packages from the blacklist

---

recipes/cpat/meta.yaml

In CPAT's code the version check for a python version that starts with 2.7 is hardcoded.
So I have updated the recipe to reflect this. Only python 2.7 is allowed now in the conda environment.

CPAT: Stricter python version requirement

---

recipes/arvados-cwl-runner/meta.yaml
recipes/arvados-python-client/meta.yaml
recipes/bcbio-variation-recall/meta.yaml

- arvados: fix py3k support by avoiding subprocess32 on py3k
- bcbio-variation-recall: fix platypus contig header generation.
Fixes bcbio/bcbio-nextgen#2688

Update: arvados-python-client, arvados-cwl-runner, bcbio-variation-recall

---

recipes/medaka/meta.yaml

bump medaka version

---

recipes/pytest-workflow/meta.yaml

Pytest-workflow is a pytest add-on that allows a user to configure workflow test in YAML. This package is used at the LUMC to test our Cromwell/WDL pipelines as well as our Snakemake pipelines. Testing of pipelines in other frameworks is also possible, because pytest-workflow is framework agnostic.
https://pytest-workflow.readthedocs.io/en/stable/

New recipe: pytest-workflow

---

recipes/chado-tools/meta.yaml

update chado-tools to version 0.2.8

---

recipes/cd-hit/build.sh
recipes/cd-hit/meta.yaml

Update cd-hit to newest version and fix GCC7 issues

---

recipes/mccortex/build.sh
recipes/mccortex/meta.yaml
recipes/mccortex/run_test.sh

Compile mccortex for extra kmer sizes

---

recipes/samtools/meta.yaml

Another attempt to fix the severe brokenness of bioconda. This is really
driving me crazy.
See 7985452cbb25dc68fdeb033ed53105cc48ae8c0e
and experiments in pb-falcon and pb-assembly

samtools: pin openssl < 1.1

---

recipes/nextgenmap/meta.yaml

Without an assembler installed, NGM fails with a 'program build error' when
JIT compiling the OpenCL code. Discovered when trying to run NextGenMap in
a miniconda docker container which does not have the binutils installed.

Let NextGenMap depend on bintuils, because it's OpenCL implementation uses 'as'

---

recipes/motus/meta.yaml

Original pull request is #13885 and there's doesn't seem to be a reason for this failure.
Retrying by increasing the build number.

Retry motus 2.1.0 due to CI failure after merge

---

recipes/fit_nbinom/meta.yaml

This PR adds a conda package to enable the fitting of negative binomial distributions via a maximum likelihood estimator. This feature is missing in scipy.

Adding recipe for fit_nbinom

---

recipes/hla-la/1.0/meta.yaml

Hadn't realized I should have updated the build number after fixing a bug in post-link.sh (https://github.com/bioconda/bioconda-recipes/pull/13767)

Increase build number

---

recipes/digestiflow-cli/meta.yaml

Releasing digestiflow-cli v0.5.1

---

recipes/samtools/meta.yaml

Not pinning openssl for runtime sometimes caused openssl-1.1 to be installed breaking samtools
Related to #12100 and #13903
:information_source: :

samtools: Use same openssl for host and run

---

recipes/motus/meta.yaml

This update does two things:
1.  Update the recepe with a new version
2.  Try to solve the problem with samtools mentioned in https://github.com/bioconda/bioconda-recipes/issues/12100. In the samtools recipe ([link](https://github.com/bioconda/bioconda-recipes/blob/e53d407b6ce688974659b88bdc501f48c260cad8/recipes/samtools/meta.yaml)) it's required `openssl <1.1` for `host`, but not for `run`. As a result, during run `openssl 1.1` is used, and samtools is not working. To solve this we:
- add `openssl=1.0` to our recipe in the `run` section
- change the test section, where we run a script that test if samtools is properly installed.

Update to version 2.1.1

---

recipes/shmlast/meta.yaml

Bump shmlast build num and remove pytest version restriction

---

recipes/lastz/build.sh
recipes/lastz/meta.yaml

Update to lastz recipe to also build the binary 'lastz_32'.
This binary is used to handle genomes bigger than 2Gb.
This is my first recipe @bioconda/core 

Added building lastz_32 to lastz recipe. 

---

recipes/pbcopper/meta.yaml

PacBio: rebuild pbcopper for GCC 7

---

recipes/nanopolish/meta.yaml

Trigger rebuild for `openssl 1.1` pinning.

Rebuild nanopolish for openssl 1.1

---

recipes/deepbgc/meta.yaml

Fix for #14007
@dpryan79 Can you please take a look at this fix for the DeepBGC module? It turns out the original python version specification was correct, specifying `python >=2.7, >3` will only accept version `>3`. 
Is it possible to fix this for version 0.1.3 or do we have to do a new version? 
Thanks!

Fix version support for Python2.7

---

recipes/hyphy/2.3.11/meta.yaml

I'm not positive why it changed, but now `$PREFIX/bin/HYPHYMPI` gets dynamically linked against `libcrypto.so.1.1`, which is found in `openssl=1.1.1`

Update openssl dependency

---

recipes/motus/meta.yaml
recipes/motus/post-link.sh

This is unnecessary now that samtools was updated to build against openssl-1.1

Remove openssl=1.0 pinning in motus

---

recipes/dropletutils-scripts/meta.yaml

Relax version requirement of bioconductor-dropletutils to <1.3

---

recipes/gat/meta.yaml

Previous recipe(s) required python without specifying the version. This
resulted in python3 to be used. However, GAT requires python2 making the
current recipe faulty. Previous tests passed because `gat-run.py -h`
doesn't hit any incompatibility.

Require python to be version 2

---

recipes/motus/meta.yaml

The previous build finished successfully but linting got stuck [in a weird state](https://github.com/bioconda/bioconda-recipes/runs/81038702)
And as consequence we don't yet have motus-2.1.1 in bioconda.

Bump motus build again

---

recipes/chorus2/meta.yaml

Chorus2 is a pipeline to select oligonucleotides for fluorescence in situ hybridization (Oligo-FISH). It can genome-widely design and select probes for FISH in plant and animal species.

add recipe for chorus2

---

build-fail-blacklist

motus was blacklisted during the openssl transition.
Removing from blacklist now that things are working again.

Remove motus from build-fail-blacklist

---

recipes/perl-threaded/meta.yaml

Xref: https://github.com/bioconda/bioconda-recipes/issues/13415
It looks like in the mass rebuild last summer perl-threaded got uploaded in a broken version for OSX but then in a fixed version for Linux a few weeks later. This should fix the OSX build while also bringing the version information more in line with the version of perl actually used.
Bioconda has finished the [GCC7 migration](https://github.com/bioconda/bioconda-recipes/issues/13578). If you are dealing with C/C++ or Python package it can be that you need to rebuild other dependent packages. [Bioconda utils - update-pinning](https://bioconda.github.io/updating.html#updating-recipes-for-a-pinning-change) will assist you with that. If you have any questions please use [issue …

Fix perl-threaded on OSX

---

recipes/khmer/meta.yaml

Removes dependency on pytest-runner

Bump khmer to 3.0.0a3

---

recipes/ngless/build.sh
recipes/ngless/meta.yaml

This is redistributing the binary, instead of compiling from scratch.
This is far from the ideal solution, but given that there is no
currently-working method to obtain a working recent-enough GHC on the
bioconda build systems, I do not see how else to package NGLess. I note
that stack is also packaged in this fashion.

Update ngless to v0.11.1

---

recipes/hicmatrix/meta.yaml

HiCMatrix update to version 8. Drop of Python 2 support.

---

build-fail-blacklist
recipes/fwdpy11/build.sh
recipes/fwdpy11/meta.yaml

I am removing fwdpy11 from the blacklist.  I recently update the recipe to 0.2.1, but noticed that it never became available for download b/c it was blacklisted.
Related: should the linting be checking for updates to blacklisted packages and issuing a warning?

remove fwdpy11 from blacklist

---

recipes/digestiflow-cli/meta.yaml

Bumping digestiflow-cli to v0.5.2.

---

recipes/fusion-report/build.sh
recipes/fusion-report/meta.yaml

This PR adds fusion-report tool that generates interactive summary report from fusion detection tools. It is part of a bigger pipeline `nf-core/rnafusion`.

Added fusion-report 1.0.0

---

recipes/fusion-report/meta.yaml

This is a downgrade for python dependency so that there is a small chance of dependency collision.

Downgrade Python dependency from 3.7 to 3.6

---

recipes/entrez-direct/meta.yaml

This pull requests updates entrez direct to version 11.0 for reasons noted in https://github.com/bioconda/bioconda-recipes/issues/14197
* [*] This PR updates an existing recipe.

updated entrez direct to version 11.0

---

recipes/bioconductor-rhdf5lib/meta.yaml

bioconductor-rhdf5lib: revert to Bioconductor URL

---

recipes/lumpy-sv/meta.yaml

Added hexdump-, sambamba- and samblaster dependencies under run and increased the build number to 4.

Lumpy-express dependencies added

---

recipes/nanopolish/meta.yaml

Nanopolish bioconda update

---

recipes/hla-la/1.0/meta.yaml

Updated build number to reflect bugfix in HLA*LA release

---

recipes/perl-logger-simple/build.sh
recipes/perl-logger-simple/meta.yaml

This package is needed for "braker2", which is bioinformatics tool. "perl-logger-simple" should go to conda-forge; however, all its dependencies are in "bioconda". These dependencies have another dependencies that are in "bioconda" too, so once the perl recipes are moved to conda-forge, I will …

Add recipe for perl-logger-simple

---

recipes/mtsv/meta.yaml

This reverts commit 2698489c9177386841b84e29e45b0916c2470a74 from #14248 

Revert "update source (#14248)"

---

recipes/tb-profiler/meta.yaml

Upstream author has updated 2.1 release with better "usage" method. This captures that update and thus bumps the build number (the upstream release number hasn't changed). Also updates description and adds DOI.

Update to capture new "usage" help

---

recipes/kmc/meta.yaml
recipes/kmc/shared_library.patch

Fixes KMC Makefile patch to compile all objects (see https://github.com/bioconda/bioconda-recipes/pull/14217#issuecomment-478514829)

Updates kmc recipe

---

recipes/perl-file-path/meta.yaml

Fix perl-file-path

---

recipes/libsequence/meta.yaml

bump libsequence recipe to 1.9.7

---

recipes/ismapper/meta.yaml

This PR is an attempt to resolve https://github.com/bioconda/bioconda-recipes/issues/14264 (https://github.com/bioconda/bioconda-recipes/pull/14180) in which the first build was never initiated.

Attempt rebuild of ismapper

---

.circleci/config.yml
recipes/dnaio/meta.yaml
recipes/pywdl/meta.yaml

Changes (hopefully) the CircleCI config so that the built-packages get uploaded as artifacts after the test. This should make debugging a little easier. Potentially might even allow installing the package locally after successful test, to double check things that cannot be easily tested with the …

Store built packages on CI's artifact system after test

---

recipes/kraken2/meta.yaml

kraken2: Use conda-forge::wget instead of bioconda::gnu-wget

---

recipes/athena_meta/build.sh
recipes/athena_meta/meta.yaml

bump to use athena version 1.3, and fix to use flye 2.3.1

---

recipes/arriba/meta.yaml

Compatibility of Arriba with HTSlib version 1.9 was tested successfully. Therefore, pinning to version 1.8 is not necessary.

do not pin Arriba to specific HTSlib version

---

recipes/varfish-annotator-cli/meta.yaml

Bumping varfish-annotator-cli to v0.2

---

recipes/bismark/meta.yaml

This bumps the bismark version to v0.21.0 and adds hisat2 as a new dependency, since bismark now optionally supports alignment using hisat2

bismark v0.21.0

---

recipes/trimmomatic/meta.yaml

Trimmomatic 0.39 was updated due to bug. Same version.

Updated Trimmomatic 0.39 (same version) requires new build and SHA256

---

recipes/quasitools/meta.yaml

`quasitools call` and `quasitools hydra` subcommands are broken in py3 for build 0, this pr fixes that issue.

Bump build for quasitools to fix sub commands for py3

---

recipes/quasitools/meta.yaml

make quasitools noarch: python, try fixing the container

---

recipes/methyldackel/build.sh
recipes/methyldackel/meta.yaml

Update MethylDackel to 0.4.0

---

.github/PULL_REQUEST_TEMPLATE.md

@bioconda/core I think this note can be removed now?

remove GCC7 hint

---

recipes/scprep/meta.yaml

Bump scprep to v0.12.0

---

recipes/medaka/meta.yaml

update medaka to v0.6.4

---

recipes/mantis/build.sh
recipes/mantis/meta.yaml

This disables the use of Haswell instructions for greater portability

Disabling Haswell instructions in mantis

---

.circleci/config.yml
recipes/sina/meta.yaml

Store mulled docker images as artifacts. See https://github.com/bioconda/bioconda-utils/issues/508

Store docker images as artifacts

---

recipes/cromwell/build.sh
recipes/cromwell/cromwell.py
recipes/cromwell/meta.yaml
recipes/cromwell/womtool.py

The original recipe did a lot of compiling and the resulting jar would not match the Jar as released by broadinstitute. 
This downloads those jars directly. It saves a lot of compile time and other hassle.
@micknudsen do you approve of this? Since you last updated cromwell.
@bioconda/core is this an okay way of packaging java packages?

Cromwell to use the released jars.

---

recipes/maker/build.sh
recipes/maker/meta.yaml

When run using MPI, maker seems to segfault in various places during execution. However, modifying the maker recipe to switch the MPI implementation from openmpi to mpich seems to resolve the issue---at least in our environment (HPC cluster environments are all bespoke to some extent, and it's difficult to ascertain whether some subtle configuration issue is causing problems).
@abretaud : could you please validate this proposed change? Otherwise, have you had success with this maker recipe using Open-MPI?

Build maker with mpich instead of openmpi to avoid runtime segfaults

---

recipes/perl-bioperl-core/meta.yaml
recipes/perl-bioperl-core/pr309.patch

This PR backports the commit from the following bioperl-live (post 1.7.5 release) PR to 1.7.2:
https://github.com/bioperl/bioperl-live/pull/309
The aforementioned patch (authored by a MAKER developer) is important for (at least) avoiding odd runtime errors when running MAKER using MPI.

Backport bioperl-live patch to perl-bioperl-core

---

recipes/gatk4/build_main.sh
recipes/gatk4/build_spark.sh
recipes/gatk4/meta.yaml

Following up on the [discussion](https://github.com/bioconda/bioconda-recipes/issues/15059) we had here, I put some work into including the spark parts of GATK4 into the recipe, too. 
This now creates two packages: `gatk4` with the local version and `gatk4-spark` with the required spark JARs inside. The latter depends on `gatk4` to be installed in the exact same version in order not to break things. 
-- edit: fixes #15059

Introduce GATK4 Spark to Bioconda

---

recipes/bioconductor-seqcat/meta.yaml

This is my very first PR to Bioconda, so would appreciate feedback from @bioconda/core. I started to read up on how to add a recipe for my `seqCAT` Bioconductor package, and got to the point of creating a skeleton when I realised it had already been added in a bulk submission some months back. I thus wanted to update the package to the latest version, but it seems Bioconda does not yet use `R 3.6`? At least I thought I could update from `1.4.0` to `1.4.1`. I tried to build it locally, which ran successfully, but please let me know if I did something wrong or if I need to change something. 

Update seqCAT to version 1.4.1

---

recipes/kaiju/build.sh
recipes/kaiju/meta.yaml

I have updated the kaiju files for the new version 1.7.0. Please review.
I don't understand the meaning of the lines 
```
build:
number: 2
no_link:
- bin/kaiju-makedb.sh  
```
I just replace makeDB.sh by kaiju-makedb (which is also a bash script and supercedes makeDB.sh).
* [ x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ x ] This PR updates an existing recipe.
@charlesreid1 @bioconda/core

update kaiju to v1.7.0

---

recipes/thapbi-pict/meta.yaml

The main change in the tool of relevance to the packaging is optional Excel output, which needs the ``xlsxwriter`` dependency (another Python package):
https://anaconda.org/conda-forge/xlsxwriter

THAPBI PICT to v0.1.12, new xlsxwriter dependency

---

recipes/phantompeakqualtools/meta.yaml

`run_spp.R` uses the `awk` bitwise operation `and()`. This is unavailable in `mawk` (AFAIK) and so `run_spp.R` failed on my system.
By adding `gawk` to the env in which I ran `phantompeakqualtools` `run_spp.R` script, I could get the latter to work.

[phantompeakqualtools] - add `gawk` as a requirement

---

recipes/cluster-picker/meta.yaml
recipes/opsin/1.4.0/meta.yaml
recipes/opsin/2.1.0/meta.yaml
recipes/opsin/2.4.0/meta.yaml

Fix structure of recipe

---

recipes/fishtaco/meta.yaml

Disable autobump for fishtaco (license issue)

---

recipes/fineradstructure/build.sh
recipes/fineradstructure/meta.yaml

fineRADstructure

---

recipes/biobb_analysis/build.sh
recipes/biobb_analysis/meta.yaml

v1.0.2 May 2019 Release

---

recipes/perl-bioperl/meta.yaml

Since PR https://github.com/bioconda/bioconda-recipes/pull/12040, perl-bioperl-core changed from version 1.7.2 to 1.007002. Need to update the version pin in perl-bioperl to get newer builds of perl-bioperl-core.

Fix perl-bioperl-core version pin

---

recipes/maker/meta.yaml
recipes/maker/mpi_init.patch

This PR implements several minor changes to the maker recipe to allow running maker from a Biocontainers-derived Singularity container on multiple nodes of an HPC cluster using the host MPI.
@abretaud : could you please review?
1. Add `-mpi` option to maker script
The "maker" script tries to detect if its parent process is an MPI process manager, and if so enables MPI support. This autodetection can fail when MAKER is run from a Singularity container.  The patch adds a command-line "-mpi" option to the "maker" script to override MPI autodetection and force MPI on. I have communicated with MAKER maintainer Carson Holt; he may include something similar in the next MAKER release, in which case this patch could be removed. 
2. Use the extended base image
If the host (MPICH-derived) MPI …

MAKER: add support for running Biocontainers-derived Singularity images using host MPI

---

recipes/rsidx/meta.yaml
recipes/rsidx/run_test.sh

This PR contains a recipe for a new package rsidx for indexing VCF files for search by rsID. The index is an sqlite3 db mapping rsIDs to genomic coordinates. The query feature uses the index to retrieve coordinates for each query term and then retrieve the requested variant using tabix.
----------

Recipe for new package rsidx

---

recipes/microhapulator/meta.yaml
recipes/microhapulator/run_test.sh

This PR updates the MicroHapulator package to version 0.2. The test build is simplified, and based on the review for version 0.1.3 I've also [restricted pysam version to < 0.16](https://github.com/bioconda/bioconda-recipes/pull/15040#discussion_r283975028).
---------

Update MicroHapulator recipe to release 0.2

---

recipes/pycoqc/meta.yaml

Pycoqc requires h5py

---

recipes/fastqsplitter/meta.yaml

A simple tool to split fastq files evenly with no positional bias.

add fastqsplitter recipe

---

build-fail-blacklist
recipes/bioconductor-mzr/2.16.2/build.sh
recipes/bioconductor-mzr/2.16.2/meta.yaml
recipes/bioconductor-mzr/meta.yaml

the so file currently seems to link wrong:
```ldd CONDA_ENV/lib/R/library/mzR/libs/mzR.so
...
libnetcdf.so.11 => not found
libhdf5_hl.so.10 => not found
libhdf5.so.10 => not found
```

mzr: try to fix linking error by rebuilding

---

recipes/hint/build.sh
recipes/hint/meta.yaml

add hint recipe

---

recipes/r-basejump/meta.yaml
recipes/r-bioverbs/meta.yaml
recipes/r-brio/meta.yaml
recipes/r-freerange/build.sh
recipes/r-freerange/meta.yaml
recipes/r-goalie/meta.yaml
recipes/r-syntactic/meta.yaml
recipes/r-transformer/meta.yaml

This pull request updates r-basejump to v0.10.9. The r-freerange recipe needs to be added, as this is a new dependency for the basejump package.

Update r-basejump recipe and dependencies

---

recipes/salmon/meta.yaml

bump salmon to version 0.14.0 build 1

---

recipes/snakemake-minimal/meta.yaml
recipes/snakemake/meta.yaml

snakemake 5.5.0

---

recipes/tspex/meta.yaml

Bump tspex to 0.5.0

---

recipes/hyphy/meta.yaml
recipes/msstitch/meta.yaml
recipes/peptide-shaker/meta.yaml
recipes/perl-cgi/meta.yaml
recipes/vardict-java/meta.yaml
recipes/vardict/meta.yaml

Vardict update

---

recipes/unitig-counter/meta.yaml

Bump unitig-counter to new release v1.0.5 (fixes error on exit)

Update unitig-counter to v1.0.5

---

build-fail-blacklist
config.yml
recipes/igvtools/build.sh
recipes/igvtools/igvtools.sh
recipes/igvtools/meta.yaml
recipes/sra-tools/build.sh
recipes/sra-tools/meta.yaml
recipes/tpmcalculator/build.sh
recipes/tpmcalculator/meta.yaml

Adding new recipe (ncbi/TPMcalculator) and bumping igvtools and sra-tools to latest versions

---

recipes/ariba/meta.yaml

I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
AFAIK, this recipe is directly relevant to the biological sciences
This PR updates an existing recipe.

Ariba v2.14.0 release

---

bootstrap.py

Under a machine with a proxy configured the script bootstrap.py was failing with the following error:
```
$ ./bootstrap.py /tmp/miniconda
fatal: unable to access …
```

fix bootstrap.py with proxy

---

bootstrap.py

Fixing the PR #15834 when variables are not set in the environment.

bootstrap fix call to env. variables when they are not set

---

recipes/blast/build.sh
recipes/blast/meta.yaml

Removing export that pollutes conda env PATH

---

recipes/snippy/meta.yaml

Hi @bioconda/core, this is a pull request to update the recipe for snippy in response to [this issue](https://github.com/tseemann/snippy/issues/259), though I'm not sure the inclusion of  `java-jdk =8.0.112` in the `meta.yaml` is a working fix.  I ran tests on branch `snippy_4.4.0` via CircleCI and they appear to be passing.  I've since turned off CircleCI builds on my fork.
For future reference, how would I go about testing the .tar.bz2 generated by conda-build?

Snippy 4.4.0

---

recipes/qualimap/build.sh
recipes/qualimap/meta.yaml

@bioconda/core @apeltzer
Hello, I have encountered a problem when running the following command:
```shell
qualimap counts -c -d path/to/samples_data.txt --java-mem-size=8G  -outformat html -outdir path/to/couts_qc
```
It gave the error:
```
Rscript /home/hidden/usr/miniconda3/envs/bioinfo/bin/scripts/countsQC.r --homedir /home/tangwh/usr/miniconda3/envs/bioinfo/bin/scripts --input /tmp/qualimap1560852042263//input.txt -k 5 --compare -o /tmp/qualimap1560852042263/
Fatal error: ??????'/home/hidden/usr/miniconda3/envs/bioinfo/bin/scripts/countsQC.r': ?????????
Failed to run counts
java.lang.RuntimeException: The RScript process finished with error.
Check log for details.
at org.bioinfo.ngs.qc.qualimap.process.CountsQcAnalysis.run(CountsQcAnalysis.java:120)
at …
```

set QUALIMAP_HOME to proper path in qualimap wrapper script

---

recipes/sambamba/meta.yaml

ldc > 1.10 causes segfaults

---

recipes/snippy/meta.yaml

Hi @bioconda/core, this is a pull request to update the recipe for snippy in response to [this issue](https://github.com/tseemann/snippy/issues/259) and is a correction to PR #16003.  This recipe specifies `openjdk =8` in the `meta.yaml`, ensures that Java 8 is called for snpEff as recommended by @tseemann
May the SNPs be with you.

specifies openjdk for Java 8

---

recipes/ganon/build.sh
recipes/ganon/meta.yaml

Build was reported broken (Illegal instruction) for some users due to -march=native flag for compilation. This build update removes those flags for conda builds following the …

fix update ganon v0.1.3

---

recipes/nullarbor/meta.yaml

Just added `make ` in the requirements list.
When installing in vanilla images, "make" will be missing but is needed to perform the analysis (i.e. `nullarbor.pl --run` requires `make `to be present). …

[Nullarbor 2] Add "make" to the requirements

---

recipes/bcbio-nextgen/meta.yaml

The unversioned scipy installs a broken version 1.1.0 that is missing
openlibblas.
1. Fixes linting issues with the recipe.
2. Re-enables building on OSX, the code should work at least on OSX.
3. python 3+ is required now, so pin to that …

pin scipy to >= 1.3.0

---

recipes/fasta-splitter/build.sh
recipes/fasta-splitter/meta.yaml

Adds `meta.yaml` and `build.sh` files for `fasta-splitter` to build the latest version (0.2.6).

fasta-splitter update to version 0.2.6

---

recipes/trinity/build.sh
recipes/trinity/meta.yaml

since the path can contain an '@' character (galaxy) single quotes are necessary.
note that trinity actually ships with trimmomatic 0.36 in `opt/trinity-2.8.5/trinity-plugins/Trimmomatic/` and `/home/berntm/miniconda3/envs/__trinity@2.8.5/opt/trinity-2.8.5/trinity-plugins/Trimmomatic-0.36` each containing seemingly identical files `trimmomatic-0.36.jar`  `trimmomatic.jar` .. what a mess.
Currently the bioconda recipe requires trimmomatic>=0.36 (introduced here https://github.com/bioconda/bioconda-recipes/pull/10581) which installs 0.39 currently. 
I don't like this and would prefer to use trimmomatic as shipped with trinity or pin version 0.36. 
Would be good to know why the conda package has the requirement anyway. ping @abretaud 
supersedes …

trinity: change quoting in perl script

---

recipes/seurat-scripts/meta.yaml

Currently the mulled container for seurat-scripts produces plots with squares instead of letters. Based on https://github.com/conda-forge/r-base-feedstock/issues/91 this adds …

[seurat-scripts] Adds mscorefonts to avoid plots with no letters

---

build-fail-blacklist
recipes/perl-set-intervaltree/build.sh
recipes/perl-set-intervaltree/meta.yaml

Update to upstream Set-IntervalTree-0.12.
Listing the build compiler requirements fixes the build on macOS, so remove from the blacklist "OSX related errors" section.
ExtUtils::CppGuess is needed only when building Set::IntervalTree; at run-time all that is needed is the libcxx runtime.
----
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be …

Update perl-set-intervaltree and fix build requirements

---

recipes/ipyrad/meta.yaml

mpi4py>3.0 is only available for py37, and requires the conda-forge channel. Because it is not a hard dependency and to keep things simple I'll exclude it. Users can install it separate if they want to use it. …

Update meta.yaml to remove mpi4py

---

recipes/fastqsplitter/meta.yaml

Contributions were made to upstream xopen in order to improve the speed of reading gzipped files. This makes fastqsplitter run with significantly less overhead.

New build for fastqsplitter.

---

recipes/ega2/build.sh
recipes/ega2/ega2.py
recipes/ega2/meta.yaml

The European Genome/ Phenome archive seems to have two clients right now, the v3 (available via @AlexanderVi 's pyega3 recipe), and the v2, which is a less friendly .jar. The …

Add the EGA v2 client

---

recipes/bold-identification/meta.yaml

Add bold-identification: A tool for taxonomic assignment for given sequences

---

recipes/r-annotables/meta.yaml

Bumped version to (hopefully) trigger a build for R 3.6.
It's my understanding that this process should happen automatically, but it's been several weeks now and no such build has been generated, preventing this package from being used in an R 3.6 environment.

Bumped version for r-annotables to trigger build for R 3.6

---

recipes/mofapy/meta.yaml

Updated mofapy meta.yaml to indicate that python >= 2.7 is required (see project [setup.py](https://github.com/bioFAM/MOFA/blob/52c430356ba42a1abc8ab1338efbcc931c9d83a6/setup.py#L23)) and that argparse is only needed for python >2.7 and <3.2. Currently, the unconditional argparse requirement results in python <= 3.6 being requested, leading to many conflicts and unneccessary downgrades.

Updated python/argparse requirements for mofapy

---

recipes/vmatch/build.sh
recipes/vmatch/meta.yaml
recipes/vmatch/post-link.sh
recipes/vmatch/run_test.sh

Following discussion on gitter and conda public ML, we don't want to modify `LD_LIBRARY_PATH` to find plugins. Since the recipe already installs the plugins in …

Avoid manipulation of LD_LIBRARY_PATH in vmatch

---

recipes/jupyterngsplugin/meta.yaml

Adding jupyterpngsplugin python package to Bioconda

---

recipes/python-goenrichment/meta.yaml

Adding goenrichment python package

---

recipes/aquila/meta.yaml

* [v ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ v] This PR adds a new recipe.
* [ v] AFAIK, this recipe …

aquila first version

---

build-fail-blacklist
recipes/r-spieceasi/meta.yaml

Checklist:
@bioconda/core / @bioconda/r
I'd like to be added to bioconda project please!
I am the primary package developer/maintainer for this R package, though another user added this recipe.
This PR does two things:
1) updates the package to the latest version. This was waiting for a dependency to be added to conda-forge.
2) Fixes an erroneous title/description. The current documentation on bioconda refers to an entirely different package. I'm guessing a leftover from an old template.

fix and update r-spieceasi

---

recipes/minced/build.sh
recipes/minced/meta.yaml

For some reason it was being forced to be built with Java 11, but it can and should be built with Java 8 so it can run across a wider range of Java versions.  This will solve dep issues with `prokka` and `nullarbor`/`bohra` @kristyhoran

minced 0.4.0 - build with older java

---

recipes/cromshell/meta.yaml

The cromshell recipe was reporting a dependency on cromwell.  It doesn't actually require cromwell.  It does have an optioanl dependency on womtool though which is published alongside cromwell.
Changed dependency from cromwell -> womtool.

Fix cromshell dependency

---

recipes/pysamstats/meta.yaml

I am suddenly having problems installing latest pysamstats (1.1.2), getting conda conflicts for:
```
CHANNEL_OPTS="--override-channels --channel conda-forge --channel bioconda --channel defaults"
SOLVER_OPTS="--strict-channel-priority"
conda create --yes -v $SOLVER_OPTS $CHANNEL_OPTS --name foo pysamstats==1.1.2
```
...which gives:
```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed …
```

Rebuild pysamstats

---

recipes/bax2bam/build.sh
recipes/bax2bam/meta.yaml
recipes/blasr/build.sh
recipes/blasr/meta.yaml

pbbam: revdep rebuilds #2

---

recipes/kyototycoon/build.sh
recipes/kyototycoon/meta.yaml

Removing "-ansi" from compiler options also works around the noted compiler error involving stdlib.h, (and the previous workaround of copying the contents of a glibc's include directory to ${PREFIX}/include would have unintended side effects).
Setting / unsetting LD_LIBRARY_PATH in conda activate/deactivate scripts has unintended side effects (and is unexpected; no other bioconda recipe appears to do this); remove for safety.
* [ x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ x] This PR updates an existing recipe.

Build kyototycoon with fewer side effects

---

recipes/ariba/meta.yaml

Seeing the same problem as explained in issue https://github.com/bioconda/bioconda-recipes/issues/17212
```
ariba getref --help
File …
```

Update pysam pinning for Ariba

---

.circleci/setup.sh

We check that `.circleci` is up to date with master before executing the CI builds. Updating the branch is error prone, but @BiocondaBot can fix it. This mentions it in the …

Announce "@BiocondaBot update" from CI script

---

recipes/seroba/meta.yaml

This is related to Issue https://github.com/bioconda/bioconda-recipes/issues/17212. 
Using `conda install -c conda-forge -c bioconda seroba` would not pull the correct build of Ariba. Forcing pysam >0.15.3, corrects the problem. …

Add pysam pinning for Seroba

---

recipes/bactopia/meta.yaml

This is related to Issue https://github.com/bioconda/bioconda-recipes/issues/17212. 
Using `conda install -c conda-forge -c bioconda bactopia` would not pull the correct build of Ariba. Forcing pysam >0.15.3, corrects the problem. …

Add pysam pinning for Bactopia

---

recipes/jass/meta.yaml

JASS is a python-based tool for computing joint statistics on GWAS
summary data.
* [] This PR updates an existing recipe.

Add the JASS package v1.0.1

---

recipes/blast/build.sh
recipes/blast/meta.yaml

The current build of blast has been built with sse4.2.  This causes it to fail on our older nodes with Opteron processors.  The official blast binaries are build without sse4.2 and work fine on the older nodes.
I also removed a duplicate line from build.sh.
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be added to the bioconda project). …

Build blast without sse4.2

---

recipes/raxml-ng/build.sh
recipes/raxml-ng/meta.yaml

Fix https://github.com/bioconda/bioconda-recipes/issues/17606 . The executable was renamed from `raxml-ng-MPI` to `raxml-ng-mpi`, as that is what the upstream uses. Tested on 2 nodes of an HPC cluster that uses the SLURM workload manager using the https://github.com/amkozlov/ng-tutorial data set, launched with both the SLURM srun:
```
srun --mpi=pmix_v3 --ntasks=${SLURM_NTASKS} --cpus-per-task=${SLURM_CPUS_PER_TASK} raxml-ng-mpi --msa rbcl.phy --model GTR+G --prefix H1 --threads ${SLURM_CPUS_PER_TASK}
```
as well as the `mpiexec` bundled with the conda-installed openmpi package:
```
mpiexec -n ${SLURM_NTASKS} raxml-ng-mpi --msa rbcl.phy --model GTR+G --prefix H1 --threads ${SLURM_CPUS_PER_TASK}
```
In both cases, raxml-ng-mpi appeared to execute on both nodes:
```
Analysis options:
... …
```

Fix MPI build for raxml-ng

---

recipes/virsorter/build.sh
recipes/virsorter/meta.yaml

This fixes issues with the conda v4.7 solver pulling the old build of virsorter package due to the solver preferring older versions of bioperl. It adds the bioperl module paths to the environment during environment activation so the modules can be used.

Fix virsorter perl paths

---

recipes/biowdl-input-converter/meta.yaml

Biowdl-input-converter is directly relevant to the biological sciences beause:
- [BioWDL pipelines](https://github.com/biowdl) are bioinformatics pipelines written in WDL. They are free and open source and are built to be shared with the scientific community.
- biowdl-input-converter exists to convert formats that can be easily edited by researchers in spreadsheet programs to formats that can be read by cromwell to be used in BioWDL pipelines. As such it can also be used by other people who write bioinformatics pipelines in WDL.
- Due to the structure of the input and output formats, it makes no sense outside of bioinformatics.
@bioconda/core I hope this motivation is sufficient to accept this package in the bioconda channel. Thanks!

add biowdl-input-converter recipe

---

recipes/pirate/build.sh
recipes/pirate/meta.yaml

pirate 1.0.2

---

recipes/bracken/meta.yaml

Related to #17791. Remove `kraken` as a dependency of `bracken`, as it conflicts with `kraken2` during installation.

bracken: remove kraken1 dependency

---

recipes/ectyper/meta.yaml

* improved O-antigen serotyping coverage of complex samples that lack some O-antigen signatures. 
* fall back to single O-antigen signature detection when both signature pairs are not found and species is E.coli
* improved O-antigen identification favoring presence of both alleles (e.g. wzx and wzy) to support the final call. 
The sum of scores for both alleles of the same antigen is used in ranking now
* verification for E.albertii species against RefSeq genomes
* addition of Quality Control flags in the output (as an extra column in the `results.tsv`) for ease of results interpretation
* species reporting to better resolve E.coli vs Shigella vs E.albertii cases and contamination
* serotype prediction for all Escherichia genus to ease classification of cryptic spqeices
* automatic …

New recipe for ecTyper v0.9.0 with improved serotyping sensitivity

---

recipes/minimap2/meta.yaml

Briefly, [minimap2](https://github.com/lh3/minimap2) has a companion script called [paftools.js](https://github.com/lh3/minimap2/tree/master/misc) but the latest [BioContainer](https://quay.io/repository/biocontainers/minimap2) won't run it because it's missing the C++ standard library - please see https://github.com/lh3/minimap2/issues/492. This PR should fix that.

minimap2 - require libstdc++ for k8 paftools.js

---

recipes/genmap/build.sh
recipes/genmap/meta.yaml

Recipe was previous built with `-march=native` which lets genmap crash when executed on older processors.

GenMap: fixed recipe

---

recipes/scanpy-scripts/meta.yaml

Currently scanpy-scripts umap part fails as described in https://github.com/ebi-gene-expression-group/scanpy-scripts/issues/58. We have nailed it down to being h5py version …

Limit to hpy 2.9.0 as 2.10 breaks UMAP

---

recipes/scmap-cli/meta.yaml

For reading SingleCellLoomExperiment, SCMap requires bioconductor-loomexperiment as dependency. This aims to address …

Add LoomExperiment as dependency for SCMap

---

recipes/scanpy/meta.yaml

Match requirements from here: https://github.com/theislab/scanpy/blob/master/requirements.txt
It seems liek the requirements of scanpy haven't been updatet a long time. And currentyl matplotlib 3.1 and h5py 2.10.0 brake some functionality. @BiocondaBot

Update requirements to match scanpy 1.4.4.post1

---

recipes/trinity/meta.yaml

The Salmon 1.0.0 version which was just uploaded to anaconda.org can not be used by Trinity. Restricting to an older version until Trinity gets updated

Salmon 1.0.0 breaks Trinity

---

recipes/pb-assembly/meta.yaml

The fix is needed in order to have the most recent pb-falcon version
installed (> 0.3.0). Otherwise, a version where fc_ovl_filter does not
have the --min-idt and --ignore-indels options is installed (2.2.1-0).
This makes it impossible to use the newest configuration files for HiFi
reads.
Bioconda requires reviews prior to merging pull-requests (PRs). To facilitate this, once your PR is passing tests and ready to be merged, please add the `please review & merge` label so other members of the bioconda community can have a look at your PR and either make suggestions or merge it. Note that if you are not already a member of the bioconda project (meaning that you can't add this label), please ping `@bioconda/core` so that your PR can be reviewed and merged (please note if you'd like to be …

pb-assembly: fix version for pb-falcon dependency

---

recipes/scanpy-scripts/0.0.5/build.sh
recipes/scanpy-scripts/0.0.5/meta.yaml
recipes/scanpy-scripts/0.0.5/post-link.sh

Due to https://github.com/h5py/h5py/issues/1307, we need this updated recipe for a legacy build of scanpy-scripts (we use this specific build in some production processes), …

Add legacy recipe for scanpy-scripts to deal with h5py issue

---

recipes/ucsc-cell-browser/0.5.43/meta.yaml

This PR fixes an old (but relevant to us) version of UCSC CellBrowser to avoid the issues generated between anndata and h5py 2.10 recently released …

Fix UCSC-CellBrowser 0.5.43 issue with anndata and h5py 2.10

---

recipes/pb-assembly/meta.yaml

Most recent pb-falcon (2.2.1-0) version works with HiFi reads.
Error reported in commit
https://github.com/bioconda/bioconda-recipes/pull/18462
could be resolved.
* [X ] …

pb-assembly: restore pb-falcon version requirements

---

recipes/picard/meta.yaml
recipes/picard/picard.sh

* [ x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/contributor/guidelines.html).
* [ X ] This PR updates an existing recipe.
The memory …

[Picard] respect ${_JAVA_OPTIONS} and set default memory to 2GB

---

recipes/mob_suite/meta.yaml
recipes/mob_suite/post-link.sh

mob_suite depends on a database of plasmid sequences. These aren't installed automatically, but a utility script called `mob_init` is provided to download and install the …

mob_suite: Add post-link script to run mob_init

---

recipes/rasusa/build.sh
recipes/rasusa/meta.yaml

Closes https://github.com/mbhall88/rasusa/issues/9

Add recipe for rasusa

---

recipes/trinity/build.sh
recipes/trinity/meta.yaml

This will set the $TRINITY_HOME env variable when the Conda environment is activated and then unset that variable when deactivated.

Trinity -- export TRINITY_HOME ENV variable 

---

recipes/control-freec/meta.yaml

Control-FreeC needs samtools in order to read BAM-files.

add samtools to control-freec

---

recipes/augustus/meta.yaml

Without this:
```
$ bamToWig.py -g scaffolds.fa -b sortedByCoord.out.bam -o sortedByCoord.wig
Was unable to locate twoBitInfo on your system, will try to download it from …
```

Augustus script bamToWig.py needs USSC fatToTwoBit and twoBitInfo

---

recipes/tiddit/build.sh
recipes/tiddit/meta.yaml

Fix TIDDIT

---

build-fail-blacklist
recipes/antismash/build.sh
recipes/antismash/meta.yaml
recipes/antismash/post-link.sh
recipes/dx-cwl/meta.yaml
recipes/fastqmetrics/meta.yaml
recipes/maxentscan/meta.yaml
recipes/theta2/build.sh
recipes/theta2/meta.yaml

Blacklist update

---

build-fail-blacklist
recipes/prinseq/meta.yaml

was forgotten here https://github.com/bioconda/bioconda-recipes/pull/9784
* `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before …

prinseq: bump build

---

recipes/qualimap/meta.yaml

Without the fonts it fails (on minimal systems) with 
```
|  Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
|  at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
|  at java.base/java.security.AccessController.doPrivileged(Native Method)
|  at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
|  at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
|  at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
|  at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:856)
|  at org.jfree.text.G2TextMeasurer.getStringWidth(G2TextMeasurer.java:79)
|  at org.jfree.text.TextUtilities.nextLineBreak(TextUtilities.java:294)
| …
```

qualimap add fonts requirement

---

recipes/abyss/meta.yaml

Otherwise fails with:
```
|  /usr/local/bin/abyss-tabtomd: line 12: column: not found
|  make: *** [/usr/local/bin/abyss-pe.Makefile:938: abyss-stats.md] Error 127
|  make: *** Deleting file 'abyss-stats.md'
```
column comes with osx, so this is linux-only
* `@BiocondaBot please add label` will add the `please review …

abyss: Add util-linux for column command

---

recipes/quast/meta.yaml

Otherwise fails with
```
File "/usr/local/bin/quast", line 307, in <module>
return_code = main(sys.argv[1:])
File "/usr/local/bin/quast", line 149, in main
icarus_gc_fpath, circos_gc_fpath = basic_stats.do(ref_fpath, contigs_fpaths, os.path.join(output_dirpath, 'basic_stats'), output_dirpath)
File "/usr/local/opt/quast-5.0.2/quast_libs/basic_stats.py", line 263, in do
html_saver.save_contigs_lengths(results_dir, contigs_fpaths, corr_lists_of_lengths)
File "/usr/local/opt/quast-5.0.2/quast_libs/html_saver/html_saver.py", line 475, in save_contigs_lengths
append(results_dirpath, json_fpath, 'contigsLengths')
File "/usr/local/opt/quast-5.0.2/quast_libs/html_saver/html_saver.py", line 220, in append
init(html_fpath)
File …
```

Use extended base for quast

---

recipes/bandage/build.sh
recipes/bandage/meta.yaml
recipes/migmap/meta.yaml

Without these containerized startup fails / produces faulty svg files.
* `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before …

Add xorg-libxrender and fonts to Bandage

---

recipes/bedtools/build.sh
recipes/bedtools/meta.yaml

Update bedtools to 2.29.1 and remove cruft from the recipe:
* Remove <inttypes.h> patches as they have been unnecessary since bedtools 2.29.0.
* As the bedtools build process does not run HTSlib's configure script, HTSlib and hence bedtools are built without libdeflate and have no dependency on it.
Supersedes PR #19171.
----
* `@BiocondaBot please update` will cause the BiocondaBot to merge the master branch …

Update bedtools to 2.29.1 and tidy up recipe

---

recipes/phylocsf/meta.yaml

PhyloCSF requires libgsl.so.23, which is not available with the last version of gsl. 
I specified gsl version 2.5 to make sure this lib is available.
For some reason it doesn't build on osx anymore and the error is too complex for me to handle at the moment, so I disabled building for osx.

Specify gsl version

---

recipes/gtdbtk/meta.yaml
recipes/gtdbtk/post-link.sh

* `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging. …

Gtdbtk 1.0.2 updates

---

recipes/samtools/build.sh
recipes/samtools/meta.yaml

Bioconda's samtools 1.x package has not previously installed the legacy samtools headers and now is not the time to start. Moreover there is little point in installing the headers without also installing _libbam.a_.
Bioconda's legacy samtools 0.1.19 package does install the legacy samtools headers, into _$PREFIX/include/bam/*_ which is a more appropriate place than dropping generic filenames like _version.h_ into _$PREFIX/include_ as the samtools 1.10 package currently does.
So it would be appropriate to leave the legacy headers to the legacy package.
I believe PR #19275 was motivated by preparing the way for lofreq, but lofreq required samtools 1.1 so that PR was in fact superseded by PR #19304 so would ideally not have been merged. And in fact PR #19304 also proved unnecessary as there …

Revert PR #19275 -- don't install legacy samtools headers

---

recipes/moabs/meta.yaml
recipes/moabs/post-link.sh

* `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging. …

Update MOABS with build 1: fix post-link.sh

---

recipes/rnachipintegrator/meta.yaml

*This PR updates the recipe for RnaChipIntegrator to build the latest version (2.0.0), which includes support for Python 3.*
* `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. …

Update Rnachipintegrator recipe to 2.0.0

---

.circleci/config.yml

We are going to be removing support for Xcode 8.3.3 soon. This project is currently the biggest user of that image. Upgrading to the latest Xcode image will ensure that your build is stable for as long as possible.

Use newer macOS image on CircleCI

---

recipes/centrifuge/meta.yaml

Needs to compile with wget. This is causing issues when using Biocontainer quay.io/biocontainers/centrifuge:1.0.4_beta--he860b03_3
* `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI …

Add wget to Centrifuge

---

recipes/biotdg/meta.yaml

Bionformatics Test Data Generator
This tool was made to generate test data transparently for genomes with mixed ploidies. (For example human male genome). 
NOTE: setuptools **is** needed as a runtime dependency. It is used to determine the version when using the `--version` flag.
----
>
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use …

add biotdg: bioinformatics test data generator.

---

recipes/mummer4/0001-sort-mgaps-file-before-postpro.-on-behalf-of-jervied.patch
recipes/mummer4/meta.yaml

mummer4: added a patch that fixes promer .  One component of mummer4 has a bug that stops it from working.   A patch has been submitted ( https://github.com/mummer4/mummer/pull/94 ) but is not yet merged.  This patch changes only the promer script and does not affect any other parts of mummer4.
---- …

mummer4: added a patch that fixes promer

---

recipes/macrel/build.sh
recipes/macrel/meta.yaml

Adds macrel
It's a pretty standard Python package, except that we also ship a modified version of `prodigal`, which is installed as `prodigal_sm`
More information:
http://big-data-biology.org/software/macrel
https://www.biorxiv.org/content/10.1101/2019.12.17.880385v1
(which uses the old name of the tool, FACS; we'll update asap)
----

Add macrel at v0.2

---

recipes/tinyalign/meta.yaml

This adds a recipe for the Python "tinyalign" package (of which I am the author).
----
>
>  * `@BiocondaBot please fetch …

Add tinyalign recipe

---

recipes/scalpel/build.sh
recipes/scalpel/meta.yaml

Microassembler was not correctly building due to not finding bamtools
include files and libaries. Adjust to BUILD_PREFIX reference to enable.
Fixes bioconda/bioconda-recipes#19844

scalpel: fix build for Microassembler

---

recipes/gimmemotifs/meta.yaml

Upstream conda-forge deps should now support 3.7 and 3.8.
----

gimmemotifs removed 3.6 restriction

---

recipes/ltr_retriever/build.sh
recipes/ltr_retriever/meta.yaml

**Replace this sentence with a detailed description of your pull request**
----
>
>  * `@BiocondaBot please fetch …

Ltr retriever 

---

recipes/kaiju/build.sh
recipes/kaiju/meta.yaml

`kaiju-excluded-accessions.txt` was added in the newest release. Without it, `kaiju-makedb` crashes for me on the latest version (1.7.3).
```
$ kaiju-makedb -t 8 -s rvdb
Error: File kaiju-excluded-accessions.txt not found in <condaenv>/bin
```
It is available next to the executables. Is it ok to place it in the bin dir? The same thing is done for the `kaiju-taxonlistEuk.tsv`. The location is hard coded.
@pmenzel Just tagged you to notify you of this proposed change.
----

Added a missing file for Kaiju

---

build-fail-blacklist
recipes/ntcard/meta.yaml

Update ntCard to version 1.2.0
----
>
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker …

update ntCard to 1.2.0

---

recipes/macrel/meta.yaml

New version uses scikit-learn instead of r-randomForest, so update to
that.
>
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers built by the CI system. You can use this to test packages locally before merging.
>
> For members of the Bioconda project, the following command is also available:
>

Add scikit-learn dependency to macrel

---

recipes/sourmash/meta.yaml

Bump sourmash to 3.2.0 and add bam2fasta dependency
(is `autobump` not working?)

Bump sourmash to 3.2.0 and add bam2fasta dependency

---

recipes/scater-scripts/meta.yaml

This PR just removes the R pinning for the scater-scripts package. I believe that's a hangover from legacy practices and is giving us conflict issues.
----
>
>  * `@BiocondaBot please add label` will …

Remove R pinning for scater-scripts

---

recipes/orthofinder/build.sh
recipes/orthofinder/meta.yaml

The OrthoFinder recipe copied a directory of binaries that OrthoFinder used. This is unnecessary since the bioconda recipes should be used to install dependencies instead. I've updated the recipe so as not to copy this directory. I've also updated the diamond requirement to <=0.9.24 as there is an outstanding issue after this release that is causing a crash for many mac users. I will monitor the situation with this issue and remove the version requirement once it's no longer needed.
https://github.com/bbuchfink/diamond/issues/303
https://github.com/davidemms/OrthoFinder/issues/328
Thanks
David

Orthofinder dev

---

recipes/braker2/meta.yaml

BRAKER 2.1.4 [requires Augustus >= 3.3.3](https://github.com/Gaius-Augustus/BRAKER/issues/22#issuecomment-531294856), and supports DIAMOND as an alternative to NCBI BLAST+.
genomethreader is now available in bioconda, and it seems the license [should no longer be an issue](https://github.com/genometools/genomethreader/blob/bfc6a051a8d06451e028af2f1dec58c88296c96f/CHANGELOG#L19)?
----

Update dependencies for braker2

---

recipes/sambamba/meta.yaml

**Note**: This will currently fail because LDC 1.17.0 isn’t available on conda-forge.
Sambamba crashes with
```
Symbol not found: _dyld_enumerate_tlv_storage
```
This is filed as [D bug 20019](https://issues.dlang.org/show_bug.cgi?id=20019) and has been [fixed in D 2.087.1](https://dlang.org/changelog/2.087.1.html).
This PR simply bumps the required LDC version to LDC 1.17.0, which is the first version to [include that fixed version](https://github.com/ldc-developers/ldc/blob/master/CHANGELOG.md#ldc-1170-2019-08-25).
The most recent Sambamba version 0.7.1 has been built with LDC 1.13, according to the [CI logs](https://app.circleci.com/jobs/github/bioconda/bioconda-recipes/84656).
* dlang PR:  dlang/druntime#2666
* sambamba bug report: biod/sambamba#424

Attempt to fix sambamba crash on macOS Catalina

---

recipes/hyphy/build.sh
recipes/hyphy/meta.yaml

Although this disables AVX, I believe it also disables FMA, which is new enough that some commonly deployed CPUs do not support it.
----
>
>  * `@BiocondaBot please add label` will add the `please …

Update HyPhy to 2.5.3 and disable AVX extensions

---

recipes/riboseqc/build.sh
recipes/riboseqc/meta.yaml

Previously had wrong directory name in build.sh - would possibly have interfered with another package 'here'
----
>
>  * …

fix that stops buil.sh overwriting another directory

---

recipes/berokka/meta.yaml

Perl and Bioperl seem to mistmatched:
```
berokka -h
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /scratch/punim0401/miniconda3/envs/berokka_env/lib/site_perl/5.26.2/x86_64-linux-thread-multi /scratch/punim0401/miniconda3/envs/berokka_env/lib/site_perl/5.26.2 /scratch/punim0401/miniconda3/envs/berokka_env/lib/5.26.2/x86_64-linux-thread-multi /scratch/punim0401/miniconda3/envs/berokka_env/lib/5.26.2 .) at /scratch/punim0401/miniconda3/envs/berokka_env/bin/berokka line 4.
```

berokka - fix broken bioperl vs perl

---

recipes/r-txrevise/meta.yaml

Signed-off-by: Vivek Rai <mail@raivivek.in>
**Replace this sentence with a detailed description of your pull request**
----
>
>  * `@BiocondaBot please add label` will add the `please review & merge` …

Add r-txrevise

---

recipes/spoa/build.sh
recipes/spoa/meta.yaml

I have updated the build for Spoa as some users have problems running the executable on their machines. The cause is the `-march=native` compiler flag which will be replaced with `-msse4.1` if cmake is run with flag `-Dspoa_optimize_for_portability=ON`. This flag is present from version `v3.0.2` which was released moments ago.
----
> Everyone has access to the following BiocondaBot commands, …

[spoa] update build

---

recipes/sourmash/meta.yaml

There is a bug in `cffi` which affects [sourmash](https://github.com/dib-lab/sourmash/pull/911), but it is fixed in `cffi == 1.14.0`.
----

fix cffi dep version for sourmash

---

recipes/racon/build.sh
recipes/racon/meta.yaml

I have updated the build for Racon as some users have problems running the executable on their machines. The cause is the `-march=native` compiler flag which will be replaced with -msse4.1 if cmake is run with flag `-Dspoa_optimize_for_portability=ON`. This flag is present from version `v1.4.11` which was released moments ago.

[racon] Update build and bump version

---

recipes/biolib/meta.yaml

From biolib 0.1.0 python 3.6 is required.
Previous versions of biolib which exist will be affected by this, possibly affecting the dependencies of other packages. Is there a way to retroactively correct this?
----
>
>  * `@BiocondaBot please update` will cause the BiocondaBot to merge the master …

Update biolib - fix python version

---

recipes/racon/meta.yaml

Trying to fix build problems some users are experiencing with the executable. Found a lost `-march=native` compiler flag in one of my submodules and removed it.

[Racon] version bump

---

recipes/mummer/build.sh
recipes/mummer/meta.yaml

Compiling mummer for 64bit support.
This is necessary to use with mummer2circos for large genome sizes
----
>
>  * …

compiling with x64bit support for large genome sizes

---

recipes/itolapi/meta.yaml

itolapi new recipes
----
>
>  * `@BiocondaBot please fetch artifacts` will post links to packages and docker containers …

add new recipes for itolapi

---

recipes/deepvariant/meta.yaml

Fix auto-update of deepvariant to match latest pinnings in new release (py36, numpy 1.16, tensorflow 2.0.0)

deepvariant: 0.10.0 requires p36, adjust pinnings

---

recipes/deepvariant/build.sh
recipes/deepvariant/dv_make_examples.py
recipes/deepvariant/dv_postprocess_variants.py
recipes/deepvariant/meta.yaml

Additional fixes for deepvariant with py36:
- Correctly fix hardcoded references to python3.6 in zip files
- Escape environmental variables in scripts

deepvariant: additional py36 fixes; point to anaconda python

---

recipes/deepvariant/build.sh
recipes/deepvariant/meta.yaml
recipes/deepvariant/post-link.sh

Hopefully last deepvariant revision bump after additional debugging work
- Fixes deepvariant issue with zipfile synlink references causing:
```
TypeError: allele_count_linear_candidates_from_allele_counter() argument counter is
not valid for ::learning::genomics::deepvariant::AlleleCounter
(deepvariant.python.allelecounter.AlleleCounter instance given):
expecting deepvariant.python.allelecounter.AlleleCounter instance, got
deepvariant.python.allelecounter.AlleleCounter instance
```
By adding `--symlinks` when recreating zipfile, thanks to reading
through deepvariant build patch (https://github.com/google/deepvariant/issues/199#issuecomment-570115804)
Fixes bcbio/bcbio-nextgen#3048
- Includes missing dependencies in new version: altair and absl.
Includes custom Google tf-slim which …

deepvariant: update 0.10.0: fix zipfile issue, finalize deps

---

recipes/anvio-minimal/meta.yaml

This is a followup PR to #21241 and corrects the version numbers for `cherrypy` and `snakemake-minimal`.
Thank you.

Update anvio 6.2 recipe to set critical version numbers

---

recipes/anvio/meta.yaml

This is an update to the anvi'o meta package (anvi'o minimal recipe for 6.2 has been recently pushed, and is already merged and the package is available through bioconda).

Update anvi'o meta package to 6.2

---

recipes/nanopolish/build.sh
recipes/nanopolish/meta.yaml

Fix the nanopolish build on macOS.
Fast5 uses `static_assert`, which is from C++11 — which is later than the default language standard on conda's macOS compiler. Explicitly pass `$CXXFLAGS` down, as it includes `-std=c++14` and so makes `static_assert` available.
---- …

nanopolish: fix macOS build

---

recipes/luciphor2/meta.yaml

bump luciphor to 2.1

---

recipes/vg/meta.yaml

add vg as a binary release

---

recipes/snakemake/meta.yaml

This PR sets the pygraphviz requirement to version 1.5 as snakemake may be installed with an older version of pygraphviz. This results in an error when creating a snakemake report.

Updated snakemake

---

build-fail-blacklist
recipes/andi/build.sh
recipes/andi/meta.yaml

update andi to 0.13
----
<details> …

update andi to 0.13

---

recipes/graphtyper/meta.yaml

Updates graphtyper to version 2.3. Removes lz4 and zstd dependencies as they are no longer used. Replaces 'call' with 'genotype' in test commands because call is no longer used.

Update graphtyper to 2.3

---

recipes/watchdog-wms/build.sh
recipes/watchdog-wms/meta.yaml

Javafx JAR files are causing an error when the GUI is started. However, the GUI starts anyway using SWT instead of ES2. 
The change of the build script uses the javafx libraries that are installed via conda.
> Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: /root/.openjfx/cache/11.0.2/libprism_es2.so: libGL.so.1: cannot open shared object file: No such file or directory
java.lang.UnsatisfiedLinkError: /root/.openjfx/cache/11.0.2/libprism_es2.so: libGL.so.1: cannot open shared object file: No such file or directory
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
at …

[Update] watchdog-wms - let conda handle javafx

---

recipes/ptrimmer/build.sh
recipes/ptrimmer/meta.yaml

This PR adds the recipe for pTrimmer.
As there is no Github Release available for pTrimmer the hash of the latest commit is used for building.

Add pTrimmer

---

recipes/gemoma/GeMoMa.py
recipes/gemoma/build.sh
recipes/gemoma/meta.yaml

Adds a recipe for GeMoMa, a homology-based gene prediction program that exploits intron position conservation and allows to used RNA-seq data. The software has been described and published in scientific literature, e.g., 
https://nar.oxfordjournals.org/content/44/9/e89
https://rdcu.be/QbKc
----
<code>@BiocondaBot please update</code>

Add GeMoMa recipe

---

recipes/bio-ting/meta.yaml

This PR adds a new recipe for [ting](http://github.com/FelixMoelder/ting) a tool for clustering antigen-specific T cell receptor repertoires.
A corresponding preprint has been published on [bioRxiv](https://www.biorxiv.org/content/10.1101/2020.05.04.069914v1) while the final manuscript is about to be submitted to peer-reviewing journal.

Add recipe for bio-ting

---

recipes/genmap/meta.yaml

Replaced ``llvm-openmp`` with ``openmp``, since it seems to cause problems on osx (UnsatisfiableError), see https://github.com/cpockrandt/genmap/issues/17
---- …

Update to fix conflicts on osx of GenMap 1.2.0

---

recipes/stringtie/1.3.3b/build.sh
recipes/stringtie/1.3.3b/meta.yaml

Adding a previous version of stringtie (1.3.3b) that I need to use to reproduce a previous analysis.  Related to https://github.com/bioconda/bioconda-recipes/issues/21982
I copied the `1.3.3` directory, modified the URL and SHA256 checksum.  That's it!

Add stringtie version 1.3.3b

---

recipes/jalview/jalview.sh
recipes/jalview/meta.yaml

Updates Jalview build to 2.11.1.0 release (2020-04-22), refined jalview summary/description and improved logic for detecting installed java version at launch time.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
For members of the Bioconda project, the …

Update bioconda/jalview to 2.11.1.0

---

recipes/pbmm2/meta.yaml

Build against latest pbbam and thus against latest htslib
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr>
<td>Upload built …

Update PacBio `pbmm2` to use new htslib 1.10

---

recipes/pyseer/meta.yaml

Manual update of the pyseer recipe, as it is not present in pypi any longer, but available as a tarball in github releases. The recipe is otherwise the same.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
For members of the Bioconda project, the following …

Update pyseer to 1.3.6

---

recipes/checkv/meta.yaml

Pytest was removed from CheckV's dependencies.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr>
<td>Upload built …

Remove pytest from CheckV's dependencies

---

recipes/scirpy/meta.yaml

the latest version of scirpy requires the latest version of scanpy.

Update scirpy (update dependencies upon version bump) 

---

recipes/stringmeup/meta.yaml

Adding StringMeUp, a tool for kraken2 post-filtering. 
----
<details> …

Add StringMeUp

---

build-fail-blacklist
recipes/plastid/meta.yaml

Update plastid to version 0.5.1
----
<details> …

Update plastid to 0.5.1

---

recipes/ectyper/meta.yaml

Update to a current E.coli serotyping tool as auto-update by bot failed. Cancel the other PR #22323.

update ectyper 1.0.0

---

recipes/gmap/meta.yaml

Latest gmap release, which includes a number of clinically relevant bug fixes. This will resolve #22456

Update gmap to version 2020-06-01

---

recipes/parsnp/build.sh
recipes/parsnp/meta.yaml
recipes/parsnp/run_test.sh

Updating Parsnp. For some reason, I'm unable to get the Muscle library to build using the `-fopenmp` flag on OSX even when using the `llvm-openmp` dependency...
For now, the parsnp build will only work serially
----
* Please …

Update Parsnp 1.5.0

---

recipes/krona/build.sh
recipes/krona/meta.yaml

The "._" files (https://apple.stackexchange.com/q/14980) get integrated into the metadata fields of the file system and are then removed. This makes the verification fail on macOS. 
See https://github.com/marbl/Krona/issues/141
````
$ tar tf KronaTools-2.7.1.tar | grep "\\._"
KronaTools-2.7.1/._updateTaxonomy.sh
KronaTools-2.7.1/lib/._KronaTools.pm
KronaTools-2.7.1/scripts/._accession2taxid.make
````
This is only a problem for Conda, not manual installation. Therefore, I would remove them here. It seemed weird to me to hardcode those three files, this is the reason for the find command.
It may be argued that they should not be in the release file at all. But again, it only affects Conda and could happen again in the future with other files.
----
<details> …

Update Krona recipe to fix macOS installation

---

recipes/genometreetk/meta.yaml

Added `hmmer` and `fasttree` to `genometreetk`'s dependencies. These are necessary for running the program and were not included in the recipe.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …

Update genometreetk dependencies

---

recipes/lofreq/build.sh
recipes/lofreq/meta.yaml

PR #22634 changed _build.sh_'s `--with-htslib` option to `--with-htslib=${PREFIX}/lib` without any explanation. This setting is incorrect as giving the _lib_ subdirectory does not supply the header files, so the build succeeded only because it implicitly fell back to use the build-env's system HTSlib from $CPPFLAGS/$LDFLAGS.
As requested on PR #22693, this reverts the recipe to use `--with-htslib=system` to explicitly use only the HTSlib already installed in the build-env:
> --with-htslib=system
> Ignores any nearby HTSlib source trees, and builds [the program] using an existing HTSlib installation in a system directory (i.e., a directory already being searched by $CPPFLAGS/$LDFLAGS).

Tidy up lofreq recipe

---

recipes/bioconductor-org.hs.eg.db/meta.yaml
recipes/bioconductor-org.hs.eg.db/post-link.sh

Update of bioconductor-org.Hs.eg.db to v3.11.4 to fix broken links of the recipe for the package version 3.11.1 which is currently out there. The update is related to issue #22806 and resolves one of the two mentioned broken packages.

Update of bioconductor-org.Hs.eg.db to v3.11.4 from v3.11.1

---

recipes/bioconductor-org.mm.eg.db/meta.yaml
recipes/bioconductor-org.mm.eg.db/post-link.sh

Update of bioconductor-org.mm.eg.db to v3.11.4 to fix broken links of the recipe for the package version 3.11.1 which is currently out there. The update is related to issue #22806 and resolves the second of the two broken packages mentioned in that issue.

Update of bioconductor-org.mm.eg.db from version 3.11.1 to version 3.11.4 to fix broken links

---

recipes/pyrodigal/meta.yaml

This PR adds `pyrodigal`, a package containing Python bindings to the Prodigal ORF finder. (This is not the same as the `prodigal` recipe, which installs Prodigal as a binary).
---- …

Add recipe for `pyrodigal` Python package

---

recipes/sra-tools/meta.yaml

Fixes gh-22929.
This is my first contribution to bioconda.
I just increased the build number of the sra-tools recipe to trigger a rebuild of sra-tools, to use an updated hdf5 1.10.6 dependency
Otherwise:
- `conda create -n myenv sra-tools hdf5=1.10.6` installs `sra-tools 2.8.0` (old version that does not depend on hdf5)
- `conda install sra-tools` on an environment with `hdf5=1.10.6` also installs `sra-tools 2.8.0` to prevent the downgrade.
- `conda install sra-tools=2.10.7` will downgrade hdf5 from 1.10.6 to 1.10.5.
So the main reason for this rebuild is to facilitate the installation of the *latest* version of sra-tools.
Feel free to close this PR, if you believe it does not make sense to trigger a sra-tools rebuild for this reason.

Update sra-tools (add missing curl dependency, rebuild hdf5)

---

recipes/sra-tools/meta.yaml

I'm encountering a few of the errors fixed by 2.10.8 in my pipeline so I'd like to (try to) update the bioconda package to latest.

Update sra-tools to 2.10.8

---

recipes/stacks/kmer_exit.patch
recipes/stacks/meta.yaml

when using the options
--write-k-freq: write kmers along with their frequency of occurrence and exit.
--k-dist: print k-mer frequency distribution and exit.
issue has been reported here: https://groups.google.com/forum/#!topic/stacks-users/fS3iJOYz6-s
seems much easier to me to introduce a patch here instead of dealing with the nonsense exit code.
---- …

stacks kmer_filter returns wrong exit code

---

recipes/cellsnp-lite/LICENSE
recipes/cellsnp-lite/build.sh
recipes/cellsnp-lite/meta.yaml

cellsnp-lite is a tool aimed to pileup biallelic SNPs from single-cell and bulk RNA-seq data. I have read the guidelines, please add this recipe, thank you.

Add new recipe for cellsnp-lite

---

recipes/bwa-mem2/find_executable.patch
recipes/bwa-mem2/meta.yaml

On older processor architectures bwa-mem2 isn't able to select the correct executable. Instead it will throw an error.
The bwa-mem2.sse4 program should work on most processors. Nevertheless Intel Sandy Bridge and Ivy Bridge processors, and some older pre-ryzen AMD processors are not able to run bwa-mem as a result.
This issue was raised: https://github.com/bwa-mem2/bwa-mem2/issues/73
This patch was proposed: https://github.com/bwa-mem2/bwa-mem2/pull/82
The changes are in this commit: https://github.com/bwa-mem2/bwa-mem2/commit/d5df37af4b6fc36120a58bb32681a2fe58f97b0f
This fix will not effect the output SAM file in any way. So this can be safely merged.
----
Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a pull …

Patch bwa-mem2 find executable

---

recipes/ncfp/meta.yaml

This PR should update the ncfp package from version 0.1.1 to 0.2.0.
- [PyPI ncfp](https://pypi.org/project/ncfp/)
- [GitHub ncfp](https://github.com/widdowquinn/ncfp)

update meta.yaml for ncfp v0.2.0 (PyPI)

---

recipes/pileuppy/meta.yaml

Update [`pileuppy`](https://bioconda.github.io/recipes/pileuppy/README.html): **1.0.0** → **1.0.1**
There was an automatic pull request [here](https://github.com/bioconda/bioconda-recipes/pull/23328), but it seems like the tests fail because of the network error.

Update pileuppy to 1.0.1

---

recipes/gmap/meta.yaml

Latest gmap release, which includes a number of clinically relevant bug fixes. See  http://research-pub.gene.com/gmap/ for details. This resolves issue #23395.

Update gmap to version 2020-06-30

---

recipes/f5c/build.sh
recipes/f5c/conda_build_config.yaml
recipes/f5c/meta.yaml

Add recipe for f5c
----
f5c is an optimised re-implementation of the call-methylation and eventalign modules in Nanopolish. Given a set of basecalled Nanopore reads and the raw signals, f5c call-methylation detects the methylated cytosine and f5c eventalign aligns raw nanopore DNA signals (events) to the base-called read.

Add recipe for f5c

---

recipes/augur/meta.yaml

Updates recipe to reflect recent changes in augur's dependencies including a minimum Python version of 3.6 and support for pandas 1.0.0.
This PR also:
- removes packages that are not true dependencies for augur including seaborn and matplotlib
- bumps augur build number
- specifies augur license file
- adds a recipe maintainer

Update augur 9.0.0 dependencies

---

recipes/bioconductor-diffbind/meta.yaml

Deseq2 includes the function: lfcShrink which dependes on bioconductor-apeglm
Check: https://rdrr.io/bioc/DESeq2/man/lfcShrink.html
I'm adding this package as a requirement for Deseq2 that is used by Diffbind

Adding bioconductor-apeglm as dependency to diffbind

---

recipes/bioconductor-diffbind/meta.yaml

Diffbind needs:
* bioconductor-apeglm
* xorg-libxt
This error is shown when plotting DiffBind graphs:
```
In grSoftVersion() :
unable to load shared object '/usr/local/lib/R/modules//R_X11.so':
libXt.so.6: cannot open shared object file: No such file or directory
```

Adding dependencies to diffbind

---

recipes/bioconductor-diffbind/meta.yaml

There are missing fonts while using this package.
It get's solved if adding: fonts-conda-ecosystem
See:
* https://github.com/conda-forge/r-base-feedstock/issues/91
* https://github.com/sigven/pcgr/issues/107

Adding fonts-conda-ecosystem to diffbind to solve missing fonts

---

recipes/ariba/meta.yaml
recipes/ariba/pubmlst_getter.patch
recipes/ariba/ref_genes_getter.patch

This PR includes two patches for Ariba related to changes in API endpoints.
`pubmlst_getter.patch` fixes broken PubMLST downloads due to a change in API endpoint.
Original Issue: https://github.com/sanger-pathogens/ariba/issues/304
Submitted Ariba PR: https://github.com/sanger-pathogens/ariba/pull/305
`ref_genes_getter.patch` fixes a change in CARD links that causes RGI to be downloading instead of CARD
Original Issue: https://github.com/sanger-pathogens/ariba/issues/301
Submitted Ariba PR: https://github.com/sanger-pathogens/ariba/pull/303
This my first time submitting a PR with patches so any advice would be appreaciated. I generated the patches through GitHub by appending `.patch` to the PR link.
https://github.com/sanger-pathogens/ariba/pull/303.patch …

Update - Patches for third party links used by Ariba

---

recipes/homer/build.sh
recipes/homer/meta.yaml

For using homer with a standard installation path `/usr/local/share/homer` as a link to the current installation path.
This help external scripts to use the standard path for installing genomes and databases.

Adding standard link to the homer installation folder

---

recipes/instrain/meta.yaml

This PR adds `numba` and `lmfit` as requirements to the inStrain recipe. It also adds two test commands on top of the existing import test.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …

Fix inStrain requirements and add test commands

---

recipes/ragtag/meta.yaml

RagTag requires either minimap2 or nucmer (mummer) for sequence alignment, as [described in the README.md](https://github.com/malonge/RagTag#dependencies).

Update RagTag recipe to add missing dependencies minimap2 and mummer

---

recipes/tiddit/build.sh
recipes/tiddit/meta.yaml

Executing TIDDIT resulted in the following error:
TIDDIT: error while loading shared libraries: libbamtools.so.2.3.0: cannot open shared object file: No such file or directory
Caused by copying the bamutils source directory instead of the built
library files.  Added a test that executes the TIDDIT binary itself,
to catch issues such as these.

TIDDIT: fix TIDDIT executable.

---

recipes/hmftools-sage/meta.yaml

In the biocontainer this libxt  was missing, which caused the Rscripts run by sage to fail on a segfault. Adding this xorg-libxt package should fix that.
---- …

Update hmftools-sage: Add xorg-libxt as dependency of hmftools-sage

---

recipes/treesapp/meta.yaml

TreeSAPP no longer uses the original RAxML software. It now uses EPA-NG and RAxML-NG for phylogenetic placement and inference, respectively. It also needs a newer version of pyfastx. 
---- …

Update old dependencies with new ones

---

recipes/hmftools-purple/PURPLE.sh
recipes/hmftools-purple/meta.yaml

Adding R package dependencies for plotting functionality in PURPLE.
Also including circos and allowing recognition of `com.*` packages on the command line.
---- …

Update hmftools-purple: add R package dependencies + circos

---

build-fail-blacklist
recipes/ngless/build.sh
recipes/ngless/meta.yaml

Update NGLess recipe
For Linux, fixes `build.sh` to run on newer conda.
For Mac OS X, installs the prebuilt binaries (as the approach used on Linux seems to fail with some OSX-internal errors).
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
For members of the …

Ngless v1.2.0 macosx build

---

recipes/trf/build.sh
recipes/trf/meta.yaml

Update trf to version 4.09.1. This is the first open-source version available.

Update trf to version 4.09.1

---

recipes/entrez-direct/meta.yaml

EDirect 13.9 is now public, with the following release notes:
`xtract -fasta` splits long sequences into groups of 50 letters.
`xtract -select` restores -in to indicate name of identifier file.
Redesigned EDirect selected by running `export USE_NEW_EDIRECT=true` to set environment variable.
New implementation also chosen by adding `-newmode` as the first argument to individual efetch, efilter, einfo, elink, epost, esearch, esummary, and nquire commands.
The EDirect reimplementation is still activated by running:
export USE_NEW_EDIRECT=true
It is version 14.0, and will become the default sometime later this year.
In addition to the release notes, the curl call in nquire uses the "--connect-timeout 20" flag. This eliminates the 300 second maximum data transfer limit, but doesn't hang …

Updated entrez-direct to version 13.9, please merge

---

recipes/pbipa/meta.yaml

Pull falconc from `pb-falconc` instead of `nim-falcon`, so we can revert the latter and fix older falcon.

Update reqs for pbipa

---

recipes/nim-falcon/meta.yaml

Most of this has moved to a different package (pb-falconc). This one is reverted here so old (pb-assembly) will continue to run.

revert nim-falcon

---

recipes/nim-falcon/meta.yaml

from 570776f10cd8f3c00869a50c9f68b83c6c3ef4d0
We want to move this soon. But for now, we are only trying to recover what existed before, used in the pb-assembly package. (pbipa now uses pb-falconc instead.)

Update nim-falcon (revert to 0.0.1)

---

recipes/perbase/build.sh
recipes/perbase/meta.yaml

This PR adds the tool `perbase` to bioconda. `perbase` is the initial release of a tool for per-base metrics generation. Currently it supports per-base depth with per-nucleotide resolution as well as per-base Ins/Del counts. 
I think I've followed all guidelines, please let me know if something is missing!

Add perbase tool

---

recipes/braker2/meta.yaml

braker2 is missing (non-core) Perl dependency List::MoreUtils, which is [used in braker.pl](https://github.com/Gaius-Augustus/BRAKER/blob/v2.1.5/scripts/braker.pl#L33) :
```
$ conda create -c conda-forge -c bioconda -n braker2 braker2
...
$ source activate braker2
(braker2) $ braker.pl
Can't locate List/MoreUtils.pm in @INC (you may need to install the List::MoreUtils module) (@INC contains: /home/user/.conda/envs/braker2/bin/. /home/user/.conda/envs/braker2/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/.conda/envs/braker2/lib/site_perl/5.26.2 /home/user/.conda/envs/braker2/lib/5.26.2/x86_64-linux-thread-multi /home/user/.conda/envs/braker2/lib/5.26.2 .) at /home/user/.conda/envs/braker2/bin/braker.pl line 33.
BEGIN failed--compilation aborted at …
```

Update braker2: add dependency perl-list-moreutils

---

recipes/drop/meta.yaml

New `wbuild 1.7.1` is incompatible with `drop`. Constrained to `wbuild=1.7.0` in recipe.
This should overwrite the [autobump PR](https://github.com/bioconda/bioconda-recipes/pull/24540).
Info | Link
-- | --
Recipe | recipes/drop (click to view/edit other files)
Releases | https://github.com/gagneurlab/drop/tags
Recipe Maintainer(s) | @c-mertes, @mumichae
Author | @gagneurlab

Update drop 0.9.2

---

recipes/deepbgc/meta.yaml

Require Biopython <= 1.76 for DeepBGC recipe

Update DeepBGC: Require Biopython <= 1.76

---

recipes/pairtools/meta.yaml

Updating the meta.yaml file to point the recipe to the new URL with the updated owner.

Update pairtools recipe because its repo changed the owner.

---

recipes/cryptogenotyper/meta.yaml

First tool release on Cryptosporidium species identification. This tools helps to quickly identify this parasite and resolve chromatogram from Sanger sequencing available from [https://github.com/phac-nml/CryptoGenotyper](https://github.com/phac-nml/CryptoGenotyper)

CryptoGenotyper v1.0  bioconda release

---

recipes/drop/meta.yaml

DROP 1.0.0 fails, as it requires features from wbuild 1.7.1

update wbuild version

---

recipes/maf2synteny/Makefile.patch
recipes/maf2synteny/build.sh
recipes/maf2synteny/meta.yaml

Add maf2synteny, a synteny block generator from MAF multiple whole-genome alignments. Project URL: https://github.com/fenderglass/maf2synteny.

Add maf2synteny recipe

---

recipes/ganon/meta.yaml

ganon version 0.3.3 requires `python >= 3.4`. However, I noticed that the conda package requires `python >=3.9 `. Is this an expected behavior? It really limits the installation of other packages in the same environment.
I am trying to change the way to define the python version but any advice on best practices is welcome.
----
* PRs require reviews prior to being merged. Once your …

Fix python version of ganon 0.3.3

---

recipes/gatk/3.6/build.sh
recipes/gatk/3.6/meta.yaml
recipes/gatk/build.sh
recipes/gatk/meta.yaml

**Note:** (Exciting news following some conversation internally) The Broad Institute Office of Strategic Alliances and Partnering has given the green light for public (re)distribution of GATK3, in line with how GATK4 will be licensed and distributed. This commit causes the `GenomeAnalysisTK.jar` file to be included in the conda package, sourced from the now-unauthenticated URL for GATK. Minor annoyance: While older GATK versions can be accessed via URLs that include the version number, it seems the latest version can only be pulled from a URL that omits the version.

add GATK jar file

---

recipes/htslib/meta.yaml
recipes/htslib/plugin-fixes.patch

Changes between HTSlib 1.10 and 1.11 have led to samtools/htslib#1176, preventing programs using bioconda's htslib from accessing files remotely over HTTPS, S3, etc. This problem will be fixed in upstream HTSlib in due course; this PR applies patches to fix the bioconda package in the meantime:
* Apply samtools/htslib#1150 to fix some externally-supplied plugins such as iRODS access;
* Revert part of samtools/htslib#1072 to fix the main HTTPS/S3/etc issue. This simply reverts the macOS part of this as it was unnecessary on macOS anyway (Linux was unaffected by the bug).
Patches applicable to HTSlib 1.11; will not be needed for future upstream versions.

Update HTSlib recipe: patches to fix https/S3/GCS/etc plugins

---

recipes/intervene/meta.yaml

in pandas 1.0 DataFrame.ix was deprecated (https://github.com/pandas-dev/pandas/pull/26438) which leads to:
```
File "/usr/local/lib/python3.8/site-packages/intervene/modules/pairwise/pairwise.py", line 214, in heatmap_triangle
D = D.ix[cluster_order, cluster_order]
File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 5139, in __getattr__
return object.__getattribute__(self, name)
```
---- …

intervene: fix pandas version <1.0

---

build-fail-blacklist
recipes/bioconductor-cardinal/buildfixes.patch
recipes/bioconductor-cardinal/meta.yaml

`<Rinternals.h>` provides its own `extern "C"`, and on macOS wrapping it again catches some C++ headers, leading to errors. (Assuming this has no adverse effects on Linux, I'll send this patch upstream too.)

Fix bioconductor-cardinal 2.8.0 build

---

recipes/bioconductor-cytolib/dyextension.patch
recipes/bioconductor-cytolib/meta.yaml

At least with Bioconductor 3.12, R library shared libraries on macOS do have the usual _.dylib_ extension. Patch bioconductor-cytolib to adjust `cytolibLibPath()` accordingly.
~Then enable building and bump the build numbers for all the bioconductor-* packages that depend on this library.~

Fix bioconductor-cytolib on macOS and rebuild dependent packages

---

build-fail-blacklist
recipes/bioconductor-cydar/meta.yaml
recipes/bioconductor-cytofast/meta.yaml
recipes/bioconductor-cytoml/meta.yaml
recipes/bioconductor-cytotree/meta.yaml
recipes/bioconductor-flowclust/meta.yaml
recipes/bioconductor-flowcore/meta.yaml
recipes/bioconductor-flowfp/meta.yaml
recipes/bioconductor-flowmatch/meta.yaml
recipes/bioconductor-flowsom/meta.yaml
recipes/bioconductor-flowspy/meta.yaml
recipes/bioconductor-flowworkspace/meta.yaml
recipes/bioconductor-immunoclust/meta.yaml
recipes/bioconductor-ncdfflow/meta.yaml
recipes/bioconductor-opencyto/meta.yaml

Followup to PR #25292. This rebuilds recipes/bioconductor-cydar, -cyto*, -flow*, -immunoclust, -ncdfflow, and -opencyto — it appears (from the previous build logs) that this needs to be done in two stages to ensure that the dependent packages are built using the freshly-built corrected bioconductor-cytolib from the previous PR.
For CytoML and CytoTree, it seems that while these have been listed in _build-fail-blacklist_ the upstream versions present in Bioconductor have changed. So this PR updates them to the upstream version actually present in Bioconductor 3.12 rather than bumping the build numbers as for the other dozen packages. (Just bumping the build number for these two wasn't enough: trying to download the non-bioc-3.12 source tarballs just resulted in 404.)

Rebuild packages that depend on bioconductor-cytolib

---

build-fail-blacklist
recipes/bioconductor-rbowtie/build.sh
recipes/bioconductor-rbowtie/ldflags.patch
recipes/bioconductor-rbowtie/meta.yaml

This was failing due to no `-headerpad` option being used when building the executables down in src/SpliceMap. Patch the Makefile to use R's LDFLAGS (alongside the existing R's CXXFLAGS) when building these executables, as (at least with conda's R) that provides `‑Wl,‑headerpad_max_install_names`.
@mbstadler: I'm happy to make a PR against **fmicompbio/Rbowtie** once this has demonstrated that it builds successfully on both Linux and macOS. Or if you want to apply _ldflags.patch_ to the repository yourself in due course, that's probably even easier.

Fix bioconductor-rbowtie build on macOS

---

build-fail-blacklist
recipes/bioconductor-macpet/meta.yaml
recipes/bioconductor-quasr/meta.yaml

Now that PR #25327 has fixed bioconductor-rbowtie on macOS, rebuild packages that depend on it.

Rebuild packages that depend on bioconductor-rbowtie

---

build-fail-blacklist
recipes/bioconductor-gmapr/build.sh
recipes/bioconductor-gmapr/meta.yaml
recipes/bioconductor-gmapr/shlib_ext.patch

Build the shared library as `gmapR$(SHLIB_EXT)` rather than hard-coding the filename `gmapR.so`.
Ensure that `src/samtools/*.[oa]` gets rebuilt — in gmapR_1.32.0.tar.gz at least, the source tarball incorrectly already contains built-for-Linux `*.o` files, which breaks building on other platforms.

Fix bioconductor-gmapr build on macOS

---

build-fail-blacklist
recipes/bioconductor-qckitfastq/meta.yaml
recipes/bioconductor-qckitfastq/shared_timed_mutex.patch

Rather than futz around with `MACOSX_DEPLOYMENT_TARGET`, simply patch to avoid the problematic header — which is not needed in any way by the code anyway.
Avoid #including an unneeded seqan header that uses a std datatype that's not available in macOS's libc++ prior to macOS 10.12. This patch can be removed when `MACOSX_DEPLOYMENT_TARGET` is raised past 10.12.

Fix bioconductor-qckitfastq build on macOS

---

recipes/vcf2maf/meta.yaml

Updating vcf2maf to use the most recent v1.6.18 tagged release. 
Note that it seems this release keeps on getting updated (most recently on August 13th 2020) but not re-tagged.
---- …

Update vcf2maf: use most recent sha256sum

---

build-fail-blacklist
recipes/r-misha/meta.yaml
recipes/r-misha/omit-FileUtils.patch

A bonus post-hackathon PR to eliminate this “Fails on OSX” section of _build-fail-blacklist_…
This package contains code that uses a Linux-specific `sendfile()` system call. Fortunately the code in question (`FileUtils::copy_file()`/`move_file()`) is unused anyway, so we just patch to remove the problematic code.
Implementing an additional alternative instead so the code compiles everywhere has been proposed upstream in PR tanaylab/misha#2.

Fix r-misha build on macOS

---

recipes/irida-uploader/meta.yaml

irida-uploader use DNS resolution as part of its upload process. The default busybox based image used for bioconda has [broken resolv.conf](https://github.com/bioconda/bioconda-recipes/issues/11583) when used as a bases for Singularity images. This patch switches the irida-uploader recipt to use the extended image to resolve this problem.
----
* PRs require reviews prior to being …

Use extended image for irida-uploader

---

recipes/intervene/meta.yaml

- remove/invert restriction on pandas which was fixed in 0.6.5 https://github.com/asntech/intervene/issues/40#issuecomment-728631675
- running the tool outputs deprection warnings for matplotlib >= 3.4 ..
so I added a version restriction
---- …

add proper tests to intervene

---

recipes/encyclopedia/meta.yaml
recipes/mpa-portable/build.sh
recipes/mpa-portable/meta.yaml

Try to fix:
```
java.io.FileNotFoundException: /usr/local/share/mpa-portable-1.4.1-2/built/X!Tandem/linux/linux_64bit/taxonomy.xml (Permission denied)
```
for running in a docker container by using chmod.
Without fonts-conda-ecosystem and openjdk 11 we get
```
|  Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
|  at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
|  at java.base/java.security.AccessController.doPrivileged(Native Method)
|  at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
|  at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:247)
|  at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:265)
|  at …
```

encyclopedia and mpa-portable: add fonts and fix permissions

---

recipes/qax/meta.yaml

Update qax to 0.6.0

---

recipes/trnascan-se/meta.yaml

Also allow infernal >= 1.1.2 as a dependency (trnascan-se INSTALL explicitly mentions internal 1.1.2, but as infernal 1.1.3 was _relatively_ recent, I suspect trnascan-se documentation just hasn't been updated yet).

Update trnascan-se to 2.0.7

---

recipes/ncrf/meta.yaml

The associated python scripts of [NCRF](https://github.com/makovalab-psu/NoiseCancellingRepeatFinder) need python <3. The previous meta.yaml was in conflict with this.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
For members of the Bioconda project, the …

Update recipe for ncrf by changing requirement to python <3

---

recipes/treesapp/meta.yaml

For some reason the changes made to treesapp's meta.yml file in the version bump PR #25406 were not merged into master. Hopefully by including those missing edits it will build successfully, as it did before.

Update treesapp meta.yml

---

recipes/chap/LICENSE.TXT
recipes/chap/build.sh
recipes/chap/meta.yaml

Adds recipe for CHAP, which carries out functional annotation of ion channel structures
There are some unfortunate version pinnings here: Gromacs versions >2018 are not compatible with the software, while using libcblas/liblapacke versions > 3.8.0 fail to compile. The netlib versions of these libraries are also required instead of the openblas versions which don't include the necessary headers for the compilation to succeed.
The software is also described as being only tested on ubuntu, and my attempts to build on macos have failed.

Add CHAP recipe

---

recipes/iqtree/build.sh
recipes/iqtree/meta.yaml

Pass `-DUSE_LSD2=ON` to `cmake` for iqtree to enable least-squares dating (`lsd2` was already included as a source)
Previously, an error would be thrown if the `--date` flag were specified.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
For members of the …

update iqtree to enable date inference via lsd2 in cmake call of iqtree build

---

recipes/t-coffee/activate.sh
recipes/t-coffee/build.sh
recipes/t-coffee/deactivate.sh
recipes/t-coffee/meta.yaml

This is the compiled T-Coffee package.
----
<details> …

Update t-coffee to 13.45.0.4846264

---

recipes/hail/meta.yaml

Hail supports python3 up to 3.7, so easing the restriction to allow 3.7 in addition to 3.6.
Plus, updating the Hail version.

Update Hail to 0.2.61, allow Python 3.7

---

recipes/maker/meta.yaml
recipes/maker/repeatmasker_check.patch
recipes/orthofinder/meta.yaml

Patch-level update; per RELEASE file:
> *maker_functional_fasta and maker_functional_gff handle newer UniProt/Swiss-Prot
format. Also fix for newer genemark command line structure.
Also an attempt to fix https://github.com/bioconda/bioconda-recipes/issues/25559

Update maker to version 2.31.11

---

recipes/chromeister/meta.yaml

This PR updates chromeister to 1.5.a which fixes the following:
- Fixed memory access error when output file path contained keyword ".csv" (and probably on other cases too)
- Fixed memory leaking at exit of 3 blocks
and also improves readability on stdout when used from workflow managers such as galaxy
----
* PRs require reviews prior to being merged. Once your PR is passing tests …

update to chromeister 1.5.a fixes potential memory errors

---

recipes/panphlan/meta.yaml

New version of PanPhlAn is out on the PanPhlAn repository (version 3.1): On top of that the dependencies were not complete, PanPhlAn needs bowtie2 and samtools to run

Update PanPhlAn 3.0 to PanPhlAn 3.1

---

recipes/ivar/meta.yaml

I have added samtools as a runtime dependency.
A few of the ivar tools take input from samtools. For example:
```
ivar consensus
Usage: samtools mpileup -aa -A -d 0 -Q 0 <input.bam> | ivar consensus -p <prefix> 
```
So, when building rules in nextflow or snakemake it would be nice to have docker containers with samtools and ivar ready to go --- or automatically create the appropriate ivar conda environment with samtools already in it.

Update ivar recipe to include samtools dependency

---

recipes/president/meta.yaml

president is a tool that computes pairwise nucleotide identities with respect to a reference sequence and reports if they are valid/invalid.

Add president v0.2.1

---

recipes/hail/meta.yaml

Update the Hail package to support Batch functionality: adds missing dependencies.
Also removing the redundant gcsfs ==0.2.1 pin.

Update Hail: update to support hailtop.batch

---

recipes/ntjoin/build.sh
recipes/ntjoin/meta.yaml

Bumping build of ntJoin recipe, due to errors seen when installing on Mac and linux. (reported by a user and I reproduced https://github.com/bcgsc/ntJoin/issues/58)
Pysam import was throwing an error, which I found I could solve by specifying a newer pysam version:
```
conda install ntjoin pysam=0.16.0
```
So, updated recipe to specify pysam and samtools versions as newer ones to hopefully avoid that error with the `conda install`. Also added a couple more tests to hopefully catch any import issues in the CI if present.
Logs of errors:
Mac:
Error:
```
conda install ntjoin
(test_ntjoin_c) Laurens-MacBook-Pro:ntjoin laurencoombe$ /Users/laurencoombe/Documents/Work/GSC/miniconda/envs/test_ntjoin_c/bin/share/ntjoin-1.0.5-0/bin/ntjoin_assemble.py 
File …
```

Update ntJoin 1.0.5 recipe

---

recipes/seqmagick/meta.yaml

This makes meta.yaml more closely match seqmagick's own setup.py which fixes seqmagick's --line-wrap feature.  Fixes #26546.

Fix seqmagick 0.8.4 requirements to specify biopython >= 1.78

---

recipes/braker2/meta.yaml

(NOTE: resubmit of https://github.com/bioconda/bioconda-recipes/pull/26432 to work around CircleCI issue)
braker2 2.1.5 script log_reg_prothints.pl needs perl module Math::Utils for log_reg_prothints.pl:
```
$ conda create -c conda-forge -c bioconda -n braker2-env braker2=2.1.5=1
$ source activate braker2-env
(braker2-env) $ log_reg_prothints.pl
Can't locate Math/Utils.pm in @INC (you may need to install the Math::Utils module) (@INC contains: /home/user/.conda/envs/braker2-env/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/.conda/envs/braker2-env/lib/site_perl/5.26.2 /home/user/.conda/envs/braker2-env/lib/5.26.2/x86_64-linux-thread-multi /home/user/.conda/envs/braker2-env/lib/5.26.2 .) at /home/user/.conda/envs/braker2-env/bin/log_reg_prothints.pl line 9.
BEGIN …
```

braker2 needs perl-math-utils for log_reg_prothints.pl

---

recipes/cryptogenotyper/meta.yaml

Updated software database to include better coverage of some species. This is build #2 as the tool announcement manuscript will rely on this version.

build 2 CryptoGenotyper v1.0 update

---

recipes/raven-assembler/meta.yaml

I have removed git submodules from the Raven repository, so the auto-generated release archives are sufficient for builds.

Update raven-assembler meta.yaml

---

recipes/jvarkit-wgscoverageplotter/build.sh
recipes/jvarkit-wgscoverageplotter/meta.yaml
recipes/jvarkit-wgscoverageplotter/wgscoverageplotter.py

This replaces the shell script wrapper for jvarkit's wgscoverageplotter with a Python based one. The Python wrapper handles parameters with possible shell metacharacters better.
---- …

Switch jvarkit-wgscoverageplotter to a python wrapper

---

recipes/fastqc-rs/build.sh
recipes/fastqc-rs/meta.yaml

This PR adds a recipe for [fastqc-rs](https://github.com/fxwiegand/fastqc-rs), a quality control tool for FASTQ files written in rust.

Add fastqc-rs v0.1.0

---

recipes/augur/meta.yaml

These differences from Augur's setup.py came to my attention because a
too-new BioPython was pulled into a new environment, which visibly broke
`augur index`.

Update augur: Sync dependency versions to those from upstream

---

recipes/ma/meta.yaml

I tried updating MA via the autobump but checks failed with python<3.9 (https://github.com/bioconda/bioconda-recipes/pull/26601).
As far as I can tell, the checks failed because python 3.9 and 3.7 were mixed during building and testing.
This pull request exists because I'd like to have a python>=3.6 requirement.

MA 1.1.4 & python 3.6

---

recipes/krona/2.7.1/build.sh
recipes/krona/2.7.1/meta.yaml
recipes/krona/2.7.1/post-link.sh

Add `make` to krona 2.7.1 recipe, which is required for `ktUpdateTaxonomy`. 
Current BioContainer lead to the following error when running `ktUpdateTaxonomy.sh taxonomy`:
```
/usr/local/bin/ktUpdateTaxonomy.sh: line 163: [: ==: unary operator expected
/usr/local/bin/ktUpdateTaxonomy.sh: line 287: make: command not found
```

Update krona 2.7.1 recipe

---

recipes/gfatools/build.sh
recipes/gfatools/meta.yaml

Add gfatools  tools for manipulating sequence graphs in the GFA and rGFA formats 
----
<details>
<summary>Please use …

Add gfatools

---

recipes/calitas/meta.yaml

Yesterday I submitted PR #26954 to add a new recipe for CALITAS.  The tests ran fine locally and in CI, but once the PR was merged I searched in bioconda and realized that the version was mistakenly set to the sha hash value instead of a reasonable version string.  This PR remedies that.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built …

Fix version string in calitas recipe to be the version not the sha hash.

---

recipes/gromacs/2020/build.sh
recipes/gromacs/2020/meta.yaml

Fix GROMACS SIMD detection on osx. /proc/cpuinfo doesn't exist, but the fallback logic was providing the SSE2 version. Now it will run other versions on suitable hardware.
---- …

Update gromacs to fix SIMD detection on OSX

---

recipes/gcta/build.sh
recipes/gcta/meta.yaml

Adding gcta v1.93.2beta.
The software is precompiled and distributed as an executable. 
I have include sources for linux and osx.

Add gcta v1.93.2beta

---

recipes/nextstrain-cli/meta.yaml
recipes/nextstrain-cli/run_test.sh

Adds a recipe for the Nextstrain CLI, using PyPI as a source.
Cc: @huddlej

Add nextstrain-cli

---

recipes/galaxy-data/meta.yaml

galaxy-data: initial commit

---

recipes/deepnog/meta.yaml

`deepnog` requires PyTorch, which was previously not available from conda standard channels. Thus, the current deepnog recipe is omitting it, requiring the user to manually install the pytorch dependency from the pytorch channel.
Now it seems, conda-forge has pytorch, and we, therefore, include it in the requirements section. Also, we can now actually do tests in this recipe. Finally, I think we had some superfluous host requirements.

Update deepnog: require PyTorch

---

recipes/sourmash/meta.yaml

sourmash 4.0 remove the dependency on bam2fasta, updating recipe to reflect it.

Update: sourmash -> remove bam2fasta dep

---

recipes/multiqc/meta.yaml

Fix for incorrect rich version being kept
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr>
<td>Upload built packages/containers …

Pin rich version to >=9.4.0

---

recipes/virulign/build.sh
recipes/virulign/meta.yaml

Please add the recipe for VIRULIGN v1.0.2. This is a bioinformatics software for codon-correct pairwise alignments, with an augmented functionality to annotate the alignment according the positions of the proteins.
----
* Please …

Add VIRULIGN v1.0.2

---

recipes/gotree/build.sh
recipes/gotree/meta.yaml

Update gotree: 0.4.0 → 0.4.1
The recipe has also been modified to prevent build errors.

Update gotree to 0.4.1

---

recipes/perl-atlas-modules/meta.yaml

This adds Perl MySQL conda package to the dependencies, which is needed for the ArrayExpress curation scripts and checker daemon to interact with the submissions tracking database.

Add mysql perl-module dependency install command

---

recipes/bactopia/meta.yaml

Auto updater missed this one
----
<details>
Everyone …

Update bactopia to v1.6.2

---

recipes/psass/meta.yaml

This PR updates PSASS to 3.1.0 and replaces the URL with that of the new repository

Update PSASS version and URL

---

recipes/leviosam/build.sh
recipes/leviosam/meta.yaml

This conda recipe is for levioSAM - a lift-over tool for SAM/BAM files for variant-aware references described in a VCF file.
preprint is here: https://www.biorxiv.org/content/10.1101/2021.02.05.429867v1
the github repo is here: https://github.com/alshai/levioSAM

Add leviosam recipe

---

recipes/antismash/meta.yaml

Biopython has removed Bio.alphabet in 1.78, which is required by antismash. Biopython is therefore additionally pinned to <=1.77.

Update antismash: pin biopython to versions including bio.alphabet

---

recipes/deepvariant/meta.yaml

This PR changes the dependency from `tensorflow` to `tensorflow-gpu`. This in turns allows for GPU support and very significant performance improvements. I am not aware of any drawbacks to this beyond the additional dependencies introduced, e.g. `cudatoolkit` and `cudnn`. Installation works fine on non-GPU machines as well.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr> …

Update deepvariant to enable GPU support

---

recipes/braker2/build.sh
recipes/braker2/meta.yaml

Fix problem with unavailability of *.py scripts in /bin/ of Braker v2.1.6

Update build.sh to add *.py scripts to bin

---

recipes/disco/1.2/build.sh
recipes/disco/1.2/meta.yaml

added missing `\`
Wondering why `READGZ=1` did not produce an error in https://github.com/bioconda/bioconda-recipes/pull/27874
Maybe one should more often `set -eo pipefail`?
----
* Please post …

disco: really compile with gz support

---

recipes/libsbml/build.sh
recipes/libsbml/meta.yaml

- added popular extensions to libsbml compilation to enable proper
usage in constraint-based modelling
- these extensions are needed for example to use sbml in R (sybiSBML)
- linux distributions often contain these extensions by default, for
example debian: https://salsa.debian.org/med-team/libsbml

Update libsbml to contain extensions

---

recipes/mimsi/meta.yaml

Adds MiMSI to Bioconda recipes. MiMSI is a deep multiple instance learning classifier for identifying microsatellite instability in next-generation sequencing results - https://github.com/mskcc/mimsi 
----
* Please post …

Add MiMSI to recipes

---

recipes/deepvariant/dv_make_examples.py
recipes/deepvariant/meta.yaml

This PR adds a the missing `--sample_name` argument to `dv_make_examples.py`. Without this flag the samples in vcfs will be named `default`, which causes problems, eg when merging vcfs.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
For members of the …

Updates deepvariant recipe

---

recipes/snakedeploy/0001-gh-13-Exclude-tests-package-from-dist.patch
recipes/snakedeploy/meta.yaml

----
<details>
Everyone has access to the following …

add snakedeploy

---

recipes/nextflow/meta.yaml

This PR updates nextflow to version 21.04.0
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr>
<td>Upload built …

Update nextflow 21.04.0

---

recipes/multiqc/meta.yaml

MultiQC dependency `networkx` needs version `>=2.5.1` to work with Python 3.9. This PR sets that version requirement.
---- …

Update MultiQC: Bump minimum `networkx` version to ensure compatibility with Py3.9

---

recipes/repeatmasker/meta.yaml

This release of RepeatMasker does not add any notable new features compared to 4.1.1, but it does fix several regressions.
Over the last few years there have been multiple different problems in the software, the recipe, and/or the bioconda build environment, at different times, due to which the classification step of `RepeatModeler` does not currently work entirely as intended, and has probably never worked, when installed via bioconda (#9988, Dfam-consortium/RepeatModeler#128). I have tested this version locally alongside the current bioconda RepeatModeler package and confirmed that it looks good, but I still want to test the artifacts built by the bot just in case!
While testing this, I did run into one pretty confusing problem: this package is built with rmblast 2.10.0 (the latest …

Update RepeatMasker to 4.1.2-p1

---

recipes/fastqc-rs/meta.yaml

This updates some necessary things after moving the [fastqc-rs repository](https://github.com/fastqc-rs/fastqc-rs) to its own [organization](https://github.com/fastqc-rs).

Update fastqc-rs recipe

---

recipes/ddocent/meta.yaml

Upcoming new release will need this dependency and upgrading meta.yaml now allows for compatibility with developmental code
Update dDocent meta.yaml to include `bedops`
---- …

Update dDocent meta.yaml to include `bedops`

---

recipes/gemoma/GeMoMa.py
recipes/gemoma/meta.yaml

Update gemoma to the latest version ([currently 1.7.1](http://www.jstacs.de/index.php/GeMoMa#Version_history))
Currently, GeMoMa wrapper script always exits with status 0. This PR suggests making the exit status of the GeMoMa wrapper script consistent with the exit status of the `java -jar /path/to/GeMoMa-1.7.1.jar ...` subprocess. This is particularly important when GeMoMa is in a workflow, as a false 0 exit status makes debugging the workflow difficult (FWIW, this issue was first noticed when trying to debug GUSHR from braker2 2.1.6, which internally invokes GeMoMa).

Update GeMoMa version & fix exit status

---

recipes/lddt/2.2/meta.yaml

This PR adds a recipe for the local Distance Difference Test (lDDT) tool. lDDT computes a superposition-free score that evaluates local distance differences in a protein structural model compared to a reference structure.
**Relevant publications**
* Mariani, V., Biasini, M., Barbato, A., Schwede, T. lDDT: a local superposition-free score for comparing protein structures and models using distance difference tests. Bioinformatics 29, 2722-2728 (2013).
----
* New recipes not directly relevant to the biological sciences need to be submitted to the …

Initial commit of lddt recipe

---

recipes/ostir/meta.yaml

In addition, this recipe UPDATES the project URL to reflect the release name and updates the dependencies to require a more recent version of vienna.

Update ostir to 1.0.4

---

recipes/deepaccess/meta.yaml

Add deepaccess as a bioconda recipe. DeepAccess provides training and interpretation of ensemble of convolutional neural networks for predicting accessibility or other functional epigenomic signal data.
----
* Please post …

Add deepaccess 

---

recipes/shapeit4/build.sh
recipes/shapeit4/meta.yaml

Recommended by developer to resolve `invalid pointer` error when using shapeit4 through conda (see odelaneau/shapeit4#54 (comment))

Update shapeit4 to v4.2.1

---

build-fail-blacklist
recipes/blast/build.sh

Adding new config option to the blast recipe

Blast update

---

recipes/grampa/grampa.patch
recipes/grampa/meta.yaml

This PR adds a recipe for [GRAMPA](https://github.com/gwct/grampa)
The patch allows the grampa.py script to be invoked from a different directory from the `lib/` module (which is installed in the site-packages directory using the less-generic name *grampa_lib*, and the grampa.py script copied to `$PREFIX/bin`)
helper_scripts/ were not included, as they were not described in the documentation, and would add additional heavyweight dependencies such as numpy & matplotlib (though I will contact the author to confirm that they are OK to exclude).

Add recipe for GRAMPA

---

recipes/odgi/meta.yaml

This updates the `odgi` recipe to v0.6. The source is now a buildable tarball. The SHA256 sum was added, too.
`odgi` has a new build dependency, `jemalloc`. I hope I did everything correctly.
Since `Conda` was updated to GCC9.3 recently, this is not a blocker for `odgi` on `Bioconda` anymore. However, we still have the custom build script. I don't have enough experience with `Bioconda`, but maybe someone experienced can judge, if we can get rid of this.
Please take a look @apeltzer @dpryan79. Thanks!

Update odgi to v0.6

---

recipes/py_fasta_validator/meta.yaml

py_fasta_validator is a simple, lightweight, python wrapper around a C-based fasta validator. It checks for common errors in a fast file and reports them via the `stderr` or the exit code.
---- …

Add py_fasta_validator

---

recipes/maxquant/maxquant
recipes/maxquant/meta.yaml

MaxQuant in combination with dotnet=2.1 or mono>=6.12 do have incompatibilities with symbolic/soft links and Thermo RAW files (run crashes at `Assemble_run_info`). The last conda package of mono=5 does not have those issues.

Update MaxQuant 1.6.17.0

---

recipes/stringdecomposer/meta.yaml

Update [stringdecomposer](https://bioconda.github.io/recipes/stringdecomposer/README.html): 1.0.0 → 1.1.0.
Fix to the recipe to account for the changed interface of the tool.
---- …

Update stringdecomposer to 1.1.0 (manual)

---

recipes/deepsig/meta.yaml

Due to a dep collision, Python needs to be of version `<3.9`.
Therefore, I downgraded python to version `3.6|3.7|3.8`

Update DeepSig Python dependency

---

build-fail-blacklist
recipes/perl-bio-db-hts/meta.yaml

Bump perl-bio-db-hts so it has a package that is installable alongside other packages that use the currently pinned htslib, 1.12.
Fixes #29193.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …

Rebuild perl-bio-db-hts with current pinned htslib

---

recipes/homer/build.sh
recipes/homer/configureHomer.patch
recipes/homer/meta.yaml

Hi,
Currently if the conda environment contains a @ in the name (like in galaxy), `annotatePeaks.pl` raise an error.
For the moment, this PR is not working but I don't know how to do it.
I would like the patch to be applied before running the `build.sh`. Is it the case like this?
Thanks

Enable homer on conda environement with @

---

recipes/maxquant/1.6.17.0/maxquant
recipes/maxquant/1.6.17.0/meta.yaml
recipes/maxquant/1.6.17.0/mod_propionamide.xml
recipes/maxquant/1.6.17.0/mod_tmtpro16plex.xml
recipes/maxquant/1.6.17.0/xmlcombine.py

In some instances newer MaxQuant versions complaining about not using .NET. It depends on the useDotNetCore parameter in the mqpar file, which by default is set to True in version >=1.6.17.0. In older versions the paramater is set to False (f.e. in 1.6.10.43). To avoid any further incompatibilities I would suggest to switch to dotnet.
**Moved files of MaxQuant 1.6.17.0 tool wrapper into versioned subdir.**

MaxQuant 1.6.17.0 use dotnet instead of mono

---

recipes/scanpy-scripts/meta.yaml

The dependencies in the receipt were not up-to-date with the dependencies in the Git repo ([setup.py](https://github.com/ebi-gene-expression-group/scanpy-scripts/blob/v1.0.0/setup.py)).
- `scanpy>=1.6.0`              --> `scanpy>=1.8.0`
- `bbknn>=1.3.12,<1.5.0`  -->  `bbknn>=1.5.0`
- `scrublet`
- `fa2`
- `numpy<1.19.5`

Update Dependencies for scanpy-scripts

---

recipes/seqwish/meta.yaml

This updates the seqwish recipe to v0.7.1. The source includes a buildable tarball now too.

Update seqwish to v0.7.1

---

recipes/deepsignal-plant/meta.yaml

The PR adds a recipe for [deepsignal-plant](https://github.com/PengNi/deepsignal-plant), a deep-learning method for detecting methylation state from Oxford Nanopore sequencing reads of plants.
---- …

Add deepsignal-plant recipe

---

recipes/seqwish/build.sh
recipes/wfmash/build.sh
recipes/wfmash/meta.yaml

To allow users to install more easily wfmash (https://github.com/ekg/wfmash/issues/87, https://github.com/pangenome/pggb/issues/112).

update wfmash to v0.6.1

---

recipes/rfplasmid/meta.yaml

Update to release 0.018
1. Automated sampsize selection for training.
2. Renaming the taxa agnostic Bacteria model to "Generic"
3. TOC in the Readme
4. Google Colab notebook
----
* Please post …

Update to release 0.018

---

recipes/maxquant/1.6.17.0/meta.yaml
recipes/maxquant/1.6.17.0/mod_tmtpro18plex.xml
recipes/maxquant/meta.yaml
recipes/maxquant/mod_tmtpro18plex.xml

This PR adds TMTpro18plex modifications (`mod_tmtpro18plex.xml`) to MaxQuant version 1.6.17.0 and 2.0.1.0.

Add TMTpro18plex modifications to MaxQuant 1.6.17.0 & 2.0.1.0

---

recipes/metasnv/build.sh
recipes/metasnv/meta.yaml

metaSNV 2.0.0 is now available updating from 1.0.3
Tagging the dev team: @theavanrossum @LucasPaoli and the initial bioconda recipe maintainer @AlessioMilanese

Update metaSNV to 2.0.0

---

recipes/metasnv/meta.yaml

We need to have samtools in the installed environment.
We missed it in #29996 as it was installed system-wide.
This PR adds it.

metaSNV: add missing dependency

---

recipes/abnumber/meta.yaml

Due to bug in ANARCI dependency, we will now require a fixed version in abnumber package

Change requirements in abnumber

---

recipes/macrel/meta.yaml

Piggy-backs on updating macrel (#30365) to also update the DOI to the published paper (instead of the preprint)
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr> …

Update macrel version (to 1.0.1) & DOI reference

---

recipes/cellprofiler/meta.yaml

restrict the numpy version <1.20 for cellprofiler 4 to work correctly

restrict numpy version in cellprofiler

---

recipes/pathogentrack/meta.yaml

----
<details>
Everyone has access to the following …

Add recipe for PathogenTrack v0.2.3

---

recipes/insilicoseq/meta.yaml

Biopython 1.79 is incompatible with InSilicoSeq for the moment, this pr updates the requirements to biopython <= 1.78
---
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr> …

Update insilicoseq requirements: bipython <= 1.78

---

recipes/fsnviz/meta.yaml

A dependency of fsnviz (crimson) has a new bugfix release, see https://github.com/bow/crimson/pull/14 for details

Rebuild fsnviz to pull in latest release of 'crimson'

---

recipes/spatyper/build.sh
recipes/spatyper/meta.yaml
recipes/spatyper/spatyper.patch

I thought I had it figured out in https://github.com/bioconda/bioconda-recipes/pull/30622 but it fails when `--entrypoint` is used due to loss of ENV variables.
This PR adds default DB location to spaTyper script
----
* Please …

Update spatyper 

---

recipes/r-ichorcna/meta.yaml

The current r-ichorcna package is the most recent github tagged version (May 2019), but there have been changes and a newer script version since then (v0.3.2 - as detailed in the DESCRIPTION file).

Update r-ichorcna to most recent github version (v0.3.2)

---

recipes/ngmaster/meta.yaml

For some reason the tool ngmaster for serotyping Neisseria gonorrhoeae assemblies does not have a docker container on Biocontainers. Going to see if rebuild will get us one
---- …

rebuild ngmaster to get docker container

---

recipes/entrez-direct/build.sh
recipes/entrez-direct/meta.yaml

Updated Entrez Direct to version 16.2
Also adding the help files that need to be located in the `$PREFIX/bin/help` folder

Updated Entrez Direct to version 16.2

---

recipes/meta-apo/build.sh
recipes/meta-apo/meta.yaml

Missing `make CC=$CXX` lead to a segment fault. This time we fixed it.

[Update]: add make argument

---

recipes/abyss/meta.yaml

As per https://github.com/bcgsc/abyss/issues/382, ABySS depends on perl that this PR adds.

Update ABySS 2.3.3 recipe

---

recipes/pbcore/1.2.7/meta.yaml

This is related to pull request  #30651. I was able to build a working package of pbcore v1.2.7 using the recipe I've added here (my package is at https://anaconda.org/bishemma1/pbcore). This package needs to be under the bioconda channel so that I can specify this version in the PBHoover recipe (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pbhoover/meta.yaml). PBHoover v1.0.7 needs pbcore v1.2.7 specifically, and we want to avoid requiring users to pip install that version of pbcore.
@simonbray

Add recipe for pbcore v1.2.7

---

recipes/spades/meta.yaml

This PR specifies the Python version (3.9) since, as reported in https://github.com/ablab/spades/issues/863, the current Spades version is not compatible with Python>=3.10. 
---- …

Update Spades v.3.15.3: specify python version

---

recipes/selenzy_wrapper/meta.yaml
recipes/selenzy_wrapper/run_test.sh

Add recipe for **selenzy_wrapper** 0.0.4: Python wrapper of selenzy tool
https://github.com/brsynth/selenzy-wrapper/
---- …

add new recipe selenzy_wrapper v0.0.4

---

recipes/hecatomb/meta.yaml

Update Hecatomb to version 1.0.0.beta.3
I'm not sure why the bot didn't automatically generate the PR.

update hecatomb to 1.0.0.beta.3

---

recipes/pyfaidx/meta.yaml

pyfaidx imports pkg_resources and therefore needs setuptools as run dependency. For some reason, `conda install pyfaidx` on Linux will pull in setuptools, while doing the same on macOS will not, so using pyfaidx on macOS fails (unless some other package happens to pull in setuptools).
This came up while bumping WhatsHap in #31867, where the macOS build fails with `ModuleNotFoundError: No module named 'pkg_resources'` in `pyfaidx/__init__.py`.
----
* New recipes not directly relevant to the biological sciences need to be submitted to the …

Update pyfaidx as it needs setuptools as dependency

---

recipes/cyvcf2/meta.yaml
recipes/cyvcf2/patches/setup.py.patch

Supercedes #31897.
The `setup.py` changed, so the patch needed to be rejigged. Ping @brentp.

Update cyvcf2 to 0.30.14

---

recipes/nextalign/meta.yaml

Update nextalign to 1.7.0
According to the author:
* Nextalign is up to 6x times faster! (now aligns and translates 100k sequences in 51 seconds, down from 5 minutes, on AWS EC2 c5.24xlarge)
---- …

Update nextalign to 1.7.0

---

recipes/pbhoover/meta.yaml

As described in the commit, we discovered that PBHoover was buggy unless using these versions of:
pbh5tools <=0.8.0
bcftools <=1.3.1
pyvcf <=0.6.7
pbcore <=1.2.7
So I updated the meta.yaml to fix this.

Update pbhoover dependency versions

---

recipes/gimmemotifs/meta.yaml

@simonvh gimmemotifs motif2factors doesn't work with genomepy lower than 0.10 :shrug:

gimmemotifs requires genomepy 0.10 or higher

---

recipes/trust4/build.sh
recipes/trust4/meta.yaml

TRUST4 v1.0.6 adds a new postprocessing script trust-airr.pl, and needs to add to the bioconda install list. Thank you!

Update TRUST4 v1.0.6

---

recipes/fusioncatcher/meta.yaml

Describe your pull request here:
fastqtk is new dependency to fusioncatcher, and tbb needs to be pinned to 2020.2 otherwise gives `error while loading shared libraries: libtbb.so.2` error.
---- …

Pin tbb version and add fastqtk

---

recipes/moments/meta.yaml

Due to a bug on Bitbucket's end (https://jira.atlassian.com/browse/BCLOUD-21582), I've switched the source download from tar.bz2 to tar.gz. This was preventing the autobump from 1.1.8 to 1.1.9 this last month.

Update moments to 1.1.9

---

recipes/hecatomb/meta.yaml

Updates Hecatomb to v1.0.0.beta.5

Update hecatomb to 1.0.0.beta.5

---

recipes/drop/meta.yaml

This is the correct version bump for DROP 1.1.2, since the autobump does not update the dependencies. Fixes #32745

bump DROP 1.1.1 -> 1.1.2 and update dependencies

---

recipes/peregrine-2021/build.sh
recipes/peregrine-2021/meta.yaml

This PR adds [peregrine-2021](https://github.com/cschin/peregrine-2021) which is a long-read assembler written in Rust.

Jc add peregrine 2021

---

recipes/ebcsgen/meta.yaml

This pull request adds a recipe for [eBCSgen](https://github.com/sybila/eBCSgen) to bioconda. The goal is to support an easier installation and to wrap this tool for usage in Galaxy.

Add eBCSgen recipe

---

recipes/stacks/build.sh
recipes/stacks/meta.yaml

Update stacks to 2.60
* Install missing r-core dependency
* Replace `#!/usr/bin/perl` with `#!/usr/bin/env perl` in convert_stacks.pl
* Test additional scripts added since previous version
* Test command output to catch missing libraries / bad interpreters

Update stacks to 2.60

---

recipes/dunovo/build.sh
recipes/dunovo/meta.yaml

I'm trying to make a package for Du Novo 3.0. The new tool version has a new dependency: BioPython.
I've also added a few other dependencies which it always depended on but weren't specified before, like samtools, bash, and a number of unix utilities.
I've had a lot of trouble getting this to build and run. I logged one problem in #32718. Based on @bgruening's suggestion, I pinned `tbb`, but even then, it still doesn't run properly unless I first manually install an old version of `tbb` in the conda environment (so far I've only tried 2018.0.3). But it sounds like this might just be my machine?

Update Du Novo: Initial version of 3.0 support.

---

recipes/antismash-lite/build.sh
recipes/antismash-lite/meta.yaml

As described in [#418](https://github.com/antismash/antismash/issues/418) of the AntiSMASH GitHub, it would be useful to have an AntiSMASH package without automatic database download available on conda.
The name `antismash-lite` is analogous to the provided Docker image without database download (see AntiSMASH [documentation](https://docs.antismash.secondarymetabolites.org/install/#antismash-standalone-lite)).
----
Ping @jfy133 @kblin

Add antismash-lite

---

recipes/artic/meta.yaml

Muscle pinned to version 3.8 for compatibility, also reimplemented the scheme downloader in python to avoid a bug with artic-tools where the latest scheme (V4.1) was processed as a float.
---- …

Update - 1.2.2 version bump

---

build-fail-blacklist
recipes/ucsc-fatovcf/build.sh
recipes/ucsc-fatovcf/inc.common.mk.v426.patch
recipes/ucsc-fatovcf/meta.yaml
recipes/ucsc-fatovcf/run_test.sh

ucsc-fatovcf has not been updated since March 2021, and it has `skip: True # [osx]`.  However, the tool pangolin, used by public health departments worldwide to assign SARS-CoV-2 lineages to new genome sequences, depends on faToVcf when using --usher mode, which is slated to become pangolin's default mode soon.  In June 2021, an important new option was added to faToVcf; pangolin really should be using the latest version of faToVcf with the new option.
This PR updates the version from 407 to the latest stable version, 426, and removes the `skip: True # [osx]`.
I expect there will be some build problems because the `skip` must have been added for a reason, but I'm sure we can work through them.

Update ucsc-fatovcf from v407 to v426; remove skip.

---

recipes/scanpy-scripts/meta.yaml

Just a bump necessary due the multiple sources preventing autobump.
FAO Bioconda overlords: I do intend to remove this hack once the upstream Scanpy releases include the requisite Scrublet fixes. 
---- …

Bump scanpy-scripts version

---

recipes/phyloacc/build.sh
recipes/phyloacc/meta.yaml

This PR adds a recipe for [PhyloAcc](https://github.com/phyloacc/PhyloAcc), which is software for estimating substitution rates and rate shifts in conserved non-exonic regions.
The main code base is built and installed and the Python interface is copied to `$PREFIX/bin/` and its associated libraries to `$SP_DIR/phyloacc_lib/`.

Add recipe for phyloacc

---

recipes/ngscheckmate/meta.yaml

Remove the version pinning for bcftools and samtools in ngscheckmate as discussed after #33443 was merged.

Remove version pinning for ngscheckmate

---

recipes/ngscheckmate/meta.yaml

samtools mpileup is removed from v1.15 so bam mode fails as the python script calls samtools mpileup.
Reverts my previous PR #33444 .

Pin ngscheckmate samtools to 1.14. samtools mpileup is removed in 1.15

---

recipes/pbipa/meta.yaml

Pinned the versions of Samtools (>=1.15), Htslib (>=1.15) and Snakemake (>=7.0.4) in recipes/pbipa/meta.yaml. Hopefully this will prevent Samtools issues with wrong OpenSSL/libcrypto, and Snakemake issue with smart_open.

Update Pbipa: pinned requirement versions.

---

recipes/triqler/meta.yaml

This PR adds a missing dependency for the latest version of Triqler.

Update Triqler dependencies for 0.6.2

---

recipes/mokapot/meta.yaml

This PR bumps the minimum version of Triqler required from v0.3.0 to v0.6.2. 
@dpryan79 --- can you add me as a Bioconda member? Thanks!

Update mokapot's dependencies

---

recipes/metanovo/build.sh
recipes/metanovo/meta.yaml
recipes/metanovo/metanovo_activate.sh

This adds a new recipe for the MetaNovo tool.
A few notes:
- I added `- should_be_noarch_python` to `skip-lints` because this does target specifically `linux-64`.  Other architectures are skipped with `skip: True`. I'm not sure why the linter expects `noarch: python`, but I used the precedent in #16556 to skip the check.
- I added some DSOs to the list of allowable missing DSOs. I expect that the user's Linux system should have these available for the packaged native dependency. In fact, these specific dependencies are not yet used (they may be at a later time) by the tool, but are included in the larger distribution that is used by MetaNovo, e.g. PepNovo in DeNovoGUI.

Add MetaNovo recipe

---

recipes/pprodigal/meta.yaml

Add recipe for pprodigal, a simple python3-based wrapper to parallelize gene prediction
with the popular prodigal tool by splitting the input into chunks.

Add pprodigal 1.0.1

---

recipes/biophi/meta.yaml

Update BioPhi dependencies, release 1.0.4
- Add `sapiens` dependency
- Add `anarci` and `hmmer` dependencies
- Run pytest tests

Update BioPhi dependencies, release 1.0.4

---

recipes/bioconductor-curatedmetagenomicdata/meta.yaml
recipes/bioconductor-curatedmetagenomicdata/post-link.sh

The source archive for version 3.2.1 of bioconductor-curatedmetagenomicdata is no longer available. Updating to 3.2.3 should fix the issue. Fixes #33841.
---- …

Update bioconductor-curatedmetagenomicdata to 3.2.3

---

recipes/pggb/meta.yaml

We need the latest versions of the tools for `pggb`.

`pggb 0.3.0`: update the dependencies

---

recipes/biophi/meta.yaml

- Use redis-py instead of redis to use the conda-forge channel
- Remove dependencies that are already included by other dependencies

Simplify BioPhi requirements

---

recipes/scar/conda_build_config.yaml
recipes/scar/meta.yaml

Add recipe for [scAR](https://github.com/Novartis/scAR). It has two build versions. One for cpu and one for gpu, based on the pytorch-mutex metapackage.

Add recipe for scAR

---

recipes/r-ramclustr/meta.yaml

Update dependencies for `RAMClustR` version `1.2.3`, currently in [PR](https://github.com/bioconda/bioconda-recipes/pull/34015).

Update r-ramclustr 1.2.3 dependencies

---

recipes/calib/meta.yaml

Current packaged version gives an "invalid instruction" error. Indicating that it must use some architecture specific instructions in the build.
Current plan: 
- Rebuild
- Use `@BiocondaBot please fetch artifacts` to fetch and test artifacts. If the invalid instruction is gone, problem solved.
- If not solved -> debug the issue.

Rebuild calib

---

recipes/antismash-lite/meta.yaml

The recent [Jinja2](https://anaconda.org/conda-forge/jinja2) python module update from version 3.0.3 to 3.1.0 caused the antiSMASH `download-antismash-databases` script to fail. Specifically, it fails on `Markup` which was removed in this Jinja2 version, causing an `ImportError: cannot import name 'Markup' from 'jinja2'` (see also the [Jinja changelog](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0)).
I now specified the previously used and working Jinja2 version explicitly in the bioconda recipe.

Update antismash-lite recipe: specify jinja2 version

---

recipes/pggb/meta.yaml

This replaces https://github.com/bioconda/bioconda-recipes/pull/34408.

update pggb to v0.3.1 and its dependencies

---

azure-pipeline-master.yml
azure-pipeline.yml
recipes/verkko/build.sh
recipes/verkko/meta.yaml
recipes/verkko/run_test.sh
recipes/verkko/version.patch

Updated verkko to v1.0 release. Added rust dependency and updated snakemake version. Also added OS X compatibility.

Update verkko to v1.0 release

---

recipes/scar/meta.yaml

Update scar to 0.2.3. Restrict setuptools version.
It should replace: https://github.com/bioconda/bioconda-recipes/pull/34403

Update scar to 0.2.3

---

recipes/mokapot/meta.yaml

This PR adds `setuptools_scm` to the host requirements, so that the version is captured correctly.

Update mokapot dependencies

---

recipes/cialign/meta.yaml
recipes/cialign/run_test.py

This is a recipe for CIAlign, a tool to clean and visualise multiple sequence alignments (https://peerj.com/articles/12983/, https://github.com/KatyBrown/CIAlign).

Add CIAlign recipe to Bioconda

---

recipes/ppx/meta.yaml

This PR updates the dependencies for ppx v1.3.0. Please note that this is a PR against the `bump/ppx` branch generated @BiocondaBot in #34618, not master.
@dpryan79 - can you add me to the Bioconda org? It would be easier to modify the autobump PR directly in the future for this and other other packages I maintain.

Update ppx dependencies for 1.3.0

---

recipes/r-breakaway/build.sh
recipes/r-breakaway/meta.yaml

This is a PR to create a recipe for r-breakaway (v.4.7.9). There was a previous version (v.3.0) of this package on bioconda that was ported over to conda. Unfortunately, because `breakaway` has a bioconductor dependency (`bioconductor-phyloseq`) it is not possible to update the recipe on conda. 
See: https://github.com/conda-forge/r-breakaway-feedstock/pull/4#issuecomment-1112406403
please review & merge @bioconda/team

Create r-breakaway v.4.7.9 recipe

---

recipes/pangolin/meta.yaml

Require usher >=0.5.4 to get a recent bugfix.

Update pangolin recipe's usher version

---

recipes/10x_bamtofastq/build.sh
recipes/10x_bamtofastq/meta.yaml

A tool to convert Cell Ranger generated BAM files to FASTQ: https://github.com/10XGenomics/bamtofastq
A bedtools based bamtofastq does cannot produce R1 from these special BAM files. Hence we need this tool. Unlike cellranger it comes with MIT license.

Add 10x bamtofastq tool

---

recipes/irma/irma-check-dir-writable.patch
recipes/irma/meta.yaml

IRMA v1.0.2 performs a Bash check to see if the output directory is writable (`[ ! -w "$output_destination" ]`), however, this check fails in some circumstances (e.g. IRMA executed as part of Nextflow pipeline on a Slurm cluster). This PR adds a patch to warn the user that the output directory may not be writable rather than IRMA aborting analysis due to the failed check. 
----
* …

Patch IRMA v1.0.2 to not abort when it detects output dir not writable

---

recipes/cgranges/meta.yaml

Adds a recipe for [cgranges](https://github.com/lh3/cgranges).
----
<details>
<table>
<tr>
</tr>
<tr>
<td><code>@BiocondaBot please add …

Adding recipe cgranges

---

recipes/pfp/build.sh
recipes/pfp/meta.yaml

This PR adds a new bioinformatic recipe to bioconda. 
Adding PFP from [https://github.com/marco-oliva/pfp](https://github.com/marco-oliva/pfp). PFP is used to build compressed data structures over pan-genomics datasets.

Add pfp recipe

---

recipes/antismash-lite/build.sh
recipes/antismash-lite/meta.yaml

Adopting the changes of antismash 6.1.0 (#34096) to the antismash-lite recipe.

Update antismash-lite to 6.1.0

---

recipes/python-crypt4gh/build.sh
recipes/python-crypt4gh/meta.yaml

This pull requests adds a new recipe for python crypt4gh 1.5 package (https://github.com/EGA-archive/crypt4gh).
The package is one of the reference implementations of [GA4GH encryption standard](https://www.ga4gh.org/news/crypt4gh-a-secure-method-for-sharing-human-genetic-data/), which is adopted by EGA.
The package is currently being maintained by both @silverdaz and @blankdots , I'm a mere user of it.

Add python-crypt4gh recipe

---

build-fail-blacklist
recipes/ngless/build.sh
recipes/ngless/meta.yaml

- Install prebuilt binaries: not ideal, but working
- Use a wrapper script to point NGLess to the right dependencies
- More verbose checks
I tested locally (`bioconda-utils build --mulled-test` with and without `--docker`) and it worked well
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built packages/containers. <br />You can use this to test packages …

Upgrade & reactivate NGLess

---

recipes/staramr/meta.yaml

I fixed the issue which requires `staramr` to need older versions of pandas (https://github.com/phac-nml/staramr/issues/136). This PR updates the dependencies to remove that restriction on pandas.
---- …

Update staramr to remove restriction on pandas version

---

recipes/bioconductor-rtracklayer/meta.yaml

Fixes
```
Error: package or namespace load failed for ‘geneLenDataBase’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object '/usr/local/lib/R/library/rtracklayer/libs/rtracklayer.so':
libssl.so.1.1: cannot open shared object file: No such file or directory
Error: package ‘geneLenDataBase’ could not be loaded
Warning message:
replacing previous import ‘utils::download.file’ by ‘restfulr::download.file’ when loading ‘rtracklayer’
```
----
* New recipes not directly relevant to the biological sciences need to be submitted to …

Add openssl runtime dependency for bioconductor-rtracklayer 

---

recipes/antismash-lite/meta.yaml

Updating the meta.yml to fetch now antiSMASH v6.1.1 (according to #34688 of the antiSMASH package) .

Update antiSMASH-lite to 6.1.1

---

recipes/pymummer/meta.yaml
recipes/pymummer/temp_dir_path.patch

pymummer makes use of `tempfile.mkdtemp()` but specifies where the temp directory is made. Which does not play well with containers:
```
File "/usr/local/bin/seroba", line 88, in <module>
args.func(args)
File "/usr/local/lib/python3.8/site-packages/seroba/tasks/sero_run.py", line 19, in run
sero.run()
File "/usr/local/lib/python3.8/site-packages/seroba/serotyping.py", line 481, in run
self._prediction(assemblie_file,cluster)
File "/usr/local/lib/python3.8/site-packages/seroba/serotyping.py", line 452, in _prediction
self.sero, self.imp = Serotyping._find_serotype(assemblie_file,serogroup_fasta,self.meta_data_dict[serogroup],\
File "/usr/local/lib/python3.8/site-packages/seroba/serotyping.py", line 261, in _find_serotype
pymummer.nucmer.Runner(
File …
```

patch pymummer recipe

---

recipes/quast/meta.yaml

The latest release of `quast` appears to have corrected the issue indicated in the recipe: https://github.com/ablab/quast/commit/bc4af762a7f53176d66bd5e6c5b7d28376d28e11. I expect that Python 3.8+ builds will work successfully now.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr> …

Update quast for python 3.8+

---

recipes/gimmemotifs/conda_build_config.yaml
recipes/gimmemotifs/meta.yaml

`Gimmemotifs` contains several motif discovery tools which are (or depend on) some very large packages. 
These tools are required for _de novo_ motif discovery by `gimme motifs` and `gimme location`. Together they add around 150 packages, worth ~1.5 GB of space.
The Bioconda's Azure container is running out of memory. I do now know if this is caused by the solver, or by the package when it's loading into memory. In this PR, I'm attempting to split the load on the solver, by separating `gimmemotifs` into `gimmemotifs-minimal` and `gimmemotifs`, similar to `matplotlib` and `snakemake`. The added benefit is that packages using gimme can save a lot if _de novo_ motif discovery is not required (e.g. `ANANSE`).

split gimmemotifs recipe

---

recipes/seqan3/build.sh

Update seqan3: remove range-v3 reference: It is no longer used
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr>
<td>Upload …

Update seqan3: remove range-v3 reference

---

recipes/fastani/meta.yaml

fastANI needs `libgsl.so.25`, while the lastest `gsl` 2.7.1 provides `libgsl.so.27`. So the `gsl` version needed to be restricted to be >=2.6, <2.7.1.
```
gsl-2.7.1 => lib/libgsl.so.27
gsl-2.7   => lib/libgsl.so.25
gsl-2.6   => lib/libgsl.so.25
gsl-2.5   => lib/libgsl.so.23
```
A workaround solution:
```
mamba install gsl==2.7.0
mamba install fastani
```
---- …

Fix gsl version needed for fastANI

---

build-fail-blacklist

Adds `fishtaco` to the blacklist.
(not to be confused with (and notably less delicious than) blackened fish tacos).
This is because versions >1.0.5 cannot be redistributed via bioconda, see https://github.com/bioconda/bioconda-recipes/pull/23476.
Since the autobump code will ignore recipes in `build-fail-blacklist`, hopefully this will prevent future `fishtaco` updates from triggering autobump-created PRs.

add fishtaco to build-fail-blacklist

---

build-fail-blacklist
recipes/bedops/meta.yaml
recipes/bedops/omit-bad-mutable.patch

As described in this PR's _omit-bad-mutable.patch_, bedops contains code that fails to compile with recent versions of Clang. Fortunately none of the problematic code is actually used, so the bioconda build can work around the problem simply by removing it.
Build failure analysis reported upstream as bedops/bedops#267.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post …

Update to bedops 2.4.40 and reinstate macOS build

---

recipes/mothur/meta.yaml

**Issue observed:**
When building mothur on osx, the pattern rule(s) on Makefile line 141 is being activated by lines 119-122 prior to the actual targets and prerequisite lists. This means that the uchime target isn't executed before compilation of mothur begins, and since build.sh passes -I. instead of -I./source due to the directory change under the uchime target, files in the root /source dir aren't compiled before the subdir sources which #include them. This leads to a missing header file error which halts the build.
**Diagnosis:**
The makefile for mothur compiles sources out of order under GNU make 4.3 due to backward-incompatible changes in how pattern rules are handled. Since make 4.3 is only offered for osx on conda-forge, the same error is not observed on linux builds. To fix …

Update mothur: remove osx platform build preclusion

---

recipes/r-disprose/build.sh
recipes/r-disprose/meta.yaml

Adds `r-disprose`; this package depends on a Bioconda package with Bioconductor dependencies, hence I add it here, not on conda-forge.

Add r-disprose.

---

recipes/simplesam/meta.yaml

I've based this change on the work done for https://github.com/bioconda/bioconda-recipes/commit/d32d9d69e304638a09cbc253c648b5554c14b0b3
@daler This update should fix the simplesam build issue described in #35449.

Update: simplesam needs setuptools as run dependency

---

recipes/igblast/meta.yaml

Updates igblast from 1.17.1 to 1.19.0.
I don't think anything major changed as far as packaging goes so I've just updated the basics (version, build, URLs, and hashes) and removed one no-longer-existent license file.

Update igblast to 1.19.0

---

recipes/fqgrep/build.sh
recipes/fqgrep/meta.yaml

This adds [`fqgrep`](https://github.com/fulcrumgenomics/fqgrep) recipe to Bioconda.  This utility searches a pair of FASTQ files for reads that match a given ref or alt sequence.
---- …

Add fqgrep

---

recipes/plink2/meta.yaml

plink2 has released a new alpha version, 3.3, at the start of June:
https://www.cog-genomics.org/plink/2.0/

update plink2 to alpha 3.3, v2.00a3.3

---

recipes/pbptyper/build.sh
recipes/pbptyper/meta.yaml

This PR adds pbptyper, a tool for in silico PBP typing of S. pneumoniae assemblies
----
<details>
<summary>Please use …

add recipe for pbptyper

---

recipes/jgoslin/meta.yaml

This PR updates the jgoslin library to version 2.0.2 and JDK17. Updates to versions 2.0.0 and 2.0.1 were blocked due to the requirement of JDK17 not being available at the time.
---- …

Update jgoslin to version 2.0.2 and JDK 17

---

recipes/msmetaenhancer/meta.yaml

This PR adds [aiocircuitbreaker](https://anaconda.org/conda-forge/aiocircuitbreaker) dependency to `MSMetaEnhancer` introduced by version `v0.2.4`. This new dependency also requires Python `3.9+`.

Update MSMetaEnhancer: add aiocircuitbreaker dependency

---

recipes/mummer2circos/meta.yaml

This pull request adds a recipe for mummer2circos, a tool to generate circos plots based on mummer or blast alignments.
https://github.com/metagenlab/mummer2circos

Add mummer2circos

---

recipes/pharokka/meta.yaml

This PR updates the pharokka recipe to remove 2 large dependencies (emboss and hhsuite) that are no longer required in pharokka v1.0.0
Please ignore the autobump #36980
----
* Please post …

Update pharokka to v 1.0.0

---

build-fail-blacklist
recipes/auspice/build.sh
recipes/auspice/meta.yaml

GitHub release notes: https://github.com/nextstrain/auspice/releases/tag/v2.38.0
---- …

Update nextstrain/auspice to 2.38.0

---

recipes/gotree/build.sh
recipes/gotree/meta.yaml

This PR solves an issue in gotree build, where the package version was not properly taken into account.

Update gotree: Correction of package version in gotree build

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

The curl restriction in bioconductor data packages (i.e., those that are noarch with a curl run-time dependency) is now loosened to >=7,<8.0a0.
---- …

Update repodating patching, loosen curl pinnings in some cases

---

build-fail-blacklist
recipes/illumina-interop/meta.yaml

Upstream 1.1.26 and 1.1.27 releases were made in August (see the evidence of the autobumps in #36529), but later removed. This explains the mysteriousness observed during the recent **bulk** merge:
> \# Building tries to install 1.1.27 for some reason (despite meta.yaml specifying 1.1.25),
> \# but 1.1.27 URL does not exist
However more recently, a new upstream 1.1.27 release was made on 21 September 2022.
Hence this PR packages this new 1.1.27 release as follows: Remove the recent bulk merge's blacklisting of illumina-interop and update the SHA256 hash; bulk has already bumped the build number.
It's not ideal for 1.1.27_0 and 1.1.27_1 to be bioconda packages of different upstream releases both labelled “1.1.27”. Probably the two are not very different, but there would be some effort …

Reinstate re-released illumina-interop 1.1.27

---

recipes/unifrac-binaries/meta.yaml
recipes/unifrac-binaries/mkstemp.patch

This function is unavailable on macOS prior to version 10.12. Conda's build settings use `-mmacosx-version-min=10.9` and it appears that conda's compiler at least sometimes interprets that strictly — it was successfully built on the **master** branch six months ago (cf PR #34002), but as configured recently on the **bulk** branch (and as noted in the comment message being deleted in this PR) apparently that branch used build settings that requested an SDK that did not declare `mkostemp()` at all.
The only reason unifrac-binaries uses `mkostemp()` is to use `O_NOATIME` if available, and no macOS SDK defines that Linux-specific oflag. So we can patch as per _mkstemp.patch_ to only attempt to use `mkostemp()` if `O_NOATIME` is indeed available, and fall back to the equivalent POSIX function …

Reinstate unifrac-binaries on macOS by patching to avoid using mkostemp()

---

recipes/parse-vcf/meta.yaml

Add parse-vcf, a dependency of VASE (#37138)
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr>
<td>Upload built …

Add parse-vcf

---

recipes/igvtools/meta.yaml

This updates the version of igvtools.
As stated in the [project's site](https://software.broadinstitute.org/software/igv/download) 
>About log4j: IGV versions 2.4.1 - 2.11.6 used log4j2 code that is subject to the log4jShell vulnerability. We recommend using version 2.11.9 (or later), which removed all dependencies on log4j.
----
* PRs require reviews prior to being merged. Once …

Update igvtools to 2.14.1

---

recipes/trnascan-se/meta.yaml

Update tRNAscan-SE to 2.0.11 and bump Infernal dependency to 1.1.4 (~2 years old)

Update tRNAscan-SE to 2.0.11

---

recipes/genomepy/meta.yaml

Set the minimum python version to 3.7
Set the minimum filelock version to 3.5

minimum genomepy version

---

recipes/pangolin/meta.yaml

Pangolin's packaged snakemake will break with the current tabulate 0.9.0.
See https://github.com/cov-lineages/pangolin/issues/489 and https://github.com/cov-lineages/pangolin/pull/491.

Pin tabulate dependency in pangolin

---

recipes/pharokka/meta.yaml

Replacing #37547. Dependencies required to lock mmseqs2 version 13.4511 as pharokka databases are not optimised for the new version of mmseqs2.
---- …

update pharokka v1.1.0

---

recipes/nextstrain-cli/meta.yaml

Supersedes <https://github.com/bioconda/bioconda-recipes/pull/37627>.

Update nextstrain-cli to 5.0.0

---

recipes/fsnviz/meta.yaml

Update the requirement on crimson to version 1.1.0, to add support for the latest version of STAR-fusion to fsnviz.
----

Update fsnviz dependency crimson: add support for latest version of star-fusion output

---

recipes/hapog/meta.yaml

Hello,
this PR updates the Hapog package already included in Bioconda to the 1.3.4 version to fix a critical bug.

Update Hapog to 1.3.4

---

recipes/president/meta.yaml

This recipe is being updated to support a migration from GitLab to GitHub. I decided to update the source to pypi instead, since it makes things easier.
---- …

Update president recipe for migration to GitHub

---

recipes/wfmash/build.sh
recipes/wfmash/meta.yaml

This should improve `wfmash`'s portability.

update wfmash build

---

recipes/iphop/meta.yaml

Fixing dependency issue between perl and bioperl that prevented the recipe to be installed as of Nov 18 2022. See issue https://bitbucket.org/srouxjgi/iphop/issues/17/unsatisfiableerror-the-following

Fix dependency issue between perl and bioperl

---

recipes/fithic/meta.yaml

Update FitHiC recipe to:
- Require Python 3.2 or newer
- Remove [argparse](https://anaconda.org/conda-forge/argparse) dependency
This should make it easier to install FitHiC on environments using a recent version of Python (e.g. >=3.7), where the argparse module is already part of the stdlib, and the [argparse](https://anaconda.org/conda-forge/argparse) package is not available.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr> …

Update FitHiC recipe

---

recipes/t-coffee/build.sh
recipes/t-coffee/expose-os-detection.patch
recipes/t-coffee/meta.yaml
recipes/t-coffee/post-link.sh
recipes/t-coffee/t_coffee.sh

This build uses the developer-provided installer script to handle the complete build and installation.
closes #38346, which is a blocker for #38199, in turn needed to take care of #32576

complete build for t-coffee

---

recipes/barriers/meta.yaml

There is an issue concerning the Perl interface of the `barriers` package. It is caused by a missing `perl` host requirement in the recipe of barriers. This causes problems when the Perl version changes, as `barriers` installs a Perl module `RNA::barrier` in a version-dependent path (e.g. `$PREFIX/lib/site_perl/5.32.0/RNA/barrier.pm`). In such cases, the module cannot be loaded by Perl. Since the `perl` recipe defines a run export including a version pinning, adding it as a host requirement would prevent this issues and ensure that the Perl module can be found and loaded. This is what this PR does.

Update barriers recipe: add perl requirement

---

recipes/hybran/meta.yaml

conda and mamba sometimes tried to use python 2.7, which is not compatible. See https://gitlab.com/LPCDRP/hybran/-/issues/54
Also, the existing python<=3.7 constraint was not due to anything on the part of hybran, but rather as a workaround for https://github.com/bioconda/bioconda-recipes/issues/32576 which was recently fixed.

hybran: improve dependency constraints

---

recipes/hifiasm/meta.yaml

The autobumper seems to choke given hifiasm's mixed tag schemes (see https://github.com/bioconda/bioconda-utils/issues/834), so this manually bumps it to the latest version.

bump hifiasm

---

recipes/proteomiqon-alignmentbasedquantstatistics/build.sh
recipes/proteomiqon-alignmentbasedquantstatistics/meta.yaml
recipes/proteomiqon-alignmentbasedquantstatistics/proteomiqon-alignmentbasedquantstatistics.sh

This PR adds the tool "ProteomIQon.AlignmentBasedQuantStatistics"
Description:
MS-based shotgun proteomics estimates protein abundances using a proxy: peptides. 
Due to the acquisition method for MS2, not every peptide ion present can be identified in every run. One approach to mitigate this problem is to align information obtained from similar runs to the current run, therefore getting more quantifications. This tool scores the quantifications obtained through alignment based on peak and run properties to obtain a measurement of reliability for the alignments.

Add ProteomIQon.AlignmentBasedQuantstatistics

---

recipes/unifrac-binaries/meta.yaml

HDF5 is fully statically linked in unifrac-binaries 1.2.
Remove runtime dependencies from the recipe.
----
<details> …

Update unifrac-binaries recipe, remove hdf5 dependency

---

recipes/vcfbub/build.sh
recipes/vcfbub/meta.yaml

**Overview**
The VCF output produced by a command like `vg deconstruct -e -a -H '#' ...` includes information about the nesting of variants. With `-a, --all-snarls`, we obtain not just the top-level bubbles, but all nested ones. This exposed snarl tree information can be used to filter the VCF to obtain a set of non-overlapping sites (n.b. "snarl" is a generic model of graph bubbles including tips and loops).
`vcfbub` accomplishes a simple task: we keep sites that are the children of those which we "pop" due to their size. These occur around complex large SVs, such as multi-Mbp inversions and segmental duplications. We often need to remove these, as they provide little information for many downstream applications, such as haplotype panels or other imputation references.

Add vcfbub

---

recipes/deeptools/meta.yaml

Deeptools makes use of np.float and np.int, but those are depcrecated since 1.20 and not supported since 1.24 anymore: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations

deeptools np.float is not supported anymore

---

recipes/usher/build.sh
recipes/usher/meta.yaml

Don't skip Mac build for usher; instead, omit ripples-fast if architecture is not x86_64.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built packages/containers. <br />You can use …

Update usher: don't skip on Mac OSX

---

recipes/gff2bed/build.sh
recipes/gff2bed/meta.yaml

Add a `gff2bed` recipe to `bioconda-recipes`.
`gff2bed` is a python-only package containing two helper functions for converting GFF3-formated data to BED format.
It is found on PyPI here: https://pypi.org/project/gff2bed/
Source code is on GitLab here: https://gitlab.com/salk-tm/gff2bed/
Overview text from the readme:
[GFF3](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) and [BED](https://bedtools.readthedocs.io/en/latest/content/general-usage.html) are common formats for storing the coordinates of genomic features such as genes. GFF3 format is more versatile, but BED format is simpler and enjoys a rich ecosystem of utilities such as [bedtools](https://bedtools.readthedocs.io/en/latest/index.html). For this reason, it is often convenient to store genomic …

Add gff2bed recipe

---

recipes/pantools/meta.yaml

PanTools received a major API change and therefore we updated the major version of PanTools (to 4.0.0).

update pantools to v4.0.0

---

recipes/phate/meta.yaml

PHATE requires graphtools 1.5.3

Bump graphtools requirement

---

recipes/plastid/meta.yaml

Update plastid meta.yaml to restrict numpy version under 1.24, as plastid uses np.TYPE aliases, and they were removed. This fixes a user issue reported here https://github.com/joshuagryphon/plastid/issues/55 
----
* Please post …

Update plastid meta.yaml to restrict numpy version under 1.24

---

recipes/pantools/conda_build_config.yaml
recipes/pantools/meta.yaml

The version of BUSCO as dependency of pantools went wrong in the previous pull request for macOS specifically (#38626 and related issue #38646). Hopefully this pull request solves this by specifying specific BUSCO versions in a separate `conda_build_config.yaml`.

pantools dependency change

---

recipes/ostir/meta.yaml

This PR manually updates the recipe for OSTIR to 1.1.0 after the the automated attempt at #37884 failed.

Update OSTIR to 1.1.0

---

recipes/cooler/meta.yaml

Hi,
I am not developer of cooler but developer of pyGenomeTracks which depends on cooler. I noticed that the last cooler version = 0.8.11 is incompatible with the last version of numpy: 1.24.
I propose to fix the conda recipe of cooler version 0.8.11 but I don't know if I have the legitimacy to do that.
I wrote a issue describing why this is needed: https://github.com/open2c/cooler/issues/303
---- …

Update recipe cooler 0.8.11: restrict numpy
