.travis.yml
scripts/build-packages.py
scripts/travis-run.sh

This will avoid redundant builds as they are happening now.

Handle python versions in build script.

---

recipes/pysam/meta.yaml

The latest development pysam collected useful fixes for 0.8.3 but
hasn't gotten a release yet.

pysam: latest GitHub development (0.8.4pre)

---

README.md
recipes/pyaml/bld.bat
recipes/pyaml/build.sh
recipes/pyaml/meta.yaml
scripts/bioconductor-scraper.py

Writing the bioconductor `meta.yaml` files is getting annoying, so this PR includes a script that scrapes the bioconductor project page for a given package, downloads the tarball, and inspects the DESCRIPTION file to extract metadata and create the `meta.yaml` and `build.sh` files.
This is because I couldn't get the `conda skeleton cran` subcommand to work for Bioconductor.
To have uniformly-formatted YAML files, I'm using `pyaml` which can write a new yaml file that maintains the order of an OrderedDict. So part of the PR also includes the conda recipe for `pyaml`.

Bioconductor scraping

---

scripts/Dockerfile
scripts/update_packages.py
scripts/update_packages_docker.sh

Johannes;
I didn't want to stomp on your current Dockerfile and bioconda/bioconda-builder image so submitting this as a PR for your approval. This gets gcc and other build tools up to date on the image for automated builds, which should help a lot in resolving build issues. Let me know the best way to push this to the automatic builds if you approve.
The current Dockerfile uses the default gcc on centos5, gcc 4.1. This
will fail to build quite a few current tools. This updates the
Dockerfile to put gcc-4.8, from devtoolset-2 in the PATH by default.
It also adds recent libtool versions to get up to date autoconf,
automake and friends, avoiding the issues in #10.
Together, this should create a more pleasant build environment that
will handle most tools.
This also updates custom test scripts …

Update Dockerfile to use latest gcc/libtools

---

scripts/Dockerfile

along the lines of #54, this PR simply adds `devtools-2-gcc-gfortran` to the container.
`gfortran` is needed to build `bioconductor-genefilter` which in turn is a dependency of `DESeq2`.

add devtoolset-2-gcc-gfortran to docker container

---

recipes/bcftools/meta.yaml
recipes/bwa/meta.yaml
recipes/samtools/meta.yaml

Bumps builds for bcftools, samtools and bwa to create packages in
the Linux docker container supporting CentOS.

bcftools/samtools/bwa: CentOS 5 compatible builds

---

recipes/snakemake/meta.yaml

rpy2 dependency apparently causes a recursion depth error in conda. I have no idea why, but always pulling R only for installing Snakemake is not a good idea anyway.

Remove rpy2 dependency.

---

recipes/snakemake/meta.yaml

because it always leads to creating a 3.5 package that is not marked with a particular Python version.
Instead, we let the 27 build just fail.

Remove dependency constraint for python version (>=3.3)

---

osx-whitelist.txt
recipes/moreutils/build.sh
recipes/moreutils/meta.yaml
recipes/varscan/build.sh
recipes/varscan/meta.yaml
recipes/varscan/varscan.sh

- varscan including shell wrapper to make it easy to call without
needing to identify the jar file location.
- moreutils supplemental package. The ifne command is useful when
running mpileup and varscan in a pipe, since you can skip varscan
runs when an mpileup file is empty.

varscan variant caller + moreutils

---

scripts/Dockerfile

This makes it easier to update in the future (the container does not need to be changed).

Take build script from mounted repo instead of using a copy from within the docker container.

---

recipes/moreutils/build.sh
recipes/moreutils/meta.yaml
recipes/parallel/build.sh
recipes/parallel/meta.yaml

Removes `parallel` from moreutils, which conflicts with the more widely
used GNU parallel. Add recipe for GNU parallel.

Add GNU Parallel, avoid conflict from moreutils

---

recipes/crossmap/meta.yaml

this passed the PR tests before because py27 built but py35 didn't. This causes
the py35 build to be skipped, hopefully making things more robust in the future.

specify only py27 from within crossmap recipe

---

recipes/mosaik/linux.inc.patch
recipes/mosaik/meta.yaml

mosaik is now dynamically linked on linux. previous compile options
included “-static”. This was removed.

mosaik now dynamically linked on linux

---

recipes/star/meta.yaml

2.5.0a fixes a showstopper bug in genome generation and includes some features for controlling how chimeric junctions are called.

STAR: update to 2.5.0a.

---

recipes/crossmap/build.sh
recipes/crossmap/meta.yaml
recipes/crossmap/setup_remove_deps.diff
recipes/lumpy-sv/build.sh
recipes/lumpy-sv/lumpyexpress.config
recipes/lumpy-sv/meta.yaml
recipes/samblaster/build.sh
recipes/samblaster/meta.yaml
recipes/svtyper/build.sh
recipes/svtyper/meta.yaml

- CrossMap -- move to latest version and avoid installing the pysam and
bx-python that are internally bundled with CrossMap. These cause
issues as they can conflict with external versions, especially in
shared libraries. Now we handle these as dependencies, which are
already in bioconda.
- lumpy-sv -- add recipe, migrating from homebrew
- samblaster -- add recipe, migrating from homebrew
- svtyper -- add recipe, migrating from bcbio-conda

Lumpy SV calling ecosystem + CrossMap update

---

osx-whitelist.txt
recipes/gatk-framework/build.sh
recipes/gatk-framework/gatk-framework
recipes/gatk-framework/meta.yaml
recipes/snpeff/meta.yaml

- Add in GATK framework -- the MIT licensed part of the GATK code-base,
runnable with `gatk-framework`
- The current snpEff package (build 0) does not have updates with
wrapper script. Bump build number to recreate.

Add GATK framework (#200) + bump snpEff build

---

recipes/cufflinks/cuffmerge.python3.patch
recipes/cufflinks/meta.yaml

Cuffmerge uses some methods that are not available on python3. This commit patches on-the-fly the script replacing them with the corresponding python3 constructs.

Patch cuffmerge for python3

---

osx-whitelist.txt
recipes/bedtools/meta.yaml

The existing bedtools conda package pre-dates the CentOS build
environment, so this makes bedtools more portable. It's also built for
OSX.

bedtools 2.25.0

---

osx-whitelist.txt

Recipe seems to build and install the executables OK.  Not sure if there are eventual downstream issues, but I suppose we can remove later if so desired.

Add lumpy-sv to OSX whitelist

---

recipes/bcbio-prioritize/meta.yaml
recipes/biobambam/build.sh
recipes/biobambam/meta.yaml
recipes/manta/build.sh
recipes/manta/meta.yaml

biobambam and manta use pre-built Linux binaries. Not sure if these
will build from scratch on OSX.

New: biobambam, manta; update: bcbio.prioritize

---

.travis.yml
scripts/travis-run.sh

This was asked by Sebastian:
> So my recipe passes the tests locally with Docker but it takes 15 minutes to complete. 
> However, Travis considers as "errored" builds those that do not output something after 10 minutes.
> Has anybody found this problem? Any advice?
I think for now travis_wait will solve the issue, as it posts an output before the timeout expires (see [here](https://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received)).

Prefix builds with travis_wait to avoid timeouts.

---

recipes/p7zip/build.sh
recipes/p7zip/meta.yaml

For some reason precompiled 7z was crashing on travis-ci, to chaged to compiling it ourselves.

Changed from pre-compiled binaries to compiled code

---

osx-whitelist.txt
recipes/bcbio-variation-recall/build.sh
recipes/bcbio-variation-recall/meta.yaml
recipes/cramtools/cramtools.sh
recipes/cramtools/meta.yaml
recipes/picard/meta.yaml
recipes/picard/picard.sh
recipes/snpeff/meta.yaml
recipes/snpeff/snpeff.sh
recipes/theta2/build.sh
recipes/theta2/meta.yaml
recipes/varscan/meta.yaml
recipes/varscan/varscan.sh

- Fixes closing bracket spacing typo in java wrappers for
cramtools, picard, snpeff and varscan
- Adds new recipes for THetA2 and bcbio.variation.recall, migrated
from homebrew recipes.

New: theta2, bcbio-variation-recall. Fix: java shell scripts

---

scripts/ucsc/create-ucsc-packages.py
scripts/ucsc/template-build-fetchChromSizes.sh

- combined improvements make recipes for another 8 programs that were
not handled before
- look for and correctly handle cases where the header program name
doesn't match the description, and then resolve the correct source dir
- handle programs with no description (and give them a description
copied from FOOTER)
- support for skipping otherwise problematic programs (currently just
sizeof)
- support for custom build scripts (currently just fetchChromSizes)
This PR also includes fetchChromSizes

Ucsc recipe builder improvements

---

recipes/trimmomatic/build.sh
recipes/trimmomatic/meta.yaml
recipes/trimmomatic/trimmomatic.sh

assumes presence of “unzip” to test. trimmomatic currently lacks a
simple argument that gives a zero exit code (email is out to author
requesting one) so the recipe checks if the jar file (as a zip file) is
valid

add trimmomatic

---

recipes/muscle/build.sh
recipes/muscle/meta.yaml
recipes/muscle/osx-makefile.patch

Mac version needs its makefile to be patched to remove flag for static linking

updated MUSCLE to latest

---

scripts/build-packages.py

In order to avoid inconsistencies with Python 3.4 builds no longer being updated, this is a try to also build for Python 3.4. In the future, we could always keep the last two Python version for convenience.
When we deactivate a Python version, we should maybe remove the builds from anaconda...

Re-activate 3.4 builds.

---

recipes/glimmer/meta.yaml

So far the recipe had only a license_file, but this is not sufficient for a proper display of the license in anaconda.org.

Specify glimmer license as "Custom".

---

recipes/bcbio-prioritize/meta.yaml
recipes/bcbio-variation-recall/meta.yaml
recipes/cramtools/meta.yaml
recipes/fastqc/meta.yaml
recipes/gatk-framework/meta.yaml
recipes/oncofuse/meta.yaml
recipes/picard/meta.yaml
recipes/qsignature/meta.yaml
recipes/qualimap/meta.yaml
recipes/snpeff/meta.yaml
recipes/trimmomatic/meta.yaml
recipes/vardict-java/meta.yaml

Now that we can support multiple Java versions, there is no need anymore to keep packages that depend on the system java. People that want to use GATK (which seemingly only supports java 7) can install java=7 from bioconda. The rest can just use the most up to date java from bioconda (currently java 8).
@chapmanb I think my changes are mostly on your packages. Any objections? Also, does the gatk-framework package need java=7 as well or is it only the full GATK?

Add java-jdk dependency to all packages that need it.

---

recipes/java-jdk/7.0.91/build.sh
recipes/java-jdk/7.0.91/meta.yaml

The Zulu java distribution is already relocatable. Conda trying to make some internal .so files relocatable actually broke hardcoded relative paths. This pull request deactivates the relocation fixes done by conda.

Fix java libs

---

recipes/bioconductor-biocinstaller/meta.yaml
recipes/gatk-framework/meta.yaml

- Bump biocinstaller to latest point release to avoid in-progress
updates when using it.
- gatk-framework -- use fixed Java 7

Update: biocinstaller and gatk

---

recipes/jamm/meta.yaml
recipes/jamm/setpath.patch

By default JAMM.sh uses the CWD to search for R/Perl scripts.
Change to using placehold prefix so the search path is set to
${PREFIX}/bin at install time.

Add placeholder prefix in JAMM.sh

---

osx-whitelist.txt
recipes/bcbio-rnaseq/build.sh
recipes/bcbio-rnaseq/meta.yaml

https://github.com/roryk/bcbio.rnaseq
This is used for generating a preliminary report from a `bcbio-nextgen` RNAseq run.

Add bcbio-rnaseq.

---

osx-whitelist.txt
recipes/arrow/build.sh
recipes/arrow/meta.yaml
recipes/botocore/build.sh
recipes/botocore/meta.yaml
recipes/fastqc/java_xms.patch
recipes/fastqc/meta.yaml
recipes/requests-toolbelt/build.sh
recipes/requests-toolbelt/meta.yaml

- Set heap (Xms) for fastqc runs. Fixes chapmanb/bcbio-nextgen#1163
- Additional python deps for bcbio, awscli and bioblend

Fix fastqc memory; additional bcbio python deps

---

recipes/trinity/2011_11_26/RunButterfly.cc.patch
recipes/trinity/2011_11_26/Trinity.pl.patch
recipes/trinity/2011_11_26/build.sh
recipes/trinity/2011_11_26/meta.yaml
recipes/trinity/meta.yaml

This adds a recipe for an older version of Trinity (2011-11-26) that
uses an older assembly algorithm that works better with highly diverse
viral genomes. It also restructures the regular trinity build script a
bit to have the Trinity files in a subdir of $BIN to reduce likelihood
of conflicts

add older Trinity

---

osx-whitelist.txt
recipes/prodigal/build.sh
recipes/prodigal/meta.yaml

The executable was not being moved to `$PREFIX/bin` despite passing tests.

Fixes `prodigal`

---

osx-whitelist.txt
recipes/awscli/build.sh
recipes/awscli/meta.yaml
recipes/bioblend/build.sh
recipes/bioblend/meta.yaml
recipes/fadapa/build.sh
recipes/fadapa/meta.yaml
recipes/logbook/build.sh
recipes/logbook/meta.yaml
recipes/tabulate/build.sh
recipes/tabulate/meta.yaml

- Includes awscli, bioblend, fadapa, logbook and tabulate

Additional python dependencies for bcbio porting

---

osx-whitelist.txt
recipes/bioconductor-graph/Makevars.patch
recipes/bioconductor-graph/meta.yaml

I was getting errors building `bioconductor-graph` on OSX.  The problem was that during the build, the R installer moves `graph.so`. Somehow conda knew about the original `graph.so` and tried to fix the prefix of that file, but couldn't find it. Patching `src/Makevars` on OSX to copy instead of move fixed the problem.
The official Bioconductor build reports for OSX look fine; I think this is a conda-specific issue. I'm not sure how to handle special cases like this in the bioconductor helper scripts.

Osx bioconductor graph

---

recipes/crossmap/build.sh
recipes/crossmap/meta.yaml
recipes/r-r.utils/bld.bat
recipes/r-r.utils/build.sh
recipes/r-r.utils/meta.yaml

CrossMap egg PKG-INFO file was not readable by non-install users
causing errors when installed by root. Additional R package dependency
trees for bcbio.

Fix strange permission errors in CrossMap eggs

---

recipes/bcbio_monitor/meta.yaml
recipes/bioconductor-degreport/meta.yaml
recipes/bx-python/meta.yaml
recipes/geneimpacts/meta.yaml
recipes/hall-lab-svtools/meta.yaml
recipes/htseq/meta.yaml
recipes/ipython-cluster-helper/meta.yaml
recipes/pyutilib/meta.yaml
recipes/r-ks/bld.bat
recipes/r-ks/build.sh
recipes/r-ks/meta.yaml
recipes/r-pscbs/bld.bat
recipes/r-pscbs/build.sh
recipes/r-pscbs/meta.yaml
recipes/vawk/meta.yaml

- Skips py3 builds for packages that don't work correctly there. Thanks
to @daler for detecting problem in #498
- Add PSCBS and ks packages for R
- Add nozzle dependency to degreport

Fix builds failing on py3 (#498). More R packages

---

recipes/star/meta.yaml

2.5.0a and b hang during genome generation on some genomes.

Update STAR to 2.5.0c.

---

recipes/python-levenshtein/meta.yaml

Has some C extensions, so should have explicit python dependency.

Add python requirement for levenshtein

---

README.md
osx-whitelist.txt
recipes/google-api-python-client/meta.yaml
scripts/build-packages.py

As discussed in #498, this is a simple change to build-packages.py to require all non-skipped recipes to successfully build. I added a fix to google-api-python-client to only build on py27 so that it passes. 
I updated the readme to reflect these changes. While I was there, added more info about the build system, more details on prerequisites, examples of skipping Python versions, and some cosmetic tweaks.

All builds must pass

---

osx-whitelist.txt
recipes/bcbio-nextgen-vm/build.sh
recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/build.sh
recipes/bcbio-nextgen/meta.yaml

Migrates bcbio and bcbio-vm installation to be conda only
with all packages supplied via bioconda.

New: bcbio-nextgen-vm, update bcbio to conda install

---

README.md

add note to README.md to mention how to enter a bash shell within the build container
Sometimes it is helpful to debug build issues within the docker container by manually calling conda build within a bash shell for the container. This PR adds a note to the readme instructing how to do this, since the default container entrypoint is overridden by the bioconda build script.

add note to README.md to mention how to enter a bash shell within the build container

---

recipes/scikit-bio/build.sh
recipes/scikit-bio/meta.yaml

The 0.2.3 version of scikit-bio from the default channel
only includes up to NumPy 1.9.

Add recipe for NPY 1.10 build of scikit-bio 0.2.3

---

recipes/bioconda_curl/build.sh
recipes/bioconda_curl/meta.yaml
recipes/pybigwig/0.1.11/build.sh
recipes/pybigwig/0.1.11/meta.yaml
recipes/pybigwig/build.sh

Update pyBigWig to version 0.2.1. Additionally, add "bioconda_curl", which replaces the problematic version of curl that comes with anaconda (as best as I can tell, this fixes https://github.com/ContinuumIO/anaconda-issues/issues/72, at least under Ubuntu).

Bioconda_curl + pyBigWig-0.2.1b

---

osx-whitelist.txt

It builds (locally, tested) correctly and it is needed to index compressed VCF files with tabix.

Add pgbzip to osx whitelist

---

osx-whitelist.txt
recipes/curl/build.sh
recipes/curl/meta.yaml
recipes/pybigwig/0.1.11/meta.yaml
recipes/pybigwig/build.sh
recipes/pybigwig/meta.yaml

@johanneskoester Can you have a look? This will hopefully work and is now using the same version of curl that comes with the most recent version of anaconda (this will hopefully avoid other issues).

Rename bioconda curl

---

scripts/build-packages.py

Currently, all recipes that have a skip instruction for a certain python version are build over and over because the message from conda build is not parsed correctly. This PR should provide a significant speed up by skipping them as well.

Also skip recipe if a certain configuration has been marked as skip in the meta.yaml.

---

osx-whitelist.txt

Also resort the osx-whitelist file, resulting in minor changes.
Both svgwrite and pyparsing are pure-python modules so there should be no problems with OSX compatibility.

Add svgwrite and pyparsing to osx-whitelist.

---

recipes/oligotyping/bld.bat
recipes/oligotyping/build.sh
recipes/oligotyping/meta.yaml

Oligotyping is a computational method that helps microbial ecologists to investigate concealed diversity within their operational taxonomic units at an extremely precise level. 
The recipe is created using the pypi skeleton with added non-python dependancies.

Add recipe for oligotyping

---

recipes/jellyfish/1.1.11/build.sh
recipes/jellyfish/1.1.11/meta.yaml

The current version of jellyfish (2) is not backwards compatible with jellyfish1.

jellyfish1-1.1.11

---

recipes/ipython-cluster-helper/meta.yaml

Adds support for UGE schedulers.

Bump ipython-cluster-helper to 0.5.1.

---

scripts/build-packages.py

This should fix issue #597. The overhead for already existing and skipped packages plus download of the docker container is about a minute now. The rest will be only compile time of the new recipe/version.

Use conda-build from master to solve issue #597 until a new version is released.

---

recipes/diamond/build.sh
recipes/diamond/cmake_patch
recipes/diamond/meta.yaml

Accelerated BLAST compatible local sequence aligner.
Includes patch from https://github.com/bbuchfink/diamond/issues/24.
Also includes a general workaround for GCC 5 dual ABI incompatibility. The situation is not great since the gcc-5/clang incompatibility bug has not been solved yet, but I'm hoping that the anaconda team will do a full rebuild of C++ pkgs with GCC 5 dual ABI and assume everything in conda is gcc.

diamond 0.7.10

---

recipes/arvados-cli/build.sh
recipes/arvados-cli/meta.yaml
recipes/pindel/build.sh
recipes/pindel/meta.yaml

- Update pindel to latest release, which uses htslib instead of older
samtools. New version has better support for complex alleles:
http://www.nature.com/nm/journal/v22/n1/full/nm.4002.html
- Add support for Arvados command line interface

Update: pindel, New: arvados-cli

---

recipes/perl/build.sh
recipes/perl/meta.yaml

The gcc 4.8.5 via the devtoolset-2 RPMs used previously to build Perl
has backports from RH from the GCC 4.9 series.  This includes the
`-fstack-protector-strong` option introduced in 4.9.  The Perl `Configure`
sees this option as supported and adds it to the default compiler options.
When building Perl modules with shared libraries, specifying `gcc` in the
build requirements pulls in the gcc from the default channel.  The build
then fails as this is an unpatched version and that option is not
supported. Using the conda gcc, `Configure` uses `-fstack-protector`
instead and avoids the issue.

Change Perl build to use Conda gcc

---

osx-whitelist.txt
recipes/perl-app-cpanminus/meta.yaml
recipes/perl-bio-db-sam/meta.yaml
recipes/perl-bioperl/meta.yaml
recipes/perl-data-uuid/meta.yaml
recipes/perl-encode-locale/meta.yaml
recipes/perl-file-sharedir-install/meta.yaml
recipes/perl-file-sharedir/meta.yaml
recipes/perl-gd/meta.yaml
recipes/perl-ipc-system-simple/meta.yaml
recipes/perl-lwp-simple/meta.yaml
recipes/perl-module-build/meta.yaml
recipes/perl-vcftools-vcf/meta.yaml
recipes/perl-xml-parser/meta.yaml

Battenberg perl requires threaded perl but libraries not built
for it. Move to perl-threaded as default.

Perl: move dependencies to perl-threaded

---

recipes/ropebwt2/build.sh
recipes/ropebwt2/meta.yaml

RopeBWT2 is an tool for constructing the FM-index for a collection of DNA sequences.

Add ropebwt2

---

recipes/rapmap/build.sh
recipes/rapmap/meta.yaml

The build results in a broken binary when you try to do anything real with it, so for now use the prebuilt one.

Use prebuilt binary for Rapmap.

---

recipes/perl-dbd-mysql/meta.yaml
recipes/perl-gdgraph/meta.yaml
recipes/perl-math-cdf/meta.yaml
recipes/perl-pdf-api2/meta.yaml
recipes/perl-scalar-list-utils/meta.yaml
recipes/perl-set-intervaltree/meta.yaml
recipes/perl-statistics-descriptive/meta.yaml
recipes/perl-sub-uplevel/meta.yaml
recipes/perl-time-hires/meta.yaml
recipes/perl-uri/meta.yaml

Second and final rounds of perl dependencies moving to perl-threaded.
Final step in transition is a upcoming PR with high level packages
using Perl.

Perl: move to threaded libraries, dependencies 2

---

recipes/fastq-screen/meta.yaml
recipes/igblast/meta.yaml
recipes/jamm/meta.yaml
recipes/mirdeep2/meta.yaml
recipes/mugsy/meta.yaml
recipes/perl-sanger-cgp-battenberg/build.sh
recipes/perl-sanger-cgp-battenberg/meta.yaml
recipes/perl-threaded/build.sh
recipes/perl-threaded/meta.yaml
recipes/prinseq/meta.yaml
recipes/protrac/meta.yaml
recipes/snippy/meta.yaml
recipes/star-fusion/meta.yaml
recipes/variant-effect-predictor/meta.yaml
recipes/vcftools/meta.yaml

- Finalizes move of packages to use perl-threaded instead of perl,
adding all final top level tools that use perl and libraries. (#722)
- Use conda gcc with perl-threaded to enable use for module library
builds (#735). Requires one final upcoming PR to re-build library
dependencies including gcc.

Perl: move to threaded, top level tools (step 3)

---

recipes/kraken-all/meta.yaml

Adds jellyfish1 dep for kraken-all to support building databases.
This is based off of #389, since `jellyfish` is an optional dependency - the best way to go about this seems to be a metapackage that installs it.

Add kraken-all metapackage that includes jellyfish dep.

---

recipes/chanjo/bld.bat
recipes/chanjo/meta.yaml

Hi,
I hope this is the way you want to handle version upgrades
This is a minor release so the primary API doesn't change but the "load" command is now significantly faster and the bundled resources have been updated :smiley_cat:

update chanjo to v3.3.0

---

recipes/rsem/build.sh
recipes/rsem/meta.yaml

- update list of executables
- update test to include actual test of parameters
- pass missing parameters from wrappers to binaries

Upgrade RSEM to 1.2.28

---

recipes/gevent/bld.bat
recipes/gevent/build.sh
recipes/gevent/meta.yaml

This recipe is required as a dependencies for other biologically-oriented packages to be added (e.g. bioservices). conda provides gevent version 1.0.2, which is python2-compatible only. Here, we provide a recipe for py2k and py3k. One issue with the gevent recipe is that the newly py3k  version of gevent introduces a syntax that is not py2k compatible. although this is not an issue for pip installation where the syntax error is ignored, this causes trouble for bioconda build process. Consequently, the recipe provided uses one package for python 2 and another package for python 3. The version of the python 2 package is gevent 1.0.2 ( as in the official conda package) whereas the python3 version is the latest version (1.1.4).

add a new recipe for geven

---

recipes/bowtie2/meta.yaml

Bumping the bowtie2 version. 
Current recipe only contains linux binaries so it should be swapped to source code in the future.

Bump bowtie2 version

---

recipes/samtools/0.1.19/meta.yaml

This was on Arch Linux
```
samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```
Manually installing ncurses fixed the issue

samtools 0.1.19 requires ncurses

---

recipes/spectacle/Spectacle.sh
recipes/spectacle/build.sh
recipes/spectacle/download_spectacle_data.sh
recipes/spectacle/meta.yaml
recipes/spectacle/run_test.sh
recipes/spectacle/shebang.patch

Add [Spectacle](https://github.com/jiminsong/Spectacle) [(paper)](http://genomebiology.com/2015/16/1/33)
- Example data are stripped from the recipe, and a `download_spectacle_data.sh` script is included as noted in the `extra -> notes` field of `meta.yaml`
-  `run_test.sh` tests the shell wrapper (similar to the one used by ChromHMM), the Python wrapper that ships with Spectacle, and the download script
- The Python wrapper is converted with `2to3` for py3 compatibility.

add spectacle

---

osx-whitelist.txt
recipes/avro/build.sh
recipes/avro/meta.yaml
recipes/isodate/build.sh
recipes/isodate/meta.yaml
recipes/keepalive/build.sh
recipes/keepalive/meta.yaml
recipes/shellescape/build.sh
recipes/shellescape/meta.yaml

Start of dependency tree: avro, isodate, keepalive, shellescape

New dependencies for cwltool and cwl-runner

---

recipes/cobra/meta.yaml

The previous version did not compile the LP solver bindings due to cython being missing from the build requirements in the meta.yaml. This pull request adds cython and yields a working cobra build.
Additionally the recipe gets bumped to the latest version and I fixed a typo in the description.

Fix for "no LP solvers" error in cobra

---

recipes/easydev/meta.yaml

no_arch causes trouble building bioservices

easydev: put the no_arch to False

---

osx-whitelist.txt
recipes/avro-python3/bld.bat
recipes/avro-python3/build.sh
recipes/avro-python3/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/typing/bld.bat
recipes/typing/build.sh
recipes/typing/meta.yaml

typing and avro-python3 are new dependencies for the latest
schema-salad release for python 3 support.

New: typing, avro-python3; updated: bcbio

---

recipes/gnuplot/meta.yaml
recipes/libgd/meta.yaml

* Use a higher version number to favor bioconda's libgd version over the one in conda's default channels
* Verify that gnuplot actually supports png terminals

[MRG] gnuplot: fix png support

---

recipes/alignlib-lite/meta.yaml

libgcc as runtime dep instead of gcc

Alignlib lite

---

recipes/gnuplot/build.sh
recipes/gnuplot/meta.yaml
recipes/libgd/build.sh
recipes/libgd/meta.yaml

Sorry for keeping you busy here. I just realized that the X11 headers / libs are optional on OS X. Therefore we have to explicitly forbid linking against them or we risk library lookup failures for some users.

[MRG] gnuplot: do not link against x11 libraries

---

recipes/gnuplot/build.sh
recipes/gnuplot/meta.yaml

Upon merge travis complained about not being able to resolve the symbol ` ___stack_chk_guard`. This is surprising - as far as I understood it should not be required anyway.
```
+gnuplot -e 'set terminal dumb; set style histogram; p '\''test-data.txt'\'''
dyld: Symbol not found: ___stack_chk_guard
Referenced from: /anaconda/envs/_test/bin/gnuplot
Expected in: /anaconda/envs/_test/bin/../lib//libtiff.5.dylib
in /anaconda/envs/_test/bin/gnuplot
/anaconda/conda-bld/test-tmp_dir/run_test.sh: line 3: 14162 Trace/BPT trap: 5       gnuplot -e "set terminal dumb; set style histogram; p 'test-data.txt'"
Using Anaconda Cloud api site https://api.anaconda.org
```
Here I am explicitly disabling the stack protector and see if this resolves the issue.

[MRG] gnuplot: relaunch build after fixing the conda-build-1.19.1 problems

---

recipes/sambamba/meta.yaml

sambamba mpileup “relies on external tools and acts as a multi-core
implementation of samtools and bcftools” This adds samtools and
bcftools as runtime dependencies of sambamba so multicore mpileup via
sambamba can be used

sambamba: add samtools and bcftools as runtime dependencies

---

recipes/pysam/meta.yaml

So pysam dynamically links to htslib and also calls samtools.  For these reasons, we should probably hard-pin the versions to ensure compatibility.  
@sebastian-luna-valero  what do you think?  I worry that people could get strange results if we don't force the recipe to use all the same versions.

Hardcode htslib and samtools versions in pysam

---

recipes/rapmap/build.sh
recipes/rapmap/meta.yaml

Includes a fix to make the compiled binary more universal.

Bump RapMap to 0.2.0.

---

recipes/hisat2/build.sh
recipes/hisat2/meta.yaml

Does what it says on the box. A possible breaking change for downstream consumers, 2.0.2 changes the names of some of the python scripts, prefixing them with `hisat2_`

Bump hisat2 to 2.0.2.

---

recipes/arvados-cwl-runner/meta.yaml
recipes/arvados-python-client/meta.yaml
recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/bcbio-prioritize/meta.yaml
recipes/cwltool/meta.yaml
recipes/schema-salad/meta.yaml

- Updates requirements for running bcbio CWL locally and on Arvados
to avoid issues with large javascript parsing.
- Updates bcbio-prioritize to fix problems with large VCF inputs.

Update: CWL support, bcbio and bcbio-prioritize

---

recipes/varscan/meta.yaml

The 2.4.1 release provides a bug fix for 2.4.0 reducing the false
positive rate by ~10x.

Update: varscan to 2.4.1

---

recipes/bowtie2/build.sh
recipes/bowtie2/meta.yaml

- Fix build problem: bowtie2 not installed on previous version.
- Updates bowtie2 to the latest release 2.2.8
- Adds OSX target using pre-compiled binaries
- Fixes build issues where bowtie2 was not installed with switch to
compilation on Linux. @bgruening, I'm not sure why the build file
changed in your update but I put it back to the previous approach
which works with the manual build.

bowtie2: bump to 2.2.8; fix build issues; add OSX

---

recipes/gnuplot/meta.yaml
recipes/libgd/meta.yaml

Unfortunately, the cool hack using the `.bioconda` postfix in the dependency string does not work since >=conda-4.0.4. And the developers do not intend to bring back the old functionality. Therefore a different strategy is necessary now.
In order to shadow the broken libgd version in continuumio's default channel, the `post` postfix is the only solution I can think of at the moment.
The solution is not as nice as the previous one, but I don't see any dramatic downsides. After all the recipe offered by continuumio is broken anyway.
See https://github.com/conda/conda/issues/2297 for a reference to the discussion.

gnuplot: removed libgd version hack

---

recipes/arvados-cwl-runner/build.sh
recipes/arvados-cwl-runner/meta.yaml
recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/cwltool/meta.yaml
recipes/vardict-java/meta.yaml

- bcbio: enable CWL runs without variant_regions
- bcbio-vm: improve update procedure
- arvados-cwl-runner, vardict-java, cwltool: bump to latest releases

Updates: bcbio, CWL runners and VarDict

---

recipes/hap.py/build.sh
recipes/hap.py/meta.yaml

graph based VCF validation tool from the Illumina team, used in GA4GH
validation working group comparisons

hap.py: new recipe (0.2.9)

---

recipes/raxml/7.3.0/build.sh
recipes/raxml/7.3.0/meta.yaml

Support for an older version of raxml as required by qiime
#1118

raxml 7.3.0

---

recipes/plink2/build.sh
recipes/plink2/meta.yaml

Plink2 has odd versioning. The betas are called plink 1.9, presumably 
the final version will be plink 2. The sub-version comes from the 
homepage, the builds from this changeset are called beta 3.35.

Recipe for plink2.

---

recipes/star-fusion/build.sh
recipes/star-fusion/meta.yaml

This PR updates STAR-Fusion and solves https://github.com/bioconda/bioconda-recipes/issues/1005. In order to solve that issue, the corresponding utilities need to depend on `STAR` itself, `bowtie-build` and `gmap_build` as can be seen here:
https://github.com/FusionFilter/FusionFilter/blob/14f87fbe2d93cf5aa7b4bbfe6bf1df203c92b03d/prep_genome_lib.pl#L123

STAR-Fusion: added utilities + dependencies (STAR, gmap_build, bowtie-build)

---

scripts/build-packages.py

This allows to pin the boost version in recipes using jinja2 templating. E.g., you can write
```
package:
name: mypackage
version: 0.1
build:
number: 0
string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}
requirements:
build:
- boost >=1.55,{{CONDA_BOOST}}*
run:
- boost {{CONDA_BOOST}}*
```

Refactor dependency version pinning, include boost.

---

recipes/cnvkit/meta.yaml

The upstream CNVkit license is Apache 2.0, see: https://github.com/etal/cnvkit/blob/master/LICENSE

Change CNVkit license to Apache 2.0

---

recipes/limix/build.sh

I fixed that on Limix setup.py.

I believe the OSX workaround is not needed anymore

---

recipes/abyss/meta.yaml

google-sparsehash is a build dependency only.

abyss: Remove google-sparsehash from run

---

recipes/arvados-cwl-runner/meta.yaml
recipes/arvados-python-client/meta.yaml
recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/bcbio-variation-recall/meta.yaml
recipes/cwltool/meta.yaml

- bcbio-variation-recall: Support genotype qualities for FreeBayes
recalls
- bcbio-nextgen: Remove requirement on scikit learn (fixes
chapmanb/bcbio-nextgen#1337)
- bcbio-vm: Fix update to include arvados dependencies
- New versions for arvados-cwl and cwltool

Updates: bcbio and CWL

---

recipes/fastqc/meta.yaml

Somehow I lost this option in the meta.yaml file before I merged.  Fixing that.

Restore the build.skip = False node in fastqc 0.11.5 meta.yaml

---

recipes/trinity/date.2011_11_26/meta.yaml

Fixing some more of trinity a la #1312

trinity: 2011 version requires java 1.6.

---

recipes/trinity/date.2011_11_26/Trinity.pl.patch
recipes/trinity/date.2011_11_26/meta.yaml

java version specified as minimum version, and trinity patched to allow java or openjdk

Set trinity java version

---

recipes/hap.py/build.sh
recipes/hap.py/meta.yaml

High level scripts re-locate themselves using __file__ to
enable import of Python libraries, and this allows them
to resolve symlinks.

hap.py: allow symlinks to runner scripts

---

recipes/arvados-cwl-runner/build.sh
recipes/arvados-cwl-runner/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/cwltool/meta.yaml

Enables CWL runs using bcbio_vm without needing full bcbio install

Update: bcbio and CWL runner dependencies

---

recipes/cgat-report/meta.yaml
recipes/matplotlib-venn/meta.yaml
recipes/quast/meta.yaml
recipes/sphinxcontrib-programoutput/meta.yaml

Omitting this causes wrong build strings.

Add Python as runtime requirement of quast and cgat-report.

---

recipes/flash/meta.yaml

I've confirmed that this recipe [flash] builds fine on osx64.  Per issue #1012, can we remove the skip: True for [osx]?

remove skip:True [osx] for recipe flash

---

README.md
scripts/build-packages.py
scripts/env_matrix.yml
scripts/travis-run.sh

This PR generalizes the pinning mechanism. In the future, we can add new environment variables for pinning recipes using `scripts/env_matrix.yml`. Our build script will automatically build all combinations. It won't build a recipe twice if it is not affected by a particular combination. E.g., non-python recipes will be build only once, although we have two python versions in our matrix.
Still, I think we should keep the number of parallel versions minimal. I would suggest to let Python be the only case where we support more than one version.

Generalize dependency pinning using an environment variable matrix

---

scripts/build-packages.py

Sort each connected component lexicographically (this fixes a bug causing subdag order to differ between runs). Don't use connected components in testonly mode (resulting subdags can become too big).

Two fixes for subdag parallelization.

---

recipes/prank/build.sh
recipes/prank/meta.yaml

added recipe for prank multiple sequence aligner

---

recipes/perl-velvetoptimiser/MANIFEST
recipes/perl-velvetoptimiser/Makefile.PL
recipes/perl-velvetoptimiser/build.sh
recipes/perl-velvetoptimiser/meta.yaml
recipes/perl-velvetoptimiser/perl_path.patch

This package isn't on CPAN, nor does the source repo include the needed distribution files.  In order for the install to be done in the standard way, the build recipe first creates a barebones distribution via `h2xs`.  Then the usual method can be used for the final build and install.

Add recipe for VelvetOptimiser 2.2.5

---

recipes/idr/meta.yaml

Disabling idr (mismatching md5) in order to continue debugging build issues (xref #1491)

temporarily disable idr; see #1491

---

recipes/bowtie2/2.2.5/build.sh
recipes/bowtie2/2.2.5/meta.yaml
recipes/bowtie2/meta.yaml

bowtie2 binaries were not found because they were not moved to `bin/` subdirectory.
Remove llvm requirement since OSX zip file contains already compiled binaries.

Sync Bowtie2 2.2.5 recipe with 2.2.8 one

---

recipes/salmon/build.sh
recipes/salmon/meta.yaml

- Download and compile against tcmalloc to avoid segfault problems:
Fixes chapmanb/bcbio-nextgen#1376
- Install pre-built OSX binary

Salmon: update to avoid NFS malloc bug

---

scripts/Dockerfile

I think we all agreed to remove the development packages from our build infrastructure.
This PR uses parts of https://github.com/bioconda/bioconda-recipes/pull/1201 to remove zlib, bzlib and ncurses development packages. It will keep GCC for the time being.
ping @bioconda/core

Remove zlib-dev, bzlib-dev and ncurses-dev

---

recipes/krona/2.5/build.sh
recipes/krona/2.5/meta.yaml
recipes/krona/2.5/post-link.sh
recipes/krona/2.6/build.sh
recipes/krona/2.6/meta.yaml
recipes/krona/2.6/post-link.sh

Added symlink so that updateTaxonomy.sh is accessible to user in PATH. 
Also, the default taxonomy directory is being left out during packaging, presumably b/c it is empty.  The placeholder file makes sure it is present for user after install.
I think it would be helpful if a message is emitted to user upon installation of this package.  I guess the user won't see the echo message from the build.sh script.  What is the better way to do this?  Does the meta.yaml support some kind of  "message" tag for this purpose?

updateTaxonomy.sh improvements

---

recipes/perl-exporter-tidy/bld.bat
recipes/perl-exporter-tidy/build.sh
recipes/perl-exporter-tidy/meta.yaml
recipes/perl-proc-fork/bld.bat
recipes/perl-proc-fork/build.sh
recipes/perl-proc-fork/meta.yaml

I'm working on adding the dependencies for iDES (https://cappseq.stanford.edu/). See also: https://github.com/bioconda/bioconda-recipes/pull/1540. If preferred I can make a single PR with all the dependencies.
- Make a recipe for `Proc::Fork` version 0.804
- Make a recipe for the dependency of `Proc::Fork`, `Exporter::Tidy` version 0.08
Suggested reviewers: @bioconda/core

Add perl-proc-fork Proc::Fork version 0.804

---

GUIDELINES.md

Update GUIDELINES.md [ci skip]

---

recipes/autoconf/meta.yaml
recipes/datamash/1.0.6/meta.yaml
recipes/datamash/1.1.0/meta.yaml
recipes/gawk/meta.yaml
recipes/gettext/meta.yaml
recipes/glpk/meta.yaml
recipes/m4/meta.yaml
recipes/ocrad/0.21/meta.yaml
recipes/parallel/meta.yaml

to download gnu software we should use the ftpmirror.gnu.org url because it will automatically
pick the closest mirror on-the-fly.
I don't think I need to bump the build number in this case, @bioconda/core comments ?

use gnu ftpmirror url

---

scripts/ucsc/include.patch

Fixes the include.patch generated by ucsc utils helper script, see #1606

fix include.patch, xref #1606

---

recipes/crossmap/meta.yaml

This is an update for CrossMap which uses samtools  under the hood. Samtools has changed certain arguments in 1.0.0 and are incompatible with CrossMap, which is the reason I fixed the version.

CrossMap: added samtools dependency

---

recipes/picard/picard.sh

Previously java would be set if JAVA_HOME was UNset, which I assume was not the intended behaviour. This would cause picard to fail if the system installation was not the correct version to use. 
For me, picard 2.3.0 used `/bin/java` which was version 1.7.x instead of the version installed by conda.

fix logic in selecting java version

---

recipes/vphaser2/build.sh
recipes/vphaser2/meta.yaml

previously, libgomp.1.dylib provided by vphaser2 was copied into the
conda env lib/, but it can conflict with the dylib provided by libgcc,
which supports different symbols

vphaser2 dylib isolation

---

recipes/arvados-python-client/meta.yaml

arvados-python-client requires a specific version of pycurl and default
install pulls in more recent version. Thanks to @lijiayong

arvados-python-client: ensure proper pycurl version

---

recipes/gatk/build.sh
recipes/gatk/gatk-register.sh
recipes/gatk/gatk.sh
recipes/gatk/meta.yaml

The license for the full version of GATK prevents it from being redistributed. This adds a recipe for a GATK package that provides the commands “gatk” and “gatk-register”. The former is a thin wrapper around the gatk.jar file, and the latter is an installer that copies a user-supplied GenomeAnalysisTK.jar file (or unpacked tar.bz2 file) to the conda environment. It includes helpful messages that instruct the user on what to do.

add (installer for) gatk-protected (full, license-restricted GATK)

---

recipes/circexplorer/meta.yaml

* Fix version info using real version of CIRCexplorer
* Upgrade from CIRCexplorer 1.1.8 to 1.1.9

Fix version info and update from 1.1.8 to 1.1.9 for CIRCexplorer

---

recipes/bcbio-prioritize/meta.yaml
recipes/gatk-framework/gatk-framework
recipes/gatk-framework/meta.yaml
recipes/gatk/meta.yaml

- Updates gatk-framework and gatk for 3.6 release, which requires Java 8
(chapmanb/bcbio-nextgen#1420)
- Update bcbio-prioritize with fixes for VCF and BED annotations.

Update: GATK for 3.6 and bcbio-prioritize

---

recipes/gatk/gatk-register.sh
recipes/gatk/meta.yaml

Ensures gatk-register uses the anaconda install java so it gets the
correct version, otherwise can fail with Java errors if 1.7 in
PATH before anaconda. (cc @tomkinsc)

gatk: Use anaconda java for gatk-register

---

recipes/aria2/build.sh
recipes/aria2/meta.yaml
recipes/c-ares/build.sh
recipes/c-ares/meta.yaml
recipes/libssh2/build.sh
recipes/libssh2/meta.yaml

This adds the `aria2` package, and needed dependencies `libssh2` and `c-ares`.  
Question for @bioconda/core - is there a recommended way to do testing for library only packages?  The `libssh2` and `c-ares` packages are both library-only.  What I've done previously is just test to see if the main libs and header files exist, so I did that here as well.  Just wondering if there's an alternate way that's preferred?

Aria2 1.23.0

---

recipes/bcbio-nextgen/meta.yaml
recipes/ipython-cluster-helper/meta.yaml
recipes/snpeff/meta.yaml

- ipython-cluster-helper fixes issue on SGE.
- snpeff update to development 4.3 version
- bcbio fixes issues for CWL generation and parallelization

Updates: ipython-cluster-helper, snpeff, bcbio

---

recipes/novoalign/build.sh
recipes/novoalign/meta.yaml
recipes/novoalign/novoalign-license-register.sh

Novoalign expects a license file, “novoalign.lic” to coexist in the same directory as the main novoalign binary (for multi-threaded operation. single-thread operation is allowed without a license file). This adds a script, `novoalign-register-license`, to copy in a license file to the conda `bin/` directory.

add script to copy novoalign license file to conda bin/

---

GUIDELINES.md

Adds a recipe to the list of uncommon examples that has a post-link.sh script (post-install hook)

add example recipe that has a post-link.sh script (krona)

---

GUIDELINES.md

Adds a section to the developer guidelines mentioning pre/post-install scripts. @bioconda/core: Does it make sense to add this?

add section to guidelines on post-install hooks

---

recipes/gatk/meta.yaml
recipes/gatk/post-link.sh

add post-link script to gatk package to call gatk-register and alert the user after install that additional manual actions are required before gatk is fully installed (the user must download a licensed copy of gatk and pass its path to gatk-register)

gatk post-link script for user alert

---

recipes/freebayes/build.sh
recipes/freebayes/meta.yaml
recipes/simple_sv_annotation/meta.yaml
recipes/snpeff/meta.yaml

- FreeBayes update to latest development with fixes for gVCF output
(correct reference bases) and VCF-specification ready GQ values
(integers)
- snpEff update to latest 4.3 development version with SV fusion
support.
- simple_sv_annotation handles problematic exon annotations

Update: FreeBayes, snpEff, simple_sv_annotation

---

recipes/lefse/build.sh
recipes/lefse/meta.yaml

We prefix with `lefse-` during symlinking some scripts names that IMHO are too generic: 
```
format_input.py 
plot_cladogram.py
plot_features.py
plot_res.py
```
@bioconda/core new software review needed

Add LEfSe version 1.0.7

---

recipes/merfishtools/meta.yaml
recipes/prosic/meta.yaml

This should fix merfishtools and prosic conflicts occuring in combination with Python 3.5 environments.

Add Python version to buildstring.

---

recipes/mapsplice/meta.yaml

If a package depends on Python and has a custom build string, it has to be ensured that `py{{CONDA_PY}}` is contained in the build string. Otherwise, this can result in a dependency conflict because Python is automatically pinned to the minor version.

Fix build string of mapsplice.

---

recipes/htseq/meta.yaml

importing current HTSeq was giving libfortran issues; htseq recipe was originally created using old bioconda-build. Hopefully rebuilding the same version on the recent builder will fix this...?
The problem is that
```bash
conda create -n htseq-test -c bioconda htseq
source activate htseq-test
python -c 'import HTSeq'
```
gives
```
File "<string>", line 1, in <module>
File "/anaconda2/envs/htseq_test/lib/python2.7/site-packages/HTSeq/__init__.py", line 9, in <module>
from _HTSeq import *
File "numpy.pxd", line 155, in init HTSeq._HTSeq (src/_HTSeq.c:34392)
File "/anaconda2/envs/htseq_test/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
import add_newdocs
File "/anaconda2/envs/htseq_test/lib/python2.7/site-packages/numpy/add_newdocs.py …
```

update htseq build

---

recipes/htseq/meta.yaml

`0.6.1p1` is not a valid PEP-386 version, so conda doesn't see it as newer than `0.6.1`. As a result, `conda install htseq` installs `htseq ==0.6.1` which has an older numpy build pinned to `numpy ==1.7.1` which in turn causes libgfortran errors (see https://github.com/ContinuumIO/anaconda-issues/issues/686 for details on that).
This changes the version to `0.6.1.post1` to be seen as newer than `0.6.1` (e.g., see [here](https://www.python.org/dev/peps/pep-0386/#the-new-versioning-algorithm), and confirmed with `verlib`).

Fix htseq version

---

recipes/viral-ngs/meta.yaml

omit krona from viral-ngs recipe until upstream tags a new release, since viral-ngs applies custom patches to updateTaxonomy.sh

omit krona from viral-ngs recipe for now

---

recipes/gatk/gatk-register.sh
recipes/gatk/gatk.sh
recipes/gatk/meta.yaml
recipes/gvcf-regions/meta.yaml

- gatk: Fixes for gatk-register -- ensure we have full path to tar.bz2
input and allow use of non-versioned tarballs like nightlies with
--noversioncheck parameter. Fixes for gatk -- use the anaconda
installed java by default.
- gvcf_regions: Fix bug with 0 based elements in Platypus gVCF output

Update: GATK and gvcf_regions

---

recipes/freebayes/build.sh
recipes/freebayes/meta.yaml

This PR modifies the freebayes build script to convert its two python scripts for Python 3 using 2to3. This allows freebayes-parallel to be used under Python 3.

Convert freebayes python scripts for Python 3 using 2to3.

---

recipes/pear/meta.yaml

Removes skip in meta.yaml to add support for pear under Mac OS X. Not clear for me why the skip was added, as building under OSX works fine here.

Add OSX support for pear.

---

recipes/bioconductor-dose/meta.yaml

This bumps DOSE to 2.10.6 to prepare to bump clusterProfileR up to a more recent version.

Bump DOSE version to 2.10.6.

---

recipes/bioconductor-clusterprofiler/meta.yaml

This a) bumps clusterprofiler up to 3.0.4, fixing some missing dependencies and b) enables it to be installed on OSX.

Bump clusterprofiler to 3.0.4. Enable OSX builds.

---

recipes/bd2k-python-lib/meta.yaml
recipes/cwltool/meta.yaml
recipes/ruamel.yaml/meta.yaml
recipes/schema-salad/build.sh
recipes/schema-salad/meta.yaml
recipes/toil/1048.diff
recipes/toil/meta.yaml

- Add ruamel.yaml and ruamel.ordereddict dependencies, migrated
from conda-forge
- Update schema-salad and cwltool reference implementation to latest
version supporting 1.0
- Update Toil to latest development with support for CWL 1.0

Update: Toil and cwltool to support CWL v1.0

---

recipes/java-jdk/build.sh
recipes/java-jdk/meta.yaml

- Move to latest java-jdk point release
- Include dejavu fonts as part of java distribution, allowing
java to work on minimal systems like cloud images without
system installed fonts.

Update java: Latest 8 point release, bundle fonts

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/java-jdk/build.sh
recipes/java-jdk/meta.yaml

- java-jdk: move libnet.so to `lib` to avoid problems with libio finding
it.
- bcbio-nextgen-vm: include support for bundling new GATK in docker with
bioconda gatk-register approach

Update: bcbio-vm, java for libnet

---

recipes/samtools/meta.yaml

The r-channel updated their sub-version of ncurses from 5.9-1 to 5.9-8
recently:
https://anaconda.org/r/ncurses/files
5.9-1 had symlinks to libncurses.so.5, which previous samtools compiled
against, but the new r version has libncursesw.so.5 so is not
compatible. This bump re-compiles against the new version and
fixes #1644

Update: samtools against new r ncurses subversion

---

recipes/gcs_oauth2_boto_plugin/build.sh
recipes/gcs_oauth2_boto_plugin/meta.yaml
recipes/google-cloud-sdk/build.sh
recipes/google-cloud-sdk/meta.yaml
recipes/retry_decorator/build.sh
recipes/retry_decorator/meta.yaml
recipes/socksipy-branch/build.sh
recipes/socksipy-branch/meta.yaml

- google-cloud-sdk provides easy command line interface
to Google Compute services
- retry_decorator, socksipy-branch are dependencies for
gcs-oauth2-boto-plugin
- gcs-oauth2-boto-plugin required for Toil GCE support

New recipes supporting Google Cloud GCE

---

scripts/build-docs.sh

With seemingly an updated git on Travis, our homepage deployment fails because the git email address was not set. This PR adds a generic github email address for bioconda to solve the issue.

Configure user.email for gh-pages.

---

recipes/prodigal/meta.yaml

Try to fix failing weekly test of prodigal (see #1744). In the weekly test, prodigal thinks that STDIN is provided, and tries to read data from that instead of just printing the help message as it was intended in the test case.

Ensure that help message is tested only.

---

recipes/ipython-cluster-helper/meta.yaml
recipes/perl-number-format/meta.yaml
recipes/perl-statistics-basic/meta.yaml

- v0.5.3 of ipython-cluster-helper
- Avoid pulling in perl and perl-threaded with perl-statistics-basic

Update: ipython-cluster-helper; Perl libs

---

docs/_static/badge-generator/index.html

changed the way the page worked, but forgot to update the instructions.
Whoops! This fixes it.

corrected badge generator instruction

---

recipes/intervaltree/bld.bat
recipes/intervaltree/build.sh
recipes/intervaltree/meta.yaml
recipes/sortedcontainers/bld.bat
recipes/sortedcontainers/build.sh
recipes/sortedcontainers/meta.yaml

Adds the intervaltree package from PyPI, together with its sortedcontainers dependency. I think this is a useful package for bioconda, as intervaltrees are frequently used for fast querying of (genomic) positions.

Add PyPI intervaltree package

---

recipes/perl-biox-workflow-plugin-fileexists/bld.bat
recipes/perl-biox-workflow-plugin-fileexists/build.sh
recipes/perl-biox-workflow-plugin-fileexists/meta.yaml
recipes/perl-hpc-runner-slurm/2.58/meta.yaml

Rebuilding perl-hpc-runner-slurm with perl-hpc-runner-scheduler as a dep.
Adding in perl-biox-workflow-plugin-fileexists

adding hpc-runner-scheduler as a dep to hpc-runner-slurm

---

recipes/lumpy-sv/142.diff
recipes/lumpy-sv/meta.yaml

Fixes problems with lumpyexpress when running head to check for insert
stats: chapmanb/bcbio-nextgen#1055

Add pipefail patch to lumpy distribution

---

recipes/biopython/build.sh
recipes/biopython/meta.yaml
recipes/mmtf-python/build.sh
recipes/mmtf-python/meta.yaml

At the end of September the NCBI will be deprecating their HTTP Entrez API in favor of the HTTPS version. A newer version of biopython that uses the HTTPS version is available (v1.68; released August 25, 2016), but it is not yet in the default conda channel. Until it is, we should probably have a package available.

add biopython 1.68

---

recipes/trinity/date.2011_11_26/README.md
recipes/trinity/date.2011_11_26/RunButterfly.cc.patch
recipes/trinity/date.2011_11_26/Trinity.pl.patch
recipes/trinity/date.2011_11_26/build.sh
recipes/trinity/date.2011_11_26/meta.yaml
recipes/trinity/date.2011_11_26/samtools_makefile.patch

There are algorithmic changes in Trinity v2 and later, and the recipe for this dated version should be preserved to serve users who prefer the older algorithm.

add older Trinity back again

---

recipes/fasttree/build.sh
recipes/fasttree/meta.yaml

Use double precision with FastTree. It defaults to single precision which can result in numerical stability issues. See concerns [here](http://darlinglab.org/blog/2015/03/23/not-so-fast-fasttree.html)

Compile FastTree with double precision

---

recipes/fastx_toolkit/meta.yaml

runtime dependencies. This is required for fasta_clipping_histogram.pl.
Also fixes tests (all fastx_* -h commands exit with exit-code 1) by
grepping for `Part of FASTX Toolkit 0.0.14 by A. Gordon
(assafgordon@gmail.com)`.
@bgruening, can you have a look at this? In particular, I don't understand why simply saying `fasta_clipping_histogram.pl` will use the system's perl (hence this awkward hack to retrieve the path to `fasta_clipping_histogram.pl`). I would have assumed for perl to be on PATH, but that perl won't have GD.pm in @INC.

Add perl dependencies to fastx_toolkit

---

recipes/vcfanno/build.sh
recipes/vcfanno/meta.yaml

Adds sha256 sums as well. This recipe is broken, and I could use a hand figuring out why. patchelf produces a binary that core dumps:
```
/home/vagrant/local/share/bcbio/anaconda/conda-bld/vcfanno_1474044392940/test_tmp/run_test.sh: line 3:  5683 Segmentation fault      (core dumped) vcfanno
```
I put a link to the original binary that doesn't core dump on linux64 and the patched one that does:
https://dl.dropboxusercontent.com/u/2822886/vcfanno-binaries.tar
If I don't update the recipe and try to rebuild the original files they also core dump. Any ideas?

Update vcfanno to 0.1.0.

---

recipes/schema-salad/meta.yaml

Hey ya'll, in addition to moving to a new version, this adds the cachecontrol and lockfile depdendencies, and switches md5sum to sha256sum. This upgrade is necessary to get the newest version of cwltool to build.

Upgrade schema-salad to 1.18.20160907135919.

---

recipes/diamond/build.sh
recipes/diamond/meta.yaml

- Diamond no longer depends on boost.
- Diamond now builds with an `-march=native` optimization that is being replaced to build for generic x86.

diamond: Remove -march=native optimization

---

recipes/rust-bio-tools/build.sh
recipes/rust-bio-tools/meta.yaml

@bioconda/core sorry for misusing this PR for ads ;-), but my feeling is that you guys might have a natural interest in this. I have started to build a set of somehow "missing" NGS related command line utilities (the rust-bio-tools) on top of my rust-bio library. The key idea is to leverage the powers of Rust to build ultra-fast and memory-safe tools for common tasks that are not easily (or quickly) solvable with what is out there right now. So, in case anybody is interested in joining or using that project, feel free to have a look. So far, I have:
* a linear time implementation for fuzzy matching of vcf/bcf files
* a linear time round-robin FASTQ splitter that splits a given FASTQ files into a given number of chunks
* a tool to extract depth information from BAMs at given loci, which is …

Add rust-bio-tools.

---

recipes/htslib/meta.yaml
recipes/pysam/meta.yaml
recipes/samtools/meta.yaml

I seem to be having trouble with the OSX build of samtools (`dyld: Symbol not found: _stdscr`) after depending on conda-forge. Triggering Travis to rebuild to see if it is just me...

bump samtools build after switch to conda-forge

---

recipes/links/build.sh
recipes/links/links.patch
recipes/links/meta.yaml

This PR bumps links to current version. The difference from previous version is that links now depends on another perl module that is not in cpan. Briefly, the recipe is recompiling the C code and installing the included perl module and copying the links runner script. Unfortunately, I can't get it to compile on osx. 
This recipe needs a review by @bioconda/core as it is offers a custom solution.

Bump links to 1.8.4

---

recipes/gmap/2015.09.10/build.sh
recipes/gmap/2015.09.10/meta.yaml
recipes/gmap/build.sh
recipes/gmap/meta.yaml

This PR adds new version of gmap recipe (version [2016.09.23](http://research-pub.gene.com/gmap/)) and keeps old version as optional (dir "2015.09.10" under gmap)

Gmap 2016.09.23 added, old 2015.09.10 kept as old version

---

recipes/abyss/1.9.0/meta.yaml
recipes/abyss/meta.yaml

bwa is needed for scaffolding with long sequences.
pandoc is needed to produce '-stats.html' files from Markdown.
Ping @druvus.

Add bwa and pandoc to runtime requirements

---

recipes/bcftools/1.3.1/build.sh
recipes/bcftools/1.3.1/meta.yaml

added detect_binary_files_with_prefix build option
to make conda automatically fix the path
bcftools plugin command has a default search path to look for plugins, and it was poiting to ``/anaconda/envs/_build/libexec/bcftools`` , this commit sets the ``detect_binary_files_with_prefix`` conda option to have conda automatically look for these paths on the binaries and update them at install time, this fixes the problem.

fixed bcftools plugin search path

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

Bumps bcbio and bcbio-vm to latest development versions to support
variable naming compatible with WDL and retrieval of genome_context
from Arvados Keep storage.

Update: bcbio, bcbio-vm for Arvados/WDL

---

recipes/pandaseq/meta.yaml

The pandaseq recipe was passing the tests but failed to generate bioconda package. It seems it was /usr/bin/perl so I am trying to add perl-threaded as a build dep.

Pandaseq fix

---

recipes/graphmap/meta.yaml

Skip building graphmap (version 3.0) until I got time to figure out why the error.

Skip build graphmap 3.0 until fixed

---

recipes/bioconductor-topgo/meta.yaml
sorted-r-blacklist

Bump the topgo build number as the 2.24.0 was not correctly pushed to bioconda channel

Bump bioconductor-topgo build number

---

recipes/autoconf/build.sh
recipes/autoconf/meta.yaml

This will fix the hard coded path in shebangs. Added an extra test to verify that the path is set correctly. The problem with the previous test was that the main autoconf script used as a test is a bash script while the most others are perl scripts.

Fix hard-coded shebangs in autoconf

---

build-fail-blacklist
config.yml
scripts/travis-run.sh
sorted-r-blacklist

@bioconda/all if you have submitted a PR since Oct 11, you may have to re-submit. The build system has been giving false positives. Builds would fail, but at the end the exit code would be 0 so travis-ci would incorrectly report the build as passing.
The problem was [this change](https://github.com/bioconda/bioconda-recipes/commit/6411abd8bb8c1cac1a32b4e9e5a30f816fcb4f63#diff-a666270151818014dbda5ced5b3bc54eR8). While `set -euo pipefail` is set at the script level, it is not set in the call to the docker container. This means that the final reported exit code from docker was from the `set +x` call, which was always zero even if the build failed.
This PR adds `set -euo pipefail` to the docker command to fix the issue.
I'm sorry to say this was my change that caused the error, so I'll be …

fix error code in travis-run.sh; blacklist failing package

---

recipes/biobambam/meta.yaml
recipes/samblaster/meta.yaml

Both tools have recent releases which avoid empty mate cigar tags (MC)
which cause validation errors in Picard and htslib derived tools.

Update: biobambam, samblaster with MC fixes

---

config.yml
docs/index.rst

@bioconda/core: as you know, we depend on 3 channels since some time:
| channel | dependency |
| ---------- | --------------- |
| anaconda | - |
| r | anaconda |
| conda-forge | anaconda |
Unfortunately, those channels are not disjoint. Some packages are available in at least two of them. From time to time, it can happen that those packages are binary incompatible, and hence not interchangeable when pulling dependencies (e.g. PR #2569). Currently, conda does not have a good mechanism to solve such problems.
The best we can do at the moment is to enforce an order (i.e. prioritization) of channels, that causes the least problems. My feeling is that this is the order `anaconda > r > conda-forge`. Why? Because the R channel builds on several packages that are also in conda-forge, while this …

Fix channel priorities for building and in the docs.

---

recipes/r-multitaper/meta.yaml
sorted-r-blacklist

@bgruening gfortran is in gcc, but we specify llvm for osx. LLVM doesn't have gfortran, so we get errors like this:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/171435317#L277
I don't know enough about gcc/llvm to know what kinds of issues having both would have. Any ideas for handling this?
xref #2475

try a package with fortran error

---

recipes/trinotate/build.sh
recipes/trinotate/meta.yaml

The conda package version was not good. See: https://github.com/Trinotate/Trinotate/releases 
@bioconda/core can you remove the version 3.2.2

add trinotate 3.0.1 ... the good version

---

recipes/msgf_plus/meta.yaml

The version of MSGF+ in bioconda is pretty old. Can't blame anyone because it was pretty hard to find another version and they are spread all over the place. Problems with this PR:
+ Where do I write the version of MSGF+? The meta.yaml previously had 1.0.0 which cannot be the version for the application (which was v9979)
+ MSGF downloads are updated all the time but the URL is not. Do we have a place to host files?

Version bump MSGF+.

---

recipes/trinotate/meta.yaml

```
|  CMD: TrinotateSeqLoader.pl --sqlite Trinotate.sqlite --gene_trans_map /tmp/tmpn9SjWG/files/000/dataset_12.dat --transcript_fasta /tmp/tmpn9SjWG/files/000/dataset_10.dat --transdecoder_pep /tmp/tmpn9SjWG/files/000/dataset_11.dat --bulk_load
|  install_driver(SQLite) failed: Can't locate DBD/SQLite.pm in @INC (you may need to install the DBD::SQLite module) (@INC contains: /usr/local/genome2/psort/lib64/perl5/site_perl/5.8.8/x86_64-linux-thread-multi /usr/local/genome2/trans-ABySS/wrappers /usr/local/genome2/lib/perl5/ /tmp/tmpn9SjWG/job_working_directory/000/16/conda-env/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /tmp/tmpn9SjWG/job_working_directory/000/16/conda-env/lib/perl5/site_perl/5.22.0 /tmp/tmpn9SjWG/job_working_directory/000/16/conda-env/lib/perl5/5.22.0/x86_64-linu …
```

Trinotate add perl-dbd-sqlite

---

recipes/perl-bioperl-core/build.sh
recipes/perl-bioperl-core/meta.yaml

perl-bioperl-core 1.7.1

---

recipes/pbcore/build.sh
recipes/pbcore/meta.yaml
recipes/python-pbcore/build.sh
recipes/python-pbcore/meta.yaml

Adding recipe for pbcore. I named it python-pbcore to follow the naming of the other pb recipe. 
Should it be called python-pbcore or only pbcore? Any opinions? @bioconda/core

Add pbcore recipe

---

recipes/kaiju/1.0/build.sh
recipes/kaiju/1.0/meta.yaml
recipes/kaiju/meta.yaml

ping @bioconda/core since this is a non-standard OS X build.
Building this with `clang` requires a minimum `MACOSX_DEPLOYMENT_TARGET` of 10.9, which I believe we don't want to do for compatibility reasons.  Building with GCC on OS X works fine, but I wanted to confirm that's ok to do.

Update Kaiju to 1.4.4, add OSX build.

---

recipes/pipmir/meta.yaml

pipmir does not work with the latest RNAfold version, 2.3.0.

pipmir/meta.yaml: use viennarna 1.8.5

---

GUIDELINES.md

Hiding test output is not that useful: The output may be less cluttered, but when the recipe builds, then no one looks at the Travis log anyway. If it does not build, on the other hand, then crucial error messages may get hidden, as in PR #3020.

Recommend against redirecting test output to /dev/null

---

.travis.yml

@bioconda/core I was in contact with Travis the last weeks and could get an extended build-time of 2h. Thanks to Travis!
I think we can just use one subdag, aka only one DAG from now on. My hope is that this will increase our turnaround as we use less concurrent builds for one PR. Most of our PRs only have a few packages included and for large restructurings like R rebuilds I hope 2h is enough.

Use one subdag by default and remove it entirely later on

---

recipes/samtools/build.sh
recipes/samtools/meta.yaml

Ensures correct curl flags passed to internal htslib. Also updates to
use bioconda gcc and tinfo. Fixes #3042

samtools: Fix curl linking for s3 support

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/manta/meta.yaml
recipes/pytest-cov/build.sh
recipes/pytest-cov/meta.yaml
recipes/umis/meta.yaml
recipes/vardict-java/meta.yaml

- Manta: update to latest point release 1.0.3
- VarDictJava: update to latest release 1.4.7
- umis: include fixes for tagging UMIs in fastq names
- pytest-cov: update to latest version to remove warning messages
- bcbio-vm: Force ipyparallel version to ensure latest version of
bcbio-nextgen installed

Update: manta, umis, vardict-java, bcbio-vm, pytest-cov

---

recipes/estscan/3.0/meta.yaml

The installation documentation here https://sourceforge.net/projects/estscan/files/documentation/Feb-2007/ is confusing in that it seems to state that these run-time dependencies are required just to execute this C version of estscan.  But these additional packages are only needed to use estscan features that this recipe does not cover (e.g. generating new scores matrices files).  In any case, neither of the perl-estscan components are needed here.

Remove unnecessary run dependencies for estscan version 3.0 recipe

---

scripts/travis-run.sh

docs are now built in the bioconda-utils repo, so disabling building here

disable docs building on bioconda-recipes

---

recipes/gatk/gatk.py
recipes/gatk/meta.yaml

Fixes problem where gatk.py wrapper script refers to /usr/bin/env python
instead of the direct path to the installed anaconda python. This can
cause issues when the former picks up a different python version.
Fixes chapmanb/bcbio-nextgen#1689

Update gatk to 3.7 and fix python issue

---

recipes/cnvkit/meta.yaml

The PyVCF dependency is dropped in favor of a newer pysam.

Update CNVkit to 0.8.2

---

recipes/tepid/meta.yaml

Both tepid-refine and tepid-discover need all of the python dependencies at runtime.

Bump version and add runtime python dependencies

---

build-fail-blacklist

`ensembl-vep` somehow got merged without the builds passing, and that's holding up other builds. This temporarily disables it just to get the ball rolling.

temporarily add ensembl-vep to blacklist

---

recipes/pysam/meta.yaml

The specific pins for htslib (and samtools, bcftools) cause resolution
errors now that there is a newer htslib (1.3.2, instead of 1.3.1). When
you install:
conda install htslib cnvkit
where the latest cnvkit relies on recent pysam (0.9.1.4) you'll get
htslib 1.3.2 and an old version of pysam and cnvkit prior to the version
pins. We relax these to these avoid confusing resolution issues and enable
both recent htslib and pysam.

pysam: avoid pinning to specific htslib versions

---

recipes/cutadapt/meta.yaml

xopen 0.1.0 can hang on gzipped files. See https://github.com/chapmanb/bcbio-nextgen/issues/1700
and https://github.com/marcelm/cutadapt/commit/d096ff2bd49112e91313a6613bf5c5306b657727

Cutadapt: Require xopen >= 0.1.1

---

recipes/cnvkit/meta.yaml
recipes/goleft/meta.yaml

- CNVkit to latest development with fixes for antitarget creation
(fixes chapmanb/bcbio-nextgen#1696)
- goleft: latest release with indexcov for fast estimation of
coverage using indexes

Update: CNVkit and goleft

---

recipes/kiwidist/meta.yaml

This is to deal with a mismatch with libpng on OSX Sierra 10.12.

Downgrading matplotlib dependency

---

recipes/canu/meta.yaml

A new version of Canu has been released.
https://github.com/marbl/canu/releases

Bump version of Canu

---

recipes/bcbio-nextgen/meta.yaml
recipes/cwltool/build.sh
recipes/cwltool/meta.yaml
recipes/schema-salad/build.sh
recipes/schema-salad/meta.yaml
recipes/toil/meta.yaml

Latest development version of Toil supporting recent cwltool.
Synchronizes cwltoil with cwltool, fixing issues in latest CWL
development.

Update: toil, cwltool, schema-salad

---

recipes/nglview/post-link.sh

Install `nglview` widget to `sys.prefix` rather than user's local directory

nglview: use sys-prefix

---

recipes/perl-gd/meta.yaml

Bumped build in the hope that jpeg >=9 is being recognized as runtime dependency.
Seemed to work locally.
Ping @nsoranzo

Bump build number for perl-gd

---

recipes/arvados-cwl-runner/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/cwltool/meta.yaml
recipes/peddy/meta.yaml
recipes/schema-salad/meta.yaml
recipes/toil/meta.yaml
recipes/vawk/meta.yaml
recipes/vcf2db/meta.yaml

- toil, arvados-cwl-runner, cwltool, schema-salad -- synchronize CWL
runners on single version of cwltool
- vawk -- Use bioconda installed gawk (fixes
chapmanb/bcbio-nextgen#1723)
- vcf2db, peddy -- support for database creation with latest peddy
containing headers

Update: toil/arvados/cwltool, vcf2db, vawk

---

recipes/openms/meta.yaml

Seems like openms needs the boost library as version 1.62 and doesn't work with 1.63.

Correct boost library version

---

recipes/rseqc/meta.yaml

this update explicitly pulls the dependencies
rather than bundling them inside the package
previous version of the package was bundling the dependencies (like pysam) instead of depending on the pysam package.

update rseqc to 2.6.4

---

recipes/umis/meta.yaml

re-implements streaming bamtagging.

Bump umis to 0.5.0a.

---

recipes/meme/build.sh
recipes/meme/meta.yaml

also fixed the build to python 2 only,
this fixes issues #2272 and #1840
as stated in the docs: http://meme-suite.org/doc/install.html, meme doesn't support python3 so I'm changing it to build on python 2 only.
unfortunately, I could not integrate the tests meme ships with because of this bug: https://github.com/conda/conda-build/issues/1453, the tests need to be executed from the build dir, however when build the shebangs strings exceed the linux maximum length and that makes the tests fail.
as a local workaround, the tests can be run if conda-build is executed with the `--prefix-length 1` option.

update meme 4.11.2

---

recipes/msstitch/meta.yaml

Version update. I had to pin lxml because the latest 3.7.2 gave lots of errors in the tests complaining about not finding a lot of shared object files. I could solve some of those but not all (got stuck at `libicui18n`).

Update msstitch to v2.2

---

recipes/extract-sv-reads/build.sh
recipes/extract-sv-reads/meta.yaml
recipes/fgbio/meta.yaml
recipes/goleft/meta.yaml

Allows extraction of split and discordant reads from sorted BAM
files for better lumpy preparation chapmanb/bcbio-nextgen#1738
chapmanb/bcbio-nextgen#1664 chapmanb/bcbio-nextgen#1526

New: extract-sv-reads

---

recipes/r-ggrepel/meta.yaml

This is a simple update of the package r-ggrepel which does not work in the version 0.5 with the current ggplot version (2.2.2).
One simple example of the error produced with v0.5:
```
> library(ggrepel)
Loading required package: ggplot2
> ggplot(mtcars, aes(wt, mpg)) +
+   geom_point(color = 'red') +
+   geom_text_repel(aes(label = rownames(mtcars))) +
+   theme_classic(base_size = 16)
Error: GeomTextRepel was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.
```
This is my first pull request so I have to ask @bioconda/core for a review. Please tell me if it means something more than just what I did in the previous sentence.

Update r-ggrepel 0.5 to 0.6.5

---

recipes/bowtie2/bowtie2.patch
recipes/bowtie2/meta.yaml

This PR patches the `bowtie2` Perl wrapper script which under some conditions failed with the following error: 
```
/anaconda/pkgs/bowtie2-2.3.0-py27_0/bin/bowtie2-align-s:
error while loading shared libraries:libtbbmalloc_proxy.so.2: cannot open shared object file: No such file or directory.
```
Specifically this was happening on a cluster where conda was installed on one filesystem and the environment containing bowtie2 was on another filesystem. The patch removes the part of the wrapper that attempts to resolve symlinks. 
This does not happen in previous versions of bowtie2, but according to the release notes there was substantial refactoring in 2.3.0 which could be why we're only seeing this now.
I think that removing the symlink resolution here is OK, since the bowtie2 perl wrapper …

patch bowtie2 to work across filesystems

---

recipes/bcbio-nextgen/alignprep.diff
recipes/bcbio-nextgen/meta.yaml
recipes/goleft/meta.yaml

- bcbio: Fixes bug where bcbio 1.0.1 release can hang when grabix
indexing bgzip files (chapmanb/bcbio-nextgen#1779)
- goleft: update to 0.1.12-dev with fixes for hg38 BAMs

Update: bcbio, goleft

---

recipes/ant/meta.yaml

Now use `openjdk` instead of `java-jdk`

Update ant to 1.10.0

---

recipes/hmmer/build.sh
recipes/hmmer/meta.yaml

Disable compiler optimizations that produce unportable binaries.

Compile hmmer with --enable-portable-binary

---

recipes/r-tibble/meta.yaml

forcing r-tibble to be re-built with conda-build>2.0

---

recipes/r-data.table/meta.yaml

Try rebuilding to fix a path length problem:
```
PaddingError: Placeholder of length '80' too short in package bioconda::r-data.table-1.10.0-r3.3.1_0.
```

r-data-table: fix a path length problem

---

recipes/anvio/meta.yaml

I updated the anvio dependencies slightly:
* Anvio's built-in test (`anvi-self-test`, used to verify installation) requires prodigal and hmmer to run successfully.
* The most recent version of cherrypy (>=9) conflicts with the bottle.
Checklist:

better dependincies for anvio

---

recipes/khmer/2.0/meta.yaml

It seems the khmer recipe was meant to work under macOS (there is an `llvm` requirement), but the `skip: True` was never removed.

Do not skip khmer build on macOS

---

recipes/dkfz-bias-filter/build.sh
recipes/dkfz-bias-filter/meta.yaml
recipes/vardict-java/meta.yaml
recipes/vardict/meta.yaml

- VarDictJava: update to 1.4.9 with fixes for overlapping reads
- VarDict: support reference calls AstraZeneca-NGS/VarDict#37
- DDFZBiasFilter: new recipe supporting filtering of DNA damage events
(oxoG, FFPE) and strand bias.

New: DKFZBiasFilter, Update: VarDict, VarDictJava

---

recipes/pysam/0.9.1.4/build.sh
recipes/pysam/0.9.1.4/meta.yaml

* [x ] I have read the guidelines above.
Minor modification to recipe to build pysam 0.10.0:
```build:
binary_relocation: False
```
CI seems to pass:
```
INFO bioconda_utils.build:build(145): BIOCONDA TEST SUCCESS recipes/pysam, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
INFO bioconda_utils.build:build_recipes(396): BIOCONDA BUILD SUMMARY: successfully built 1 of 1 recipes
```
but then fails at upload stage, presumably because of missing permissions.
```
File "/anaconda/lib/python3.5/site-packages/bioconda_utils/upload.py", line 37, in upload
raise ValueError("Env var ANACONDA_TOKEN not found")
ValueError: Env var ANACONDA_TOKEN not found
```
Full log is here: …

{AH} add pysam 0.10.0 build recipe

---

recipes/salmon/0.7.2/build.sh
recipes/salmon/0.7.2/meta.yaml
recipes/salmon/build.sh
recipes/salmon/meta.yaml

Building from source on OS X is still a WIP.  The binary is created ok, but throws symbol not found errors at runtime.  The pre-built OS X binary was built using 10.12, and gives a `lazy symbol binding failed` error when run on earlier OS versions.

Add recipe for salmon 0.8.0.

---

recipes/cgcloud-lib/meta.yaml
recipes/toil/meta.yaml
recipes/vardict/meta.yaml

- toil, cgcloud-lib: update to latest 3.6.0 release and dependencies
- vardict: fix for empty paired inputs

Update: Toil and VarDict

---

docs/generate_docs.py
recipes/openms/meta.yaml

Since some time, the docs were not properly updated any more. This was because of an undetected error in the openms recipe (the notes section contained a list). This PR improves the error messages of our doc script (they now point to the failing recipe) and fixes the problem with openms.

[ci skip] Better error reporting when generating docs. Fix notes section of openms.

---

recipes/srst2/0.1.4.6/build.sh
recipes/srst2/0.1.4.6/meta.yaml
recipes/srst2/0.1.4.6/use_setuptools.patch
recipes/srst2/build.sh
recipes/srst2/meta.yaml
recipes/srst2/use_setuptools.patch

Added in srst2 recipes for 0.1.4.6 and 0.2.0

---

recipes/vcf2maf/meta.yaml

----
The changes are simple. Other than updating the link, I had to add `htslib` as a requirement, because `vcf2maf` now depends on `tabix` (part of `htslib`).

Update vcf2maf recipe to v1.6.12

---

.travis.yml

Many bioconda PRs are held up by builds from other PRs where one job in the build matrix has failed but secondary jobs within the failing build still run. This PR enables the [Travis-CI `fast_finish` feature]( https://docs.travis-ci.com/user/customizing-the-build#Fast-Finishing ), which marks a build finished as soon as a single member job has failed.  This allows other builds to continue. Since a contributor will need to submit a new commit to correct a failing job, all jobs in the build matrix will eventually be tested. @bioconda/core: Thoughts?

Enable Travis Fast Finishing

---

scripts/travis-setup.sh

This pins the python version used for conda to py3.5 to be internally consistent with the dependencies of bioconda_utils. See https://github.com/bioconda/bioconda-recipes/issues/3808
This is likely temporary until we can update bioconda_utils dependencies etc. to use Python 3.6.

Pin conda to python3.5

---

recipes/r-matrixstats/meta.yaml

bump build of r-matrixstats to trigger a rebuild with conda-build > 2
```
WARNING conda_build.build:create_env(699): Build prefix failed with prefix length 255
WARNING conda_build.build:create_env(700): Error was: 
WARNING conda_build.build:create_env(701): Placeholder of length '80' too short in package bioconda::r-matrixstats-0.51.0-r3.3.1_0.
WARNING conda_build.build:create_env(702): One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING conda_build.build:create_env(704): Falling back to legacy prefix length of 80 characters.
WARNING conda_build.build:create_env(705): Your package will not install into prefixes > 80 characters.
[...]
Placeholder of length '80' too short in package …
```

Bump matrixstats

---

recipes/trinity/date.2011_11_26/Chrysalis_stacksize.patch
recipes/trinity/date.2011_11_26/build.sh
recipes/trinity/date.2011_11_26/headerpad.patch
recipes/trinity/date.2011_11_26/meta.yaml

Chrysalis relies on unlimited stack size but OS X can only set stack size during compilations. Which we set to 1GB.

trinity: date.2011_11_26 fix for OS X

---

recipes/pindel/meta.yaml

The pindel package was broken, because it fails to find libgomp.so in stripped down containers. That library is part of libgcc, hence, this PR adds gcc/libgcc as dependencies to fix pindel.

Add missing dependencies.

---

recipes/rdflib-jsonld/meta.yaml
recipes/rdflib/meta.yaml

- FreeBayes: move to 1.1.0 release build which has a fix for Allele
creation edge cases
- rdflib, redflib-jsonld: latest version without html5lib requirement

Update: rdflib-jsonld, rdflib

---

recipes/treebest/meta.yaml

Fix for:
```
PaddingError: Placeholder of length '80' too short in package bioconda::treebest-1.9.2_ep78-0.
```

Rebuild with conda-build > 2.0

---

recipes/dunovo/meta.yaml

This just updates the version of bowtie2 from 2.2.4 to 2.2.5, so it's compatible with the version in the Galaxy Toolshed.
It passes both Travis tests.

Du Novo: Update bowtie2 dependency version

---

recipes/dunovo/build.sh
recipes/dunovo/meta.yaml

I'd forgotten a few scripts that need to be in `$PREFIX/bin`. `meta.yaml` also had to be edited to pull down new code which can find the scripts in `$PREFIX/bin`.
P.S. Sorry, I screwed up by pushing my changes before syncing with upstream. Also, I committed on `master`, not the `dunovo` branch. I'll make sure to do it right next time!

Du Novo: Fix missing scripts in bin directory

---

.travis.yml
recipes/snakemake/meta.yaml
recipes/svtools/0.3.0/meta.yaml
scripts/travis-run.sh

Following a discussion in #3845, this is a try to get rid of the redundancy in our travis builds. For both PRs and master, we obtain the list of changed recipes and run bioconda-utils restricted to those. However, if either the env matrix changed or the current build is a cron job, we consider all recipes instead.

[WIP] Non redundant builds

---

scripts/travis-run.sh

Fixes a problem with non-redundant-builds in master (see PR #3891).

Format $TRAVIS_COMMIT_RANGE properly.

---

boost-1.61-migration-blacklist
recipes/mothur/1.36.1/meta.yaml

According to @bgruening it does not work with the newer version. Hence, I hardcoded the latest working version into this recipe. This is reasonable since it is just an old version of the recipe that won't be updated.
ping @bgruening @bebatut @shiltemann

Pin the old mothur-1.36.1 to old boost version

---

scripts/travis-run.sh

When building the master branch, we don't want to lint. 
1. This should have happened before.
2. We have periodic cron jobs that consider all recipes. We don't want failures due to failing lints in old stuff. Further, we can't deactivate lints by commit messages in such cases.

Disable linting when building master branch.

---

scripts/bioconductor/bioconductor_skeleton.py

This should ensure that R-specific code in conda-build is triggered.

Depend on r-base instead of r.

---

recipes/samtools/0.1.19/build.sh
recipes/samtools/0.1.19/meta.yaml

In #3900 we run into failures during the mulled build
when unpacking the samtools 0.1.19 package. It complains about
permissions when installing `vcfutils.pl`:
https://travis-ci.org/bioconda/bioconda-recipes/jobs/209609560#L1767
```
[Mar 10 03:48:15] DEBU Packing failed due to open build/dist/bin/vcfutils.pl: permission denied
[Mar 10 03:48:15] WARN Local execution errorred with error [open build/dist/bin/vcfutils.pl: permission denied], retrying with remote execution
```
The cause appears to be that `vcfutils.pl` does not have read
and execute permissions set for non-root users:
```
/anaconda/pkgs/samtools-0.1.19-1/bin:
total 2.4M
-rwxr-xr-x 1 root root 643K Apr 20  2016 bcftools
-rwxr-xr-x 1 root root 1.8M Apr 20  2016 samtools
-rwxrwx--- 1 root root  16K Apr 20  2016 vcfutils.pl
``` …

samtools 0.1.19: update permissions for vcfutils.pl

---

recipes/minialign/build.sh
recipes/minialign/meta.yaml

@ocxtal I am using an older platform string here. The `-march=native` makes the built package use features that some not bleeding edge CPUs (e.g., our cluster with `Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz` CPUs) do not support. This is a *proposal* only.
@bgruening @johanneskoester is there a policy of backwards compatibility in terms of CPU instruction set?

Using older CPU architecture for minialign

---

recipes/bioconductor-methylkit/build.sh
recipes/bioconductor-methylkit/meta.yaml
recipes/bioconductor-methylkit/rpath.patch

This upgrades [methylKit](https://bioconductor.org/packages/release/bioc/html/methylKit.html) to 1.0.0, the current version in Bioconductor release channel.  
Also, a patch is included to enable OSX build by passing the correct library paths and C++11 flags. This is my first attempt at creating patch for bioconda so @bioconda/core please review my patch. Any feedback is highly welcomed. Thanks!

Bump Bioconductor methylkit to 1.0.0 and enable OSX build

---

recipes/bcbio-nextgen/meta.yaml
recipes/gemini/meta.yaml
recipes/sambamba/meta.yaml

- sambamba: 0.6.6 with ldc fixes for some HPC architectures
- gemini: gnomad support and fixes for VEP extras in variants tables
- bcbio: clean validation plots with matplotlib 2.0

Update: sambamba, gemini, bcbio

---

recipes/beagle-lib/build.sh
recipes/beagle-lib/meta.yaml

By default, using march=native is enabled.  This causes SIGILL
crashes on hardware sufficiently different than the build
environment.

Disable march=native for beagle-lib.

---

recipes/probamconvert/meta.yaml

My first attempt to modify the conda package for proBAMconvert, i'm still pretty amateur at this.
I've updated to a newer proBAMconvert version, compatible with pysam 0.10.0, also, the previous version did have some errors in galaxy which should be fixed now.
Also, I'm no quite sure but should the usage of python2 not be a requirement ? proBAMconvert is not made compatible with python 3.
Also, is there away to adjust the galaxy xml file to use a fork of the bioconda recipe so I could test it out before requesting a pull?
Thank you for all your work, I'm still in the progress of figuring Conda out !

newer version proBAMconvert

---

recipes/salmon/build.sh
recipes/salmon/meta.yaml

- Avoids compiling from source due to incompatibilities between autoconf
and lxml. autoconf requires icu 56.* and lxml uses icu 58.*
- Re-adds OSX support with binary install

Update: salmon 0.8.1 with pre-compiled binaries

---

recipes/bcbio-nextgen/meta.yaml

matplotlib pin causes issues with other pinned tools, breaking upgrades
and causing incompatibilities with icu. Fixes chapmanb/bcbio-nextgen#1865

bcbio: update and remove matplotlib pinning

---

recipes/gemini/meta.yaml

Not sure how to deal with reproducibility on this, but there is not gemini release for version 0.19.2a

Fix incorrect gemini version

---

recipes/bcftools/1.2/meta.yaml
recipes/bcftools/build.sh
recipes/bcftools/meta.yaml
recipes/htslib/meta.yaml
recipes/sailfish/meta.yaml
recipes/samtools/0.1.17/meta.yaml
recipes/samtools/build.sh
recipes/samtools/meta.yaml

- samtools, bcftools, htslib: latest 1.4 release
- sailfish: avoid pinning to older icu 56, which is
incompatible with lxml

Update: samtools, bcftools, htslib, sailfish

---

recipes/bcbio-nextgen/meta.yaml
recipes/qsignature/build.sh
recipes/qsignature/meta.yaml
recipes/qsignature/qsignature.sh

- bcbio: pin htslib to avoid problems with htslib 1.4 and pysam
- qsignature: ensure default java points to anaconda installed
java. Thanks to @ohofmann

Update: bcbio, qsignature

---

recipes/trinity/build.sh
recipes/trinity/meta.yaml

In particular, symlinking `util/R/` prevents creating an environment containing also any R package.
Also fix md5 key name.

Do not symlink subdirectories of util/

---

recipes/trinity/meta.yaml

Otherwise the completely broken bowtie2 2.2.5-0 is chosen by conda when creating a new environment.

Add minimum version 2.3.0 to bowtie2 requirement for Trinity

---

recipes/phylip/drawtree.py
recipes/phylip/font-paths.patch
recipes/phylip/maxtrees.patch
recipes/phylip/meta.yaml

New version of phylip-recipe to build 1. 
(Reason for update: By default, phylip only save a maximum number of phylogenetic trees determined by the hard-coded variable maxtrees. This update applies a patch that changes maxtrees to 10000 in several programs -- previous value of 100 in several programs was way to low for biologically relevant analyses.)
* [x ] I have read the guidelines above.
* [x ] This PR updates an existing recipe.

updated version of phylip recipe

---

recipes/arvados-cwl-runner/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/cwltool/meta.yaml
recipes/gridss/meta.yaml
recipes/schema-salad/meta.yaml

- arvados-cwl-runner -- update to latest release
- gridss -- include fix for disk space usage in latest release
- cwltool, schema-salad -- pin to correct version of typing
- bcbio-nextgen -- support for generating WDL compatible output

Update: arvados-cwl-runner, gridss, bcbio-nextgen

---

recipes/kraken/meta.yaml

It is required for `kraken-build`.
Also add `perl` as build requirement.
Change `perl-threaded` to `perl`.

Add jellyfish 1 as run requirement for kraken

---

recipes/kraken/0.10.5beta/build.sh
recipes/kraken/0.10.5beta/meta.yaml
recipes/kraken/build.sh
recipes/kraken/meta.yaml

kraken had a global sed to fix perl files that created `.bak` files
for internal anaconda files (like activate) that causes install
issues.
https://groups.google.com/d/msg/biovalidation/hZBLfeOqMDc/SGr6Gxv7AgAJ

Update: kraken to fix missing `.bak` files

---

recipes/bioconductor-dexseq/meta.yaml

Use depot URL, upstream is gone.

Require deseq2 version built with conda > 2.0. Change r to r-base

---

recipes/rmblast/build.sh
recipes/rmblast/meta.yaml

This is a cleaned up version of the commits that went into PR #4324. It:
* adds the bzip2 dependency for rmblast (for makeblastdb)
* adds code to the build.sh to link bzip2.so.1.0 to bzip2.so.1 if necessary
* locks boost to <= 1.58

Update rmblast as per #4324

---

recipes/gclib/Makefile.patch
recipes/gclib/build.sh
recipes/gclib/meta.yaml

GffCompare links with GFastaIndex.o, among others, which gclib's Makefile doesn't build. With this change, that is no longer the case. Obviously GffCompare's Makefile will also need to be patched to reflect this modification.

Build additional object files used by GffCompare

---

recipes/kaptive/meta.yaml

Tool only works for blast 2.30 or lower if you want multiple threading. Also now has support for python 3 so removed those restriction

updated to latest release of Kaptive

---

recipes/mgs-canopy/build.sh
recipes/mgs-canopy/meta.yaml

The [mgs-canopy-algorithm](https://github.com/fplaza/mgs-canopy-algorithm) repo have a pretty well written Makefile for system-wide install, but it does not work within Conda. This is due to `boost` location, even by setting `BOOST_INCDIR` and others. So I compile "manually" the sources.

Recipe for mgs-canopy

---

recipes/biopython/meta.yaml

This should resolve #4399 (but does not pick a license family for the metadata)
Note I recommend applying this prior to #4403 in order to fix the Biopython 1.68 recipe.
Then, as part of supporting Biopython 1.69, update the ``license_file:`` to point at ``LICENSE.rst`` to reflect this being renamed in Biopython 1.69

Biopython License Agreement, not MIT.

---

.gitmodules

Buildkite might at some point replace our travis setup. It allows us to host CI agents ourselves. By that, we can scale our build system with the community size. We keep the whole configuration in public (via bioconda/bioconda-buildkite), such that transparency is ensured.

[ci skip] Setup buildkite configuration as a submodule.

---

recipes/bioconductor-pcamethods/meta.yaml

Because of this error:
```
$ /tmp/mcglc/bin/conda create -y --name mulled-v1-90e10224e0dae515c59ba938ab2d983ed80b151d226620521a523e67e6f55720 bioconductor-pcamethods=1.64.0
[…]
PaddingError: Placeholder of length '80' too short in package bioconda::bioconductor-pcamethods-1.64.0-r3.3.1_0.
```

rebuild bioconductor-pca

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

Use latest pysam to force consistent use of htslib 1.4

Update: bcbio, bcbio-vm to force latest pysam

---

recipes/stacks/build.sh
recipes/stacks/gcc48.patch
recipes/stacks/meta.yaml

Now uses boost::regex instead of std::regex
It should fix runtime errors due to std::regex not being available in gcc 4.8

Stacks: fix runtime errors

---

recipes/bcbio-nextgen/meta.yaml
recipes/svtyper/meta.yaml

- svtyper: support for --max_reads to downsample in complex regions
- bcbio-nextgen: Improved install size by removing mkl libraries
and ipython notebook html with associated dependencies like pandoc.

Update: svtyper, bcbio-nextgen

---

recipes/bbmap/37.10/build.sh
recipes/bbmap/37.10/meta.yaml

Also remove no_osx flag, it builds successfully on osx and the docs say osx is supported.

bbmap 37.10 -> 37.17

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

- Pins toil and ruamel.yaml versions to avoid getting old
installs.
- Includes support for interacting with Seven Bridges and the Cancer
Genomics Cloud

Update: bcbio and bcbio-vm

---

recipes/picopore/meta.yaml

Not sure why I keep swapping between tar.gz and zip... probably to do with what dist I use to build+push.
* [Y] I have read the guidelines above.
* [N] This PR adds a new recipe.
* [Y] This PR updates an existing recipe.
* [N] This PR does something else (explain below).

Bump Picopore to v1.1.4

---

recipes/gmap/2014.12.23/build.sh
recipes/gmap/2014.12.23/meta.yaml

This PR adds explicit zlib support for gmap (first tried on version 2014.12.23). It also adds the `--check` flag for testing. I also want to test the use of `--disable-sse*` flag for `--configure` since the default setting seems to break in some installations.

Use zlib for gmap & update tests

---

recipes/biopython/1.65/build.sh
recipes/biopython/1.65/meta.yaml
recipes/biopython/1.66/build.sh
recipes/biopython/1.66/meta.yaml

We now have BioConda packages for Biopython 1.67 onwards, with 1.67 added as a legacy package in #4462 to help with Galaxy tool dependencies.
Older versions of Biopython 1.65 and 1.66 are still being used by one or more of the IUC maintained Galaxy Tools, and therefore it is expedient to have them available on BioConda as well.
See https://github.com/galaxyproject/tools-iuc/
```
$ grep biopython tools/*/*.xml
tools/jbrowse/macros.xml:      <requirement type="package" version="1.66">biopython</requirement>
tools/kraken_taxonomy_report/kraken_taxonomy_report.xml:        <requirement type="package" version="1.66">biopython</requirement>
tools/ncbi_entrez_eutils/macros.xml:      <requirement type="package" version="1.68">biopython</requirement>
tools/ncbi_entrez_eutils/tool_dependencies.xml: …
```

BioConda recipes for Biopython 1.65 and 1.66

---

.travis.yml
scripts/travis-run.sh
scripts/travis-setup.sh

Consider env matrix updates only when on a branch called "bulk/*".
Together with PR #96, this allows us to perform bulk updates in an iterative way,
without using blacklist. The workflow is as follows:
1. Create a PR with an updated env matrix, with a target branch called "bulk/*".
2. The PR will be tested, but bioconda-utils will only build recipes that have changed in addition to the env matrix.
3. Once the PR is merged, bioconda-utils will build the changes induced by the new env matrix. Whenever a recipe has been successfully built, the package will be immediately uploaded to anaconda and biocontainers (mulled).
4. If errors occur, they can be fixed in a PR against the bulk branch. In such a case, we start again at step 1. Importantly, since successfully built packages have been …

Bulk update support

---

recipes/galaxy-w4m-r-classfilter/build.sh
recipes/galaxy-w4m-r-classfilter/meta.yaml

Please review and provide suggestions for improvement if appropriate.
This is a new recipe for an R package that will implement processing for a new tool for the Workflow4Metabolomics flavor of Galaxy.  My intent is to add just two files:
- recipes/galaxy-w4m-r-classfilter/build.sh
- recipes/galaxy-w4m-r-classfilter/meta.yaml
This is my first pull request (ever), so, if there are more files than these two, that's a problem that I didn't detect!
The travis build failed for the commit that added them (which is what I believe is the basis of this pull request); however, [in that build](https://travis-ci.org/eschen42/bioconda-recipes/jobs/228312460), **this recipe succeeded**, viz:
> 14:27:31 BIOCONDA INFO BUILD START recipes/galaxy-w4m-r-classfilter, env: …

New recipe galaxy-w4m-r-classfilter

---

scripts/env_matrix.yml

such that new PRs don't build against 3.5 only while we are still doing the bulk update.

Enable Python 3.6 in the env matrix

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

New 1.0.3 release for bcbio. Ansible fix and version pinning for
bcbio-vm

Update: bcbio, bcbio-vm

---

recipes/w4mclassfilter/0.98.0/build.sh
recipes/w4mclassfilter/0.98.0/meta.yaml

This recipe-change built and passed its test in [build 11.1 of eschen42/bioconda-recipes](https://travis-ci.org/eschen42/bioconda-recipes/jobs/229590498). Most of my travis builds are terminating in an error that I cannot trace to any of my changes.
```
13:38:59 BIOCONDA INFO BUILD START recipes/w4mclassfilter, env: CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
13:39:59 BIOCONDA INFO BUILD SUCCESS /anaconda/conda-bld/linux-64/w4mclassfilter-0.98.1-0.98.1.tar.bz2, CONDA_BOOST=1.61;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.4;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
13:39:59 BIOCONDA INFO TEST START via mulled-build …
```

Recipe for v0.98.1 of w4mclassfilter

---

recipes/ghostscript/9.07/build.sh
recipes/ghostscript/9.07/meta.yaml
recipes/ghostscript/9.10/build.sh
recipes/ghostscript/9.10/meta.yaml
recipes/ghostscript/meta.yaml

In order to facilitate Galaxy Admins transitioning from Galaxy's old packaging system to Conda, this pull request adds recipes for old versions of GhostScript available as packages on the Galaxy Tool Shed,
* https://toolshed.g2.bx.psu.edu/view/iuc/package_ghostscript_9_07/
* https://toolshed.g2.bx.psu.edu/view/devteam/package_ghostscript_9_10/
See also https://github.com/galaxyproject/tools-iuc/issues/1001

Recipes for GhostScript 9.07 and 9.10

---

.github/PULL_REQUEST_TEMPLATE.md

While writing a pull request GitHub shows the following above the text box:
> Before you create a pull request, please review [the guidelines for contributing](https://github.com/bioconda/bioconda-recipes/blob/master/CONTRIBUTING.md) to this repository.
However, the ``CONTRIBUTING.md`` file just points you at https://bioconda.github.io/contributing.htm
Moreover, once a pull request is created, "above" becomes meaningless, so I think it is better to make this explicit in the template, as in this pull request.

Make link to contributing guidelines explicit

---

recipes/snpeff/meta.yaml

snpeff current version is "4.3k" but conda is sorting it below "4.3", this PR changes the version to "4.3.0k", that seems to do the trick (see openssl versions).

change snpeff version to fix conda version sorting

---

recipes/r-checkmate/meta.yaml

Apparently the travis CI does not find the r-checkmate package it is supposed to build in #4688, so the recipe changes there are failing tests. This should resolve that situation.

Build r-checkmate separately.

---

.gitignore

Remove `.patch` from `.gitignore` since it's commonly used when adding patch files to a recipe.  Xref: #4591.

Remove .patch extension from gitignore.

---

recipes/ensembl-vep/meta.yaml
recipes/perl-bio-db-hts/build.sh
recipes/perl-bio-db-hts/meta.yaml

Upgrades to htslib 1.4 and current perl in conda-forge. Avoids using
package gcc for compilation because of fstack-protector-strong error,
instead using gcc in condaforge/linux-anvil container.
Fixes #4703
Fixes chapmanb/bcbio-nextgen#1911

Update: ensembl-vep, perl-bio-db-hts with htslib

---

recipes/gap2seq/0002-renamed-lock-to-Gap2Seq_lock-to-avoid-name-conflicts.patch
recipes/gap2seq/build.sh
recipes/gap2seq/meta.yaml

gap2seq: re-enabled multi-threading on osx; cleaned up recipe

gap2seq: re-enabled multi-threading on osx; cleaned up recipe

---

recipes/sourmash/meta.yaml

sourmash won't work with khmer < 2.1

Fix runtime requirements for khmer

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/ensembl-vep/meta.yaml
recipes/perl-bio-db-hts/meta.yaml
recipes/toil/meta.yaml

- Adds CONDA_HTSLIB version string to VEP and Bio::DB::HTS (#4793)
- bcbio: latest development and remove pytest-marks dependency
- bcbio-vm: include Rabix and Synapse support
- Toil: avoid file copying during cwltoil

Update: Toil, bcbio (+vm), VEP

---

recipes/gatk-framework/gatk-framework
recipes/gatk-framework/meta.yaml
recipes/gatk4/build.sh
recipes/gatk4/meta.yaml
recipes/multiqc-bcbio/meta.yaml

- gatk4 -- initial wrapper for gatk4 alpha release. This is BSD licensed
and fully open source. Uses the Broad team's gatk-launch wrapper
script instead of a custom bioconda wrapper. Only supports local
execution for now.
- gatk-framework -- Fix problem where we detect java in `/bin/java` even
if JAVA_HOME is unset. Thanks to Tanner Koomar.
https://groups.google.com/d/msg/biovalidation/-HzLgUnK2eA/ugmqnPGjAwAJ

New: gatk4 wrapper, Update: gatk-framework

---

scripts/travis-run.sh

I saw a `GITHUB_TOKEN: unbound variable` ...

GITHUB_TOKEN: unbound variable

---

recipes/genepop/build.sh
recipes/genepop/meta.yaml

Original recipe by @tiagoantao 
It looks like @bgruening restricted this to exclude Mac, not sure why - it compiles for me locally and my tests passed.
I have also made the compilation requirements explicit in line with evolving BioConda best practises, and added a minimal test.
Note the authors seem to reuse their filenames and URL, meaning older releases are not cached. I have added a checksum, but this is a concern as sources for the old releases are no longer available.

Update for Genepop 4.6, works on Mac

---

recipes/cnvkit/meta.yaml
recipes/ipython-cluster-helper/meta.yaml
recipes/variantbam/meta.yaml

- ipython-cluster-helper -- v0.5.5 with fix for multiple interfaces
(chapmanb/bcbio-nextgen#1960)
- CNVkit -- latest development with fix for `--filter cn` problems
(etal/cnvkit#217)
- VariantBam -- upgrade to latest version with SeqLib support
VariantBam needs recursive Git retrieval
[lint skip uses_git_url for recipes/variantbam]
[lint skip missing_hash for recipes/variantbam]

Update: CNVkit, ipython-cluster-helper, VariantBam

---

scripts/travis-run.sh

Fixes #4553.  As @ivirshup nicely explained there, when pushing a new branch with a single commit to your fork, the build will always fail as the `TRAVIS_COMMIT_RANGE` variable is empty for that case.  This change checks for that, and sets the range to pick up the last commit.  When multiple commits are made locally to a new branch and then pushed, `TRAVIS_COMMIT_RANGE` has the proper value, so we should only ever need to look at the last commit when it's empty.
Ping @bioconda/core since this is a change to a build script.

Handle case of a new branch with a single commit on forks.

---

recipes/biomaj/meta.yaml
recipes/circlator/meta.yaml
recipes/iva/meta.yaml
recipes/minepy/meta.yaml
recipes/pepr/meta.yaml
recipes/pyfasta/meta.yaml
recipes/pyfastaq/meta.yaml
recipes/seqmagick/meta.yaml
recipes/stacks_summary/meta.yaml
recipes/xmltramp2/meta.yaml

I've not found any BioConda documentation defining the ``license_family:`` field (see also #1581), but none of the GNU licenses (i.e. any versions of the GPL and LGPL) can be considered as public domain.
It makes sense to me to class any version of the GPL as ``license_family: GPL`` as in this LGPL example:
```
about:
home: https://pypi.python.org/pypi/xmlbuilder/1.0
license: LGPL v3
summary: 'pythonic way to crate xml/(x)html files'
license_family: LGPL
```

GNU licenses like GPL, AGPL, LGPL are not public domain

---

recipes/cnvkit/meta.yaml

Recent pysam release has pickier requirements for
retrieving INFO fields during VCF parsing.

CNVkit: update with support for latest pysam

---

recipes/snpeff/build.sh
recipes/snpeff/meta.yaml
recipes/snpsift/build.sh
recipes/snpsift/meta.yaml

`snpEff.config` is needed by SnpSift annotate
`scripts/vcfEffOnePerLine.pl` is mentioned in the SnpSift documentation
Broken in abbda6ea25c4342d15d5c494ba1bcdd86cce5de0

Update SnpEff and SnpSift to v4.3p. Re-add scripts/ and snpEff.config to snpsift

---

recipes/clinod/clinod.py
recipes/clinod/meta.yaml

The original recipe accidentally used the Galaxy cache's filename ``clinod_1.3_src_all.jar`` rather than the original filename, ``clinod-1.3.jar``.
This restores the original JAR filename.

Preserve the original JAR filename: clinod-1.3.jar

---

recipes/unicycler/Makefile.patch
recipes/unicycler/meta.yaml
recipes/unicycler/misc.py.patch

- Replace `-march=native` with `-mtune=generic` to prevent the possibility of building with architecture-specific hardware instructions.
- Remove unicode left/right arrows so that the job output handler definitely won't explode.

Fixes for unicycler

---

recipes/gatk-framework/gatk-framework
recipes/gatk-framework/meta.yaml
recipes/picard/meta.yaml
recipes/picard/picard.sh
recipes/snpeff/meta.yaml
recipes/snpeff/snpeff.sh

The shell wrapper scripts had inconsistent ways of checking for
JAVA_HOME which were incorrect on gatk-framework and snpeff and would
pick up a java installed in `/bin/java` even if unset.
chapmanb/bcbio-nextgen#1968

Update shell wrappers: gatk-framework, picard, snpeff

---

recipes/fgbio/meta.yaml

Latest development version supports duplex UMIs with a fix to handle
strand changes from 0.1.4

fgbio: update to latest devel with duplex support

---

recipes/umis/build.sh
recipes/umis/meta.yaml
recipes/wham/meta.yaml

- umis -- Fix for duplex only barcodes
- wham -- Fix header issue with string/int chapmanb/bcbio-nextgen#1980
[skip uses_git_url for recipes/wham]

Update: umis, wham

---

recipes/freebayes/build.sh
recipes/freebayes/meta.yaml

Update of previous PR (#2588), which no longer pointed to a valid branch. Fixes issues mentioned in #2148. Essentially, the modified recipe now also builds the vcflib submodule and copies the required scripts + library from the vcflib directory for freebayes-parallel.
I am still having some trouble building for OSX. My initial problems with intervaltree are fixed after replacing ``-std=c++0x`` with ``-std=c++11 -stdlib=libc++``. However, I still run into the following error:
```
"std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)", referenced from:
FastaIndex::entry(std::string) in libvcflib.a(Fasta.o)
FastaReference::open(std::string) in libvcflib.a(Fasta.o)
"std::basic_istream<char, …
```

Build and copy vcflib files for freebayes-parallel.

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/cwl2wdl/meta.yaml

Updates cwl2wdl and bcbio to support generation of WDL proposed structs.
Updates bcbio-vm to support AWS runs on non us-east regions.

Update: cwl2wdl, bcbio-nextgen, bcbio-vm

---

recipes/plant_tribes_assembly_post_processor/1.0.1/build.sh
recipes/plant_tribes_assembly_post_processor/1.0.1/meta.yaml

The enhancements to the AssemblyPostProcessor script are necessary as a work-around for issues in the current version of TransDecoder related to fasta accessions.  In our work, we discovered that the format of the fasta IDs in the TransDecoder output changes depending on the input fasta ID string.  These issues have been reported to the TransDecoder folks and will be addressed in an upcoming release.  In the meantime, the enhancements we've made to this version of AssemblyPostProcessor should be sufficient.

Bump PlantTribes AssemblyPostProcessor to version 1.0.1

---

recipes/json-collect-data-source/build.sh
recipes/json-collect-data-source/meta.yaml

Extension of the [json_data_source](https://github.com/mdshw5/galaxy-json-data-source) tool.
It allows to handle archives (gz, bz2, tar, and zip) organizing their content in a collection.
Reference [https://github.com/fabio-cumbo/galaxy-json-collect-data-source](https://github.com/fabio-cumbo/galaxy-json-collect-data-source)

JSON Collect Data Source

---

recipes/bioconductor-dupradar/meta.yaml

I found in some cases bioconductor-dupradar has a runtime error because it can't load `KernSmooth` in some functions. `KernSmooth` is one of the packages no longer included by default in R so this adds the dependency.

add kernsmooth dep to dupradar

---

recipes/crispresso/build.sh
recipes/crispresso/meta.yaml

* [  ] This PR adds a new recipe.
* [X ] This PR does something else (explain below).
There are some dep files for CRISPResso, by default they are copied in ~/CRISPREsso_dependencies, but this can be overridden by setting an env variable () before calling the setup. I have modified the build script to put those files in CONDA_ROOT/share. Please let me know if this is acceptable.
I am new to this so please let me know if I am missing something.
Thanks!

new recipe for CRISPResso 1.0.6

---

recipes/bcbio-nextgen/meta.yaml
recipes/fgbio/build.sh
recipes/fgbio/meta.yaml

- fgbio: latest release to avoid problems with temporary directories
and duplex reads
fulcrumgenomics/fgbio#256 fulcrumgenomics/fgbio#257
- bcbio: work around issue with google_compute_engine imports on Travis
builds by avoiding global import of boto

Update: fgbio, bcbio

---

recipes/bcftools/build.sh
recipes/bcftools/meta.yaml
recipes/htslib/meta.yaml
recipes/pysam/meta.yaml
recipes/samtools/meta.yaml

Update samtools, bcftools and htslib to latest 1.5 release, including
fixes for samtools multithread index problems. Bumps pysam requirements
to be compatible with latest release.

Update: htslib, samtools, bcftools to 1.5

---

recipes/netreg/build.sh
recipes/netreg/meta.yaml

Add netReg to Bioconda

---

recipes/toil/meta.yaml
recipes/variantbam/meta.yaml

- Toil: include fixes for PBSPro, AWS and local symlink runs
- VariantBam: QC flagging downsampled reads (walaj/VariantBam#9)
and large VCF line support (walaj/VariantBam#10)
[lint skip uses_git_url for recipes/variantbam]

Update: Toil, VariantBam

---

recipes/gffutils/build.sh
recipes/gffutils/meta.yaml

Fixes the build error `RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://files.pythonhosted.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz`

fix build.sh; bump build

---

recipes/perl-bioperl/meta.yaml

This was missed in #2876.
Also:
- change `perl-threaded` requiments to `perl`.
- remove requirements provided by `perl-bioperl-core` >= 1.6.924-pl5.22.0_2

Increase build number for perl-bioperl

---

recipes/whatshap/meta.yaml

Remove run dependency on setuptools. Use ``$PYTHON setup.py install --single-version-externally-managed --record=record.txt`` to avoid the problems discussed in pull request #5124.

Bump WhatsHap to version 0.14.1

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/gatk4/build.sh
recipes/gatk4/meta.yaml

- gatk4 -- move to latest beta.1 release with fixes for MuTect2 headers
- bcbio-vm -- Correct boto imports. Fixes chapmanb/bcbio-nextgen#1997

Update: gatk4, bcbio-vm

---

recipes/homer/meta.yaml

* weblogo, blat and ghostscript are no longer dependencies
* `configureHomer.pl` depends on gcc, wget, zip and unzip which are not present in the build environment

added deps for configureHomer.pl

---

recipes/fastx_toolkit/fastx.patch
recipes/fastx_toolkit/meta.yaml

This corrects the behavior of fastq_quality_filter, and contains the contents of agordon/fastx_toolkit@f65f634
This should bring galaxyproject/tools-iuc#1413 and galaxyproject/tools-devteam#375 closer to a mergeable state.

Apply fixes from upstream git repo.

---

recipes/metameta/1.0/build.sh
recipes/metameta/1.0/meta.yaml

As stated in the PR #5132 I needed the new version of the metameta tool (1.1) on bioconda but the folder with the version 1.0 was giving a strange error on travis ("permission denied" error trying to delete the "locks" file). I kept just the new version and passed the tests and now I'm bringing the old version back to keep it there.

bringing back metameta v1.0

---

recipes/bcftools/meta.yaml

Temporary workaround for issues with perl dependency resolution and
large dependencies in bcftools
chapmanb/bcbio-nextgen#2004

bcftools: remove tex and matplotlib deps

---

recipes/vispr/build.sh
recipes/vispr/meta.yaml

Fix incompatibility issues of vispr and new panda versions >=0.20. Require panda versions to be <0.20.

Update meta.yml to fix incompatibility issues

---

recipes/bcbio-prioritize/meta.yaml
recipes/bcbio-rnaseq/meta.yaml
recipes/bcbio-variation-recall/meta.yaml
recipes/bcbio-variation/meta.yaml
recipes/cramtools/meta.yaml
recipes/gatk/meta.yaml
recipes/oncofuse/meta.yaml
recipes/qualimap/meta.yaml
recipes/seqbuster/meta.yaml
recipes/trimmomatic/meta.yaml
recipes/varscan/meta.yaml
recipes/vcflatten/meta.yaml

Removes use of java-jdk and modernizes recipes to include checksums.
Aimed at avoiding double java installs of openjdk/java-jdk.

Move older recipes to use openjdk

---

recipes/perl-gdgraph-histogram/meta.yaml

```
~/miniconda_galaxy/bin/conda create -n mulled-v1-e83a3e475b70bd872ec10963ee67d0896b09886f6d7b371688258b06447c4b2e fastx_toolkit
Warning: 2 possible package resolutions (only showing differing packages):
- bioconda::perl-gdgraph-histogram-1.1-0.tar.bz2
- bioconda::perl-gdgraph-histogram-1.1-pl5.22.0_0.tar.bz2
…
Linking packages ...
[pango               ]|#####################################################################################################################                       |  83%
PaddingError: Placeholder of length '80' too short in package conda-forge::pango-1.40.1-0.
```
https://github.com/bioconda/bioconda-recipes/pull/5191#issuecomment-316620456
Let try a bump
ping @nsoranzo @Mataivic

perl-gdgraph-histogram - Bump build number

---

recipes/bcbio-nextgen-vm/build.sh
recipes/bcbio-nextgen-vm/meta.yaml
recipes/vcf2db/meta.yaml
recipes/vcfanno/meta.yaml

- vcf2db: correctly handle non-string values when calculation length.
Fixes chapmanb/bcbio-nextgen#2011
- vcfanno: Update to latest bug fix version
- bcbio-vm: Include CWL generation with local reference data. Thanks
to @brainstorm

Update: vcfanno, vcf2db, bcbio-vm

---

recipes/goleft/meta.yaml

This is specifically for `goleft depth` that parallelizes `samtools` calls. `samtools` is not a monstrous dependency to have so better include it rather than forcing user to install it upon `depth` subcommand failures (cc: @brentp)

Update goleft recipe to include samtools as a run requirement

---

scripts/bioconductor/requirements.txt

tl;dr This PR adds the Python dependencies pyaml and colorlog for building Bioconductor recipes.
I followed the [directions](https://github.com/bioconda/bioconda-recipes/blob/998a13938db4b0905b9a74e9d765749921c8fccc/scripts/bioconductor/README.md) to install the Python dependencies prior to running [bioconductor_skeleton.py](https://github.com/bioconda/bioconda-recipes/blob/998a13938db4b0905b9a74e9d765749921c8fccc/scripts/bioconductor/bioconductor_skeleton.py), but [requirements.txt](https://github.com/bioconda/bioconda-recipes/blob/998a13938db4b0905b9a74e9d765749921c8fccc/scripts/bioconductor/requirements.txt) didn't list pyaml or colorlog. After I added them and updated the conda environment, I was able to run the script.
As an aside, this script was really useful. Any chance of it …

Update requirements for bioconductor_skeleton.py.

---

recipes/r-downloader/build.sh
recipes/r-downloader/meta.yaml

Provides a wrapper for the download.file function, making it possible to download files over HTTPS on Windows, Mac OS X, and other Unix-like platforms. The 'RCurl' package provides this functionality (and much more) but can be difficult to install because it must be compiled with external dependencies. This package has no external dependencies, so it is much easier to install.

downloader R/CRAN package

---

recipes/r-ggthemes/build.sh
recipes/r-ggthemes/meta.yaml

Some extra themes, geoms, and scales for 'ggplot2'. Provides 'ggplot2' themes and scales that replicate the look of plots by Edward Tufte, Stephen Few, 'Fivethirtyeight', 'The Economist', 'Stata', 'Excel', and 'The Wall Street Journal', among others. Provides ‘geoms' for Tufte's box plot and range frame.

ggthemes R/CRAN package

---

recipes/r-km.ci/build.sh
recipes/r-km.ci/meta.yaml

Computes various confidence intervals for the Kaplan-Meier estimator, namely: Petos CI, Rothman CI, CI's based on Greenwoods variance, Thomas and Grunkemeier CI and the simultaneous confidence bands by Nair and Hall and Wellner.

km.ci R/CRAN package

---

recipes/bioconductor-signer/build.sh
recipes/bioconductor-signer/meta.yaml

I cannot build this package on macOS using llvm nor llvmdev as an alternative solution mentioned in #1332. So I followed the way RcppArmadillo was compiled on macOS using gcc and managed to compile the package.
The compilation error i got when using llvmdev was:
```
/private/tmp/miniconda/conda-bld/bioconductor-signer_1501610880420/_b_env_blah/lib/R/library/RcppArmadillo/include/armadillo_bits/Cube_bones.hpp:288:49: note: 
candidate template ignored: couldn't infer template argument 'functor'
template<typename functor> inline const Cube& transform(functor F);
^
```

Add bioconductor-signer

---

recipes/genometools-genometools/build.sh
recipes/genometools-genometools/meta.yaml

This is an update to add the genometools python bindings in order to add gff3toembl afterwards. (ref https://github.com/bioconda/bioconda-recipes/issues/5383 )
However, independently of my update the build now wouldn't pass the mulled-test with cairo activated so I had to remove it. I tried without removing the cairo dependencies but the test never passed.

Add python binding genometools

---

recipes/mira/meta.yaml

Following existing recipe approach and using the pre-compiled binaries from MIRA author Bastien Chevreux for either 64 bit Linux or Mac OS X (Darwin).

MIRA 4.0.2 is GPLv2+ and also available on Mac OS X

---

simulate-travis.py

Avoids causing the warning `Please run using "bash" or "sh", but not "." or "source"` when using `simulate-travis.py --bootstrap` (xref https://github.com/bioconda/bioconda-recipes/issues/5374#issuecomment-320710105)

save miniconda temp file with .sh ext to avoid "bash" or "sh" warnings

---

recipes/singlecell-barcodes/build.sh
recipes/singlecell-barcodes/meta.yaml

This recipe adds a repository of cellular barcodes used in single-cell sequencing along with descriptions of the read structure for each protocol. These can be tough to track down and understand, so this has them all in one place, organized in a way that makes it easy to parse programmatically.

Add singlecell-barcodes.

---

scripts/bioconductor/bioconductor_skeleton.py

Remove empty lines in build.sh generated with bioconductor_skeleton.py as discussed in https://github.com/bioconda/bioconda-recipes/pull/5428

Remove empty lines in build.sh generated with bioconductor_skeleton.py

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/rabix-bunny/build.sh
recipes/rabix-bunny/meta.yaml
recipes/toil/meta.yaml

- Toil: fix for CWL runs with multiple samples staging same files
- Rabix: update to 1.0.1, re-enable Docker runs
- bcbio: pin latest version of ipython-cluster-helper and CWL generation
fixes
- bcbio-vm: Support 2bit genomes

Update: toil, rabix-bunny, bcbio, bcbio-vm

---

recipes/mira/4.9.5/build.sh
recipes/mira/4.9.5/meta.yaml
recipes/mira/4.9.6/build.sh
recipes/mira/4.9.6/meta.yaml

MIRA's stable series is currently version 4.0.x, latest is version 4.0.2 - and I have therefore left ``recipes/mira/meta.yaml`` for the stable release.
MIRA's development series is currently version  4.9.x, most recently 4.9.5 and 4.9.6 - which I have defined with explicit sub-folders.
I am including 4.9.5 (for which only Linux binaries were provided) as this is/was used by one of my Galaxy wrappers https://github.com/peterjc/galaxy_mira/tree/master/tools/mira4_9
I am including 4.9.6 (Linux and Mac) as the current latest release.
Question: Should these development releases be tagged differently in conda? In practice the author has started recommending them now anyway, so I don't think it really matter.

mira 4.9.5 and 4.9.6 (developement series)

---

recipes/orthofinder/build.sh
recipes/orthofinder/meta.yaml

This adds the new version of orthofinder. I have removed the links to  tree_from_MSA because now everything should be run from the orthofinder script. One can add more software (mafft, fasttree) depending on the type of analysis needed but it is not compulsory. 
Cheers,

Orthofinder update 1.1.8

---

recipes/entrez-direct/build.sh
recipes/entrez-direct/ftp-cp.patch
recipes/entrez-direct/meta.yaml
recipes/entrez-direct/xtract.patch

This is a patch for fixing the xtract binary name. Without this patch the latest xtract version must be accessed by xtract.Linux our xtract.Darwin. Otherwise xtract alone is of version 2.9999 instead of 7.00. Plus there was a problem in one of the perl file to download the binary, fixed it in ftp-cp.patch.
Otherwise I have noted that the install scripts copies a bunch of files in the ${PREFIX}/bin folder, some that are not binarie, and that the setup.sh contacts CPAN to install dependencies, I have tried removing this steps to rely only on the bioconda dependencies but I'm not sure this is the proper way to proceed so they are not included in this PR. Tell me if you'd rather I put them back.

Update entrez direct

---

recipes/dunovo/build.sh
recipes/dunovo/meta.yaml

Making an optional feature not crash the tool if it fails (e.g. b/c of network error).
Passes `simulate-travis.py`.

Du Novo: Bump to 0.7.5: Make failures in --phone-home not fatal.

---

recipes/dunovo/meta.yaml

This is a very minor update that just bumps the version of Du Novo installed from 0.7.5 to 0.7.6.
Du Novo 0.7.6 itself is a two-line bugfix.

Du Novo: Update to 0.7.6 (bugfix).

---

recipes/igdiscover/meta.yaml

Seaborn 0.8, which has been released recently, contains a regression that
makes IgDiscover fail when creating some plots.

IgDiscover: Depend on seaborn 0.7

---

recipes/multiqc/meta.yaml

Trying to get the Python 3 build to work for MultiQC by explicitly setting the locale before running test commands.

MultiQC: Try to get py3 working by exporting a locale.

---

recipes/dunovo/build.sh
recipes/dunovo/meta.yaml

This update simply adds a line to `build.sh` to move the `VERSION` file to `$PREFIX/lib`. This allows the various scripts to find the current Du Novo version number, allowing the `--version` option to work. This also allows `--phone-home` to work, since that requires the version number.

Du Novo: Include VERSION file in build, to allow --version and --phone-home to work.

---

recipes/busco/build.sh
recipes/busco/generate-busco-config.py
recipes/busco/meta.yaml
recipes/busco/post-link.sh
recipes/busco/run_test.sh

Another attempt at #5429.
Since there's a lot going on with dependencies and paths, this recipe now includes a minimal functional test. Data (10MB) are temporarily downloaded within `run_test.sh`. The test includes a command similar to https://github.com/bioconda/bioconda-recipes/issues/5429#issuecomment-322312966.
@mschatz your comment shows that the config needs to be adjusted depending on the tool, so I had added back in the more flexible python config generator that is run in the post-link step. However the test seems to be running without special-casing the augustus paths or the env var, so we might be OK as-is. Is there something in the eukaryota_odb9 example you show that triggers a call to gff2gbSmallDNA.pl that is not being triggered in this test with proteobacteria_odb9?

Busco config

---

recipes/bcbio-nextgen/meta.yaml
recipes/gatk4/meta.yaml
recipes/mosdepth/build.sh
recipes/mosdepth/meta.yaml
recipes/rabix-bunny/build.sh
recipes/rabix-bunny/meta.yaml
recipes/schema-salad/meta.yaml
recipes/sentieon/meta.yaml

- gatk4: latest beta4 release with fixes for VCF headers and gVCF joint
calling
- mosdepth: 0.1.3 release with bcbio compatibility additions. Fix recipe
to make binary executable and link to conda htslib version.
- rabix-bunny: Fix docker defaults to avoid issues on systems without
docker.
- sentieon: update to latest version
- bcbio: include fix for avoiding dots in variable names

Update: gatk4, mosdepth, rabix-bunny, sentieon, bcbio

---

recipes/hmmer/2.3.2/meta.yaml
recipes/hmmer/meta.yaml
recipes/hmmer2/meta.yaml

Fixes an error in the meta data, the license for HMMER 2.3.2 is GPL v2 not v3 as per the ``LICENCE`` and ``00README`` files. It looks like HMMER3 switched to GPL v3.
Update the checksums from MD5 to SHA256.
Added notes metadata field to talk about having HMMER2 and HMMER3 installed in parallel.
Also expands the tool tests to check *all* the binaries are installed (especially important for the hmmer2 package to confirm the additional 2 is present on the filenames).

Updates to the HMMER recipes

---

recipes/trimmomatic/meta.yaml
recipes/trimmomatic/trimmomatic.sh

The custom wrapper script in the recipe checks for `$JAVA_HOME/bin/java` if `JAVA_HOME` is empty (`-z`) rather than if its non-empty (`-n`).

Fix JAVA_HOME ignored

---

recipes/pizzly/build.sh
recipes/pizzly/meta.yaml

This prepends a `pizzly_` prefix onto the scripts to make them more unique,
since they are generically named.
There are two python scripts that go along with pizzly that are missing from the installation, for now we grab them and prefix them with `pizzly_` to make them more unique.

Add missing pizzly scripts.

---

recipes/bwa/0.7.3a/build.sh
recipes/bwa/0.7.3a/meta.yaml

Based off of the bwa 0.7.8 recipe.
Based on md5sum pulled from sourceforge on 2017-09-07.
To get it to pass the `simulate-travis` tests, I added this to meta.yaml (taken from an earlier PR to add bwa 0.6):
```
test:
commands:
- bwa 2>&1 | grep 'index sequences'
```
but there do not appear to be tests for other bwa commands, so I'm not sure whether this is required.
At a minimum, it seems to build just fine.

Add bwa 0.7.3a recipe

---

recipes/uropa/build.sh
recipes/uropa/meta.yaml

Hi all,
UROPA (‘Universal RObust Peak Annotator’) is a python-based tool, intended for genomic region annotation. Based on a configuration file, different target features can be prioritized with multiple integrated queries. These can be sensitive for feature type, distance, strand specificity, feature attributes (eg. protein_coding) or the anchor position relative to the feature. UROPA can incorporate reference annotation files (GTF) from different sources, like Gencode, Ensembl, or RefSeq, as well as custom reference files produced by the user. UROPA is published under the doi: [10.1038/s41598-017-02464-y](https://www.nature.com/articles/s41598-017-02464-y).
Because of the requirement installation burden, we would like to include UROPA in bioconda to enable the usage for a wider target …

Added a recipe for UROPA

---

recipes/blast/boost_106400.patch
recipes/blast/build.sh
recipes/blast/meta.yaml

If `--with-hard-runpath` configure option is not used, BLAST programs search libraries first in the directories defined by the `LD_LIBRARY_PATH` environment variable, instead of using the rpath specified by conda.
Also add patch to support Boost 1.64.0 and later.

Fix BLAST 2.6.0 when LD_LIBRARY_PATH is defined

---

recipes/blast/2.5.0/boost_106400.patch
recipes/blast/2.5.0/build.sh
recipes/blast/2.5.0/meta.yaml

If `--with-hard-runpath` configure option is not used, BLAST programs search libraries first in the directories defined by the `LD_LIBRARY_PATH` environment variable, instead of using the rpath
specified by conda.
Also add patch to support Boost 1.64.0 and later.

Fix BLAST 2.5.0 when LD_LIBRARY_PATH is defined

---

recipes/rtg-tools/build.sh
recipes/rtg-tools/meta.yaml

Recipe no longer installs the "third-party" directory, as this is not required at runtime (it is included in the original distribution in order to provide source code to a modified library class).
Recipe now installs the "scripts" directory, which contains a bash-completion helper and some other small resources that may be useful to the end user. (Although this is optional and could be dropped if required.)
Recipe is explicit in settings for usage logging (false) and crash-only reporting (true).

update: rtg-tools 3.8.4

---

recipes/illumina-interop/build.sh
recipes/illumina-interop/meta.yaml

@matthdsm put up an interop recipe for Illumina's interop library in  #6015, but commented that the command names were very generic and looked for a solution. I agree - the names should be prefixed, otherwise I think they're likely to unintentionally shadow other tool names (plus harder to tell where they are from in scripts).
This recipe updates the illumina-interop recipe to prefix all commands with `interop_`.
Not sure what the policy is regarding these sorts of changes / respecting tool names.
cc @kyleabeauchamp

Illumina interop: Prefix command names with interop

---

recipes/spades/build.sh
recipes/spades/meta.yaml

spades genome assembler - on osx fetch binaries rather than compile, because compiling disables multi-threading (see https://github.com/ablab/spades/issues/30#issuecomment-329631647 )

spades genome assembler - on osx fetch binaries rather than compile

---

recipes/bcbio-nextgen/meta.yaml
recipes/sentieon/meta.yaml
recipes/toil/build.sh
recipes/toil/meta.yaml

- Toil: 3.11.0 release with fixes for batch system sleeps
- sentieon: 201704.03 with fix for BQSR platform unit
- bcbio: Add mock test to dependencies, no longer pulled by pytest-mock

Update: toil, sentieon, bcbio-nextgen

---

recipes/multiqc/meta.yaml

Networkx has recently been updated to 2.0, which is incompatible with `colormath` `spectra` dependency (see https://github.com/ewels/MultiQC/pull/561 and 
https://github.com/ewels/MultiQC/issues/592). Until a new `colormath` version is released, we have to downgrade `networkx` dependency for MultiQC.
cc @ewels

Downgrade networkx dependency

---

recipes/gnu-getopt/meta.yaml

gnu-getopt depends on gettext, which had a linking issue with 0.19.8 (fixed in 0.19.8.1). This bumps gnu-getopt to hopefully trigger a rebuild with gettext 0.19.8.1 from conda-forge
I'll also try to add gnu-getopt to conda-forge, but I submit this to bioconda now since conda-forge is slow to add new recipes. Edit: [PR to add to conda-forge is open](https://github.com/conda-forge/staged-recipes/pull/4063).

bump gnu-getopt build

---

recipes/ococo/build.sh
recipes/ococo/meta.yaml

Using master branch, software does not compile anymore. Furthermore it removes reproducibility.
Recipe may be improved to use htslib conda package but this fix at least the rebuild of the package.
Add hash to source.
* [ X ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ X ] This PR updates an existing recipe.

Set hstlib version to use as recipe clone master branch

---

recipes/vsearch/meta.yaml

This updates to the newest release of vsearch, also also supports reading `.gz` files directly.

Bump vsearch version and add .gz support

---

recipes/bioconductor-limma/meta.yaml

In this PR I've added statmod as a dependency to limma, as discussed in the Galaxy IUC PR here https://github.com/galaxyproject/tools-iuc/pull/1471 (cc @bgruening ) and also because in the limma user guide pg 9 (here: https://www.bioconductor.org/packages/devel/bioc/vignettes/limma/inst/doc/usersguide.pdf) it states "you’ll probably want biocLite("statmod)" as well".

bioconductor-limma - add statmod as dependency

---

recipes/blast/meta.yaml

Updates the recipe from BLAST+ 2.6.0 to 2.7.0
Also switched from HTTP to HTTPS in line with NCBI site changes.
Also switched from MD5 to SHA256 checksum.

BLAST+ 2.7.0

---

recipes/yara/build.sh
recipes/yara/meta.yaml

Hey @bioconda/core ,
there are also binaries that are compiled with SSE4 support and are therefore more efficient.
For the sake of maximizing compatibility, there are only the 64x packages in this recipe.
I have found three different ways so far to include the SSE4 packages which each have different requirements:
- Check for SSE4 support in meta.yaml:
This could be done by `{% set sse4_support = os.system("grep flags /proc/cpuinfo | grep sse4  > /dev/null") %} # [linux64]` for linux and a similar command for osx, but it would require os to be available in the jinja environment
- Download all sources and check for SSE4 support in build.sh:
This would require at least cond-build 3.0, so you can download different sources and put them in different folders by using the 'folder: <folder>' …

Yara 0.9.9 64x

---

recipes/ribotaper/meta.yaml

To overcome the error ``An error occurred while installing package 'defaults::r-base-3.2.2-0'. PaddingError: Placeholder of length '80' too short in package. (..) The package must be rebuilt with conda-build > 2.0.``

rebuild with newer conda-build

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/rabix-bunny/meta.yaml

- rabix-bunny: 1.0.2 release with improvements to caching
- bcbio, bcbio-vm: Generalize support for retrieval of BED files
from non-local directories.

Update: rabix bunny, bcbio, bcbio-vm

---

recipes/dunovo/build.sh
recipes/dunovo/meta.yaml

This update installs the 2.0.6 release of Du Novo, along with a few tweaks to the `meta.yaml`.
The main new thing in the conda recipe is installing a new submodule, `kalign`, and placing its `.so` files correctly after compilation.
Passes `simulate-travis.py` locally.

Du Novo: Update to 2.0.6.

---

recipes/backspinpy/meta.yaml

Some notes for reviewers:
* [backspinpy](https://pypi.python.org/pypi/backspinpy) implements the [BackSPIN](https://github.com/linnarsson-lab/BackSPIN) algorithm for clustering single cells based on their gene expression levels.
* I created the recipe using conda-build 3.0.19.
* The package exports a command-line tool, `backspin`, so I added a test for this.
* The license situation is confusing. In the `setup.py` it says the license is MIT ([link](https://github.com/linnarsson-lab/BackSPIN/blob/406c150e0e29979b06bdd418b9680186333e128d/setup.py#L21)); however, the file [LICENSE](https://github.com/linnarsson-lab/BackSPIN/blob/406c150e0e29979b06bdd418b9680186333e128d/LICENSE) in the repo is BSD-2. I tried to manually add the license file using the [conda-forge …

Add backspinpy from PyPI.

---

recipes/fgbio/meta.yaml

@chapmanb I think you added fgbio originally (thank-you!).  I am not sure why it requires python 2.7 only (I want python 3 support); perhaps the included script to run `fgbio`?  It feels odd to me to depend on a specific version of python when `fgbio` itself does not.  An alternate solution would be to (picard/meta.yaml)[https://github.com/bioconda/bioconda-recipes/blob/master/recipes/picard/meta.yaml]

Fgbio should be supported in any python version

---

recipes/racon/meta.yaml

This is an update to the run dependencies for racon.  The current recipe prevents installs on py3 environments because of a conflicting numpy/matplotlib requirement in the example script.  I don't think these should be enforced as strict run dependencies since the example script is discarded during install.  Also, the Unicycler recipe needs racon and is only py3 compatible

Racon: Remove python and mummer run deps

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/dx-cwl/build.sh
recipes/dx-cwl/meta.yaml
recipes/pysam/meta.yaml

- dx-cwl: Compile CWL workflows for DNAnexus
- pysam: update build string to provide most recent version with htslib
1.6 support (chapmanb/bcbio-nextgen#2127)
- bcbio: Include caching when preparing CWL with remote runner
- bcbio-vm: DNAnexus retriever improvements

New: dx-cwl, Update: pysam, bcbio, bcbio-vm

---

recipes/antismash/meta.yaml

MEME's FIMO tool changes output formatting in version 4.11.4+, so pin meme to the supported version of 4.11.2
Signed-off-by: Kai Blin <kblin@biosustain.dtu.dk>

antismash: Pin meme version to 4.11.2

---

recipes/manta/meta.yaml
recipes/strelka/meta.yaml

Update manta to v1.2.1 and strelka to v2.8.4. The binary releases for both packages now require Centos 6+.

Update to latest release for manta/strelka

---

recipes/mummer4/build.sh
recipes/mummer4/meta.yaml

This PR adds [mummer4](https://mummer4.github.io), which is partially backwards compatible with mummer3 syntax but includes niceties like multithreaded nucmer, out of the box 64bit support (any sized genome), read-based analysis and SAM output.
This does conflict with the `mummer` recipe that exists, in that the binaries have the same name.  I'm adding a new, `mummer4` recipe instead of updating the existing mummer recipe since the build process has changed and requires newer libgcc, which may not be compatible with existing environments.

Add Mummer4 recipe

---

recipes/dunovo/build.sh
recipes/dunovo/meta.yaml

Update to install Du Novo 2.0.8 (a bugfix release).
Also, change networkx dependency to version 1.10 to allow compatibility with Galaxy Toolshed (which lacks a 1.11).

Du Novo: Update to 2.0.8.

---

recipes/multiqc/meta.yaml

enum34 was missing as a dependency for MultiQC

---

recipes/multiqc/meta.yaml
recipes/multiqc/setup.patch

I had hoped that enum34 was only actually needed in python2.7, since `enum` was added in python 3.4. However, since it's listed in `setup.py` you get errors like the following if you actually try to run the current recipe:
```
$ multiqc ./
[INFO   ]         multiqc : This is MultiQC v1.3
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
File "/package/anaconda3/envs/MultiQC-1.3/bin/multiqc", line 724, in <module>
multiqc()
File "/package/anaconda3/envs/MultiQC-1.3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/package/anaconda3/envs/MultiQC-1.3/lib/python3.5/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File …
```

Get MultiQC working properly under python3

---

recipes/arvados-cwl-runner/meta.yaml
recipes/ericscript/avoid_bwa_update.patch
recipes/ericscript/meta.yaml
recipes/rabix-bunny/build.sh
recipes/rabix-bunny/meta.yaml

- rabix-bunny: Update to 1.0.3 to avoid permissions errors rabix/bunny#325
- ericscript: Avoid rebuilding bwa indices during runs chapmanb/bcbio-nextgen#2147
- arvados-cwl-runner: pin runtime to correct version of cwltool

Update ericscript, arvados-cwl-runner, rabix-bunny

---

recipes/chipseq-greylist/build.sh
recipes/chipseq-greylist/meta.yaml

This is a command line re-implementation of the ChIP-seq greylisting Bioconductor package written in python with some fixes to make it easier to use when building ChIP-seq pipelines.

Add chipseq-greylist.

---

recipes/spades/3.9.0/meta.yaml

I noticed that spades version 3.9.0 is not running on python 3.6 but conda does install it without dependency errors. I changed the recipe but I am not sure if that is the correct way of doing it.
```
$ spades.py --test; echo $?
== Error ==  python version 3.6 is not supported!
Supported versions are 2.4, 2.5, 2.6, 2.7, 3.2, 3.3, 3.4, 3.5
In case you have troubles running SPAdes, you can write to spades.support@bioinf.spbau.ru
Please provide us with params.txt and spades.log files from the output directory.
1
```

spades 3.9.0 with python 3.6

---

recipes/ucsc-bedgraphtobigwig/build.sh
recipes/ucsc-bedgraphtobigwig/include.patch
recipes/ucsc-bedgraphtobigwig/meta.yaml
recipes/ucsc-bedtobigbed/build.sh
recipes/ucsc-bedtobigbed/include.patch
recipes/ucsc-bedtobigbed/meta.yaml
recipes/ucsc-bigbedinfo/build.sh
recipes/ucsc-bigbedinfo/include.patch
recipes/ucsc-bigbedinfo/meta.yaml
recipes/ucsc-bigbedsummary/build.sh
recipes/ucsc-bigbedsummary/include.patch
recipes/ucsc-bigbedsummary/meta.yaml
recipes/ucsc-bigbedtobed/build.sh
recipes/ucsc-bigbedtobed/include.patch
recipes/ucsc-bigbedtobed/meta.yaml
recipes/ucsc-bigwiginfo/build.sh
recipes/ucsc-bigwiginfo/include.patch
recipes/ucsc-bigwiginfo/meta.yaml
recipes/ucsc-bigwigsummary/build.sh
recipes/ucsc-bigwigsummary/include.patch
recipes/ucsc-bigwigsummary/meta.yaml
scripts/ucsc/create-ucsc-packages.py
scripts/ucsc/include.patch
scripts/ucsc/template-build.sh
scripts/ucsc/template-meta.yaml
scripts/ucsc/ucsc_config.yaml

Also updates the `scripts/ucsc/*` files which were used to generate these recipes.
As discussed in https://github.com/bioconda/bioconda-recipes/issues/5430, this uses `mysql-connector-c` instead of the full `mysql` to reduce the size of the resulting packages. Other modifications include:
- build the bundled `htslib`
- make the meta.yaml files templated
- use sha256 instead of md5
- move osx-specific copying to build.sh
- fix patch file

round 1 of ucsc updates

---

.travis.yml

This PR modifies builds in two ways.
1. Linux and macOS builds happen in two stages. If the first stage (linux) fails, the second is not tried. While this could in theory make builds slower, the osx queue is in practice so slow that the difference should not be noticeable. Moreover the benefit is that we only fill the osx queue for builds that pass the linux tests. This should significantly improve the backlog situation within Bioconda.
2. The skipping of pushes in pull requests is now handled via conditions in the travis configuration. This means that, instead starting a job and exiting immediately, we do not even need to start the job. Again, this should help a lot with our queue. Further, it also makes the PR experience cleaner, because we have no pseudo-succeeded jobs.
ping …

Staged and conditional testing.

---

recipes/meraculous/meta.yaml

Meraculous use Perl functions that are depreciated in the newer version of Perl, which is the case in the default channel.  This may is probably not necessary to pin the Perl version right now if we can assume that users will always set conda's the channel preference based on bioconda's recommendation.  However it has not been the case in my experience.  Additionally, this change will mitigate the risk of conda-forge upgrading its default Perl to a version that is not compatible with Meraculous in the future.

Pin Perl verison in Meraculous to the current defualt in conda-forge

---

recipes/abyss/1.5.2/build.sh
recipes/abyss/1.5.2/create-wrapper.sh
recipes/abyss/1.5.2/meta.yaml
recipes/abyss/1.9.0/build.sh
recipes/abyss/1.9.0/create-wrapper.sh
recipes/abyss/1.9.0/meta.yaml
recipes/abyss/2.0.2-k128/build.sh
recipes/abyss/2.0.2-k128/create-wrapper.sh
recipes/abyss/2.0.2-k128/meta.yaml
recipes/abyss/build.sh
recipes/abyss/create-wrapper.sh
recipes/abyss/meta.yaml

@jamesabbott: I didn't consider overly long shebang lines when I recommended to replace `/usr` with `$PREFIX` in `abyss-pe`, my bad.
This creates a wrapper for `abyss-pe` and moves the original `abyss-pe` to `abyss-pe.Makefile`. Although it would be nicer to move it to `$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/abyss-pe.Makefile` or the like, I didn't do that since the makefile has a line
```
path?=$(shell dirname `which $(MAKEFILE_LIST)`)
```
which depends on the directory the makefile is in. If we want to move it out of `$PREFIX/bin`, we'd have to patch that too.
@pvanheus: sorry for the troubles!

abyss: add abyss-pe wrappers, fixes installs on long prefixes

---

recipes/fgbio/fgbio.py
recipes/fgbio/meta.yaml

I'm bumping up the memory allocated in the default invocation of fgbio via the wrapper script to 4GB from 1GB.  Most of the programs are fairly memory intensive and will struggle in 1GB.  4GB should be enough for most to succeed.

Bumped up the default memory for fgbio's JVM to 4g.

---

recipes/jannovar-cli/jannovar.sh
recipes/jannovar-cli/meta.yaml

…fied in jannovar sources must start withe de (de.charite.compbio....) not with org
bugfix in conda jannovar command (`jannovar.sh`). If main file is specified in jannovar sources must start withe `de` (`de.charite.compbio...`) not with `org`

bugfix in conda jannovar command (jannovar.sh)

---

recipes/pfam_scan/build.sh
recipes/pfam_scan/meta.yaml
recipes/trawler/build.sh
recipes/trawler/meta.yaml

e.g. Using -pfamB with pfam_scan.pl should return error code 1, but as written the wrapper script returned 0.
I've opted to use the simple one-line approach to setting the variable, which ensures the call is the last line of the script - and thus its return value gets passed back.

Ensure 2 perl wrapper scripts do not mask failures

---

recipes/abyss/1.5.2/build.sh
recipes/abyss/1.5.2/meta.yaml
recipes/abyss/1.5.2/osx-std_string_length-no-export.patch
recipes/abyss/1.9.0/build.sh
recipes/abyss/1.9.0/meta.yaml
recipes/abyss/1.9.0/osx-std_string_length-no-export.patch

* [ x AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
This updates `abyss 1.5.2` and `abyss 1.9.0` to enable builds on OSX (like it's done for the current version in https://github.com/bioconda/bioconda-recipes/pull/6867).
It also removes the explicit `--enable-maxk=96` parameter. This is no change for `1.9.0` (default already 96) but for `1.5.2` this now uses the default 64.

Abyss osx other versions

---

recipes/mgs-canopy/build.sh
recipes/mgs-canopy/meta.yaml

Likely resolves: https://github.com/bioconda/bioconda-recipes/pull/2499#issuecomment-347174900

canopy: target march=x86-64 instead of march=native

---

recipes/poretools/build.sh
recipes/poretools/meta.yaml
recipes/poretools/poretools.patch

- Use the Agg backend for matplotlib if saving to file. This eliminates the error message when the DISPLAY environment variable is unset, e.g. on a headless system.
- Add an option to output timestamps in UTC, in order to have reproducible output regardless of timezones.
- Inadvertently strip trailing whitespace on some lines.

Fixes for poretools conda package.

---

recipes/ragout/build.sh

See comments;  the make step creates executables that need to end up in the PATH so ragout can find them later.

Update Build to include executables from lib

---

recipes/bioconductor-snplocs.hsapiens.dbsnp144.grch38/meta.yaml
recipes/bioconductor-snplocs.hsapiens.dbsnp144.grch38/post-link.sh

https://bioconductor.org/packages/3.2/data/annotation/html/SNPlocs.Hsapiens.dbSNP144.GRCh38.html
Notes:
* I created the recipe using bioconductor-skeleton
* I tested it locally on a linux-64 machine, but if failed. This is my first recipe for a Bioconductor data package, so I'm not sure how to debug this. Output below:
```
$ ./simulate-travis.py --disable-docker --packages bioconductor-snplocs.hsapiens.dbsnp144.grch38
INFO:fetch.update:898581361
INFO:fetch.stop:None
INFO:conda_build.build:Packaging bioconductor-snplocs.hsapiens.dbsnp144.grch38-0.99.20-r3.4.1_0
BUILD START: bioconductor-snplocs.hsapiens.dbsnp144.grch38-0.99.20-r3.4.1_0
(actual version deferred until further download or env creation)
The following NEW packages will be INSTALLED:
bioconductor-biobase: …
```

Add Bioconductor data package SNPlocs.Hsapiens.dbSNP144.GRCh38.

---

recipes/haploclique/1.3.1/meta.yaml
recipes/nanopore_simulation/meta.yaml

While #6950 happened, two commits to `master` (https://github.com/bioconda/bioconda-recipes/commit/b273e3be8e868162f1bcd44173fb2220617c5863, https://github.com/bioconda/bioconda-recipes/commit/0d0b215a5c3099b8d058c02b97959622bd1a1ff5) didn't build for OSX.

nanopore_simulation, haploclique: trigger osx builds

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/dx-cwl/build.sh
recipes/dx-cwl/meta.yaml

- dx-cwl: avoid small machine partitioning for short jobs runs
- bcbio, bcbio-vm: Initial work on RNA-seq support and improved
remote retrieval of file references

Update: dx-cwl, bcbio, bcbio-vm

---

recipes/maker/meta.yaml

* [X ] This PR updates an existing recipe.
Trigger **maker** biocontainers image rebuild to use functional trnascan-se bioconda recipe, and allow trnascan-se to (eventually) be upgraded to version 2.0 (which unfortunately introduces some minor CLI option incompatibilities vs. trnascan-se 1.3.1, one of which affects maker 2.31.9).

Pin trnascan-se version to 1.3.1

---

recipes/perl-indirect/build.sh
recipes/perl-indirect/meta.yaml

@bioconda/perl So should I add this? This is not a bio related perl package, but as far as I can see anything perl currently lives in bioconda. Need this as a dependency of a proper bioinformatics tool.

add perl-indirect

---

recipes/bioconductor-bubbletree/meta.yaml
recipes/bioconductor-deseq2/meta.yaml
recipes/multiqc-bcbio/meta.yaml

- deseq2: pin required dependency versions for latest release
https://groups.google.com/d/msgid/biovalidation/e5fe0b7d-3a07-4f79-b78e-373724b31e55%40googlegroups.com
- bubbletree: include required genomeinfodb package
(chapmanb/bcbio-nextgen#2180)
- multiqc-bcbio: Fix support for read_count_multiplier in display

Update: DESeq2, Bubbletree, MultiQC_bcbio

---

recipes/deepvariant/build.sh
recipes/deepvariant/dv_call_variants.py
recipes/deepvariant/dv_make_examples.py
recipes/deepvariant/dv_postprocess_variants.py
recipes/deepvariant/meta.yaml
recipes/deepvariant/post-link.sh
recipes/deepvariant/pre-unlink.sh

DeepVariant with post-link based download of models, following up on
review and discussion in #7134. The whole genome model will be
downloaded on the users machine during installation.
This works on recent Ubuntu 16.04+, Centos 7+ with pre-built binaries.
Additional work to do:
- Uses pre-built binaries, building problematic due to clif dependency
- Need recent kernel with GLIBC > 2.23 due to pre-built htslib
- Build patches main.py in zip files to generalize python dependency
- Requires numpy 1.13, want to sync with CONDA_NPY
- Uses python wrappers that don't expose all underlying options
Fixes google/deepvariant#9

DeepVariant: 0.4.1 with post-link model download

---

recipes/bowtie2/build.sh
recipes/bowtie2/meta.yaml

```
Fixed major issue causing corrupt SAM output when using many threads (-p/--threads) on certain systems.
Fixed an issue whereby bowtie2 processes could overwrite each others' named pipes on HPC systems.
Fixed an issue causing bowtie2-build and bowtie2-inspect to return prematurely on Windows.
Fixed issues raised by compiler "sanitizers" that could potentially have caused memory corruption or undefined behavior.
Added the "continuous FASTA" input format (-F) for aligning all the k-mers in the sequences of a FASTA file. Useful for determining mapability of regions of the genome, and similar tasks.
```

Update Bowtie2 to 2.3.4

---

recipes/dunovo/build.sh
recipes/dunovo/meta.yaml

This updates the recipe to install Du Novo 2.0.12 instead of 2.0.9.
The new version has different dependencies, namely a switch from bowtie2 to bowtie, and dropping the samtools requirement.
I also rewrote `build.sh` to put the code for installing a submodule in a function, instead of repeating it for each of the 3 submodules.

Du Novo: Update to 2.0.12, reduce redundancy in build.sh.

---

recipes/fastqc/meta.yaml

I tried to run the biocontainer created with this recipe and got the following error: 
```
$ docker run -it -v $PWD:/data quay.io/biocontainers/fastqc:0.11.6--pl5.22.0_0
Started analysis of example.fq.gz
Analysis complete for example.fq.gz
Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.
at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1236)
```
I tried to figure out how the container was built but it seems that the biocontainer on Dockerhub works but is different than the one on quay.io (this is the one missing the font). 
cc @bgruening @luizirber

FastQC - Add fonts to fix biocontainer on quay.io 

---

recipes/picard/meta.yaml
recipes/picard/picard.sh

Turns out that quoting the arguments is an easy fix.
also removes a duplicated -o pipefail
fixes #7322
* [x ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).

quotes options passed to picard, updates picard to latest version

---

recipes/perl-text-balanced/build.sh
recipes/perl-text-balanced/meta.yaml

* [ X] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
When attempting to update a perl recipe that depends on this one (https://github.com/bioconda/bioconda-recipes/pull/7261), the mulled-build failed when installing gcc as previously required to build/run this recipe, apparently related to issue https://github.com/bioconda/bioconda-recipes/issues/3496. However, as no compiler is actually needed to build/run this perl module, I propose removing such dependencies from the recipe.

Remove unnecessary gcc build/run dependencies

---

.circleci/config.yml

This way, we save build time that would otherwise be wasted.
Otherwise, we would waste macos build time for every failed attempt to get a recipe working.

Only build on macos if linux succeeded outside of the master branch.

---

recipes/porechop/build.sh
recipes/porechop/meta.yaml

Followup to #7382. Adds some minor fixes and one crucial one: Due to a bug in `conda-build 2.1.x` Python won't get properly pinned if its version is constrained (and `python` is `build`+`run` requirement and not `noarch: python`), i.e., we get a Python version-specific package with a non version-specific build string.

porechop: fixes: python pinning

---

recipes/ipython-cluster-helper/meta.yaml

This relaxes some of the dependency pinning. Tested to work
on SGE and SLURM.
Pushing without local testing, I couldn't figure out how to get CircleCI working locally.

ipython-cluster-helper to 6.0.1.

---

.circleci/config.yml

In CircleCI's macOS image the locale isn't set with `LC_ALL` and `LANG`. Hence `click` will complain if run with Python 3, see https://github.com/bioconda/bioconda-recipes/pull/7417.
The variables are set to `en_US.UTF-8` which mirrors the `extended-base` image.
Tested on https://github.com/bioconda/bioconda-recipes/pull/7417 and works as intended.

.circleci: set LC_ALL+LANG to en_US.UTF-8 on macos

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

Avoids pinning to lower versions of ipyparallel to mirror improvements
in ipython-cluster-helper and avoid dependency issues.
* [] This PR adds a new recipe.

Update: bcbio, bcbio-vm; no ipyparallel pinning

---

recipes/porechop/meta.yaml

This PR points the source metadata to the (now updated) mainstream repo. As the upstream author chose a different version string for the branch/tag, and as this is a temporary workaround for the GCC issue, I have replaced the templated URL string with an explicit string. This seems preferable to modifying the recipe version when there are no actual changes to the package code. This can be replaced for the next upstream release.

Porechop update

---

recipes/bioconda-utils/meta.yaml

Updates the dependency on `conda`.
Also removes all build requirement apart from `python` and `setuptools` as they are not needed during the actual build.

bioconda-utils 0.11.4: fix conda dependency

---

recipes/octopus/build.sh
recipes/octopus/meta.yaml

This requires a recent compiler (7.2) and a newer boost (>=1.65) compiled
with this so uses a custom boost build. Once conda-forge and bioconda
migrate to conda-build 3 with support for these we can use a standard
package.

New: octopus, a haplotype based variant caller

---

recipes/multiqc-bcbio/meta.yaml
recipes/octopus/meta.yaml

- octopus -- ensure libstdc++ available as part of dependencies
for machines with older gcc
- multiqc-bcbio -- fix ordering and display of viral table

Update: octopus, multiqc-bcbio

---

recipes/perl-dbi/meta.yaml

Note that I still see https://github.com/bioconda/bioconda-recipes/issues/7415 upon issuing `circleci build`, even after a `docker pull bioconda/bioconda-utils-build-env:latest` to try to incorporate https://github.com/bioconda/bioconda-utils/pull/262 . Submitting this so someone can help troubleshoot.

Bump perl DBI version to 1.640

---

recipes/biodiff/build.sh
recipes/biodiff/meta.yaml
recipes/biodiff/osx.patch

@bioconda/core, this package uses the program `diff` on the system. The implementation that comes with MacOS may not be compatible.  Is there a way to exclude MacOS? I'd rather not maintain a conda package for GNU diff.

Add biodiff

---

recipes/sga/meta.yaml

* [] This PR adds a new recipe.
When running MacOS 10.13 (at least), llvm is required at runtime - without it you get the standard:
dyld: Library not loaded: @rpath/libc++.1.dylib
Referenced from: /Users/kastman/miniconda/envs/agape/bin/sga
Reason: image not found
Abort trap: 6

Add llvm as runtime req for osx (libc++ fail without it)

---

recipes/kraken/build.sh
recipes/kraken/meta.yaml

If the recipe is used with a conda environment with an at sign in the directory name, given the double quotes Perl would try to interpret this - and fail.
Note given the way the recipe works there will be no dollar signs present to worry about.
This is intended to fix a bug seen under Galaxy which used the form ``__prefix@_uv_`` in an environment name, and thus in the path. Perl didn't like this:
```
Global symbol "@_uv_" requires explicit package name (did you forget to declare "my @_uv_"?)
```
Cross reference https://github.com/galaxyproject/galaxy/pull/5498

Change path quoting in case of special chars like '@'

---

.circleci/config.yml
.circleci/setup.sh

This does a couple of small things in regard to the CircleCI configuration:
1. Explicitly installs `git` and `pip` to our Conda environment. Should be a no-op since `python` (and thus `pip`) and `git` are dependencies of `bioconda-utils`. But since we `pip install git+https://...` it doesn't hurt to be sure we have those dependencies in place.
2. Uses `--system` parameter for `conda config`. Without that parameter, I think, the configuration is written to the home directory and not `$WORKSPACE`. Since we cache `$WORKSPACE`, we should write it there. \[NOTE: I'm a little confused as to why we didn't already run into problems on macOS since the cache was activated there...\]
3. Checks `CIRCLE_PROJECT_USERNAME == bioconda` for the nightly uploads and exits early on forks.
4. ~\[**EDIT**: …

Circleci fixes

---

recipes/augustus/3.2.3_boost1.57/meta.yaml
recipes/augustus/3.2.3_boost1.57/patches/filterBam.src.Makefile.patch
recipes/augustus/meta.yaml
recipes/augustus/patches/filterBam.src.Makefile.patch

Finishes @jerowe 's work in #3500 to get Augustus compiling on OSX; this patches the filterBam Makefile to use  c++11 which fixes the "fatal error: 'unordered_map' file not found" also listed in #3284.

Fix Augustus build errors on OSX

---

.circleci/config.yml
.circleci/setup.sh

This is a followup to #7684 that just makes local builds source `/tmp/repo/docker-entrypoint-source` instead of `/opt/docker/bin/entrypoint_source`.

circleci: use docker-entrypoint-source for local build

---

.circleci/config.yml
.circleci/setup.sh

Pointing the remote upstream to the main repository does not work for the local build if it is already set. Here is a simple check, but I'm not sure it solves the problem completely. I still get an error:
```
====>> Setup bioconda-utils
#!/bin/bash -eo pipefail
.circleci/setup.sh
/usr/bin/scl_source: line 34: _scls[@]: unbound variable
Error: Exited with code 1
Step failed
Task failed
```

Circle ci add upstream check

---

recipes/krakenhll/meta.yaml

`krakenhll-build --standard` fails if perl's libwww is not installed. This adds the needed dependency.

Add missing libwww dependency

---

recipes/cancerit-allelecount/meta.yaml
recipes/genblastg/meta.yaml
recipes/gvcftools/meta.yaml
recipes/leptonica/1.73/meta.yaml
recipes/lighter/meta.yaml
recipes/megagta/meta.yaml
recipes/metavelvet/1.1.01/meta.yaml
recipes/metavelvet/meta.yaml
recipes/perl-compress-raw-zlib/meta.yaml
recipes/soapdenovo2-prepare/meta.yaml
recipes/soapdenovo2/meta.yaml
recipes/soapec/meta.yaml
recipes/somatic-sniper/meta.yaml
recipes/tesseract/3.04.01/meta.yaml
recipes/variant-effect-predictor/meta.yaml

cancerit-allelecount:
- add hash
genebastg:
- add hash
- corrected version number that didn't agree with downloaded file
gvcftools:
- add hash
leptonica:
- add hash
lighter:
- add hash
megagta:
- add hash
metavelvet (and legacy version):
- add hash
perl-compress-raw-zlib:
- add hash
soapdenovo2:
- add hash
soapdenovo2-prepare:
- add hash
soapec:
- add hash
somatic-sniper:
- add hash
tesseract:
- add hash
variant-effect-predictor:
- add hash

bulk hash-hunt, adding a bunch of missing hashes 

---

recipes/arvados-cwl-runner/meta.yaml
recipes/cgcloud-lib/meta.yaml
recipes/cwltest/meta.yaml
recipes/cwltool/meta.yaml
recipes/schema-salad/meta.yaml
recipes/toil/build.sh
recipes/toil/meta.yaml

Updates cwltool to latest release shared by Toil and Arvados CWL runner.
Includes matching updates to cwltool dependencies: cgcloud, cwltest and
schema-salad.
Unpins boto in toil, avoiding issues with old version of boto. Fixes
chapmanb/bcbio-nextgen-vm#167

Update: cwltool, cwltest, toil, arvados and deps

---

recipes/combined-pvalues/meta.yaml

Due to some deprecated functions in scipy, a subcommand of comb-p failed on recent versions from scipy. This is fixed in v0.48.
Best,
Jens

Bumped comb-p version to 0.48

---

build-fail-blacklist
recipes/prosolo/build.sh
recipes/prosolo/meta.yaml

This PR unblacklists this recipe from the bulk updates here:
https://github.com/bioconda/bioconda-recipes/issues/7712#issuecomment-366089958
A quick shout out to @johanneskoester as a major commiter of rust recipse: Do you approve the fix I am committing here? If yes, feel free to merge it directly -- I would then go about unblacklisting the other three recipes with the same failure. Some background and cross-references on the fix:
It seems the failures are down to this bug in conda build:
https://github.com/conda/conda-build/issues/2255
And the workaround is taken from here:
https://github.com/conda-forge/mosfit-feedstock/issues/23#issuecomment-349112622
(especially [this commit](https://github.com/guillochon/mosfit-feedstock/commit/7a3a9ca4236f7aa6e722d5b14dcb18b99f3de503) that is …

Unblacklist prosolo

---

recipes/racon/build.sh
recipes/racon/meta.yaml

This update uses git_url even if it is not recommended to fix the broken 0 first build. A typo in the recipe made it to download previous version. The reason for using git_url is 5 additional submodules in this updated version of racon. Maybe we could make an exception until the submodules are added to bioconda/conda-forge?

Fixing racon

---

recipes/cistrome-ceas/build.sh
recipes/cistrome-ceas/disable_no_mysqldb_warning.patch
recipes/cistrome-ceas/meta.yaml

@bioconda/core please review - this is my first recipe.
This PR submits a new recipe for the version of the CEAS 1.0.2 package which is available as part of the Cistrome project (https://bitbucket.org/cistrome/cistrome-applications-harvard).
The Cistrome version differs from the 'official' CEAS release as it adds support for bigWig-formatted files, and has been recommended by CEAS co-authors Tao Lui on the MACS mailing list: https://groups.google.com/d/msg/macs-announcement/LBhAtmC-Zho/AJCp5dmgkPYJ
As the source code on Bitbucket doesn't have an associated release tag, I've added the trailing `b1` to the version number (i.e. it's `1.0.2b1`) to indicate this. The commit ID is noted in the meta.yml file.
Please let me know if there are any issues that I need to address - many thanks!

Add recipe for cistrome-ceas

---

recipes/rna-seqc/meta.yaml

ping recipe to use java 7.
rna-seqc is using a version of javassist that is incompatible with java 8.

pin recipe to use java 7, see #4945

---

recipes/bioconductor-scde/meta.yaml

The latest version of flexmix (2.3-14) broke scde. Needs to be pinned to 2.3-13:
https://hms-dbmi.github.io/scde/help.html?place=msg%2Fsinglecellstats%2FrbFUTOQ9wu4%2Fyg4cxLbeAAAJ
xref: #7859 https://github.com/conda-forge/r-flexmix-feedstock/commit/92f7ee3936cc1dfc5483473fb19524c99f95ccee
Unrelated, but I also learned that the scde has an additional license file that restricts commercial use:
https://github.com/hms-dbmi/scde/blob/master/license.txt
Should I add this file and insert a `license_file` line? Is there anyway to alert users in `meta.yaml` that the software isn't really licensed under GPL-2?

Pin flexmix for bioconductor-scde.

---

recipes/anvio/meta.yaml

As suggested by @druvus,  after testing that Anvio 4 runs on pytohn 3.6, I'm adding py36 to the build configuration

adding Anvio 4 to py36

---

recipes/vcfpy/meta.yaml

Updating runtime dependency of vcfpy v0.11

---

recipes/emboss/fix_acd_path.py
recipes/emboss/meta.yaml

This fixes examples where filenames include spaces, e.g. https://github.com/biopython/biopython/issues/1523
```
$ needle -outfile="Emboss/temp with space.needle" -asequence=asis:ACCCGGGCGCGGT -bsequence=asis:ACCCGAGCGCGGT -gapopen=10 -gapextend=0.5 -snucleotide=True
$ water -outfile="Emboss/temp with space.water" -asequence=asis:ACCCGGGCGCGGT -bsequence=asis:ACCCGAGCGCGGT -gapopen=10 -gapextend=0.5
```
Without the fix, these examples used "Emboss/temp" as the output filename.

Quote arguments in EMBOSS wrapper scripts.

---

recipes/nextgenmap/0.4.13/build.sh
recipes/nextgenmap/0.4.13/meta.yaml

This PR adds an older version of NextGenMap, which is needed for reproducability since newer versions (> 0.5) seems to map some reads differently.

nextgenmap 0.4.13 (old version for reproducability)

---

recipes/krakenhll/meta.yaml

Argument mismatch in Bioconda's version where `krakenhll` calls `classify` with nonexistent `-r` option. Updated to the most recent commit.

Use updated KrakenHLL code

---

recipes/idr-py/meta.yaml

This library is used for accessing https://idr.openmicroscopy.org, will be used in concert with an environment file: https://github.com/IDR/idr-py/pull/11, and depends on `python-omero` which we [maintain](https://github.com/bioconda/bioconda-recipes/pull/8187).
* Created via `conda skeleton pypi idr-py`
* Dependency on python-omero added manually
----

idr-py: add recipe from PyPI

---

recipes/mdasim/meta.yaml

This PR tries to resolve this problem that is not caught by circleci:
Package for bioconda worked and the test and building in circleci all passed. However, installing it locally seems to give the following error:
```
mdasim: error while loading shared libraries: libmpi_cxx.so.40: cannot open shared object file: No such file or directory
```
At the same time, this exact file is present in the local miniconda3 libraries, as specified by the `openmpi` dependency -- only the location does not seem to be linked correctly during the build.

mdasim: attempt at fixing openmpi library linking issue

---

recipes/mir-prefer/meta.yaml

The initial recipe of miR-PREFeR locked samtools and bowtie to single versions which aren't required. This PR allows the version numbers to float upward following the original package's dependencies.

Open version numbers constraints

---

recipes/metfrag/meta.yaml

A possible way to use MetFrag is to pass a ZIP file of queries and run MetFrag on all of them. 
This requires the dependencies GNU Parallel and ZIP, which are available as conda packages.

Add dependencies required to run metfrag in batch

---

recipes/perl-uri/1.71/meta.yaml
recipes/perl-uri/meta.yaml

Remove unnecessary build/run dependencies that bloat install size, especially on macOS.
Not updated to latest version (1.73), as that would require Test::Needs (not on bioconda-recipes).

perl-uri: remove unnecessary build/run dependencies

---

recipes/augustus/build.sh
recipes/augustus/meta.yaml

Need some feedback from @bioconda/core regarding my change to the build string. I recently updated augustus to 3.3 and built it with [CGP support](http://bioinf.uni-greifswald.de/augustus/binaries/README-cgp.txt) and this pull request also adds sqlite support as well. I figured this should be noted in the build string instead of specifying the boost library and bamtools version, but I'm not sure. Maybe this is a job for [conda features](https://conda.io/docs/user-guide/tasks/build-packages/features.html).

include sqlite support in augustus 3.3 build

---

recipes/perl-perl-ostype/1.010/build.sh
recipes/perl-perl-ostype/1.010/meta.yaml

Requires perl-extutils-makemaker, perl-constant and perl-exporter which are present in bioconda but not conda-forge, so can not be submitted there...

Added new recipe for perl-perl-ostype

---

recipes/ont-tombo/meta.yaml

Changed micro versioning scheme so the most recent version is the default download from conda. Currently the 1.2.1b version is not downloaded by default since it is interpreted as a beta release.

Changed micro versioning scheme for ont-tombo (release 1.2.1.2)

---

.circleci/setup.sh
bootstrap.py
recipes/gffutils/meta.yaml

After we moved to CircleCI, it got harder to do local tests with mulled-build due to docker not running nicely from within docker using `circleci build`. This PR makes some changes to `.circleci/setup.sh` to make it play nicer with the new driver script `bootstrap.py`. The driver script creates a custom `activate` script to activate the new conda installation.
Example usage:
```bash
$ ./bootstrap.py /tmp/minconda
$ source activate ~/.config/bioconda/activate
(BIOCONDA-UTILS) $ bioconda-utils build recipes config.yml --mulled-build --git-range master
(BIOCONDA-UTILS) $ source deactivate
```

Enable easy local testing of mulled-build

---

.circleci/setup.sh
recipes/augustus/meta.yaml

As mentioned in https://github.com/bioconda/bioconda-recipes/issues/8549#issuecomment-379310530, MacOS uses `mktemp`, Linux uses `tempfile`.

Use mktemp on osx for bootstrap

---

recipes/htslib/build.sh
recipes/htslib/meta.yaml

In the process of testing my previous PR, I found that somehow the HTSLib binaries and libraries were not linking to libdeflate.  This PR updates the build commands and also adds tests that the binaries are actually linked to libdeflate.

Fix and test libdeflate in htslib recipe

---

recipes/sicer/genome_additions_v1.patch
recipes/sicer/meta.yaml

SICER contains hard-coded, mandatory genome reference data (chromosome codes, names, and lengths) that hasn't been updated in years. This patch adds annotations for all new builds for their included genomes from the intervening years. It also does a better job locking python=2.7

Sicer genome update 1

---

recipes/plant_tribes_gene_family_classifier/1.0.3/meta.yaml

Older versions of blast throw the following exception on some Linux systems, and this PR should correct this problem.
```blastp: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory```

Increase minimal blast version for plant_tribes_gene_family_classifier

---

recipes/fastqc/meta.yaml

Updating openjdk to come from conda-forge explicitly, rather than default. The openjdk in default is old and does not include fonts; the conda-forge version is the more recent. This change is also discussed in #8586 and #5026.
* <s>This PR adds a new recipe.</s>
* <s>This PR does something else (explain below).</s>

Fixing openjdk version for fastqc container

---

recipes/bioconductor-mspurity/meta.yaml

pin libnetcdf to version 4.4.*

---

recipes/t_coffee/meta.yaml
recipes/t_coffee/t_coffee/__main__.py
recipes/t_coffee/t_coffee/config.py

In #8715 I removed the setting of `DIR_4_TCOFFEE` env variable, but failed to notice that `PLUGINS_4_TCOFFEE` was not set, so `t_coffee` was searching the plugins in `~/.t_coffee/plugins/linux` , as per https://tcoffee.readthedocs.io/en/latest/tcoffee_technical_documentation.html#setting-up-the-variables .
Also:
- fix `MAFFT_BINARIES` env variable setting (multiple colon-separated paths are not supported)
- test that `t_coffee` can find the mafft plugin
- return the proper exit code from `t_coffee`
- find the correct `plugins` dir under macOS
- add missing `libgcc` run requirement

 Set PLUGINS_4_TCOFFEE env variable 

---

recipes/sourmash/meta.yaml

This will hopefully fix https://github.com/dib-lab/sourmash/issues/464#issuecomment-383843225, where `sourmash_lib` has been renamed to `sourmash` (but still exists for backwards compat).
Question - if we update this recipe without changing the hash or version, will new installs get the new recipe?

Fix issue to do with renamed sourmash_lib -> sourmash

---

recipes/perl-devel-stacktrace/meta.yaml

Version 2.03 of `Devel::StackTrace` is required by `Moose` 2.2009, which is currently the default version of Moose that is installed with `conda install perl-moose`. This PR also changes the `perl-threaded` requirement to `perl`, according to #3418.

Perl devel stacktrace update

---

recipes/umis/build.sh
recipes/umis/meta.yaml

Currently, umis is restricted to py27. This renders a usage within snakemake impossible. Since I was able to install umis==0.7.0 in py3 via pip, building for py3 in general should not be a problem.

Build umis for py3

---

recipes/idba/idba-kmer.patch
recipes/idba/meta.yaml

Patches idba such that also larger read length are possible for the short read input (250->600) and the separation for the Minimum/Maximum k value is increased (124->312). The patch has been submitted upstream: https://github.com/loneknightpy/idba/pull/41
The idea for the patch originated in the discussion on updating idba_ud for Galaxy: https://github.com/galaxyproject/tools-iuc/pull/1850 ping @bgruening 
Please note that this is more or less my first contact with conda. I read the docs only partially and made the changes more or less based on intuition (hoping for help by the community). I hope that this is OK .. and I can learn by doing (mistakes).

patch for idba allowing for longer short read sizes

---

recipes/blobtools/blobtools-build_nodesdb
recipes/blobtools/build.sh
recipes/blobtools/meta.yaml
recipes/blobtools/post-link.sh

This pull request adds the blobtools package, which is "A modular command-line solution for visualisation, quality control and taxonomic partitioning of genome datasets". I have found this pipeline very useful for assessing the quality of Illumina sequencing data generated from cultured bacterial DNA. It's especially useful for identifying and filtering low concentration contaminating sequences from these datasets.
As the NCBI taxdump db needs to be downloaded for this pipeline I have included a download script and a post-link.sh script to inform users that they need to run this prior to use. I've adapted this from the gatk recipe, however, I've had problems getting this post-link script to run with conda build 3.
Could @bioconda/core please review this new recipe? Especially the …

Added recipe for blobtools pipeline

---

recipes/bcbio-nextgen/meta.yaml
recipes/gatk/build.sh
recipes/gatk/meta.yaml

- Rename gatk scripts to prefix with gatk3 to avoid clashing with gatk4
package. bioconda/bioconda-recipes#8752
- Update bcbio with CWL fixes for Torque and building install tarballs

Update: gatk with gatk3 script prefix; bcbio

---

recipes/pypeflow/meta.yaml

In the absence of an official tag on the upstream repository, this uses the commit which bumped the version number to 0.1.1 (and at which point their ``setup.py`` dependencies have not changed).
See https://github.com/PacificBiosciences/pypeFLOW/issues/51, comments welcome from @pb-cdunn, @cschin or any of the pypeFLOW contributors.

Update BioConda pypeFLOW package to v0.1.1

---

recipes/mummer/meta.yaml
recipes/mummer/patches/gnuplot_mouse_clipboardformat.patch

Patch is based on changes in mummerplot v4 to cope with being run on gnuplot 5, with a tweak to still work on older versions of gnuplot. See also: https://github.com/mummer4/mummer/pull/64

Patch mummerplot to work with gnuplot 5

---

recipes/pypeflow/meta.yaml

This follows on from pull request #9016 for v0.1.1
In the absence of an official tag on the upstream repository,
this is the commit which bumped the version number to 1.0.0
See PacificBiosciences/pypeFLOW#51
Note that the dependencies declared in the setup.py changed,
which is reflected in the meta.yaml dependencies. It now
requires networkx.
Also, the updated setup.py declares additional python libraries
which we now test can be imported.

Update BioConda pypeFLOW package to v1.0.0

---

recipes/pypeflow/meta.yaml

In the absence of an official tag on the upstream repository, this is the commit which merged pull request 20 into the master branch, and that included the version bump.
See PacificBiosciences/pypeFLOW#51
There is a new futures dependency declared in their setup.py, which is a backport for Python 2 only. Given pypeFLOW does not yet support Python 3 this is perhaps not worth noting, but I marked this dependency as conditional.

Update to pypeFLOW v1.1.0

---

recipes/abundancebin/meta.yaml

This fixes the home page URL for the package. I have not bothered to bump the build number as I don't think this change means we need the package to be rebuilt.
Separately the software's license is not clear - has anyone reached out to the authors to pick a recognised open source license (and suggest hosting on GitHub or similar)?

Fix URL for abundancebin

---

recipes/r-ngsplot/build.sh
recipes/r-ngsplot/meta.yaml

So this should hopefully work and provide the base package of ngs.plot as a bioconda package, as requested [here](https://github.com/shenlab-sinai/ngsplot/issues/74) and  [here](https://github.com/nf-core/chipseq/issues/15).
One question regarding the packaging here remains open for me: This is NOT a "real" R package, but instead a bunch of R scripts that are bundled together, so I can't install these e.g. using `R CMD INSTALL --build .` similar to a standard CRAN or BIOCONDUCTOR package. I did this with symlinking the respective scripts (all of them!) in `bin` and that should probably work, however some feedback from @bioconda/core  would be great to be sure this is fine for everyone. Happy to do things differently, just nothing on the docs for such a case... 
Regarding the Databases …

Add r-ngsplot package

---

build-fail-blacklist
recipes/plastid/meta.yaml

Later versions of numpy are incompatible with the currently released
plastid: https://github.com/joshuagryphon/plastid/issues/18

Prevent plastid bug with newer numpy versions

---

recipes/phyluce/build.sh
recipes/phyluce/meta.yaml

Adding the python package [phyluce](https://phyluce.readthedocs.io), which is used to analyze target enrichment data collected from ultraconserved elements (e.g. http://ultraconserved.org/) and other genomic targets.  [phyluce](https://phyluce.readthedocs.io) includes lots of 3rd party dependencies, which I previously built and maintained on my own.  Porting over to bioconda makes dealing with those a whole lot easier.

Adding phyluce 1.6.2

---

recipes/verifybamid2/build.sh
recipes/verifybamid2/meta.yaml
recipes/verifybamid2/verifybamid2.sh

Wraps the new version of VerifyBamID, called VerifyBamID2 to avoid
confusion. They have overlapping binary names and confusion versioning
numbers, but are different efforts from the same group to approach
contamination estimation. This provides a shell wrapper, verifybamid2 that
provides access to resource files for 1000g and HGDP as background for
estimating contamination without needing to provide an external VCF
input.

New: VerifyBamID2 -- avoid overlapping with VerifyBamID

---

recipes/bam2fastx/1.3.0/meta.yaml
recipes/bax2bam/0.0.9/meta.yaml
recipes/blasr/5.3.2/meta.yaml
recipes/blasr_libcpp/5.3.1/meta.yaml

* Avoids ABI breakage when upgrading dependencies,
as all PacBio libraries use the Boost ABI versioning
scheme, i.e., every change of the version number
is potentially ABI breaking.

PacBio: Pin exact dependency versions

---

recipes/itero/meta.yaml

Update fixes an error that could cause MPI to hang.  It also adds
nomkl to package.

Update to itero v1.1.1

---

recipes/fasta-splitter/0.2.4/build.sh
recipes/fasta-splitter/0.2.4/meta.yaml
recipes/perl-file-util/build.sh
recipes/perl-file-util/meta.yaml

PR adds a new recipe for `fasta-splitter` 0.2.4. The recipe is in a `0.2.4` subdirectory of the `recipes/fasta-splitter` directory as this is not the most recent version.
The PR also adds a recipe for the Perl `File::Util` module, which `fasta-splitter` depends on; although this package is arguably not directly relevant to the biological sciences, it seems there are several similar packages in `bioconda` (do e.g. `conda search -c bioconda "perl-file*"` for examples).

Fasta splitter 0.2.4

---

recipes/vawk/build.sh
recipes/vawk/meta.yaml

The url git commit is an untagged commit made 2 years after the tagged 0.0.2 release. Should the recipe version still be 0.0.2?

lint vawk hash and noarch

---

.circleci/config.yml
.circleci/setup.sh

@bioconda/core
This does:
1. reenable CircleCI cache
2. reinstate the separate lint job for branches other than `master`/`bulk` (i.e., PRs)
3. remove some temporary workarounds
4. improve the error message for outdated CI config
5. update to a newer Miniconda version, because why not :)

ci: remove workarounds

---

recipes/sourmash/build.sh
recipes/sourmash/meta.yaml

Turns out #9533 broke sourmash because #9391 bumped the khmer version to `3.0.0a1` and we still don't support it in sourmash (yes, I see the irony). Instead of just fixing the khmer version and bumping the version number I also updated the recipe with other similar changes I saw in the khmer recipe.
I'll ping @corburn since he did the last khmer recipe changes.

Update sourmash recipe (fix khmer version)

---

.circleci/setup.sh

* [ X] This PR does something else (explain below).
On my macOS 10.11.6 workstation, `./bootstrap.py --no-docker /tmp/miniconda` hangs during the `tr` command in .circleci/common.sh, with the `tr` command continuing to consume CPU cycles without terminating due to the SIGPIPE that should result from the subsequent `head -c10`. Executing the command manually at the command line results in an error:
```
$ tr -dc a-z < /dev/urandom | head -c10
tr: Illegal byte sequence
```
A workaround is noted here:
https://unix.stackexchange.com/questions/45404/why-cant-tr-read-from-dev-urandom-on-osx
However, even implementing the LC_ALL/LC_TYPE workaround, `tr` still seems to not terminate. …

Use mktemp instead of tr ... < /dev/urandom for osx compatibility

---

recipes/libmems/build.sh
recipes/libmems/meta.yaml

Linking against libmems with boost 1.66 seems to have some problems, but earlier versions seem ok so pin to 1.65. Possible bugfix in 1.67 so pinning can hopefully be removed in future.
Newer boost versions also can not find symbols (e.g. boost::system::system_category) unless boost_system is last in list of libraries to link. libMems-1.6pc modified to provide libraries in appropriate order

pin against boost 1.65, fix pkg-config library ordering

---

recipes/sqt/meta.yaml

I’m getting this “WARNING” message over at #9581: 
```
Placeholder of length '80' too short in package /opt/conda/conda-bld/igdiscover_1530040000852/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python3.5/site-packages/sqt/_helpers.cpython-35m-x86_64-linux-gnu.so.
```
It’s not clear to me whether that is the reason for that PR failing, but I’m attempting to force a rebuild of sqt here to fix this.

sqt rebuild

---

build-fail-blacklist
recipes/rust-overlaps/build.sh
recipes/rust-overlaps/meta.yaml

Removes `rust-overlaps` from the blacklist, using the same fix from `rust-bio-tools`.

Fix rust-overlaps using the same fix from rust-bio-tools

---

recipes/fastqc/meta.yaml

The "defaults" build was bumped, leading to the defaults version of openjdk be installed, instead of the conda-forge one.  See #5026. To prevent the next build bump causing this issue again, increment the minimum version by one.

FastQC: Update the openjdk dependency.

---

recipes/fastp/meta.yaml

The old version v0.17.0 has a small bug in the HTML report. I fixed it several days ago and released v0.17.1

Update to fastp v0.17.1

---

recipes/jbrowse/meta.yaml

JBrowse's Bio::JBrowse::Cmd::FlatFileToJson uses Bio::FeatureIO, but this is not on the requirements list. This update adds the requirement and bumps the build version.

Add perl Bio::FeatureIO requirement

---

recipes/bioconductor-genomeinfodbdata/meta.yaml
recipes/bioconductor-genomeinfodbdata/post-link.sh

The specific reason I care about this is that my cluster environment seems to block the tcp port 80 (plain http) but allows 443/https.
While that reason may not be widely applicable, using https is a generally good idea and I see very few downsides to this change.

genomeinfodbdata: use https for download

---

recipes/multiqc-bcbio/meta.yaml
recipes/multiqc/meta.yaml
recipes/sentieon/meta.yaml

- MultiQC: fixes for peddy QC table display
- MultiQC-bcbio: improve display of viral QC with no hits
- Sentieon: bump sub-version to force build #9686

Update: MultiQC, MultiQC-bcbio, Sentieon

---

recipes/scrappie/meta.yaml

The previous recipe had an issue. It listed 'blas' as a dependency which should be 'openblas'. Apparently, that passed the testing the previous time? I reran the test today and now it failed. I replaced 'blas' with 'openblas', which seems to solve the issue.
See also https://github.com/nanoporetech/scrappie/issues/19

Fixing scrappie blas dependency

---

.circleci/config.yml

From Gitter conversion with @dpryan79:
https://gitter.im/bioconda/Lobby?at=5b30d85ab9c2fb2557097c8b:
>
>> Devon Ryan @dpryan79 13:56
Would it make sense to disable the nightly uploads (at least for OSX) while the bulk branches are getting updated a couple times a day? Since there's only one OSX build at a time on circleci this creates a bit of a backlog.
>
>> Marcel Bargull @mbargull 14:47
I'd rather not disable the nightly builds to keep the rebuild running. But maybe we could separate the Linux and macOS jobs into separate workflows for nightly as well as bulk uploads. That way we could easily restart/reschedule the macOS jobs (on demand) to make room for macOS builds on master and PRs. (If we don't separate them we'd have to needlessly stop running Linux jobs since the CircleCI UI only …

.circleci: separate workflows for Linux/macOs jobs on bulk/nightly uploads

---

build-fail-blacklist
recipes/bcbio-nextgen/meta.yaml
recipes/octopus/build.sh
recipes/octopus/conda_build_config.yaml
recipes/octopus/meta.yaml

- octopus: Re-enable builds using gcc 7.2, removing from blacklist.
Thanks to tips from #9904. Still uses custom boost build until
conda-forge boost available with 7.2 support.
- bcbio: latest development version with CWL ensemble support

Update: octopus, fix gcc 7.2; bcbio, ensemble support

---

recipes/rgi/meta.yaml

Though my own testing, I found that using a newer version of blast like 2.7.1, or a newer version of diamond like 9.2.2 will break RGI version 4.0.3 when running resistance gene detection using the `--alignment_mode DIAMOND` flag of `rgi main`
These exact matches should fix the aforementioned dependency issues.

Update RGI recipe to fix dependency problems

---

build-fail-blacklist
recipes/perl-test-yaml/build.sh
recipes/perl-test-yaml/meta.yaml

Update perl-test-yaml to 1.07

---

recipes/jbrowse/meta.yaml

Note that Perl module dependencies in general seem to be in a temporary state of disarray due to the Perl version mismatch issue articulated in https://github.com/bioconda/bioconda-recipes/issues/10100, though I assume this will be resolved in the future. 

Bump JBrowse version to 1.15.0

---

build-fail-blacklist
recipes/perl-perl-version/build.sh
recipes/perl-perl-version/meta.yaml
recipes/perl-type-tiny/build.sh
recipes/perl-type-tiny/meta.yaml

Fix 2 perl packages

---

recipes/msisensor/build.sh
recipes/msisensor/meta.yaml

add msisensor

---

recipes/r-ggrasp/build.sh
recipes/r-ggrasp/meta.yaml

Add r-ggrasp

---

recipes/pymisc-utils/build.sh
recipes/pymisc-utils/meta.yaml

Added recipe prototype for pymisc-utils

---

recipes/r-htssip/build.sh
recipes/r-htssip/meta.yaml

Add r-htssip

---

recipes/biokit/meta.yaml

update biokit to v0.4.4

---

recipes/chado-tools/build.sh
recipes/chado-tools/meta.yaml

command line tool to access CHADO databases

Chado tools

---

recipes/rgi/meta.yaml

This recipe should not skip py36, as version 4.0.3 of RGI primarily supports Python3. This change will enable rgi to work in Python3 environments.

Enable python3.6 build

---

recipes/Drop-seq_tools/build.sh
recipes/Drop-seq_tools/meta.yaml

Dropseq tools

---

recipes/toulligqc/meta.yaml

Update toulligqc to v0.10

---

recipes/isatools/meta.yaml

Update isatools to v0.10.2

---

build-fail-blacklist
recipes/fasttree/2.1.3/build.sh
recipes/fasttree/2.1.3/meta.yaml
recipes/fasttree/2.1.8/build.sh
recipes/fasttree/2.1.8/meta.yaml
recipes/fasttree/build.sh
recipes/fasttree/meta.yaml

Fix FastTree build.
Because FastTree is a single file it gets put into the `SRC_DIR` and we must change the build script accordingly. IN doing so I can see that CLANG will not build FastTreeMP so I moved that into a linux specif portion of the build

Fasttreecondbuild3

---

recipes/viennarna/2.4.5/build.sh
recipes/viennarna/2.4.5/meta.yaml
recipes/viennarna/build.sh
recipes/viennarna/meta.yaml

remove universal binaries for ViennaRNA

---

recipes/multiqc/meta.yaml

MultiQC version 1.6 release

---

recipes/lordfast/build.sh
recipes/lordfast/meta.yaml

adding recipe for lordfast

---

recipes/shovill/meta.yaml

Update shovill to 1.0.0

---

build-fail-blacklist
recipes/perl-file-fetch/build.sh
recipes/perl-file-fetch/meta.yaml
recipes/perl-file-sharedir-install/build.sh
recipes/perl-file-sharedir-install/meta.yaml
recipes/perl-file-sharedir/build.sh
recipes/perl-file-sharedir/meta.yaml
recipes/perl-html-tree/build.sh
recipes/perl-html-tree/meta.yaml

Perl fix 13

---

build-fail-blacklist
recipes/graphmap/build.sh
recipes/graphmap/meta.yaml
recipes/hera/build.sh
recipes/htseq/0.6.1/meta.yaml

Remove various packages from the blacklist

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml

Update: bcbio, bcbio-vm with WES support

---

recipes/mappy/meta.yaml
recipes/minimap2/meta.yaml

Updated minimap2 to v2.12

---

recipes/delly/meta.yaml

Trying to fix:
```
delly: symbol lookup error: delly: undefined symbol: _ZN5boost15program_options3argE
```
and seems like it might need a re-build after being unblacklisted.

delly: update to fix boost linker error

---

build-fail-blacklist
recipes/mlst/build.sh
recipes/mlst/meta.yaml

Also removes it from blacklist.

Update mlst to 2.11

---

build-fail-blacklist
recipes/starseqr/meta.yaml
recipes/strainest/build.sh
recipes/strainest/meta.yaml
recipes/strainest/strainest.patch
recipes/strudel/meta.yaml

Remove strainest, starseqr, strudel, and svtools from the blacklist

---

recipes/perl-lwp-protocol-https/build.sh
recipes/perl-lwp-protocol-https/meta.yaml

perl-lwp-protocol-https fix

---

recipes/sevenbridges-python/meta.yaml

Update seven-bridges-python to 0.15.2

---

recipes/crossmap/build.sh
recipes/crossmap/meta.yaml

Update CrossMap to version 0.2.8

---

build-fail-blacklist
recipes/flye/build.sh
recipes/flye/meta.yaml

fixed flye build error (due to zlib) - package removed from blacklist

---

recipes/lumpy-sv/build.sh
recipes/lumpy-sv/meta.yaml

The build for gh-10337 gave
```
20:12:37 BIOCONDA INFO Nothing to be done for recipe recipes/lumpy-sv
```
which is not correct of course. Trying to fix it here.
Best guess so far: The run-only `python` requirement picked up `python 3.*` and thus triggered `skip: True # [not py27]`?

lumpy: trying to fix skipped build

---

build-fail-blacklist
recipes/perl-bio-cigar/meta.yaml
recipes/perl-bio-db-sam/meta.yaml
recipes/perl-bio-eutilities/build.sh
recipes/perl-bio-eutilities/meta.yaml

Unblacklist some other perl-bio-*

---

recipes/helperlibs/build.sh
recipes/helperlibs/meta.yaml

Update helperlibs to release-0-1-9

---

recipes/binsanity/build.sh
recipes/binsanity/meta.yaml

Update binsanity to 0.2.6.3

---

recipes/snippy/3.2/build.sh
recipes/snippy/3.2/meta.yaml
recipes/snippy/build.sh

Update snippy to 4.0.0

---

build-fail-blacklist
recipes/perl-image-exiftool/build.sh
recipes/perl-image-exiftool/meta.yaml
recipes/perl-test-output/build.sh
recipes/perl-test-output/meta.yaml
recipes/perl-text-nsp/build.sh
recipes/perl-text-nsp/meta.yaml

Perl fix 17

---

build-fail-blacklist
recipes/r-ngsplot-hg19/meta.yaml
recipes/r-ngsplot-hg38/meta.yaml
recipes/r-ngsplot-mm10/meta.yaml
recipes/r-ngsplot/meta.yaml

This removes the ngsplot, ngsplotdb-[hg19,hg38,mm10] recipes from the blacklist. They're all fine, but had a small issue with the installation of the datasets unfortunately, which I fixed in a separate PR yesterday.

Remove ngsplot/ngsplotdbs from blacklist

---

recipes/vt/meta.yaml

I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).

Allow vt to build on macOS

---

recipes/gffmunger/build.sh
recipes/gffmunger/meta.yaml

@bioconda/core please review my my first pull request, and first receipe
first commit for gffmunger
(Munges GFF3 files exported from Chado database to make them suitable for loading into WebApollo)
recipe shamelessly ripped off from chado-tools with minimal tweaks
* [y ] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [y ] This PR adds a new recipe.
* [y ] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [n ] This PR updates an existing recipe.
* [n ] This PR does something else (explain below).

new recipe: gffmunger

---

recipes/python-intervaltree/build.sh
recipes/python-intervaltree/meta.yaml
recipes/python-sortedcontainers/build.sh
recipes/python-sortedcontainers/meta.yaml

Actual Python package is called 'intervaltree'. Note that bioconda
already has 'intervaltree_bio'

New: python-intervaltree @ 2.1.0

---

recipes/bwa/0.7.4/build.sh
recipes/bwa/0.7.4/meta.yaml

Hello @bioconda/core, I have updated BWA to include version 0.7.4. This version is used heavily for McClintock a TE finding software https://github.com/bergmanlab/mcclintock . This update should allow us to be able to more easily create environments for mcClintlock. 
I modified the current recipe in BWA to include the new version and abided by the best practices as outlined by the bioconda guides. 
Best,
Pablo Mendieat

Version 0.7.4 of BWA

---

recipes/perl-compress-bgzf/0.005/build.sh
recipes/perl-compress-bgzf/0.005/meta.yaml

Compress::BGZF

---

recipes/bcbio_monitor/meta.yaml
recipes/eden/meta.yaml

Follow up to
https://github.com/bioconda/bioconda-recipes/pull/10527
and
https://github.com/conda-forge/staged-recipes/pull/6532#issuecomment-414265097
gh-10527 removed the recipe for `bioconda::py-graphviz` which is the same package as `conda-forge::python-graphviz` so we should use the latter as a dependency.

bcbio_monitor + eden: update depedency of graphviz python package

---

recipes/quast/meta.yaml

Circos dependency added to meta.yaml to prevent bioconda revert back to QUAST 4.6.3 when installing Circos.
The issue is caused by Perl packages required by Circos and built with deprecated Perl 5.22.0 on macOS. See https://github.com/bioconda/bioconda-recipes/issues/10100 for more details. 
Note that QUAST 4.6.3 has pretty the same dependencies as 5.0.0 (at least it also requires Perl) but it was built using the previous version of bioconda and Perl version is not specified there explicitly. 
Also note: if Circos is installed, QUAST can draw Circos plots automatically (--circos option). This functionality was added since version 5.0

QUAST 5.0.0: circos dependency added

---

recipes/slicedimage/meta.yaml

The `slicedimage` recipe is primarily intended as a prerequisite for `starfish`. While testing a development environment.yml file:
```
name: starfish
channels:
- defaults
- bioconda
- conda-forge
dependencies:
- python>=3.6
- click
- pandas>=0.23.4
- pytest>=3.6.3
- regional
- scikit-image>=0.14.0
- scikit-learn
- semantic_version
- showit==1.1.4
- slicedimage==0.0.1
- tqdm
- trackpy
- validators
- xarray
```
this error was raised:
```
UnsatisfiableError: The following specifications were found to be in conflict:
- python >=3.6
- slicedimage ==0.0.1 -> enum34 -> python 3.3* -> xz 5.0.5
Use "conda info <package>" to see the dependencies for each package.
```

slicedimage: skip enum34 on py2k

---

recipes/slicedimage/meta.yaml

cF. https://github.com/spacetx/slicedimage/pull/48 to fix the underlying enum34 issue
seealso: https://github.com/bioconda/bioconda-recipes/pull/10637

Bump slicedimage to 0.0.2

---

recipes/perl-sys-info-base/build.sh
recipes/perl-sys-info-base/meta.yaml

This recipe builds a conda package for the Perl module Sys::Info::Base.
* No, this a general purpose package. However, virtually all Perl packages are in Bioconda, including the 58 (recursive) dependencie. Since CondaForge does not allow Bioconda dependencies in their recipes, I decided to upload this recipe here.

Added recipe for perl-sys-info-base.

---

recipes/perl-test-sys-info/build.sh
recipes/perl-test-sys-info/meta.yaml

* No, this a general purpose package. However, virtually all Perl packages are in Bioconda, including the 58 (recursive) dependencie. Since CondaForge does not allow Bioconda dependencies in their recipes, I decided to upload this recipe here.

 Added recipe for Perl module perl-test-sys-info. 

---

recipes/perl-math-random-mt-auto/build.sh
recipes/perl-math-random-mt-auto/meta.yaml

* No, this a general purpose package. However, virtually all Perl packages are in Bioconda, including all dependencies of this one. Since CondaForge does not allow Bioconda dependencies in their recipes, I decided to upload this recipe here.

Added recipe for Perl package perl-math-random-mt-auto.

---

recipes/perl-sys-info-driver-osx/build.sh
recipes/perl-sys-info-driver-osx/meta.yaml

* No, this a general purpose package. However, virtually all Perl packages are in Bioconda, including all dependencies of this one. Since CondaForge does not allow Bioconda dependencies in their recipes, I decided to upload this recipe here.

Added recipe for Perl package perl-sys-info-driver-osx.

---

recipes/bcbio-nextgen/meta.yaml

Initial work on simplifying bcbio dependencies to avoid long install
times. Removes:
- azure -- should get pulled in at bcbio-vm level like with boto
- patsy, path.py, sqlalchemy -- do not appear to be used
- tornado -- bcbio server client removed

Update: bcbio; simplifying dependencies

---

recipes/focus/meta.yaml

Sorry @bgruening. I believe this may be the last update until FOCUS a new release comes up. The current recipe works fine, but when i try to create a conda enviroment (e.g. `conda create -n focus_run -c bioconda focus`), Jellyfish `2.2.6` is giving me a `Segmentation fault: 11` error when counting k-mers on the enviroment I created (outside of the enviroment it works fine). So I tested it with Jellyfish `2.2.3`, and it worked fine.

change jellyfish on focus

---

recipes/mccortex/build.sh
recipes/mccortex/meta.yaml
recipes/mccortex/run_test.sh

Adds recipe for mccortex

---

recipes/hicexplorer/meta.yaml

Fixing dependency issues with numpy caused by wrong conda-forge compatibility declaration of numpy versions.

Fixing dependency issues with numpy

---

recipes/rmblast/boost_106400.patch
recipes/rmblast/boost_106500.patch
recipes/rmblast/build.sh
recipes/rmblast/isb-2.6.0+-changes-vers2.patch
recipes/rmblast/meta.yaml

Rmblast is using an old boost version which creates dep problems with repeatmasker, maker and perl.
As there's a 2.6.0 version, let's update it... Now it's just a patch on top of standard blast, so I just adapted the blast recipe

Rmblast: update to 2.6.0

---

recipes/meme/meta.yaml

MEME: update to 5.0.2 + compile with mpi support

---

.circleci/config.yml

The local `circleci build` based testing recently failed because the `--prelint` option has been removed from bioconda-utils. This is fixed here.

Fix bioconda-utils invocation in case of local circleci client usage.

---

recipes/pb-falcon/meta.yaml

Apparently, this is because the build-prefix changed
while the version string did not, so the new builds
are not alphabetically successive.

pb-falcon: Must bump ver for conda update to work

---

recipes/pb-falcon/meta.yaml

Attempting to solve this problem:
```
% conda install pb-falcon=0.2.1
Solving environment: failed
UnsatisfiableError: The following specifications were found to be in
conflict:
- pb-falcon=0.2.1
- pbalign -> pbbam[version='>=0.18.0'] -> htslib=1.7
```

pb-falon: htslib=1.7

---

recipes/pb-assembly/meta.yaml

The problem was that pb-falcon-phase was built with `-march=native`,
so we needed to update/rebuild a chain of dependencies.

pb-assembly: bump ver and req non-broken pb-falcon

---

recipes/peptide-shaker/meta.yaml
recipes/peptide-shaker/peptide-shaker.py

Internal improvements:
- Added default protein, peptide and PSM reports that also include the non-validated hits. Note: Some of the numbers used to refer to the previous reports have changed and that you may need to update your command lines. Check PeptideShaker documentation for the new ids.
- Updated utilities to version 4.12.8 (better management of gene-mappings).
- Bugfixes

PeptideShaker: updated version to 1.16.29

---

recipes/flashlfq/FlashLFQ.sh
recipes/flashlfq/meta.yaml
recipes/pisces/meta.yaml
recipes/pisces/pisces.sh
recipes/pisces/pisces_vqr.sh

Following #8155 where I fixed a problem with the EMBOSS wrappers breaking when used with filenames with spaces, I used the following grep command to identify other cases of the same underlying issue - two cases identified and fixed in this pull request.
```
$ grep " \$\@" */*/*.sh
recipes/perl-html-tidy/build.sh: 	$(RM_F) $@
recipes/perl-html-tidy/build.sh:-	$(LD)  $(LDDLFLAGS) $(LDFROM) $(OTHERLDFLAGS) -o $@ $(MYEXTLIB)	\
recipes/perl-html-tidy/build.sh:+	$(LD) $(LDFROM) $(LDDLFLAGS) $(OTHERLDFLAGS) -o $@ $(MYEXTLIB)	\
recipes/perl-html-tidy/build.sh: 	$(CHMOD) $(PERM_RWX) $@
recipes/watchdog-wms/run_test.sh:function timeoutbash() { bash -c '(sleep 180; kill -9 $$ 2>/dev/null) & exec $@' $0 $@; }
```
The remaining grep matches are in the ``perl-html-tidy`` recipe's patch (the underlying …

Quote in case of spaces

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/delly/Makefile.patch
recipes/delly/conda_build_config.yaml
recipes/delly/meta.yaml

- Fix delly installs with new compiler defaults. Doesn't build with
boost and new compilers like octopus and salmon, so use libboost.
Fixes delly lookup errors with old boost:
```
delly: symbol lookup error: delly: undefined symbol: _ZN5boost15program_options3argE
```
- Update bcbio, bcbio-vm to support CWL builds with reference data
versions enumerated.

Update: delly (boost fix); bcbio, bcbio-vm (CWL fixes)

---

recipes/maker/build.sh
recipes/maker/meta.yaml
recipes/maker/mpi_init.patch

This should fix a problem with Maker: currently, the first time running Maker with MPI, some C code is compiled by perl-inline-c in the install directory. This is a problem in multiuser env = fails with permission denied
with this patch, the code is compiled when building the conda package

Maker: precompile inline C code for MPI support

---

recipes/weeder/meta.yaml
recipes/weeder/weeder2.py

PR to update recipe for the `weeder` package, specifically it updates the Python wrapper script to fix an egregious bug whereby any valid non-trivial command line (i.e. anything except the `-h`/`--help` or any empty argument list) resulted in the wrapper calling itself with the same arguments, and so on *ad infinitum*.
As an aside: when I first encountered this bug, the infinite recursion ultimately consumed all available memory and effectively crashed the workstation I was running on. AFAIK this would happen for any non-trivial usage of the program, which would suggest that the original changes were never tested by their author.
There are a couple of other changes:
* Updates `meta.yml` to include C++ compiler as a build requirement (C compiler didn't seem to be enough when I tried to …

Weeder2 fix wrapper script

---

recipes/wtdbg/meta.yaml

The project name was wrongly spelled in the earlier PR today. I am sorry for this mistake...

Fixed wrong project name: changed wtdbg2 to wtdbg

---

recipes/bcbio-nextgen-vm/meta.yaml
recipes/bcbio-nextgen/meta.yaml
recipes/vardict-java/meta.yaml
recipes/vardict/meta.yaml

- vardict-java: 1.5.5 release with fixes for boundary errors
- vardict: compatibility with 1.5.5 java release
- bcbio, bcbio-vm: support for Google Storage and http URLs in CWL

Update: vardict-java, vardict, bcbio, bcbio-vm

---

recipes/bcbio-nextgen/meta.yaml
recipes/cromwell/meta.yaml

- cromwell: adds support for gs and http URLs in workflows
- bcbio: supports cromwell 35 with back compatibility for older
version. Avoids speed issue on 35 pre-processing. Fixes
chapmanb/bcbio-nextgen#2527

Update: cromwell (35), bcbio

---

recipes/ensembl-vep/build.sh
recipes/ensembl-vep/meta.yaml

VEP: bump major version

---

build-fail-blacklist
recipes/bioconductor-purecn/build.sh
recipes/bioconductor-purecn/meta.yaml

PureCN development (https://github.com/lima1/PureCN) has several
improvements over the BioC 3.6 release for handling multiple VCF input
types, and is back compatible with R 3.4.1 so still builds cleanly
with two new dependencies.
Also exposes PureCN wrapper scripts for running from the command line.
Prefixes ambiguous scripts with PureCN_.

Update: PureCN to latest devel (1.11.13); wrapper scripts

---

recipes/rfmix/build.sh
recipes/rfmix/meta.yaml

New recipe for RFMix

---

recipes/fsm-lite/build.sh
recipes/fsm-lite/meta.yaml

Add recipe for fsm-lite

---

recipes/fastqc/0.11.7/build.sh
recipes/fastqc/0.11.7/java_xms.patch
recipes/fastqc/0.11.7/meta.yaml
recipes/fastqc/meta.yaml

just an update. needed here: https://github.com/galaxyproject/tools-iuc/pull/2115

fastqc: update to version 0.11.8

---

recipes/dnp-binstrings/build.sh
recipes/dnp-binstrings/conda_build_config.yaml
recipes/dnp-binstrings/meta.yaml
recipes/dnp-corrprofile/build.sh
recipes/dnp-corrprofile/conda_build_config.yaml
recipes/dnp-corrprofile/meta.yaml
recipes/dnp-diprofile/build.sh
recipes/dnp-diprofile/conda_build_config.yaml
recipes/dnp-diprofile/meta.yaml
recipes/dnp-fourier/build.sh
recipes/dnp-fourier/meta.yaml

Dinucleotide patterns analysis tools v1.0

---

recipes/metabat2/build.sh
recipes/metabat2/meta.yaml
recipes/taxator-tk/build.sh
recipes/taxator-tk/meta.yaml

Metawrap preqs2

---

recipes/gemma/build.sh
recipes/gemma/meta.yaml

gemma 0.98

---

recipes/dca/meta.yaml

Add DCA recipe

---

recipes/segtools/meta.yaml

Reverts bioconda/bioconda-recipes#9073 as the merge build failed due to the pinned rpy2 versions not being available for R3.5.
https://circleci.com/gh/bioconda/bioconda-recipes/29151

Revert "Update recipe for Segtools 1.2.1 for both Python 2 and Python 3"

---

recipes/umis/meta.yaml

New version of click changes the way subcommands are named, so cb_filter ->
cb-filter which affects downstream stuff built on top of this repo. This moves
umis to that version of click, since it seems like it will be the default
behavior going forward.
click changed the way subcommands are named, _ separators go to - in 0.7.0. This ensures umis is distributed with the right version of click.

Ensure umis gets click 7.0 along with it.

---

recipes/motus/meta.yaml

Using `noarch: True` made the package compatible with all platforms (#10125) but caused all [containers](https://quay.io/repository/biocontainers/motus?tab=tags) to default to building with python 2.7. 
In light of the limitations mentioned in https://github.com/conda/conda-build/issues/542#issuecomment-130870047 this pull request sets the requirement to python 3.

Update motus to build only for python3

---

recipes/r-dartr/meta.yaml
recipes/r-deconstructsigs/meta.yaml
recipes/r-gkmsvm/meta.yaml
recipes/r-phylosignal/meta.yaml
recipes/r-rapidr/meta.yaml
recipes/r-sigQC/meta.yaml
recipes/r-sigtree/meta.yaml
recipes/r-stampp/meta.yaml

Various CRAN package fixes, since they all lack license files

---

recipes/r-polysat/build.sh
recipes/r-polysat/meta.yaml

Add r-polysat version 1.7-3

---

recipes/bioconductor-biomart/meta.yaml

* [ x] I have read the [guidelines for bioconda recipes](https://bioconda.github.io/guidelines.html).
* [ x] AFAIK, this recipe **is directly relevant to the biological sciences** (otherwise, please submit to the more general purpose [conda-forge channel](https://conda-forge.org/docs/)).
* [ x] This PR updates an existing recipe.
Hello , I am updating version of biomaRt because the current one didn't work with R above 3.4. It passed the basic "bootstrap" tests without CircleCI locally. (Please note: this is my first bioconda recipe.)
Thanks for review.

Update biomart version so that compatible with r351

---

recipes/sonicparanoid/build.sh
recipes/sonicparanoid/meta.yaml

Added recipe for SonicParanoid 1.0.13

---

recipes/meme/build.sh
recipes/meme/meta.yaml

This PR is for two changes that allow `meme-chip` to run smoothly when built with python 3. The first change is to add `perl-json` to the requirements list to allow the final `meme-chip_html_to_tsv` step of `meme-chip` to run without errors. The second change is to modify the `meme-chip` script to execute `dreme-py3`, the python 3 version of `dreme`, if the package is built with python 3.

Fixes to meme-chip with python3.

---

recipes/r-coloc/meta.yaml
recipes/r-metama/meta.yaml
recipes/r-mutoss/meta.yaml
recipes/r-nanostringnorm/meta.yaml
recipes/r-structssi/meta.yaml
recipes/r-tcga2stat/meta.yaml

@bioconda/core Another update to the CRAN recipes in bulk. Hopefully we're nearing the end of these. For whatever it's worth, my desktop computer can now build all of the remaining recipes in ~24 hours, so I hopefully have a close to finalized list of conda-forge packages to update now.

There is a light at the end of the tunnel

---

build-fail-blacklist
recipes/igblast/build.sh
recipes/igblast/meta.yaml

Re-package the binary version this time. There are problems building the
source version when the configure script reaches this step:
"trying to build the NCBI SRA/VDB Toolkit from GitHub"
The previous problem about the binaries linking against libbz2.so, for
which we had no conda package, is now solved.
Also, this saves about 45 minutes compilation time.

Bump IgBLAST to 1.9.0

---

recipes/rnastructure/build.sh
recipes/rnastructure/meta.yaml

Update rnastructure to 6.1.

---

recipes/bam2fastx/meta.yaml
recipes/bax2bam/meta.yaml
recipes/blasr/meta.yaml
recipes/blasr_libcpp/meta.yaml
recipes/pbbam/meta.yaml
recipes/pbcopper/meta.yaml
recipes/pbmm2/meta.yaml
recipes/python-consensuscore/meta.yaml

* Meson 0.47 inserted duplicate RPATHs in
macOS binaries, causing `install_name_tool`
failures when installing the package.
Requiring 0.48 ensures we do not run into
these issues anymore in the future.

PacBio: require Meson 0.48.1 for all recipes

---

build-fail-blacklist
recipes/r-deconstructsigs/build.sh
recipes/r-deconstructsigs/meta.yaml

The 1.8.0 release, from 2016, has some issues with hg38 and other
custom genomes that are fixed in development (raerose01/deconstructSigs#27).
There hasn't been a new release pushed so this rolls these into a new
sub-version and makes them available.

Update: r-deconstructsigs with fixes for hg38

---

recipes/nanocomp/build.sh
recipes/nanocomp/meta.yaml

Update nanocomp to 0.23.1

---

recipes/bioconductor-titancna/meta.yaml

titancna: fix for hg38, remove conda build hacks

---

recipes/biobb_model/build.sh
recipes/biobb_model/meta.yaml

Adding biobb_model recipe

---

recipes/nextflow/meta.yaml

nextflow 18.10.1

---

recipes/pydemult/meta.yaml

I added a small tool from PyPI, pydemult, to demultiplex fastq files (e.g. from single-cell RNA-seq) in parallel. It utilizes the mputil package *sloppily* stream the input file and distribute the demultiplexing work onto many cores. Hope this is useful for others as well 😊

Added recipe for pydemult: Streamed and parallel demultiplexing of fastq files

---

recipes/stacks/2.2/build.sh
recipes/stacks/2.2/meta.yaml

In the perl scripts there could be an `@` in the exe_path variable (Galaxy). Which does not work. 
Alternatively the `@` could be quoted.

stacks: fix for @ in exe_path

---

build-fail-blacklist
recipes/metaseq/build.sh
recipes/metaseq/meta.yaml

Modify and unblacklist recipe for Metaseq
