bioconda/bioconda-recipes

recipes/pangolin/meta.yaml
recipes/pangolin/run_test.py

The new minimal version of usher fixes a bug with input sequences without mutations, which makes it possible to revert the previous patch of run_test.py.

Require usher >=0.6.2 for pangolin

---

recipes/mlst/build.sh
recipes/mlst/meta.yaml

Added some missing dependencies to `mlst` as some of the scripts did not work.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
<table>
<tr>
<td><code>@BiocondaBot please …

chore: Update MLST

---

recipes/aster/build.sh
recipes/aster/meta.yaml

I noticed that the binaries created by bioconda resulted in an "Illegal instruction" error when running on my own (probably older) linux infrastructure; therefore, I am making the compilation a bit more general with `-march=x86-64` instead of `-march=native`.

Fix ASTER v1.13 compilation

---

recipes/isoquant/meta.yaml

Updates IsoQuant to the latest 3.1.1, several bug-fixes made compared to 3.1.0

update IsoQuant to 3.1.1

---

recipes/deepsig/meta.yaml

Numpy dependency of Deepsig was pinned to version 1.23 since Tensorflow 2.2.0 uses `numpy.object` which was deprecated in version `1.24`.
np.object attribute is deprecated since Numpy 1.24 resulting in the following error:
```
File ".../lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
np.object,
File ".../lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'object'
```

fix numpy dependency to 1.23

---

recipes/riassigner/meta.yaml

Updated the meta.yaml file to use `pint <0.20` since larger versions don't have `pint.unit` which is something that `RIAssigner` relies on.
---- …

Update RIAssigner dependency since pint > 0.20 is incompatible

---

recipes/pggb/build.sh
recipes/pggb/meta.yaml

This fixes https://github.com/pangenome/pggb/issues/276.

Update pggb: copy python scripts instead of moving them

---

recipes/mob_suite/meta.yaml

Update the mob_suite tool to version 3.1.2. Restricted the upper bound for the numpy version <1.23.5 to avoid the 'bool' data type warning as a temporary fix

mob_suite version update to 3.1.2. Numpy version restriction 

---

recipes/transposonpsi/build.sh
recipes/transposonpsi/meta.yaml

TransposonPSI uses a wrapper in the enviornments bin, this PR makes sure we pass any arguments onwards.

Update transposonpsi to pass any arguments to tools properly

---

recipes/pantools/meta.yaml

This pull request updates the PanTools recipe to v4.1.1 (needed because v4.1.0 seemed disfunctional via bioconda and this updated version fixes that).

Update pantools to v4.1.1

---

recipes/isoquant/meta.yaml

Updates IsoQuant to 3.1.2, an important bug-fix release

Update IsoQuant to 3.1.2

---

recipes/drtransformer/meta.yaml

This pull request adds the Python package / program: DrTransformer for cotranscriptional RNA folding.
See:
https://doi.org/10.1093/bioinformatics/btad034
---- …

Add drtransformer recipe

---

recipes/ivar/meta.yaml
recipes/ivar/patches/ivar_version.patch

ivar 1.3.2 got released without bumping its version string.
see upstream issue at: https://github.com/andersen-lab/ivar/issues/148

Patch ivar version reporting

---

recipes/thermorawfileparser/meta.yaml

Update the recipe to the latest version of ThermoRawFileParser
Mono <6 requirement is removed

Update to ThermoRawFileParser v 1.4.2

---

recipes/dbcan/meta.yaml

----
Upgrade dbCAN to dbCAN4. 
1. CAZyme substrate prediction based on [dbCAN-sub ](https://bcb.unl.edu/dbCAN_sub/); 
2. CGC substrate prediction based on dbCAN-PUL searching and dbCAN-sub majority voting. For CGC substrate prediction, please see our [dbCAN-seq update paper ](https://academic.oup.com/nar/article/51/D1/D557/6833251)for details. With these new functions (esp. the dbCAN-sub search), dbCAN3 is now slower to get the result back to you. Please be patience

Upgrade dbCAN to dbCAN4

---

recipes/pharokka/meta.yaml

Updates pharokka to v1.2.1. Minor change. Manual PR required as I am fixing an [issue](https://github.com/chapmanb/bcbb/issues/136) with bcbio-gff which breaks due to the newest update to biopython v1.81. Accordingly I need to add to the dependencies of pharokka an upper bound for biopython <1.81.
----
* PRs require reviews prior to being merged. Once …

Update pharokka to  v1.2.1

---

recipes/arriba/meta.yaml

Just a version bump. The Bioconda bot did not create a PR automatically.

Update arriba to 2.4.0

---

recipes/get_fasta_info/build.sh
recipes/get_fasta_info/meta.yaml

Add get_fasta_info (<https://github.com/nylander/get_fasta_info>) - a tool for fast info on fasta- or fastq-formatted files

Add get_fasta_info

---

recipes/snakemake-wrapper-utils/meta.yaml

Mainly, this is an update to `snakemake-wrapper-utils` version `0.5.2`. But `poetry` changed the file naming of the sdist files (`.tar.gz`) in its `build` command, and that is what is uploaded to `pypi` for `snakemake-wrapper-utils`. The long story is in one of the commit messages, that I reproduce here for better findability and cross-references on GitHub:
**Make package name in sdist .tar.gz filename conform to specs (using underscores)**
The official specs for sdist file names require that the package name is in snake case, see these places:
* https://peps.python.org/pep-0625/#specification
* https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode
* https://peps.python.org/pep-0491/#escaping-and-unicode
[`poetry` switched to conforming to …

update snakemake-wrapper-utils to 0.5.2

---

recipes/rnaquast/meta.yaml

Update rnaQUAST to 2.2.3
- Fixes BUSCO offline usage

Update rnaQUAST to 2.2.3

---

recipes/kseqpp/meta.yaml

This PR fixes an issues in `kseqpp` recipe: 'zlib' should be in the 'host' section of requirements.

Move zlib to host requirements

---

.mergify.yml

Still to solve: we need to ensure that the autobump PR does not contain additional commits from others than the BiocondaBot.

chore: use mergify to automatically merge autobump PRs from BiocondaBot after waiting 3 days

---

recipes/isoquant/meta.yaml

A major update for IsoQuant:
- significant performance improvements (10x lower RAM, 5x lower disk space)
- improved output formats
- intuitive option usage

Update IsoQuant to 3.2.0

---

azure-pipeline-master.yml
azure-pipeline-nightly.yml
azure-pipeline.yml

Now that https://github.com/bioconda/bioconda-common/pull/32 is merged, use the script on the master branch of bioconda-common.

use bioconda-common/master branch for script

---

recipes/r-shinyngs/build.sh
recipes/r-shinyngs/meta.yaml

The shinyapps.io deployment as started failing again with shinyngs, due to packrat issues. For some reason the hack here to edit DESCRIPTION was not working, so I'm attempting a fix.
---- …

Fix shinyngs recipe hackery for packrat

---

recipes/r-shinyngs/meta.yaml

For some reason, on some systems I'm getting an older version of r-stringi, which leads to errors like:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
unable to load shared object '/usr/local/lib/R/library/stringi/libs/stringi.so':
libicui18n.so.58: cannot open shared object file: No such file or directory
Calls: ggplot_boxplot ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
```
Just adding a pin here to see if I can ensure the most up to date one. 
----
* New recipes not directly relevant to the biological sciences …

pin r-stringi to avoid libicui18n.so.58 error

---

recipes/mnnpy/meta.yaml

n_jobs was deprecated from cKDTree in scipy 1.6.0 on and removed on 1.9.0, which mnnpy uses and fails due to it in current installations that get a newer scipy. …

Update mnnpy: Pin scipy to <1.9.0 as mmnpy uses n_jobs

---

recipes/pbhoover/meta.yaml

Missing `bgzip` resulted in errors like
```
No such file or directory
```
at the normalization step following variant calling

pbhoover: add missing runtime dependency on htslib

---

recipes/qiskit-xyz2pdb/meta.yaml

Added recipe for qiskit-xyz2pdb. This is a program used to convert XYZ files from Qiskit workflows, into proper PDB files.

new recipe for qiskit-xyz2pdb

---

recipes/gtdbtk/download-db.sh
recipes/gtdbtk/meta.yaml

Conda is not available on the containers. So, if downloading from a container the script will exit with code 1, even though the download finished. 
This PR makes it so that the user will receive a warning for missing conda. This atleast allows the containers to play nice with workflow managers
---- …

Update GTDB-tk recipe

---

recipes/mapad/meta.yaml

Update [mapad](https://bioconda.github.io/recipes/mapad/README.html): 0.41.0 → 0.42.1
This PR includes a fix of a typo (`recipe.maintainers` instead of `recipe-maintainers`) preventing me ( @jch-13 ) from being listed as a maintainer.

Update mapad to 0.42.1

---

recipes/diamond/build.sh
recipes/diamond/meta.yaml

This PR pulls in libzstd for compression and the BLAST C++ libaries to be able to read NCBI blast formatted databases, two compile-time optional features DIAMOND has recently supported.
---- …

Update diamond: build with zstd & blast support

---

recipes/frogs/build.sh
recipes/frogs/meta.yaml

This PR updates FROGS: a workflow designed to metabarcoding sequence analysis, it produces an ASVs count matrix from high depth sequencing amplicon data.
Frédéric Escudié, Lucas Auer, Maria Bernard, Mahendra Mariadassou, Laurent Cauquil, Katia Vidal, Sarah Maman, Guillermina Hernandez-Raquet, Sylvie Combes, Géraldine Pascal;[ FROGS: ](https://academic.oup.com/bioinformatics/article/34/8/1287/4708232?guestAccessKey=a3b4c7f6-d18e-43a0-971e-8f6422c67f56)Find, Rapidly, OTUs with Galaxy Solution, Bioinformatics, Volume 34, Issue 8, 15 April 2018, Pages 1287–1294
Maria Bernard, Olivier Rué, Mahendra Mariadassou and Géraldine Pascal;[ FROGS](https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bbab318/6354026?guestAccessKey=c3c28079-333a-432e-9d9e-b4c37da8284d): a powerful tool to …

Update FROGS to 4.1.0

---

recipes/hybran/meta.yaml

- Version 1.6 requires biopython >=1.80
- Removed direct dependency on prodigal (no longer called directly in v1.6)
- Removed direct dependency on mummer (never used directly. (required by and depended on by ratt)
----
* Please …

Update hybran to 1.6

---

recipes/m6anet/meta.yaml

Add conda recipe to build m6anet package. m6anet is a Python tool that leverages Multiple Instance Learning framework to detect m6a modifications from Nanopore Direct RNA Sequencing data
---- …

add m6anet recipe

---

recipes/bedtools/build.sh
recipes/bedtools/meta.yaml

Update checksum (again) to reflect the re-released upstream tarball. Remove `run` dependencies, which will be detected automatically.
---- …

Update bedtools to 2.31.0

---

recipes/pantools/meta.yaml

Update PanTools recipe from 4.1.1 to 4.2.0 (manual bump since PanTools source code is hosted on git.wur.nl instead of github.com).

Update PanTools to v4.2.0

---

recipes/tiny-count/meta.yaml

An autobump PR is already open under #40761 but this should supersede it and the other should be closed.
**Edit 5/5/23:** This PR should still supersede #40761. The v1.4.0 update required changes to the recipe.
Closes #40761

Update tiny-count 1.4.0

---

recipes/elastic-blast/meta.yaml

This pull request updates the metadata for the ElasticBLAST bioconda recipe so that architecture specific builds are created (linux and macos) so users do not attempt to run this tool on windows (as in https://github.com/ncbi/elastic-blast/issues/15). Additionally, the ElasticBLAST publication's DOI is added
---- …

Update elastic-blast: remove noarch:python; add publication DOI

---

recipes/ms2deepscore/LICENCE
recipes/ms2deepscore/meta.yaml

MS2Deepscore is a package used to calculate chemical similarity scores between tandem mass spectra.

Add ms2deepscore

---

recipes/r-saige/meta.yaml

Add missing dependencies to r-saige: r-skat is necessary for step2 at runtime also. This was overlooked during the big build refactor.
Without this, only step 1 of SAIGE is runnable. users have been manually installing r-skat to workaround. 
---- …

fix r-saige 1.1.9: Missing runtime dependencies

---

recipes/deepmicro/meta.yaml

Update DeepMicro
Pinnned tensorflow to 2.11.0, in the hopes to avoid this error: 
```
File "/usr/local/tools/_conda/envs/__deepmicro@1.4/bin/DM.py", line 16, in <module>
import keras
File "/usr/local/tools/_conda/envs/__deepmicro@1.4/lib/python3.10/site-packages/keras/__init__.py", line 21, in <module>
from keras import models
File "/usr/local/tools/_conda/envs/__deepmicro@1.4/lib/python3.10/site-packages/keras/models/__init__.py", line 18, in <module>
from keras.engine.functional import Functional
File "/usr/local/tools/_conda/envs/__deepmicro@1.4/lib/python3.10/site-packages/keras/engine/functional.py", line 24, in <module>
import tensorflow.compat.v2 as tf
File "/usr/local/tools/_conda/envs/__deepmicro@1.4/lib/python3.10/site-packages/tensorflow/__init …
```

pinned tensorflow to 2.11.0

---

recipes/plannotate/meta.yaml

1. The following dependency is missing from the recipe: https://github.com/barricklab/pLannotate/blob/daabf1a63be79c43ff6166c76403d358b1d53da8/environment.yml#LL20C5-L20C18
2. Pinned to match versions from repo.  Higher versions of dependencies caused exceptions on my machine.
3. Fixed linting issues

Update plannotate recipe: lint and dependencies

---

recipes/r-recetox-xmsannotator/meta.yaml

The `r-recetox-xmsannotator` package does not create automatic PR on a new release.
This might be caused by minor issue with the URL (`recetox` was not uppercase).

Update r-recetox-xmsannotator: change repo URL

---

recipes/tassel/meta.yaml

This PR updates the TASSEL Bioconda package to the most recent public release, `5.2.89`.

Update TASSEL package to 5.2.89

---

recipes/pangolin/meta.yaml

Since v4.3 pangolin works again with the latest releases of all its dependencies.

Remove outdated dependency restrictions for pangolin

---

recipes/ltr_retriever/meta.yaml

The auto-update of `ltr_retriever` v2.9.5 encounters dependency conflicts (#41933) which are resolved in this manual update. Setting version restrictions for `repeatmasker`, `rmblast`, and `libstdcxx-ng` solve this conflict.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr> …

update ltr_retriever to v2.9.5

---

recipes/medicc2/meta.yaml

Manual update to MEDICC2 version 1.0.2 due to some dependency changes with Cython.
Cython was recently updated to version 3.0, however, MEDICC2 does not compile with the new version which is why the old version 0.29 was pinned.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr> …

Update MEDICC2 to version 1.0.2

---

recipes/bioconductor-affy/meta.yaml

Meaningful usage of the affy package (e.g. the justRMA function) requires a bunch of packages not currently present in the dependencies, and they end up getting installed dynamically, which is unhelpful and sometimes fails. Adding them here instead.
---- …

Add basic affy dependencies

---

recipes/snakemake/meta.yaml

7.30.2 requires at least Python 3.9
I hope that's correct @johanneskoester?

Update snakemake Python dependency

---

recipes/snakemake/meta.yaml

Mamba is only meant to be installed in the base environment. Furthermore, the recommendation is to install no packages other than conda and mamba deps in the base environment. See the [mamba docs](https://mamba.readthedocs.io/en/latest/installation.html#installation).
See #41477
Closes snakemake/snakemake#2288, closes snakemake/snakemake#2343

Remove mamba from Snakemake deps

---

recipes/t-coffee/meta.yaml

TL;DR: `viennarna = 2.1.9` pulls in the very old python `3.7` and this can easily clash with other dependencies nowadays. And I don't see any reason for the pinning to be necessary, here's where I checked:
* [The original commit that introduced the pinning gives no reason](https://github.com/bioconda/bioconda-recipes/commit/90fad72c3dbe47ff0a1284a659afaa3dd7573062), so I am assuming this was introduced as a side-effect while trying to get the recipe to work.
* [t-coffee README.md mentions the `vienna` package for using `RNAplfold`, but gives no specific version requirements.](https://github.com/cbcrg/tcoffee/blob/master/docs/tcoffee_installation.rst#r-coffee-associated-packages)
* [The `viennarna` package Changelog only mentions fixes for the `RNAplfold` functionality, but no breaking …

fix: [t-coffee] unpin viennarna to avoid pulling in old python

---

recipes/snakemake/meta.yaml

BugFix: dependencies for snakemake-minimal
- since snakemake 7.2.0, filelock isn't used anymore
- since snakemake 7.29.0, packaging is used instead of distutils
---- …

Update: snakemake, BugFix dependencies

---

recipes/concoct/meta.yaml

Concoct fails with newer versions of sklearn. Fixes the sklearn version in the concoct recipe to a compatible version.
https://github.com/BinPro/CONCOCT/issues/323
---- …

Concoct: fix sklearn version

---

recipes/unifrac-binaries/meta.yaml

Update unifrac-binaries to 1.4.
Also force nompi version of hdf5 (used to be default).
----
<details> …

Update unifrac-binaries to 1.4

---

recipes/auspice/meta.yaml

See Auspice changes <https://github.com/nextstrain/auspice/releases/tag/v2.47.0> for full details.
Note that this PR also modifies the supported nodejs versions
---- …

Update auspice to 2.47.0

---

recipes/mtbseq/meta.yaml

Update to version 1.1.0
changed test command
changed picard requirements
----
<details> …

Update mtbseq to v.1.1.0

---

recipes/crispector2/build.sh
recipes/crispector2/meta.yaml

This is an extension of the existence crispector tool that was published 2 years ago.
It has some added abilities and analyses that were lacking in the previous edition.
The additional code is significant, thus it is published as a new tool with the same name.
---- …

Add crispector2 2.0.0

---

recipes/freebayes/meta.yaml

Fix freebayes-prarallel because of bug in vcflib=1.0.9 (https://github.com/vcflib/vcflib/issues/389).
Also, htslib=1.17 does not work with freebayes-parallel.

fix: freebayes

---

recipes/lisa2/meta.yaml

Update package lisa2 to version 2.3.2 , which relaxes some dependencies.

Update lisa2 to version 2.3.2

---

recipes/picard-slim/build.sh
recipes/picard-slim/meta.yaml
recipes/picard/build.sh
recipes/picard/meta.yaml

Autobump branches `bump/picard{,_slim}` exist for these, but appear never to have been turned into PRs — presumably due to autobump bot disruption at the time.
There has been a nontrivial organisational change upstream in v3.1.0: _picardcloud.jar_ is no more, and _picard.jar_ is now much larger and includes cloudy functionality and dependencies. However it appears that bioconda's recipes will not need any changes to deal with this.
~~I have not attempted to add `run_exports` because~~ I have seen no adequate explanation of the rationale for this.
----
* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in its …

Update picard and picard-slim to 3.1.0

---

recipes/sfs/build.sh
recipes/sfs/meta.yaml

Adds recipe `sfs` CLI tool to work with site frequency spectra (population genetics).
Passes both
```bash
bioconda-utils build --packages sfs
bioconda-utils lint --packages sfs
```

Add sfs recipe

---

recipes/gum/meta.yaml

Update [gum](https://bioconda.github.io/recipes/gum/README.html) from 1.1.1 to 2.0.1.

Update gum to 2.0.1

---

recipes/savana/meta.yaml

Attempted fix for reported issue with scikit-learn minor version (>=1.2.2 specified but 1.3.0 breaks, see: https://github.com/cortes-ciriano-lab/savana/issues/27)
---- …

Update savana to 1.0.4 (Resolve errors by pinning scikit-learn to 1.2.x)

---

recipes/rsrq/build.sh
recipes/rsrq/meta.yaml

Adds a new package rsrq to Bioconda. This program is a minimal Redis-backed queueing system that integrates with Snakemake.
https://github.com/aaronmussig/rsrq

Add rsrq v1.0.0

---

recipes/hitac/meta.yaml

This PR updates HiTaC to v 2.1.0. It fixes a lint error with `run_export` and adds the command line tests for the new version.

Update HiTaC to v2.1.0

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

Somewhat similarly to PR #40675 for libdeflate, this PR recommends patching htslib dependencies to extend version ranges instead of pinning htslib in bioconda. Pinning htslib causes deployment difficulties each time there is an upstream htslib/samtools/bcftools joint release; e.g. #42167 and #42168 have still not been merged six weeks after bcftools and samtools 1.18 were released, because the htslib pinning still has not been updated (cf bioconda/bioconda-utils#915).
The reason for pinning htslib is that it is a common dependency and if several tools using it are all going to be installed in the same environment they all need to be using (and hence built against) the same htslib version.
If we patch repodata to loosen these htslib dependencies, this need will go away. Then we can …

Patch repodata to relax HTSlib dependency upper bounds

---

recipes/bedtools/meta.yaml

`$ /Users/u005069/miniconda3/bin/conda build .`
brings
```
...
raise RuntimeError(
RuntimeError: SHA256 mismatch: 'a93e6b6bfdd8d33db1e6decbefdd2b03771e0ac63ac69a4059b7b3464efe281d' != '183cf9a96aabc50ef4bd557a53fd01557a123c05a0dc87651371878f357439ec'
...
```
I do not really understand why this happens, since the bioconda package was indeed released later than the code on GitHub - but I executed `shasum -a 256 ` directly on the tarball and the runtime error is correct - the SHA256 mismaches.

bedtools: adjusted checksum to what is downloaded from GitHub

---

recipes/agfusion/meta.yaml

update agfusion 1.252->1.4.1
home: [AGFusion](https://github.com/murphycj/AGFusion)
reason: An [error](https://github.com/murphycj/AGFusion/issues/40) is repirted when the agfusion of the 1.252 version is used.
```
>>> import agfusion
File "<stdin>", line 1, in <module>
File "/app/software/Python/Python-3.8.6/lib/python3.8/site-packages/agfusion/__init__.py", line 2, in <module>
from .model import *
File "/app/software/Python/Python-3.8.6/lib/python3.8/site-packages/agfusion/model.py", line 9, in <module>
from Bio.Alphabet import generic_dna, generic_protein
File "/app/software/Biopython/1.78/Python-3.8.6/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
raise ImportError(
ImportError: Bio.Alphabet has been removed from …
```

Update agfusion to 1.4.1

---

recipes/haplink/build.sh
recipes/haplink/meta.yaml
recipes/haplink/scripts/activate.sh
recipes/haplink/scripts/deactivate.sh

Adds a package for [HapLink](https://github.com/ksumngs/HapLink.jl). HapLink is a software tool for identifying viral haplotypes.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please merge</code> command is now depreciated. …

Add HapLink recipe

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

Libdeflate 1.19 is newly released (conda-forge/libdeflate-feedstock#25) and does not change the shared library soversion. As noted in PR #40675 and the TODO comment in the code, we should update the repodata patching to allow this version too.
---- …

bioconda-repodata-patches: Include libdeflate v1.19 in dependency patching

---

recipes/bakta/meta.yaml

Pin Pyrodigal to `2.x` forestalling installation of the not yet supported version `3.0`

fix Pyrodigal to 2.x

---

recipes/sepp/meta.yaml

Currently, SEPP breaks for dendropy version 4.6.0 and above (see smirarab/sepp#126).
This PR pins the dendropy version requirement to `<= 4.5.1`, the latest working version.
Also, it adds pasta to the requirements (it's required to run UPP).
When SEPP supports a current dendropy version, I will create another PR to update the version requirement.

update/fix SEPP recipe

---

recipes/ninja-nj/meta.yaml

I was looking into the ninja-nj package on bioconda for macOS and I found out that it still is an issue for `mamba install repeatmodeler` on macOS. I noticed that it should be quite simple to fix this for macOS, so that's what this PR changes.
Related to this, #33626 seems to mention that there were problems to add this recipe in the past for macOS. @Juke34 since you originally looked into this issue, could you please confirm whether this PR fixes it for macOS?

Update ninja-nj for OSX

---

recipes/samtools/meta.yaml

I'm having the same issue with samtools 1.17 as described in this old issue from 2018: https://github.com/samtools/samtools/issues/790
Last time a build bump fixed it, so probably there's been an update to ncurses that broke the linkage

Update: Rebuild samtools

---

recipes/ncbi-fcs-gx/build.sh
recipes/ncbi-fcs-gx/meta.yaml

This PR replaced a pre-compiled binary with bioconda normal cxx compilation from github. It also makes certain called external programs explicit dependencies at the request of galaxy.

Update ncbi-fcs-gx to use github and explicit requirements

---

recipes/pixelator/meta.yaml

Update [`pixelator`](https://github.com/PixelgenTechnologies/pixelator) to 0.14.0.
Relax poetry build dependency restrictions.

Update pixelator to 0.14.0

---

recipes/abismal/build.sh
recipes/abismal/meta.yaml

I'm trying to fix a problem in an autobump.
---- …

Update abismal: fixing issues in an autobump

---

recipes/ont-modkit/build.sh
recipes/ont-modkit/meta.yaml

This PR adds a recipe for Oxford Nanopore Technologies' [modkit](https://github.com/nanoporetech/modkit). The tool is e.g. used to convert basecalls for methylated bases to other formats like CSV/TSV and published under _Oxford Nanopore Technologies PLC. Public License Version 1.0_. 
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built …

Add modkit (Oxford Nanopore)

---

recipes/checkqc/meta.yaml

This updates the requirements for the checkqc recipe which now installs a broken version of checkqc. It gets installed in a python 3.12 env and the `interop` package only supported on python < 3.11.  
Unfortunately I have not been able to test these changes locally due to an issue with bioconda-utils:https://github.com/bioconda/bioconda-utils/issues/929.
---- …

Update checkqc recipe

---

recipes/macrel/meta.yaml

Python after 3.11 only accepts newer version of sklearn that does not unpickle the tree estimator properly inducing a error.
---- …

Fix Python version to macrel execution

---

recipes/phylogenize/build.sh
recipes/phylogenize/meta.yaml

Adds [Phylogenize](https://github.com/pbradleylab/phylogenize) to conda. Allows for users to link microbial genes to environments, accounting for phylogeny. More specifically, given community composition data, phylogenize links genes in microbial genomes to either microbial prevalence in, or specificity for, a given environment, while also taking into account an important potential confounder: the phylogenetic relationships between microbes.
Paper: [(Bradley and Pollard, 2020)](https://pubmed.ncbi.nlm.nih.gov/31588499/)

Add Phylogenize

---

recipes/bioconductor-rhdf5/meta.yaml

I think that this will fix an issue with `libcrypto.so` not being found that I reported over at `rhdf5`: https://github.com/grimbough/rhdf5/issues/131
---- …

update bioconductor-rhdf5: rebuild after including libcurl dependency downstream in bioconductor-rhdf5lib, include pin_subpackage syntax

---

recipes/auspice/meta.yaml

Following recent release on NPM.
Post-merge task:
---- …

Update auspice to 2.50.0

---

recipes/ucsc-twobittofa/meta.yaml

Updates ucsc-twobittofa of the UCSC kent utils from version 447 to 455. This also triggers a rebuild, to update the openssl version, because it is otherwise incompatible with more recently built kent utils.
There are two other PRs that I opened in parallel to this one, which have very similar changes: https://github.com/bioconda/bioconda-recipes/pull/44040 and https://github.com/bioconda/bioconda-recipes/pull/44041.
---- …

Update ucsc-twobittofa from 447 to 455

---

recipes/ucsc-fatotwobit/meta.yaml

Updates ucsc-fatotwobit of the UCSC kent utils from version 447 to 455. This also triggers a rebuild, to update the openssl version, because it is otherwise incompatible with more recently built kent utils.
There are two other PRs that I opened in parallel to this one, which have very similar changes: https://github.com/bioconda/bioconda-recipes/pull/44039 and https://github.com/bioconda/bioconda-recipes/pull/44041.
---- …

Update ucsc-fatotwobit from 447 to 455

---

recipes/eigensoft/0002-replace-finite.patch
recipes/eigensoft/0003-remove-wrong-cflag.patch
recipes/eigensoft/build.sh
recipes/eigensoft/meta.yaml

With these fixes eigensoft can also bei installed on OSX-arm64.
Two issues prevented this so far:
1.  The `finite` function is obsolete and should be replaced with `isfinite` (see https://linux.die.net/man/3/finite). Since this should be done not only for osx, I did not specify the `#  [osx]`  selector.
2. The compiler option `-p` seems to be invalid for the apple clang compiler. I never had this issue on a linux machine, so I added the `#  [osx]`  selector.
I further adjusted the name and version specifiers to match the recipe standard. 
---- …

Update eigensoft: fix build for osx-arm64

---

recipes/abricate/meta.yaml

Some database downloads using `abricate-get_db` (those that fetch over HTTPS) fail in the latest version because of missing HTTPS support (see e.g. https://github.com/tseemann/abricate/issues/193). This PR adds the required library.

Update abricate: add missing dep to fix database download issues

---

recipes/el_gato/build.sh
recipes/el_gato/meta.yaml

Add el_gato recipe to Bioconda.
el_gato is a command line application for performing sequence typing of _Legionella pneuomphila_ samples from short reads or assemblies.
https://github.com/appliedbinf/el_gato/

Add el_gato package to Bioconda

---

recipes/multiqc/meta.yaml

After version 1.17, MultiQC stopped supporting Python 3.6 and 3.7, and added the `packaging` dependency to handle the calls of the deprecated `distutils` that was removed in 3.12: https://github.com/ewels/MultiQC/pull/2113
However, we forgot to updated the bioconda recipe accordingly. Thos PR:
- Pins Python to >=3.8
- Adds the missing `packaging` dependency
- Additionally, adds the `humanize` dependency that is added in the dev version and will be used in the future MultiQC 1.18 version.
Addresses https://github.com/nextflow-io/rnaseq-nf/issues/22

MultiQC: add missing dependencies, pin to Python >=3.8

---

recipes/hostile/meta.yaml

Workaround for performance issue associated with `bowtie2` >= `2.5.x`

Update Hostile, pinning older bowtie2==2.4.5

---

.circleci/config.yml

Port .github/workflows/bulk.yml to Circle CI for ARM builds.
Notes:
- Tested the workflow except for `--anaconda-upload` on https://github.com/bioconda/bioconda-recipes/pull/43995 but wanted to have a less cluttered branch.
- Holding off for now from `--mulled-upload-target biocontainers` per discussion with the core team.
- Used `machine` instead of docker for the `executor` because "nested" docker with mounted volumes is [not supported by CircleCI](https://circleci.com/docs/using-docker/#docker-benefits-and-limitations).
- Do we want to use a branch other than `bulk` to do the first bulk update?
- Not sure if there's anything additional needed to test `--anaconda-upload` to make sure `linux-aarch64` does not conflict with `linux-64`.

CircleCI workflow for Bulk builds on ARM

---

recipes/paml/meta.yaml

Update PAML to [latest GitHub release 4.10.7](https://github.com/abacus-gene/paml/releases/tag/4.10.7)

Update PAML to 4.10.7

---

recipes/pantools/meta.yaml

Previously, I had assumed that dependencies in the `run` section have to be valid for both Linux and macOS. I have just found out that these can be platform specific too. Therefore, this PR makes two previously excluded dependencies Linux specific since they are not conflicting on Linux. They are still conflicting on macOS and therefore the `# [linux]` has been added for them. This will also make sure that these dependencies are included for the PanTools image on biocontainers.

Update Pantools v4.2.3 recipe

---

recipes/lima/meta.yaml

lima consistently segfaults on EL8 (RHEL 8, Rocky Linux 8, etc.) due to an interaction with `patchelf --set-rpath` (possibly for certain versions of patchelf?) and the kernel version used by EL8. This PR disables such binary relocation ordinarily performed by `conda-build`, resulting in the packaging of unmodified PacBio-built lima executables.
Tested locally (`bioconda-utils build --packages lima`) on Rocky 8.
Reference: https://github.com/PacificBiosciences/pbbioconda/issues/557#issuecomment-1819767535

Update lima: set binary_relocation: False to fix EL8 segfault

---

.circleci/config.yml

This targets the `arm-builds` branch. It incorporates some fixes identified from testing over on https://github.com/bioconda/bioconda-recipes/pull/43995.
Specifically:
1. **Disable caching.** Turns out the cache restore was not working, apparently because the CircleCI restore process doesn't make a directory if it doesn't exist. So the cache restore was taking 7+ minutes....just to report 130k+ times that the directory didn't exist! Making the directory ahead of time fixed that, allowing the cache to be restored in 21s. But then the bioconda-common install script failed, because the directory `/opt/mambaforge` already existed (from aforementioned cache restore...). It appears that CircleCI does not have a mechanism for detecting a cache hit, which would otherwise allow us to conditionally …

Arm builds circleci fixes

---

.circleci/config.yml
recipes/test/meta.yaml

This adds a test package (likely to be deleted later from channel and biocontainers) to test that, once this PR is merged into master, `bioconda-utils handle-merged-pr` correctly picks up the package & container artifacts built on circleci and uploads them appropriately.
Edit: don't want to actually merge this into master, instead, this modifies the branches used by circleci to simulate the master branch.

Test ARM artifact merging

---

recipes/trtools/meta.yaml

Closes #44482
Update [`trtools`](https://bioconda.github.io/recipes/trtools/README.html): **5.1.0** → **5.1.1**
Please merge this PR instead of #44482. We've added a new dependency and some additional tests.

Update trtools to 5.1.1

---

.github/workflows/Bulk.yml
.github/workflows/build-failures.yml
recipes/art/build_failure.osx-64.yaml

Use BiocondaBot instead of bioconda-bot in GitHub actions for consistency.
Removed the token from Bulk.yml which should now be using the built in credentials from GitHub Actions. (tested on bulk arm builds test branch: https://github.com/bioconda/bioconda-recipes/pull/43995)
The build-failures.yml uses an action to update the wiki and still requires the token from what I can tell. This PR will not fix the action directly. However, since bioconda-bot has been giving errors, that action doesn't work anyway. So, I am making the change now to BiocondaBot.

Bot consolidation

---

recipes/nextstrain-cli/meta.yaml

Remove skip lint now that bug is fixed
Remove Python 3.6 and 3.7 specific run requirements as bioconda no longer supports them (https://github.com/bioconda/bioconda-utils/pull/878)
Raise host requirement to 3.8 and above
Python 3.7 can no longer be installed, see:
```
micromamba create -n py37 -c conda-forge -c bioconda nextstrain-cli python=3.7
```
which errors
---- …

Update nextstrain-cli recipe (not version)

---

recipes/nextclade2/build.sh
recipes/nextclade2/meta.yaml
recipes/nextclade2/run_test.sh

The nextstrain conda runtime should be able to contain both nextclade2 and nextclade3 binaries.
The addition of this package means that workflows requiring nextclade2 once nextclade has moved to major version 3 can still use nextclade2 alongside nextclade(3).
---- …

Add nextclade2 to allow nextclade 3 and nextclade 2 to exist in same environment

---

recipes/rebar/LICENSE
recipes/rebar/build.sh
recipes/rebar/meta.yaml
recipes/rebar/run_test.sh

This pull request creates a new recipe for the program [`rebar`](https://github.com/phac-nml/rebar). `rebar` is a **RE**combination **BAR**code detector, that _detects_ and _visualizes_ recombination between genomic sequences. It was designed primarily with SARS-CoV-2 in mind but has been generalized for other organisms.
`rebar` is written in Rust and I've used the [`nextclade`](https://github.com/nextstrain/bioconda-recipes/blob/f7b372627ae2f65862c03e555fd593f641633889/recipes/nextclade/meta.yaml) recipe as a template. The binaries are pre-compiled for `linux-64`, `osx-64`, and `win-64`. This is my first bioconda PR for a Rust program, so please bear with me as I update the recipe according to the CI results.

Create new recipe for rebar

---

recipes/cobs/meta.yaml

Update COBS to v0.3.0: Bumping build number to trigger rebuild as the cobs release has been amended
----
Conda is able …

Update COBS to v0.3.0 (build 1)

---

build-fail-blacklist
recipes/bbknn/meta.yaml

Someone else contributed a package I wrote to conda (many thanks for that!). I've since released a new version, and have taken a stab at updating the recipe to match current dependencies, versions, and the hash.

Update bbknn to 1.6.0

---

recipes/cogent3/meta.yaml

Updating bioconda autobump to include changes to minimum supported python release, and numba
NB: Max python support is constrained by most recent numba release
----

Update cogent3 recipe to version 2023 12 15a1

---

recipes/gsearch/meta.yaml

Update to gsearch v0.1.7 with support for reverse optimal densification and superminhash 2 for amino acid
---- …

Update gsearch v0.1.7

---

recipes/mob_suite/meta.yaml
recipes/mob_suite/run_test.sh

Since pandas v1.5.0 the `line_separator` parameter is deprecated  in `df.to_csv()` so we need to restrict pandas version to <2. Hence the new build for the same version 3.1.8. Addressing issue https://github.com/phac-nml/mob-suite/issues/155

Mob_suite v3.1.8 build 1 due to restrict pandas to <=1.5.3

---

recipes/mcl/build.sh
recipes/mcl/meta.yaml
recipes/mcl/scripts/README
recipes/mcl/scripts/mclblastline
recipes/mcl/scripts/mcxdeblast

The last mcl release mistakenly excluded the `mcxdeblast` (and `mclblastline`) scripts. The developer confirmed this and promised to include it in the next release. Until that happens, the bioconda package can bring them back. This follows the approach by the Debian package maintainers that the developer recommended.
Because of the mistake, the last update of the mcl package broke several packages:
- https://github.com/nf-core/modules/issues/3828
- https://github.com/sanger-pathogens/Roary/issues/217
- as well as `hybran`
See https://github.com/micans/mcl/discussions/25

mcl: restore bioinformatics tools support

---

recipes/r-misha/3.7.0/build.sh
recipes/r-misha/3.7.0/meta.yaml

The package `r-misha` has only versions 4.x available in bioconda, but in our case seems some package like `umi4cpackage` depends on misha 3.x. so I found misha history version (not tagged) in github repo and created this pr.
---- …

add r-misha 3.7.0 (history version)

---

recipes/r-misha/3.7.1/build.sh
recipes/r-misha/3.7.1/meta.yaml

The package `r-misha` has only versions 4.x available in bioconda, but in our case seems some package like `umi4cpackage` depends on misha 3.x. so I found misha history version (not tagged) in github repo and created this pr.
related: `r-misha` 3.7.0 https://github.com/bioconda/bioconda-recipes/pull/44981
---- …

add r-misha 3.7.1 (history version)

---

recipes/unitig-caller/meta.yaml

New bifrost versions 1.3.0 have breaking changes, rebuilding library to use correct functions
---- …

Rebuild unitig caller for new bifrost version

---

recipes/viroconstrictor/meta.yaml

A quick patch to the recipe of ViroConstrictor to exclude the usage of snakemake 8.x for the time being as there are quite some changes which require more attention at a later date.
---- …

patch viroconstrictor snakemake requirements to not use version 8.x

---

recipes/mitos/mitos1/meta.yaml

- bumps mitos1 recipe
- simplifies pins
---- …

bump mitos1

---

recipes/ncbi-fcs-gx/meta.yaml
recipes/ncbi-fcs-gx/no_static.patch

Remove static compilation from ncbi-fcs-gx
---- …

remove static compilation from ncbi-fcs-gx

---

recipes/orthofinder/meta.yaml

Orthofinder seems to use the old muscle syntax `muscle -in INPUT`.
See https://github.com/davidemms/OrthoFinder/blob/04455a31c12f361b34ae2791253a546338678cec/scripts_of/config.json#L13
AFAIK this was removed in muscle v5.
I'm getting errors when I try to run orthofinder from the biocontainer. 
```
Invalid command line
Unknown option in
ERROR: Cannot run MSA method 'muscle'
```
---- …

Update orthofinder recipe to pin muscle dependency

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

pin max version of pulp to <2.8.0 for Snakemake <8.1.2

---

recipes/deepvariant/meta.yaml

The deepvariant package pins out-of-date tensorflow versions. The upstream built against 2.11, and we pin 2.0.XXX which is no longer available, making the package uninstallable.
Also added a run-exports section

Update deepvariant dependency versions

---

recipes/haptools/meta.yaml

Closes https://github.com/bioconda/bioconda-recipes/pull/45224
Update [`haptools`](https://bioconda.github.io/recipes/haptools/README.html): **0.3.0** → **0.4.0**
Please merge this PR instead of #45224. We added a new dependency and changed some of the version constraints for python to support 3.11+
----
`haptools` is a collection of tools for simulating and analyzing genotypes and phenotypes while taking into account haplotype and ancestry information
https://pypi.org/project/haptools/
https://github.com/CAST-genomics/haptools

Update haptools to 0.4.0

---

recipes/evigene/build.sh
recipes/evigene/meta.yaml

The problem with the first build was that `#!/usr/bin/perl` replaced with `#!/usr/bin/env perl` only in the main file `tr2aacds.pl`.  This file calls other perl scripts which also need the correct shebang: `#!/usr/bin/env perl`
---- …

Evigene: Replaced bin_perl with env_perl in all perl files

---

recipes/edta/build.sh
recipes/edta/meta.yaml

I am in the process of creating a NextFlow DSL2 module for LTR_FINDER_parallel which is part of the EDTA pipeline. To access LTR_FINDER_parallel in a portable manner, I have placed a bash script for LTR_FINDER_parallel under /usr/local/bin. Please see further discussion here: https://github.com/nf-core/modules/pull/4746
---- …

LTR_FINDER_parallel is now also exposed to /usr/local/bin

---

recipes/hostile/meta.yaml

This replaces the autobump PR for version `1.0.0` which is missing a new dependency (https://github.com/bioconda/bioconda-recipes/pull/45351)

Update hostile to 1.0.0, add new dep, update DOI

---

recipes/piscem/meta.yaml

Update piscem to 0.7.1

---

recipes/ntlink/meta.yaml

With refactoring in previous versions, ntLink no longer has compiled components (it uses binaries via the btllib dependency instead), so made the recipe 'noarch' and removed the 'build' section under requirements.
Also removed the version dependency for btllib.
---- …

Update ntLink build

---

recipes/linearfold/0001-FIX-command-broken-with-symbolic-link.patch
recipes/linearfold/meta.yaml

This is a release from the last commit on github from 2022-08-29, git-sha1 c3ee9bd80c06c2fc39a7bb7ae5e77b9566227cac to fix issues with the currently released version.
Changes since the last release 1.0 (my summary):
- driver script works with python3
- fixes for dangles
- SHAPE support
- other bugfixes
All upstream releases require python2 for the driver script, making it difficult to use the package with other packages depending on python3.
Upstream issue:
https://github.com/LinearFold/LinearFold/issues/14

Update linearfold to 1.0.1.dev20220829

---

recipes/gtfsort/build.sh
recipes/gtfsort/meta.yaml

Added recipe for gtfsort, a tool for sorting GTF files efficiently.
---- …

Add gtfsort recipe

---

recipes/centrifuge/meta.yaml

Repairs the `centrifuge`  recipe to restrict the version of python
In my previous recipe PRs from last week, I misunderstood  'Does not include evaluation scripts' of the description to mean in `centrifuge-core`  that it physically didn't have the scripts. So I replicated the version pins across both.
I just discovered that it actually means that the python version in the recipe `centrifuge-core` didn't support the evaluation scripts.
This re-adds the restriction in the `centrifuge`  recipe to allow the evaluation scripts to work, but not be included in environments with anything python >=3, and keeps `centrifuge-core` as is.
----
* If this PR adds …

Update centrifuge to fix python incompatibility

---

recipes/metabuli/meta.yaml

Metabuli 1.0.3
- New parameter: --tie-ratio in classify module. [default 0.95]
When the best matching species has a score MAX, species with score >= (MAX * --tie-ratio) is considered as a tie to the best score. When tie species occur for a read, the read is classified into their LCA.

metabuli1.0.3

---

recipes/gridss/0001-fix-samtools-version-check.patch
recipes/gridss/0002-set-gridssargs-for-virusbreakend-annotation.patch
recipes/gridss/meta.yaml

Apply two patches to GRIDSS:
1. make SAMtools version retrieval more robust (rel: SAMtools from bioconda had an unhanded version string format)
1. pass `gridssargs` to VIRUSbreakend annotation to enable users to control default heap size
---- …

Apply patches to GRIDSS 2.13.2

---

recipes/varfish-cli/meta.yaml

Python 3.9 is required for `typing.Annotated`.
---- …

require python >=3.9 for varfish-cli

---

recipes/bigtools/build.sh
recipes/bigtools/meta.yaml
recipes/pybigtools/build.sh
recipes/pybigtools/meta.yaml

This adds two recipes: one for the `bigtools` Rust crate binaries; and the second for `pybigtools`, a Python wrapper for Bigtools (also available on PyPI).
Bigtools is a library and associated tools for reading and writing bigwig and bigbed files, common files for storing processed NGS data.
---- …

Add recipes for `bigtools` and `pybigtools`

---

recipes/linearpartition/0001-FIX-command-broken-with-symbolic-link.patch
recipes/linearpartition/meta.yaml

This updates linearpartition to git-sha1
fa953f6323274eeadd92cc1f4e5535417f3fb821 from 2024-01-23.
The main reason for the update to an unreleased version is that all releases by the upstream repo require python2.
Changes since 1.0 (my summary):
- driver script uses python3
- support for SHAPE chemical probing data
- FASTA file input
- dangles -d0 mode support
---- …

Update linearpartition to 1.0.1.dev20240123

---

recipes/gatk4/meta.yaml
recipes/gcnvkernel/meta.yaml

Attempt to  gatk in gcnvkernel
---- …

Bump GATK4 gcnvkernel

---

recipes/multiqc/meta.yaml

Pin Plotly version tag (to address issues like https://github.com/MultiQC/MultiQC/issues/2323) and bump build number.

MultiQC: pin Plotly version

---

recipes/gffutils/meta.yaml

With `python >= 3.12`, gffutils will throw this error:
```
raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'sqlite3' has no attribute 'OptimizedUnicode'
```
This is due to `OptimizedUnicode` having been removed from python, starting with version `3.12`. See:
https://github.com/python/cpython/pull/23163/files
---- …

fix: pin gffutils python to <3.12

---

recipes/mgnify-pipelines-toolkit/meta.yaml

Adding the mgnify-pipelines-toolkit package to Bioconda for use in the development of MGnify nextflow and nf-core pipelines and subworkflows

Add mgnify-pipelines-toolkit recipe

---

recipes/snakemake/meta.yaml

Fix wrong Snakemake dependencies in last version bump
---- …

fix: snakemake dependencies

---

recipes/trtools/meta.yaml
recipes/trtools/test_trtools.sh.patch

Closes https://github.com/bioconda/bioconda-recipes/pull/45892
Update [trtools](https://bioconda.github.io/recipes/trtools/README.html): 5.1.1 → 6.0.0
Please merge this PR instead of https://github.com/bioconda/bioconda-recipes/pull/45892. We've removed a dependency, added a build dependency, and changed nearly all of our version constraints (via extensive testing in https://github.com/gymrek-lab/TRTools/pull/203)

Update trtools to 6.0.0

---

recipes/galah/meta.yaml

Unclear to me (as a galah author) why fastani was pinned to an exact version - doing so was limiting the python installed to exactly 3.8 for tools downstream (e.g. singlem)
---- …

galah: Loosen fastani version requirement.

---

recipes/igblast/build.sh
recipes/igblast/meta.yaml
recipes/igblast/shared_vdb.patch

Updates igblast from 1.21.0 to 1.22.0.
I updated the `shared_vdb.patch` file to account for a now-wrapped line in the original source, but other than confirming that it should patch correctly I don't know any details about that patch.  I also defined `run_exports` in the `meta.yaml` to use `max_pin="x"` following the [linter's advice](https://bioconda.github.io/contributor/linting.html#missing-run-exports) (as far as I can tell igblast seems to follow semantic versioning).

Update igblast to 1.22.0

---

recipes/pybigtools/build.sh
recipes/pybigtools/meta.yaml

Manually updating pybigtools v0.1.0 -> v0.1.1. [EDIT: -> v0.1.2]
`pybigtools` lives in a [monorepo](https://github.com/jackh726/bigtools.git) with `bigtools` and wasn't picked up for autobump, while `bigtools` was.
Changed URL to point to PyPI as source, hoping Bioconda Bot is able to autobump next time.
cc @jackh726 
----
* PRs require reviews prior to being merged. Once your PR is …

Update pybigtools to v0.1.2

---

recipes/bakta/meta.yaml

Temporarily pin Diamond to v2.1.8 due to a known upstream bug https://github.com/bbuchfink/diamond/issues/785.

pin Diamond to 2.1.8

---

recipes/hybran/meta.yaml

A deprecation snuck up:
https://github.com/biopython/biopython/blob/master/DEPRECATED.rst#bioseqfeature
> The `location_operator` argument was removed from the SeqFeature initializer in Release 1.82.

hybran: limit biopython dependency to <1.82 due to breaking change

---

recipes/kseqpp/meta.yaml

There is already an autobumped PR #46145 for this version. This PR adds the missing `run_exports`.

Add missing run_exports for kseqpp

---

recipes/jronn/meta.yaml

JRONN was incorrectly given an Apache-2.0 license, but Biojava tools are released under LGPL-2.1.
Updated the license in the meta.yaml.

Change incorrect license to LGPL-2.1 form Apache-2.0

---

recipes/msfragger/build.sh
recipes/msfragger/meta.yaml
recipes/msfragger/msfragger.py

In the `ionquant` script, `__file__` resolves to the symlink that is called, whereas we need to follow this symlink to find the location of the jar file.
The automated test was actually insufficient to catch this, so I fixed the test clause to ensure the Java program is successfully executed.
I also updated `build.sh` to remove the installation zip when done.
This PR is analogous to  #46124.
---- …

Fix MSFragger Recipe

---

recipes/pysam/arm_hwcap.patch
recipes/pysam/meta.yaml

* Add additional-platforms entry
* Work around old sysroot_linux-aarch64 version (as per the htslib recipe)
Avoid 2.17's missing HWCAP_* values by including the kernel header.
* Remove run requirements for shared libraries
These will be inferred from the library dependencies, as appropriate. In particular, this will omit the spurious zlib package dependency: only libzlib is required.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr> …

Build pysam for linux-aarch64

---

recipes/toulligqc/meta.yaml

There is a v2.6 but due to some package dependencies (pod5), conda build fails.
We have published a new pypi package for v2.5.2 but there was no update to v2.5.2 in bioconda

Update ToulligQC to v2.5.2

---

recipes/pybigtools/build.sh
recipes/pybigtools/meta.yaml

Reverts a diff made in #46052; installing only the wheel should significantly reduce the distribution size.
----
Conda …

pybigtools update

---

recipes/nextclade/meta.yaml
recipes/nextclade/run_test.sh

https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/109939/workflows/d6e1d687-5cdc-4c5d-865a-1ba0cb41b932/jobs/180788?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary
---- …

Update Nextclade: Enable linux-aarch64

---

recipes/locityper/build.sh
recipes/locityper/meta.yaml

Add recipe for Locityper `v0.13.4`.
[Locityper](https://github.com/tprodanov/locityper) is a targeted genotyper for complex polymorphic genes/loci based on short and long-read whole genome sequencing.

Add Locityper

---

recipes/taxor/meta.yaml

fixed a bug in `taxor profile` which cause program crashes on larger input files
updated taxor version from 0.1.1 to 0.1.2
---- …

update taxor to version 0.1.2

---

recipes/dnaio/meta.yaml

Needed by `cutadapt`: https://github.com/bioconda/bioconda-recipes/pull/46424
---- …

dnaio: add linux-aarch64 build

---

recipes/sistr_cmd/build.sh
recipes/sistr_cmd/meta.yaml

Recipe for SISTR version 1.1.2 (version update) that includes database init during setup

bump sistr v1.1.2 new conda recipe

---

recipes/snippy/meta.yaml

related to https://github.com/bioconda/bioconda-recipes/issues/46114
the pinned vcflib version does not owrk with newer versions of tabixxp
---- …

pin tabix version in snippy

---

recipes/plink2/meta.yaml

Updating plink2 to the latest stable build (https://www.cog-genomics.org/plink/2.0/)

Update Plink2 to Alpha 5.10 final (5 Jan)

---

recipes/busco/meta.yaml

Patch existed but had not been added to meta.yaml so it wasn't patched.

fix busco patch

---

recipes/bowtie2/build.sh
recipes/bowtie2/meta.yaml

bowtie2: add linux-aarch64 build

---

recipes/stringtie/build.sh
recipes/stringtie/meta.yaml

update stringtie adding new platform
---- …

update stringtie adding new platform

---

recipes/srahunter/meta.yaml

added new file:   srahunter/meta.yaml
Dear Bioconda team,
I'm Bortoletto Enrico from university of Padova (Italy), I developed a new tool useful for automatizing the download of data and metadata from SRA.
Specifically SRAHunter is a tool designed to facilitate the downloading and processing of data and metadata from the Sequence Read Archive (SRA) of the National Center for Biotechnology Information ([NCBI](https://www.ncbi.nlm.nih.gov/)). This Python package includes three modules : a module for automatized download of fastq files from SRA (srahunter download), a module for main SRA associated metadata retrieval (srahunter metadata), and a module to retrieve the full associated metadata to an accession number (srahunter fullmetadata).
Sincerely,
Bortoletto Enrico  
----
<table>
<tr> …

 Add srahunter/meta.yaml

---

recipes/toulligqc/meta.yaml

There is a v2.6 but due to some package dependencies (pod5), conda build fails.
We have published a new pypi package for v2.5.3 but there was no update to v2.5.3 in bioconda.

Updated ToulligQC to v2.5.3

---

recipes/gffread/meta.yaml

update gffread adding new platform
---- …

update gffread adding new platform

---

recipes/ucsc-bedgraphtobigwig/meta.yaml
recipes/ucsc-bedgraphtobigwig/patch1.patch

add additional platform to compile for aarch.
----
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this:
```yaml
build:
run_exports:
- ...
```
with `...` being one of:
| Case                             | …

update bedgraphtobigwig with additional platform

---

recipes/mugsy/meta.yaml

Attempt to fix sed issue on macos m1
On macos m1, an error is produced during install of mugys:
```
stderr: sed: 1: "/Users/XXXX/miniforge3 ...": command a expects \ followed by text
```
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the …

Update: Musgy - Fix issue with sed on macos m1

---

recipes/toulligqc/meta.yaml

There is a v2.6 but due to some package dependencies (pod5), conda build fails.
We have published a new pypi package for v2.5.4 but there was no update to v2.5.4 in bioconda.

Updated ToulligQc to v2.5.4

---

recipes/sistr_cmd/build.sh
recipes/sistr_cmd/meta.yaml

sistr container tries to write in the container, as it adds a few MB of database files. This should add the data
```
File "/usr/local/lib/python3.12/site-packages/sistr/sistr_cmd.py", line 368, in main
setup_sistr_dbs()
File "/usr/local/lib/python3.12/site-packages/sistr/sistr_cmd.py", line 222, in setup_sistr_dbs
download_to_file(SISTR_DB_URL, tmp_file)
File "/usr/local/lib/python3.12/site-packages/sistr/sistr_cmd.py", line 187, in download_to_file
with open(file, 'wb') as f:
^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.12/site-packages/sistr/data.tar.gz'
```
----
* If this PR adds or updates a recipe, use …

fix issue with sistr container

---

recipes/gubbins/meta.yaml

Met with this on the singularity image:
```
File "/usr/local/bin/run_gubbins.py", line 7, in <module>
from gubbins.run_gubbins import main
File "/usr/local/lib/python3.10/site-packages/gubbins/__init__.py", line 16, in <module>
from gubbins import common
File "/usr/local/lib/python3.10/site-packages/gubbins/common.py", line 42, in <module>
from gubbins.pyjar import jar, get_base_patterns
File "/usr/local/lib/python3.10/site-packages/gubbins/pyjar.py", line 212, in <module>
def seq_to_int(seq,out_seq):
File "/usr/local/lib/python3.10/site-packages/numba/core/decorators.py", line 229, in wrapper
disp.enable_caching()
File "/usr/local/lib/python3.10/site-packages/numba/core/dispatcher.py", line 856, in enable_caching
self._cache = …
```

adjust python pinning in gubbins

---

recipes/abritamr/meta.yaml

abritamr packages a prebuilt database that is locked to a specific ncbi-amrfinderplus version. Added a note to review this every new release, and which file to review
```
Database directory: '/usr/local/lib/python3.12/site-packages/abritamr/db/amrfinderplus/data/2024-01-31.1'
Database version: 2024-01-31.1
ESC[1;31m*** ERROR ***ESC[0m
Database requires sofware version at least 3.12.1
HOSTNAME: ?
SHELL: ?
PWD: /home/robert_petit/pytest_workflow_a9fmmcy8/abritamr-test/work/43/5c9ff0c6ef49be3520c78e6dcff64c
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Progam name:  amrfinder
Command line: amrfinder -n GCF_001682305.fna -o results/amrfinder.out --plus --threads 4 -d /usr/local/lib/python3.12/site-packages/abritamr/db/amrfinderplus/data/2024-01-31.1
```
----
Please read …

fix amrfinderplus pinning in abritamr

---

recipes/dram/fix_setup.patch
recipes/dram/meta.yaml

Update DRAM version

---

recipes/locidex/meta.yaml

Submitting build 1. 
Updated pyrodigal >=3.0 requirement as `locidex` calls an option called `GeneFinder` that only exists in version 3 of pyrodigal

LOCIDEX BUILD #1 v0.1.1 -> updated pyrodigal >=3.0 due to new feature for locidex

---

recipes/magus-msa/meta.yaml

I have changed the packaging of MAGUS in the recent v0.2.0 release.
The build is still done via `pip install .`, but some of the tests were failing, because they were testing imports that no longer exist.
This commit changes the tests to reflect the new architecture.

Update MAGUS recipe, bump to v0.2.0

---

recipes/hybran/meta.yaml

New dependencies in this version. Also, we've restored compatibility with latest biopython versions and so I've removed the version pinning.

hybran: update to version 1.8

---

recipes/bioconductor-dexseq/meta.yaml

I think htseq-count is required for dexseq_count.py.
Hopefully this is OK, I don't know why but it was removed in https://github.com/bioconda/bioconda-recipes/commit/25494d8ab5b1380a3e69445a1bb7e1d251cb3d2f  
----
* Please post …

Update dexseq to reinstate htseq-count dependency

---

.circleci/check-for-additional-platforms.sh

Using sed does not work with inputs like:
```
- {{ name | lower }} --version | grep {{ version }}
```
i.e. with several placeholders on the same line.
I was not able to tell sed to use non-gready match.
Found the issue while debugging https://github.com/bioconda/bioconda-recipes/pull/46880
---- …

ci: [CircleCI] Use `tr` to drop `{{` and `}}`

---

.circleci/check-for-additional-platforms.sh

Saving to `/usr/local/bin` fails with `Permission denied` error. For example
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/112535/workflows/40d63e46-327b-4fcd-8386-b4384a686ce7/jobs/183359?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary is a successful job that fails with `Permission denied`. It seems (an older version of) `yq` is still available in the PATH that is used later.
---- …

ci: [CircleCI] Save `yq` to ~/bin/

---

recipes/tower-cli/meta.yaml
recipes/tower-cli/tw.sh

Removes shell script which matched `org*` which caused issues when calling `tw organizations`: https://github.com/seqeralabs/tower-cli/issues/388
---- …

Fix tw organizations sub command

---

recipes/phispy/meta.yaml

Changes in BioPython's `SeqFeature` class in v1.82 (https://github.com/biopython/biopython/issues/4563) brought issues to PhiSpy (https://github.com/nf-core/modules/pull/5292#issuecomment-2032147178, https://github.com/linsalrob/PhiSpy/issues/67). This fixes the BioPython version in PhiSpy's recipe to a functional one.
---- …

Update PhiSpy with fixed biopython version

---

recipes/fragpipe/meta.yaml

Philosopher 5.1.0 is actually incompatible with FragPipe 20.0, which becomes apparent in certain configurations. This downgrades Philosopher to 5.0.0.
In the near future, we can upgrade both FragPipe and Philosopher to 21.* and 5.1.0 in tandem.
---- …

Downgrade Philosopher for compatibility with FragPipe

---

recipes/megahit/linux-aarch64-support-pr-368.patch
recipes/megahit/meta.yaml

megahit: add linux-aarch64 build

---

azure-pipeline-nightly.yml

The nightly build is marked as a failure because bioconda-repodata-patches has already been built in a previous step of the pipeline. `--exclude` was added for this purpose in https://github.com/bioconda/bioconda-utils/pull/962 
---- …

ci: nightly uploader needs to exclude bioconda-repodata-patches that's already built

---

recipes/argnorm/meta.yaml

Adding argNorm to bioconda. argNorm is a tool to normalize antibiotic resistance genes (ARGs) by mapping them to the antibiotic resistance ontology created by the CARD database. argNorm also provides drug categorization of drugs that antibiotic resistance genes confer resistance to.
----

Add argNorm recipe

---

recipes/querynator/meta.yaml

bioconda linting failed because of missing_run_exports. This should fix it.
---- …

fix missing_run_exports

---

recipes/argnorm/meta.yaml

Explicitly specify pronto version as current conda installation downloads older version of pronto

BUG specify pronto version for argnorm

---

recipes/cd-hit/meta.yaml

cd-hit: add linux-aarch64 build

---

.github/workflows/Bulk.yml
.github/workflows/PR.yml
.github/workflows/master.yml
.github/workflows/nightly.yml

GitHub Actions changes are being rolled out to change `macos-latest` to use `macos-14` which has ARM architecture. Specify `macos-13` to continue to build and test on x86-64.
NOTE: This really only affects the `bulk` branch because the other workflows are currently disabled on GitHub Actions and run on Azure instead. I'm updating those disabled workflow files now in case we decide to reuse them in the future.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

ci: specify macos version to control architecture

---

recipes/merqury/meta.yaml

Both are requirements not necessarily present in a working version on host systems and are used in merqury-mash.sh. In particular `awk -v name=$name '{print name"\t"$2"\t"-10*log(1-$1)/log(10)"\t"(1-$1)}'` fails with busybox awk:
`Math support is not compiled in`
---- …

Add awk and sed to merqury dependencies

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

Bump the patching to include #47235's new HTSlib release and the (coincidentally the same version number!) recent upstream libdeflate release. Neither upstream release changes its library's soversion.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that …

bioconda-repodata-patches: Bump for new htslib and libdeflate releases

---

recipes/metabuli/meta.yaml

- Fixed a minor reproducibility issue.
- Fixed a performance-harming bug occurring with sequences containing lowercased bases.
- Auto adjustment of --match-per-kmer parameter. 
- Record version info. in db.parameter
----
* …

[Update] Metabuli 1.0.5

---

recipes/nextclade/meta.yaml

Update [nextclade](https://bioconda.github.io/recipes/nextclade/README.html): 3.3.1 → 3.3.1.
<table>
<tr>
<td>Home</td>
<td><a href="https://github.com/nextstrain/nextclade">https://github.com/nextstrain/nextclade</a></td>
</tr>
<tr>
<td>Summary</td>
<td>Viral genome alignment, mutation calling, clade assignment, quality checks and phylogenetic placement</td>
</tr>
<tr>
<td>Recipe maintainers</td>
<td>@pvanheus, @corneliusroemer, @ivan-aksamentov</td>
</tr>
</table>
@BiocondaBot please fetch artifacts
Note: this pull request is submitted [automatically](https://github.com/nextstrain/nextclade/blob/master/.github/workflows/bioconda.yml), triggered by [a release](https://github.com/nextstrain/nextclade/releases) in …

fix: Nextclade sha256sum for 3.3.1 osx_64

---

recipes/snakemake/meta.yaml

This raises the minimum required version for smart-open to ">=4". This prevents a bug 
https://github.com/snakemake/snakemake/issues/2765
when using snakemake with the old version of smart-open: 
I have also opened a PR to snakemake, to also set the restriction in "setup.cfg" as well: 
https://github.com/snakemake/snakemake/pull/2833

Update snakemake minimum version for smart-open

---

recipes/bactopia/meta.yaml

Bactopia will be receiving an update that will make previous versions no longer work with `bactopia-py >=1.0.9`. As a pre-cursor to this change I am pinning v3.0.1 to `bactopia-py 1.0.9` 
When the latest version is released, the pinning will go back to `bactopia-py >=1.10.0`
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, …

fix pinning of bactopia

---

recipes/prophyle/build.sh
recipes/prophyle/meta.yaml

prophyle: add linux-aarch64 build

---

recipes/hifiasm/build.sh
recipes/hifiasm/linux-aarch64-support.patch
recipes/hifiasm/meta.yaml

hifiasm: add linux-aarch64 build

---

recipes/pygtftk/meta.yaml

pygtftk: add linux-aarch64 build

---

recipes/earlgrey/build.sh
recipes/earlgrey/meta.yaml

Add EMBOSS and pybedtools as requirements for the environment. 
---- …

Update Earl Grey meta.yml

---

recipes/pybigtools/build.sh
recipes/pybigtools/meta.yaml

Trying to switch to a URL pattern autobump will recognize.
---- …

Update pybigtools to 0.1.3

---

recipes/wgatools/meta.yaml

wgatools is reporting a divergent build string in the nightly build for osx. This appears to be because a previous build output file from the same PR ended up in the Azure OSXArtifacts.zip file.
(The artifact behavior will be handled separately. This is just to resolve the error for wgatools.)
---- …

bump build number for wgatools

---

.circleci/config.yml

In the (hopefully near-ish) future, `quay.io/bioconda/bioconda-utils-build-env-cos7` will point to a manifest usable for all architectures.
Until then, let's make sure we use the versioned and not `latest` tag for the `aarch64` builds (as we do for the `x86_64` builds via the default for `--docker-base-image`).
----
* PRs require reviews prior to being merged. Once your PR is …

CI: use correct build-env container for aarch64

---

recipes/pyopal/meta.yaml

Supersedes #47772
The recipe needed to be updated to add the new `scoring-matrices` dependency. I also added `linux-aarch64` as an additional platform since PyOpal supports Aarch64 using NEON vectorization.
----
* Please post …

Update pyopal to 0.6.0

---

recipes/snpeff/meta.yaml
recipes/snpeff/snpeff.py

Currently SneEff phones home to `www.dnaminer.com` (https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/logStatsServer/LogStats.java#L37-L42) which is no longer a registered domain. Phoning home can be disabled with `-noLog`.
This PR makes it so that SnpEff is always executed with `-noLog` I have submitted an issue upstream at https://github.com/pcingola/SnpEff/issues/541
I also added a debug feature to the python wrapper just for sanity checks to make sure `-noLog` is being passed
----
* New recipes not directly relevant to …

disable phone home snpeff

---

recipes/scalpel/build.sh
recipes/scalpel/conda_build_config.yaml
recipes/scalpel/meta.yaml

scalpel: add linux-aarch64 build

---

recipes/multiqc/meta.yaml

* Bumped to v1.22
* Removed the `uses_setuptools` skip lint, hopefully no need to skip this any more since `pkg_resources` was removed in v1.16
---- …

Update: MultiQC - Bump to v1.22

---

recipes/sambamba/build.sh
recipes/sambamba/meta.yaml

- Sambamba recompiles the output binary for both the `make` and `make test` targets
- the `make` target but not `make test` target applies optimisation
- the current command ordering in `build.sh` means that the unoptimised binary is inadvertently distributed
- I have observed a ~8x slowdown for `sambamba merge` when using the Conda package compared to manually compiled
The following issues are also likely related:
- https://github.com/biod/sambamba/issues/503
- https://github.com/biod/sambamba/issues/447
- adjust command ordering so that the optimised binary is distributed
- please do not merge until I have been able to confirm slowdown is resolved with in the new build artefacts
----
Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) …

Update Sambamba recipe to use release binary rather than test binary

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

The current build of `pysam` contains a max pin of 1.19 for `libdeflate`, which conflicts with a lot of packages in the QIIME 2 ecosystem. However, it appears as though `pysam` is compatible with the newer version of `libdeflate` - this just needs to be reflected in the bioconda build (see this related [PR](https://github.com/bioconda/bioconda-recipes/pull/40675) and [comment](https://github.com/pysam-developers/pysam/issues/1114#issuecomment-1521641722)).

PATCH: include pysam in libdeflate repodata-patches

---

recipes/metav/meta.yaml

add two software dependencies (samtools >=1.14, salmon >=1.10.0) for metav to resolve the running bug when [Trinity](https://github.com/trinityrnaseq/trinityrnaseq) is called.

update metav recipes

---

recipes/hmftools-mark-dups/1.1.5/build.sh
recipes/hmftools-mark-dups/1.1.5/markdups.sh
recipes/hmftools-mark-dups/1.1.5/meta.yaml

- update MarkDups 1.1.5 recipe to use fixed Sambamba package, see:
- https://github.com/bioconda/bioconda-recipes/pull/48071
- https://github.com/bioconda/bioconda-recipes/pull/48074
- the change is applied only to the most recent MarkDups release that is available (1.1.5)
- MarkDups 1.1.6 has since been deleted from the [hartwigmedical/hmftools releases](https://github.com/hartwigmedical/hmftools/releases?q=mark-dups)
- I expect the next MarkDups release will be 1.1.6 (re-release) or 1.1.7, and I'll handle accordingly as that happens
----
* …

Update MarkDups 1.1.5 to use fixed Sambamba package

---

recipes/kissplice/build.sh
recipes/kissplice/meta.yaml

New upstream version, and simplify build.sh to use modern cmake commands.
---- …

Update kissplice 2.6.5

---

recipes/strdust/build.sh
recipes/strdust/meta.yaml

This PR adds [STRdust](https://github.com/wdecoster/STRdust)
---- …

Add STRdust

---

recipes/cami-opal/meta.yaml

This tool failed with the current build with:
```
File "/home/paul/miniconda3/envs/opal/bin/opal.py", line 242, in <module>
main()
File "/home/paul/miniconda3/envs/opal/bin/opal.py", line 235, in main
html.create_html(pd_rankings, ranks_scored, pd_metrics, labels, sample_ids_list, plots_list, output_dir, args.desc)
File "/home/paul/miniconda3/envs/opal/lib/python3.10/site-packages/cami_opal/html_opal.py", line 636, in create_html
select_sample, select_rank, heatmap_legend_div, mytable1 = create_metrics_table(pd_metrics, labels, sample_ids_list)
File "/home/paul/miniconda3/envs/opal/lib/python3.10/site-packages/cami_opal/html_opal.py", line 505, in create_metrics_table
html.write(mydf_metrics.style.apply(get_heatmap_colors, df_metrics=mydf_metrics, …
```

Update OPAL meta.yaml

---

recipes/biobb_pytorch/meta.yaml

* [CI/CD] Updating checkout GA action to v4
* [TESTS] Avoiding type hint checking in test files
* [CI/CD] Add sync workflow for CASTIEL project
* [DOCS] Updating command line documentation
* [FIX] Adding shebang to the file first line
* [FIX] Adding mypy_cache to gitignore
* Merge branch 'master' of github.com:bioexcel/biobb_pytorch
* [DOCS] Update Bioschemas
* references.jsonld
* Updated CITATION.cff
* citation GitHub Action
* citation
* JSON
* Fixed bugs in documentation
----
* New recipes not directly relevant to the biological sciences need …

[biobb_pytorch] update 4.2.1

---

.github/workflows/PR.yml
config.yml

This is in conjunction with https://github.com/bioconda/bioconda-common/pull/54 to remove `defaults` channel from our builds.
---- …

CI: Remove `defaults` from `config.yml`

---

recipes/difcover/0001-Replaces-fname-char-with-std-string.patch
recipes/difcover/build.sh
recipes/difcover/meta.yaml

This PR addresses this issue: https://github.com/timnat/DifCover/pull/4
It also fixes a missing file in the original DifCover build script.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please merge</code> command is now …

Update: Patches difcover, adds missing R script

---

recipes/sortmerna/build.sh
recipes/sortmerna/meta.yaml

sortmerna: add linux-aarch64 build and update to 4.3.7

---

recipes/auspice/meta.yaml

Resolves https://github.com/nextstrain/auspice/issues/1778
---- …

Bump auspice to v2.53.0

---

recipes/kraken2/Makefile.patch
recipes/kraken2/build.sh
recipes/kraken2/meta.yaml

`kraken2-build` needs `rsync` (and likely wget as well). 
---- …

kraken2: add missing requirements

---

recipes/tbvcfreport/meta.yaml

This updates tbvcfreport to the bugfix release 1.0.1 (which adds support for when TB-Profiler predicts mixed lineages)
---- …

Update tbvcfreport to version 1.0.1

---

recipes/abnumber/meta.yaml

Bump up abnumber to latest release 0.3.3: https://github.com/prihoda/AbNumber/releases/tag/v0.3.3

Bump up abnumber to 0.3.3

---

recipes/binette/meta.yaml

This PR updates the Binette recipe to fix the required `pyfastx` version.
As mentioned in this Binette issue: https://github.com/genotoul-bioinfo/Binette/issues/15.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please …

Update Binette recipe

---

recipes/centrifuge/build.sh
recipes/centrifuge/centrifuge-linux-aarch64.patch
recipes/centrifuge/meta.yaml

centrifuge: add linux-aarch64 build

---

recipes/tcfinder/meta.yaml

Add `tcfinder`, a lightweight tool to find clusters of samples within a phylogeny.

Add tcfinder v1.0.0

---

azure-pipeline-master.yml
azure-pipeline-nightly.yml
azure-pipeline.yml

- Remove caching from CI (causing more issues than it solves and not saving much time)
- Remove old quay.io/dpryan79/mulled_container image which is no longer used
- Source `common.sh` to include MACOSX environment variables (needed for new pinnings)

CI updates: remove caching, remove old docker image, mac vars

---

recipes/plink2/meta.yaml

Update [`plink2`](https://www.cog-genomics.org/plink/2.0): **2.00a5.10** → **2.00a5.12** (released on June 25, 2024)
I simply adapted https://github.com/bioconda/bioconda-recipes/pull/46505 to write this PR

Update plink2 to 2.00a5.12 final

---

recipes/icfree-ml/meta.yaml

New package « icfree-ml » to be published in bioconda:
> iCFree is a Python-based program designed to automate the process of generating and running a Snakemake workflow for sampling and preparing instructions for laboratory experiments. The program includes components for generating samples, creating plates, and instructing the handling of these plates.
---- …

Add recipe for icfree-ml 2.3.0

---

recipes/sambamba/meta.yaml

Addressing the following lints:
```
16:53:04 BIOCONDA INFO (OUT) WARNING (sambamba): dso library package conda-forge/linux-64::ldc==1.38.0=h8d30b7e_2 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
16:53:04 BIOCONDA INFO (OUT) WARNING (sambamba): run-exports library package conda-forge/linux-64::bzip2==1.0.8=hd590300_5 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
16:53:04 BIOCONDA INFO (OUT) WARNING (sambamba): run-exports library package conda-forge/linux-64::xz==5.2.6=h166bdaf_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps …
```

Remove unnecessary run constraints from sambamba

---

.circleci/config.yml
recipes/sambamba/build.sh
recipes/sambamba/meta.yaml

sambamba: add linux-aarch64 build

---

.github/workflows/CommentResponder.yml

The comment responder is repeatedly triggering for no reason. I'm not sure if it's caught in a loop of triggering itself, but it keeps running against the latest commit on master. The `check_run` trigger doesn't pass the conditions for any of the bot jobs as of 3 years ago (see comment on line 11).
It's showing up in GitHub Actions as "completed by ghost". I'm not sure if that's because the latest commit was authored by more than one person. Maybe a GitHub Actions bug. In any case, there is no reason to keep this going.

fix: disable unused trigger for comment responder

---

recipes/kmertools/build.sh
recipes/kmertools/meta.yaml

This PR adds [`kmertools`](https://github.com/anuradhawick/kmertools) to bioconda. `kmertools` is a k-mer based feature extraction tool designed to support metagenomics and other bioinformatics analytics.
---- …

Add kmertools v0.1.0

---

recipes/parm/meta.yaml

The major change is fixing an error caused when attribution_range was set.
Other small changes:
* The output directory of mutagenesis is created if it doesn't exist.
* The cuda log (telling whether cuda is available) is shown only when training starts.
* Small changes in how the arguments are printed at the start of each program
**Full Changelog**: https://github.com/vansteensellab/PARM/compare/v0.0.2...v0.0.3

Update parm to v0.0.3

---

recipes/epik/meta.yaml

This PR is brother to PR #49000 . See details there.
It just fixes version of boost-cpp to attempt to solve an issue that cannot be detected in the bioconda CI.

epik: updates boost-cpp to strict version 1.85

---

recipes/vsearch/build.sh
recipes/vsearch/meta.yaml

no idea if this _should_ even work, but let's try!
[Current error](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/122140/workflows/754c2e91-577e-4ba9-91e4-4e721cf3384a/jobs/196176?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) is that it's using the `m4` that comes with macs, not the one from conda. Strange!
>01:20:07 BIOCONDA INFO (ERR) autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
01:20:07 BIOCONDA INFO (ERR) aclocal: error: /opt/mambaforge/envs/bioconda/conda-bld/vsearch_1720660763326/_build_env/bin/autom4te failed with exit status: 1
01:20:07 BIOCONDA INFO (ERR) autoreconf: error: aclocal failed with exit status: 1
@martin-g, would you be willing to have a look?

Build vsearch for osx-arm64

---

recipes/meteor/meta.yaml

Dear Bioconda maintainers,
The modified recipe in https://github.com/bioconda/bioconda-recipes/commit/3a31c36a3ce1b0d8fb2c57d1cfb9547252ae7524 removed the minimal version for bcftools (which was also incorrect in my commit). We need the version 1.19 as minimal version for bcftools. 
Current users face issues libcrypto which was solved in more recent version of bcftools.
Thank you,
Amine
---- …

Fix version for bcftools

---

recipes/galaxy-data/meta.yaml
recipes/galaxy-files/meta.yaml
recipes/galaxy-objectstore/meta.yaml
recipes/galaxy_sequence_utils/meta.yaml
recipes/jms-metabolite-services/meta.yaml
recipes/khipu-metabolomics/meta.yaml

Related to #48971 
Setuptools changed some sdist paths, making autobump fail for recipes that use the pre-change path.
I went through all packages that have been received Pypi updates since the setuptools change at the end of Dec 2023.
and contained vulnerable paths (containing hyphen `-`).
---- …

Fix pypi urls for bot autobump: setuptools changed some source paths

---

recipes/bx-python/meta.yaml

Autobump didn't work because of changed pypi source file path, see #48971 
I disabled python 3.8 builds because the build errored with python 3.8
You can see the failing build here: https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/122485/workflows/1586943a-0729-439c-9c87-1c2bc52eecbd/jobs/196844?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary
As the recipe has no maintainers (volunteers come forward please!) I requested reviews from bx-python contributors who are also members of bioconda. Maybe you know how to get 0.12 to work with py38.
----
* If this PR adds or updates a …

Bump bx-python to 0.12, fix pypi url

---

recipes/paragone/meta.yaml
recipes/paragone/post-link.sh
recipes/paragone/pre-unlink.sh

Restricting dependency Julia to v1.8.5, as conda-forge Julia packages for v1.9.x  - 1.10.x do not use the conda dependency `libz.so.1`  as described [here](https://github.com/conda-forge/julia-feedstock/issues/281), which can result in the error described [here](https://github.com/chrisjackson-pellicle/ParaGone/issues/8).
Adding `post-link.sh` and `pre-unlink.sh` scripts to install and precompile the Julia module dependency `ArgParse`, so that this happens at package install time rather than program run-time (and hence fails in the latter scenario when paragone is installed in a read-only container). The alternative approach (installation and precompilation of the module during package build) fails because the precompiled binaries contain the placeholder prefix - replacement of this with …

Update recipe for paragone

---

recipes/pathogen-embed/meta.yaml

pathogen-embed: Use predictable url that autobump can use

---

recipes/methbat/build.sh
recipes/methbat/meta.yaml

Adds the MethBat tool to bioconda. The recipe is based on existing recipe setup from pb-StarPhase.
----
Conda is able …

Add MethBat to bioconda recipes

---

.github/workflows/CommentResponder.yml

This seems to have been disabled with a plan to re-enable it that never happened.
This may cause excessive runs, but there's no way to know without merging it in. I'll keep an eye on it.

ci: reenable artifact fetching on successful check suite

---

.github/workflows/CommentResponder.yml

This bot is a little out of control. I guess GitHub considers each CI platform to be its own check suite?
I'll see if I can figure out a way to get it to do what we want, but for now, I don't want to spam all the PRs.

ci: revert automatic artifact fetching

---

recipes/bioconductor-maaslin2/meta.yaml

Update Maaslin2 recipe to pull v1.81.0 which is the latest release from the new release of BioC v3.19.

Update Maaslin2 version to use latest release from BioC v3.19

---

recipes/bowtie/build.sh
recipes/bowtie/meta.yaml

Build bowtie on macOS ARM

---

recipes/galaxy-data/meta.yaml
recipes/galaxy-schema/meta.yaml
recipes/isa-rwval/build_failure.linux-64.yaml
recipes/isa-rwval/build_failure.osx-64.yaml
recipes/isa-rwval/meta.yaml

Attempt to update galaxy-data to 24.1.1.
galaxy-data now requires another package, galaxy-schema, so this PR also adds that.
I cannot figure out how to get the import tests to pass: galaxy-schema requires `pydantic[email]` but just installing the extra dependency `email-validation` does not seem to work. I wonder whether adding the extra `[email]` to pydantic has some side-effects beyond installing `email-validation`.
Any help greatly appreciated. I don't use galaxy at all - I just wanted to help update a package that has not received autobumps. 
Past editors of galaxy-data have been:
- @bernt-matthias 
- @bgruening
----
* If this PR adds or updates …

Update galaxy-data to 24.1.1, add galaxy-schema recipe

---

recipes/clermontyping/build.sh
recipes/clermontyping/meta.yaml

Restructured clermontyping to use the share folder for rscripts and a small reference dataset (few megabytes)
---- …

clermontyping use share folder

---

recipes/arcas-hla/meta.yaml

Fix for the error from `arcasHLA genotype` command:
```
Deprecated: `kallisto pseudo` is deprecated. See `kallisto bus`.
```
---- …

Update arcas-hla fix kallisto version

---

recipes/iqtree/build.sh
recipes/iqtree/conda_build_config.yaml
recipes/iqtree/meta.yaml
recipes/iqtree/patch

- Compiling iqtree2 with cmaple feature
- Soft-link iqtree alias to iqtree2 to half disk space usage (previously was copied), saves 3MB
- Use 4 CPUs for CircleCI's large arm runners, when used, halfs build time -> better resource usage
- Remove example files (saves 2MB disk space), these shouldn't be packaged, they aren't included in env anyways
- Add actual functional test (on osx only due to mulled-tests not working with `source_files`, but better than nothing)
- Use ninja instead of make with cmake
- Silence warnings -> build log is finally not 10k lines
----
* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first …

Build iqtree2 with cmaple feature, reduce pkg size from 8MB to 3MB

---

recipes/el_gato/meta.yaml

Updates el_gato to version 1.18.0 and adds packaging dependency.
Replaces #49528

Update el_gato to 1.18.0

---

recipes/pacu_snp/meta.yaml

A recipe for the PACU SNP phylogeny workflow.
PACU is a workflow for whole genome sequencing based phylogeny of Illumina and ONT R9/R10 data for bacteria.
More information is available on the [GitHub page](https://github.com/BioinformaticsPlatformWIV-ISP/PACU) or in the corresponding [publication](https://pubmed.ncbi.nlm.nih.gov/38441926/).
----
This is my first pull request for bioconda. I followed the instructions as best I could, but please let me know if I need to change anything.

Add recipe for PACU snp

---

recipes/neodisambiguate/build.sh
recipes/neodisambiguate/meta.yaml

This PR adds a new tool ([`neodisambiguate`](https://github.com/clintval/neodisambiguate)) for multi-species read disambiguation.
This type of NGS analysis is commonly used in patient-derived xenograft experiments. e.g.:
- https://pubmed.ncbi.nlm.nih.gov/27990269/
---- …

Add neodisambiguate for multi-species read disambiguation (xenografts, etc.)

---

recipes/cmaple/build.sh
recipes/cmaple/meta.yaml

cmaple: disable AVX, for Rosetta2 and old CPU compatibility

---

recipes/pacu_snp/meta.yaml

I have added a missing dependency and increased the build number.

Update PACU SNP (new build) - added missing bedtools dependency, increased build number

---

recipes/isoquant/meta.yaml

Updates IsoQuant to 3.5.0
Adds a few more requirements, so should be preferred over 
https://github.com/bioconda/bioconda-recipes/pull/49779

Update isoquant to 3.5.0

---

recipes/blast/meta.yaml

The upload CI didn't run because there was a "ci skip" in the commit message for the Blast PR merge. Now it's overwhelming the resources on the nightly linux build. This will rebuild on the PR by itself and then get uploaded on merge to master.
---- …

blast: bump build number to rebuild linux

---

recipes/mummer/build.sh
recipes/mummer/meta.yaml
recipes/mummer/patches/addleafcount_explicit.patch
recipes/mummer/patches/findmaxmat_explicit.patch
recipes/mummer/patches/findmumcand_explicit.patch
recipes/mummer/patches/linkloc_explicit.patch
recipes/mummer/patches/procmaxmat_explicit.patch

Should fix the hashbang (issue #28209; see https://bioconda.github.io/contributor/troubleshooting.html#perl-or-python-not-found), but also tries to re-enable building on macOS plus adding osx-arm64 for use on recent Apple hardware.
---- …

Fix mummer hashbang and build on macOS including ARM

---

recipes/nanoplot/meta.yaml

At first the URL didn't seem to work. Luckily @martin-g discovered that the capitalized NanoPlot was the problem. Using a lowercase nanoplot in the url solves the issue.
---- …

Nanoplot: Use a versioned URL for downloading 

---

recipes/pasta/meta.yaml
recipes/sepp/meta.yaml

As suggested by @aliciaaevans in #47895, I here lift the pinning of dendropy for PASTA and SEPP.
---- …

lift restrictions of dendropy, which is a dependency of SEPP

---

recipes/metabinner/build.sh
recipes/metabinner/meta.yaml

When trying to follow the tutorial, I noticed many of the auxiliary/preparation scripts were not available on the path because only the directory was copied to the `bin/`, not the scripts themselves. 
This updates the recipe so the build is backwards compatible - i.e., the directories are still copied in the bin but the scripts are also symlinked into the `bin/` so they are easily available to the user.
---- …

Update Metabinner (Make scripts/auxilirary tools available on path)

---

recipes/cyrcular/build.sh
recipes/cyrcular/meta.yaml

This PR adds a recipe for [cyrcular](https://github.com/tedil/cyrcular/tree/v0.3.0), a circular DNA calling tool optimized for nanopore sequencing data.

Add recipe for cyrcular

---

recipes/polap/meta.yaml

Fix a bug and a bioconda package name.
- A bug in polap is fixed.
- kmer-jellyfish replaces jellyfish, which has duplicates in conda-forge channel as well.

Update polap to v0.2.6

---

recipes/bowtie2/build.sh
recipes/bowtie2/meta.yaml

TBB concurrency replaced with C++ threads since bowtie 2.4.3
(see: https://bowtie-bio.sourceforge.net/bowtie2/news.shtml)

Update bowtie2 to remove TBB dependencies

---

recipes/pgenlib/meta.yaml

Update [`pgenlib`](https://github.com/chrchang/plink-ng/tree/master/2.0/Python#readme): **0.90.2** → **0.91.0** (released on Jun 18, 2024)
`pgenlib` v0.91.0 adds numpy 2.0 as a build dependency for versions of python >= 3.9 (see https://github.com/chrchang/plink-ng/pull/272)
This PR also drops `pin_compatible` per https://github.com/conda-forge/conda-forge.github.io/issues/2156 and enables builds on macOS ARM and linux aarch64

Update pgenlib to 0.91.0 and enable arm64/aarch64 builds

---

recipes/cyvcf2/meta.yaml

`cyvcf2` already has support for ARM on PyPI. This PR also adds ARM support on bioconda

cyvcf2: enable osx-arm64 build

---

recipes/r-buencolors/build.sh
recipes/r-buencolors/meta.yaml

This adds [the GitHub R package `BuenColors`](https://github.com/caleblareau/BuenColors) as `r-buencolors`. Upstream lacks proper Releases/tags ([requested here](https://github.com/caleblareau/BuenColors/issues/5)), but for now the recipe uses a specific commit as identifier.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, …

Adds r-buencolors

---

recipes/art/build.sh
recipes/art/meta.yaml

Enable osx-arm64 builds for ART
For some reason, I had to manually check the host and alter the `./configure` command to cross-compile for ARM ([as suggested here](https://stackoverflow.com/a/54070358/16815703)). I hope that's ok.

art: enable osx-arm64 build

---

scripts/bioconductor/missingCranPackages.py

This script originally output missing CRAN packages, but I've added an option to output conda-forge packages stuck in migration. Also added an option to output a checklist in markdown format, which includes the first couple of pertinent lines from the bot output. (Inspired by https://github.com/bioconda/bioconda-recipes/issues/49778)
Example output from `python ./scripts/bioconductor/missingCranPackages.py --format markdown --migration_id r-base44_and_m2w64-ucrt`
```
```

feat: Prereqs for Bioconductor script

---

recipes/sorted_nearest/meta.yaml
scripts/check-for-additional-platforms.sh

The extra logging added in https://github.com/bioconda/bioconda-recipes/pull/50325 is great, but the CI was using the echoed output to determine if it should build without failing the job. Some broken osx-arm64 recipes (no build) got merged to master (found them on bulk). 
I want to find a better solution (see https://github.com/bioconda/bioconda-recipes/pull/50388), but for now, I think we need this script working again, so just reverting the problematic area.

ci: Fix platform script echo

---

.circleci/config.yml
.github/workflows/nightly.yml

We have a nightly build on Azure for linux-64 and osx-64. It's for picking up and rebuilding/uploading recipes that failed to upload when a PR is merged into master.
CircleCI for linux-aarch64 since that's the only CI option right now. This should be able to finish within the 1 hour limit as long as there are not too many catch-up builds needed.
GitHub Actions for osx-arm64 to avoid blocking any PR build/upload jobs and it has a longer timeout than CircleCI as a bonus. (I repurposed the existing nightly config file which has been disabled since switching to Azure.)

ci: nightly builds for linux-aarch64 and osx-arm64

---

recipes/fastahack/meta.yaml

While working on a different package, I noted that the bioconda fastahack package was slightly out of date and didn't have the (only) release version of upstream. As such, I've done the very minor patching required to bump to upstream's 1.0.0.
Something interesting I noted while doing this is that, while upstream is a very small executable, debian's package management defines a linked library that can be pulled into different projects, and which is apparently now used by freebayes. Since the library isn't actually defined in the upstream fastahack project itself, I'm dubious about reimplementing debian's work for a corresponding conda package. But I just thought I'd note this here in case someone stumbles across this in the future.
---- …

Update fastahack to 1.0.0 and modernize recipe style

---

recipes/auspice/meta.yaml

Changelog via [GitHub release page](https://github.com/nextstrain/auspice/releases/tag/v2.57.0)
---- …

Update auspice to 2.57.0

---

recipes/pytrimal/meta.yaml

Because of a CI issue, pytrimal recipe with osx-arm64 got into master without building successfully. It's failing its tests on the nightly build.
The tests don't pass. It's a little unusual to have full unit tests run for a recipe, but since they failed, I'm assuming there might be something wrong with the build itself. (Upstream docs mention they do not currently build for osx-arm64.)
---- …

pytrimal: remove osx-arm64 (failing tests)

---

recipes/vcflib/build.sh
recipes/vcflib/march_native.patch
recipes/vcflib/meta.yaml
recipes/vcflib/pkg-config.patch

My previous attempt to disable "march=native" by unsetting EXTRA_FLAGS from the command line failed.
I guess this is because variable set via the command line are defined before those in CMakeLists.txt.
https://github.com/bioconda/bioconda-recipes/pull/50531
This new recipe directy remove EXTRA_FLAGS  from the CMakeLists.txt
I have built this recipe and I have I checked that the "march=native" flag does not appear anymore.

Update vcflib 

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

Bump the patching to include #50665's new HTSlib release. As usual, this release does not change libhts's soversion.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just …

Bump bioconda-repodata-patches for new htslib release

---

README.md

I check the status of the various nightly builds every day or so to see if any manual intervention is needed. Instead, it would be nice if that status could be seen at a glance. 
Unfortunately, CircleCI's status badge doesn't differentiate between workflows on the same branch, so I used their Insights widget. [This post](https://support.circleci.com/hc/en-us/articles/28238747450907-Understanding-the-3-Different-Status-Badges-in-CircleCI-Builds) suggests there is a way to do it, but I was not able to successfully get a badge for the `Nightly (ARM)` workflow, even by URL-encoding the name.
**Example:**
> ## Nightly build status
> The nightly build any recipes that exist on master but were not successfully uploaded to the [bioconda channel](https://anaconda.org/bioconda). Any failure in the …

Include Nightly Build status in the readme

---

recipes/busco/meta.yaml

As of sepp 4.5.5, there is no longer a dependency on dendropy 4.5.2 (builds are currently up on [bioconda](https://anaconda.org/bioconda/sepp/files)) - so this max pin can be dropped, which will allow for greater compatibility of busco with other more modern packages.

UPDATE: remove old dendropy pin

---

recipes/eva-sub-cli/build.sh
recipes/eva-sub-cli/meta.yaml

Update eva-sub-cli to 0.4 and update build script. Supersedes #50762.
---- …

Update eva-sub-cli to 0.4

---

recipes/seq-hasher/build.sh
recipes/seq-hasher/meta.yaml

This PR adds [`seq-hasher`](https://github.com/apcamargo/seq-hasher), a tool for fast computation of hash digests for DNA sequences in FASTA files, with support for circular permutations.
---- …

Add `seq-hasher`

---

recipes/bwa-aln-interactive/meta.yaml

The executable associated with this version was missing a [commit](https://github.com/fulcrumgenomics/bwa-aln-interactive/pull/4). Instead of releasing a new version, I have opted to increment the build number.
----
* Please …

Update bwa-aln-interactive to correct executable

---

recipes/gfastats/build.sh
recipes/gfastats/meta.yaml

update gfastats to version 1.3.7
changed from using a tar.gz to the actually git repositories since the software contains a submodule that needs to be fetched.
---- …

feat: update to gfastats 1.3.7

---

recipes/pgrc/meta.yaml

update of pgrc version and recipe (added osx build)
---- …

updated revision and enabled osx build

---

recipes/cutadapt/meta.yaml

ping @marcelm 
This updates the dnaio dependency to 1.2.2 which fixes a bug in the uBAM reader. This will make a new biocontainer available without the bug.

Update dnaio dependency for cutadapt

---

recipes/get_mnv/meta.yaml

Add get_mnv, a tool designed to identify Multi-Nucleotide Variants (MNVs) within the same codon in genomic sequences. 
---- …

Add get_mnv

---

recipes/orthofinder/build.sh
recipes/orthofinder/meta.yaml

Update orthofinder for 3.0.1b1 beta release

---

recipes/pyliftover/meta.yaml

Update pyliftover to 0.4.1

---

recipes/pgscatalog.core/meta.yaml

Bump pgscatalog.core from `0.2.2` -> `0.3.1`
`0.3.x` added pydantic as a dependency, which broke autobump
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge …

Update pgscatalog.core to 0.3.1

---

recipes/pgscatalog.calc/meta.yaml

Autobump broke because pgscatalog.core needs a minor version bump
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Also, the bot watches for …

Update pgscatalog.calc to 0.3.0

---

recipes/r-cobrar/meta.yaml

r-cobrar: add aarch64/arm64 builds

---

recipes/vitap/meta.yaml

Update meta.yaml, VITAP v.1.7

---

recipes/breseq/build.sh
recipes/breseq/meta.yaml

Rebuild breseq

---

recipes/kmercamel/build.sh
recipes/kmercamel/meta.yaml

This adds the recipe for installing [KmerCamel](https://github.com/OndrejSladky/kmercamel) for computing masked superstrings for k-mer sets.
---- …

Add KmerCamel

---

.circleci/config.yml

Needed `large` for https://github.com/bioconda/bioconda-recipes/pull/51214
----
Conda …

Revert back to medium VM for Linux aarch64.

---

build-fail-blacklist
recipes/pepnovo/.gitattributes
recipes/pepnovo/0002-fix-float-positive-infinity.patch
recipes/pepnovo/build.sh
recipes/pepnovo/meta.yaml

pepnovo: add aarch64/arm64 build

---

recipes/gfastats/meta.yaml

This PR concerns with version update of gfastats tool from 1.3.7 to 1.3.8
---- …

Update gfastats tool version

---

recipes/pgscatalog.match/meta.yaml

* https://github.com/bioconda/bioconda-recipes/pull/51216 had inconsistent dependencies across `pyproject.toml` and `meta.yaml` but passed CI/CD checks
* Adding `pip check` to the tests section prevent this from happening again 
* Also the patch release fixed some broken tests
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built packages/containers. <br …

Update pgscatalog.match to 0.3.3

---

recipes/pggb/meta.yaml

To address https://github.com/pangenome/pggb/issues/415

`pggb`: update `vg` to v 1.59.0

---

recipes/hmftools-chord/LICENSE
recipes/hmftools-chord/build.sh
recipes/hmftools-chord/chord.sh
recipes/hmftools-chord/meta.yaml

Add recipe for hmftools-chord 2.1.0_beta
---- …

Add hmftools-chord 2.1.0_beta

---

recipes/pgscatalog-utils/meta.yaml

https://github.com/bioconda/bioconda-recipes/pull/51254 accidentally has some dodgy dependencies 👀 
Manual update to add `pip` check and bump minor versions
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please merge</code> command …

Fix pgscatalog-utils 1.4.1

---

recipes/patchify/meta.yaml

This is a relatively old package but still useful for our pipelines.
---- …

Add patchify

---

recipes/kmercamel/build.sh
recipes/kmercamel/meta.yaml

kmercamel: add aarch64/arm64 builds

---

recipes/harpy/meta.yaml

This adds `conda` as a bounded dependency and bumps the HTSlib versions to 1.21
Otherwise, everything else is the same
---- …

Update Harpy deps

---

recipes/kmc/build.sh
recipes/kmc/meta.yaml

kmc: add arm64 build

---

recipes/phyloacc/meta.yaml
recipes/phyloacc/run_test.sh

adding better tests to the build
---- …

Update PhyloAcc recipe

---

recipes/pantax/build.sh
recipes/pantax/meta.yaml

add pantax

---

recipes/vamos/meta.yaml

This updates vamos to v2.1.5. v2.1.4 had an error in the vcf output format.
---- …

Update to fix a vcf output error

---

recipes/samshee/meta.yaml

Add samshee recipe

---

recipes/earlgrey/build.sh
recipes/earlgrey/meta.yaml

Update Earl Grey build.sh

---

recipes/biobb_common/meta.yaml

[biobb_common] update 5.0.0

---

recipes/busco/build.sh
recipes/busco/meta.yaml

Update busco to v5.8.0

---

recipes/gmap/build.sh
recipes/gmap/meta.yaml

Update gmap to 2024-10-10

---

recipes/rna-seqc/build.sh
recipes/rna-seqc/meta.yaml

This PR updates RNA-seqc to its current version. It additionally installs the python scripts too.

Update rna-seqc to 2.4.2

---

recipes/fragpipe/build.sh
recipes/fragpipe/fragpipe
recipes/fragpipe/licenses/diann_LICENSE.txt
recipes/fragpipe/meta.yaml

It's been confirmed with both the FragPipe and DIA-NN authors that their license confers the ability to distribute the DIA-NN package along with the FragPipe download. 
---- …

Don't remove DIA-NN from FragPipe installation.

---

recipes/cosigt/build.sh
recipes/cosigt/meta.yaml

Cosigt computes the cosine similarity between pangenome-based coverage vectors that can be used to genotype read samples.

Add `cosigt`

---

sopa/meta.yaml

Adding the [sopa](https://github.com/gustaveroussy/sopa) package to bioconda
---- …

Add sopa package

---

recipes/gnparser/build.sh
recipes/gnparser/meta.yaml

gnparser: add aarch64/arm64 builds

---

recipes/gafpack/build.sh
recipes/gafpack/meta.yaml

[`gafpack`](https://github.com/pangenome/gafpack) is a tool to convert alignments to pangenome variation graphs to coverage maps (vectors). These vectors can be used together with [`odgi`](https://github.com/pangenome/odgi), [`pggb`](https://github.com/pangenome/pggb), and [`cosigt`](https://github.com/davidebolo1993/cosigt) to perform pangenome-based genotyping.

add gafpack

---

recipes/r-archr/build.sh
recipes/r-archr/meta.yaml
recipes/r-archr/patches/0001-cap-threads.patch

The [`ArchR` package](https://www.archrproject.com/index.html) is routinely used in the community without a canonical Conda version. This proposes to establish one in Bioconda. The recipe is mostly derived from https://github.com/bioconda/bioconda-recipes/pull/36855.
> 📢 *Initial discussion*
<details>
Unfortunately, there has been minor bug fixing in the `main` branch since the last Release. In lieu of this, I propose using a commit-specific build, with the number `"8"` corresponding to the *8th commit after the v1.0.2 release* (build 0).
However, it appears the `dev` branch has been solving more substantial issues, also without version releases. As an alternative to custom build strings, perhaps we should **consider customizing the version string**? For example, something like …

add `r-archr`

---

recipes/rmats/meta.yaml

Pin gsl to 2.5 for rmats

---

recipes/devider/build.sh
recipes/devider/devider-aarch64.patch
recipes/devider/meta.yaml

devider: add aarch64/arm64 builds

---

recipes/biobb_amber/meta.yaml

[biobb_amber] update 5.0.0

---

recipes/biobb_analysis/meta.yaml

[biobb_analysis] update 5.0.0

---

recipes/biobb_chemistry/meta.yaml

[biobb_chemistry] update 5.0.0

---

recipes/mess/meta.yaml

PR to update recipe:
* Bumped minimum python version (to match snakemake's minimal python version)  
* Added apptainer as dependency 
* Removed mamba dependency
* Bumped rich-click min version
---- …

Update mess recipe

---

recipes/assembly_finder/meta.yaml
recipes/mess/meta.yaml

PR to update recipe dependencies:
* Bumped minimal python, pyaml and rich-click versions
* Removed mamba from dependencies
---- …

Update assembly_finder recipe

---

.circleci/config.yml
recipes/cloudspades/build.sh
recipes/cloudspades/meta.yaml

cloudspades: add linux-aarch64 build

---

recipes/vcf-validator/build.sh
recipes/vcf-validator/meta.yaml

vcf-validator: add linux-aarch64 build

---

recipes/genbank/meta.yaml

genbank: add aarch64/arm64 builds

---

recipes/umicollapse/meta.yaml

Also changes the source GitHub repo to another fork because the original author is non-responsive.
Some discussion on this in https://github.com/nf-core/rnaseq/issues/1087#issuecomment-2392499060
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the …

Update UMICollapse to 1.1.0

---

recipes/annembed/build.sh
recipes/annembed/meta.yaml

With this new release, we add our own svd algorithm to get rid of ndarray-linalg and also new logo added
---- …

Update annembed to v0.1.5

---

recipes/el_gato/build.sh
recipes/el_gato/meta.yaml

Update el_gato to 1.20.0 
Replaces #51051. Hopefully fixed the build issues experienced in that PR.

Update el_gato version to 1.20.1

---

recipes/gene-trajectory-python/LICENSE
recipes/gene-trajectory-python/meta.yaml

Add the Python version of Gene-Trajectory (https://github.com/KlugerLab/GeneTrajectory-python) to bioconda. 
The method is described in detail in the article [Gene trajectory inference for single-cell data by optimal transport metrics](https://doi.org/10.1038/s41587-024-02186-3), Documentation and tutorials are available at https://genetrajectory-python.readthedocs.io/.
----
* PRs …

Add gene-trajectory-python recipe

---

recipes/fastplong/build.sh
recipes/fastplong/meta.yaml

fastplong is a tool for ultra-fast preprocessing and quality control for long-read sequencing data
---- …

Add fastplong

---

recipes/diamond/meta.yaml

Added support for extra platforms. Removed blast depedency as compilation with blast support was not working anyway.
---- …

Added support for extra platforms.

---

recipes/diamond/build.sh
recipes/diamond/meta.yaml

Update diamond recipe

---

recipes/pybbi/meta.yaml

pybbi: add linux-aarch64 build

---

recipes/centrifuge-core/build.sh
recipes/centrifuge-core/meta.yaml

centrifuge-core: add linux-aarch64 build

---

recipes/fmsi/0002-version.patch
recipes/fmsi/meta.yaml

Update fmsi recipe

---

recipes/irma/irma-check-dir-writable.patch
recipes/irma/irma-fix-bin-cmds.patch
recipes/irma/meta.yaml

Update irma recipe to version 1.1.4

---

recipes/strainy/meta.yaml

Please enter the commit message for your changes. Lines starting
---- …

version update

---

recipes/matchms/meta.yaml

Update `matchms` dependencies to match those in the [pyproject.toml](https://github.com/matchms/matchms/blob/4e1cbaf06cec8fce9282cae55155b0ad306b180b/pyproject.toml#L26) of the project
---- …

Update matchms dependencies

---

recipes/pyfastani/meta.yaml

This PR updates the build for `pyfastani` which has replaced `setuptools` with `scikit-build-core`.
Closes #51547.
---- …

Bump pyfastani to v0.6.0

---

recipes/pykofamsearch/meta.yaml

This PR adds [`pykofamsearch`](https://github.com/jolespin/pykofamsearch)
---- …

Add `pykofamsearch`

---

recipes/biobb_dna/meta.yaml

[biobb_dna] update 5.0.0

---

recipes/macsyfinder/meta.yaml

add setuptools for build
relax versions for pandas, hmmer dependencies

Update macsyfinder dependencies

---

recipes/genodsp/meta.yaml

genodsp: add linux-aarch64 build

---

recipes/steamboat/meta.yaml

Adds recipe for a python package with tools/scripts for microbial binf
---- …

add recipe for steamboat

---

recipes/pgscatalog-utils/meta.yaml

`pip check` was failing on the autobump
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …

Fix pgscatalog-utils patch update 1.4.2

---

recipes/snippy/meta.yaml

this is a workaround to make snippy work again.
samtools should be version <= 1.20, as Snippy fails to run with samtools v1.21, see https://github.com/tseemann/snippy/issues/598
---- …

Update Snippy: restrict samtools to version <=1.20

---

recipes/augustus/build.sh
recipes/augustus/meta.yaml
recipes/augustus/patches/0001-Makefile.patch
recipes/augustus/patches/utrrnaseq.patch

Rebuild Augustus recipe

---

recipes/ggcat/build.sh
recipes/ggcat/meta.yaml

Add the recipe for ggcat, a program to build and query compacted and optionally colored de Bruijn graphs.  
----
Conda …

Add ggcat 1.1.0 recipe

---

recipes/svtopovz/meta.yaml

This is a new python tool for visualization of complex genomic structural variants from HiFi sequencing data. Initial release.
---- …

Add svtopovz python package

---

recipes/meta.yaml

Add flexiformatter version 1.0.2
---- …

add flexiformatter version 1.0.2

---

recipes/bindash/build.sh
recipes/bindash/meta.yaml

Build bindash on osx

---

recipes/strainy/meta.yaml

strainy req update

---

recipes/lofreq/meta.yaml

#51417 introduced additional post-2.1.5 development changes to lofreq 2.1.5. These included a new dependency on bcftools, which was not a dependency of the package. Without this dependency the current build of lofreq is broken for all invocations of `lofreq call-parallel`.
---- …

Update lofreq to add bcftools dependency

---

recipes/poseidon-trident/meta.yaml

Update poseidon-trident to 1.5.7.0

---

.github/workflows/PR.yml
.github/workflows/master.yml
azure-pipeline-master.yml
azure-pipeline.yml

Due to the memory issues on Azure lately, use GitHub Actions for linux-64 and osx-64 builds. Existing PRs with Azure builds should be caught by the fallback option when merged to master. The nightly builds will remain on Azure for now.
- Disable Azure PR and master pipelines
- Update old GitHub Actions workflows to be more consistent with recent changes
- Remove old unused image download
- Disable osx-arm64 builds from GHA because there are only 5 concurrent osx runners alllow and arm is already working on CircleCI.

ci: Switch PR checks for linux-64 and osx-64 to GitHub Actions

---

recipes/libgff/build.sh
recipes/libgff/meta.yaml

Add libgff recipe

---

azure-pipeline.yml

Azure popped back into new PRs. I think `trigger: none` is not enough and it needs `pr: none`

ci: Update azure-pipeline.yml

---

recipes/pbaa/meta.yaml

Update pbaa version 1.1.0
---- …

Update pbaa version 1.1.0

---

recipes/ucsc-pslcdnafilter/build.sh
recipes/ucsc-pslcdnafilter/include.macos.patch
recipes/ucsc-pslcdnafilter/meta.yaml

Update ucsc-pslcdnafilter to 472

---

recipes/cell2cell/meta.yaml

This PR adds cell2cell package required by liana+
---- …

Add cell2cell

---

recipes/chopper/meta.yaml

This PR adds some changes to make this work on mac M3s, based on https://github.com/wdecoster/chopper/issues/40
---- …

Update chopper for M3s

---

recipes/prodigal-gv/meta.yaml

Due to CI transition, linux-64 and osx-64 didn't get uploaded. Bumping the build number so the nightly build stops trying to build it.
---- …

bump prodigal-gv build number

---

recipes/pbtk/meta.yaml

Update pbtk to version 3.4.0
---- …

Update pbtk to version 3.4.0

---

recipes/nf-core/meta.yaml

The bioconda version of nf-core tools produced errors when running commands that launched the trogon TUI. The reason was the missing package linkify,
which gets pulled in as a dependency of textual in the PyPi build, but not in the conda-forge recipe.
See https://github.com/Textualize/textual/blob/22770300252deb28d266fe4ed4766d6e2a2f5dd2/pyproject.toml#L44, https://github.com/conda-forge/textual-feedstock/blob/main/recipe/meta.yaml and https://github.com/nf-core/tools/issues/3257.
---- …

Update nf-core - Add missing linkify dependency

---

recipes/deepchopper-cli/build.sh
recipes/deepchopper-cli/meta.yaml

A CLI for Language models identify chimeric artificial reads in NanoPore direct-RNA sequencing data.
---- …

Add deepchopper-cli 

---

recipes/stxtyper/build.sh
recipes/stxtyper/meta.yaml

Add recipe for stxtyper v1.0.25

---

recipes/doubletdetection/meta.yaml

Add package doubletdetection

---

recipes/bioconductor-bambu/meta.yaml

Adds linux-aarch64 to the package.

Add Linux aarch64 to bioconductor-bambu

---

recipes/perl-list-moreutils-xs/meta.yaml

Add linux-aarch64 to additional-platforms.

Enable perl-list-moreutils-xs for linux-aarch64

---

recipes/seqscreen/meta.yaml

Updated versions to not be static, nf restrained to DSL1 versions

Update seqscreen meta.yaml 

---

recipes/hybpiper/meta.yaml

Adding setuptools to host requirements in meta.yaml as conda build is now failing without it (for bioconda build, as well as local builds of both macOS and Linux).
---- …

Update - add setuptools to host requirements as hybpiper conda build now failing without it

---

recipes/hmftools-orange/meta.yaml
recipes/hmftools-purple/meta.yaml

Update hmftools-purple and hmftools-orange

---

recipes/csvtk/meta.yaml

- [csvtk v0.31.0](https://github.com/shenwei356/csvtk/releases/tag/v0.31.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.31.0/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.31.0)
- `csvtk sort/join`:
- faster speed and lower memory.
- `csvtk sort`:
- do not panic for empty input. [#287](https://github.com/shenwei356/csvtk/issues/287)
- `csvtk summary`:
- fix the order of columns. [#282](https://github.com/shenwei356/csvtk/issues/282)
- `csvtk rename2`:
- fix `-n/--start-num`. [#286](https://github.com/shenwei356/csvtk/issues/286)
- add flag `--nr-width`.
- `csvtk replace`:
- fix implementing `{nr}`. [#286](https://github.com/shenwei356/csvtk/issues/286)
- `csvtk csv2json`:
- fix values with …

Update csvtk to v0.31.0

---

recipes/sentieon/meta.yaml

Add ARM support to Sentieon recipe.
---- …

Sentieon add ARM support

---

recipes/seqkit/meta.yaml

- [SeqKit v2.9.0](https://github.com/shenwei356/seqkit/releases/tag/v2.9.0) - 2024-11-01 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.9.0/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.9.0)
- `seqkit`:
- **Fix sequence ID parsing with the default regular expression (in this case, we actually use bytes.Index instead) for a rare case: "xxx\tyyy zzz" was wrongly parsed as "xxx\tyyy"**. [#486](https://github.com/shenwei356/seqkit/issues/486)
- `seqkit locate`:
- **Fix `-G/--non-greedy` for tandem repeats**, e.g., ATTCGATTCGATTCG (ATTCGx3).
- `seqkit grep/subseq`:
- Fix negative regions longer than sequence length. [#479](https://github.com/shenwei356/seqkit/issues/479).
- `seqkit stats`:
- Add …

Update SeqKit to v2.9.0

---

recipes/bioconductor-protgenerics/meta.yaml

This PR updates ProtGenerics to version 1.38.0 which is needed for qfeatures_1.16
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Also, the bot …

update ProtGenerics version to 1.38.0

---

ntstat/build.sh
ntstat/meta.yaml

Add ntStat

---

recipes/stranger/meta.yaml

The noarch version of the tool results in 
```
File "/home/felix/.local/bin/mambaforge/envs/stranger9.2/bin/stranger", line 6, in <module>
from stranger.__main__ import base_command
File "/home/felix/.local/bin/mambaforge/envs/stranger9.2/lib/python3.13/site-packages/stranger/__main__.py", line 14, in <module>
from stranger.cli import cli as base_command
File "/home/felix/.local/bin/mambaforge/envs/stranger9.2/lib/python3.13/site-packages/stranger/cli.py", line 11, in <module>
from stranger.resources import repeats_json_path
File "/home/felix/.local/bin/mambaforge/envs/stranger9.2/lib/python3.13/site-packages/stranger/resources/__init__.py", line 1, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
Not entirely …

Update stranger with setuptools and change dev url

---

recipes/perl-bloom-faster/meta.yaml
recipes/perl-class-methodmaker/meta.yaml
recipes/perl-crypt-openssl-random/0.11/meta.yaml
recipes/perl-crypt-openssl-rsa/meta.yaml
recipes/perl-file-copy-recursive/meta.yaml
recipes/perl-filesys-df/meta.yaml
recipes/perl-heap-simple-xs/meta.yaml
recipes/perl-ipc-sharelite/meta.yaml
recipes/perl-json-parse/meta.yaml
recipes/perl-math-cdf/meta.yaml
recipes/perl-math-random/meta.yaml

This breaks PR #51856 up to smaller pieces to get past build-timeout due to size of package list.
This adds osx-arm64 and linux-aarch64 where the packages would already work but for lack of meta.yaml or historic missing dependency in conda-forge.

Add linux-aarch64 and/or osx-arm64 to various perl-* packages 1 of 2

---

recipes/perl-unicode-map/meta.yaml
recipes/perl-unicode-normalize/meta.yaml
recipes/perl-unicode-utf8/meta.yaml

This pull request adds support for linux-aarch64 and/or osx-arm64 perl-unicode-* where these packages ought to already work.  This is a slice of previous PR request that is timing out due to size of package list.
@martin-g - can you review

Add linux-aarch64 and/or osx-arm64 variants to various perl-unicode-*

---

recipes/rotate/build.sh
recipes/rotate/meta.yaml

install_rotate_1.0

---

recipes/snapatac2/build.sh
recipes/snapatac2/meta.yaml
recipes/snapatac2/pyproject.toml.patch

Update snapatac2 to v2.7.1

---

recipes/rpsbproc/build.sh
recipes/rpsbproc/meta.yaml

Fix compile flags in build.sh to enable linux-aarch64. Add linux-aarch64 and osx-arm64 to additional platforms.

Add linux-aarch64 and osx-arm64 support to rpsbproc

---

recipes/table2asn/build.sh
recipes/table2asn/meta.yaml

Update table2asn to 1.28.1179

---

recipes/trtools/meta.yaml

Closes https://github.com/bioconda/bioconda-recipes/pull/51983
Update [trtools](https://bioconda.github.io/recipes/trtools/README.html): 6.0.2 → 6.1.0
Please merge this PR instead of https://github.com/bioconda/bioconda-recipes/pull/51983. We've updated a dependency, added a dependency, and added an entrypoint.

Update TRTools to 6.1.0

---

recipes/bam2plot/meta.yaml

Add bam2plot

---

recipes/biobb_chemistry/meta.yaml
recipes/polap/build.sh
recipes/polap/meta.yaml

Please, update to v0.3.7 build1. Thank you!

Update polap to v0.3.7 Build1

---

recipes/phabox/meta.yaml

- added new packages accelerate that maybe required on some system.
- fix some bugs in the phabox2 scripts.

Update PhaBOX to 2.1.5

---

recipes/lamps/meta.yaml

Add lamps v1.0.3

---

recipes/argo/meta.yaml

update argo to 0.1.2 and fix setuptool

---

recipes/r-seamless/meta.yaml

Update `r-seamless` to version 0.1.1
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` section like this: …

Update r-seamless to 0.1.1

---

recipes/cd-hit/build.sh
recipes/cd-hit/cd-hit.patch
recipes/cd-hit/meta.yaml

cd-hit: add osx-arm64 build

---

recipes/revbayes/build.sh
recipes/revbayes/meta.yaml

Update revbayes to v1.2.4

---

recipes/bayestyper/bayestyper.patch
recipes/bayestyper/meta.yaml

Rebuild bayestyper recipe

---

recipes/biobb_chemistry/meta.yaml

[biobb_chemistry] update 5.0.3

---

recipes/krakentools/meta.yaml

https://github.com/jenniferlu717/KrakenTools/blob/d4a2fbe2833c2392a724697c0c97a3014e748474/DiversityTools/alpha_diversity.py#L32
---- …

krakentools: alpha_diversity requires scipy

---

recipes/merqury/meta.yaml

Pinning `ggplot2` versions since, with newer versions, it gives error:
```
[...]
Error in `coord_cartesian()`:
! `xlim` must be a vector of length 2, not a number of length 1.
Backtrace:
▆
1. └─global spectra_cn_plot(...)
2.   └─global plot_line(dat, name, x_max, y_max, zero = dat_0, cutoff = dat_cut)
3.     └─ggplot2::coord_cartesian(xlim = c(0, x_max), ylim = c(0, y_max))
4.       └─ggplot2:::check_coord_limits(xlim)
5.         └─cli::cli_abort(...)
6.           └─rlang::abort(...)
Warning messages:
1: In max(dat[dat[, 1] != "read-total" & dat[, 1] != "read-only" &  :
no non-missing arguments to max; returning -Inf
2: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead. 
3: A numeric …
```

Pinning ggplot2 version

---

recipes/hmftools-redux/meta.yaml

Use openjdk <=21 for hmftools-redux

---

.circleci/config.yml
recipes/libmaus2/build.sh
recipes/libmaus2/meta.yaml
recipes/libmaus2/patch

Update libmaus2 to v2.0.183

---

recipes/muse/fix-install_muse.sh.patch
recipes/muse/meta.yaml
recipes/muse/version.patch

Rebuild muse recipe

---

recipes/biobambam/build.sh
recipes/biobambam/meta.yaml

Update biobambam to v2.0.185

---

recipes/agc/meta.yaml

Add osx-arm64 to agc

---

recipes/biobb_godmd/meta.yaml

[biobb_godmd] update 5.0.0

---

recipes/lsabgc/meta.yaml

Update lsabgc recipe/build to constrain dependency

---

recipes/ampcombi/meta.yaml
recipes/teloscope/meta.yaml

Update ampcombi to v.2.0.1

---

recipes/hmftools-chord/meta.yaml
recipes/hmftools-cuppa/build.sh
recipes/hmftools-cuppa/meta.yaml

Update hmftools CHORD and CUPPA

---

recipes/mzpaf/LICENSE
recipes/mzpaf/meta.yaml

This PR adds the recipe for the mzPAF pypi package, implementing the HUPO-PSI standard for the peak annotation format.
---- …

Add mzpaf as requirement for mzSpecLib

---

recipes/gempipe/meta.yaml

update gempipe to v1.37.3

---

recipes/clusty/build.sh
recipes/clusty/buildfixes.patch
recipes/clusty/meta.yaml

Update clusty to v1.1.4

---

recipes/meryl/0003-align.patch
recipes/meryl/build.sh
recipes/meryl/meryl-utility-aarch64.patch
recipes/meryl/meta.yaml

meryl: add linux-aarch64 and osx-arm64 build

---

recipes/phabox/meta.yaml

1. update the scripts used in phabox
2. try to fix the diamond version

Update PhaBOX to 2.1.6

---

recipes/hmftools-cuppa/meta.yaml
recipes/hmftools-esvee/meta.yaml
recipes/hmftools-isofox/meta.yaml
recipes/hmftools-lilac/meta.yaml

Enforce openjdk 21 for hmftools, part 2/4 (Cuppa, Esvee, Isofox, Lilac)

---

recipes/core-snp-filter/meta.yaml

* Adds linux-aarch64 and osx-arm64 platforms
* Removes unnecessary Python dependency
---- …

Update core-snp-filter: add aarch64/arm64 builds

---

recipes/biobb_pmx/meta.yaml

[biobb_pmx] update 5.0.0

---

recipes/pblat/meta.yaml
recipes/pblat/pblat-aarch64.patch

Building pblat for more platforms

---

recipes/psm-utils/meta.yaml

Adds `pyarrow` dependency to the psm_utils recipe.
Fixes an issue in the builds from #52286.
---- …

Update psm_utils recipe

---

recipes/absense/build.sh
recipes/absense/meta.yaml

Dear Admin,
i am adding recipe for absense to prevent issue with GenEra recipe
https://github.com/bioconda/bioconda-recipes/pull/51721
Best regards,
Anupam
---- …

adding recipe for absense to prevent issue with genera

---

recipes/hmftools-purple/meta.yaml
recipes/hmftools-sage/meta.yaml
recipes/hmftools-sigs/meta.yaml
recipes/hmftools-virus-interpreter/meta.yaml

Enforce openjdk 21, part 4/4 (Purple, Sage, Sigs, Virusinterpreter)

---

recipes/vgorient/meta.yaml

**Description:**
This pull request adds a new recipe for the `vgorient` package to the Bioconda channel.
**About `vgorient`:**
- **Homepage:** [https://github.com/whelixw/mitographs](https://github.com/whelixw/mitographs)
- **Description:** `vgorient` is a collection of scripts for analyzing and processing mitochondrial genome graphs using various bioinformatics tools. The package includes the following executable scripts:
- `jaccard_dit_wrapper.py`
- `VG_diterative.py`
- `kmer_jaccard.py`
- `cut_and_rot.py`
**Key Features:**
- Provides tools for processing mitochondrial graphs.
- Utilizes external tools like `vg` for graph operations.
- Facilitates comparative analysis of mitochondrial genomes.
**Recipe Details:**
- **Version:** 0.1.0
- **License:** MIT
- **Source:** Downloaded from the …

Add recipe for vgorient

---

recipes/polap/meta.yaml

Resolve a build issue; no change in the code; but a new build number because:
"The issue was the autobump bot's PR (that only updated the version, not your other changes) was merged right before your PR were merged (the approver probably didn't notice they were for the same package). So your changes got into master but there was an error uploading the new package because that version and build number already existed. To fix this, you can simply update the build number in meta.yaml and open a new PR. That will supersede the previous build that was made from the autobump bot (https://github.com/bioconda/bioconda-recipes/pull/52303)."

Update polap to v0.3.7.3 build1

---

recipes/gretl/meta.yaml

- Add build tests for plotting utils
- Fix for too old github revision in the initial build
---- …

Update gretl recipe

---

recipes/fastani/fix-reported-version.patch
recipes/fastani/meta.yaml

This is an attempt to fix fastANI issue #135: Sadly fastANI v1.34 reports its version at the command line as v1.33
---- …

Patch fastANI v1.34 source code to report correct version

---

recipes/perl-extutils-cppguess/meta.yaml
recipes/perl-set-intervaltree/meta.yaml

Adds linux-aarch64 to perl-extutils-cppguess and perl-set-intervaltree, and documents requirement for adding osx-arm64

Add linux-aarch64 to perl-extutils-cppguess and perl-set-intervaltree

---

recipes/meraculous/build.sh
recipes/meraculous/meraculous-aarch64.patch
recipes/meraculous/meta.yaml

meraculous: add linux-aarch64 build

---

recipes/hisat2/build.sh
recipes/hisat2/meta.yaml
recipes/hisat2/simde-mr-c.patch
recipes/strelka/meta.yaml

This PR adds support to hisat2 for linux-aarch64 and osx-arm64. The original patch is courtesy @mr-c - at https://github.com/DaehwanKimLab/hisat2/pull/251 .  
That patch has been waiting to be merged into the upstream of that project for some time, pragmatically this PR adds a patch to this bioconda recipe to incorporate this work.

hisat2: Add linux-aarch64 and osx-arm64 support

---

recipes/pyskani/meta.yaml

This PR adds a recipe for the `pyskani` Python package, which provide Python bindings to `skani`.
---- …

Add recipe for `pyskani` Python package

---

recipes/varifier/meta.yaml

This updates varifier to 0.4.0, using the release from github (the package in pypi is out of date).
----
Conda is able …

Update varifier to 0.4.0

---

.github/workflows/Bulk.yml
.github/workflows/CommentResponder.yml
.github/workflows/PR.yml
.github/workflows/build-failures.yml
.github/workflows/master.yml

ubuntu-latest soon will be re-linked to ubuntu-24.04 and this may lead to problems because it provides less pre-installed software
The upgrade to 24.04 should be done intentionally with another PR.
See
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#ubuntu-latest-upcoming-breaking-changes and https://github.com/actions/runner-images/issues/10636
---- …

Use `runs-on: ubuntu-22.04` instead of `ubuntu-latest`

---

recipes/subread/0001-macOS-Makefile.patch
recipes/subread/0002-longread-Makefile.patch
recipes/subread/0003-Linux-Makefile.patch
recipes/subread/0004-macOS-sse.patch
recipes/subread/build.sh
recipes/subread/meta.yaml

Update subread to v2.0.8 and enable arm64 build

---

recipes/abnumber/meta.yaml

Bump up abnumber to 0.4.2 https://github.com/prihoda/AbNumber/releases/tag/v0.4.2

Bump up abnumber to 0.4.2

---

recipes/deepfplearn/meta.yaml

there is no tensorflow-gpu 2.9 and therefor we can not create a conda env using GPU acceleration
---- …

deepfplearn: bump keras

---

recipes/alevin-fry/meta.yaml

This PR changes 'osx-arm' to 'osx-arm64' in additional targets so as to build for the proper OSX arm target.

Change osx-arm to osx-arm64 in additional targets

---

recipes/ectyper/meta.yaml
recipes/ectyper/post-link.sh

Initial build 0 for ectyper v2.0.0 had obsolete database `post-link.sh` script that requires update with integrated utility `ectyper_init`. This will ensure that resulting recipe will be complete and images will be complete with all databases initialized. This is a very small but important script

ECTyper v2.0.0 build #1 now with fixed automatic database init

---

recipes/novae/meta.yaml

Adding [`novae`](https://github.com/MICS-Lab/novae) recipe. I used grayskull to generate the recipe, but had to update the name for `torch_geometric`.
---- …

Add novae package

---

recipes/pymethylation_utils/meta.yaml

A python wrapper for [methylation_utils](https://github.com/SebastianDall/methylation_utils), which processes a methylation pileup file created with [modkit](https://github.com/nanoporetech/modkit). It finds the contig methylation pattern of predefined motifs. This package is a dependency of a new release in [Nanomotif](https://github.com/MicrobialDarkMatter/nanomotif), which is able to find motifs in metagenomic samples. Nanomotif is also on bioconda.
----
* New recipes not directly relevant to the biological sciences need to be submitted to …

add recipe for pymethylation_utils pypi package

---

recipes/gtdbtk/meta.yaml

fastani was incorrectly set to = 1.32, which is causing issues building now that fastani recipes only builds 1.34.  The docs (per #36934) say > 1.32
---- …

gtdbtk: use fastani >= 1.32, as per #36934

---

recipes/bioconda-repodata-patches/gen_patch_json.py
recipes/bioconda-repodata-patches/meta.yaml

Bump the patching to account for conda-forge/libdeflate-feedstock#29, which does not change the library's soversion.
Bumping by two because we missed the 1.22 release in October.
---- …

Bump bioconda-repodata-patches for new libdeflate release

---

recipes/gtdbtk/meta.yaml
recipes/lodei/meta.yaml

Adding LoDEI - the local differential editing index - to bioconda. LoDEI offers a collection of programs to detect and analyze differentially edited A-to-I regions in two sets of RNA-seq samples.
---- …

Add lodei recipe

---

recipes/phasius/build.sh
recipes/phasius/meta.yaml

phasius: Update to 0.2.0 and add linux-aarch64 build

---

build-fail-blacklist
recipes/ghostx/build.sh
recipes/ghostx/ghostx-makefile.patch
recipes/ghostx/meta.yaml

ghostx: add aarch64/arm64 builds

---

recipes/suchtree/meta.yaml

Add a recipe for SuchTree 1.2.
SuchTree is a Python library built with Cython for fast, thread-safe computations with phylogenetic trees. It is particularly suitable for MCMC sampling of distances and relationships within very large trees (up to millions of taxa). 
- PiPy : https://pypi.org/project/SuchTree/
- Development : https://github.com/ryneches/SuchTree/
- Issues : https://github.com/ryneches/SuchTree/issues
- Documentation : https://github.com/ryneches/SuchTree/blob/master/README.md
- Publication : https://joss.theoj.org/papers/10.21105/joss.00678

Add recipe for SuchTree

---

recipes/pdb2fasta/build.sh
recipes/pdb2fasta/meta.yaml
recipes/pdb2fasta/pdb2fasta.patch

This PR adds [`pdb2fasta`](https://github.com/kad-ecoli/pdb2fasta).
---- …

Add `pdb2fasta`

---

recipes/nanopack/meta.yaml

A meta package for several other recipes by the same author
---- …

Add a recipe for nanopack.

---

recipes/ngscheckmate/meta.yaml

ngscheckmate is a noarch-generic package - and yet on linux-aarch64, a freshly installed conda environment and in rocky9 linux:
```
Could not solve for environment specs
The following packages are incompatible
├─ ngscheckmate is installable with the potential options
│  ├─ ngscheckmate 1.0.0 would require
│  │  └─ python 2.7.18.* , which does not exist (perhaps a missing channel);
│  ├─ ngscheckmate 1.0.0 would require
│  │  └─ bcftools 1.3.1.* , which does not exist (perhaps a missing channel);
│  └─ ngscheckmate 1.0.1 would require
│     └─ python [2.* |2.7.* ] with the potential options
│        ├─ python 2.7.15, which can be installed;
│        └─ python 2.7.15 would require
│           └─ openssl >=1.0.2p,<1.0.3a , which does not exist (perhaps a missing channel);
└─ pin-1 is not …
```

ngscheckmate: bump the build - attempt to get aarch64 installing

---

recipes/hicberg/meta.yaml

This PR add ```hicberg```(Hi-C reconstruction of genomic signals from repeated elements) to bioconda.
Hicberg is a genomic data (contact data) reconstruction tool based on statistical profiling of data for the inference of missing fraction of the genomic data related to repeated elements in genomes, implemented in python.
---- …

Add hicberg v1.0.0

---

recipes/mumemto/build.sh
recipes/mumemto/meta.yaml

Add Mumemto v1.1.0 recipe to bioconda
---- …

Add mumemto recipe

---

recipes/kyber/build.sh
recipes/kyber/meta.yaml

Add a recipe for kyber

---

recipes/immuneml/meta.yaml

This PR updates the `immuneML` recipe to include `pytorch=2.*=cpu_*` as a dependency, ensuring compatibility for systems without GPU support.

Add PyTorch 2.x (CPU-only) dependency for immuneML

---

recipes/bioconductor-genetonic/build_failure.linux-64.yaml
recipes/bioconductor-genetonic/build_failure.osx-64.yaml
recipes/bioconductor-genetonic/meta.yaml
recipes/bioconductor-pcaexplorer/build_failure.linux-64.yaml
recipes/bioconductor-pcaexplorer/build_failure.osx-64.yaml
recipes/bioconductor-pcaexplorer/meta.yaml

bioconductor-mosdef was built, so these can build now.

build bioconductor-genetonic and bioconductor-pcaexplorer

---

recipes/r-scroshi/build.sh
recipes/r-scroshi/meta.yaml

Trying to add scROSHI package to bioconda

recipe for scROSHI package based on CRAN repo

---

recipes/star/build.sh
recipes/star/meta.yaml

Closes https://github.com/bioconda/bioconda-recipes/issues/53018 
---- …

Add openmp support to star

---

recipes/pyhmmer/meta.yaml

Supersedes #53164, the build-system was changed from `setuptools` to CMake and `scikit-build-core` so the dependencies have to be updated.
---- …

Update `pyhmmer` to `v0.11.0`

---

recipes/itsxpress/meta.yaml

This bumps the build version after setting the hmmer dependency to be >= '3.1bxx' because for QIIME2 installs hmmer v3.4 is dependency on newer tools and there is a conflict having old version of hmmer 3.1 dependency.
https://forum.qiime2.org/t/itsxpress-2-0-in-qiime2023-2-with-emp-data/26976/5
https://forum.qiime2.org/t/need-help-plugin-error-from-itsxpress/32046/8
@arivers I think can indicate if this would be a problem but this allows itsxpress and  q2-fragment-insertion to co-exist in same conda env if hmmer3.4 is allowed to be used.

Update to relax the hmmer build version supported to allow newer version

---

recipes/ngscheckmate/build.sh
recipes/ngscheckmate/meta.yaml
recipes/ngscheckmate/py3.patch

* change python2 to python3 - largely tabulation and print syntax
* the ngscheckmate_fastq binary is now built by the build script; the source has been updated to be more modern C, and the installation no longer uses the linux-x86_64-only binary that was in this package.
* this package no longer marked as architecture generic.

ngscheckmate - migrate to python3 and enable linux-aarch64 and osx-arm64 

---

recipes/ngmlr/mapq.patch
recipes/ngmlr/meta.yaml

Add a patch that applies a version of PR philres/ngmlr#96. This bug has been known for ~18 months and prevents use with samtools >= 1.10, which rejects negative values for MAPQ (which are invalid in SAM). The upstream patch has been available for a couple of months and has been applied in e.g. Debian's packaging but not yet by the upstream project.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td><code>@BiocondaBot please fetch …

Patch ngmlr to avoid producing an invalid MAPQ value

---

recipes/muscle/3.8.1551/build.sh
recipes/muscle/3.8.1551/meta.yaml
recipes/muscle/3.8.1551/osx-makefile.patch

Pasta has a hard requirement for muscle < 4 due to a change of command arguments in muscle 5.  
Muscle 4 was removed from bioconda in 2022 and replaced by muscle 5.  Pasta can't build for linux-aarch64 until this is resolved.
This PR re-enabled the last working version of the 3.8 series by adding a subdirectory with this revision in as per other packages that do this kind of legacy support (first time I've added one, I hope this is the right idea)
This PR also adds linux-aarch64

Muscle - add legacy version - required by pasta

---

recipes/muscle/3.8.1551/meta.yaml
recipes/pasta/meta.yaml

adds linux-aarch64, osx-arm64.
---- …

pasta: add linux-aarch64; muscle/3.8 enable osx-arm64

---

recipes/htstream/build.sh
recipes/htstream/meta.yaml

Update to version 1.4.0, should fix build for mac.

Update meta.yaml for htstream 1.4.0 release

---

recipes/arborator/meta.yaml

We have updated one of the dependencies of the `arborator` package, `genomics_address_service`, to [version 0.1.3](https://github.com/phac-nml/genomic_address_service/releases/tag/0.1.3) to fix a bug. While `arborator` will work with older versions of `genomic_address_service`, I would like the container on biocontainers to be updated to include the most recent version of `genomic_address_service`. This PR updates the build number in order to trigger a re-build of the container.
---- …

Update build number of arborator

---

recipes/easypqp/meta.yaml

Attempt to fix the following error when running the quay.io container of this package
> Command error:
Unable to find image 'quay.io/biocontainers/easypqp:0.1.50--pyhdfd78af_0' locally
0.1.50--pyhdfd78af_0: Pulling from biocontainers/easypqp
36b7914fc8ba: Already exists
2cc3d3b08aaa: Already exists
bd9ddc54bea9: Already exists
1bb084e8d0f9: Pulling fs layer
1bb084e8d0f9: Verifying Checksum
1bb084e8d0f9: Download complete
1bb084e8d0f9: Pull complete
Digest: sha256:82ec6181308514b01ce4618fd410732de501d1620738007944a7c119b409bdfa
Status: Downloaded newer image for quay.io/biocontainers/easypqp:0.1.50--pyhdfd78af_0
Matplotlib created a temporary cache directory at /tmp/matplotlib-1ck8ubs9 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to …

easypqp: export matplotlib and xdc cache dir

---

recipes/centrifuger/build.sh
recipes/centrifuger/meta.yaml

Add centrifuger-quant to the executable folder
---- …

Add centrifuger-quant to Centrifuger

---

recipes/igv/meta.yaml

Update IGV from 2.17.4 to 2.19.1. Requires Java >= 21 per the [release notes](https://igv.org/doc/desktop/#ReleaseNotes/2.19.x/)
---- …

Update IGV to version 2.19.1

---

recipes/foldseek/build.sh
recipes/foldseek/meta.yaml
recipes/foldseek/prostt5-memory.patch

I jumped the gun a bit yesterday. This should solve issues with the release yesterday
---- …

Fix macOS Metal in Foldseek release 10

---

recipes/sra-tools/build.sh
recipes/sra-tools/conda_build_config.yaml
recipes/sra-tools/meta.yaml

`ncbi-vdb` is already available in `linux-aarch64` and `osx-arm64`, try to build `sra-tools` too
Closes #53254.
---- …

sra-tools: build for linux-aarch64

---

recipes/ectyper/meta.yaml

This is build #2 where bioconda v1.85 recent update resulted in errors reading FASTA files. This incompatibility was addressed in this build thanks to making source code compatible with both previous and recent biopython versions. 
This addresses issue #99 at https://github.com/phac-nml/ecoli_serotyping/issues/99

ECTYPER v2.0.0 build #2 addressing the bioconda 1.85 incompatibility

---

recipes/nafcodec/meta.yaml

This PR adds [`nafcodec`](https://github.com/althonos/nafcodec/tree/main/nafcodec-py).
---- …

Add `nafcodec`

---

recipes/genomad/meta.yaml

This PR fixes the dependencies of geNomad 1.9.0.
---- …

Fix geNomad 1.9.0 dependencies

---

recipes/frag_gene_scan_rs/meta.yaml

Add a recipe for FragGeneScanRs, a tool predict genes in short reads.
----

Add recipe for FragGeneScanRs

---

recipes/manta/meta.yaml

Manta boost fix: add boost-cpp dependency at runtime.

---

recipes/ncbi-amrfinderplus/build.sh
recipes/ncbi-amrfinderplus/meta.yaml

This is just a minor update to the NCBI AMRFinderPlus software latest version. For some reason autobump didn't pick it up.

Update to AMRFinderPlus 4.0.15

---

recipes/dendropy/meta.yaml

Update dendropy to 5.0.2

---

recipes/bioconductor-biocgenerics/meta.yaml
recipes/bioconductor-copynumber/build.sh
recipes/bioconductor-copynumber/meta.yaml
recipes/bioconductor-genomeinfodb/meta.yaml
recipes/bioconductor-genomicranges/meta.yaml
recipes/bioconductor-iranges/meta.yaml
recipes/bioconductor-s4vectors/meta.yaml
recipes/bioconductor-ucsc.utils/meta.yaml
recipes/bioconductor-xvector/meta.yaml
recipes/bioconductor-zlibbioc/meta.yaml

bioconductor-copynumber has been removed from bioconductor since 3.18 due to lack of maintainers, and subsequently removed from bioconda but is still used by some packages: hmftools-amber/cobalt (still used by some nf-core pipelines), r-eacon, and a couple of bioconductor packages.
The legacy builds enable x86 to continue to function, but that leaves no workable path for aarch64 as the legacy binaries cannot be made due to lack of support in legacy versions of some current tools.
This PR restores bioconductor-copynumber and lets it build against more recent bioconductor/r-base. If removed in a subsequent PR, at least the binaries will continue to exist for aarch64 and x86.
A number of  bioconductor packages needed a build bump (including some 'generic' noarch) - which are in this PR too. …

bioconductor-copynumber restore to enable aarch64 supporting package

---

recipes/maxbin2/meta.yaml

- Replace perl-lwp-simple with perl-libwww-perl.
- perl-lwp-simple is blacklisted and only installs perl-libwww-perl these days, so let's cut out and go direct to perl-libwww-perl.
- perl-libwww-perl itself is in conda-forge - but required missing perl-mime-base64 for linux-aarch64 (https://github.com/conda-forge/perl-mime-base64-feedstock/pull/2).  Once that's merged and built, this PR should be retested.

maxbin2: start enabling linux-aarch64

---

recipes/r-ukbrapr/meta.yaml

v0.3.0 removed some deprecated dependencies. Updating recipe to reflect this.

Update r-ukbrapr - remove deprecated dependencies

---

recipes/a3partitioner/meta.yaml

Add a3partitioner v0.1.0

---

recipes/hatchet/meta.yaml

We have made minor update to support recent updates on third-party dependencies. This PR updates the version number to v2.1.1 and hash checksum in YAML file. Thank you.

Update HATCHet to v2.1.1

---

recipes/transannot/build.sh
recipes/transannot/meta.yaml

UPDATE troubleshoot transannot build

---

recipes/excludonfinder/meta.yaml

- Update to version 0.1.4
- Fix script paths handling
- Add support for both -h and --help flags
- Remove run_exports section

Update excludonfinder to 0.1.4

---

recipes/ncbi-amrfinderplus/meta.yaml

Manually update ncbi-amrfinderplus for AMRFinderPlus 4.0.19. For some reason autobump doesn't seem to be picking up new releases.

Update ncbi-amrfinderplus to version 4.0.19

---

recipes/star/2.7.3a/build.sh
recipes/star/2.7.3a/meta.yaml
recipes/star/2.7.3a/patches/0004-comptimeplace.patch

Adds support for this specific STAR version since it's needed for an ongoing effort to port `oncoanalyser` pipeline to `linux-aarch64`.
This specific version is needed since latest versions generate runtime issues, as reported by Hartwig.
/cc @scwatts

Add Star 2.7.3a

---

recipes/t-coffee/build.sh
recipes/t-coffee/coredump.patch
recipes/t-coffee/meta.yaml
recipes/t-coffee/t_coffee.sh

Reverts bioconda/bioconda-recipes#53845
This is a revert of a revert. 
We removed the changes introduced because it seeminlgy broke some downstream applications. 
We figured the issue was not the addition of the arm64 support but a change in some dependencies version (tmalign in concrete) which was then not compatible with t-coffee. 
Now all versions are explicitly provided.

t-coffee: add versions of dependencies and revert the removal of arm64 support

---

mutalyzer_hgvs_parser/meta.yaml
recipes/mutalyzer_hgvs_parser/meta.yaml

New recipe for mutalyzer_hgvs_parser, a python library and command line tool to parse HGVS descriptions (a nomenclature to describe genetic variants).
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built …

Add recipe for mutalyzer_hgvs_parser

---

recipes/perl-template-toolkit/meta.yaml
scripts/check-for-additional-platforms.sh

Several dependencies are missing:
```
Attempting to finalize metadata for perl-template-toolkit
2025-02-19T00:25:09.6612660Z Reloading output folder: ...working... done
2025-02-19T00:25:09.7988480Z Getting pinned dependencies: ...working... done
2025-02-19T00:25:16.3462490Z Reloading output folder: ...working... done
2025-02-19T00:25:16.4355420Z Getting pinned dependencies: ...working... failed
2025-02-19T00:25:16.4406050Z WARNING: failed to get package records, retrying.  exception was: Unsatisfiable dependencies for platform osx-arm64: {MatchSpec("perl-test-leaktrace"), MatchSpec("perl-xml-libxml"), MatchSpec("perl-image-info==1.38=pl5321hdfd78af_2")}
2025-02-19T00:25:16.4408180Z Encountered problems while solving:
2025-02-19T00:25:16.4408860Z   - nothing provides requested …
```

perl-template-toolkit: Do not build for osx-arm64

---

recipes/grz-cli/meta.yaml

Update grz-cli to 0.1.4 manually.
Also change source url path from pypi.org to pypi.io such that the autobumper can correctly pick up on changes.

Update grz-cli to 0.1.4

---

.github/workflows/PR.yml
.github/workflows/build-failures.yml
.github/workflows/master.yml
.github/workflows/nightly.yml

Attempts to speed up GHA via shallower checkouts: https://github.com/bioconda/bioconda-recipes/issues/53383.  Reduces checkout time from minutes to tens of seconds
---- …

ci: optimize fetch-depth in github actions

---

.github/workflows/master.yml

Originally introduced in #53384, discussed here: https://github.com/bioconda/bioconda-recipes/pull/53384#issuecomment-2678736676
---- …

fix: revert git fetch depth in master build

---

recipes/pretextgraph/meta.yaml

- fixed the gradually dropping to 0 problem
- added noise_filter for `coverage` and `repeat_density`
- update the extension types

Update PretextGraph to 0.0.8

---

recipes/trinity/cflags-remove-m64.patch
recipes/trinity/meta.yaml

- also removes -m64 flag from x86 configs, this has been default for many many years.

Trinity: add linux-aarch64 support

---

recipes/lsabgc/meta.yaml

Updating recipe for lsaBGC to ensure pyhmmer v0.10.15 is used (a dependency of zol) because zol v1.4.12 - which lsaBGC is currently designed to use is incapable of using the current pyhmmer v0.11.
More recent version of zol will address this issue and I will eventually update lsaBGC to use newer versions of zol and take away this requirement for the pyhmmer version.
----
* PRs …

Update lsabgc build 

---

.github/workflows/PR.yml
.github/workflows/build-failures.yml

ci: fix base ref in GHA workflow

---

recipes/mob_suite/meta.yaml

The ete3 library uses sqlite to query taxonomy database. Recent `libsqlite v3.49.0` library causes error when forming and sql query. This build fixes the upper bound of the `blast` to version < 2.16 and `libsqlite <3.49` to avoid the following error.
```
File "/galaxy/database/dependencies/_conda/envs/__mob_suite@3.1.9/lib/python3.11/site-packages/mob_suite/utils.py", line 167, in getTaxonConvergence
ranks = ncbi.get_rank(lineage)
^^^^^^^^^^^^^^^^^^^^^^
File "/galaxy/database/dependencies/_conda/envs/__mob_suite@3.1.9/lib/python3.11/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 201, in get_rank
result = self.db.execute(cmd)
^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: "211968" - should this be a string literal in single-quotes? …
```

mob_suite v3.1.9 build #1 fixing the sqlite error linked to double and single quote use by ete3 library

---

recipes/ivar/build.sh
recipes/ivar/meta.yaml

* Bumped iVar to v1.4.4.
* Added `osx-arm64` to additional platforms

Update ivar version to 1.4.4 and added osx-arm64 to additional platforms

---

recipes/hmftools-esvee/meta.yaml

Tested successfully with AWS Corretto Java SDK 23 on an ARM64 instance.
No need for:
```yaml
extra:
additional-platforms:
- linux-aarch64
```
Since this is a `noarch` target (Java).

Update hmftools-esvee recipe: Bump sambamba version and openjdk version range(s)

---

recipes/kgwasflow/meta.yaml

When using the bio container of kgwasflow we noticed that there was an incorrect version of ln. Therefore, I added coreutils to the dependencies of kgwasflow. While updating the recipe we found out that setuptools was missing, as well. 
@akcorut Do you see any big issues with this?

Add setuptools and core utils to dependencies of kgwasflow

---

.github/workflows/PR.yml
recipes/bioconductor-lpsymphony/build_failure.osx-64.yaml

Updating the hash so this gets skipped in the osx-64 nightly build. I also pasted in the pertinent part of the log since there was not much useful information in what was automatically included.
(This PR was demonstrating some issues so I aded some logging to the workflow, but now it's working so that's been reverted.)

update build failure for bioconductor-lpsymphony

---

recipes/bwa-mem2/build.sh
recipes/bwa-mem2/meta.yaml

fix erroneous use of 'native ' as build flags to bwa-mem2
resolves: https://github.com/simd-everywhere/simde/issues/1286
- enables working on earlier non-SVE aarch64 platforms
----
* Please post …

bwa-mem2: fix build for aarch64 to pin to not use SVE

---

recipes/frogs/meta.yaml

Bugs fixed
- Issue: unable to use denoising.py with swarm and --denoising option with --distance > 1
- splitbc.pl: fix R2 truncation
- denoising.py: Allow vsearch to deal with AVITI reads (higher max quality value allowed)

Update FROGS to v5.0.1

---

recipes/pfam_scan/build.sh
recipes/pfam_scan/meta.yaml

Wrapper script for `pfam_scan.pl` currently overwrites `PERL5LIB` path. On OSX this causes error locating the IPC run.pm dependency.
This PR appends the existing `PERL5LIB` path at time of execution to fix this issue. No effect on other platforms.

Update: Preserve existing PERL5LIB path on run

---

recipes/ensembl-vep/build.sh
recipes/ensembl-vep/meta.yaml

this adds the missing dependency perl-list-moreutils 
it also removes the insecure curl requests.
note: with my strict conda channel priority perl>=5.27.0 had to be specified for this to build
context:
since bioconda::ensembl-vep>=112.0 the vep command errors out because of missing List/MoreUtils.pm 
see https://github.com/bioconda/bioconda-recipes/issues/54304#issue-2895018904

fix ensembl-vep missing dependency "perl-list-moreutils"

---

recipes/pysamstats/meta.yaml

Build-bump pysamstat so it is built against the latest pysam 0.23
(pysam 0.23's newer functionality doesn't affect pysamstat. I know it: [I wrote that function](https://github.com/pysam-developers/pysam/pull/1294))
----
* Please …

Update (~ish kind-of: buildbump) pysamstat

---

recipes/r-pathosurveilr/meta.yaml

This needed to be renamed because there was already a package on CRAN called `psminer` that we did not know about.

Update r-psminer and rename to r-pathosurveilr

---

recipes/autobigs-cli/meta.yaml

As title states. Upgrading autobigs-cli to 0.6.3. Fixes a bug in CSV output for listing databases.
----
Conda is able …

update autobigs-cli bioconda recipe to PYPI autobigs-cli 0.6.3.

---

recipes/pysamstats/meta.yaml

The `pysamstats` package is not currently available for `osx-arm64`, which prevents the installation of `smallgenomeutilities>=0.5.0` on Apple Silicon Macs. This PR adds `osx-arm64` to the `additional-platforms` section in the `meta.yaml` file to enable ARM support.
- Added `osx-arm64` to `build.additional-platforms` in `recipes/pysamstats/meta.yaml`.
- This change should resolve issues for users on `osx-arm64` who need `pysamstats` for downstream dependencies.
Related issues: 
- https://github.com/alimanfoo/pysamstats/issues/173
Please review and let me know if additional changes are needed.
----
* If this PR adds or updates a recipe, use "Add" or …

Update: Add osx-arm64 support for pysamstats

---

.github/workflows/PR.yml

This takes the snipped of code from [`build-failures`](https://github.com/nh13/bioconda-recipes/blob/795299ebe05d970ca70711db525ff10ebca427c9/.github/workflows/build-failures.yml#L36-L52) and adds it to the [PR GHA workflow](https://github.com/nh13/bioconda-recipes/blob/795299ebe05d970ca70711db525ff10ebca427c9/.github/workflows/PR.yml).
This reduces the bioconda-utils setup time from ~1-2 minutes to 10-15 seconds (on linux) 😄  .
To test this workflow, I've re-run the checks a second time to show that the cache works.
----
* New recipes not …

ci: adding caching of bioconda-utils install in PR workflow

---

recipes/ectyper/meta.yaml

Users identified small issues including
- higher number of mixed O-antigen calls
- [issue 101](https://github.com/phac-nml/ecoli_serotyping/issues/101) with the inconsistent number of output columns depending on `--pathotype` parameter specified or not

updated ectyper_v2.0.0 build #3 recipe to fix minor bugs in serotyping

---

recipes/mgnify-pipelines-toolkit/meta.yaml

This PR upgrades the mgnify pipelines toolkit to version 1.0.1 (a bugfix release)

Update mgnify pipelines toolkit to version 1.0.1

---

recipes/autobigs-engine/meta.yaml

Updated autobigs-engine to 0.14.2. Increased query timeout. CSV writing now supports pre-determined headers which fixes an issue with queries that result in missing targets causing the export process to fail.
----
* Please post …

update autobigs-engine bioconda recipe to 0.14.2.

---

recipes/snakemake-interface-storage-plugins/meta.yaml

Reverts bioconda/bioconda-recipes#54666
The release should be a major version bump instead. Hence retracting this.

Revert "Update snakemake-interface-storage-plugins to 3.6.0"

---

recipes/autobigs-cli/meta.yaml

Allows autobigs-cli to make use of autobigs-engine 0.14.*. This results in less timeout errors, and fixes issues caused by a query not returning all defined targets for a scheme.
---- …

update autobigs-cli bioconda recipe to 0.6.5.

---

build-fail-blacklist
recipes/maker/meta.yaml

hoping to solve (with strict channel priority)
```
Could not solve for environment specs
The following package could not be installed
└─ maker 3.01.03**  is not installable because it requires
├─ perl >=5.26.2,<5.26.3.0a0 , which can be installed;
└─ perl-bit-vector but there are no viable options
├─ perl-bit-vector 7.4 would require
│  └─ perl >=5.32.1,<5.33.0a0 *_perl5, which conflicts with any installable versions previously reported;
└─ perl-bit-vector 7.4 conflicts with any installable versions previously reported.
```
or the following wo channel priority
```
Could not solve for environment specs
The following package could not be installed
└─ maker 3.01.03**  is not installable because it requires
├─ perl >=5.26.2,<5.26.3.0a0 , which can be installed;
└─ perl-bioperl-core >=1.007002 …
```

bump maker

---

recipes/bioconductor-scater/meta.yaml

I'm hoping that building the latest bioconductor-scater 1.34.1 will help resolve the conda solver issues I am observing in my PR to fix the bioconductor-singlecelltk build.
xref: https://github.com/bioconda/bioconda-recipes/pull/54729

Update bioconductor-scater 1.34.1

---

recipes/semibin/meta.yaml

Update SemiBin to version 2.2.0
In addition to updating version & hash, MMSeqs2 is no longer required and the `SemiBin` entry_point is no longer installed (only `SemiBin1` or `SemiBin2`)
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the …

Update SemiBin to 2.2.0

---

recipes/cctyper/activate.sh
recipes/cctyper/build.sh
recipes/cctyper/deactivate.sh
recipes/cctyper/meta.yaml
recipes/cctyper/post-link.sh
recipes/cctyper/pre-unlink.sh

This is an update of the cctyper recipe. The tool is still exactly the same (so no version number change) but the build number was increased as the recipe was changed.
The recipe was changed to now automatically install the CCTyper database upon build, rather than having the user need to install the database separately.

Update cctyper - new build to automatically install database

---

recipes/rtg-tools/0001-feat-support-arm64.patch
recipes/rtg-tools/build.sh
recipes/rtg-tools/meta.yaml

`rtg-tools` is not installing locally on either intel or arm64 osx.  See if a new build will help.
----
Conda is able …

Fix rtg-tools java installation path

---

recipes/grz-pydantic-models/meta.yaml

This PR adds `grz-pydantic-models`, a dependency of `grz-cli`.

Add grz-pydantic-models recipe

---

recipes/snakemake/meta.yaml

Previous dependency constraints prevented installation of snakemake-interface-storage-plugins to version 4
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please merge</code> command is now depreciated. Please just squash and merge …

Update: realign dependency of snakemake package to snakemake pyproject

---

recipes/snippy/meta.yaml

* vt used year numbers for versioning (2015.11.10) before changing to version 0.5. These are still available in the linux-64 subdir. And 2015 is greater than 0.5 so the newer versions never get used. The latest 2015.11.10 build has a bug that causes zero variants to be detected. Excluding 2015 from the version range will mean that the newer 0.5221 versions of vt get used.
-----
There is a version of vt in the bioconda linux-64 subdir that causes snippy to fail to detect variants, this is reported in https://github.com/tseemann/snippy/issues/410. The workaround on the linked issue rolls back the version of vt to a previous version by pinning the channel with a tag.
```conda install --name snippy-env -c bioconda/label/cf201901 vt==2015.11.10```
There are however later releases of vt, but …

Update snippy 4.6 recipe to not use vt from 2015

---

recipes/sistr_cmd/meta.yaml

The pytables > 3.10.2 could cause installation issues on older systems running Ubuntu 22.04 that do not have `blosc2` library available required now for pytables 3.10.2 https://github.com/PyTables/PyTables/releases
In addition improved recipe by using pip3 installer instead of `python setup.py install` as per guidelines
Error on Ubuntu 22.04
```
zip_safe flag not set; analyzing archive contents...
sistr.__pycache__.sistr_cmd.cpython-310: module references __file__
error: Couldn't find a setup script in /tmp/easy_install-lpl7j_y_/blosc2-3.2.0.tar.gz
Error: Process completed with exit code 1.
```
Updated database version 3 url  due to small error identified in the database as stated here https://zenodo.org/records/15078586.

SISTR v1.1.3 build #1 due to pytables < 3.10.2 req

---

recipes/vcflib/meta.yaml

Fixed vcflib not having dependency on fastahack causing `vcfvarstats --help` not to work.

Fixed #52603 vcflib fastahack dependency

---

.mergify.yml

Mergify hasn't been merging successful autobumps because the "OSX Tests" check name changed to "OSX-64 Tests". Also, we should not merge if the ARM builds failed.

ci: update check names in mergify

---

recipes/sr2silo/meta.yaml

This PR adds sr2silo, a tool for converting short-read genomic alignments data (SAM/BAM/CRAM) to custom cleartext JSON format required for the upload to the [SILO](https://github.com/GenSpectrum/LAPIS-SILO) Database as part of the [GenSpectrum](https://genspectrum.org/) and the [Loculus project](https://loculus.org/).
This package is still in early development. However, we would like to start an early release for better integration.
sr2silo is a Python tool developed at ETH Zurich's D-BSSE [Computational Biology Group](https://bsse.ethz.ch/cbg) in collaboration with the [Computational Evolution Group](https://bsse.ethz.ch/cevo)
While this project is currently specific to our in-house application, we intend to generalize its functionality soon.
---- …

Add sr2silo package

---

recipes/grampa/build.sh
recipes/grampa/meta.yaml
recipes/grampa/run_test.sh

This PR takes precedence over the [auto-generated one for v1.4.4 of GRAMPA](https://github.com/bioconda/bioconda-recipes/pull/55244) since I also needed to update the recipe.
This PR:
- Updates the test script to work with the bioconda option of GRAMPA's tests (newly implemented)
- Adds a build script in lieu of the script commands in the `meta.yaml` file
---- …

Update GRAMPA recipe

---

recipes/plink2/meta.yaml

Update `plink2` to version 2.0.0-a.6.9 (29 Jan 2025), following what was done on #48787.

Update plink2 to 2.0.0-a.6.9

---

recipes/reduce/build.sh
recipes/reduce/meta.yaml

This pull request includes updates to the build process and versioning for the `reduce` package. The most important changes include adding new flags(see https://github.com/rlabduke/reduce/issues/60) to the `cmake` command and updating the build number in the `meta.yaml` file.
Build process improvements:
* [`recipes/reduce/build.sh`](diffhunk://#diff-6bfbe2d3f68c7be97776494ff778f01b08607a3041f4d272ea1a99130ea7b11fR12-R16): Added `-DHET_DICTIONARY` and `-DHET_DICTOLD` flags to the `cmake` command to specify paths for dictionary files.
Versioning update:
* [`recipes/reduce/meta.yaml`](diffhunk://#diff-37430d7a465b92aa3eeb2b877b8f0a0114a69da464c4f46f0581677dceff8daaL13-R13): Incremented the build number from 0 to 1.

reduce: Update build script to add `-DHET_DICTIONARY` and `-DHET_DICTOLD` flags

---

recipes/r-dimsum/meta.yaml

This pull request addresses a build failure in autobump pull request #55493. The failure was due to not allowing any patch version of fastqc 0.11.

Update r-dimsum to 1.4; Fix: Incorporate autobump version update and allow any patch version of fastqc 0.11

---

recipes/sistr_cmd/meta.yaml

This build #2 fixes a very minor typo in the serovar  `I 1,4,[5],12:b:-` where letter `b` was mistyped as `i`. This affects the QC message output by the tool (`Perform d-tartrate test (dT) as both dT+ and dT- I 1,4,[5],12:b:- subtypes exist.`) alerting users about the need to perform d-tartrate test that is also done for Paratyphi B and Paratyphi B variant Java
As per `CHANGELOG.md`:
- Paratyphi B, Paratyphi B var. Java and I 1,4,[5],12:b:- will get information message in the qc_messages about the d-tartrate testing
@rpetit3  Please take a quick look at this re-release as we are about to release this version publicly to the Canadian provincial labs

SISTR v1.1.3 build #2 release to fix I 1,4,[5],12:i:- serovar mistyped for I 1,4,[5],12:b:-

---

recipes/jvarkit/jvarkit.sh
recipes/jvarkit/meta.yaml

Bug: broken java path with latest build.
```
mamba create -n jvarkit jvarkit
mamba activate jvarkit
jvarkit -h
```
```
/path/to/envs/jvarkit/bin/jvarkit: line 80: /path/to/envs/jvarkit/bin/java: No such file or directory
```
Update to discover the correct java path.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue …

fix: jvarkit java path

---

recipes/alignoth/build.sh
recipes/alignoth/meta.yaml

This pull request updates the build configuration for the `alignoth` package in its `meta.yaml` file. The most significant change is the increment of the build number and the removal of the build skip directive for macOS.

Add osx build to alignoth

---

recipes/parascopy/meta.yaml

This failed the nightly build, so trying to build on GHA. I suspect it's due to updates with freebayes.
----
Conda is …

parascopy: bump build number

---

recipes/gsearch/build.sh
recipes/gsearch/meta.yaml

Update gsearch to v0.2.8
----
in this release, I added coreset instruction command to cluster large HNSW graphs. 
Conda …

Update gsearch v0.2.8

---

recipes/sigprofilerplotting/meta.yaml

…ing 1.4.1
This PR patches the existing recipe for SigProfilerPlotting v1.4.1 to update the pandas dependency.
- Updated pandas requirement from <2.0.0 to >=2.0.0.
- Bumped build number from 0 to 1.
- No upstream code changes; only dependency compatibility updated.
- Local build and tests passed successfully.
**Context:**
In [SigProfilerPlotting v1.4.1's setup.py](https://github.com/AlexandrovLab/SigProfilerPlotting/blob/v1.4.1/setup.py#L64), the dependency on `pandas>=2.0.0` is explicitly specified.  
----
* New recipes not directly relevant …

Update: SigProfilerPlotting 1.4.1 pandas dependency and build number

---

recipes/snakemake-executor-plugin-cannon/meta.yaml

This adds a recipe for the snakemake-executor-plugin-cannon, which is a fork of the snakemake-exector-plugin-slurm specifically for the Cannon cluster at Harvard University.
---- …

add recipe for snakemake-executor-plugin-cannon

---

recipes/ltr_harvest_parallel/build.sh
recipes/ltr_harvest_parallel/meta.yaml

There was an error in the path to access a dependency script from the  main script.
It is now fixed
----
Conda is able …

fix sed command to touch the correct file

---

recipes/libcarna/build.sh
recipes/libcarna/meta.yaml
recipes/libcarna/run_test.sh
recipes/libcarna/test/CMakeLists.txt
recipes/libcarna/test/test.cpp

Update libcarna to 3.4.0, plus:
- Fix issue with Find*.cmake file
- Add missing LICENSE files
- Fix missing dependency warning
---- …

Update libcarna to 3.4.0

---

recipes/picrust2/meta.yaml
recipes/picrust2/post-link.sh

Made necessary changes to post-link.sh to update to v2.6.2 and incremented build number in meta.yaml
The automatic update to PICRUSt2-v2.6.2 was broken and some of the default files needed weren't being downloaded because only meta.yaml was updated, not post-link.sh. I've now updated post-link.sh to match version 2.6.2 so this should now be fixed. 
----
* PRs require reviews prior …

Fix PICRUSt2 v2.6.2

---

build-fail-blacklist
recipes/meme/4.11.2/meta.yaml

This is needed for antismash-lite. 
Package was missing liblzma-devel but now builds on linux-aarch64.
build-fail-blacklist entry removed.

meme 4.11.2: reenable and add linux-aarch64

---

recipes/omamer/meta.yaml

Hello, I'm opening this PR to adapt the libsqlite version. 
I found this error on this PR (https://github.com/galaxyproject/iwc/pull/767):
`Traceback (most recent call last):
File "/usr/local/bin/omark", line 52, in <module>
omark.launcher(arg)
File "/usr/local/lib/python3.9/site-packages/omark/omark.py", line 269, in launcher
get_omamer_qscore(omamerfile, dbpath, outdir, taxid, original_FASTA_file = original_fasta, isoform_file=isoform_file, taxonomic_rank=taxonomic_rank)
File "/usr/local/lib/python3.9/site-packages/omark/omark.py", line 116, in get_omamer_qscore
closest_corr = spd.get_sampled_taxa(likely_clade, 5 , tax_tab, sp_tab, tax_buff, taxonomic_rank)
File "/usr/local/lib/python3.9/site-packages/omark/species_determination.py", line 403, in get_sampled_taxa
ranks = …

Change version libsqlite for omamer recipe

---

recipes/omark/meta.yaml

Hello, I'm opening this PR to adapt the libsqlite version.
I found this error on this PR (https://github.com/galaxyproject/iwc/pull/767):
`Traceback (most recent call last): File "/usr/local/bin/omark", line 52, in <module> omark.launcher(arg) File "/usr/local/lib/python3.9/site-packages/omark/omark.py", line 269, in launcher get_omamer_qscore(omamerfile, dbpath, outdir, taxid, original_FASTA_file = original_fasta, isoform_file=isoform_file, taxonomic_rank=taxonomic_rank) File "/usr/local/lib/python3.9/site-packages/omark/omark.py", line 116, in get_omamer_qscore closest_corr = spd.get_sampled_taxa(likely_clade, 5 , tax_tab, sp_tab, tax_buff, taxonomic_rank) File "/usr/local/lib/python3.9/site-packages/omark/species_determination.py", line 403, in get_sampled_taxa ranks = …

Change version libsqlite for omark recipe

---

recipes/heasoft/meta.yaml

The OSX-64 test failed, but it should have been skipped since meta.yaml includes:
```
build:
number: {{ build }}
skip: true  # [win or osx]
```
This should prevent Conda from building or testing on macOS (including osx-64). However, the pipeline is still triggering a macOS-64 job, which fails early due to a runner error (No MediaTypeFormatter is available...).
Therefore this PR adds a condition to skip the tests for non-Linux-64 platforms.
----
* New recipes not directly relevant to the biological sciences need to be submitted to the …

Skip test for non-Linux-64 platforms (not built anyway)

---

recipes/auspice/meta.yaml

Changelog: <https://github.com/nextstrain/auspice/releases/tag/v2.63.0>
Note the Node version requirements were updated in <https://github.com/nextstrain/auspice/pull/1975> and are reflected here
---- …

Update Auspice to 2.63.0

---

recipes/vafator/meta.yaml

This is an update to vafator 2.2.2
This replaces this PR https://github.com/bioconda/bioconda-recipes/pull/56561 as this release requires some further changes to the recipe.
* Add run_exports to meta.yaml
* Add @LKress as a maintainer
---- …

Update vafator to 2.2.2

---

recipes/giatools/meta.yaml
recipes/pasta/build.sh
recipes/pasta/meta.yaml

The recipe for PASTA has an issue. It was using the wrong `hmmeralign` file. We have fixed that. We also move PASTA one version ahead. 
---- …

Update pasta to change build.sh and 1.9.3

---

recipes/phabox/meta.yaml

Solve a "ValueError" caused by the update of PyTorch
```
ValueError: Due to a serious vulnerability issue in torch.load, even with weights_only=True, we now require users to upgrade torch to at least v2.6 in order to use the function. This version restriction does not apply when loading files with safetensors.
```

Update PhaBOX's meta.yaml to solve a "ValueError" caused by the update of PyTorch

---

recipes/freyja/meta.yaml

Currently, Freyja can't be installed on arm/aarch because this conda recipe lists usher as a dependency. Usher is not available for those platforms - yet it's not needed by most subcommands. The workaround right now is to pip install Freyja, but that's silly. Just drop Usher as a requirement for aarch/arm and things work.
----
* PRs require reviews prior to being merged. Once your …

Allow installation of Freyja on arm64/aarch64 by not requiring usher there

---

recipes/resistify/meta.yaml

Changes to the hmmer recipe (see https://github.com/bioconda/bioconda-recipes/issues/56856) cause jackhmmer to be broken when installed alongside resistify due to libopenblas. Adding explicitly and testing jackhmmer as a potential fix
---- …

Update resistify recipe

---

recipes/coot-headless/run_test.py

This pull request updates the `run_test.py` script in the `recipes/coot-headless` directory to improve code clarity and consistency by directly using the `coot_headless_api` module instead of aliasing it as `chapi`.
Key change:
* Updated `run_test.py` to remove the alias `chapi` for `coot_headless_api` and directly use `coot_headless_api` for all method calls, improving code readability and reducing potential confusion.
---- …

coot-headless: Update test script

---

recipes/pyhmmer/meta.yaml

I'm not sure if this is the fix, but as reported in https://github.com/althonos/pyhmmer/issues/91 the latest update in Bioconda somehow only supports Python 3.9. I think this is because of the version pinning introduced in the autobump for the last release (#56020).
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue …

Fix Python host version in `pyhmmer` recipe

---

recipes/hifiasm_meta/meta.yaml

Not sure why this didn't get an autobump, the new version was released more than 12 hours ago.
---- …

Update hifiasm_meta to version 0.3.3

---

recipes/csubst/meta.yaml

This PR increases the build number to trigger a new build and publish osx-arm64 binaries for the csubst package.
As shown in the attached screenshot, currently only linux-64 and osx-64 are available on Anaconda.org.
All checks (including osx-arm64 build) have previously passed.
Thank you for your support!
---- …

Update: Enable osx-arm64 build for csubst (bump build number)

---

recipes/craq/build.sh
recipes/craq/meta.yaml

`craq` currently does not run as intended, because the `craq` executable expects scripts in the `CRAQ/src` folder to be in path relative to itself (relative paths are hardcoded in the `craq` scripts. However, when packaged in Conda, `craq` is called from a symlink in the Conda `${PREFIX}/bin/`, so the expected relative paths are broken. To fix this, the build script should symlink all scripts in `CRAQ/src` to `${PREFIX}/src`.
---- …

Update craq build script with expected relative paths

---

recipes/bx-python/conda_build_config.yaml
recipes/bx-python/meta.yaml

- **Remove py<39 guards as no longer supported**
- **Build bx-python for Python 3.13 as well**
I will remove the extra conda build config file once Python 3.13 is supported by Bioconda.
Bx-python is required by bcbio-gff which in turn is required by augur, hence making a Python 3.13 build now this manual way.

Build bx-python with Python 3.13 as well

---

recipes/snakemake-interface-scheduler-plugins/meta.yaml

Add recipe for snakemake-interface-scheduler-plugins
---- …

add: snakemake-interface-scheduler-plugins

---

recipes/nomadic/meta.yaml

Update nomadic to new version [0.5.0](https://github.com/JasonAHendry/nomadic/releases/tag/v0.5.0)
Nomadic is a real-time bioinformatics pipeline and dashboard for nanopore sequencing data, see [documentation](https://jasonahendry.github.io/nomadic/)
---- …

Update nomadic to v0.5.0

---

recipes/dapcy/meta.yaml

To be used instead of the autobump (https://github.com/bioconda/bioconda-recipes/pull/58296). Includes pinning of bio2zarr.
- Incidentally, is there an intended way to add changes on top of the autobump instead?
- Should I be using `seaborn-base` in favour of regular `seaborn`?
- Grayskull automatically added the `pip check` command section; is this required or recommended?
----
* …

Update dapcy recipe to 1.3.1

---

recipes/tetrimmer/meta.yaml

This PR updates the samtools runtime dependency in the TEtrimmer recipe to >=1.2.
TEtrimmer relies on samtools faidx to index FASTA genomes. When older versions of samtools (e.g., 0.1.19) are used, segmentation faults (error code -11) can occur during indexing, as reported in downstream usage.
By requiring samtools >=1.2, we ensure compatibility with current samtools versions (e.g., 1.20) and avoid runtime failures in TEtrimmer workflows.
- Updated meta.yaml:
yaml
- samtools >=1.2

Set the version of samtools to >=1.2 for TEtrimmer package

---

recipes/harpy/meta.yaml

@mencian I noticed that despite adding the `# [linux]` preprocessing selector to `apptainer`, it still tries to install it on a macOS system. Not sure if this will work or why it's still acting up, maybe you have ideas? See this log (Conda v25.5.1):
```
(base) person@hostname-MacBook-Pro ~ % conda create -n harpy -c bioconda -c conda-forge harpy=2.5.0
2 channel Terms of Service accepted
Channels:
- bioconda
- conda-forge
- defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
LibMambaUnsatisfiableError: Encountered problems while solving:
- nothing provides apptainer needed by harpy-2.5.0-pyhdfd78af_0
Could not solve for environment specs
The following package could not be installed
└─ harpy =2.5.0 * is not installable because it …
```

Update harpy preprocessing selector

---

recipes/remag/meta.yaml

**Supersedes #58368**
This PR updates REMAG to version v0.1.5 and fixes the failing tests by adding missing dependencies that were not included in the automated bump.
**Missing dependencies added:**
- `python-igraph >=0.10.0` - Required for Leiden clustering functionality  
- `leidenalg >=0.9.0` - Clustering algorithm
**Fixes:**
- Resolves `ModuleNotFoundError: No module named 'igraph'` that was causing test failures in #58368
- Updates to latest version with all required dependencies
REMAG is a specialized metagenomic binning tool designed for recovering high-quality eukaryotic genomes from mixed prokaryotic-eukaryotic samples.
- **homepage**: https://github.com/danielzmbp/remag
- **documentation**: https://github.com/danielzmbp/remag#readme
- **doi**: …

Update remag to v0.1.5

---

recipes/pharokka/meta.yaml

patch pharokka biopython dependency to remove upper limit to support python v3.13
https://github.com/gbouras13/pharokka/issues/397
Also observed on Google Colab notebook
----
* Please post …

Update pharokka build to support python v3.13

---

recipes/psipred/build.sh
recipes/psipred/meta.yaml
recipes/psipred/run_test.sh

This pull request adds a new conda recipe for the PSIPRED protein secondary structure prediction tool, enabling it to be built and installed within a conda environment. The new recipe includes build scripts, metadata, and tests to ensure correct installation and operation. The most important changes are grouped below:
**Recipe and Build System Integration:**
* Added a new `meta.yaml` file describing the PSIPRED package, its dependencies, source, license, and test commands for conda packaging.
* Introduced a `build.sh` script to automate building, patching, and installing PSIPRED binaries and data files in the correct conda locations, including adapting scripts for conda environments.
**Testing and Validation:**
* Added a `run_test.sh` script to verify that PSIPRED runs correctly after …

Add psipred v3.5

---

recipes/cuna/meta.yaml

- Pin pyarrow =20.0.0 to avoid incompatibilities.
- Keep pod5 without version to use default available in bioconda/conda-forge.

Update cuna 0.3.0 pin pyarrow

---

recipes/ddquint/meta.yaml

**Package name:** ddquint
**Version:** 0.1.0
**License:** MIT
**Summary:** Droplet Digital PCR Multiplex Analysis for chromosomal copy number detection
**Home:** https://github.com/globuzzz2000/ddQuint
**PyPI:** https://pypi.org/project/ddquint/
**Source:** https://pypi.io/packages/source/d/ddquint/ddquint-0.1.0.tar.gz
**SHA256:** b4a9d5e0f5d53edc860a6e0516a23894bd13765b5a7a5150975d97574f029241
**Build:**
- noarch: python
- installs from PyPI sdist via pip
**Run deps (conda):**
python>=3.10, numpy, scipy, pandas, scikit-learn, hdbscan, matplotlib, seaborn, openpyxl, wxpython, colorama, tqdm, send2trash
**Test:**
- `ddquint --help` passes locally with `conda mambabuild`

Add ddquint recipe (v0.1.0)

---

recipes/auspice/meta.yaml

[release notes](https://github.com/nextstrain/auspice/releases/tag/v2.64.0)
---- …

[auspice] version bump to 2.64.0

---

recipes/seqforge/meta.yaml

Bump seqforge to 1.0.4.
- Fixes visualize import issue and version mismatch
- Source: GitHub tag v1.0.4
- SHA256: <same as in meta.yaml>
- noarch: python, python >=3.10
Tests:
- `seqforge --version`
- import of `.utils.visualize`
---- …

seqforge 1.0.4; Conda install bug fix; correct version

---

recipes/varpubs/meta.yaml

This pull request adds a new conda recipe for `varpubs`, which is a tool for finding PubMed evidence on genetic variants and generating LLM-based summaries.

Add bioconda recipe for varpubs 0.1.1

---

recipes/sadie-antibody/meta.yaml

- Adds sadie-antibody v2.0.0 to bioconda
- SADIE (Sequencing Analysis and Data library for Immunoinformatics Exploration) provides command-line apps and a Python API for antibody/AIRR analyses
- **Homepage**: https://sadie.jordanrwillis.com
- **Source**: https://github.com/jwillis0720/sadie
- **License**: MIT
- **Version**: 2.0.0
- Package installs from PyPI source tarball
- Removed semantic-version from conda dependencies (will be installed via pip)
- All other dependencies are available in conda-forge/bioconda

Add sadie-antibody 2.0.0

---

recipes/auspice/meta.yaml

Update to latest version, see release notes:
<https://github.com/nextstrain/auspice/releases/tag/v2.65.0>
----
Conda is …

Update Auspice to 2.65.0

---

recipes/rseqc/meta.yaml

rseqc needs `r-base` at runtime, as multiple of its python scripts actually call `Rscript` internally, see here for a current list:
https://github.com/snakemake-workflows/rna-seq-star-deseq2/pull/91#issuecomment-3253583847
Also, there is more context in the comment above:
https://github.com/snakemake-workflows/rna-seq-star-deseq2/pull/91#issuecomment-3253559667
And I just added the new constraint `setuptools <81` following the linting recommendation:
> /opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/bioconda_utils/utils.py:43: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
----
Please …

update rseqc: explicitly declare cryptic Rscript dependency

---

recipes/gtdbtk/meta.yaml

Version and source update:
* Updated the `gtdbtk` version from `2.5.0` to `2.5.1` in `recipes/gtdbtk/meta.yaml` to pull in the latest release.
* Changed the source `sha256` hash to match the new version's tarball for verification.
Build configuration:
* Reset the build `number` from `1` to `0`, which is standard when bumping the package version.

Bump gtdbtk version to 2.5.1 and update hash

---

recipes/cdst/meta.yaml

This PR adds a new Bioconda recipe for **CDST (CoDing Sequence Typer)**, version **v0.2.0**.
CDST is a decentralized, MD5-hash–based pipeline for bacterial genome typing and clustering.  
It bypasses allele annotation and central databases, computes pairwise distances directly from predicted coding sequences,  
and supports multi-scale clustering for outbreak, lineage, and population-level analysis.
- **Source code:** https://github.com/l1-mh/CDST  
- **License:** GPL-3.0  
- **Tested environment:** Python 3.12, Biopython 1.85, pandas 2.2.2, SciPy 1.13.1, scikit-learn 1.5.1, networkx 3.3, matplotlib 3.9, joblib 1.4  
- **Build type:** noarch: python

Add recipe for cdst v0.2.1

---

recipes/stripepy-hic/meta.yaml

Closes https://github.com/bioconda/bioconda-recipes/pull/59403
---- …

Update stripepy-hic to v1.2.0

---

recipes/ipcr/LICENSE
recipes/ipcr/build.sh
recipes/ipcr/meta.yaml

**Summary**
* Packages `ipcr`, a fast in‑silico PCR tool with mismatch thresholds, 3′ terminal window policy, and a human‑readable `--pretty` alignment view.
* CLI provides `--forward/--reverse`, FASTA input, text/JSON/FASTA outputs, and deterministic `--sort`. `--mode realistic` defaults to a 3‑nt terminal window.&#x20;
**Upstream**
Repo: [https://github.com/KPU-AGC/ipcr](https://github.com/KPU-AGC/ipcr)
License: MIT (included)
Version: 1.1.0 (CLI prints `ipcr version 1.1.0`).&#x20;
**Build / recipe notes**
* Language: Go (CGO disabled). Build from source via `build.sh` using `go build -trimpath -buildvcs=false`.
* No third‑party Go modules; vendoring not required (script uses `-mod=vendor` only if `vendor/` exists).
* Platforms: linux‑64 (local build OK); CI will build osx‑64 / …

Add: `ipcr` 1.1.0 — pure‑Go in‑silico PCR CLI

---

recipes/pbstarphase/build.sh
recipes/pbstarphase/meta.yaml

Reverts bioconda/bioconda-recipes#59255
We are receiving reports that this build does not work.  Upon inspection it appears to be completely gutting the actual install of pb-StarPhase, and is potentially malicious.  This reverts the change.

Revert "update pbstarphase and enabled linux-aarch64 "

---

recipes/ena-webin-cli/ena_webin_cli.py
recipes/ena-webin-cli/meta.yaml

Fix bug in ena-webin-cli that results in errors when args contain parentheses
See:
- https://github.com/pathoplexus/ena-submission/issues/132
- https://github.com/enasequence/webin-cli/issues/156
Took me some time to figure out this was a bug in the bioconda wrapper.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue …

Fix ena-webin-cli bug due to unsafe wrapper script not doing proper shell quoting

---

recipes/snpeff/meta.yaml

SnpEff 5.3.0a install from bioconda.
On version 20 OpenJDK or below, getting:
```bash
snpEff -h
Error: LinkageError occurred while loading main class org.snpeff.SnpEff
java.lang.UnsupportedClassVersionError: org/snpeff/SnpEff has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 64.0
```
On version 21, it successfully runs.

Bump snpeff minimum java version

---

recipes/shovill/meta.yaml

Shovill is a very commonly used wrapper around some other assemblers. The tool has not been updated in some years but its dependencies (especially spades and skesa) have kept evolving. Bumping the build version will cause the new dependencies to be included in bioconda-derived containers.
---- …

Bump build version of shovill

---

recipes/coot-headless/build.sh
recipes/coot-headless/meta.yaml

This pull request updates the `coot-headless` build process to generate API documentation using Doxygen and ensures the necessary build dependency is included. It also increments the build number to reflect these changes.
Build process and documentation improvements:
* The build script (`build.sh`) now runs Doxygen in the `api/doxy-sphinx` directory to generate API documentation before proceeding with the rest of the build steps.
* The `meta.yaml` file adds `doxygen` as a build dependency to guarantee that documentation generation can occur during the build.
Packaging and versioning:
* The build number in `meta.yaml` is incremented from 1 to 2 to reflect the new changes in the package.
---- …

coot-headless: Add Doxygen python modules' documentation generation step

---

recipes/alloshp/meta.yaml

After observing that the latest github release of the underlying [repo](https://github.com/eead-csic-compbio/AlloSHP/releases/tag/2025.09.12) did not trigger a new recipe after 3 weeks we asked in 
[gitter](https://matrix.to/#/!MhHkICgthNLZeLiygG:gitter.im/$_VVQw0Jxl_HkYGdbsjway61AfxevC-KQ46svJqUPdJY?via=gitter.im&via=matrix.org&via=robbinsa.me) and @bgruening suggested the problem might be the version format.
So this PR changed the version in the header of meta.yaml to yyyy.mm.dd format

Update alloshp recipe

---

recipes/get_pangenes/meta.yaml

This is similar to https://github.com/bioconda/bioconda-recipes/pull/59876 .
After observing that the latest github release of the underlying [repo](https://github.com/Ensembl/plant-scripts/releases/tag/v1.3) did not trigger a new recipe after 3 weeks we asked in
[gitter](https://matrix.to/#/!MhHkICgthNLZeLiygG:gitter.im/$_VVQw0Jxl_HkYGdbsjway61AfxevC-KQ46svJqUPdJY?via=gitter.im&via=matrix.org&via=robbinsa.me) and @bgruening suggested the problem might be the version format.
So this PR changed the version in the header of meta.yaml to 1.3 format

Update get_pangenes recipe

---

recipes/wakhan/meta.yaml

Pinned python-kaleido ==0.2.1 to ensure compatibility with plotly ==5.24.1
When creating conda environments, newer versions of python-kaleido (v1.0.0+) were being automatically installed, causing incompatibility with the pinned Plotly version (5.24.1). This resulted in wakhan crashing during PDF generation with the following error:
```
Warning: You have Plotly version 5.24.1, which is not compatible with this version of Kaleido (1.0.0).
This means that static image generation (e.g. `fig.write_image()`) will not work.
Please upgrade Plotly to version 6.1.1 or greater, or downgrade Kaleido to version 0.2.1.
File "/home/fvillena/miniforge3/envs/wakhan_test/bin/wakhan", line 10, in <module>
sys.exit(main())
File …
```

fix: pin python-kaleido==0.2.1 for stability
