bioconda/bioconda-recipes

- recipes/biobb_analysis/meta.yaml
> [biobb_analysis] update 4.0.1

- .github/workflows/PR.yml
- azure-pipeline-master.yml
- recipes/quickbam/build.sh
- recipes/quickbam/instrument.h
- recipes/quickbam/meta.yaml
> Add quickBAM

- recipes/minibusco/meta.yaml
Update to minibusco v0.2.1.
----
<details>
Everyone …
> Update to minibusco v0.2.1

- recipes/hificnv/build.sh
- recipes/hificnv/meta.yaml
Adds the recipe for HiFiCNV. This is a static binary file, recipe was mirrored from `hiphase`.
----
<details> …
> Add HiFiCNV

- .github/workflows/PR.yml
- recipes/libbigwig/meta.yaml
> Test artifact creation

- recipes/metaphor/meta.yaml
> Edit metaphor

- build-fail-blacklist
- recipes/medaka/LICENSE.md
- recipes/medaka/build.sh
- recipes/medaka/meta.yaml
> Update medaka to 1.8.0 and remove from blacklist

- recipes/auspice/meta.yaml
Release notes available at
https://github.com/nextstrain/auspice/releases/tag/v2.46.0
---- …
> Update Auspice to 2.46.0

- recipes/panfeed/meta.yaml
Adding a new recipe for [panfeed](https://github.com/microbial-pangenomes-lab/panfeed), described in [this publication](https://www.biorxiv.org/content/10.1101/2023.04.11.536385v1.full).
Disclaimer: I am one of the maintainers and an author in the publication.
> Add panfeed 1.5.0

- recipes/abritamr/meta.yaml
https://github.com/MDU-PHL/abritamr/blob/eff5b0e471185edf84cd8c471449c9b205a1699b/abritamr/RunFinder.py#L39
---- …
> abritamr: add parallel

- recipes/biotransformer/LICENSE
- recipes/biotransformer/biotransformer.py
- recipes/biotransformer/meta.yaml
This updates biotransformer to the latest build of the biotransformer 3.0 jar file.
----
<details>
<summary>Please use …
> update biotransformer version

- recipes/matchmsextras/LICENCE
- recipes/matchmsextras/meta.yaml
A package with additional functions for matchms (already on bioconda)
> Add matchmsextras

- recipes/annonars/build.sh
- recipes/annonars/meta.yaml
Adding the annonars package.
----
<details>
Everyone …
> adding annonars v0.2.0

- recipes/pyhmmer/meta.yaml
This PR updates the DOI for PyHMMER, since there is now a Bioinformatics application note describing the package.
---- …
> Update `pyhmmer` recipe with Bioinformatics paper DOI

- recipes/agat/meta.yaml
This PR Includes some missing dependencies.
----
<details> …
> AGAT: include missing depencies

- recipes/kingfisher/meta.yaml
Update Kingfisher dependencies
----
<details> …
> Update Kingfisher dependencies

- recipes/harpy/meta.yaml
fix the declaration of recipe-maintainers
----
<details> …
> Update meta.yaml to include recipe-maintainers

- recipes/medicc2/meta.yaml
Update MEDICC2 to version 1.0.0
Some changes to the dependencies were made so an automatic version bump would not have worked.
---- …
> Update MEDICC2 to version 1.0.0

- build-fail-blacklist
- recipes/makehub/meta.yaml
- recipes/makehub/patch
> Update makehub to 1.0.6 and remove from blacklist

- build-fail-blacklist
- recipes/ucsc-bedtobigbed/include.patch
- recipes/ucsc-bedtobigbed/meta.yaml
- recipes/ucsc-fatotwobit/include.patch
- recipes/ucsc-fatotwobit/meta.yaml
- recipes/ucsc-liftover/include.patch
- recipes/ucsc-liftover/meta.yaml
- recipes/ucsc-twobitinfo/include.patch
- recipes/ucsc-twobitinfo/meta.yaml
- recipes/ucsc-twobittofa/include.patch
- recipes/ucsc-twobittofa/meta.yaml
- recipes/ucsc-wigtobigwig/include.patch
- recipes/ucsc-wigtobigwig/meta.yaml
Update ucsc-bedtobigbed, -fatotwobit, -liftover, -twobitinfo, -twobittofa, and -wigtobigwig to v447 and take them off the blacklist.
---- …
> Update select UCSC tools to v447 and remove from blacklist

- recipes/gsearch/build.sh
- recipes/gsearch/meta.yaml
> Update gsearch 0.1.2 with annembed

- recipes/circtools/meta.yaml
> Update circtools to 1.3.0

- build-fail-blacklist
- recipes/ucsc-genepredcheck/include.patch
- recipes/ucsc-genepredcheck/meta.yaml
- recipes/ucsc-genepredtobed/include.patch
- recipes/ucsc-genepredtobed/meta.yaml
- recipes/ucsc-genepredtobiggenepred/include.patch
- recipes/ucsc-genepredtobiggenepred/meta.yaml
- recipes/ucsc-gff3togenepred/include.patch
- recipes/ucsc-gff3togenepred/meta.yaml
- recipes/ucsc-gtftogenepred/include.patch
- recipes/ucsc-gtftogenepred/meta.yaml
Update ucsc-genepredcheck, -genepredtobed, -genepredtobiggenepred, -gff3togenepred, and -gtftogenepred to v447 and remove them from blacklist.
---- …
> Update UCSC genepred tools to v447 and remove from blacklist

- recipes/segway/meta.yaml
GMTK recently had an issue fixed with an updated build and Segway was previously pinned to a specific build. This removes the build pinning.
---- …
> Remove pinned build from Segway recipe's gmtk dependency

- recipes/rnabloom/meta.yaml
Update meta.yaml to include publication DOI for RNA-Bloom2.
----
<details> …
> Update recipe for RNA-Bloom

- recipes/biobb_flexdyn/meta.yaml
> [biobb_flexdyn] update 4.0.2

- recipes/viroconstrictor/meta.yaml
Change in requirements to only use `snakemake-minimal` in order to circumvent an error.
----
<details> …
> update recipe for ViroConstrictor (v1.3.1)

- recipes/biobb_flexserv/meta.yaml
> [biobb_flexserv] update 4.0.0.1

- recipes/eklipse/build.sh
- recipes/eklipse/meta.yaml
eklipse --test was not working because it was looking for the data required in bin/data, I have now created the data folder within bin and copied the required files in there
---- …
> feat added data folder in bin to make --test work

- recipes/sra-tools/build.sh
- recipes/sra-tools/meta.yaml
> Update SRA-tools recipe to build with CXX

- recipes/rmblast/build.sh
- recipes/rmblast/configurellvm.patch
- recipes/rmblast/isb-2.14.0+-rmblast.patch
- recipes/rmblast/meta.yaml
> Update rmblast to 2.14.0

- recipes/deeplc/meta.yaml
> Update DeepLC to 2.1.8

- recipes/nrpys/LICENSE.txt
- recipes/nrpys/build.sh
- recipes/nrpys/meta.yaml
[NRPyS](https://github.com/kblin/nrpys/): Python language bindings for nrps-rs substrate specificity predictor
Python module required by antiSMASH v7, which hopefully addresses the missing "nrpys" module error during antiSMASH v7 build tests.
---- …
> Add recipe for NRPyS v0.1.1

- recipes/anospp-analysis/meta.yaml
Updating anospp-analysis v0.2.1 recipe with version restrictions and more tests
----
<details> …
> anospp-analysis v0.2.1 recipe build update

- recipes/dnaapler/meta.yaml
Adds dnaapler, program to reorient assembled bacterial chromosomes, plasmids, phages or anything you want to start with a specific gene.
---- …
> Add dnaapler

- recipes/genoflu/build.sh
- recipes/genoflu/meta.yaml
> genoflu version 1.0

- recipes/biobb_flexdyn/meta.yaml
> [biobb_flexdyn] update 4.0.3

- recipes/biobb_flexserv/meta.yaml
> [biobb_flexserv] update 4.0.2

- recipes/genomepy/meta.yaml
> Update genomepy to 0.16.0

- recipes/abromics_galaxy_json_extractor/meta.yaml
**abromics_galaxy_json_extractor** is a tool:
- extract results from some antimicrobial tools (see the tool doc) 
-  generate a json file to be use to database integration
-  summarize some already generated json file ton only one
- Was developped also to take the *historic ID* from Galaxy to automatically download from a Galaxy instance the files
----
* PRs require reviews prior to …
> add abromics_galaxy_json_extractor_tool

- recipes/repic/meta.yaml
PR to Add new REPIC recipe:
REPIC is an ensemble learning approach to cryogenic-electron microscopy (cryo-EM) particle picking. It identifies particles common to multiple picked particle sets (i.e., consensus particles) using graph theory and integer linear programming (ILP). Picked particle sets may be found by a human specialist (manual), template matching, mathematical function (e.g., RELION's Laplacian-of-Gaussian auto-picking), or machine-learning method.
----
* New recipes not directly relevant to the biological sciences need to be …
> please add REPIC recipe

- recipes/biscuit/meta.yaml
Update BISCUIT version to 1.2.1
----
<details> …
> Update to biscuit v1.2.1.20230601

- recipes/biobb_structure_checking/meta.yaml
> Update biobb_structure_checking 2023.2_RC

- recipes/biobb_model/meta.yaml
> [biobb_model] update 4.0.1 update biobb_structure_checking to 3.13.0

- recipes/plassembler/build.sh
- recipes/plassembler/meta.yaml
Updates Plassembler to v1.1.0.
Code has been refactored with better software development standards and added to Pypi, so build.sh no longer required and meta.yaml completely overhauled. Some dependencies also changed.
---- …
> Update Plassembler to 1.1.0

- recipes/metabuli/build.sh
- recipes/metabuli/meta.yaml
> Add metabuli

- recipes/hmftools-linx/meta.yaml
Update linx to 1.23.6
----
<details>
Everyone has …
> Update hmftools-linx to 1.23.6

- recipes/searchgui/meta.yaml
- recipes/searchgui/searchgui.py
> Update searchgui to 4.2.14

- recipes/idr/meta.yaml
I am having some issues with idr and newer numpy versions as they deprecated np.int for int. Also see: 
https://github.com/nboley/idr/issues/64 and https://github.com/kundajelab/idr/pull/3
Somehow there were already builds higher than this one, so I had to go from 7 to 10
---- …
> Update idr, idr doesn't work with numpy > 1.19

- recipes/raptor/build.sh
- recipes/raptor/meta.yaml
> Update raptor to 3.0.0

- recipes/unifrac-binaries/build.sh
- recipes/unifrac-binaries/meta.yaml
Update unifrac-binaries to v1.3.2.
New build procedure.
----
<details> …
> Update unifrac-binaries to v1.3.2

- recipes/selenzy_wrapper/meta.yaml
Update selenzy_wrapper dependancies
> Update selenzy_wrapper dependencies

- recipes/harpy/meta.yaml
> Update build to include missing deps

- recipes/biophi/meta.yaml
> Allow python 3.8 in biophi

- recipes/abromics_galaxy_json_extractor/meta.yaml
Update dependencies due to Galaxu conda error :
```
PackagesNotFoundError: The following packages are not available from current channels:
- abromics_galaxy_json_extractor -> libexpat
- abromics_galaxy_json_extractor -> libuuid[version='>=2.38.1,<3.0a0']
Current channels:
- https://conda.anaconda.org/conda-forge/linux-64
- https://conda.anaconda.org/conda-forge/noarch
- https://conda.anaconda.org/bioconda/linux-64
- https://conda.anaconda.org/bioconda/noarch
- https://repo.anaconda.com/pkgs/main/linux-64
- https://repo.anaconda.com/pkgs/main/noarch
- https://repo.anaconda.com/pkgs/free/linux-64
- https://repo.anaconda.com/pkgs/free/noarch
- https://repo.anaconda.com/pkgs/r/linux-64
- https://repo.anaconda.com/pkgs/r/noarch
```
----
`@BiocondaBot please add …
> Update dependencies abromics galaxy json extractor

- recipes/tciaclient/LICENSE
- recipes/tciaclient/meta.yaml
Add recipe for tciaclient
----
<details>
Everyone has …
> Add recipe for tciaclient

- recipes/iqtree/build.sh
- recipes/iqtree/meta.yaml
> Update iqtree to 2.2.2.7

- recipes/genoflu/build.sh
- recipes/genoflu/meta.yaml
> Genoflu update

- recipes/sctagger/meta.yaml
Update sctagger version to 1.1.1
----
<details> …
> Update sctagger version to 1.1.1

- recipes/kraken2/Makefile.patch
- recipes/kraken2/build.sh
- recipes/kraken2/meta.yaml
> Update kraken2 to 2.1.3

- recipes/dfam/build.sh
- recipes/dfam/download-dfam.py
- recipes/dfam/meta.yaml
Update dfam to 3.7.
----
<details>
Everyone has …
> Update dfam to 3.7.

- recipes/meningotype/meta.yaml
`mlst` versions before version 2.13 rely on `file` (part of the `coreutils` package) which isn't bundled with the package. As of this writing the latest (tag `0.8.5--pyhdfd78af_0`) container for `meningotype` thus does not contain `file` but does contain an old version of `mlst` (v 2.11) which requires `file` and thus fails, causing a failure in the `meningotype` command.
This PR bumps the version requirement for `mlst` to a version that does not exhibit this problem.
----
* New recipes not directly relevant to the biological sciences need to …
> Update meningotype 0.8.5 dependencies

- recipes/pmx_biobb/meta.yaml
> pmx_biobb python38 Update meta.yaml

- recipes/hiphase/meta.yaml
Update for HiPhase to v0.10.0.  Changes generated with updates from PR https://github.com/bioconda/bioconda-utils/pull/896.
---- …
> Update HiPhase to v0.10.0

- recipes/reframed/meta.yaml
- recipes/smetana/meta.yaml
Also add dependency reframed 1.4.0.
----
<details> …
> Add recipe for smetana/1.2.0

- recipes/mbg/meta.yaml
- recipes/mbg/osx_availability.patch
- recipes/mbg/version.patch
Update MBG to version 1.0.15
----
<details>
Everyone …
> Update MBG to version 1.0.15

- recipes/compleasm/meta.yaml
This PR adds [compleasm](https://github.com/huangnengCSU/compleasm) (compleasm: a faster and more accurate reimplementation of BUSCO) to bioconda. Compleasm is an efficient tool for assessing the completeness of genome assemblies.
---- …
> Add compleasm v0.2.2

- recipes/confindr/meta.yaml
Update ConFindr v0.8.1 package requirements and add self to list of recipe maintainers.
----
<details> …
> Update ConFindr v0.8.1 package requirements

- recipes/pmx_biobb/meta.yaml
> pmx_biobb python39 Update meta.yaml

- recipes/pmx_biobb/meta.yaml
> pmx_biobb python 3.10 Update meta.yaml

- recipes/episcanpy/meta.yaml
> Update episcanpy to 0.4.0

- recipes/gfflu/meta.yaml
This PR adds a Conda recipe for gfflu v0.0.1 a Python CLI app to generate annotations of Influenza A virus (IAV) gene segment nucleotide sequences with [BLASTX](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastx&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome) and [Miniprot](https://github.com/lh3/miniprot) using the same protein sequences as [Influenza Virus Sequence Annotation Tool](https://www.ncbi.nlm.nih.gov/genomes/FLU/annotation) and output a [GFF3](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) file with the expected genetic features for each of the 8 IAV gene segments.
----
* If this PR adds or updates a recipe, …
> Add gfflu v0.0.1

- recipes/deeptools/meta.yaml
I had to remove and re-create [the latest release (it's again 3.5.2)](https://github.com/deeptools/deepTools/releases), this was pushed to pypi now. But I still need to update the conda recipe.
Thanks in advance!
> Fix deeptools/deepTools/issues/1223

- recipes/dendropy/build.sh
- recipes/dendropy/meta.yaml
> Update dendropy to 4.6.1

- recipes/flair/meta.yaml
Update flair
----
<details>
Everyone has access to …
> update flair with latest version

- recipes/cooltools/meta.yaml
Add a temporary upper ceiling on pandas version for cooltools due to incompatibility.
----
<details> …
> Update: add upper limit on pandas version for cooltools

- recipes/trnascan-se/build.sh
- recipes/trnascan-se/meta.yaml
> Update tRNAscan-SE to 2.0.12

- recipes/r-recetox-xmsannotator/meta.yaml
Update recetox-xMSannotator to 0.10.0. This introduced new dependencies and version pinning.
> Update recetox-xMSannotator to 0.10.0

- recipes/isoquant/meta.yaml
Update IsoQuant to 3.3.0
Mostly cosmetics and bug-fixes
> Update IsoQuant to 3.3.0

- recipes/superdsm/meta.yaml
Updates superdsm to v0.1.1
----
<details>
Everyone …
> Updates superdsm to v0.1.1

- build-fail-blacklist
- recipes/short-read-connector/build.sh
- recipes/short-read-connector/meta.yaml
* Change source URL to GitHub, INRIA server from v1.1.3 not reachable
* Add C++ compiler dependency for build
* Main shell script name has changed, update build.sh and tests
* Use abbreviation for license; add license_family field
* Remove short-read-connector from build blacklist - No longer failing when tested locally
* Skip build for OS X
Second try to update this recipe (see PR #40889 ), this time using a new branch instead and skipping build for OS X that failed tests that I could not troubleshoot.
----
* New recipes not directly relevant …
> Update short-read-connector to v1.2.0

- recipes/dram/meta.yaml
DRAM is not compatilbe with latests version of python 3.11, hence scipy, scikit learn and probalby pandas. 
---- …
> limit dependencies versions of dram

- recipes/clair3/meta.yaml
> Update clair3 to v1.0.3

- recipes/unikseq/meta.yaml
----
<details>
Everyone has access to the following …
> Update unikseq to 1.3.4

- recipes/tower-cli/build.sh
- recipes/tower-cli/meta.yaml
Adds [Nextflow Tower CLI](https://github.com/seqeralabs/tower-cli). 
See https://github.com/seqeralabs/tower-cli/issues/293
---- …
> Add tower-cli recipe

- recipes/repic/meta.yaml
Adds link to new documentation and improvements to the REPIC codebase.
----
<details> …
> Update REPIC recipe to 0.1.0

- recipes/superdsm/meta.yaml
Removes a dispensable dependency from the recipe.
----
<details> …
> Update recipe for superdsm-0.1.2

- recipes/ncbi-genome-download/assembly_accession.patch
- recipes/ncbi-genome-download/meta.yaml
There has been a recent change to a header in a file parsed by ncbi-genome-download.
This patch incorporates an open PR to ncbi-genome-download: https://github.com/kblin/ncbi-genome-download/pull/210 which is related to this issue https://github.com/kblin/ncbi-genome-download/issues/209
---- …
> Patch ncbi-genome-download recipe

- recipes/bioconvert/build.sh
- recipes/bioconvert/meta.yaml
> Update bioconvert to 1.1.0

- recipes/beav/meta.yaml
Update beav to v.0.0.14 and added pftools req.
----
<details> …
> Update beav to 0.0.14 plus added req

- recipes/biobb_structure_checking/meta.yaml
> biobb_structure_checking biopython>=1.79

- recipes/table2asn/build.sh
- recipes/table2asn/meta.yaml
> Add recipe for table2asn v1.27.792

- recipes/derna/build.sh
- recipes/derna/meta.yaml
Add DERNA recipe.  DERNA optimizes RNA sequence design for a target protein sequence.
----
<details> …
> Add derna recipe

- recipes/biocantor/meta.yaml
PR to add BioCantor, a python library for coordinate manipulation.
----
<details> …
> Add biocantor

- recipes/viromeqc/build.sh
- recipes/viromeqc/meta.yaml
Adding ViromeQC. A package that determines viral enrichment in metagenomic samples (https://github.com/SegataLab/viromeqc)
---- …
> Add ViromeQC

- recipes/csvtk/meta.yaml
- [csvtk v0.26.0](https://github.com/shenwei356/csvtk/releases/tag/v0.26.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.26.0/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.26.0)
- `csvtk`:
- **near all commands skip empty files now**. [#204](https://github.com/shenwei356/csvtk/issues/204)
- the global flag `--infile-list` accepts stdin "-". [#210](https://github.com/shenwei356/csvtk/issues/210)
- new command `csvtk fix`: **fix CSV/TSV with different numbers of columns in rows**. [#226](https://github.com/shenwei356/csvtk/issues/226)
- `csvtk pretty`: **rewrite to support wrapping cells**. [#206](https://github.com/shenwei356/csvtk/issues/206) …
> Update CSVTK to v0.26.0

- recipes/emvc-2/meta.yaml
Resume osx build for recipe emvc-2
Previously skipped because of issue #41526, now resolved
----
<details> …
> Update emvc-2, resume osx build

- recipes/derna/meta.yaml
Resume osx build for recipe derna
Previously skipped because of issue #41526 which has been resolved
----
<details> …
> Update derna, resume osx build

- recipes/cazy_webscraper/meta.yaml
> Update cazy_webscraper to 2.3.0

- recipes/varlociraptor/meta.yaml
Build Varlociraptor 8.3 for macOS after it has been disabled due to issues in the build process.
----
<details> …
> Update Varlociraptor 8.3, resume osx build

- recipes/table2asn/build.sh
- recipes/table2asn/meta.yaml
> Update table2asn binary permissions

- recipes/foldseek/meta.yaml
> Update Foldseek to release 7

- recipes/trinity/build.sh
- recipes/trinity/meta.yaml
> Update trinity recipe to build on OSX

- recipes/shigeifinder/meta.yaml
> Update shigeifinder to 1.3.5

- recipes/dysgu/meta.yaml
Update of dysgu to v1.4
----
<details>
Everyone has …
> Rebuild dysgu 1.4

- recipes/flams/meta.yaml
With this pull request, I want to add the FLAMS-package to Bioconda. FLAMS is a command line tool for identifying conserved lysine modification sites.
---- …
> Add recipe for flams

- recipes/r-crbhits/build.sh
- recipes/r-crbhits/meta.yaml
> Add CRBHits

- recipes/pbfusion/build.sh
- recipes/pbfusion/meta.yaml
Update pbfusion recipe for v0.2.2
----
<details> …
> Update pbfusion recipe for v0.2.2

- recipes/geno2phenotb/meta.yaml
geno2phenoTB is a machine learning based engine to predict Mycobacterium tuberculosis drug resistance using whole-genome sequencing data.
---- …
> Add geno2phenoTB

- recipes/decoupler/meta.yaml
> Add Python decoupler

- recipes/meme/build.sh
- recipes/meme/meta.yaml
> Update MEME to 5.5.3

- recipes/hlafreq/meta.yaml
- recipes/metagenome-atlas/meta.yaml
Add HLAfreq recipe building from pypi
----
<details> …
> Add HLAfreq recipe

- recipes/python-monovar/build.sh
- recipes/python-monovar/meta.yaml
Add Python-MonoVar recipe.
----
<details>
Everyone …
> Add Python-MonoVar recipe

- recipes/deepfplearn/meta.yaml
> initial commit of deepfplearn

- recipes/galaxy-files/meta.yaml
> add galaxy-files

- recipes/nanometa-live/meta.yaml
Adding Nanometa-Live
----
<details>
Everyone has …
> Add Nanometa Live

- recipes/fasta3/meta.yaml
Also update homepage URL, previous page no longer up
----
<details> …
> Update fasta3 to v38.3.8i

- recipes/pmx_biobb/meta.yaml
> [pmx_biobb] update 4.1.2

- recipes/pmx_biobb/meta.yaml
> [pmx_biobb] update 4.1.2 build 1: Python 3.7

- recipes/pmx_biobb/meta.yaml
> [pmx_biobb] update 4.1.2 build 2: Python [no vers]

- recipes/scirpy/meta.yaml
v0.13 is compatible with pandas 2.0. Forgot to remove the constraints during autobump. 
Fixes https://github.com/scverse/scirpy/issues/426
---- …
> Scirpy: unpin pandas

- recipes/dropest/meta.yaml
> Equivalent to #40459

- recipes/pedesigner/meta.yaml
Add pedesigner
----
<details>
Everyone has access to …
> Add Pedesigner

- recipes/openms-meta/meta.yaml
> [Update] Enable OpenMS for macOS again

- recipes/superdsm/meta.yaml
- recipes/tspex/meta.yaml
Update superdsm to 0.1.3:
- dependency on `posix_ipc` removed
- dependency on `ray-default` replaced by `ray-core`
---- …
> Update superdsm to 0.1.3

- recipes/r-wormbase/build.sh
- recipes/r-wormbase/meta.yaml
Add r-wormbase R package:
- https://r.acidgenomics.com/packages/wormbase/
- https://github.com/acidgenomics/r-wormbase/
---- …
> Add r-wormbase 0.4.1

- recipes/verticall/meta.yaml
Adds a recipe for the [Verticall](https://github.com/rrwick/Verticall) tool for building recombination-free trees.
---- …
> Add Verticall

- recipes/gnparser/build.sh
- recipes/gnparser/meta.yaml
[Gnparser](https://github.com/gnames/gnparser) parses scientific names into its semantic components; part of the Global Names Architecture project.
---- …
> Add gnparser 1.7.3

- recipes/btllib/meta.yaml
- Fixed issues related to coverage tests being included in release
- Added a utility function to calculate the Phred average given a string
- Enabled strict mode in bash scripts
- Fixed const-related clang-tidy complaints
----
* …
> Update btllib to 1.6.2

- recipes/gmtk/build.sh
- recipes/gmtk/meta.yaml
This removes a previous erraneous inclusion of the entire build environments lib directory when building/linking gmtk binaries and libraries.
---- …
> Update: Remove extra libs from being linked in with gmtk build

- recipes/searchgui/build.sh
- recipes/searchgui/meta.yaml
- recipes/searchgui/searchgui.py
> Update searchgui to 4.2.17

- recipes/matchms/meta.yaml
> Update matchms with pandas dependency

- recipes/svim/meta.yaml
> Update svim to 2.0.0

- recipes/pmx_biobb/meta.yaml
> [pmx_biobb] update 4.1.3

- recipes/pmx_biobb/meta.yaml
> Update meta.yaml to create py3.7 version

- recipes/blast/build.sh
- recipes/blast/meta.yaml
This PR aims to include blast_vdb and tblastn_vdb introduced from the 2.13.0
https://ncbiinsights.ncbi.nlm.nih.gov/2022/03/29/blast-2-13-0/
---- …
> Update blast: include *_vdb

- recipes/biobb_pmx/meta.yaml
> [biobb_pmx] update 4.0.0

- recipes/spoa/build.sh
- recipes/spoa/meta.yaml
> Update spoa to 4.0.8

- recipes/superdsm/meta.yaml
Fixes dependencies of the superdsm recipe (turns out compatibility is broken if `scikit-image` is newer than 0.19)
---- …
> Updates recipe for superdsm 0.1.3

- build-fail-blacklist
- recipes/tobias/build.sh
- recipes/tobias/meta.yaml
> Update tobias to 0.15.1

- recipes/metabuli/meta.yaml
- Fixed memory-related bugs.
- `classify` generates a Krona report file.
- New option of `classify`: Low-complexity masking by `--mask` and `--mask-prob` (#20) 
- New option of `classify`: `--match-per-kmer` option in `classify` workflow (#20) 
- `databases` downloads DBs as tar.gz and unzips them. 
- `classify` ignores reads shorter than 26 nt.
- `database-report` generates a report of taxa included in a database.
---- …
> Update Metabuli to 1.0.1

- recipes/fastlin/meta.yaml
> add fastlin to Bioconda channel

- recipes/freebayes/meta.yaml
- recipes/vcflib/meta.yaml
> fix: pin compatible versions of vcflib in freebayes recipe

- recipes/hmftools-neo/build.sh
- recipes/hmftools-neo/meta.yaml
- recipes/hmftools-neo/neo.sh
Add recipe for hmftools-neo
----
<details>
Everyone …
> Add hmftools-neo

- recipes/hmftools-isofox/meta.yaml
> Update hmftools-isofox to v1.6.2

- recipes/replidec/meta.yaml
> Add replidec

- recipes/freebayes/meta.yaml
> add vcflib to freebayes run section

- recipes/clair3-trio/build.sh
- recipes/clair3-trio/meta.yaml
> Update Clair3-Trio to v0.7

- recipes/libsbml/meta.yaml
> Try building libsbml on OSX

- recipes/clair3/meta.yaml
> Update clair3 to v1.0.4

- recipes/msamtools/meta.yaml
Update version to 1.1.3 build 0
----
<details> …
> Update version to 1.1.3 build 0

- recipes/perl-perldoc/build.sh
- recipes/perl-perldoc/meta.yaml
> Add perl-perldoc

- recipes/phyml/Makefile.patch
- recipes/phyml/build.sh
- recipes/phyml/meta.yaml
- recipes/phyml/phytime.patch
> Update phyml to 3.3.20220408

- recipes/tabixpp/build.sh
- recipes/tabixpp/meta.yaml
- recipes/tabixpp/shared_lib.patch
> Update tabixpp to 1.1.2

- recipes/flair/meta.yaml
Flair runs but fails its test because minimap2 output changed substantially. This is a quick fix until we figure out if the new minimap2 output is better.
---- …
> Update downgraded minimap2, incompatibility issues

- recipes/liftover/meta.yaml
> Add recipe for liftover v1.1.16

- recipes/peekseq/build.sh
- recipes/peekseq/meta.yaml
Adding recipe for peekseq - a k-mer based approach for assessing protein coding potential de novo
----
<details> …
> Add peekseq recipe

- recipes/kmcp/meta.yaml
- `kmcp compute/split-genomes`:
- fix a bug in chunk computation when splitting circular genomes (`--circular`).
- `kmcp search/merge`:
- append simple stats to the search result as comment lines, including the number of input and matched queries. e.g.,
- `kmcp profile`:
- fix metaphlan out format. [#34](https://github.com/shenwei356/kmcp/issues/34)
- show stats of the number of input and matched queries in log. **It would be helpful to show whether the reference genomes cover all microorganisms in the sample**.
20:00:55.295 [INFO] 99.3084% (923820/930254) reads matched
20:00:55.295 [INFO] 100.0000% (923820/923820) matched reads belong to the 2 references in the profile
- new tutorials:
- [Detecting specific …
> Update KMCP to v0.9.3

- recipes/seqkit/meta.yaml
- [SeqKit v2.5.0](https://github.com/shenwei356/seqkit/releases/tag/v2.5.0) - 2023-07-16 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.5.0/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.5.0)
- new command `seqkit merge-slides`: merge sliding windows generated from seqkit sliding. [#390](https://github.com/shenwei356/seqkit/issues/390)
- `seqkit stats`:
- added a new flag `-N/--N` for appending other N50-like stats as new columns. [#393](https://github.com/shenwei356/seqkit/issues/393)
- added a progress bar for > 1 input files.
- write the result of each file immediately (no output buffer) when using `-T/--tabular`.
- `seqkit translate`:
- add options `-s/--out-subseqs` and `-m/--min-len` to …
> Update SeqKit to v2.5.0

- recipes/arcas-hla/meta.yaml
Executing `arcasHLA genotype` does not result in intermediate quantification files to be produced by kallisto which is a dependency package of arcasHLA. The log of arcasHLA gives the following message:
```
Deprecated: `kallisto pseudo` is deprecated. See `kallisto bus`.
```
The latest version of Kallisto deprecates the usage of `kallisto pseudo`. To fix this problem the version of kallisto should be fixed to `v0.44.0` in this recipe.
------- …
> Update version of kallisto to 0.44.0 meta.yaml

- recipes/aviary/meta.yaml
Update Aviary to v0.6.0
----
<details>
Everyone has …
> Update Aviary to v0.6.0

- recipes/fastools/meta.yaml
Add recipe for fastools 1.1.5.
----
<details> …
> Add recipe for fastools 1.1.5.

- recipes/biobb_cmip/meta.yaml
> [biobb_cmip] update 4.0.0

- recipes/demultiplex/LICENSE
- recipes/demultiplex/meta.yaml
Add recipe for demultiplex 1.2.2.
----
<details> …
> Add recipe for demultiplex 1.2.2.

- recipes/kneaddata/meta.yaml
Add dependencies needed for kneaddata_build_database
----
<details> …
> Add dependencies needed for kneaddata_build_database

- recipes/pyopenms/meta.yaml
Update pyopenms recipe for the 3.0.0 release.
----
<details> …
> Update pyopenms to 3.0.0

- recipes/gmap/build.sh
- recipes/gmap/meta.yaml
> Update GMAP to 2023-07-20

- recipes/bioconvert/COPYING
- recipes/bioconvert/meta.yaml
> Update bioconvert to 1.1.1

- recipes/gmwi2/meta.yaml
Update GMWI2 package (https://github.com/danielchang2002/GMWI2) to 1.4
Fixed bug related to generating output.
---- …
> Update GMWI2 to 1.4

- recipes/table2asn/build.sh
- recipes/table2asn/meta.yaml
> Update table2asn to 2023-07-13

- recipes/hhsuite/meta.yaml
> Rebuild hh-suite to allow install with newer python versions

- recipes/bioconductor-genarise/meta.yaml
> build bioconductor-genarise

- recipes/bioconductor-affylmgui/meta.yaml
> bump affylmgui

- recipes/bioconductor-limmagui/meta.yaml
> Build limmagui

- recipes/bioconductor-meb/meta.yaml
> Build bioconductor-meb

- recipes/bioconductor-scmultiome/meta.yaml
> Build bioconductor-scmultiome

- recipes/bioconductor-sctgif/meta.yaml
> Build bioconductor-sctgif

- recipes/planemo/meta.yaml
> Update planemo to 0.75.9

- recipes/dysgu/meta.yaml
> added Mac build to dysgu

- recipes/dimet/meta.yaml
This PR adds the meta.yaml file for dimet generated using grayskull from PyPI
----
<details> …
> add dimet from grayskull

- recipes/r-metadig/bld.bat
- recipes/r-metadig/build.sh
- recipes/r-metadig/meta.yaml
> Add r-metadig

- recipes/viennarna/build.sh
- recipes/viennarna/meta.yaml
Bump to upstream release of ViennaRNA Package 2.6.3
----
<details> …
> Update ViennaRNA to v2.6.3

- recipes/oakvar/meta.yaml
> Update oakvar to 2.9.34

- recipes/referee/build.sh
- recipes/referee/meta.yaml
Add new recipe Referee. Referee is a program to calculate a quality score for every position in a genome assembly. 
---- …
> Add recipe referee

- recipes/bioconductor-preprocesscore/build.sh
- recipes/bioconductor-preprocesscore/meta.yaml
Once again reinstating the preprocesscore fix that keeps getting lost in bulk updates.
See https://github.com/bioconda/bioconda-recipes/pull/39042 for history and phenotype of the error (which is still occurring). 
----
* Please …
> Fix bioconductor-preprocesscore again after bulk update

- recipes/graphbin/meta.yaml
This PR updates [GraphBin](https://github.com/metagentools/GraphBin) (DOI: [10.1093/bioinformatics/btaa180](http://dx.doi.org/10.1093/bioinformatics/btaa180)) to version 1.7.1.
---- …
> Update graphbin to v1.7.1

- recipes/metaxa/meta.yaml
Replace blast with blast-legacy because blastall is needed
----
<details> …
> Replace blast with blast-legacy because blastall is needed

- recipes/snippy/meta.yaml
This PR fixes two bugs:
For vcflib 1.0.9 (similar errors for previous versions, up until build XXX of version 1.0.3):
```
vcfuniq: symbol lookup error: /home/boas/mambaforge/envs/env_snippy/bin/../lib/libvcflib.so.1: undefined symbol: wavefront_align
vcfstreamsort: symbol lookup error: /home/boas/mambaforge/envs/env_snippy/bin/../lib/libvcflib.so.1: undefined symbol: wavefront_align
```
For SnpEff v5.1 (when using an annotated reference genome):
```
ERROR: CDS check file '/home/boas/analysis/test_snippy/test_out/reference/./ref/cds.fa' not found.
ERROR: Protein check file '/home/boas/analysis/test_snippy/test_out/reference/./ref/protein.fa' not found.
ERROR: Database check failed.
```
With these fixes the default bioconda recipe should produce a working snippy installation without …
> Update Snippy - restrict versions of snpeff and vcflib

- recipes/isoquant/meta.yaml
> Update IsoQuant to 3.3.1

- recipes/galah/meta.yaml
Galah is not compatible with dashing >0.4.0 - fixes dashing version. Also fixes fastANI to the version recommended in the galah documentation.
---- …
> Galah - fix versions as not compatible with dashing >0.4.0

- recipes/biobb_flexserv/meta.yaml
> [biobb_flexserv] update 4.0.3

- recipes/biobb_godmd/meta.yaml
> [biobb_godmd] update 4.0.1

- recipes/beav/build.sh
- recipes/beav/meta.yaml
This is an update of beav to version 0.4.5. Some included files have been compressed to save space and the recipe is optimized to mv rather than cp files.
---- …
> Update beav: version 0.4.5

- recipes/bx-python/meta.yaml
> Update bx-python to 0.10.0

- recipes/pbfusion/meta.yaml
Update pbfusion to v0.3.0 since it's not doing it automatically
----
<details> …
> Update pbfusion to v0.3.0

- recipes/marti/build.sh
- recipes/marti/meta.yaml
Added recipe for [MARTi](https://github.com/richardmleggett/MARTi).
----
<details> …
> Add MARTi 0.9.14

- recipes/mob_suite/meta.yaml
- recipes/mob_suite/setup.py.patch
> Update mob_suite to 3.1.5

- recipes/biobb_structure_utils/meta.yaml
> [biobb_structure_utils] update 2023.2

- recipes/bayescode/build.sh
- recipes/bayescode/meta.yaml
> Updated bayescode to v1.2.2

- recipes/gmwi2/meta.yaml
Update GMWI2 to 1.5
Add quality filtration and dependencies
----
<details> …
> Update GMWI2 to 1.5

- recipes/pasa/build.sh
- recipes/pasa/meta.yaml
> Update pasa to 2.5.3

- recipes/augur/meta.yaml
Includes dependency changes¹.
¹ See setup.py in https://github.com/nextstrain/augur/compare/22.1.0...22.2.0
---- …
> Update Augur to 22.2.0

- recipes/bioconductor-structtoolbox/meta.yaml
> Bump StructToolbox to v1.12.2 and add missing dependencies

- recipes/ncbi-datasets-pylib/meta.yaml
> Update ncbi-datasets-pylib to 15.11.0

- recipes/savana/meta.yaml
Fix to autobump PR #42268 
Updating requirements and test commands in meta.yaml
----
<details> …
> Update savana to 1.0.0 - autobump fix

- recipes/bioconductor-structtoolbox/meta.yaml
- recipes/phynteny/meta.yaml
This PR adds [Phynteny](https://github.com/susiegriggo/Phynteny) (PHage sYNTENY) to bionda. Phynteny is a bacteriophage annotation tool and is implemented in python. 
A publication to support Phynteny is currently in preparation. A more detailed description of Phynteny is available [here](https://github.com/susiegriggo/Phynteny/blob/main/README.md). 
---- …
> Add phynteny v0.1.11

- recipes/smallgenomeutilities/meta.yaml
- use asset as source tarball can be bandwitch-limited by GitHub.
- version option now properly supported
---- …
> Update smallgenomeutilities to 0.4.0

- recipes/rmblast/build.sh
- recipes/rmblast/isb-2.14.0+-rmblast.patch
- recipes/rmblast/meta.yaml
> Update rmblast recipe to build on macOS

- recipes/ribotin/meta.yaml
Update ribotin to version 1.1
----
<details>
Everyone …
> Update ribotin to v1.1

- recipes/dicey/meta.yaml
> Update dicey 0.2.6

- recipes/genomedata/meta.yaml
Updates Genomedata to version 1.7.0.
Adds a missing dependency from the autobump bot.
----
<details> …
> Update recipe for Genomedata 1.7.0

- recipes/conifer/build.sh
- recipes/conifer/meta.yaml
Adding recipe for conifer tool
----
<details> …
> add recipe for Conifer tool

- recipes/metasnek/meta.yaml
Add recipe for metasnek
----
<details>
Everyone has …
> Add metasnek v0.0.5

- recipes/snaketool-utils/meta.yaml
Add recipe for snaketool-utils
----
<details> …
> Add snaketool-utils v0.0.3

- recipes/condiga/meta.yaml
This PR adds [`condiga`](https://github.com/metagentools/ConDiGA) to bioconda. ConDiGA (Contigs Directed Gene Annotation) is a taxonomic annotation pipeline for metagenomic data to construct accurate protein sequence databases for deep metaproteomic coverage.
---- …
> Add condiga v0.2.0

- recipes/snakemake-interface-executor-plugins/meta.yaml
> add: snakemake-interface-executor-plugins

- recipes/spclust/build.sh
- recipes/spclust/conda_build_config.yaml
- recipes/spclust/meta.yaml
> Add spclust

- recipes/r-shinyngs/meta.yaml
Just a bump in lieue of autobump (broken for this recipe).
----
<details> …
> bump shinyngs to 1.8.1

- recipes/dsh-bio/meta.yaml
> Update dsh-bio to 2.2.2

- recipes/multiqc/meta.yaml
Bump MultiQC to the new v1.15 release.
----
<details> …
> Update: MultiQC version 1.15 release

- recipes/abismal/meta.yaml
Update abismal to version 3.2.0 and update the libraries required for building and running abismal.
----
<details> …
> Update version and library dependencies

- recipes/easypqp/meta.yaml
> Update easypqp to 0.1.39

- build-fail-blacklist
- recipes/bioconductor-bambu/meta.yaml
> Build bioconductor-bambu

- build-fail-blacklist
- recipes/bioconductor-bayesspace/meta.yaml
> Build bioconductor-bayesspace

- recipes/iqtree/build.sh
- recipes/iqtree/meta.yaml
> Update iqtree to 2.2.2.9

- build-fail-blacklist
- recipes/bioconductor-flames/meta.yaml
> Build r-xgboost failures

- recipes/savana/meta.yaml
adding matplotlib dependency to resolve build errors in #42338
----
<details> …
> Update savana to 1.0.3 - autobump dependency fix

- recipes/skder/meta.yaml
Update skder to include wget in run dependencies in case it is unavailable. 
----
<details> …
> Update skder meta.yaml to include wget in run dependencies

- recipes/igvtools/build.sh
- recipes/igvtools/igvtools.sh
- recipes/igvtools/meta.yaml
Update IGVtools version
----
<details>
Everyone has …
> Update IGVtools version

- recipes/igv/meta.yaml
Update IGV version
----
<details>
Everyone has access …
> Update IGV version

- build-fail-blacklist
> Build bioconductor-singlecelltk

- .github/PULL_REQUEST_TEMPLATE.md
Removed the description of the depreciated "@BiocondaBot please merge" command
----
<details> …
> Update PR template: squash and merge

- recipes/seqkit/meta.yaml
- [SeqKit v2.5.1](https://github.com/shenwei356/seqkit/releases/tag/v2.5.1) - 2023-08-09 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.5.1/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.5.1)
- `seqkit stats`:
- **fix a concurrency bug (file name error) introduced in v2.5.0**. [#405](https://github.com/shenwei356/seqkit/issues/405)
- `seqkit subseq`:
- sequence/chromosome IDs are case-sensitive now. [#400](https://github.com/shenwei356/seqkit/issues/400)
----
* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first word in …
> Update SeqKit to v2.5.1

- recipes/longstitch/meta.yaml
Updating longstitch to version 1.0.5
----
<details> …
> Update longstitch to v1.0.5

- recipes/pyspoa/build.sh
- recipes/pyspoa/meta.yaml
> Update pyspoa to 0.0.10

- recipes/dnmtools/meta.yaml
Update for version 1.3.0 of dnmtools.
----
<details> …
> Update dnmtools version

- recipes/tb_variant_filter/meta.yaml
This updates tb_variant_filter to version 0.4.0, in the process fixing bugs with VCF parsing and updating the MTBSeq mask.
---- …
> Update tb_variant_filter to version 0.4.0

- recipes/matchms/meta.yaml
> Update matchms to 0.21.2

- recipes/ufcg/build.sh
- recipes/ufcg/meta.yaml
Update ufcg to 1.0.5
----
<details>
Everyone has …
> Update ufcg to 1.0.5

- recipes/mimseq/meta.yaml
> Update mimseq to 1.3.6

- recipes/trackplot/meta.yaml
add flask as new requirement to trackplot
----
<details> …
> Update trackplot to 0.3.2 and add flask in requirements

- recipes/cptac/meta.yaml
> Update cptac to 1.5.0

- recipes/verkko/meta.yaml
- recipes/verkko/run_test.sh
- recipes/verkko/tips.patch
- recipes/verkko/version.patch
Also fixes OSX support, adds dependencies missing in v1.4, and expand tests to be more comprehensive (to catch the missing dependencies in future)
> Update verkko to v1.4.1

- recipes/pgenlib/meta.yaml
This adds the Pgenlib package to Bioconda, in response to https://github.com/chrchang/plink-ng/issues/228 .
---- …
> Add Pgenlib

- recipes/r-panther/build.sh
- recipes/r-panther/meta.yaml
Add new [r-panther](https://r.acidgenomics.com/packages/panther/) recipe, which is an R package for downloading annotations from the PANTHER database.
---- …
> Add r-panther 0.4.0

- recipes/iqtree/meta.yaml
> Update iqtree to 2.2.3

- recipes/lrtk/meta.yaml
update lrtk v1.5 to lrtk v1.6
----
<details> …
> Update  the lrtk recipes

- recipes/rsv-typer/meta.yaml
Update rsv-typer 0.1.0 to 0.2.0
----
<details> …
> Update rsv-typer to 0.2.0

- recipes/r-eggnog/build.sh
- recipes/r-eggnog/meta.yaml
Add new [r-eggnog](https://r.acidgenomics.com/packages/eggnog/) recipe, which downloads annotations from the EggNOG database.
---- …
> Add r-eggnog 0.2.2

- recipes/sdeper/LICENSE
- recipes/sdeper/meta.yaml
add sdeper v1.0.0 to bioconda
home page of sdeper is https://az7jh2.github.io/SDePER/
documents in https://sdeper.readthedocs.io/en/latest/
our paper is still under preparation
----
* Please post …
> add sdeper v1.0.0

- recipes/csvtk/meta.yaml
- [csvtk v0.27.0](https://github.com/shenwei356/csvtk/releases/tag/v0.27.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.27.0/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.27.0)
- `csvtk`:
- code refactoring and simplifying code, with 16% less code.
- **most commands support open column range syntax**, e.g.,  `csvtk grep -f 2-`. [#120](https://github.com/shenwei356/csvtk/issues/120)
- **only selected column names are not allowed to be duplicated in the input data**: box, corr, filter, filter2, fold, freq, gather, historysort, inter, join, line, mutate, mutate2, rename, replace, sep, split, summary, unfold, uniq, watch. Other commands do not have the restriction. …
> Update csvtk to v0.27.0

- recipes/graphanalyzer/meta.yaml
> Update meta.yaml to include dataclasses

- recipes/metamobilepicker/meta.yaml
Updating MetaMobilePicker to new version, adding dependency
> Update Metamobilepicker to version 0.7.3

- recipes/r-bcbiobase/meta.yaml
- recipes/sativa/build.sh
- recipes/sativa/meta.yaml
> Add sativa

- recipes/piper/meta.yaml
> Update piper to 0.13.2

- recipes/spaln/meta.yaml
> Update spaln to 2.4.13g

- recipes/csvtk/meta.yaml
- [csvtk v0.27.1](https://github.com/shenwei356/csvtk/releases/tag/v0.27.1) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.27.1/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.27.1)
- `csvtk filter2/mutate2`:
- fix the bug of selecting with field numbers. [#242](https://github.com/shenwei356/csvtk/issues/242)
---- …
> Update csvtk to v0.27.1

- recipes/jalview/meta.yaml
Update Jalview to 2.11.2.7
----
<details> …
> Update Jalview to 2.11.2.7

- recipes/dnaapler/meta.yaml
Manual PR required as BLAST version needs to be >=2.10 (2.9 breaks dnaapler).
Please ignore #42550
---- …
> Update dnaapler to v0.3.0

- recipes/captus/meta.yaml
- Last time `perl` had problems during building, hopefully this will fix the installation and allow the upgrade to Captus v0.9.95
---- …
> Update perl dependencies for Captus

- recipes/taxonkit/meta.yaml
- [TaxonKit v0.15.0](https://github.com/shenwei356/taxonkit/releases/tag/v0.15.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/taxonkit/v0.15.0/total.svg)](https://github.com/shenwei356/taxonkit/releases/tag/v0.15.0)
- `taxonkit reformat`:
- For lineages with more than one node, if it fails to query TaxId with the parent-child pair, use the last child only. [#82](https://github.com/shenwei356/taxonkit/issues/82)
- The flag `-T/--trim` also does not add the prefix for missing ranks lower than the current rank. [#82](https://github.com/shenwei356/taxonkit/issues/82)
- New flag `-s/--miss-rank-repl-suffix` to set the suffix for estimated taxon names. [#85](https://github.com/shenwei356/taxonkit/issues/85)
----
Please read …
> Update TaxonKit to v0.15.0

- recipes/csvtk/meta.yaml
- [csvtk v0.27.2](https://github.com/shenwei356/csvtk/releases/tag/v0.27.2) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.27.2/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.27.2)
- `csvtk pretty`:
- fix the bug of empty first row with `-H/--no-header-row`, introduced in v0.27.0.
- new style `3line` for three-line table.
- `csvtk csv2xlsx`:
- binaries compiled with go1.21 would result in a broken xlsx file. [#243](https://github.com/shenwei356/csvtk/issues/243)
- `csvtk splitxlsx`:
- fix the error of `invalid worksheet index`. [#1617](https://github.com/qax-os/excelize/issues/1617)
----
Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) …
> Update csvtk to v0.27.2

- recipes/aviary/meta.yaml
Update Aviary to v0.7.0
----
<details>
Everyone has …
> Update Aviary to v0.7.0

- recipes/kmd_hmdb_api_client/LICENSE.md
- recipes/kmd_hmdb_api_client/meta.yaml
Adding a Python3 package that implements a client for the KMD HMDB Database: kmd_hmdb_api_client.
----
<details> …
> Add KMD HMDB API Client tool

- recipes/msgf_plus/meta.yaml
@bernt-matthias [AFAIK](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#:~:text=%3C%2C%20%3E%2C%20%3C%3D%2C%20%3E%3D%2C%20%3D%3D%2C%20and%20!%3D%20are%20relational%20operators%20on%20versions%2C%20which%20are%20compared%20using%20PEP%2D440.%20For%20example%2C%20%3C%3D1.0%20matches%200.9%2C%200.9.1%2C%20and%201.0%2C%20but%20not%201.0.1.%20%3D%3D%20and%20!%3D%20are%20exact%20equality.) "<= 17" means 16.8, 16.9, up to 17.0 but not 17.0.3 (Which is the only 17 version on conda-forge)
Also, the README says: Releases after April 2019 support Java 11 and newer; older releases will not work with Java 11 or newer (at least for reading mzML files) due to the deprecation and removal of some built-in libraries.
So why not put ">=11" which I propose here?
----
Please …
> [msgf_plus] fix jdk reqs

- recipes/pxblat/meta.yaml
> Update pxblat to 0.3.1

- recipes/clair3/meta.yaml
> update clair3 in the same release

- recipes/captus/meta.yaml
- The latest Bioconda build for macOS for MEGAHIT has compilation errors, here we point to a functional build
---- …
> Update specific MEGAHIT build for macOS

- recipes/learnmsa/meta.yaml
Let bioconda know all new requirements introduced with version 1.3.0 of the learnMSA package.
> Update dependencies for learnMSA v1.3.0

- recipes/piscem/meta.yaml
> Bump piscem to v0.6.2

- recipes/ganon/meta.yaml
Update ganon to 1.8.0
----
<details>
Everyone has …
> Update ganon to 1.8.0

- recipes/somalier/build.sh
- recipes/somalier/meta.yaml
see above. Previously, just the binary was downloaded for the linux case.
----
<details> …
> build somalier from source and properly download source file

- recipes/tabixpp/meta.yaml
see code
----
<details>
Everyone has access to the …
> fix: add run_exports to tabixpp

- recipes/wfa2-lib/meta.yaml
> fix: add run_exports to wfa2-lib

- recipes/captus/meta.yaml
- Trying to get the syntax right to point to a specific build of MEGAHIT for macOS
---- …
> Update recipe syntax for a specific build of MEGAHIT in macOS

- recipes/vcflib/backport_pr_394.patch
- recipes/vcflib/build.sh
- recipes/vcflib/meta.yaml
- recipes/vcflib/shared_lib.patch
CI run has to be triggered after https://github.com/bioconda/bioconda-recipes/pull/42671 has been merged and propagated into the bioconda CDN.
---- …
> bump vcflib and add test for vcfstreamsort

- recipes/psm-utils/meta.yaml
Update psm_utils to 0.4.1. Auto-bump did not seem to be working for the last few versions.
----
<details> …
> Update psm_utils to 0.4.1

- recipes/blast/build.sh
- recipes/blast/meta.yaml
Update BLAST from 2.14.0 to 2.14.1.
Also an attempt to see if I can reduce the Linux release artefact size again to the ~25MB it was before.
---- …
> Update blast to 2.14.1

- recipes/ntedit/meta.yaml
Updating ntedit to v1.4.3
Note that in this PR, we are now updating to 1.4.3 instead of 1.4.2 because a bug in compilation for mac was found in 1.4.2
---- …
> Update ntedit to 1.4.3

- recipes/pygenomeviz/meta.yaml
Update pygenomeviz v0.4.1 to v0.4.2. Fix previous autobump PR #42686.
----
<details> …
> Update pygenomeviz to 0.4.2

- recipes/mtbseq/meta.yaml
- recipes/riblast/meta.yaml
Add RIblast v1.2.0
----
<details>
Everyone has access …
> Add RIblast

- recipes/pyrodigal/meta.yaml
> Update pyrodigal recipe to build on separate python versions

- recipes/lrtk/meta.yaml
update lrtk1.6 to 1.7 and fix some bugs
----
<details> …
> update lrtk1.6 to 1.7

- recipes/dnamarkmaker/LICENSE.txt
- recipes/dnamarkmaker/build.sh
- recipes/dnamarkmaker/meta.yaml
- recipes/r-bcbiornaseq/meta.yaml
> Add DNAMarkMaker

- recipes/happy-python/LICENSE
- recipes/happy-python/meta.yaml
> Add recipe for HapPy-python v0.2.1rc0

- recipes/ms-entropy/meta.yaml
> Add ms-entropy recipe

- recipes/pharokka/build.sh
- recipes/pharokka/meta.yaml
Pharokka updated to v1.4.0. Adds some dependencies and simplifies installation with pip (no need for build.sh).
---- …
> Update pharokka to v1.4.0

- recipes/aviary/meta.yaml
> Update Aviary to v0.7.2

- recipes/piscem/meta.yaml
> Bump piscem to v0.6.3

- recipes/pbmm2/meta.yaml
> Update PacBio `pbmm2` version 1.13.0

- recipes/rbpbench/meta.yaml
Add new bioconda recipe for rbpbench ( https://github.com/michauhl/RBPBench )
---- …
> add rbpbench meta yaml

- recipes/dnaapler/meta.yaml
Fixes the listing error in #42749 by adding the version pin with run_exports
Please close #42749
---- …
> update dnaapler to v0.3.1

- recipes/mimseq/meta.yaml
> Update mimseq gmap dependency

- recipes/noah-cli/meta.yaml
Add noah-cli: a project management tool for reproducible, portable, and streamlined bioinformatics analysis.
---- …
> Add noah-cli

- recipes/auspice/meta.yaml
Release notes: https://github.com/nextstrain/auspice/releases/tag/v2.48.0
---- …
> Upgrade Auspice to v2.48.0

- recipes/vcflib/build.sh
- recipes/vcflib/meta.yaml
> Update vcflib to build on OSX

- recipes/snakemake-interface-common/meta.yaml
> Add recipe for snakemake-interface-common v1.3.2

- recipes/biobb_common/meta.yaml
> [biobb_common] update 4.1.0

- recipes/sentieon/meta.yaml
> Update Sentieon recipe to 202308

- recipes/cojac/meta.yaml
This bumps COJAC v0.9 --> v.0.9.1
Minor bug fix, and UX improvements.
---- …
> Update: bump COJAC up to 0.9.1

- recipes/actc/meta.yaml
> Update actc to version 0.5.0

- recipes/pywfa/meta.yaml
> more pywfa fixes

- recipes/biobb_amber/meta.yaml
> [biobb_amber] update 4.1.0

- recipes/biobb_chemistry/meta.yaml
> [biobb_chemistry] update 4.1.0

- recipes/biobb_io/meta.yaml
> [biobb_io] update 4.1.0

- recipes/guidescan/meta.yaml
Update Guidescan to v2.1.7
---- …
> Update Guidescan to v2.1.7

- recipes/rich-msa/meta.yaml
This PR adds a recipe for [`rich-msa`](https://github.com/althonos/rich-msa), by @althonos.
---- …
> Add rich-msa

- recipes/taxtastic/meta.yaml
Adding requirements as per https://github.com/fhcrc/taxtastic/blob/master/setup.py
Was seeing import errors (specifically sqlparse, but here adding all the official dependencies)
---- …
> taxtastic: Update deps.

- recipes/dnmtools/meta.yaml
Update: this PR is just a rebuild for dnmtools. I also added a `pin_subpackage` to the `meta.yaml` and set `max_pin` to `x.x` because currently we can't guarantee stability between minor versions.
---- …
> dnmtools update

- recipes/poseidon-trident/meta.yaml
I also added the `run_exports` field to the recipe. `poseidon-trident` uses [Haskell PVP](https://pvp.haskell.org), which is similar, but not identical to SemVer. I think that means I can only set `max_pin=None`.
----
* Please …
> Update poseidon-trident to v1.3.0.4

- recipes/biobb_analysis/meta.yaml
> [biobb_analysis] update 4.1.0

- recipes/biobb_vs/meta.yaml
> [biobb_vs] update 4.1.0

- recipes/biobb_gromacs/meta.yaml
> [biobb_gromacs] update 4.1.0

- recipes/cmsearch_tblout_deoverlap/build.sh
- recipes/cmsearch_tblout_deoverlap/meta.yaml
- recipes/cmsearch_tblout_deoverlap/run_test.sh
This PR is to include https://github.com/nawrockie/cmsearch_tblout_deoverlap/, this is perl script that removes lower scoring overlaps from cmsearch v1.1x --tblout files.
---- …
> Add cmsearch_tblout_deoverlap

- recipes/snakemake/meta.yaml
See: https://snakemake.readthedocs.io/en/stable/project_info/history.html
---- …
> Restore Python v to >=3.7

- recipes/biobb_cp2k/meta.yaml
> [biobb_cp2k] update 4.1.0

- recipes/biobb_godmd/meta.yaml
> [biobb_godmd] update 4.1.0

- recipes/biobb_dna/meta.yaml
> [biobb_dna] update 4.1.0

- recipes/biobb_ml/meta.yaml
> [biobb_ml] update 4.1.0

- recipes/tcdemux/meta.yaml
> add tcdemux

- recipes/varscan/meta.yaml
- recipes/varscan/varscan.sh
Update Varscan version to 2.4.6
Increase starting Varscan Java mem allocations 2x
---- …
> Update Varscan version and increase java mem

- recipes/ntjoin/meta.yaml
Updating ntJoin to v1.1.2
* Remove btllib version constraint
* Add run_exports
---- …
> Update ntjoin to 1.1.2

- recipes/jvarkit/build.sh
- recipes/jvarkit/dispatcher.sh
- recipes/jvarkit/jvarkit.sh
- recipes/jvarkit/meta.yaml
This is a _**new**_ recipe for jvarkit:
- A big change in recent versions of jvarkit, is that it changed from separate per-tool commands and jars (as in the old jvarkit-* bioconda packages)  to a single central dispatcher.
i.e.: you don't run `bamstat04` anymore  like in package [jvarkit-bamstat04](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/jvarkit-bamstat04), now you run `jvarkit bamstat04` as [per latest docs](https://jvarkit.readthedocs.io/en/latest/BamStats04/)
I've [added a bunch of symlinked wrappers](https://github.com/bioconda/bioconda-recipes/compare/master...DrYak:update_jvarkit?expand=1#diff-18982b6f24756c6572d90352581041f61cf00072dee2afc9adae9d16f31f61aeR23) for the old-style single commands, so hopefully people who relied on the old _jvarkit-\*_ packages …
> Add jvarkit (the new toolkit with central dispatcher)

- build-fail-blacklist
- recipes/microbecensus/2to3.patch
- recipes/microbecensus/meta.yaml
This PR adds a patch to the [MicrobeCensus](https://github.com/snayfach/MicrobeCensus/) recipe to allow it to be used in Python 3 environments.
---- …
> Apply 2to3 patch to MicrobeCensus

- recipes/psiclass/meta.yaml
It is required for fixing this problem I think:
`/usr/local/bin/junc: error while loading shared libraries: libz.so.1: cannot open shared object file`
---- …
> Update PsiCLASS dependencies

- recipes/r-mytai/meta.yaml
> Update myTAI description

- recipes/gw/meta.yaml
> Added versions to dependencies for GW

- recipes/dysgu/meta.yaml
> Added versions for some dependencies to dysgu

- recipes/meme/meta.yaml
> Update meme to 5.5.4

- recipes/foldseek/meta.yaml
> Update Foldseek to release 8

- recipes/gimbleprep/build.sh
- recipes/gimbleprep/meta.yaml
> gimbleprep recipe

- recipes/tracknado/meta.yaml
> Add recipe for tracknado v0.2.3

- recipes/ntjoin/meta.yaml
> Update ntjoin to 1.1.3

- recipes/biobb_structure_utils/meta.yaml
> [biobb_structure_utils] update 4.1.0

- recipes/vsnp3/meta.yaml
> vsnp3 version 3.15

- recipes/ngsngs/build.sh
- recipes/ngsngs/meta.yaml
Update build to also compile `misc` tools.
---- …
> Update ngsngs to compile misc tools

- recipes/lrtk/meta.yaml
> update lrtk to 1.8

- recipes/biobb_cmip/meta.yaml
> [biobb_cmip] update 4.1.0

- recipes/biobb_vs/meta.yaml
> [biobb_vs] update 4.1.1

- recipes/biobb_model/meta.yaml
> [biobb_model] update 4.1.0

- recipes/trackplot/meta.yaml
- the auto bump lint failed, add `run_exports` in build section manually 
----
Conda is …
> update trackplot to v0.3.5, add run_exports to build section

- recipes/star/meta.yaml
> Update star to 2.7.11a

- recipes/spaln/makefile.patch
- recipes/spaln/meta.yaml
- recipes/spaln/patch-makefile_ldflags
> Update spaln to 3.0.0

- recipes/iqtree/meta.yaml
> Update iqtree to 2.2.5

- recipes/ale-core/build.sh
- recipes/ale-core/conda_build_config.yaml
- recipes/ale-core/meta.yaml
The bioconda installation of ALE (https://github.com/sc932/ALE) is broken
When you try and install ALE as follows:
`conda install -c bioconda ale`
v0.9.1 is downloaded but nothing is actually installed (i.e. ALE isn't actually executable).
If you try and specifically install the last update, it requires a deprecated version of matplotlib.:
```
conda install -c bioconda ale==20180904
```
```
The following package could not be installed
└─ ale 20180904  is uninstallable because it requires
└─ pymix  , which requires
└─ matplotlib >=1.1.0,!=1.4.2,<1.5.0 , which does not exist (perhaps a missing channel).
```
I don't know enough about the conda ecosystem to know how easy it is easier to fix this error.
However, for my own (and I imagine others') purpose, the …
> Issues with ale bioconda package /Add ale-core as alternative if it can be fixed

- recipes/magus-msa/meta.yaml
- recipes/magus/meta.yaml
Adds [MAGUS](https://github.com/vlasmirnov/MAGUS) to bioconda.
> add magus-msa

- build-fail-blacklist
- recipes/expansionhunter/0001-adjust-cmake-targets.patch
- recipes/expansionhunter/0002-specify-boost-for-make_unique.patch
- recipes/expansionhunter/0003-add-missing-limits-import.patch
- recipes/expansionhunter/0004-add-fmt-formatters-for-classes.patch
- recipes/expansionhunter/0005-apply-bioconda-4.0.2-patches.patch
- recipes/expansionhunter/LICENSE.txt
- recipes/expansionhunter/build.sh
- recipes/expansionhunter/conda_build_config.yaml
- recipes/expansionhunter/meta.yaml
This PR updates the blacklisted expansionhunter recipe to v5.0.0. The following changes are implemented:
- all dependencies managed by cmake are disabled in favor of conda management
- abseil is still built, as that's it's model
- in-repo third party utilities still get compiled, but they're relatively small
- boost, abseil, htslib runtimes pinned to build
- patches are restructured to match v5.0.0 file layout
- dependencies are set to minima corresponding to versions in package's CMakeLists
- C++ 2014 standard is enabled to make compatible with current boost
- patches added for function scoping to make 2014 compatible
- seemingly to make compatible with modern spdlog/fmt, formatting handlers are added for two classes
- abseil is pinned to exactly the version from the package's internal …
> Update expansionhunter to v5.0.0

- recipes/olivar/meta.yaml
Olivar is migrated from GitLab to GitHub
---- …
> Update source of Olivar v1.1.2

- recipes/dbcanlight/meta.yaml
This PR adds recipe for dbcanlight package, a lightweight version rewrite of run_dbcan. dbcanlight use pyhmmer hmmsearch instead of cli version hmmscan to accelerate the searching process.
---- …
> Add dbcanlight 1.0.0

- recipes/pyrodigal/meta.yaml
Bump `pyrodigal` to `v3.0.0`.
---- …
> Update `pyrodigal` to `v3.0.0`

- recipes/marker-magu/meta.yaml
PR to add `Marker-MAGu`, a Trans-Kingdom Marker Gene Pipeline for Taxonomic Profiling of Human Metagenomes.
https://github.com/cmmr/Marker-MAGu
---- …
> Add marker-magu v0.4.0

- recipes/biobb_pmx/meta.yaml
> [biobb_pmx] update 4.1.0

- recipes/solote/meta.yaml
> solote v1.08

- recipes/perl-retroseq/meta.yaml
Retroseq needs a specific version of samtools to function, it currently fails to complete and gives an error about samtools.
---- …
> update retroseq: samtools requirements

- recipes/pixelator/meta.yaml
Add a new package for pixelator (0.13.1).
Pixelator is a command-line tool and library to process and analyze sequencing data from Molecular Pixelation (MPX) assays.
GitHub: https://github.com/PixelgenTechnologies/pixelator
PyPI: https://pypi.org/project/pixelgen-pixelator/
---- …
> Add new recipe for pixelator

- recipes/ganon/meta.yaml
> Update ganon to 1.9.0

- recipes/monsda/meta.yaml
> dep fixes, build bump

- recipes/gmap/build.sh
- recipes/gmap/meta.yaml
> Patch gmap recipe

- recipes/kingfisher/meta.yaml
Update kingfisher to v0.3.0
---- …
> Update kingfisher to v0.3.0

- recipes/flexiplex/meta.yaml
Hi, this change updates the checksum of the release .tar.gz due to a minor change which was made.
----
<details>
<summary>
Please read the guidelines for Bioconda recipes before opening a pull request (PR).
</summary> …
> Update/fix flexiplex 0.97.1

- recipes/daligner/build.sh
- recipes/daligner/meta.yaml
Update daligner to v1.0.20230620
---- …
> Update daligner 1.0.20230620

- recipes/seqfu/build.sh
- recipes/seqfu/meta.yaml
> [seqfu] update building script

- recipes/orfanage/meta.yaml
Updates ORFanage software to the next major release 1.1.0.
---- …
> update orfanage to 1.1.0

- recipes/nextstrain-cli/meta.yaml
Includes dependency updates that will not be in the autobump PR. 
---- …
> Update nextstrain-cli to 7.3.0.post1

- recipes/csvtk/meta.yaml
- [csvtk v0.28.0](https://github.com/shenwei356/csvtk/releases/tag/v0.28.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.28.0/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.28.0)
- `csvtk`:
- add the shortcut `-X` for the flag `--infile-list`. [#249](https://github.com/shenwei356/csvtk/issues/249)
- `csvtk pretty`:
- support field ranges for `-m/--align-center` and `-r/--align-right`. [#244](https://github.com/shenwei356/csvtk/issues/244)
- `csvtk spread`:
- support values sharing the same keys. [#248](https://github.com/shenwei356/csvtk/issues/248)
- `csvtk join`:
- a new flag `-P/--prefix-duplicates`: add filenames as colname prefixes only for duplicated colnames. …
> Update csvtk to v0.28.0

- recipes/augur/meta.yaml
Dependency changes in setup.py: https://github.com/nextstrain/augur/compare/23.0.0...23.1.0
---- …
> Update augur to 23.1.0

- recipes/rgi/meta.yaml
> Update rgi to 6.0.3

- recipes/dnoise/meta.yaml
Add recipe `dnoise` for [DnoisE](https://github.com/adriantich/DnoisE) authored by @adriantich for denoising of protein-coding metabarcode sequences.
---- …
> Add recipe dnoise

- recipes/goldrush/meta.yaml
> update goldrush to 1.1.0

- recipes/pneumo-typer/build.sh
- recipes/pneumo-typer/meta.yaml
> add pneumo-typer recipes

- recipes/prokka/meta.yaml
> prokka: Licence fix / run_exports

- recipes/metaprokka/meta.yaml
> Update requirements for metaprokka

- recipes/metadmg/meta.yaml
> Update metadmg wrapper with openssl lib

- recipes/pantools/meta.yaml
This PR updates the PanTools recipe to its most recent version v4.2.3
> update pantools to 4.2.3

- recipes/versionix/meta.yaml
> Add recipe for versionix v0.2.0

- recipes/singlem/meta.yaml
> update SingleM dependencies

- recipes/viennarna/meta.yaml
Upgrade to upstream release v2.6.4
---- …
> Update ViennaRNA Package to 2.6.4

- recipes/tissuumaps/meta.yaml
Add a recipe for TissUUmaps
----
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see …
> Add TissUUmaps

- recipes/ice-cream/build.sh
- recipes/ice-cream/meta.yaml
> add ice-cream

- recipes/auspice/meta.yaml
> Update auspice to 2.49.0

- recipes/meryl/meta.yaml
> Update meryl to 1.4.1

- recipes/guidescan/meta.yaml
Update Guidescan to v2.1.8
---- …
> Update Guidescan to v2.1.8

- recipes/minimap2/build.sh
- recipes/minimap2/meta.yaml
Update minimap2: add library (currently static library only, libminimap2.a) and header files, for tools that want to use minimap2's API.
---- …
> Update minimap2:  add library and headers

- recipes/goldrush/meta.yaml
Add dependency `bc` - required to use docker image
---- …
> update goldrush 1.1.0 build

- recipes/plink2/meta.yaml
Updating plink2 to the latest major build.
> Update plink2 to version alpha 5

- recipes/dupsifter/build.sh
- recipes/dupsifter/meta.yaml
- recipes/dupsifter/patch
Add new recipe for [dupsifter](https://github.com/huishenlab/dupsifter) to bioconda.
---- …
> Add dupsifter

- recipes/dbcanlight/meta.yaml
This PR update the package dbcanlight to v1.0.1 to fix a bug in substrate detection mode.
---- …
> Update dbcanlight to v1.0.1

- recipes/olivar/meta.yaml
> Update home url

- recipes/nf-test/meta.yaml
> Update nf-test to v0.8.0

- recipes/deeptools/meta.yaml
Update dependencies for deeptools
---- …
> Update dependencies for deeptools

- recipes/viralmsa/build.sh
- recipes/viralmsa/meta.yaml
This PR adds ViralMSA v1.1.35 to bioconda.
---- …
> Add ViralMSA v1.1.35

- recipes/graftm/meta.yaml
> Fix GraftM update PR

- recipes/ice-cream/build.sh
- recipes/ice-cream/meta.yaml
> update ice-cream recipe

- recipes/slow5tools/1.0.0/build.sh
- recipes/slow5tools/1.0.0/meta.yaml
- recipes/slow5tools/meta.yaml
update slow5tools to 1.1.0
---- …
> update slow5tools to 1.1.0

- recipes/f5c/1.2/build.sh
- recipes/f5c/1.2/meta.yaml
- recipes/f5c/meta.yaml
Update f5c to version 1.3
---- …
> update f5c to 1.3

- recipes/peptide-shaker/meta.yaml
- recipes/peptide-shaker/peptide-shaker.py
> Update peptide-shaker to 3.0.0

- recipes/gmwi2/meta.yaml
Add the GMWI2 (Gut Microbiome Wellness Index 2) package hosted here: https://github.com/danielchang2002/GMWI2
---- …
> :hankey: add GMWI2 package

- recipes/physiofit/meta.yaml
Changed the openpyxl dependency to a lower version
---- …
> Made change to openpyxl version requirement

- recipes/dsh-bio/meta.yaml
> Update dsh-bio to 2.3

- recipes/hictk/build.sh
- recipes/hictk/conanfile.txt.patch
- recipes/hictk/meta.yaml
> Update hictk to v0.0.3

- recipes/svjedi-graph/meta.yaml
New version of SVJedi-graph (v1.2.1)
---- …
> Update recipe for new version of SVJedi-graph v1.2.1

- recipes/pbsim3/build.sh
- recipes/pbsim3/meta.yaml
Add pbsim3, a simulator for PacBio and Oxford Nanopore long reads
---- …
> Add pbsim3, a simulator for PacBio and Oxford Nanopore long reads

- recipes/bcftools/meta.yaml
Update bcftools; supersedes #42167.
---- …
> Update to two months ago's bcftools 1.18 release

- recipes/amplisim/build.sh
- recipes/amplisim/meta.yaml
- recipes/amplisim/run_test.sh
> Add initial commit for amplisim

- recipes/sharg/build.sh
- recipes/sharg/meta.yaml
- recipes/sharg/patch
- recipes/sharg/run_test.sh
Add sharg, the argument parser for bio-c++ tools from the seqan3 library
---- …
> Add sharg, the argument parser for bio-c++ tools from the seqan3 library

- recipes/gogstools/meta.yaml
https://github.com/genouest/ogs-tools
---- …
> Add gogstools

- recipes/tandem-genotypes/meta.yaml
New version; add lamassemble dependency
---- …
> new tandem-genotypes

- recipes/samtools/meta.yaml
Bump build number to rebuild this with the corresponding htslib, as unfortunately PR #43283 was merged using stale artifacts built months before the recent removal of htslib pinning (as released in bioconda/bioconda-utils#920). A properly built samtools-1.18 executable contains burnt-in macros and inline functions from the htslib-1.18 headers, but the existing samtools-1.18-0 has these burnt in from htslib-1.17 — running such an executable against a shared libhts-1.18 helps, but cannot avoid deficiencies from the outdated burnt-in macro and inline code.
PR #43251 added a conservative `run_exports` section without presenting any evidence. This PR also probably fixes that: samtools does not have an API, and its maintainers treat its command-line compatibility seriously (carefully managed …
> Rebuild samtools using an up-to-date htslib

- recipes/searchgui/meta.yaml
- recipes/searchgui/searchgui.py
> Update searchgui to 4.3.1

- recipes/peptide-shaker/meta.yaml
- recipes/peptide-shaker/peptide-shaker.py
> Update peptide-shaker to 3.0.1

- khipu-metabolomics/meta.yaml
> Add khipu metabolomics

- recipes/cascade-config/meta.yaml
> added cascade-config

- recipes/fgsv/meta.yaml
Update the fgsv recipe from 0.0.2 to 0.1.0.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
> Update fgsv recipe to 0.1.0.

- recipes/beagle/build.sh
- recipes/beagle/gpl_license
- recipes/beagle/meta.yaml
Very simple update to most recent version of beagle imputation software. Project is both java and ancient, and so it's a very basic recipe.
---- …
> Update beagle to 5.4

- recipes/biocantor/meta.yaml
Update BioCantor to the latest release (1.1.0)
---- …
> biocantor 1.1.0

- recipes/dimet/meta.yaml
six library demanded during build_test azure pipelines. This should fix the PR blockage v 0.1.4
---- …
> dimet update to 0.1.4: add six library

- recipes/gmap/meta.yaml
> Update GMAP to 2023-10-01

- recipes/olivar/meta.yaml
> Update Olivar source

- recipes/koverage/meta.yaml
New recipe to add the PyPI python package Koverage to bioconda. Koverage is a command-line, snakemake based pipeline for performing read-coverage analysis over multiple samples.
---- …
> Add recipe for Koverage 0.1.6

- recipes/trimnami/meta.yaml
Add recipe for Trimnami 0.1.1. Trimnami is a Snakemake-based command line tool providing wrappers for performing read-trimming on many samples, using different read-trimming tools, with optional extras.
----
* Please post …
> Add recipe for Trimnami version 0.1.1

- recipes/mosdepth/build.sh
- recipes/mosdepth/meta.yaml
Update mosdepth from v0.3.4 to v0.3.5
---- …
> Update mosdepth v0.3.4 -> v0.3.5

- recipes/assemblycomparator2/meta.yaml
Could'n get autobump to work.
---- …
> update assemblycomparator2 v2.5.7

- recipes/rmblast/isb-2.14.1+-rmblast.patch
- recipes/rmblast/meta.yaml
> Update rmblast to 2.14.1

- recipes/pythoncyc/meta.yaml
Add recipe for pythoncyc 2.0.2.
---- …
> Add recipe for pythoncyc 2.0.2.

- recipes/pypolca/meta.yaml
Adds pypolca, Standalone Python re-implementation of the POLCA polisher from MaSuRCA https://github.com/alekseyzimin/masurca.
---- …
> Add pypolca 0.1.1

- recipes/gmap/meta.yaml
> Update GMAP to 2023-10-10

- recipes/tadlib/meta.yaml
###
This PR adds [TADlib](https://github.com/XiaoTaoWang/TADLib) to bioconda
---- …
> Add Tadlib

- recipes/customtkinter/meta.yaml
- recipes/tadlib/meta.yaml
> customtkinter dependency of ms2rescore

- recipes/submission-excel2xml/build.sh
- recipes/submission-excel2xml/meta.yaml
- recipes/submission-excel2xml/patch
I have made a bioconda recipe for submission_excel2xml, which is a tool to generate and validate XML files required for data submission at DNA Data Bank of Japan
---- …
> Add submission_excel2xml

- recipes/vvv2_display/meta.yaml
Add vvv2_display-0.1.10 bioconda recipe
---- …
> Vvv2 display 0.1.10

- recipes/truvari/meta.yaml
> Add missing dependency to truvari

- recipes/chewbbaca/meta.yaml
Update recipe for chewBBACA v3.3.0. Added some imports and FastTree as a dependency.
---- …
> Update chewBBACA recipe.

- recipes/corgi/meta.yaml
Add corgi v0.4.0
cc @rbturnbull
> Add corgi v0.4.0

- recipes/hybracter/meta.yaml
> Add recipe for hybracter v0.1.2

- recipes/rabies/meta.yaml
Adds rabies 0.5.1. RABIES: Rodent Automated Bold Improvement of EPI Sequences 
---- …
> Add Rabies 0.5.1

- recipes/orthoflow/meta.yaml
> Add orthoflow

- recipes/nextflow/meta.yaml
This PR updates nextflow to version 23.10.0
> nextflow 23.10.0

- recipes/assembly_finder/meta.yaml
PR to add [assembly_finder](https://github.com/metagenlab/assembly_finder). 
Assembly finder is a snakemake pipeline for downloading genomes and reports from [NCBI assembly](https://www.ncbi.nlm.nih.gov/assembly).
----
* Please …
> Add recipe for assembly finder

- recipes/snakemake/meta.yaml
> Ensure that Snakemake uses at most Python 3.11 because of breaking changes in Python 3.12

- recipes/zdb/build.sh
- recipes/zdb/meta.yaml
- Update zdb to v1.2.1 
- fix the build.sh script 
- update recipe 
---- …
> Update zdb to v1.2.1

- recipes/nii2dcm/001-version_info.patch
- recipes/nii2dcm/LICENSE
- recipes/nii2dcm/meta.yaml
Add recipe for nii2dcm 0.1.2.
---- …
> Add recipe for nii2dcm 0.1.2.

- recipes/r-shinyngs/meta.yaml
Just bumping version in lieu of autobump
---- …
> Bump shinyngs version to 1.8.4

- recipes/t1dgrs2/meta.yaml
Added authors list to package documentation and updated version number.
---- …
> Expanded docs and updated version

- recipes/snpeff/meta.yaml
Reverts bioconda/bioconda-recipes#43701
> Revert "Update SnpEff"

- recipes/deepdirect/meta.yaml
> update deepdirect to 0.2.5

- recipes/physiofit/meta.yaml
Update Physiofit to 3.2.0
---- …
> Update physiofit to 3.2.0

- recipes/tb-profiler/meta.yaml
Updating pathogen-profiler dependancy version
---- …
> updpate build

- recipes/fgsv/meta.yaml
Update fgsv recipe to 0.1.1
----
<details>
<table>
<tr>
<td><code>@BiocondaBot please …
> Update fgsv to 0.1.1

- recipes/semibin/meta.yaml
Very minor metadata update, changing DOI to point to final manuscript (not preprint).
> Update SemiBin metadata

- recipes/clair3/meta.yaml
> Update Clair3 to use extended base image

- recipes/assembly_finder/meta.yaml
Small patch to restrict python version up to 3.11
---- …
> Update assembly_finder recipe

- recipes/auriclass/meta.yaml
PR to add AuriClass to bioconda. AuriClass is a package to predict clade type based on Candida auris WGS data.
---- …
> Add auriclass

- recipes/taxmyphage/meta.yaml
This PR adds the taxmyPHAGE tool for taxonomic classifiction of bacteriophages.
---- …
> Add taxmyPHAGE recipe

- recipes/syngap/build.sh
- recipes/syngap/meta.yaml
> add syngap recipes

- recipes/bamdash/LICENSE
- recipes/bamdash/meta.yaml
Add bamdash to bioconda. 
Aggregate pathogen NGS results into an interactive plot
---- …
> Add bamdash

- recipes/dnmtools/build.sh
- recipes/dnmtools/meta.yaml
> Update dnmtools: new version 1.4.2

- recipes/mavis-config/meta.yaml
> Add recipe for mavis-config v1.2.2

- recipes/virheat/LICENSE
- recipes/virheat/meta.yaml
Add virheat to bioconda. Visualize and compare multiple vcf files as a heatmap.
---- …
> Add virheat

- recipes/isospecpy/meta.yaml
> added recipe for isospecpy

- recipes/pyopenms/build.sh
- recipes/pyopenms/meta.yaml
Updates pyopenms to 3.1.0
---- …
> Update pyopenms 3.1.0

- recipes/mafft/meta.yaml
> add gawk as run-time dep

- recipes/pixelator/meta.yaml
Update pixelator to 0.15.2.
---- …
> update pixelator to 0.15.2

- recipes/table2asn/meta.yaml
> Update table2asn to 2023-10-05

- recipes/tower-cli/meta.yaml
Update Tower CLI to v0.9.0
---- …
> Update tower-cli to 0.9.0

- recipes/auriclass/build.sh
- recipes/auriclass/meta.yaml
The original auriclass recipe did not include a build.sh script which should have been included. I have added this now and bumped the build number in `meta.yaml`
---- …
> Update auriclass recipe

- recipes/mashtree/meta.yaml
- recipes/profile_dists/meta.yaml
Initial release with pinned version
> profile_dists release 1.0.0

- recipes/genomic_address_service/meta.yaml
First conda release of the genomic address service for biological needs
> gas release v0.1.1

- recipes/pxblat/meta.yaml
The PR Update License info for pxblat
---- …
> Update License info for pxblat

- recipes/bismark/meta.yaml
Update bismark to version 0.24.2
> Update bismark 0.24.2

- recipes/aspera-cli/build.sh
- recipes/aspera-cli/meta.yaml
PR to simplify aspera-cli recipe (removing dso whitelist and ignore run export) and improving build script
----
Conda …
> Update aspera-cli recipe

- recipes/openms-meta/meta.yaml
PepNovoAdapter has been deprecated in 3.1
---- …
> openms: remove pepnovo requirement

- recipes/merquryfk/build.sh
- recipes/merquryfk/meta.yaml
- recipes/merquryfk/patch
> Merqury fk

- recipes/gmap/build.sh
- recipes/gmap/meta.yaml
> Fixing the perl paths for all relevant gmap scripts

- recipes/comebin/build.sh
- recipes/comebin/meta.yaml
add COMEBin recipes
add a conda recipe for COMEBin, a metagenomics contig binner (https://github.com/ziyewang/COMEBin).
> Add COMEBin

- recipes/args_oap/meta.yaml
> update recipe for args_oap

- recipes/bioconductor-rhdf5filters/meta.yaml
This pull request is to follow up on #43930 , and should be merged and uploaded before #43900 .
---- …
> Update bioconductor-rhdf5filters: include run_exports and rebuild after bioconductor-rhdf5lib update

- recipes/psm-utils/meta.yaml
Autobump of psm-utils 0.6.0 -> 0.7.0 did not include novel dependency `pyopenms`. This needs to be added in order to use the full functionality of the package
---- …
> Update psm-utils: Add missing pyopenms dependency

- recipes/severus/build.sh
- recipes/severus/meta.yaml
> Add severus

- recipes/vcf2cytosure/meta.yaml
No biocontainer was generated for the last version of this recipe. This is just a bump in build number to try and generate the artifacts. 
---- …
> build bump

- recipes/biscuit/meta.yaml
Update BISCUIT to new version
---- …
> Update biscuit to v1.3.0

- recipes/bioconductor-rhdf5/meta.yaml
- recipes/gtfparse/meta.yaml
gtfparse: add polars<0.17 as >=0.17 is incompatible
----
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in the recipe.
If not already present in the meta.yaml, make sure to specify `run_exports` (see [here](https://bioconda.github.io/contributor/linting.html#missing-run-exports) for the rationale and comprehensive explanation).
Add a `run_exports` …
> Update:  gtfparse: fix dependency

- recipes/phantasm-xenogi/meta.yaml
Adding a recipe for `phantasm-xenogi`. Currently build works but it is not running. @rpetit3 is going to help me resolve things.
---- …
> Add phantasm-xenogi

- recipes/mbgc/build.sh
- recipes/mbgc/meta.yaml
Update of mbgc recipe (new version of the tool)
---- …
> Update mbgc recipe

- recipes/colabfold/meta.yaml
> Colabfold 1.5.3

- recipes/rmath4/meta.yaml
> Adds Rmath4 library

- recipes/stecfinder/meta.yaml
Update stecfinder to 1.1.1
---- …
> Update stecfinder to 1.1.1

- recipes/pysais/meta.yaml
> Add pysais library

- recipes/ucsc-chainscore/build.sh
- recipes/ucsc-chainscore/include.patch
- recipes/ucsc-chainscore/meta.yaml
- recipes/ucsc-chainscore/run_test.sh
Adds chainScore, part of the UCSC kent utils. chainScore is one of three UCSC kent utils required for Hiller lab's [make_lastz_chains](https://github.com/hillerlab/make_lastz_chains) pipeline but not yet available on bioconda (there are nine UCSC kent utils are required *and* available on bioconda).
----
* PRs require reviews prior to being merged. Once your PR is passing tests and …
> Add ucsc-chainscore

- recipes/ucsc-pslsortacc/build.sh
- recipes/ucsc-pslsortacc/include.patch
- recipes/ucsc-pslsortacc/meta.yaml
- recipes/ucsc-pslsortacc/run_test.sh
Adds pslSortAcc, part of the UCSC kent utils. pslSortAcc is one of three UCSC kent utils required for Hiller lab's [make_lastz_chains](https://github.com/hillerlab/make_lastz_chains) pipeline but not yet available on bioconda (there are nine UCSC kent utils are required *and* available on bioconda).
----
* PRs require reviews prior to being merged. Once your PR is passing tests and …
> Add ucsc-pslsortacc

- recipes/ucsc-chaincleaner/build.sh
- recipes/ucsc-chaincleaner/include.patch
- recipes/ucsc-chaincleaner/meta.yaml
- recipes/ucsc-chaincleaner/run_test.sh
Adds chainCleaner, part of the UCSC kent utils. chainCleaner is one of three UCSC kent utils required for Hiller lab's [make_lastz_chains](https://github.com/hillerlab/make_lastz_chains) pipeline but not yet available on bioconda (there are nine UCSC kent utils are required *and* available on bioconda).
----
* PRs require reviews prior to being merged. Once your PR is passing tests …
> Add ucsc-chaincleaner

- recipes/dwgsim/meta.yaml
> Update dwgsim to 1.1.14

- recipes/cafe/meta.yaml
> Update CAFE to 5.1

- recipes/syngap/build.sh
- recipes/syngap/meta.yaml
> update syngap recipes

- recipes/orthofisher/meta.yaml
> Add recipe for orthofisher v1.1.0

- recipes/gfftk/meta.yaml
> Add recipe for gfftk v23.9.6

- build-fail-blacklist
- recipes/ucsc-chainsort/include.patch
- recipes/ucsc-chainsort/meta.yaml
Updates ucsc-chainsort of the UCSC kent utils from version 377 to 455. This also triggers a rebuild, to update the openssl version, because it is otherwise incompatible with more recently built kent utils.
There are two other PRs that I opened in parallel to this one, which have very similar changes: #44039 and #44040.
---- …
> Update ucsc-chainsort from 377 to 455

- recipes/mtm-align/build.sh
- recipes/mtm-align/meta.yaml
Adds mTM-align (https://doi.org/10.1093/bioinformatics/btx828 / http://yanglab.nankai.edu.cn/mTM-align/)
> add mTM-align

- recipes/r-ldweaver/meta.yaml
Adding a pin to openjdk. 
r-ldweaver has an interface to run SnpEff. If the system openjdk version is outdated, SnpEff will not run, this pin fixes the issue
---- …
> r-ldweaver add missing pin 

- recipes/htseq/meta.yaml
Update HTSeq from version 2.0.3 to 2.0.4
---- …
> Update HTSeq to 2.0.4

- recipes/ms2rescore/meta.yaml
Updating the dependency tree of ms2rescore, since psm_utils 0.7.0 version comes with pyopenms, so we can write out idXML files 🥳 
---- …
> Update ms2rescore: Add pyopenms as dependency

- recipes/gapmm2/meta.yaml
> Add recipe for gapmm2 v0.2.0

- recipes/buscolite/meta.yaml
> Add recipe for buscolite v23.10.26

- recipes/omamer/meta.yaml
> Add omamer

- build-fail-blacklist
- recipes/ucsc-axtchain/include.patch
- recipes/ucsc-axtchain/meta.yaml
This is one of a batch of six PRs updating a USCS kent utils. The other five, very similar PRs, are #44060, #44061, #44062, #44063, and #44064.
---- …
> Update ucsc-axtchain from 377 to 455

- build-fail-blacklist
- recipes/ucsc-chainnet/include.patch
- recipes/ucsc-chainnet/meta.yaml
This is one of a batch of six PRs updating a USCS kent utils. The other five, very similar PRs, are #44059, #44060, #44061, #44062, and #44063.
---- …
> Update ucsc-chainnet from 377 to 455

- build-fail-blacklist
- recipes/ucsc-axttopsl/include.patch
- recipes/ucsc-axttopsl/meta.yaml
This is one of a batch of six PRs updating a USCS kent utils. The other five, very similar PRs, are #44059, #44061, #44062, #44063, and #44064.
---- …
> Update ucsc-axttopsl from 377 to 455

- build-fail-blacklist
- recipes/ucsc-chainantirepeat/include.patch
- recipes/ucsc-chainantirepeat/meta.yaml
This is one of a batch of six PRs updating a USCS kent utils. The other five, very similar PRs, are #44059, #44060, #44062, #44063, and #44064.
---- …
> Update ucsc-chainantirepeat from 377 to 455

- build-fail-blacklist
- recipes/ucsc-chainfilter/include.patch
- recipes/ucsc-chainfilter/meta.yaml
This is one of a batch of six PRs updating a USCS kent utils. The other five, very similar PRs, are #44059, #44060, #44061, #44063, and #44064.
---- …
> Update ucsc-chainfilter from 377 to 455

- recipes/lotus2/meta.yaml
Also:
- Add extra section (recipe-maintainers, identifiers)
---- …
> Fix sdm requirement pin in LotuS2

- build-fail-blacklist
- recipes/ucsc-chainmergesort/include.patch
- recipes/ucsc-chainmergesort/meta.yaml
This is one of a batch of six PRs updating a USCS kent utils. The other five, very similar PRs, are #44059, #44060, #44061, #44062, and #44064.
---- …
> Update ucsc-chainmergesort from 377 to 455

- recipes/tides-ml/meta.yaml
Add tides-ml recipe to Bioconda.
tides-ml is a command line application for identifying open-reading frames (ORFs) from transcriptome assemblies as well as ORF classification for "contaminant" removal.
https://github.com/xxmalcala/TIdeS/
---- …
> Add TIdeS package to BioConda

- recipes/cellsnake/meta.yaml
A recent update on r-dbplyr package causes a bug, explained here https://stackoverflow.com/questions/77370659/error-failed-to-collect-lazy-table-caused-by-error-in-db-collect-using
Therefore I restricted the package version to an old version.
Cheers,
---- …
> Update meta.yaml to a new build due to a package update bug

- recipes/teloclip/meta.yaml
> Update meta.yaml [teloclip]

- build-fail-blacklist
- recipes/ucsc-fasomerecords/include.patch
- recipes/ucsc-fasomerecords/meta.yaml
This updates ucsc-fasomerecords from 377 to 455.
---- …
> Update ucsc-fasomerecords from 377 to 455

- build-fail-blacklist
- recipes/last/meta.yaml
> Upldate LAST recipe

- recipes/dgenies/meta.yaml
Fix flask requirement for dgenies and add `run_exports` part in the recipe.
`max_pin="x.x"` is because config file have evolve beween 1.x versions.
---- …
> Update dgenies flask version

- recipes/vsnp3/meta.yaml
> vsnp3 version 3.17

- recipes/pbpigeon/meta.yaml
Update pbpigeon to v1.2.0
---- …
> Update pbpigeon to v1.2.0

- recipes/idemuxcpp/build.sh
- recipes/idemuxcpp/meta.yaml
Update idemuxcpp to 0.2.0.
---- …
> Update idemuxcpp to 0.2.0

- recipes/sequencetools/meta.yaml
This PR updates sequenceTools to version 1.5.3.2.
---- …
> Update sequenceTools to 1.5.3.2

- recipes/colabfold/fix-jax-04-nan.patch
- recipes/colabfold/meta.yaml
> Fix NaN issue in ColabFold 1.5.3

- recipes/plassembler/meta.yaml
Corrects the plassembler dependencies canu and dnaapler versions to match the v1.4.1 release.
---- …
> Correct plassembler dependencies v1.4.1

- recipes/vsnp3/meta.yaml
> vsnp3 version 3.18

- recipes/r-monocle3/meta.yaml
> Update r-monocle3 to 1.3.1

- recipes/blast/meta.yaml
Update BLAST from 2.14.1 to 2.15.0.
---- …
> Update BLAST to 2.15.0

- recipes/augur/meta.yaml
Include dependency change for pyfastx¹ that was missed in the autobump PR²
¹ https://github.com/nextstrain/augur/commit/a7210930b6cbd617db3c16ff3bde4889762e2f96 
² https://github.com/bioconda/bioconda-recipes/pull/44150
----
* …
> Update Augur dependencies for 23.1.1

- recipes/lima/meta.yaml
> Update lima to v2.9.0

- recipes/cooltools/meta.yaml
> Update cooltools to 0.6.0

- recipes/sequali/meta.yaml
This adds the recipe for sequali. A fast sequencing quality metrics program.
---- …
> Add sequali recipe

- recipes/r-saige/meta.yaml
New r-saige version has released: https://github.com/saigegit/SAIGE/commit/92b6c6cd7f552d340cfc4b3b395574fbc598ee2e . 
---- …
> Update r-saige to version 1.3.1

- recipes/poseidon-xerxes/meta.yaml
This PR updates poseidon-xerxes to version 1.0.0.2
---- …
> Update poseidon-xerxes to v1.0.0.2

- recipes/curare/meta.yaml
Update of Curare to 0.5.0. Dependencies were updated, and spaces between package name and version number were added for lint checks.
---- …
> Update Curare to 0.5.0

- recipes/blast/meta.yaml
- recipes/blast/run_test.sh
This pull request adds a BLASTDB integrity check to the test suite.
---- …
> Update BLAST: add blastdb integrity check

- recipes/deepbgc/meta.yaml
> Bump deepbgc to 0.1.31

- recipes/annembed/build.sh
- recipes/annembed/meta.yaml
This new software annembed further improves UMAP and t-SNE algorithm for non-linear dimension reduction and allow very large-scale biological data to run very fast and efficiently. See details here https://github.com/jean-pierreBoth/annembed and here https://github.com/jianshu93/annembed_analysis. For single cell RNA sequencing data or genomics data, annembed can be extremely fast and memory efficient because  of new algorithm design and data structures. Jean Pierre-Both and I are preparing a paper on this software and the preprint will be available soon. We want to add the bioconda install channel first. 
----
* If …
> Add annembed v0.1.1

- recipes/bedgovcf/build.sh
- recipes/bedgovcf/meta.yaml
> New recipe: bedgovcf

- recipes/megalodon/meta.yaml
> Update megalodon version

- recipes/pbtk/meta.yaml
> Update pbtk to v3.1.1

- recipes/pbskera/meta.yaml
> Update pbskera to v1.2.0

- recipes/seqerakit/meta.yaml
Adds seqerakit - see https://github.com/seqeralabs/seqera-kit
---- …
> Add seqerakit recipe

- recipes/biophi/meta.yaml
> Use flask<3 in biophi

- recipes/metaphor/meta.yaml
- Use Python<=3.12 for now, see snakemake/snakemake#2480 for discussion
> Update Metaphor dependencies

- recipes/flight-genome/meta.yaml
> Fix flight-genome command

- recipes/tracy/meta.yaml
> Update tracy to v0.7.6

- recipes/reneo/meta.yaml
This PR adds [reneo](https://github.com/Vini2/reneo) (Reneo: Unraveling Viral Genomes from Metagenomes) to bioconda. Reneo is a software developed to unravel high-quality genomes from viral communities (including both prokaryotic and eukaryotic viruses) found within metagenomes using assembly graphs.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and …
> Add reneo v0.2.0

- recipes/seqkit/meta.yaml
- [SeqKit v2.6.1](https://github.com/shenwei356/seqkit/releases/tag/v2.6.1) - 2023-11-18 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.6.1/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.6.1)
- `seqkit`:
- fix panic of nil pointer introduced in v2.6.0, which happens when handling multiple input files and some of them have file sizes of zero.
- `seqkit seq`:
- fix panic (close of closed channel) when using `-v` to checking sequences.
----
* New …
> Update SeqKit to v2.6.1

- recipes/mbg/meta.yaml
Update MBG to version 1.0.16
---- …
> Update MBG to version 1.0.16

- recipes/centrifuger/build.sh
- recipes/centrifuger/meta.yaml
> Centrifuger is an efficient taxonomic classification method that compares sequencing reads against a microbial genome database. It implemented a novel lossless compression method, run-block comprssed BWT, and other strategies to efficiently reduce the size of the microbial genome database like RefSeq. For example, Centrifuger can classify reads against the 2023 RefSeq prokaryotic genomes containing about 140G nucleotides using 43 GB memory. Despite running on a compressed data structure, Centrifuger is also highly efficient and can process a typical sequencing sample within an hour.
https://github.com/mourisl/centrifuger
----
* If this PR adds or …
> Add Centrifuger

- recipes/mmquant/meta.yaml
I would like to update to mmquant recipe, in order to include the version 1.0.9.
---- …
> Update to mmquant 1.0.9

- recipes/graphaligner/meta.yaml
Update GraphAligner to version 1.0.18
---- …
> Update GraphAligner to version 1.0.18

- recipes/peaks2utr/LICENSE
- recipes/peaks2utr/meta.yaml
> Add recipe for peaks2utr v1.2.0

- recipes/qualimap/meta.yaml
Update [qualimap](https://bitbucket.org/kokonech/qualimap) to v2.3
----
Conda is able …
> Update qualimap to v2.3

- recipes/hpcblast/meta.yaml
This PR adds a recipe for [hpc-blast](https://github.com/yodeng/hpc-blast), a simple and efficient method for running the NCBI-BLAST+ suite program.
---- …
> Add hpcblast recipe

- recipes/braker3/meta.yaml
> Update Braker v3.0.3 to v3.0.6

- recipes/genomepy/meta.yaml
> Added run_exports to meta.yaml

- recipes/ribotin/build.sh
- recipes/ribotin/meta.yaml
Update ribotin to version 1.2
---- …
> Update ribotin to version 1.2

- recipes/poppunk/meta.yaml
Updates poppunk (not sure why this wasn't autobumped). Possibly we need run_exports added
---- …
> Update poppunk to v2.6.1

- recipes/merquryfk/meta.yaml
Hello! 👋🏼 
- added `fastk` to dependencies for `merquryfk`, so that HAPmaker function works
- added `R` (base & some packages) to dependencies for `merquryfk`, so that the plotting functions work 
R package version minimums used are copied from the `merqury` package's meta.yaml.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, …
> Update merquryfk dependencies

- recipes/pantools/meta.yaml
Update PanTools to v4.3.0 (which includes some dependency updates)
> Update pantools to 4.3.0

- recipes/anansnake/meta.yaml
> Update anansnake to 0.1.0

- recipes/taxonkit/meta.yaml
- [TaxonKit v0.15.1](https://github.com/shenwei356/taxonkit/releases/tag/v0.15.1) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/taxonkit/v0.15.1/total.svg)](https://github.com/shenwei356/taxonkit/releases/tag/v0.15.1)
- `taxonkit name2taxid`:
- remove the restriction of name types. [#87](https://github.com/shenwei356/taxonkit/issues/87)
---- …
> Update TaxonKit to v0.15.1

- recipes/matchms/meta.yaml
> Pin numpy version in matchms

- recipes/slow5curl/build.sh
- recipes/slow5curl/meta.yaml
> add slow5curl

- recipes/cstag-cli/meta.yaml
I would like to allow the latest pysam version.
---- …
> Update the recipe of cstag-cli

- recipes/annembed/meta.yaml
Add hubness and LID estimation from HNSW graph
---- …
> Update annembed v0.1.2

- .circleci/config.yml
NOTE: this is is going into the `arm-builds` branch, not master. 
See @daler comment on the arm builds PR: https://github.com/bioconda/bioconda-recipes/pull/40550#issuecomment-1825923035
1. Use machine executor for both regular builds and bulk.
2. Do mulled test during build-and-test
3. Include images in artifacts
4. Remove outdated comments
> ARM builds: CircleCI jobs consistency

- recipes/csvtk/meta.yaml
- [csvtk v0.29.0](https://github.com/shenwei356/csvtk/releases/tag/v0.29.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.29.0/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.29.0)
- new commands:
- [`fix-quotes`](https://bioinf.shenwei.me/csvtk/usage/#fix-quotes): fix malformed CSV/TSV caused by double-quotes. [#260](https://github.com/shenwei356/csvtk/issues/260)
- [`del-quotes`](https://bioinf.shenwei.me/csvtk/usage/#del-quotes): remove extra double-quotes added by `fix-quotes`.
- `csvtk del-header`:
- fix deleting headers of 2nd and later files. [#257](https://github.com/shenwei356/csvtk/issues/257)
- `csvtk concat`:
- fix panic when no data found.
- `csvtk sort`:
- support column names …
> update csvtk to v0.29.0

- recipes/poppunk/meta.yaml
> Bump poppunk to v2.6.2

- recipes/jgoslin/meta.yaml
This PR updates jgoslin to the latest published artifact version from Maven central.
---- …
> Update jgoslin to latest Maven central release 2.2.0

- recipes/earlgrey/meta.yaml
Added citation to the description block in meta.yaml and iterated build number by 1. 
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Also, …
> Update earlgrey meta.yaml

- recipes/raiss/meta.yaml
This new release includes:
- More flexibility in LD files
- A more comprehensive performance report
- A command to run sanity checks (Do we see inflated p-value in imputed  data?) comparing inputed and original data
----
* …
> added new tag for RAISS

- recipes/genomad/meta.yaml
The latest pyrodigal-gv made it incompatible with geNomad. This PR sets a specific version for pyrodigal-gv.
----
Conda …
> Fix geNomad dependencies

- recipes/earlgrey/meta.yaml
This update adds a requirement for bedtools, which is needed in the new update.
---- …
> Update earlgrey meta.yaml - add requirement for bedtools

- recipes/sequenoscope/meta.yaml
The following marks the first release for a versatile bioinformatic pipeline for the analysis of sequencing data. The pipeline handles different types of sequencing data and has specific tools that give insight into adaptive sampling sequencing introduced by Oxford Nanopore sequencer
- **Used to generate Seq Manifest Files**
- Accepts an input fastq file, a reference fastq file, and an optional sequencing summary file.
- Utilizes the tools fastp, mash, pysam, and mash to map, parse and organize sequencing data statistics.
- Generates sequence manifest files and summary sequence manifest files containing essential sequencing statistics.
- **Used to plot Seq Manifest and Manifest summary Files**
- Takes test and control sequence manifest or sequence manifest summary files as input.
- …
> First sequenoscope release 0.0.5

- recipes/earlgrey/meta.yaml
> Update earlgrey autobump build number

- recipes/sphae/meta.yaml
This PR adds [`sphae`](https://github.com/linsalrob/sphae), a phage toolkit to Bioconda.
---- …
> add sphae v1.3.1

- recipes/nrpys/LICENSE.txt
- recipes/nrpys/meta.yaml
> nrpys -  fix license text

- recipes/jalview/jalview.sh
- recipes/jalview/meta.yaml
Update Jalview to 2.11.3.2
---- …
> Update Jalview to 2.11.3.2

- recipes/resistify/meta.yaml
Resistify is a plant resistance gene annotation toolkit
---- …
> Add Resistify

- recipes/poly-qtlseq/build.sh
- recipes/poly-qtlseq/meta.yaml
- recipes/poly-qtlseq/polyQtlseq.sh
Add poly-qtlseq (PolyploidQtlSeq is a program that extends QTL-seq for polyploid F1 populations.)
---- …
> Add poly-qtlseq

- recipes/nextclade/build.sh
- recipes/nextclade/meta.yaml
- recipes/nextclade/run_test.sh
add nextclade2 symlink to nextclade
---- …
> Update: add nextclade2 symlink to nextclade

- recipes/shortseq/meta.yaml
ShortSeqs are compact and efficient Python objects that hold short sequences while using up to 73% less memory compared to built-in types. They have a pre-computed hash value, can be compared for equality, and are easily converted back to the original sequence string.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, please issue …
> Add ShortSeq

- recipes/insilicosv/meta.yaml
> Added insilicoSV

- recipes/biobb_pdb_tools/meta.yaml
> [v4.1.0] update 2023.4

- recipes/ribotin/build.sh
- recipes/ribotin/meta.yaml
Includes annotation index files for ribotin. Normally these would be automatically generated during runtime by liftoff but when the package is installed in a read-only location the automatic generation fails. Therefore include the indexes in the package and require the exact same version of liftoff to make sure version changes do not invalidate the index.
---- …
> Update ribotin v1.2 build 1

- recipes/kissplice/build.sh
- recipes/kissplice/meta.yaml
Update kissplice to 2.6.2
---- …
> Update kissplice to 2.6.2

- recipes/olga/meta.yaml
> Add OLGA 1.2.4 recipe to Bioconda

- recipes/campy-against/meta.yaml
- recipes/campyagainst/meta.yaml
> Add campy-against

- recipes/lotus2/meta.yaml
xref. https://github.com/hildebra/lotus2/releases/tag/v2.30
---- …
> Fix lotus2 2.30 updated requirements

- build-fail-blacklist
- recipes/lorikeet-genome/build.sh
- recipes/lorikeet-genome/meta.yaml
update lorikeet-genome version and recipe
---- …
> Update lorikeet-genome version v0.8.2

- recipes/searchgui/meta.yaml
- recipes/searchgui/searchgui.py
> Update searchgui to 4.3.3

- recipes/ncbi-fcs-gx/0.4.1/aria_split_16.patch
- recipes/ncbi-fcs-gx/0.4.1/meta.yaml
- recipes/ncbi-fcs-gx/aria_split_16.patch
- recipes/ncbi-fcs-gx/meta.yaml
ncbi-fcs-gx : Add a patch to improve AWS download times
---- …
> ncbi-fcs-gx : Add a patch to improve AWS download times

- recipes/pantools/meta.yaml
> update pantools to v4.3.1

- recipes/ntlink/build.sh
- recipes/ntlink/meta.yaml
Update ntLink build
Adjust build.sh to ensure wrapper shell script can properly recognize multiple input read files as per the ntLink documentation
---- …
> Update ntlink build

- recipes/bioconductor-geoquery/build_failure.linux-64.yaml
- recipes/bioconductor-geoquery/meta.yaml
> Try building bioconductor-geoquery

- recipes/medaka/meta.yaml
> Update medaka to 1.11.3

- recipes/bioconductor-gpumagic/meta.yaml
- recipes/bioconductor-graph/build_failure.osx-64.yaml
- recipes/bioconductor-graph/meta.yaml
> Bioconductor graph

- recipes/proovframe/meta.yaml
> Update - add long description, dev_url and run_export

- recipes/cutadapt/meta.yaml
https://github.com/marcelm/cutadapt/issues/746
ping @marcelm 
Maybe a bump might have been sufficient, but I thought it's better to be explicit.
---- …
> cutadapt: require dnaio 1.2

- recipes/proteinortho/meta.yaml
> Update meta.yaml, added doi
