bioconda/bioconda-recipes

recipes/dicey/meta.yaml
=> Update dicey v0.2.8

build-fail-blacklist, recipes/methylpy/build.sh, recipes/methylpy/meta.yaml
=> Update methylpy to 1.4.7

recipes/scib/meta.yaml, recipes/scib/setup_compiler.patch
=> Add scib start from 1.1.4

recipes/ananse/meta.yaml
=> Fix ANANSE v0.5

recipes/beav/meta.yaml
A major update of beav which improvise Circos plot, generate combined log, and fix minor bugs. 
---- …
=> Update beav to v1.0.0

recipes/bcftools-gtc2vcf-plugin/conda_build_config.yaml, recipes/bcftools-gtc2vcf-plugin/meta.yaml
Rebuild `bcftools +gtc2vcf` against htslib/bcftools 1.19 and integrate a C90 patch from the plugin itself. A 1.18 PR happened about a week ago; hopefully this modification is very straightforward.
---- …
=> Update bcftools-gtc2vcf-plugin to htslib/bcftools 1.19

recipes/cobra-meta/meta.yaml
=> Add recipe for cobra-meta

recipes/peptide-shaker/meta.yaml, recipes/peptide-shaker/peptide-shaker.py
=> Update peptide-shaker to 3.0.4

recipes/searchgui/build.sh, recipes/searchgui/meta.yaml, recipes/searchgui/searchgui.py
=> Update searchgui to 4.3.5

recipes/nohuman/build.sh, recipes/nohuman/meta.yaml
=> add nohuman recipe

recipes/poppunk/meta.yaml
=> Update poppunk to v2.6.3

recipes/snakemake-interface-common/meta.yaml, recipes/snakemake-interface-executor-plugins/meta.yaml
=> fix: update dependencies and versions of snakemake interface packages

recipes/tf-comb/meta.yaml
=> Add recipe for tf-comb

recipes/igdiscover/meta.yaml
IgDiscover works fine with newer Snakemake versions, so let’s remove the overly restrictive version bound (which is causing problems for me).
---- …
=> Update IgDiscover: Allow higher snakemake versions

recipes/clair3/meta.yaml
=> update Clair3 to v1.0.5

recipes/snapatac2/meta.yaml
Adding SnapATAC2 python package for single-cell ATAC-seq data analysis.
=> Add recipe for snapatac2

recipes/snakemake-interface-storage-plugins/meta.yaml, recipes/snakemake-storage-plugin-azure/meta.yaml, recipes/snakemake-storage-plugin-fs/meta.yaml, recipes/snakemake-storage-plugin-ftp/meta.yaml, recipes/snakemake-storage-plugin-gcs/meta.yaml, recipes/snakemake-storage-plugin-http/meta.yaml, recipes/snakemake-storage-plugin-irods/meta.yaml, recipes/snakemake-storage-plugin-s3/meta.yaml, recipes/snakemake-storage-plugin-sftp/meta.yaml, recipes/snakemake-storage-plugin-zenodo/meta.yaml
Add various storage plugins for the upcoming Snakemake 8.
---- …
=> feat: add snakemake storage plugins

recipes/fiji/bunwarpj.sh, recipes/fiji/meta.yaml
=> Update fiji version

recipes/primer3-py/build.sh, recipes/primer3-py/meta.yaml
=> Build primer3-py on python 3.8-3.10

build-fail-blacklist, recipes/hatchet/build.sh, recipes/hatchet/meta.yaml
=> Update hatchet to 2.0.1

recipes/binchicken/meta.yaml
Add Bin chicken metagenomics tool
---- …
=> Add binchicken

recipes/snakemake/meta.yaml
=> fix: cleanup dependencies in snakemake 8 recipe and upgrade to 8.0.1

recipes/fiji-max_inscribed_circles/meta.yaml
Update fiji-max_inscribed_circles to version 2.1.0
---- …
=> Update fiji-max_inscribed_circles to version 2.1.0

recipes/hictkpy/build.sh, recipes/hictkpy/conanfile.txt.patch, recipes/hictkpy/meta.yaml
=> Update hictkpy to v0.0.3

recipes/hisat2-pipeline/meta.yaml
**Hisat2-pipeline** is an automated, easy-to-use pipeline to run RNA-seq analyses using Hisat2 in conjucture with stringtie. The pipeline is aimed at scientist who run RNA-seq analyses frequently, as well as at scientists who lack the necessary skills to run an RNA-seq analysis without assistance.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and …
=> Add hisat2-pipeline

recipes/mitos/mitos1/meta.yaml
=> bump mitos1

recipes/gw/build.sh, recipes/gw/meta.yaml
=> gw version 0.9.1

recipes/hictk/conanfile.txt.patch, recipes/hictk/meta.yaml, recipes/hictk/run_test.sh
=> Update hictk to v0.0.4

recipes/haplink/meta.yaml
Updates HapLink to its latest released version.
=> Update HapLink to version 1.1.0

recipes/hictk/conanfile.txt.patch, recipes/hictk/meta.yaml
=> Update hictk to v0.0.5

recipes/bcbio-gff/meta.yaml
bugfix: strand deprecated and removed in BioPython 1.82
- see: https://github.com/chapmanb/bcbb/issues/138
---- …
=> Update: bcbio-gff bugfix: breaks with BioPython 1.82

recipes/lollipop/meta.yaml
bugfix: breaking API change between ruamel.yaml 0.17.x and 0.18
---- …
=> Update: LolliPop bugfix: breaks with ruamel.yaml 0.18

recipes/recognizer/build.sh, recipes/recognizer/meta.yaml
Removes build.sh from reCOGnizer's recipe. Could not find how to do it through GitHub in another way
----
Conda is able …
=> Fix recognizer

recipes/cellbender/meta.yaml
=> Add recipe for CellBender v0.3.0

recipes/nrpys/build.sh, recipes/nrpys/cargo.patch, recipes/nrpys/meta.yaml, recipes/nrpys/pyproject.patch
=> Fix nrpys to build on python 3.8+

recipes/antismash-lite/build.sh, recipes/antismash-lite/meta.yaml
=> Update antismash-lite to 7.1.0

recipes/annosine2/meta.yaml
=> Update annosine2 build

recipes/deepmei/build.sh, recipes/deepmei/license.txt, recipes/deepmei/meta.yaml
Add : DeepMEI
----
DeepMEI is a convolutional neural network based tool to identify non-reference mobile elements insertions in short-read sequencing data
---- …
=> Add Deepmei version 1.0.0 recipes

recipes/prodigal/meta.yaml, recipes/prodigal/score_nodes.patch, recipes/prodigal/sd_motif_A.patch, recipes/prodigal/sd_motif_B.patch
The developer has accepted these patches, but [no new release has been made](https://github.com/hyattpd/Prodigal/issues/97) in over two years since at least the first was accepted.
See:
https://github.com/hyattpd/Prodigal/pull/88
https://github.com/hyattpd/Prodigal/pull/100
=> prodigal: include upstream patches fixing critical bugs

recipes/bioframe/meta.yaml, recipes/vcfphasesets/meta.yaml
=> Add vcfphasesets

recipes/complexcgr/meta.yaml, recipes/odgi/meta.yaml
This PR adds the python library complexcgr, it contains encoders and associated image representation of k-mers distribution of DNA/RNA sequences based on the Chaos Game Representation of DNA (CGR). Since its publication in 1990 [1], CGR encoding and siblings have found a range of applications in bioinformatics, see [5].
Encoders implemented:
CGR [1]: Chaos Game Representation of DNA/RNA
iCGR [2]: integer Chaos Game Representation
Complex CGR [unpublished]: encoding of sequences for general alphabet based on complex numbers
Image Representation implemented:
FCGR [3-4]: Frequency matrix of CGR, an image (square) representation of the distribution of k-mers of a DNA/RNA sequence.
ComplexFCGR [unpublished]: circular representation of a based on the ComplexCGR encoding.
References:
[1] …
=> Complexcgr

recipes/vcf2db/meta.yaml
The older versions caused some issues in genotype parsing
---- …
=> Update dependencies for vcf2db

recipes/snakefmt/meta.yaml
black and python versions need to be updated
---- …
=> Update snakefmt dependencies

recipes/vcf2db/meta.yaml
=> Fix even more dependencies in vcf2db

recipes/conipher/meta.yaml
Updated CONIPHER version and the associated doi.
---- …
=> Update conipher version 2.2.0

recipes/flexiplex/meta.yaml
Updates package Flexiplex to a new release.
---- …
=> Update Flexiplex to v1.01

recipes/cenote-taker3/meta.yaml
PR to add `Cenote-Taker 3`, a bioinformatics tool to discover and annotate the virome.
[https://github.com/mtisza1/Cenote-Taker3](https://github.com/mtisza1/Cenote-Taker3)
---- …
=> Add Cenote-Taker3 v3.2.0

recipes/htsinfer/meta.yaml
=> Add HTSinfer

recipes/ganon/meta.yaml
=> Update ganon to 2.0.1

recipes/fastlin/meta.yaml
=> Update fastlin to v0.2.3

recipes/braker3/build.sh, recipes/braker3/meta.yaml
=> Update braker3 to 3.0.7

recipes/phigaro/meta.yaml
Removed argparse requierement, since it's a part of the Python Standard Library. Restricted Python <=3.7.11 to prevent from trying to use 2.12.0_pr3
---- …
=> Phigaro: remove argparse, python <=3.7.11

recipes/snakemake/meta.yaml
See https://github.com/snakemake/snakemake/pull/2610/files
Since v8.1.2 actually
---- …
=> Fix snakemake: pulp dependency changes

recipes/meme/build.sh, recipes/meme/meta.yaml
=> Update meme to 5.5.5

recipes/maegatk/meta.yaml
=> Add recipe for MAEGATK v0.2.0

recipes/htseq/meta.yaml
=> Update HTSeq version

recipes/tntblast/build.sh, recipes/tntblast/meta.yaml
Add tntblast (aka. [thermonucleotideBLAST](https://github.com/jgans/thermonucleotideBLAST))
---- …
=> Add tntblast (thermonucleotideBLAST)

recipes/mgatk/meta.yaml
=> Add recipe for MGATK v0.7.0

recipes/massdash/meta.yaml
=> Add recipe for massdash

recipes/monsda/meta.yaml
=> Update snakemake pinning, version 8 major changes that break everything

recipes/revoluzer/build.sh, recipes/revoluzer/meta.yaml
=> add revoluzer

recipes/moods/build.sh, recipes/moods/meta.yaml
=> Update MOODS to 1.9.4.2

recipes/svync/build.sh, recipes/svync/meta.yaml
=> new recipe svync

recipes/toil/drop_ruamel_yaml_string_dependency.patch, recipes/toil/meta.yaml
Update toil to version 6.0.0
- ~~Depends on a new package for [ruamel.yaml.string](https://pypi.org/project/ruamel.yaml.string/)~~
---- …
=> Update toil for 6.0.0

recipes/augur/meta.yaml
Includes dependency changes.
<https://github.com/nextstrain/augur/commit/13b7fb8709921e5d90c725c43bd11b3594913435> <https://github.com/nextstrain/augur/commit/aa0b7d8922b5c72bcc3fe9114af2985165f3e2f3>
----
* Please post …
=> Update augur to 24.0.0

recipes/svync/meta.yaml
=> Bump svync to v0.1.1

recipes/svync/meta.yaml
=> Bump svync to v0.1.2

recipes/coverm/meta.yaml
=> Update CoverM to v0.7.0

recipes/beav/meta.yaml
In this build, following things are updated:
- MacSyFinder and DefenseFinder model path updated
- DBScan download path updated
- Circos issue fixed
- Minor bugs fixed
---- …
=> Beav 1.1.0 release update

recipes/crispector/meta.yaml
New version with better translocation detection
---- …
=> better translocation detection

recipes/quicktree/build.sh, recipes/quicktree/meta.yaml, recipes/quicktree/patches/0001-Add-rule-to-build-shared-library.patch
Enable building a shared library for usage of quicktree functions by other software.
---- …
=> Build shared library for quicktree

recipes/floria/build.sh, recipes/floria/meta.yaml
Adding recipe for floria, a method for recovering microbial haplotypes from metagenomics sequencing data by haplotype phasing and read clustering.
See https://github.com/bluenote-1577/floria/
---- …
=> Add floria recipe.

recipes/icescreen/meta.yaml
=> Update icescreen v1.3.1

recipes/memote/meta.yaml
Add a recipe for [memote](https://www.nature.com/articles/s41587-020-0446-y), a test suite for constraint-based metabolic models.
---- …
=> Add memote

recipes/bindash/meta.yaml, recipes/gsearch/meta.yaml
Update gsearch v0.1.8 for better output format
---- …
=> Update gsearch v0.1.8

recipes/skyline2isocor/meta.yaml
=> Added recipe for skyline2isocor v0.1.0

recipes/seqfu/build.sh, recipes/seqfu/meta.yaml
=> [seqfu] Re-add macOS support

recipes/ucsc-twobitinfo/meta.yaml
Similar to https://github.com/bioconda/bioconda-recipes/pull/44040
This update should resolve issues with incompatible openssl versions
---- …
=> Update ucsc-twobitinfo to 455

recipes/ucsc-bedgraphtobigwig/meta.yaml
Similar to https://github.com/bioconda/bioconda-recipes/pull/44040
This update should resolve issues with incompatible openssl versions
Opened along with https://github.com/bioconda/bioconda-recipes/pull/45418
----
* Please post …
=> Update ucsc-bedgraphtobigwig to 455

recipes/r-deconcell/build.sh, recipes/r-deconcell/meta.yaml
This adds the R package DeconCell. This package was previously developed here https://github.com/raguirreg/DeconCell but now lives here https://github.com/molgenis/systemsgenetics/tree/master/Decon2/DeconCell
----
* Please post …
=> Add recipe r-deconcell

recipes/pegasuspy/meta.yaml
* Fix some dependencies.
* Add `forceatlas2-python` back to avoid users installing incorrect dependency.
----
Conda is …
=> Update Pegasuspy to 1.9.0

recipes/parsnp/cpu_count.patch, recipes/parsnp/meta.yaml
Trying to get the MacOS build working again...
=> Enable macos build for parsnp

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.19

recipes/binette/meta.yaml
This PR updates Binette recipe to v0.1.7 
Additionally, I also added the documentation URL of the tool and adjusted some of the requirements. 
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Note that the <code>@BiocondaBot please merge</code> command is now …
=> Update Binette to v0.1.7

recipes/tksm/meta.yaml
Fix python build + add more tests
---- …
=> Update TKSM recipe: to fix bump to 5.0

recipes/bbmap/build.sh, recipes/bbmap/meta.yaml
Updating bbmap to latest 39.06
=> Update bbmap to 39.06

recipes/annembed/meta.yaml
with this version, we optimized output format and several minor improvement. 
---- …
=> Update annembed v0.1.4

recipes/itol-config/meta.yaml
Add new package that generates itol config files
---- …
=> add itol-config

recipes/locarna/meta.yaml
using recent viennarna package
---- …
=> rebuild locarna 2.0

recipes/annonars/meta.yaml
We moved the repo to another org.
---- …
=> adjust GitHub org for annonars

recipes/mehari/meta.yaml
We moved mehari to another org.
---- …
=> mehari: adjust GitHub org

recipes/learnmsa/meta.yaml
Manually fixed problem with #45492
=> Update learnMSA to version 1.3.4

recipes/ephemeris/meta.yaml, recipes/ezaai/build.sh, recipes/ezaai/meta.yaml
=> Update ezaai to 1.2.3

recipes/seqkit/meta.yaml
- [SeqKit v2.7.0](https://github.com/shenwei356/seqkit/releases/tag/v2.7.0) - 2024-01-31 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.7.0/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.7.0)
- `seqkit`:
- Grouping subcommands in help message, which is intuitive for beginners.
- `seqkit grep`:
- New flag: `-D/--allow-duplicated-patterns` for outputting records multiple times when duplicated patterns are given. [#427](https://github.com/shenwei356/seqkit/issues/427)
- `seqkit subseq`:
- Use the ID regular expression from the option `--id-regexp` to create FASTA index file. This solves the panic happened for sequences containing tabs in the headers. …
=> Update SeqKit to v2.7.0

recipes/megan/meta.yaml
Updates MEGAN to 6.25.9, and includes a URL change due to new website (old URL 'works' through redirecting, but has an out of date SSL certificate and bioconda tools will fail to download. The new URL is the new canonical one).
---- …
=> Update MEGAN to 6.25.9

recipes/pourrna/meta.yaml
rebuild of package with recent dependencies and yaml changes
---- …
=> rebuild pourRNA

recipes/kma/build.sh, recipes/kma/meta.yaml
=> Update kma to 1.4.14

recipes/dropkick/meta.yaml
=> Add recipe for dropkick v1.2.8

recipes/lusstr/meta.yaml
This PR pins Snakemake to version <8.0 until lusSTR can be updated.
---- …
=> lusSTR: pin snakemake <v8.0

recipes/cgelib/meta.yaml
=> Add recipe for cgelib v0.7.4

recipes/gmap/build.sh, recipes/gmap/meta.yaml
=> Update gmap to 2023.12.01

recipes/rnastructure/meta.yaml
Changelog:
https://rna.urmc.rochester.edu/Overview/Updates.html
---- …
=> Update rnastructure to 6.4

recipes/unikseq/meta.yaml
Needed to add run_exports section
---- …
=> Update unikseq to 1.3.5

recipes/monopogen/LICENSE, recipes/monopogen/meta.yaml
=> Add recipe for Monopogen v1.1.0

recipes/amplify/build.sh, recipes/amplify/meta.yaml
=> Update amplify to 2.0.0

recipes/deeptoolsintervals/meta.yaml
=> Fix deeptoolsintervals license

build-fail-blacklist, recipes/kmer-jellyfish/build.sh, recipes/kmer-jellyfish/meta.yaml
run_exports subpackage pinned to 2.3.1 because there are compilation changes between patch releases (x.x.x)
----
Conda …
=> Update kmer-jellyfish to 2.3.1

recipes/superdsm/meta.yaml
The [autobump](https://github.com/bioconda/bioconda-recipes/pull/45663) failed due to `missing_run_exports`, which is fixed in this PR.
---- …
=> Update superdsm to 0.2.0

recipes/hmftools-bam-tools/bamtools.sh, recipes/hmftools-bam-tools/build.sh, recipes/hmftools-bam-tools/meta.yaml
Add recipe for hmftools-bam-tools 1.2
---- …
=> Add hmftools-bam-tools 1.2

recipes/hmftools-virus-interpreter/build.sh, recipes/hmftools-virus-interpreter/meta.yaml, recipes/hmftools-virus-interpreter/virusinterpreter.sh
Add recipe for hmftools-virus-interpreter 1.3
---- …
=> Add hmftools-virus-interpreter 1.3

recipes/r-mutsigextractor/build.sh, recipes/r-mutsigextractor/meta.yaml
Add recipe for r-mutsigextractor 1.14
---- …
=> Add r-mutsigextractor 1.14

recipes/r-chord/build.sh, recipes/r-chord/meta.yaml
Add recipe for r-chord 2.02
---- …
=> Add r-chord 2.02

recipes/gametes/LICENSE, recipes/gametes/build.sh, recipes/gametes/gametes.py, recipes/gametes/meta.yaml
This PR adds a recipe for [gametes](https://sourceforge.net/projects/gametes/), a tool for genotype and phenotype data simulation.
=> Add gametes new recipe

recipes/perl-ms/meta.yaml
Adds run_exports to meta.yml; bump version
=> Update perl-ms: add run_exports, bump version

recipes/virulencefinder/meta.yaml
Virulencefinder's db does not contain a VERSION file thus git is used to get the latest commit. This cannot be retrieved when using this container, hence it has been added.
---- …
=> Add git to virulencefinder

recipes/resfinder/meta.yaml
I have pulled the new resfinder image and I get the following error when running `python -m resfinder`:
```
File "/usr/local/lib/python3.12/site-packages/git/__init__.py", line 140, in <module>
refresh()
File "/usr/local/lib/python3.12/site-packages/git/__init__.py", line 127, in refresh
if not Git.refresh(path=path):
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/git/cmd.py", line 456, in refresh
raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
- be included in your $PATH
- be set via $GIT_PYTHON_GIT_EXECUTABLE
- explicitly set via git.refresh()
All git commands will error until this is rectified.
This initial warning can be silenced or aggravated in the …
```
=> Add git to resfinder

recipes/ntsynt/build.sh, recipes/ntsynt/meta.yaml
Add recipe for ntSynt - a multi-genome synteny detection tool 
---- …
=> Add ntsynt

recipes/varfish-cli/meta.yaml
We need to fix the dependency `pydantic` of `varfish-cli` to be above `2.0`.
---- …
=> Fix pydantic dependency of varfish-cli more strictly.

recipes/nanomotif/meta.yaml, recipes/seqnado/meta.yaml
=> Add seqnado

recipes/hmftools-sv-prep/gridss_shell_with_jar_entrypoint, recipes/hmftools-sv-prep/meta.yaml, recipes/hmftools-sv-prep/svprep.sh
* Fix discovery of the GRIDSS JAR, which is installed as a dependency
* Fix classpath detection in BASH script
---- …
=> Patch hmftools-sv-prep 1.2.3

recipes/gffpandas/meta.yaml
=> Add recipe for gffpandas v1.2.2

recipes/purge_haplotigs/meta.yaml
Manually updating as bioconda bot hasn't bumped the new version
---- …
=> Update purge_haplotigs to 1.1.3

recipes/evofr/meta.yaml
Includes dependency changes
https://github.com/blab/evofr/commit/4b64dfc5cb14620021835aaee41337affcd3a3a4
----
Conda is …
=> Update evofr to 0.1.22

recipes/verkko/meta.yaml, recipes/verkko/osx_availability.patch, recipes/verkko/run_test.sh, recipes/verkko/version.patch
=> update verkko to v2.0

recipes/hmftools-mark-dups/build.sh, recipes/hmftools-mark-dups/markdups.sh, recipes/hmftools-mark-dups/meta.yaml
Add recipe for hmftools-mark-dups 1.1
---- …
=> Add hmftools-mark-dups 1.1

recipes/r-linxreport/build.sh, recipes/r-linxreport/meta.yaml
Add recipe for r-linxreport 1.0.0
---- …
=> Add r-linxreport 1.0.0

recipes/pytransaln/meta.yaml
Python package for translation guided nucleotide alignment of coding sequences.
---- …
=> Add recipe pytransaln v0.2.1

recipes/hmftools-cuppa/build.sh, recipes/hmftools-cuppa/cuppa-chart.sh, recipes/hmftools-cuppa/cuppa.sh, recipes/hmftools-cuppa/meta.yaml
Add recipe for hmftools-cuppa 1.8.1
---- …
=> Add hmftools-cuppa 1.8.1

recipes/multirnafold/0001-FIX-Makefile.patch, recipes/multirnafold/0002-FIX-printf-missing-arg.patch, recipes/multirnafold/0003-FIX-remove-unneeded-include.patch, recipes/multirnafold/build.sh, recipes/multirnafold/meta.yaml
http://www.rnasoft.ca/download/README.html
http://www.rnasoft.ca/download.html
The MultiRNAFold package contains software for secondary structure prediction of one, two, or many interacting RNA or DNA molecules. It is composed of three pieces of software: SimFold, PairFold and MultiFold.
The programs are part of the RNAsoft suite.
The tarball doesn't include an explicit license file, but the README webpage includes this declaration:
From: http://www.rnasoft.ca/download/README.html
```
Authorship & reference
The MultiRNAFold package is copyrighted under GNU General Public Licence,
by Mirela Andronescu, Zhi Chuan Zhang and Anne Condon, Computer Science UBC.
```
---- …
=> Add recipe for MultiRNAFold v2.1

recipes/scanpy-scripts/meta.yaml
This pull request aims to test the move of scanpy scripts to scanpy 1.9.x and subsequent below changes. This has been tried in that repo, but we want to to test the bioconda artifacts before releasing that new version of scanpy scripts in its repo. Once test with the artifacts pass, we will release there and autobump here.
* PRs require reviews prior …
=> Update scanpy-scripts to scanpy 1.9.x

recipes/hmftools-bam-tools/bamtools.sh, recipes/hmftools-bam-tools/meta.yaml
Fix class-path detection in BASH script
---- …
=> Update hmftools-bam-tools 1.2 recipe

recipes/hmftools-sage/meta.yaml, recipes/hmftools-sage/sage.sh
Fix class-path detection in BASH script
---- …
=> Update hmftools-sage 3.4 recipe

recipes/gatk4/meta.yaml
Update gatk4 with the newly built gcnvkernel
---- …
=> Update GATK4 to 4.5.0.0

recipes/segalign-full/meta.yaml
SegAlign is a Scalable GPU System for Pairwise Whole Genome Alignments based on LASTZ's seed-filter-extend paradigm.
This recipe has a run requirement on segalign from conda-forge.  It adds recipes from bioconda that are not in conda-forge, namely lastz, ucsc-fatotwobit, and ucsc-twobittofa.
---- …
=> recipe for segalign-full

recipes/cenote-taker3/meta.yaml
Updating `Cenote-Taker 3` to v3.2.1 which has two new dependencies, pandas and pyarrow
[https://github.com/mtisza1/Cenote-Taker3](url)
---- …
=> Update Cenote-Taker3 v3.2.1

recipes/ltr_finder_parallel/build.sh, recipes/ltr_finder_parallel/meta.yaml
Recipe for LTR_FINDER_parallel: https://github.com/oushujun/LTR_FINDER_parallel?tab=readme-ov-file
----
Conda is able …
=> Add LTR_FINDER_parallel

recipes/serotypefinder/build.sh, recipes/serotypefinder/download-db.sh, recipes/serotypefinder/meta.yaml
Update serotypefinder version from v2.0.1 to v.2.0.2
---- …
=> Update serotypefinder to v2.0.2

recipes/infernal/build.sh, recipes/infernal/meta.yaml
=> Update infernal to 1.1.5

recipes/genbank/meta.yaml
=> Add recipe for genbank v0.110

recipes/peptide-shaker/meta.yaml, recipes/peptide-shaker/peptide-shaker.py
=> Update peptide-shaker to 3.0.6

recipes/searchgui/meta.yaml, recipes/searchgui/searchgui.py
=> Update searchgui to 4.3.6

recipes/icescreen/meta.yaml
Update icescreen v1.3.2: https://forgemia.inra.fr/ices_imes_analysis/icescreen/-/releases/v1.3.2
---- …
=> Update icescreen v1.3.2

recipes/kb-python/meta.yaml
kallisto|bustools build fails due to obscure pysam incompatibilities on Python 3.9. Until this is fixed, kb-python should be restricted to older versions of Python.
---- …
=> Update/fix kb-python

recipes/serotypefinder/build.sh, recipes/serotypefinder/meta.yaml
Serotypefinder's db does not have a VERSION file, thus the only way to track it's version is via a commit id. Thus, git is required in the image.
---- …
=> Add git to serotypefinder

recipes/harpy/meta.yaml
I've reconfigured the package release cycle to strip unnecessary things out of the tarball and use the release tarball instead, which is a difference of ~120mb down to 170kb in disk space savings. Modifying the build recipe to reflect that going forward.
---- …
=> Update harpy build to use smaller release instead of source

recipes/ganon/meta.yaml
=> Update ganon to 2.1.0

recipes/snakemake-interface-report-plugins/meta.yaml
=> add snakemake-interface-report-plugins

recipes/mirmachine/meta.yaml
Hi,
I have added run_exports to the recipe manually in the new version.
Cheers,
@sinanugur 
---- …
=> Update mirmachine meta.yaml

recipes/sctriangulate/LICENSE, recipes/sctriangulate/meta.yaml
=> Add recipe for sctriangulate v0.13.0

recipes/mgnify-pipelines-toolkit/meta.yaml
Had forgotten to add the alias for the standard_primer_matching script in the initial merge of the mgnify-pipelines-toolkit to bioconda recipes. This PR adds the missing alias.
---- …
=> Update mgnify-pipelines-toolkit package to add missing alias for standard_primer_matching script

recipes/pharokka/meta.yaml
fix phanotate to lower than v1.6.4, which introduced errors in pharokka
---- …
=> Update Pharokka Recipe fix phanotate to lower than 1.6.4

recipes/scanpy-scripts/meta.yaml
This PR updates properly the scanpy-scripts package to use the released pypi artifact, as it used to be. …
=> Update scanpy-scripts to 1.9.301

recipes/ltr_harvest_parallel/build.sh, recipes/ltr_harvest_parallel/meta.yaml
Added ltr_harvest_parallel from https://github.com/oushujun/EDTA/tree/master/bin/LTR_HARVEST_parallel
----
Conda is …
=> Added ltr_harvest_parallel

.circleci/config.yml, recipes/test/meta.yaml
Related to #44462, this is again testing that the PR merging infrastructure works correctly on circleci builds.
=> Test arm artifact merging, round 2

recipes/dudes/meta.yaml
=> Update dudes to 0.10.0

recipes/multiqc/meta.yaml
See https://github.com/MultiQC/MultiQC/issues/2283
---- …
=> Bump multiqc to do another build

recipes/ionquant/academic_install.py, recipes/ionquant/build.sh, recipes/ionquant/ionquant.py, recipes/ionquant/meta.yaml
Adds the IonQuant application: http://ionquant.nesvilab.org/.
---- …
=> Add IonQuant recipe.

recipes/woltka/meta.yaml
=> Update Woltka to 0.1.6

.circleci/check-for-additional-platforms.sh, .circleci/config.yml, recipes/test/meta.yaml
debugging circleci hash handling
=> Test arm artifact merging 3

recipes/segmetrics/meta.yaml
Update [`segmetrics`](https://bioconda.github.io/recipes/segmetrics/README.html): **1.4** → **1.4.1**
----
Conda is …
=> Update segmetrics to 1.4.1

recipes/minute/meta.yaml
Autobump failed, manual update.
I’m also changing the source URL in the hope that the bot starts recognizing it again.
CC @cnluzon
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built packages/containers. <br …
=> Update minute to 0.6.0

recipes/emboss/meta.yaml
=> add libpdf support to EMBOSS

recipes/hictk/conanfile.txt.patch, recipes/hictk/meta.yaml
=> Update hictk to v0.0.9

recipes/poseidon-trident/meta.yaml
A new version of poseidon-trident. FYI @stschiff @TCLamnidis 
---- …
=> Update poseidon-trident to v1.4.1.0

recipes/aacon/aacon.sh, recipes/aacon/build.sh, recipes/aacon/meta.yaml
Add Amino Acid Conservation tool.
https://www.compbio.dundee.ac.uk/aacon/
=> Add AACon 1.1 recipe

recipes/fairy/build.sh, recipes/fairy/meta.yaml
Adding the method "fairy" (https://github.com/bluenote-1577/fairy). Fairy is a method for approximate coverage calculation intended for read-to-assembly coverage for multi-sample metagenomic binning. 
----
* Please post …
=> Add fairy recipe

recipes/strainr2/build.sh, recipes/strainr2/meta.yaml
=> StrainR2 - Relax R dependencies

recipes/multiqc/meta.yaml
Bump MultiQC and update source URL
---- …
=> Bump Multiqc to v1.21

recipes/curare/meta.yaml
Update Curare to 0.6.0
progressbar2 and biopython were added as dependencies
---- …
=> update Curare to 0.6.0

recipes/ebi-eva-common-pyutils/meta.yaml
Add recipe for ebi-eva-common-pyutils - Library of functions used in tools for the European Variation Archive
Created with `grayskull pypi ebi-eva-common-pyutils`
---- …
=> Add recipe for ebi-eva-common-pyutils

recipes/gecco/meta.yaml
This PR updates GECCO to the latest release.
---- …
=> Update GECCO to `v0.9.10`

recipes/magic-impute/LICENSE, recipes/magic-impute/meta.yaml
Adding magic-impute or magic. Added missing LICENSE file
=> add magic-impute

recipes/influx_si/meta.yaml
=> Update meta.yaml of influx_si v7.0.2

recipes/anndata2ri/meta.yaml
Update recipe to include the increased `rpy2` minimum version introduced in v1.3.1.
[relevant commit](https://github.com/theislab/anndata2ri/commit/d33be9b72ce172188dda49168005e10f7e32d5fe)
----
* …
=> anndata2ri: fix rpy2 dependency for v1.3.1

recipes/jronn/build.gradle, recipes/jronn/build.sh, recipes/jronn/jronn.sh, recipes/jronn/meta.yaml
Add JRONN a.k.a. protein-disorder recipe.
=> Add JRONN recipe

recipes/macs3/meta.yaml
=> Add macs3 recipe

recipes/ionquant/build.sh, recipes/ionquant/ionquant.py, recipes/ionquant/meta.yaml
In the `ionquant` script, `__file__` resolves to the symlink that is called, whereas we need to follow this symlink to find the location of the jar file.
The automated test was actually insufficient to catch this, so I fixed the test clause to ensure the Java program is successfully executed.
I also updated `build.sh` to remove the installation zip when done.
----
* PRs require …
=> Fix IonQuant Recipe

recipes/gum/meta.yaml
=> Update gum to v2.0.2

recipes/captus/meta.yaml
- Due to recent breaking changes in `pandas` we need to restrict it to versions >=2.1.0
---- …
=> captus - add version restriction for pandas (second try)

recipes/mmseqs2/meta.yaml
=> Update MMseqs2 build-number for arm build

recipes/metaeuk/build.sh, recipes/metaeuk/meta.yaml
=> Update metaeuk for linux-aarch64

recipes/spacepharer/build.sh, recipes/spacepharer/meta.yaml
=> Update spacepharer for linux-aarch64

recipes/metabuli/build.sh, recipes/metabuli/meta.yaml
=> Update metabuli for linux-aarch64

recipes/htslib/arm_hwcap.patch, recipes/htslib/meta.yaml
Add `additional-platforms` entry.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Build htslib for linux-aarch64

recipes/bcftools/meta.yaml, recipes/samtools/meta.yaml
Add `additional-platforms` sections.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Build bcftools and samtools for linux-aarch64

recipes/bedtools/meta.yaml
Add additional-platforms sections.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Build bedtools for linux-aarch64

recipes/ms2pip/meta.yaml
New ms2pip development version includes new timsTOF models needed in ms2rescore.
---- …
=> Update MS2PIP to 4.0.0.dev8

recipes/varfish-server-worker/meta.yaml
=> moving org for varfish-server-worker

recipes/ms2rescore/meta.yaml
=> Update ms2pip version in ms2rescore

recipes/macs3/meta.yaml
=> try to build macs for more than one python version

recipes/alignoth/meta.yaml
The repo for alignoth moved from koesterlab to a dedicated organization. This PR updates the recipe accordingly.
---- …
=> Update alignoth repository url

recipes/mitos/meta.yaml
to avoid broken builds for infernal 1.1.4: https://gitlab.com/Bernt/MITOS/-/issues/44
---- …
=> bump mitos2

recipes/jbrowse2/meta.yaml
=> reupload jbrowse2

recipes/taxonkit/meta.yaml
- [TaxonKit v0.16.0](https://github.com/shenwei356/taxonkit/releases/tag/v0.16.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/taxonkit/v0.16.0/total.svg)](https://github.com/shenwei356/taxonkit/releases/tag/v0.16.0)
- `taxonkit create-taxdump`:
- TaxIds are generated from the hash value of "rank+taxon_name", this allowed duplicated names with different ranks (common in GTDB). [#92](https://github.com/shenwei356/taxonkit/issues/92).
- `taxonkit taxid-changelog/create-taxdump`:
- Add notes about the possible error records in taxid-changelog built from taxonomic data created by `create-taxdump`. [#91](https://github.com/shenwei356/taxonkit/issues/91)
- Dont't worry, a single version of taxonomic data created by `taxonkit …
=> Update TaxonKit to v0.16.0

recipes/gxf2chrom/build.sh, recipes/gxf2chrom/meta.yaml
=> Add gxf2chrom

recipes/pbiotools/meta.yaml, recipes/ribotools/meta.yaml
Please add ribotools to bioconda. Ribotools, an add-on to [Rp-Bp](http://rp-bp.readthedocs.io/en/latest/), is a toolbox for the analysis of matched ribosome profiling (Ribo-seq) and RNA sequencing (RNA-seq) data.
----
* Please …
=> Add ribotools

recipes/dart/build.sh, recipes/dart/meta.yaml
Building linux-aarch64 for dart
---- …
=> linux-aarch64 build for dart

recipes/pybigtools/build.sh, recipes/pybigtools/meta.yaml
=> Update pybigtools source URL

recipes/pybarrnap/meta.yaml
=> Add recipe for pybarrnap v0.3.0

recipes/colabfold/meta.yaml
jax 0.4.25 broke colabfold, this fixes the issue.
---- …
=> colabfold: fix incompatibility with jax and dm-tree 

recipes/rdp_classifier/meta.yaml, recipes/rdp_classifier/rdp_classifier.sh
This PR updates RDP Classifier to v.2.14 ([released 2023-08-23](https://sourceforge.net/projects/rdp-classifier/files/rdp-classifier/))
---- …
=> Update `RDP Classifier` to 2.14

recipes/hmmer/meta.yaml
Add additional-platforms entry.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Build hmmer for linux-aarch64

recipes/architeuthis/meta.yaml
This adds the architeuthis package to bioconda whcih should fit well here. 
> architeuthis is a fast standalone command to supplement the Kraken suite of software tools such like Kraken2, KrakenUniq, and Bracken. I saw myself repeatedly rewriting the same code in my pipelines when dealing with Kraken output, like merging files or maninpulating lineage annotations. It also adds some functionality to dive deeper into the individual k-mer classifications for reads.
It's my first Golang package, so hopefully that works...
----
* New recipes not …
=> Add architeuthis

recipes/vcf-validator/LICENSE, recipes/vcf-validator/LICENSE_ODB, recipes/vcf-validator/build.sh, recipes/vcf-validator/meta.yaml
Add recipes for [vcf-validator](https://github.com/EBIvariation/vcf-validator)
---- …
=> Add VCF-Validator

recipes/merge-gbk-records/meta.yaml
Add a new recipe for the small utility script `merge-gbk-records` which merges Genbank format records
----
Conda is …
=> Add recipe for merge-genbank-records

recipes/ms2rescore/meta.yaml
The most recent pyteomics version throws pickle errors, therefore we need to constraint the version to the most recent working version (4.6.3)
---- …
=> Update ms2rescore: Constraint pyteomics version

recipes/seqkit/meta.yaml
- [SeqKit v2.8.0](https://github.com/shenwei356/seqkit/releases/tag/v2.8.0) - 2024-03-11 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.8.0/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.8.0)
- `seqkit stats`:
- Add column `N50_num`, an alias of L50, [#15](https://github.com/shenwei356/seqkit/issues/15).
- `seqkit seq/locate/fish/watch`:
- Removing the flag `-V/--validate-seq-length`. Now the whole sequence will be checked if `-v/--validate-seq` is given.
- `seqkit amplicon`:
- Fix the speed problem, introduced in v2.7.0. [#439](https://github.com/shenwei356/seqkit/issues/439).
- Slightly faster by reusing objects.
- `seqkit seq`:
- Change the threshold sequence length for parallelizing …
=> Update SeqKit to v2.8.0

recipes/segalign-full/meta.yaml
Remove twoBitToFa from the requirements
---- …
=> segalign-full does not need twoBitToFa

recipes/viralmsa/meta.yaml
This PR updates the `meta.yaml` file for `viralmsa` to follow the `extra` section for `identifiers` and `maintainers` as per the following comment on another one of my PRs:
> The identifier goes into an extra section for example together with the maintainer. The recipe which you modified had this for example. Can you please create an extra PR for the recipe that you update. Thanks!
https://github.com/bioconda/bioconda-recipes/pull/46292#pullrequestreview-1926920849
----
* New recipes not directly relevant to the biological sciences need to be …
=> Update viralmsa meta.yaml

recipes/viral_consensus/meta.yaml
This PR updates the `meta.yaml` file for `viral_consensus` to follow the `extra` section for `identifiers` and `maintainers` as per the following comment on another one of my PRs:
> The identifier goes into an extra section for example together with the maintainer. The recipe which you modified had this for example. Can you please create an extra PR for the recipe that you update. Thanks!
https://github.com/bioconda/bioconda-recipes/pull/46292#pullrequestreview-1926920849
----
* New recipes not directly relevant to the biological sciences need …
=> Update viral_consensus meta.yaml

recipes/tn93/meta.yaml
I added identifiers to the `tn93` recipe.
---- …
=> Added identifiers to tn93

recipes/perl-digest-sha1/meta.yaml
=> perl-digest-sha1: enable linux-aarch64 builds

recipes/macs3/meta.yaml
=> Update MACS3 recipe to build on python 3.9

recipes/poppunk/meta.yaml
=> Bump poppunk to v2.6.4

recipes/gw/meta.yaml
=> Reduce requirements for GW

recipes/ribotin/build.sh, recipes/ribotin/makefile.patch, recipes/ribotin/meta.yaml
Update ribotin to version 1.3
---- …
=> Update ribotin to version 1.3

recipes/gottcha2/meta.yaml, recipes/gottcha2/post-link.sh
GOTTCHA2 is an application of signature-based metagenomic taxonomic profiling method with significantly smaller false discovery rates (FDR) that is laptop deployable.  The tool uses minimap2 to map reads to signature databases that needs to be download separately.
---- …
=> Add gottcha2

recipes/poppunk/meta.yaml
=> Bump poppunk to v2.6.5

recipes/minimap2/meta.yaml
=> bump minimap2 so it's built and posted

recipes/snakemake/meta.yaml
=> snakemake: add linux-aarch64 build

recipes/mafft/meta.yaml
=> mafft: add linux-aarch64 build

recipes/vsearch/meta.yaml
=> vsearch: add linux-aarch64 build

recipes/callingcardstools/meta.yaml
In preparation for an update to the package, I am adding pyranges as a dependency. The build number has been incremented as a result
=> adding pyranges as a dep; incrementing build number

recipes/iqtree/meta.yaml
=> Update iqtree to 2.3.0

recipes/biocamlib/build.sh, recipes/biocamlib/meta.yaml
BiOCamLib is an OCaml foundation upon which a number of the bioinformatics tools are built,
including KPop (https://github.com/PaoloRibeca/KPop). It consists of four tools:
1. RC, which can efficiently compute the reverse complement of sequences.
2. Octopus, which is a high-throughput program to compute the transitive closure of strings.
3. Parallel, which allows the splits and processes an input file chunk-wise using a reader/workers/writer model.
4. FASTools, which is a Swiss-knife tool for the manipulation of FASTA/FASTQ files.
----
* New …
=> Add BioCamLib

recipes/fragpipe/meta.yaml
These libraries are necessary for the database splitting feature of FragPipe.
---- …
=> Add libraries necessary for database splitting in FragPipe.

recipes/csvtk/meta.yaml
- [csvtk v0.30.0](https://github.com/shenwei356/csvtk/releases/tag/v0.30.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/csvtk/v0.30.0/total.svg)](https://github.com/shenwei356/csvtk/releases/tag/v0.30.0)
- `csvtk`:
- grouping subcommands in help message.
- add a new global flag `--quiet`. [#261](https://github.com/shenwei356/csvtk/issues/261)
- add a new global flag `-U, --delete-header` for disable outputing the header row. Supported commands: concat, csv2tab/tab2csv, csv2xlsx/xlsx2csv, cut, filter, filter2, freq, fold/unfold, gather, fmtdate, grep, head, join, mutate, mutate2, replace, round, sample. [#258](https://github.com/shenwei356/csvtk/issues/258)
- support more commands with `-Z/--show-row-number`: head.
- …
=> Update csvtk to v0.30.0

recipes/clair3/meta.yaml
=> Update clair3 to v1.0.6

recipes/revoluzer/meta.yaml
=> Add revoluzer 0.1.5

recipes/falco/meta.yaml
Updating falco to new version.
---- …
=> Falco update

recipes/pybedtools/meta.yaml
=> linux-aarch64 build for pybedtools

recipes/bgreat/meta.yaml
=> linux-aarch64 build for bgreat

recipes/kallisto/meta.yaml
=> update kallisto: enable linux-aarch64 build

recipes/bowtie/meta.yaml
=> bowtie: enable linux-aarch64 build

recipes/star-fusion/meta.yaml
Update star-fusion to 1.13.0
---- …
=> Update star-fusion to 1.13.0

recipes/revoluzer/meta.yaml
=> bump revoluzer 0.1.6

recipes/psm-utils/meta.yaml
Fix the entrypoint for the `psm-utils` package.
---- …
=> Update psm-utils: Fix entrypoint

recipes/python-edlib/meta.yaml
=> update python-edlib: enable linux-aarch64 build

recipes/alcor/meta.yaml
=> linux-aarch64 build for alcor

recipes/ac/meta.yaml
=> linux-aarch64 build for ac

recipes/mgatk/meta.yaml
=> Update mgatk recipe

recipes/pyspoa/meta.yaml
=> pyspoa: enable linux-aarch64 build

recipes/pyrodigal/meta.yaml
=> pyrodigal: enable linux-aarch64 build

recipes/pyhmmer/meta.yaml
=> pyhmmer: enable linux-aarch64 build

recipes/fastp/meta.yaml
update fastp adding new platform
---- …
=> update fastp adding new platform

recipes/star/build.sh, recipes/star/meta.yaml
update star for linux-aarch64
---- …
=> update star adding new platform

recipes/hairsplitter/build.sh, recipes/hairsplitter/conda_build_config.yaml, recipes/hairsplitter/meta.yaml
Add recipe for HairSplitter
---- …
=> Add recipe hairsplitter

recipes/pybigwig/build.sh, recipes/pybigwig/meta.yaml
=> pybigwig: enable linux-aarch64 build

recipes/pyfamsa/meta.yaml
=> pyfamsa: enable linux-aarch64 build

recipes/bx-python/meta.yaml
=> bx-python: enable linux-aarch64 build

recipes/parasail-python/meta.yaml
=> parasail-python: enable linux-aarch64 build

recipes/pyabpoa/meta.yaml
=> pyabpoa: enable linux-aarch64 build

recipes/cyvcf2/meta.yaml
=> cyvcf2: enable linux-aarch64 build

recipes/pixelator/LICENSE.txt, recipes/pixelator/meta.yaml
=> Update pixelator to 0.16.2

recipes/preseq/meta.yaml
update preseq adding new platform
---- …
=> update preseq adding new platform

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
=> linux-aarch64 build for bioawk

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
I have tested it, and it looks good for me
---- …
=> linux-aarch64 build for bfc

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
=> linux-aarch64 build for Bcalm

recipes/fq/meta.yaml
update fq adding new platform
---- …
=> update fq adding new platform

recipes/seqkit/meta.yaml
Add linux-aarch64 build for seqkit
---- …
=> Add linux-aarch64 build for seqkit

recipes/sigprofilerplotting/meta.yaml
=> Add SigProfilerPlotting recipe

recipes/mosdepth/meta.yaml
This PR is to update mosdepth to `0.3.7` with updates to htslib 1.19.1
---- …
=> Update mosdepth to 0.3.7

recipes/baredsc/meta.yaml
The nightly builds on Azure are crashing and this is the last recipe in progress in the logs. Testing out a build to see if we can figure out what is happening.
---- …
=> bump baredsc to test build

recipes/sigprofilermatrixgenerator/meta.yaml
=> Add SigProfilerMatrixGenerator recipe

recipes/ltr_harvest_parallel/meta.yaml
ltr_harvest_parallel: Removed ver for genometools-genometools
---- …
=> ltr_harvest_parallel: Removed ver for genometools-genometools

recipes/ltr_finder_parallel/meta.yaml
ltr_finder_parallel: Removed ver constraint for ltr_finder
---- …
=> ltr_finder_parallel: Removed ver constraint for ltr_finder

recipes/splitcode/build.sh, recipes/splitcode/meta.yaml
Add splitcode recipe. splitcode is a bioinformatics software tool for "Flexible parsing, interpretation, and editing of technical sequences".
---- …
=> Add splitcode recipe

recipes/cenote-taker3/meta.yaml
Update Cenote-Taker3 v3.3.0
---- …
=> Update Cenote-Taker3 v3.3.0

recipes/tb-profiler/meta.yaml
The version on one dependancy has been updated
=> update tb-profiler dependencies

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
I have tested it, and it looks well
---- …
=> linux-aarch64 build for abundancebin

build-fail-blacklist, recipes/ucsc-bedclip/build.sh, recipes/ucsc-bedclip/conda_build_config.yaml, recipes/ucsc-bedclip/meta.yaml, recipes/ucsc-bedclip/patch1.patch
update ucsc-bedclip adding new platform
---- …
=> update ucsc-bedclip adding new platform

recipes/ntsynt/meta.yaml
Updating ntSynt build to pin lower btllib version, due to potential issues in current version
---- …
=> Update ntsynt build

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
=> linux-aarch64 build for mappy

recipes/arborator/meta.yaml
This is a new Arborator tool release on conda from https://github.com/phac-nml/arborator
=> arborator v1.0.0

recipes/rgi/meta.yaml
Issue is described here: https://github.com/bioconda/bioconda-recipes/issues/46581
pyrodigal [v3.0.0](https://github.com/althonos/pyrodigal/releases/tag/v3.0.0) renamed OrfFinder to GeneFinder, breaking the use of pyrodigal in rgi.
---- …
=> update rgi pinning for pyrodigal

recipes/locidex/meta.yaml
New Locidex tool v0.0.1 https://github.com/phac-nml/locidex/tree/main
=> locidex v0.1.1 recipe

recipes/lemur/meta.yaml
Adding the `lemur` CLI tool. 
---- …
=> Add lemur v1.0.0

recipes/bamtools/meta.yaml
=> bamtools: add linux-aarch64 build

recipes/seqtk/meta.yaml
=> seqtk: add linux-aarch64 build

recipes/dimet/meta.yaml
=> update dimet for Ben

recipes/umi_tools/meta.yaml
update umi_tools adding new platform
---- …
=> update umi_tools adding new platform

build-fail-blacklist
treeqmc is a duplicate of tree-qmc, based on dev feedback (https://github.com/molloy-lab/TREE-QMC/issues/4) we are going to add this one to the blacklist so that only the tree-qmc version receives future updates
Without the typo this time! 
---- …
=> add treeqmc to blacklist

recipes/gmap/build.sh, recipes/gmap/meta.yaml
=> Update gmap to 2024.03.15

recipes/scib/meta.yaml
=> Update scib recipe

recipes/harpy/meta.yaml
This PR adds the new `0.8.0` version of Harpy, which includes build changes in the `meta.yaml`, hence having to submit the PR manually.
---- …
=> Harpy 0.8.0 + recipe change

recipes/raxml/build.sh, recipes/raxml/meta.yaml
Related to: https://github.com/stamatak/standard-RAxML/commit/69a7edcba961f95f732e07ce64e7e5b1c7ae548b
---- …
=> raxml: add linux-aarch64 build

recipes/wfa2-lib/build.sh, recipes/wfa2-lib/meta.yaml, recipes/wfa2-lib/patches/1-macOS_endian.patch
=> wfa2-lib: enable linux-aarch64 build

recipes/rsv-typer/meta.yaml
Update rsv-typer to 0.3.0
---- …
=> update from 0.2.0 to 0.3.0

recipes/vcftools/meta.yaml
=> vcftools: add linux-aarch64 build

recipes/prodigal/meta.yaml
=> prodigal: add linux-aarch64 build

recipes/igv/build.sh, recipes/igv/meta.yaml
=> Update IGV to 2.17.3

recipes/abromics_galaxy_json_extractor/meta.yaml
Update abromics_galaxy_json_extractor to 0.8.3.5
=> Update abromics_galaxy_json_extractor to 0.8.3.5

recipes/ucsc-fatovcf/build.sh, recipes/ucsc-fatovcf/htmshell.patch, recipes/ucsc-fatovcf/meta.yaml, recipes/usher/meta.yaml
=> usher & ucsc-fatovcf: add linux-aarch64 build

recipes/abromics_galaxy_json_extractor/meta.yaml
=> Update to 0.8.3.6

recipes/primerforge/meta.yaml
Added an installation for `primerForge` found at https://github.com/dr-joe-wirth/primerForge
@rpetit3 can you serve as a reviewer?
---- …
=> Add primerforge

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
=> linux-aarch64 build for selam

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
=> linux-aarch64 build for annonars

recipes/hictkpy/CMakeLists.txt.patch, recipes/hictkpy/build.sh, recipes/hictkpy/conanfile.txt.patch, recipes/hictkpy/meta.yaml, recipes/hictkpy/pyproject.toml.patch
=> Update hictkpy to v0.0.4

recipes/ntroot/build.sh, recipes/ntroot/meta.yaml, recipes/ntroot/ntroot.patch
ntRoot: Ancestry inference using genomic data
---- …
=> Add ntroot recipe

recipes/gb-io/build.sh, recipes/gb-io/meta.yaml
This PR adds a build recipe for `gb-io`, a Python package based on the `gb-io` Rust crate for fast parsing and serializing of GenBank files.
---- …
=> Add `gb-io` Python package

recipes/viennarna/build.sh, recipes/viennarna/meta.yaml
=> ViennaRNA: add linux-aarch64 build

recipes/trycycler/meta.yaml
Update [trycycler](https://bioconda.github.io/recipes/trycycler/README.html): 0.5.4 → 0.5.5
=> Update trycycler to 0.5.5

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
=> linux-aarch64 build for anise_basil

recipes/balrog/meta.yaml
=>  linux-aarch64 build for balrog

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.20

recipes/assembly_finder/meta.yaml
Updating assembly_finder's recipe to include changed dependencies, license and docs_url
---- …
=> Update assembly_finder to v0.6.0

recipes/r-liger/meta.yaml
Hi all,
Noticed that people were using bioconda to install our latest update of liger and figured I'd come in and try to sync the dependencies with the Imports field from CRAN.
Best,
Andrew Robbins
---- …
=> Update - clean dependencies for liger

recipes/last/build.sh, recipes/last/meta.yaml
=> last: add linux-aarch64 build

recipes/freebayes/meta.yaml, recipes/vcflib/build.sh, recipes/vcflib/meta.yaml
=> freebayes: add linux-aarch64 build

recipes/pasa/build.sh, recipes/pasa/meta.yaml
=> Update pasa recipe

recipes/vcflib/backport_pr_394.patch, recipes/vcflib/meta.yaml
=> Patch vcflib recipe

recipes/trinity/build.sh, recipes/trinity/meta.yaml
=> Update trinity recipe

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
=> linux-aarch64 build for bcftools-gtc2vcf-plugin

recipes/tb-profiler/build.sh, recipes/tb-profiler/meta.yaml
I have tested, and it works on ARM
---- …
=> linux-aarch64 build for bcov

recipes/bcbio-gff/meta.yaml
xref: https://github.com/chapmanb/bcbb/pull/141
---- …
=> remove unneded pin, fixed upstream

recipes/genoflu/meta.yaml
=> genoflu version 1.03

recipes/plass/build.sh, recipes/plass/meta.yaml
=> Update plass to 5.cf8933

recipes/python-edlib/LICENSE, recipes/python-edlib/build.sh, recipes/python-edlib/meta.yaml
=> Update python-edlib recipe

recipes/flye/0001-Makefile-aarch64.patch, recipes/flye/build.sh, recipes/flye/meta.yaml
=> flye: enable linux-aarch64 build

recipes/rabbitqcplus/build.sh, recipes/rabbitqcplus/meta.yaml
RabbitQCPlus is a highly optimized and easy-to-use tool for sequencing data that successfully addresses efficiency issues in quality control. Our main contributions are three-fold:
- Improving the efficiency of quality control for both short-read and long-read sequencing data on modern multi-core CPUs featuring fast SSDs;
- Reducing the compute resources required to meet the peak I/O bandwidth by improving per-thread perfor-mance;
- Eliminating the performance bottleneck when processing gzip-compressed FASTQ files by integrating highly tuned fast (de)compression engines.
----
* If this PR adds or updates a recipe, use …
=> Add rabbitqcplus

recipes/cgatcore/meta.yaml
=> Update cgatcore 0.6.16

recipes/test/meta.yaml
This adds/updates a test package (likely to be deleted later from channel and biocontainers) to test that, once this PR is merged into master, bioconda-utils handle-merged-pr correctly picks up the package & container artifacts built on GitHub Actions and uploads them appropriately.
This will be merged to the mock-master target branch `target-for-arm-osx`.
=> [test branch] Test osx-arm64 merging to mock target branch

recipes/prank/LICENSE.md, recipes/prank/meta.yaml
=> prank: add linux-aarch64 build

recipes/paml/meta.yaml
=> paml: add linux-aarch64 build

recipes/busco/0001-Set-conda-distribution.patch, recipes/busco/meta.yaml
=> Update to 5.7.1

recipes/rabbitqcplus/build.sh, recipes/rabbitqcplus/meta.yaml
update rabbitqcplus 2.2.9, fix illegal instruction
---- …
=> update rabbitqcplus 2.2.9, fix illegal instruction

build-fail-blacklist, recipes/cgat-apps/meta.yaml
=> Update cgat-apps 0.7.0

.github/check-for-additional-platforms.sh, .github/workflows/PR-arm.yml, .github/workflows/master-arm.yml, recipes/test/meta.yaml
This adds/updates a test package (likely to be deleted later from channel and biocontainers) to test that, once this PR is merged into master, bioconda-utils handle-merged-pr correctly picks up the package & container artifacts built on GitHub Actions and uploads them appropriately.
This will be merged to the mock-master target branch `target-for-arm-osx`.
=> [test branch] Test osx-arm64 merging to mock target branch (2)

recipes/arborator/meta.yaml
Added scipy missing dependency to the conda package
=> arborator v1.0.0 build #1 -> added missing scipy dependency

recipes/ddrage/meta.yaml
This PR updates ddRAGE to Version 1.8.1 and switches the source link over to PyPI.
---- …
=> Update ddRAGE to 1.8.1

recipes/mtgrasp/build.sh, recipes/mtgrasp/meta.yaml
mtGrasp: reference-grade de novo animal mitochondrial genome assembly and standardization pipeline
----
Conda is able …
=> Add mtgrasp

recipes/graphembed/meta.yaml
Update graphembed to 0.1.1 with a new centric AUC
---- …
=> Update graphembed v0.1.1

recipes/seqkit/meta.yaml
- [SeqKit v2.8.1](https://github.com/shenwei356/seqkit/releases/tag/v2.8.1) - 2024-04-07 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.8.1/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.8.1)
- `seqkit sana`:
- Add support for FASTQ files with IDs in the separator (`+`, 3rd) lines.. [#446](https://github.com/shenwei356/seqkit/pull/446), [#429](https://github.com/shenwei356/seqkit/issues/429), [#408](https://github.com/shenwei356/seqkit/issues/408)
- `seqkit subseq`:
- Add some docs to show how to keep the original order of sequences when extracting with BED: compress the input FASTA file. [#451](https://github.com/shenwei356/seqkit/issues/451)
---- …
=> Update SeqKit to v2.8.1

recipes/gofasta/meta.yaml
=> gofasta: add linux-aarch64 build

recipes/kma/meta.yaml
=> kma: add linux-aarch64 build

recipes/cgat-apps/meta.yaml
Update cgat-apps v0.7.2 to remove dependancies
---- …
=> Update cgat-apps v0.7.2

recipes/htseq/meta.yaml
=> htseq: add linux-aarch64 build

recipes/tidyp/build.sh, recipes/tidyp/meta.yaml
=> tidyp: add linux-aarch64 build

recipes/ucsc-fatotwobit/build.sh, recipes/ucsc-fatotwobit/htmshell.patch, recipes/ucsc-fatotwobit/meta.yaml
=> ucsc-fatotwobit: add linux-aarch64 build

recipes/gseapy/meta.yaml
=> gseapy: add linux-aarch64 build

recipes/cgat-apps/meta.yaml, recipes/r-dimsum/meta.yaml
Update r-dimsum to v1.3.1., add run_exports statement and requirements for r-base and fastqc
---- …
=> Update r-dimsum to v1.3.1

recipes/ncls/meta.yaml
=> ncls: add linux-aarch64 build

recipes/ncbi-ngs-sdk/meta.yaml
=> ncbi-ngs-sdk: add linux-aarch64 build

recipes/severus/meta.yaml
Update to version 1.0 (version change from 0.x.x seemed to broke autobump)
---- …
=> Severus 1.0

recipes/clair3/meta.yaml
=> Update Clair3 to v1.0.7

recipes/ntedit/build.sh, recipes/ntedit/meta.yaml
Updating ntEdit build + dependencies for 2.0.0 release
---- …
=> Update ntedit to 2.0.0

recipes/pychopper/meta.yaml
Updating pychopper to the new url
---- …
=> Bump pychopper

recipes/gmap/build.sh, recipes/gmap/meta.yaml
=> gmap: add linux-aarch64 build

recipes/csvtk/meta.yaml
=> csvtk: add linux-aarch64 build

recipes/whatshap/meta.yaml
=> whatshap: add linux-aarch64 build

recipes/glimmerhmm/meta.yaml
=> glimmerhmm: add linux-aarch64 build

recipes/ucsc-wigtobigwig/htmshell.patch, recipes/ucsc-wigtobigwig/meta.yaml
=> ucsc-wigtobigwig: add linux-aarch64 build

recipes/segalign-full/meta.yaml
Update to a newer version of SegAlign
---- …
=> Update to newer version, reset build number

recipes/isonform/meta.yaml
Adding RNA-seq assembler for long reads 
---- …
=> Add isonform

recipes/pycomo/meta.yaml
Adding a new recipe to bioconda for the pycomo package. Pycomo is only relevant for biological research and not part of other conda channels.
---- …
=> Add recipe for pycomo

recipes/btllib/build.sh, recipes/btllib/meta.yaml
Ignore coverage tests when building from conda
---- …
=> Fix btllib recipe

recipes/ncbi-vdb/build.sh, recipes/ncbi-vdb/env.cmake.patch, recipes/ncbi-vdb/meta.yaml
=> Update ncbi-vdb recipe

recipes/galitime/meta.yaml
Add a new recipe for galitime
---- …
=> Add galitime recipe

recipes/ncbi-vdb/meta.yaml
=> ncbi-vdb: enable linux-aarch64 build

recipes/perl-algorithm-cluster/meta.yaml
=> perl-algorithm-cluster: add linux-aarch64 build

recipes/gadem/meta.yaml
=> gadem: add linux-aarch64 build

build-fail-blacklist, recipes/prosampler/build.sh, recipes/prosampler/meta.yaml
=> prosampler: add linux-aarch64 build

recipes/weeder/meta.yaml
=> weeder: add linux-aarch64 build

recipes/homer/meta.yaml
=> homer: add linux-aarch64 build

recipes/dinamo/meta.yaml
=> dinamo: add linux-aarch64 build

recipes/cenote-taker3/meta.yaml
Update Cenote-Taker3 v3.3.1
---- …
=> Update Cenote-Taker3 v3.3.1

recipes/gubbins/meta.yaml
Updates to Gubbins v3.3.5
---- …
=> Update to v3.3.5

recipes/ddocent/meta.yaml
=> Update vcflib requirement for dDocent

recipes/taxonomy/meta.yaml
taxonomy fails on the nightly osx build, saying a build number bump is needed.
---- …
=> bump build number for taxonomy

recipes/ms2rescore-rs/build.sh, recipes/ms2rescore-rs/meta.yaml
Add ms2rescore-rs recipe (Rust-based dependencies for existing ms2rescore bioconda package).
---- …
=> Add ms2rescore-rs recipe

build-fail-blacklist, recipes/maaslin2/meta.yaml
Updating Maaslin2 recipe to latest bioC version.
=> Update Maaslin2 version to use latest from BioC

recipes/pairix/meta.yaml
=> pairix: add linux-aarch64 build

recipes/hyphy/build.sh, recipes/hyphy/meta.yaml
=> hyphy: add linux-aarch64 build

build-fail-blacklist, recipes/xxmotif/conda_build_config.yaml, recipes/xxmotif/fix-build.patch, recipes/xxmotif/meta.yaml
=> xxmotif: add linux-aarch64 build

recipes/localhgt/build.sh, recipes/localhgt/conda_build_config.yaml, recipes/localhgt/meta.yaml
=> add localhgt

recipes/iow/meta.yaml
=> iow: add linux-aarch64 build

recipes/seqsizzle/LICENSE.md, recipes/seqsizzle/build.sh, recipes/seqsizzle/meta.yaml
Add new TUI package: seqsizzle
---- …
=> Add seqsizzle

recipes/helitronscanner/HelitronScanner.sh, recipes/helitronscanner/build.sh, recipes/helitronscanner/meta.yaml
=> Added HelitronScanner

recipes/sorted_nearest/meta.yaml
=> sorted_nearest: add linux-aarch64 build

recipes/sniffles/meta.yaml
Two libraries necessary to run sniffles v2.3.2 are missing from the meta.yaml
I have added them in order for conda to install them as requirements 
---- …
=> Update sniffles requirements

recipes/ucsc-gtftogenepred/htmshell.patch, recipes/ucsc-gtftogenepred/meta.yaml
=> ucsc-gtftogenepred: add linux-aarch64 build

recipes/pyrle/meta.yaml
=> pyrle: add linux-aarch64 build

recipes/mawk/meta.yaml
=> mawk: add linux-aarch64 build

recipes/grabix/meta.yaml
=> grabix: add linux-aarch64 build

recipes/seqfu/build.sh, recipes/seqfu/meta.yaml
=> seqfu: add linux-aarch64 build

recipes/staden_io_lib/meta.yaml
=> staden_io_lib: add linux-aarch64 build

recipes/ntedit/meta.yaml
=> Update ntedit build

recipes/haddock_biobb/build.sh, recipes/haddock_biobb/meta.yaml, recipes/haddock_biobb/post-link.sh
=> [haddock_biobb] New package

recipes/ntroot/meta.yaml
=> Update ntroot build

recipes/tir-learner/build.sh, recipes/tir-learner/meta.yaml
=> Added TIR-Learner

recipes/libmaus2/build.sh, recipes/libmaus2/meta.yaml
=> libmaus2: add linux-aarch64 build

recipes/delly/build.sh, recipes/delly/meta.yaml
Always build from sources
---- …
=> delly: add linux-aarch64 build

recipes/hictkpy/conanfile.txt.patch, recipes/hictkpy/meta.yaml
=> Update hictkpy to v0.0.5

recipes/hictk/conanfile.txt.patch, recipes/hictk/meta.yaml
=> Update hictk to v0.0.12 and enable linux-aarch64 builds

recipes/gmap/build.sh, recipes/gmap/meta.yaml
=> Try building gmap on OSX

recipes/salty/meta.yaml
=> Update salty to 1.0.6

recipes/mess/meta.yaml
PR for updating mess to v0.8.0 and recipe cleanup (new dependencies, license, doc url...)
---- …
=> Update mess recipe to 0.8.0

recipes/miniasm/meta.yaml
=> miniasm: add linux-aarch64 build

recipes/mummer/meta.yaml
=> mummer: add linux-aarch64 build

recipes/tcdemux/meta.yaml
Pinning bbmap in this recipe as a workaround for https://github.com/TomHarrop/tcdemux/issues/23
---- …
=> Update tcdemux pinning

recipes/ucsc-bedtobigbed/htmshell.patch, recipes/ucsc-bedtobigbed/meta.yaml
=> ucsc-bedtobigbed: add linux-aarch64 build

recipes/intarna/meta.yaml
=> intarna: add linux-aarch64 build

recipes/ucsc-twobitinfo/htmshell.patch, recipes/ucsc-twobitinfo/meta.yaml
=> ucsc-twobitinfo: add linux-aarch64 build

recipes/pyfastx/meta.yaml
=> pyfastx: add linux-aarch64 build

recipes/umis/meta.yaml
=> umis: add linux-aarch64 build

recipes/atropos/meta.yaml
=> atropos: add linux-aarch64 build

recipes/pytabix/meta.yaml
=> pytabix: add linux-aarch64 build

recipes/vcfanno/meta.yaml
=> vcfanno: add linux-aarch64 build

recipes/crispresso2/meta.yaml
=> crispresso2: add linux-aarch64 build

recipes/pb-falcon/meta.yaml, recipes/python-msgpack/meta.yaml
=> pb-falcon & python-msgpack: add linux-aarch64 build

recipes/taxonkit/meta.yaml
=> taxonkit: add linux-aarch64 build

recipes/pbgzip/build.sh, recipes/pbgzip/meta.yaml
=> pbgzip: add linux-aarch64 build

recipes/deeptoolsintervals/meta.yaml
=> deeptoolsintervals: add linux-aarch64 build

recipes/localhgt/meta.yaml
=> Update description for localhgt in the same version

recipes/rust-bio-tools/meta.yaml, recipes/starcode/meta.yaml
=> rust-bio-tools & starcode: add linux-aarch64 build

recipes/phyloacc/build.sh, recipes/phyloacc/meta.yaml
I've added a symlink to the `phyloacc.py` executable so it can be called as just `phyloacc`.
=> Update PhyloAcc recipe

recipes/localhgt/meta.yaml
Revise a bug in localhgt v1.0.1. 
---- …
=> Update localhgt v1.0.1

recipes/haddock_biobb/build.sh, recipes/haddock_biobb/meta.yaml, recipes/haddock_biobb/post-link.sh
=> [haddock_biobb] update

recipes/ivar/build.sh, recipes/ivar/meta.yaml
=> ivar: add linux-aarch64 build

recipes/ucsc-liftover/build.sh, recipes/ucsc-liftover/htmshell.patch, recipes/ucsc-liftover/meta.yaml
=> ucsc-liftover: add linux-aarch64 build

recipes/primer3-py/meta.yaml
=> primer3-py: add linux-aarch64 build

recipes/samblaster/build.sh, recipes/samblaster/meta.yaml
=> samblaster: add linux-aarch64 build

recipes/alfred/build.sh, recipes/alfred/meta.yaml
=> alfred: add linux-aarch64 build

recipes/ucsc-genepredtobed/build.sh, recipes/ucsc-genepredtobed/htmshell.patch, recipes/ucsc-genepredtobed/meta.yaml
=> ucsc-genepredtobed: add linux-aarch64 build

recipes/bioconductor-deseq2/meta.yaml
On multiple occasions (https://github.com/bioconda/bioconda-recipes/pull/23290, https://github.com/bioconda/bioconda-recipes/pull/37391), shrinkage methods have been added to this recipe since they're pretty core to function.
Unfortunately they're only 'suggests' in the R package, so they get wiped on updates. Nevertheless, I'm reintroducing here. 
----
* PRs require reviews prior …
=> Update meta.yaml for DESeq2 to include shrinkage methods

recipes/wisecondorx/meta.yaml
bump wisecondorx to latest version
---- …
=> bump wisecondorx

recipes/dodge/meta.yaml, recipes/salty/meta.yaml
=> Update dodge to v1.0.0

recipes/exonerate/build.sh, recipes/exonerate/conda_build_config.yaml, recipes/exonerate/meta.yaml
=> exonerate: add linux-aarch64 build

recipes/shiver/build.sh, recipes/shiver/meta.yaml
Use new tests that check required external programs can be run and required python modules can be imported
=> Update to version v1.7.1, added better tests

recipes/goleft/build.sh, recipes/goleft/meta.yaml
=> goleft: add linux-aarch64 build

recipes/hicexplorer/meta.yaml
We have the same issue as here with scikit-learn>=1.4: https://github.com/scikit-learn/scikit-learn/discussions/28388
=> update hicexplorer scikit-learn requirement

recipes/giatools/meta.yaml
Add recipe for giatools package.
This is a Python module which combines the tools required by many tool wrappers in [GIA](https://github.com/BMCV/galaxy-image-analysis). In the current version 0.1, only the function [`giatools.io.imread`](https://github.com/BMCV/giatools/blob/09ccfa1577c0d1c0dc33b795d240c27d3d32728e/giatools/io.py#L13) is provided, but more will be added in the future.
---- …
=> Add giatools recipe

recipes/infernal/build.sh, recipes/infernal/meta.yaml
=> infernal: add linux-aarch64 build

recipes/kmc/meta.yaml
=> kmc: add linux-aarch64 build

recipes/cdbtools/build.sh, recipes/cdbtools/meta.yaml
=> cdbtools: add linux-aarch64 build

recipes/trimal/build.sh, recipes/trimal/meta.yaml
=> trimal: add linux-aarch64 build

recipes/nextalign/meta.yaml, recipes/nextalign/run_test.sh
=> nextalign: add linux-aarch64 build

recipes/illumina-interop/build.sh, recipes/illumina-interop/meta.yaml
=> illumina-interop: add linux-aarch64 build

recipes/shiver/build.sh, recipes/shiver/meta.yaml
Fix non-fatal absence of HXB2 sequence file
=> Update shiver: fix non-fatal absence of HXB2 sequence file

recipes/vt/meta.yaml
=> vt: add linux-aarch64 build

recipes/cmappy/meta.yaml
=> cmappy: add linux-aarch64 build

recipes/bindash/build.sh, recipes/bindash/meta.yaml
=> bindash: add linux-aarch64 build

recipes/popdel/build.sh, recipes/popdel/meta.yaml
=> popdel: add linux-aarch64 build

recipes/kaiju/build.sh, recipes/kaiju/meta.yaml
=> kaiju: add linux-aarch64 build

recipes/phynteny/meta.yaml
=> update phynteny v0.1.13

recipes/haddock_biobb/meta.yaml, recipes/haddock_biobb/post-link.sh
=> [haddock_biobb] update: Add post-link.sh install instructions

recipes/sentieon/meta.yaml, recipes/sentieon/sentieon_symlinks.patch
Updating sentieon to 202308.02
---- …
=> Updating Sentieon to 202308.02

recipes/epic2/meta.yaml
=> epic2: add linux-aarch64 build

recipes/lofreq/build.sh, recipes/lofreq/meta.yaml
=> lofreq: add linux-aarch64 build

recipes/megalodon/meta.yaml
=> megalodon: add linux-aarch64 build

recipes/nextdenovo/build.sh, recipes/nextdenovo/meta.yaml
=> Update nextdenovo recipe

recipes/comet-ms/build.sh, recipes/comet-ms/meta.yaml
=> comet-ms: add linux-aarch64 build

recipes/varlociraptor/meta.yaml
=> varlociraptor: add linux-aarch64 build

recipes/gottcha2/meta.yaml
Update gottcha2 to v2.1.8.6
---- …
=> Update gottcha2 to v2.1.8.6

build-fail-blacklist, recipes/percolator/build.sh, recipes/percolator/meta.yaml
Adds latest version of percolator. I'm having difficulties trying to build it though. Just updating the latest source gives boost errors .
---- …
=> Update percolator to version 3.6.5

recipes/camlhmp/meta.yaml
This PR adds a new recipe for [camlhmp](https://github.com/rpetit3/camlhmp) which is a framework for creating bacterial typing schemas.
---- …
=> add recipe for camlhmp

recipes/tooldistillator/meta.yaml
Hi,
This PR adds a new tool (mostly a renamed version of an existing tool here: abromics_galaxy_json_extractor).
Bérénice
---- …
=> Add tooldistillator recipe

recipes/haddock_biobb/meta.yaml, recipes/haddock_biobb/post-link.sh
=> [haddock_biobb] Fix post-link.sh message

recipes/biobb_pytorch/meta.yaml
=> [biobb_pytorch] New conda package 4.1.0

recipes/pindel/meta.yaml
=> pindel: add linux-aarch64 build

recipes/longshot/meta.yaml, recipes/longshot/update-rust-htslib.patch
=> longshot: add linux-aarch64 build

recipes/gemini/meta.yaml
=> gemini: enable linux-aarch64 build

recipes/assembly_finder/meta.yaml
Updated entrypoint and dependencies
---- …
=> Update assembly_finder recipe to v0.7.1

recipes/metamate/meta.yaml
Add the tool metamate (https://github.com/tjcreedy/metamate).
This package is useful for the bioconda community as it helps postprocess metabarcode data.
---- …
=> Add metamate recipe by tjcreedy

recipes/melon/meta.yaml
Add a new dependency (`tqdm`) to the recipe
---- …
=> update melon to 0.1.4

recipes/trf/build.sh, recipes/trf/meta.yaml
=> trf: add linux-aarch64 build

recipes/gappa/build.sh, recipes/gappa/meta.yaml
=> gappa: add linux-aarch64 build

recipes/ska2/meta.yaml
=> ska2: add linux-aarch64 build

recipes/raxml-ng/build.sh, recipes/raxml-ng/meta.yaml
=> raxml-ng: add linux-aarch64 build

recipes/ucsc-twobittofa/build.sh, recipes/ucsc-twobittofa/htmshell.patch, recipes/ucsc-twobittofa/meta.yaml
=> ucsc-twobittofa: add linux-aarch64 build

recipes/r-dsb/bld.bat, recipes/r-dsb/build.sh, recipes/r-dsb/meta.yaml
Add recipe for r-dsb package (cran package with Bioconductor dependencies)
---- …
=> Add r-dsb recipe

recipes/fastani/build.sh, recipes/fastani/meta.yaml, recipes/fastani/wrap-memcpy-only-for-linux-x86_64.patch
=> fastani: add linux-aarch64 build

recipes/pysamstats/meta.yaml
=> pysamstats: add linux-aarch64 build

recipes/ucsc-bigwigtowig/build.sh, recipes/ucsc-bigwigtowig/htmshell.patch, recipes/ucsc-bigwigtowig/meta.yaml
=> ucsc-bigwigtowig: add linux-aarch64 build

recipes/chewbbaca/meta.yaml
Update chewBBACA to v3.3.5. List of changes available [here](https://github.com/B-UMMI/chewBBACA/blob/master/CHANGELOG.md).
---- …
=> Update chewBBACA to v3.3.5

recipes/mmseqs2/meta.yaml
mmseqs2 added `linux-aarch64` as an additional platform with 51b9013 but the build infrastructure wasn't ready at the time
---- …
=> mmseqs2: re-build for linux-aarch64 support

recipes/samsum/meta.yaml
=> samsum: add linux-aarch64 build

recipes/hicmatrix/meta.yaml
HiCMatrix17.1 is not working with python 3.7. Here is the correct recipe.
---- …
=> Update HiCMatrix 17.1 recipe

recipes/resistify/meta.yaml
=> bump resistify to v0.1.1

recipes/impg/build.sh, recipes/impg/meta.yaml
Add recipe for `impg` (https://github.com/pangenome/impg).
=> Add `impg`

recipes/bedgovcf/meta.yaml
=> Bump bedgovcf to v0.1.1

recipes/genometools-genometools/build.sh, recipes/genometools-genometools/meta.yaml
=> genometools-genometools: add linux-aarch64 build

recipes/bioconductor-s4vectors/meta.yaml
=> Bioconductor-s4vectors: add linux-aarch64 build

recipes/bioconductor-dnacopy/meta.yaml
=> bioconductor-dnacopy: add linux-aarch64 build

recipes/recon/build.sh, recipes/recon/meta.yaml
=> recon: add linux-aarch64 build

recipes/libdivsufsort/build.sh, recipes/libdivsufsort/meta.yaml
=> libdivsufsort: add linux-aarch64 build

recipes/fastobo/build.sh, recipes/fastobo/meta.yaml
=> fastobo: add linux-aarch64 build

recipes/svdb/meta.yaml
=> svdb: add linux-aarch64 build

recipes/vg/meta.yaml
=> vg: add linux-aarch64 build

recipes/dunovo/build.sh, recipes/dunovo/meta.yaml
=> dunovo: add linux-aarch64 build

recipes/gsalign/build.sh, recipes/gsalign/meta.yaml, recipes/gsalign/support-linux-aarch64.patch
=> gsalign: add linux-aarch64 build

recipes/rseqc/meta.yaml
=> rseqc: add linux-aarch64 build

recipes/emboss/meta.yaml
depends on: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5737
---- …
=> emboss: add linux-aarch64 build

recipes/bbmap/meta.yaml
=> bbmap: add linux-aarch64 build

recipes/bioconductor-limma/meta.yaml
=> Build bioconductor-limma for linux-aarch64

recipes/cooltools/meta.yaml
cooltools is failing in the nightly build, so trying to build it here.
---- …
=> cooltools for osx

recipes/r-shinyngs/meta.yaml
=> Bump r-shinyngs recipe

recipes/cialign/meta.yaml
Pandas was previously missing from the dependencies which sometimes makes installation fail.
---- …
=> Update: added pandas to dependencies for CIAlign

recipes/bioconductor-biocparallel/meta.yaml
=> bioconductor-biocparallel: add linux-aarch64 build

recipes/bioconductor-iranges/meta.yaml, recipes/bioconductor-xvector/meta.yaml
=> Bioconductor-xvector & bioconductor-iranges: add linux-aarch64 build

recipes/tesorter/build.sh, recipes/tesorter/meta.yaml
=> Update tesorter recipe

recipes/bedgovcf/meta.yaml
=> Fix 0.1.1 build of bedgovcf

recipes/bioconductor-matrixgenerics/meta.yaml
=> bioconductor-matrixgenerics: add linux-aarch64 build

recipes/crocodeel/meta.yaml
=> Add crocodeel

recipes/genotyphi/build.sh, recipes/genotyphi/meta.yaml
The repo for genotyphi has moved from https://github.com/katholt/genotyphi to  https://github.com/typhoidgenomics/genotyphi
this PR adjusts for those changes
---- …
=> update recipe for genotyphi

recipes/locarna/meta.yaml
=> locarna: add linux-aarch64 build

recipes/subread/build.sh, recipes/subread/meta.yaml
=> subread: add linux-aarch64 build and fix LICENSE's permissions

recipes/bioconda-utils/meta.yaml
=> Update bioconda-utils recipe

recipes/sincei/meta.yaml
Hi Team
This PR adds a new tool to bioconda: [sincei](https://github.com/bhardwaj-lab/sincei)
**sincei: A user-friendly toolkit for QC, counting, clustering and plotting of single-cell (epi)genomics data)**
----
* Please post …
=> Add sincei

recipes/locarna/meta.yaml
Reverts
-  #47413
The linux-aarch64 binaries are not usable. For more info see https://github.com/s-will/LocARNA/issues/83
---- …
=> Revert #47413 - locarna binaries hang on Linux ARM64

recipes/squigualiser/meta.yaml
Add squigualiser - a tool to visualise and analyse nanopore (ONT) raw signals to bioconda
---- …
=> Add squigualiser

recipes/bioconductor-apeglm/meta.yaml, recipes/bioconductor-genomicranges/meta.yaml
Needed by https://github.com/bioconda/bioconda-recipes/pull/46594
---- …
=> bioconductor -apeglm & -genomicranges: add linux-aarch64 build

recipes/cami-amber/meta.yaml
=> add two AMBER script to path

recipes/mockinbird/meta.yaml
Cleaning up the nightly builds. The osx build is trying to build py310 for mockinbird, but it's failing on lint.
---- …
=> mockinbird: add run_exports

recipes/r-workflowscriptscommon/build.sh, recipes/r-workflowscriptscommon/meta.yaml
=> Update r-workflowscriptscommon recipe

recipes/biobb_pytorch/meta.yaml
=> [biobb_pytorch] update 4.1.1

recipes/scoring-matrices/meta.yaml
The `scoring-matrices` package is a Python package for handling and distributing scoring matrices for biological sequence alignment. Ultimately, it will be used to handle scoring matrices in `pyopal`, `pytrimal`, `pyfamsa`, `pytantan`, etc.
---- …
=> Add `scoring-matrices` Python package

recipes/annotsv/meta.yaml
=> Add missing dependencies to annotsv

recipes/cogent3/meta.yaml
Quarterly (Q2) release of cogent3
---- …
=> Update Cogent3 to 2024.5.7a1

recipes/bioconductor-affxparser/meta.yaml, recipes/bioconductor-amountain/meta.yaml, recipes/bioconductor-coregnet/meta.yaml, recipes/bioconductor-ebseq/meta.yaml, recipes/bioconductor-garfield/meta.yaml, recipes/bioconductor-geneticsped/meta.yaml, recipes/bioconductor-genocn/meta.yaml, recipes/bioconductor-hmmcopy/meta.yaml, recipes/bioconductor-iclusterplus/meta.yaml, recipes/bioconductor-isolde/meta.yaml, recipes/bioconductor-mgsa/meta.yaml
- affxparser
- amountain
- coregnet
- ebseq
- garfield
- geneticsped
- genocn
- hmmcopy
- iclusterplus
- isolde
- mgsa
---- …
=> Add Linux aarch64 build for more Bioconductor packages

recipes/biobb_pytorch/meta.yaml
=> [biobb_pytorch] New parameters 4.1.2

recipes/biobb_pytorch/meta.yaml
=> [biobb_pytorch] update 4.1.3

recipes/jcvi/meta.yaml, recipes/ucsc-liftover/meta.yaml
=> jcvi: add linux-aarch64 build

recipes/poseidon-xerxes/meta.yaml
This PR updates poseidon-xerxes to a new version.
---- …
=> Update poseidon-xerxes to 1.0.1.1

recipes/rebar/meta.yaml
Update [rebar](https://github.com/phac-nml/rebar): 0.2.0 → 0.2.1
[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat)](http://bioconda.github.io/recipes/rebar/README.html) [![Conda](https://img.shields.io/conda/dn/bioconda/rebar.svg)](https://anaconda.org/bioconda/rebar/files)
Info | Link or Description
-----|--------------------
Summary | Detect and visualize genomic recombination events.
Home | [https://github.com/phac-nml/rebar](https://github.com/phac-nml/rebar)
Releases |[https://github.com/phac-nml/rebar/tags](https://github.com/phac-nml/rebar/tags)
Author | `@ktmeaton`
***
=> Update rebar to v0.2.1

recipes/biobb_io/meta.yaml
=> [biobb_io] update 4.1.1

recipes/gmap/meta.yaml
=> Update gmap to 2024-05-07

recipes/biobb_vs/meta.yaml
=> [biobb_vs] update 4.1.2

recipes/seqverify/build.sh, recipes/seqverify/meta.yaml
This PR updates SeqVerify to v1.2.0. SeqVerify is a Python-based command line tool for analysis of whole genome sequencing data for gene-editing verification.
---- …
=> Update seqverify to v1.2.0

recipes/isoquant/build.sh, recipes/isoquant/meta.yaml
=> Update IsoQuant to 3.4.0

recipes/clair3/meta.yaml
=> Update clair3 to v1.0.8

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.21

recipes/ebcsgen/meta.yaml
Add `run_exports` to the `meta.yaml` file.
=> Update eBCSgen - add run_exports

recipes/foldseek/meta.yaml
=> Update Foldseek to 9-427df8a

recipes/liqa/meta.yaml
=> Add recipe for LIQA v1.2.0

recipes/cialign/meta.yaml
Added a missing dependency to the CIAlign recipe.
---- …
=> Update CIAlign recipe

recipes/libcifpp/build.sh, recipes/libcifpp/conda_build_config.yaml, recipes/libcifpp/meta.yaml
=> Update libcifpp version

recipes/necat/build.sh, recipes/necat/meta.yaml, recipes/necat/src_ctg_cns_filter_m4.mk.patch, recipes/necat/src_ctg_cns_pm4_main.mk.patch, recipes/necat/src_partition_candidates_main.mk.patch, recipes/necat/src_partition_m4_main.mk.patch, recipes/necat/src_trim_bases_accurate0_pm4.mk.patch, recipes/necat/src_trim_bases_accurate_pm4.mk.patch, recipes/necat/src_trim_bases_extract_trimmerd_reads.mk.patch, recipes/necat/src_trim_bases_largest_cover_range.mk.patch, recipes/necat/src_trim_bases_pm4.mk.patch
Add aarch64 build for necat
---- …
=> Add aarch64 build for necat

recipes/dechat/build.sh, recipes/dechat/meta.yaml
=> add dechat

recipes/pstrain/build.sh, recipes/pstrain/meta.yaml
Add a strain-profiling method: PStrain.
---- …
=> add pstrain

recipes/shigapass/build.sh, recipes/shigapass/meta.yaml
Add ShigaPass, a bash package that predicts Shigella serotypes
---- …
=> Add a new recipe for shigapass

recipes/perl-retroseq/build.sh, recipes/perl-retroseq/meta.yaml
The conda recipe works well, but in the docker and singularity containers, retroseq gives the error: `cannot determine samtools version number`. This PR aims to fix the docker and singularity versions.
----
* Please post …
=> Fix retroseq to add samtools to build requirements

recipes/biobb_common/meta.yaml
=> [biobb_common] update 4.2.0

recipes/haddock_biobb/meta.yaml
=> [haddock_biobb] update 3.0.5

recipes/pixelator/meta.yaml
Update pixelator to 0.17.0. Supersedes https://github.com/bioconda/bioconda-recipes/pull/48001.
=> Update pixelator to 0.17.0

recipes/gmap/meta.yaml
=> Update gmap to 2024-05-20

recipes/haddock_biobb/meta.yaml
=> Haddock biobb

recipes/jalview/meta.yaml
Updated Jalview to 2.11.3.3
---- …
=> Update Jalview to 2.11.3.3

recipes/mgikit/build.sh, recipes/mgikit/meta.yaml
mgikit is a collection of tools used to demultiplex fastq files and generate demultiplexing and quality reports.
https://sagc-bioinformatics.github.io/mgikit/
---- …
=> adding mgikit 

recipes/bioconductor-fraser/meta.yaml
=> Update bioconductor-fraser to 1.99.4

recipes/earlgrey/meta.yaml
Update build to specify version 4.1.5 of RepeatMasker, rather than >4.1.4. Prevent the use of RepeatMasker 4.1.6
---- …
=> Update meta.yaml for Earl Grey

recipes/biobb_analysis/meta.yaml
=> [biobb_analysis] update 4.2.0

recipes/biobb_amber/meta.yaml
=> [biobb_amber] update 4.2.0

recipes/biobb_chemistry/meta.yaml
=> [biobb_chemistry] update 4.2.0

recipes/biobb_cmip/meta.yaml
=> [biobb_cmip] update 4.2.0

recipes/biobb_cp2k/meta.yaml
=> [biobb_cp2k] update 4.2.0

recipes/biobb_flexdyn/meta.yaml
=> [biobb_flexdyn] update 4.2.0

recipes/biobb_flexserv/meta.yaml
=> [biobb_flexserv] update 4.2.0

recipes/biobb_godmd/meta.yaml
=> [biobb_godmd] update 4.2.0

recipes/biobb_ml/meta.yaml
=> [biobb_ml] update 4.2.0

recipes/biobb_pdb_tools/meta.yaml
=> [biobb_pdb_tools] update 4.2.0

recipes/biobb_io/meta.yaml
=> [biobb_io] update 4.2.0

recipes/biobb_structure_utils/meta.yaml
=> [biobb_structure_utils] update 4.2.0

recipes/biobb_vs/meta.yaml
=> [biobb_vs] update 4.2.0

recipes/biobb_gromacs/meta.yaml
=> [biobb_gromacs] update 4.2.0

recipes/r-restfulr/meta.yaml
=> update r-restfulr with additional-platform

recipes/syny/build.sh, recipes/syny/meta.yaml
I created a conda recipe for syny, a pipeline that investigates collinearity between genomes (https://github.com/PombertLab/SYNY). I tested the conda build locally and it works fine in a clean Ubuntu VM.  I'm still learning about conda so hopefully I did not make any mistake.
Best regards,
JF
---- …
=> Add recipe for syny (a pipeline that investigates collinearity between genomes)

recipes/classpro/build.sh, recipes/classpro/meta.yaml
Added ClassPro for conda installation
---- …
=> Add ClassPro meta.yaml

recipes/biobb_dna/meta.yaml
=> [biobb_dna] update 4.2.0

recipes/smallgenomeutilities/meta.yaml
[bugfix] deprecations in BioPython
---- …
=> Update smallegenomeutilities to 0.4.1

recipes/bioconductor-fraser/1.99.3/build.sh, recipes/bioconductor-fraser/1.99.3/meta.yaml, recipes/bioconductor-fraser/meta.yaml
- This FRASER version is needed for drop 1.3.4 and will be pinned here: #48083
---- …
=> add FRASER 1.99.3

recipes/biobb_pmx/meta.yaml
=> [biobb_pmx] update 4.2.0

recipes/sigprofilerassignment/meta.yaml
Add SigProfilerAssignment a tool for assignment of known mutational signatures to individual samples and individual somatic mutations
---- …
=> Add  SigProfilerAssignment

recipes/bali-phy/build.sh, recipes/bali-phy/meta.yaml
Update bali-phy to the latest 4.0 beta version (I am the author).
=> Update bali-phy to 4.0-beta13

recipes/augur/meta.yaml
Augur 24.4.0 [release notes](https://github.com/nextstrain/augur/releases/tag/24.4.0)
---- …
=> Update augur to 24.4.0

recipes/venndata/meta.yaml
Adding venndata python package. This is needed for spapros (gene panel design tool). Recipe is generally relevant (not only for biological science).
---- …
=> Add venndata recipe

recipes/stranger/meta.yaml
=> Update stranger to 0.9.0

recipes/drop/meta.yaml
- update drop to 1.4.0
- adjust bioconductor-fraser and bioconductor-outrider versions
- makes #48150 obsolete
---- …
=> Update drop to 1.4.0

recipes/fast-edit-distance/meta.yaml
=> Add recipe for fast-edit-distance v1.2.1

recipes/biobb_pmx/meta.yaml
=> [biobb_pmx] update 4.2.1

recipes/sra-tools/meta.yaml
=> Update sra-tools to 3.1.1

recipes/metaeuk/meta.yaml
=> Update MetaEuk to 7-bba0d80

recipes/perl-spreadsheet-parseexcel/meta.yaml
Update to version 0.66 to fix [CVE-2023-7101](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-7101) [JSON format](https://github.com/CVEProject/cvelistV5/blob/main/cves/2023/7xxx/CVE-2023-7101.json)
---- …
=> Update Perl's Spreadsheet::ParseExcel version to 0.66 to fix  CVE-2023-7101

recipes/coverm/meta.yaml
Add strobealign to CoverM dependencies (https://github.com/wwood/CoverM/issues/186)
=> Update CoverM recipe with new dependencies

recipes/biobb_model/meta.yaml
=> [biobb_model] update 4.2.0

recipes/tbvcfreport/meta.yaml
Update tbvcfreport to version 1.0.0
---- …
=> Update tbvcfreport to 1.0.0

recipes/anospp-analysis/meta.yaml
=> Update anospp-analysis to 0.3.0

recipes/beagle/build.sh, recipes/beagle/meta.yaml
Update [`beagle`](https://bioconda.github.io/recipes/beagle/README.html): **5.4_22Jul22.46e** → **5.4_27May24.118**
Just a pretty simple update! Nothing fancy except maybe a [small tweak to the `build.sh` script](https://github.com/bioconda/bioconda-recipes/pull/48204/commits/94c0e8e32a0de3efb08a25bacbf3d9265331d283)
=> Update beagle to 5.4_27May24.118

recipes/dice/meta.yaml
Add recipe for DICE - Fast and Accurate Distance-Based Reconstruction of Single-Cell Copy Number Phylogenies.
---- …
=> Add dice recipe

recipes/dnmtools/meta.yaml
Update dnmtools for new release v1.4.3
---- …
=> Update dnmtools: new release v1.4.3

recipes/abismal/meta.yaml
Update abismal for new version.
Also added zlib to requirements for host and run. The auto-bump failed because the build system now seems to require zlib explicitly among requirements; previously it was downloaded automatically due to the htslib requirement.
---- …
=> Update abismal for new version

recipes/biophi/meta.yaml
Fixing sqlalchemy issue by downgrading pandas https://github.com/Merck/BioPhi/issues/63
=> Use pandas <2.2 in biophi

recipes/ervdetective/build.sh, recipes/ervdetective/meta.yaml
add a recipes named ervdetective
description: ervdetective, an efficient pipeline for identification and annotation of endogenous retroviruses (ERVs)
=> add ervdetective recipes

recipes/biobb_haddock/meta.yaml
=> [biobb_haddock] update 4.2.1

recipes/peptide-shaker/build.sh, recipes/peptide-shaker/meta.yaml, recipes/peptide-shaker/peptide-shaker.py
=> Update peptide-shaker to 3.0.8

recipes/searchgui/build.sh, recipes/searchgui/meta.yaml, recipes/searchgui/searchgui.py
=> Update searchgui to 4.3.9

recipes/salmon/build.sh, recipes/salmon/meta.yaml
=> Update salmon recipe

recipes/ggcaller/meta.yaml
Updates ggCaller version 1.3.5 build 1
---- …
=> Update ggCaller to 1.3.5 build 1

recipes/assemblycomparator2/build.sh, recipes/assemblycomparator2/meta.yaml
Hi @mencian 
I see that you made some changes to my recipe (https://github.com/bioconda/bioconda-recipes/pull/48242/commits/bf3dab0d7b76e909c0a0346a55392599c4f73747). Thank you very much, it is much cleaner your way. But we must add a few more files.
---- …
=> Update assemblycomparator v2.7.1

recipes/vartrix/build.sh, recipes/vartrix/meta.yaml
=> Build vartrix on OSX
