bioconda/bioconda-recipes

recipes/zarp/build.sh, recipes/zarp/built.sh, recipes/zarp/meta.yaml
=> Update zarp to 1.0.0

recipes/sneakernet-qc/meta.yaml, recipes/sneakernet-qc/post-link.sh
manual update for Sneakernet-qc to v0.26.0. Some dependencies were added or subtracted and so I didn't want to depend on the automated biocondabot version bump.
---- …
=> update to sneakernet-qc v0.26.0

recipes/ena-upload-cli/meta.yaml
=> Update ENA upload CLI to 0.7.3

recipes/auspice/build.sh, recipes/auspice/meta.yaml
=> auspice: add linux-aarch64 build

recipes/digestiflow-cli/build.sh, recipes/digestiflow-cli/meta.yaml
=> digestiflow-cli: add linux-aarch64 build

recipes/mgkit/meta.yaml
=> mgkit: add linux-aarch64 build

recipes/igblast/meta.yaml
=> igblast: add linux-aarch64 build

recipes/tracy/build.sh, recipes/tracy/meta.yaml
=> tracy: add linux-aarch64 build

recipes/pegasusio/meta.yaml
=> pegasusio: add linux-aarch64 build

recipes/spades/build.sh, recipes/spades/meta.yaml
=> spades: Enable NCBI SRA input. Update `about` metadata

recipes/segalign-full/meta.yaml
updating to latest version of segalign
---- …
=> updating to latest version of segalign

recipes/graphembed/build.sh, recipes/graphembed/meta.yaml
Update graphembed to v0.1.2 with better command line description, SIMD distance computation and improved VCPMR@k metric. 
---- …
=> Update graphembed v0.1.2

recipes/libsequence/build.sh, recipes/libsequence/fix-build.patch, recipes/libsequence/meta.yaml
=> libsequence: add linux-aarch64 build

build-fail-blacklist, recipes/selene-sdk/meta.yaml
=> selene-sdk: add linux-aarch64 build

recipes/r-hgvsparser/meta.yaml
=> Add hgvsparser recipe

recipes/mycotools/meta.yaml
Add [Mycotools](https://github.com/xonq/mycotools) to bioconda channel
----
<details> …
=> Add mycotools

recipes/mmlong2-lite/build.sh, recipes/mmlong2-lite/meta.yaml
Introduction of the mmlong2-lite pipeline into Bioconda
=> Add mmlong2 lite

recipes/survindel2/build.sh, recipes/survindel2/meta.yaml, recipes/survindel2/run_test.sh
=> Add survindel2.

recipes/bbknn/meta.yaml
=> bbknn: add linux-aarch64 build

recipes/bamread/meta.yaml
=> bamread: add linux-aarch64 build

recipes/dajin2/meta.yaml, recipes/rsv-typer/meta.yaml
Update to rsv-typer 0.4.0
---- …
=> update to rsv-typer0.4.0

recipes/segalign-full/meta.yaml
=> update to segalign v0.1.2.6

recipes/dsh-bio/meta.yaml
=> Update dsh-bio to 2.4

recipes/unikmer/meta.yaml
- v0.20.0 - 2023-11-11
- `unikmer`:
- update help messages
- **rename subcommand `uniqs` to `map`**.
- do not add the extension `.unik` if the value of flag `-o/--out-prefix` already has one.
- `unikmer sort`:
- fix the bug of using both `-d/--repeated` and `-m/--chunk-size`, which seems to existed for 4 years.
- `unikmer merge`:
- fix the bug of missing one record when taxid information is contained.
- `unikmer num`:
- `-f/--force` also support sorted files.
- `unikmer map`:
- fix a bug of missing some regions.
- `unikmer locate`:
- fix seq ID error in output.
- deduplicate output.
----
* If this PR adds or updates a …
=> Update Unikmer to 0.20.0

recipes/checkm2/meta.yaml
Update CheckM2 version and download url
---- …
=> Update CheckM2 version and download url

recipes/dicey/meta.yaml
=> Update dicey v0.3.1

recipes/mykrobe/build.sh, recipes/mykrobe/meta.yaml
=> mykrobe: add linux-aarch64 build

recipes/spoa/build.sh, recipes/spoa/meta.yaml
=> spoa: add linux-aarch64 build

recipes/ucsc-hggcpercent/build.sh, recipes/ucsc-hggcpercent/htmshell.patch, recipes/ucsc-hggcpercent/meta.yaml
=> ucsc-hggcpercent: add linux-aarch64 build

recipes/auspice/meta.yaml
=> Bump auspice to v2.54.1

recipes/moments/meta.yaml
=> moments: add linux-aarch64 build

recipes/ucsc-gff3togenepred/build.sh, recipes/ucsc-gff3togenepred/htmshell.patch, recipes/ucsc-gff3togenepred/meta.yaml
=> ucsc-gff3togenepred: add linux-aarch64 build

recipes/r-wgcna/meta.yaml
=> r-wgcna: add linux-aarch64 build

recipes/libbigwig/build.sh, recipes/libbigwig/meta.yaml, recipes/methyldackel/build.sh, recipes/methyldackel/meta.yaml
=> methylation & libbigwig: add linux-aarch64 build

recipes/bowtie2/build.sh, recipes/bowtie2/meta.yaml
=> Update bowtie2 recipe

recipes/elprep/meta.yaml
=> elprep: add linux-aarch64 build

recipes/phispy/meta.yaml
=> phispy: add linux-aarch64 build

recipes/ucsc-genepredtobiggenepred/build.sh, recipes/ucsc-genepredtobiggenepred/htmshell.patch, recipes/ucsc-genepredtobiggenepred/meta.yaml
=> ucsc-genepredtobiggenepred: add linux-aarch64 build

recipes/razers3/build.sh, recipes/razers3/meta.yaml
=> razers3: add linux-aarch64 build

recipes/fermi2/build.sh, recipes/fermi2/fermi2-aarch64.patch, recipes/fermi2/meta.yaml, recipes/ropebwt2/build.sh, recipes/ropebwt2/meta.yaml, recipes/tiddit/meta.yaml
=> tiddit & fermi2 & ropebwt2: add linux-aarch64 build

recipes/pygcap/LICENSE, recipes/pygcap/meta.yaml
=> Add pygcap recipe

recipes/last/build.sh, recipes/last/meta.yaml
=> Update last to 1544

recipes/pyranges/meta.yaml
=> Update pyranges recipe

build-fail-blacklist, recipes/ucsc-bigbedinfo/build.sh, recipes/ucsc-bigbedinfo/include.patch, recipes/ucsc-bigbedinfo/meta.yaml, recipes/ucsc-bigbednameditems/build.sh, recipes/ucsc-bigbednameditems/include.patch, recipes/ucsc-bigbednameditems/meta.yaml, recipes/ucsc-bigbedsummary/build.sh, recipes/ucsc-bigbedsummary/include.patch, recipes/ucsc-bigbedsummary/meta.yaml, recipes/ucsc-bigmaftomaf/build.sh, recipes/ucsc-bigmaftomaf/include.patch, recipes/ucsc-bigmaftomaf/meta.yaml
- ucsc-bigbedinfo
- ucsc-bigbednameditems
- ucsc-bigbedsummary
- ucsc-bigmaftomaf
---- …
=> ucsc- bigbedinfo & bigbednameditems & bigbedsummary & bigmaftomaf: add linux-aarch64 build

recipes/biobb_model/meta.yaml
=> [biobb_model] update 4.2.2

build-fail-blacklist, recipes/ucsc-bigwiginfo/build.sh, recipes/ucsc-bigwiginfo/include.patch, recipes/ucsc-bigwiginfo/meta.yaml
=> Update ucsc-bigwiginfo to 466

recipes/abnumber/meta.yaml
Bump up abnumber to 0.3.4 latest release https://github.com/prihoda/AbNumber/releases
=> Bump up abnumber to 0.3.4

recipes/metacache/meta.yaml
=> Metacache doesn't need python, let alone python 2

recipes/mmlong2/build.sh, recipes/mmlong2/meta.yaml
This pull request introduces the full mmlong2 pipeline into the Bioconda channel
---- …
=> Add mmlong2

build-fail-blacklist, recipes/ucsc-bigpsltopsl/build.sh, recipes/ucsc-bigpsltopsl/include.patch, recipes/ucsc-bigpsltopsl/meta.yaml, recipes/ucsc-bigwigaverageoverbed/build.sh, recipes/ucsc-bigwigaverageoverbed/include.patch, recipes/ucsc-bigwigaverageoverbed/meta.yaml, recipes/ucsc-bigwigcat/build.sh, recipes/ucsc-bigwigcat/include.patch, recipes/ucsc-bigwigcat/meta.yaml, recipes/ucsc-bigwigcluster/build.sh, recipes/ucsc-bigwigcluster/include.patch, recipes/ucsc-bigwigcluster/meta.yaml, recipes/ucsc-bigwigcorrelate/build.sh, recipes/ucsc-bigwigcorrelate/include.patch, recipes/ucsc-bigwigcorrelate/meta.yaml
- ucsc-bigpsltopsl
- ucsc-bigwigaverageoverbed
- ucsc-bigwigcat
- ucsc-bigwigcluster
- ucsc-bigwigcorrelate
---- …
=> ucsc- bigpsltopsl & bigwigaverageoverbed & bigwigcat & bigwigcluster & bigwigcorrelate: add linux-aarch64 build

recipes/biobb_model/meta.yaml
=> [biobb_model] update 4.2.3

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.22

recipes/callerpp/build.sh, recipes/callerpp/meta.yaml
=> Add callerpp

recipes/abnumber/meta.yaml
=> Bump up abnumber to 0.3.5

recipes/deepblast/meta.yaml
=> Add recipe for deepblast

build-fail-blacklist, recipes/ucsc-addcols/build.sh, recipes/ucsc-addcols/include.patch, recipes/ucsc-addcols/meta.yaml, recipes/ucsc-ameme/build.sh, recipes/ucsc-ameme/include.patch, recipes/ucsc-ameme/meta.yaml, recipes/ucsc-autodtd/build.sh, recipes/ucsc-autodtd/include.patch, recipes/ucsc-autodtd/meta.yaml, recipes/ucsc-autosql/build.sh, recipes/ucsc-autosql/include.patch, recipes/ucsc-autosql/meta.yaml, recipes/ucsc-autoxml/build.sh, recipes/ucsc-autoxml/include.patch, recipes/ucsc-autoxml/meta.yaml, recipes/ucsc-avecols/build.sh, recipes/ucsc-avecols/include.patch, recipes/ucsc-avecols/meta.yaml, recipes/ucsc-axtsort/build.sh, recipes/ucsc-axtsort/include.patch, recipes/ucsc-axtsort/meta.yaml
- ucsc-addcols
- ucsc-ameme
- ucsc-autodtd
- ucsc-autosql
- ucsc-autoxml
- ucsc-avecols
- ucsc-axtsort
---- …
=> Update several ucsc-** packages to v466. Add linux-aarch64 build

recipes/swarm/build.sh, recipes/swarm/meta.yaml
=> swarm: add linux-aarch64 build

recipes/dinopy/meta.yaml
=> dinopy: add linux-aarch64 build

recipes/primer3/build.sh, recipes/primer3/meta.yaml
=> primer3: add linux-aarch64 build

recipes/pegasuspy/meta.yaml
Use matplotlib v3.7+ and PegasusIO v0.9.1+
---- …
=> Update Pegasuspy dependencies

recipes/r-spp/meta.yaml
=> r-spp: add linux-aarch64 build

recipes/callerpp/build.sh, recipes/callerpp/meta.yaml
=> callerpp: add linux-aarch64 build

build-fail-blacklist, recipes/genepop/build.sh, recipes/genepop/meta.yaml
=> genepop: add linux-aarch64 build

recipes/velvet/build.sh, recipes/velvet/meta.yaml
=> velvet: add linux-aarch64 build

recipes/curves/meta.yaml
=> [curves] update 3.0.2

recipes/vsnp3/meta.yaml
=> vsnp3 - v3.23 update

recipes/pathogen-embed/meta.yaml
Adds initial recipe for [pathogen-embed](https://pypi.org/project/pathogen-embed/).
---- …
=> Add pathogen-embed

recipes/psirc/build.sh, recipes/psirc/meta.yaml
This PR adds the [psirc](https://github.com/Christina-hshi/psirc) package to bioconda. The goal is to use it in the [nf-core/circrna](https://nf-co.re/circrna/dev) pipeline
=> Add psirc recipe

recipes/snp-sites/build.sh, recipes/snp-sites/meta.yaml
=> snp-sites: add linux-aarch64 build

recipes/pyplink/LICENSE.txt, recipes/pyplink/meta.yaml
Add pyplink, a python package to read and write Plink's binary files
=> Add pyplink

recipes/rmats/build.sh, recipes/rmats/meta.yaml
=> rmats: add linux-aarch64 build

recipes/biobb_dna/meta.yaml
=> [biobb_dna] update 4.2.2

recipes/comparem2/build.sh, recipes/comparem2/meta.yaml
CompareM2 is formerly known as Assemblycomparator2 which is already published on bioconda. 
---- …
=> Add CompareM2

recipes/pgscatalog.match/meta.yaml
=> Add recipe for pgscatalog.match v0.2.1

recipes/last/meta.yaml
=> Update last to 1548

recipes/biobloomtools/build.sh, recipes/biobloomtools/meta.yaml
=> Update biobloomtools - rebuild after bulk failure

recipes/selene-sdk/build_failure.linux-64.yaml, recipes/selene-sdk/meta.yaml
=> Selene SDK: rebuild after build failure

recipes/porechop/meta.yaml
=> porechop: add linux-aarch64 build

recipes/concoct/meta.yaml
=> concoct: add linux-aarch64 build

recipes/r-hemdag/meta.yaml
=> r-hemdag: add linux-aarch64 build

recipes/clever-toolkit/build.sh, recipes/clever-toolkit/meta.yaml
=> clever-toolkit: add linux-aarch64 build

recipes/fraggenescan/build.sh, recipes/fraggenescan/conda_build_config.yaml, recipes/fraggenescan/meta.yaml
=> fraggenescan: add linux-aarch64 build

recipes/phyml/build.sh, recipes/phyml/meta.yaml, recipes/phyml/phyml-aarch64.patch
=> phyml: add linux-aarch64 build

recipes/blockclust/build_failure.linux-64.yaml, recipes/blockclust/meta.yaml
=> blockclust: rebuild after bulk build failure

recipes/deepmicroclass/meta.yaml
Hey, 
Here a little update for the DeepMicroClass recipe I pushed yesterday. 
It includes a new description (because this recipe is only for the CPU version) and a basic -h test command. 
Thanks for you review.
=> Update DeepMicroClass recipe

recipes/usearch/meta.yaml
=> add usearch

.circleci/check-for-additional-platforms.sh, recipes/usearch/meta.yaml
=> Build again usearch for linux-aarch64 artifact

recipes/mummer4/build.sh, recipes/mummer4/meta.yaml
=> mummer4: add linux-aarch64 build

recipes/sickle-trim/build.sh, recipes/sickle-trim/meta.yaml
=> sickle-trim: add linux-aarch64 build

recipes/ntroot/meta.yaml
Add new required dependency: bedtools
---- …
=> Update ntroot to 1.1.0

build-fail-blacklist, recipes/metabat2/arm_hwcap.patch, recipes/metabat2/build.sh, recipes/metabat2/cmake-htslib.patch, recipes/metabat2/meta.yaml
=> metabat2: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-bedtogenepred/build.sh, recipes/ucsc-bedtogenepred/include.patch, recipes/ucsc-bedtogenepred/meta.yaml
=> ucsc-bedtogenepred: update to v466

build-fail-blacklist, recipes/ucsc-axtswap/build.sh, recipes/ucsc-axtswap/include.patch, recipes/ucsc-axtswap/meta.yaml
=> ucsc-axtswap: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-bedgraphpack/build.sh, recipes/ucsc-bedgraphpack/include.patch, recipes/ucsc-bedgraphpack/meta.yaml
=> ucsc-bedgraphpack: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-bedremoveoverlap/build.sh, recipes/ucsc-bedremoveoverlap/include.patch, recipes/ucsc-bedremoveoverlap/meta.yaml
=> ucsc-bedremoveoverlap: add linux-aarch64 build

recipes/groot/meta.yaml
Add ca-certificates in requirements
Add ca-certifacte to requirement to build the biocontainer with it and bypass the tls error
---- …
=> Add ca-certificates in meta.yaml

recipes/kaptive/meta.yaml
Update Kaptive to v3.0.0b4
---- …
=> Update Kaptive to v3.0.0b4

recipes/concoct/concoct-newer-scikit-learn.patch, recipes/concoct/meta.yaml
=> concoct: pin scikit-learn to 1.1.3

recipes/bali-phy/build.sh, recipes/bali-phy/meta.yaml
Update from 4.0-beta13 to 4.0-beta14 (I am the author).
Fixes a few bugs, decreases startup time.
=> bali-phy: 4.0-beta14

recipes/pangwes/build.sh, recipes/pangwes/meta.yaml
=> add_pangwes

recipes/ensembl-utils/meta.yaml
Add the newly released ensembl-utils repository into bioconda to facilitate its distribution and usage.
_Note:_ Recipe generated with `grayskull`.
---- …
=> Add bioconda recipe for ensembl-utils

recipes/covtobed/meta.yaml
=> covtobed: add linux-aarch64 build

recipes/dsrc/build.sh, recipes/dsrc/meta.yaml
=> dsrc: add linux-aarch64 build

recipes/yacrd/meta.yaml
=> yacrd: add linux-aarch64 build

recipes/bamutil/build.sh, recipes/bamutil/meta.yaml
=> bamutil: add linux-aarch64 build

recipes/genomedata/meta.yaml
=> genomedata: add linux-aarch64 build

recipes/artic-tools/build.sh, recipes/artic-tools/meta.yaml
=> artic-tools: add linux-aarch64 build

recipes/kegg-pathways-completeness/meta.yaml
kegg-pathways-completeness is a tool for computing the completeness of KEGG pathways
---- …
=> Add kegg-pathways-completeness

recipes/ngmlr/.gitattributes, recipes/ngmlr/build.sh, recipes/ngmlr/meta.yaml, recipes/ngmlr/ngmlr-aarch64.patch
=> ngmlr: add linux-aarch64 build

recipes/ucsc-fatotwobit/meta.yaml
Attempting to compile faToTwoBit against zlib 1.3
---- …
=> Attempting to compile against zlib 1.3

recipes/ont-modkit/meta.yaml
=> ont-modkit: add linux-aarch64 build

recipes/nonpareil/meta.yaml
=> nonpareil: add linux-aarch64 build

.circleci/config.yml, recipes/orthanq/meta.yaml
=> orthanq: add linux-aarch64 build

recipes/pathphynder/build.sh, recipes/pathphynder/meta.yaml
Removes the patching command as was included in the latest version of the tool, see:
https://github.com/ruidlpm/pathPhynder/commit/1459bc34ce755a0f19a8f7678c1ee30ea6e5e4ac
---- …
=> Update pathphynder: remove code patch now not necessary due to inclusion in latest release

recipes/wfmash/build.sh, recipes/wfmash/meta.yaml
=> wfmash: add linux-aarch64 build

recipes/mason/meta.yaml
=> mason: add linux-aarch64 build

recipes/vcfbub/meta.yaml
=> vcfbub: add linux-aarch64 build

recipes/kaptive/meta.yaml
Update Kaptive to 3.0.0b5
---- …
=> Update Kaptive to 3.0.0b5

recipes/snap-aligner/build.sh, recipes/snap-aligner/meta.yaml, recipes/snap-aligner/snap-aligner-aarch64.patch
=> snap-aligner: add linux-aarch64 build

recipes/rnaquast/build.sh, recipes/rnaquast/meta.yaml
=> Update rnaQUAST to 2.3.0

recipes/sdm/build.sh, recipes/sdm/meta.yaml
Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>
(cherry picked from commit 8f14d7648e39a5081b45f5fd04c079c78006bc86)
---- …
=> sdm: add linux-aarch64 build

recipes/perbase/meta.yaml, recipes/perbase/perbase-aarch64.patch
=> perbase: add linux-aarch64 build

recipes/desalt/build.sh, recipes/desalt/meta.yaml
=> desalt: add run_exports

build-fail-blacklist, recipes/idba/build.sh, recipes/idba/meta.yaml
=> idba: add linux-aarch64 build

recipes/biobb_dna/meta.yaml
=> [biobb_dna] update 4.2.4

recipes/wiggletools/build.sh, recipes/wiggletools/meta.yaml
=> wiggletools: add linux-aarch64 build

recipes/slow5tools/build.sh, recipes/slow5tools/meta.yaml
=> slow5tools: add linux-aarch64 build

recipes/strobealign/build.sh, recipes/strobealign/meta.yaml
=> strobealign: add linux-aarch64 build

recipes/olivar/meta.yaml
=> Update Olivar to 1.1.5

recipes/freyja/meta.yaml
Adds pyarrow as a dependency
---- …
=> Update Freyja meta.yaml

recipes/mvip/LICENSE, recipes/mvip/meta.yaml
=> mvip_recipe

recipes/sonicparanoid/meta.yaml, recipes/sonicparanoid/sys_tools.patch, recipes/sonicparanoid/use-env-vars.patch
=> Update sonicparanoid to 2.0.7

recipes/ngs-disambiguate/meta.yaml
=> ngs-disambiguate: add linux-aarch64 build

build-fail-blacklist, recipes/bmtool/bmtool-cplusplus-template.patch, recipes/bmtool/bmtool-fix-ctime.patch, recipes/bmtool/build.sh, recipes/bmtool/meta.yaml
=> bmtool: add linux-aarch64 build

build-fail-blacklist, recipes/srprism/build.sh, recipes/srprism/meta.yaml, recipes/srprism/srprism-fix-compilation.patch
=> srprism: add linux-aarch64 build

recipes/pairtools/meta.yaml
=> pairtools: add linux-aarch64 build

recipes/snp-dists/build.sh, recipes/snp-dists/meta.yaml
=> snp-dists: add linux-aarch64 build

build-fail-blacklist, recipes/bmfilter/0001-Cast-getline-stream-to-bool.patch, recipes/bmfilter/bmtool-cplusplus-template.patch, recipes/bmfilter/bmtool-fix-ctime.patch, recipes/bmfilter/build.sh, recipes/bmfilter/meta.yaml
=> bmfilter: add linux-aarch64 build

recipes/cgpbigwig/build.sh, recipes/cgpbigwig/meta.yaml
=> cgpbigwig: add linux-aarch64 build

recipes/gangstr/gangstr-aarch64.patch, recipes/gangstr/meta.yaml
=> gangstr: add linux-aarch64 build

build-fail-blacklist, recipes/merfishtools/build.sh, recipes/merfishtools/fix-build.patch, recipes/merfishtools/meta.yaml
=> merfishtools: add linux-aarch64 build

recipes/syngap/build.sh, recipes/syngap/meta.yaml
=> Update syngap to v1.2.4

recipes/argo/meta.yaml
=> add recipe argo

recipes/clermontyping/build.sh, recipes/clermontyping/meta.yaml
Adding recipe for Clermontyping tool. 
---
=> Add Clermontyping 

recipes/auspice/meta.yaml
See the changelog on the [Auspice releases page](https://github.com/nextstrain/auspice/releases/) for more details
---- …
=> Update Auspice to 2.56.0

recipes/syngap/meta.yaml
=> Update syngap to v1.2.5

recipes/flumut/meta.yaml, recipes/flumutdb/meta.yaml
This recipe is needed by FluMut recipe and contains the markers database. It is just a package data, therefore does not needs tests.
---- …
=> Add flumutdb

recipes/piscem/build.sh, recipes/piscem/build_rs.patch, recipes/piscem/meta.yaml
=> Update meta.yaml for piscem v0.9.0

recipes/r-sigminer/meta.yaml
=> r-sigminer: add linux-aarch64 build

recipes/expansionhunter/build.sh, recipes/expansionhunter/meta.yaml
=> expansionhunter: add linux-aarch64 build

recipes/rasusa/meta.yaml
=> rasusa: add linux-aarch64 build

recipes/krbalancing/meta.yaml
=> krbalancing: add linux-aarch64 build

recipes/fibertools-rs/build.sh, recipes/fibertools-rs/meta.yaml
Fix and simplify build script for fibertools-rs, try targeting generic CPU architecture with `rustc`.
=> Update : Fix build script for fibertools-rs 

recipes/squizz/build.sh, recipes/squizz/meta.yaml
=> squizz: add linux-aarch64 build

recipes/harpy/meta.yaml
Adding `pysam` as a dependency and bumping the build number, otherwise nothing else is changed. This is to prepare the build recipe for the upcoming Harpy 1.1 release.
---- …
=> add pysam dep

recipes/tooldistillator/meta.yaml
Update to new version
[tooldistillator](https://bioconda.github.io/recipes/tooldistillator/README.html?highlight=tooldistillator#package-package%20'tooldistillator'): 0.8.5.0 → 0.9
---- …
=> Update ToolDistillator to 0.9

recipes/flumutdb/meta.yaml
Added tests to fix linter error on autobump.
---- …
=> bump-flumutdb

recipes/crispector2/meta.yaml
=> add crispector2 2.1.1

recipes/harpy/meta.yaml
=> harpy: add linux-aarch64 build

recipes/centrifuger/build.sh, recipes/centrifuger/meta.yaml
=> centrifuger: add linux-aarch64 build

recipes/r-biodb/meta.yaml
=> r-biodb: add linux-aarch64 build

recipes/bwakit/build.sh, recipes/bwakit/meta.yaml
Updates the bwakit recipe to use bwa version 0.7.18
---- …
=> Update bwakit to use 0.7.18

recipes/pathogen-embed/meta.yaml
Update pathogen-embed to 2.1.0
---- …
=> Update pathogen-embed to 2.1.0

recipes/taxonkit/meta.yaml
- [TaxonKit v0.17.0](https://github.com/shenwei356/taxonkit/releases/tag/v0.17.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/taxonkit/v0.17.0/total.svg)](https://github.com/shenwei356/taxonkit/releases/tag/v0.17.0)
- `taxonkit filter`:
- Fix keeping taxids with a rank of "no rank" or "clade". [#97](https://github.com/shenwei356/taxonkit/issues/97)
- `taxonkit list`:
- Accept input TaxIds from stdin/files, not just the flag `--ids`. [#93](https://github.com/shenwei356/taxonkit/issues/93)
- `taxonkit name2taxid`:
- Add support of fuzzy match with `-f/--fuzzy`. [#88](https://github.com/shenwei356/taxonkit/issues/88)
- `taxonkit profile2cami`:
- Add a new flag `-S/--no-sum-up` to disable summing up abundances. …
=> Update TaxonKit to 0.17.0

recipes/arriba/build.sh, recipes/arriba/meta.yaml, recipes/star/meta.yaml
=> arriba: add linux-aarch64 build

recipes/codoff/meta.yaml
Take away requirement for specific biopython version from codoff's meta.yaml to prevent issues with installation of other programs. 
---- …
=> Update codoff 

recipes/survivor/build.sh, recipes/survivor/meta.yaml
=> survivor: add linux-aarch64 build

recipes/tcdemux/meta.yaml
`tcdemux` [needs to be updated](https://github.com/TomHarrop/tcdemux/issues/26) to snakemake 8 but just pinning the deps for now.
---- …
=> Update tcdemux recipe

.circleci/config.yml, recipes/iqtree/meta.yaml
=> Update iqtree to 2.3.5

recipes/ribotaper/meta.yaml
=> Fix ribotaper readlink bug

recipes/ribotaper/LICENSE, recipes/ribotaper/meta.yaml
Thanks @mkatsanto for noticing!
---- …
=> fix: readlink (with k) is in coreutils, not readline

recipes/dysgu/meta.yaml
=> dysgu 1.6.4 Update meta.yaml

recipes/cpstools/build.sh, recipes/cpstools/meta.yaml
=> add cpstools recipes

recipes/handyreadgenotyper/meta.yaml
Change python dependency to be >3.10 from =3.9.
=> Update to version 0.1.21

recipes/decifer/build.sh, recipes/decifer/meta.yaml
=> decifer: add linux-aarch64 build

recipes/bigtools/meta.yaml
=> bigtools: add linux-aarch64 build

recipes/dysgu/conda_build_config.yaml, recipes/dysgu/meta.yaml
=> dysgu: add linux-aarch64 build

recipes/manta/meta.yaml
* see the minimum specification here: https://github.com/Illumina/manta/blob/75b5c38d4fcd2f6961197b28a41eb61856f2d976/docs/userGuide/installation.md?plain=1#L59
* also note, we had it installing a python version `1.6` in the snakemake wrapper: https://github.com/snakemake/snakemake-wrappers/pull/2114/files#diff-8b4a5764a647f4182cb9f49051b48b25e5b72e38365ec1311475134a3440ed76R7
---- …
=> fix: ensure minimum python version of 2.6 for manta

recipes/augur/meta.yaml, recipes/auspice/meta.yaml, recipes/nextclade/meta.yaml, recipes/nextclade2/meta.yaml, recipes/nextclade2/run_test.sh, recipes/nextstrain-cli/meta.yaml, recipes/nextstrain/meta.yaml, recipes/treetime/meta.yaml
=> Add publication identifiers to nextstrain recipes, aarch64 to nextclade2

recipes/crispector2/meta.yaml
newer pandas package version
---- …
=> crispector2: v2.1.2

recipes/narfmap/meta.yaml
=> chore: Emiller88 => bioinformaticsorphanange

recipes/nonpareil/meta.yaml
=> Update Nonpareil 3.5.4

recipes/orthanq/meta.yaml, recipes/ufcg/meta.yaml
=> update ufcg to 1.0.6

recipes/piscem/meta.yaml
Move from vcs to `source_recursive` for build.
---- …
=> bump piscem to v0.10.0

recipes/sentieon/meta.yaml
Update sentieon to 202308.03
---- …
=> Update sentieon to 202308.03

recipes/pybigtools/meta.yaml
=> pybigtools: add linux-aarch64 build

recipes/voyager/build.sh, recipes/voyager/meta.yaml, recipes/voyager/run_test.sh
=> Add voyager

recipes/poppunk/meta.yaml
=> Update poppunk to v2.6.7

recipes/zol/meta.yaml
Restrict DIAMOND to versions  >=2.1.7 because zol uses the --ignore-warnings argument that was temporarily removed in some versions.
---- …
=> Update zol 

recipes/fasta3/build.sh, recipes/fasta3/meta.yaml
=> fasta3: add linux-aarch64 build

recipes/cpat/meta.yaml
=> cpat: add linux-aarch64 build

recipes/generax/build.sh, recipes/generax/meta.yaml
=> generax: add linux-aarch64 build

recipes/ipk/meta.yaml
=> ipk: add linux-aarch64 build

recipes/trust4/build.sh, recipes/trust4/meta.yaml
=> trust4: add linux-aarch64 build

recipes/odgi/meta.yaml, recipes/odgi/patch
=> Patch odgi for bugfix

recipes/t1k/build.sh, recipes/t1k/meta.yaml
=> t1k: add linux-aarch64 build

recipes/physher/build.sh, recipes/physher/meta.yaml, recipes/physher/physher-aarch64.patch
=> physher: add linux-aarch64 build

recipes/haplomap/build.sh, recipes/haplomap/meta.yaml
=> haplomap: add linux-aarch64 build

recipes/vamos/build.sh, recipes/vamos/meta.yaml, recipes/vamos/vamos-aarch64.patch
=> vamos: add linux-aarch64 build

recipes/htslib/meta.yaml
=> Build htslib on macOS ARM

recipes/iqtree/meta.yaml
=> Build Iqtree for osx-arm64

recipes/pyfastx/meta.yaml
=> Build pyfastx for osx-arm64

recipes/ncbi-vdb/meta.yaml
=> Build ncbi-vdb on osx-arm64

recipes/bx-python/meta.yaml
=> Build bx-python for osx-arm64

recipes/bcftools/meta.yaml, recipes/samtools/meta.yaml
These depend on the previously built htslib.
---- …
=> Build samtools and bcftools on macOS ARM

recipes/pysam/meta.yaml
Rebuild pysam, to finally address pysam-developers/pysam#1206.
---- …
=> Build pysam on macOS ARM

recipes/fasttree/meta.yaml
- **Build fasttree for osx-arm64**
=> Build fasttree for osx-arm64

recipes/bedtools/meta.yaml
=> Build bedtools on macOS ARM

recipes/foldcomp/meta.yaml
=> Update foldcomp with ARM support

recipes/plass/meta.yaml
=> Update plass with MacOS ARM support

recipes/metaeuk/meta.yaml
=> Update metaeuk with MacOS ARM support

recipes/spacepharer/meta.yaml
=> Update spacpharer with MacOS ARM support

recipes/kalign2/meta.yaml
=> Update kalign2 with MacOS ARM support

recipes/metabuli/meta.yaml
=> Update metabuli with MacOS ARM support

recipes/hhsuite/meta.yaml
=> Update hhsuite with MacOS ARM support

recipes/mmseqs2/meta.yaml
=> Update MMseqs2 with MacOS ARM support

recipes/psdm/meta.yaml
=> Update psdm with arm support

recipes/rasusa/meta.yaml
=> update rasusa with osx arm64 support

recipes/csvtk/meta.yaml
=> Builds csvtk for osx-arm64

recipes/clermontyping/meta.yaml
For some reason, Azure didn't run on the final commit of https://github.com/bioconda/bioconda-recipes/pull/48829
---- …
=> rebuild clermontyping

recipes/colorid_bv/build.sh, recipes/colorid_bv/meta.yaml
update colorid_bv to include the executable colorid too. This executable is exactly the same thing except it does not allow multithreading. By making this, we help the package become more reverse-compatible.
----
* Please post …
=> Colorid_bv

recipes/piscem/meta.yaml
=> Try building piscem on osx-arm64

recipes/xtandem/build.sh, recipes/xtandem/meta.yaml
=> xtandem: add linux-aarch64 build

recipes/mmseqs2-server/meta.yaml
=> Update MMseqs2 server with MacOS ARM support

recipes/taxonkit/meta.yaml
=> Add osx-arm64 support for TaxonKit

recipes/icfree-ml/meta.yaml
=> build(icfree-ml): update python versions allowed

recipes/bowtie2/meta.yaml
=> bowtie2: add osx-arm64

recipes/epik/build.sh, recipes/epik/epik-aarch64.patch, recipes/epik/meta.yaml
Pin boost to 1.85 as discussed at https://github.com/bioconda/bioconda-recipes/pull/49000
---- …
=> epik: add linux-aarch64 build

recipes/gap2seq/build.sh, recipes/gap2seq/meta.yaml
=> gap2seq: add linux-aarch64 build

recipes/phylodm/meta.yaml
=> phylodm: add aarch64/arm64 builds

recipes/mbg/.gitattributes, recipes/mbg/build.sh, recipes/mbg/mbg-aarch64.patch, recipes/mbg/meta.yaml
=> mbg: add aarch64/arm64 builds

recipes/skesa/build.sh, recipes/skesa/meta.yaml, recipes/skesa/skesa-aarch64.patch
=> skesa: add linux-aarch64 build

recipes/augur/meta.yaml
Includes dependency and maintainer list updates.
---- …
=> Update augur to 25.1.0

README.md
=> [skip ci] Add supported architectures to readme

recipes/breseq/build.sh, recipes/breseq/meta.yaml
=> breseq: add aarch64/arm64 support

recipes/gtdb_to_taxdump/meta.yml
=> Add new recipe gtdb_to_taxdump

recipes/perl-digest-sha1/meta.yaml
=> perl-digest-sha1: enable osx-arm64 build

recipes/pairix/meta.yaml
=> pairix: enable osx-arm64 build

recipes/poseidon-trident/meta.yaml
Added our new `osx-arm64` executable for this release.
---- …
=> Update poseidon-trident to 1.5.4.0

recipes/hictk/meta.yaml
=> hictk: enable osx-arm64 build

recipes/checkqc/meta.yaml
This PR updates checkqc to 4.0.4. It uses versions released in GitHub instead of PyPi.
---- …
=> Update checkqc to 4.0.4

recipes/narfmap/build.sh, recipes/narfmap/meta.yaml
=> Fix NARFMAP static build

recipes/perbase/meta.yaml
perbase: add osx-arm64 build
---- …
=> perbase: add osx-arm64 build

recipes/gsearch/meta.yaml
=> Update gsearch v0.2.0

recipes/comparem2/build.sh, recipes/comparem2/meta.yaml
Update CompareM2 - genomes-to-report pipeline.
---- …
=> Update CompareM2 to v2.8.2

recipes/pathogen-embed/meta.yaml
Update pathogen-embed to 2.2.0.
---- …
=> Update pathogen-embed to 2.2.0

recipes/singlem/meta.yaml
Been having some issues with breaking changes so locking almost all dependencies.
---- …
=> singlem: Pin deps and update description.

recipes/hicap/meta.yaml
- use correct biopython version
- see https://github.com/scwatts/hicap/issues/7
/cc @KatSteinke
---- …
=> Update hicap recipe

recipes/viguno/meta.yaml
=> viguno: add linux-aarch64 build

recipes/bellmans-gapc/build.sh, recipes/bellmans-gapc/meta.yaml, recipes/knotinframe/build.sh, recipes/knotinframe/meta.yaml
=> knotinframe & bellmans-gapc: add linux-aarch64 build

recipes/r-rrbgen/meta.yaml
=> r-rrbgen: add aarch64/arm64 builds

recipes/architeuthis/meta.yaml
=> architeuthis: add aarch64/arm64 builds

recipes/egglib/meta.yaml
=> egglib: add aarch64/arm64 builds

recipes/mappy/meta.yaml
=> Build mappy on macOS ARM

recipes/liftoff/meta.yaml
Pinned minimap2 version in liftoff to fix file not found error: https://github.com/nf-core/modules/actions/runs/9654312526/job/26628335722
Verified here: https://github.com/nf-core/modules/actions/runs/9951336845/job/27490669473
Potentially fixes: https://github.com/agshumate/Liftoff/issues/128
---- …
=> Pinned minimap2 version in liftoff

recipes/seismic-rna/build.sh, recipes/seismic-rna/meta.yaml
Add a recipe for the package `seismic-rna`.
SEISMIC-RNA is software for processing RNA mutational profiling data and separating RNA ensembles into their constituent structures. For more information, please see the GitHub repo (https://github.com/rouskinlab/seismic-rna) and BioRxiv preprint (https://doi.org/10.1101/2024.04.29.591762).
----
* PRs require reviews prior to being merged. …
=> Add recipe for seismic-rna

recipes/pixelator/meta.yaml
=> Update pixelator to 0.18.2

recipes/pytrf/meta.yaml
=> pytrf: add aarch64/arm64 builds

build-fail-blacklist, recipes/ucsc-pslsort/build.sh, recipes/ucsc-pslsort/include.patch, recipes/ucsc-pslsort/meta.yaml
=> ucsc-pslsort: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-nibfrag/build.sh, recipes/ucsc-nibfrag/include.patch, recipes/ucsc-nibfrag/meta.yaml
=> ucsc-nibfrag: add linux-aarch64 build

recipes/libbigwig/meta.yaml
=> libbigwig: add osx-arm64 build

build-fail-blacklist, recipes/ucsc-xmlcat/build.sh, recipes/ucsc-xmlcat/include.patch, recipes/ucsc-xmlcat/meta.yaml
=> ucsc-xmlcat: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-tolower/build.sh, recipes/ucsc-tolower/include.patch, recipes/ucsc-tolower/meta.yaml
=> ucsc-toLower: add linux-aarch64 build

recipes/orfanage/build.sh, recipes/orfanage/meta.yaml
=> orfanage: add aarch64/arm64 builds

recipes/fastp/build.sh, recipes/fastp/meta.yaml
=> fastp: add osx-arm64 build

recipes/biobb_chemistry/meta.yaml
=> [biobb_chemistry] update 4.2.1

recipes/r-stitch/build.sh, recipes/r-stitch/conda_build_config.yaml, recipes/r-stitch/meta.yaml, recipes/r-stitch/seqlib-aarch64.patch
=> r-stitch: add linux-aarch64 build

recipes/metacerberus-lite/meta.yaml
Please add MetaCerberus-lite
a reduced version of MetaCerberus
---- …
=> Add MetaCerberus-lite

recipes/proteinortho/meta.yaml
update to 6.3.2 (autobump seems not to like this release)
=> manual update v6.3.2

recipes/bwa/meta.yaml
=> Build bwa on macOS ARM

recipes/crispresso2/meta.yaml
This PR pins the matplotlib and numpy versions in the recipe (due to breaking changes in the most recent major releases of both).
---- …
=> Update CRISPResso2 dependencies

recipes/hmftools-neo/meta.yaml, recipes/hmftools-neo/neo.sh
- update hmftools-neo recipe to 1.2_beta
---- …
=> Update hmftools-neo to 1.2_beta

recipes/hmftools-esvee/build.sh, recipes/hmftools-esvee/esvee.sh, recipes/hmftools-esvee/meta.yaml
Add recipe for hmftools-esvee 1.0_beta
---- …
=> Add hmftools-esvee 1.0_beta

recipes/sdrf-pipelines/meta.yaml
=> sdrf-pipelines update to 0.0.27

recipes/longphase/build.sh, recipes/longphase/meta.yaml
=> Add longphase

recipes/khmer/meta.yaml
trying to update `khmer` recipe so that it is compatible with versions of python up to 3.11.x (<3.12).
=> attempting to update `khmer` pinnings

build-fail-blacklist, recipes/ucsc-psltochain/build.sh, recipes/ucsc-psltochain/include.patch, recipes/ucsc-psltochain/meta.yaml
=> ucsc-psltochain: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-stringify/build.sh, recipes/ucsc-stringify/include.patch, recipes/ucsc-stringify/meta.yaml
=> ucsc-stringify: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-psltobed/build.sh, recipes/ucsc-psltobed/include.patch, recipes/ucsc-psltobed/meta.yaml
=> ucsc-psltobed: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-oligomatch/build.sh, recipes/ucsc-oligomatch/include.patch, recipes/ucsc-oligomatch/meta.yaml
=> ucsc-oligomatch: add linux-aarch64 build

recipes/kalign3/build.sh, recipes/kalign3/meta.yaml
=> kalign3: add aarch64/arm64 builds

recipes/cancerit-allelecount/build.sh, recipes/cancerit-allelecount/meta.yaml
=> cancerit-allelecount: add linux-aarch64 build

recipes/fido/build.sh, recipes/fido/meta.yaml
=> fido: add linux-aarch64 build

recipes/famsa/build.sh, recipes/famsa/meta.yaml
=> famsa: add aarch64/arm64 builds

recipes/hits/meta.yaml
=> Upgrade hits to 0.4.2

recipes/cassiopeia/meta.yaml
=> Add recipe for cassiopeia v2.0.0

recipes/crispresso2/meta.yaml
Adding `osx-arm64` to the `crispresso2` recipe.
---- …
=> Update crispresso2: osx-arm64 additional platform

recipes/hits/meta.yaml
=> hits: add aarch64/arm64 builds

recipes/cassiopeia/meta.yaml
=> Update cassiopeia recipe

recipes/scmidas/meta.yaml
=> Add recipe for scmidas 0.0.17

recipes/jupiterplot/LICENSE, recipes/jupiterplot/build.sh, recipes/jupiterplot/meta.yaml
Adding this genome visualization tool: https://github.com/JustinChu/jupiterplot to bioconda.
Upon adding this request https://github.com/bioconda/bioconda-recipes/pull/26504 may be closed.
---- …
=> Add new recipe: Jupiterplot

recipes/viennarna/build.sh, recipes/viennarna/meta.yaml, recipes/viennarna/remove-register.patch
=> Update viennarna to build for platform osx-arm64

recipes/primer3-py/meta.yaml
=> Build primer3-py on macOS ARM

recipes/cmaple/build.sh, recipes/cmaple/meta.yaml, recipes/cmaple/patch
=> Add cmaple recipe

recipes/auspice/build.sh, recipes/auspice/meta.yaml
- Run `yarn cache clean --all` to remove unnecessary cache, saving 250 MB
- Make build.sh posix compliant and DRYer
---- …
=> fix: half auspice pkg size through `yarn cache clean`

recipes/handyreadgenotyper/meta.yaml
- Fixed minor bugs
- Relaxed Python version requirement to >=3.10
- Added extra detail to report
---- …
=> Update HandyReadGenotyper to version 0.1.22

recipes/scrubby/build.sh, recipes/scrubby/meta.yaml
Originally started here: https://github.com/bioconda/bioconda-recipes/pull/39452
Adds scrubby
---- …
=> add recipe for scrubby

recipes/querynator/meta.yaml
fixes [querynator issue 37](https://github.com/qbic-pipelines/querynator/issues/37) that prevailed with the biocontainer
---- …
=> querynator: pin pandas to 1.5.3

recipes/btllib/meta.yaml
Add build for osx-arm64
Don't install optional lrzip dependency for osx-arm64 (no build available currently, and attempts to do that build weren't working).
---- …
=> btllib build for osx-arm64

recipes/pybedtools/meta.yaml
Enable osx-arm64 build for pybedtools
---- …
=> pybedtools: add osx-arm64 build

recipes/r-easylift/build.sh, recipes/r-easylift/meta.yaml
This adds the R package `easyLift` from GitHub https://github.com/caleblareau/easyLift as `r-easylift`. Please note that this is distinct from `bioconductor-easylift`. This is needed as a dependency of `r-epitrace` (see #49412).
---- …
=> Add R package `easyLift` as `r-easylift`

recipes/hybpiper/meta.yaml
Updating entry point of HybPiper from `hybpiper.assemble:main` to `hybpiper.hybpiper_main:main` due to refactor in v2.2.0.
---- …
=> Update HybPiper entry point for v2.2.0

recipes/pydna/meta.yaml
Includes build updates caused by pydna switching to Poetry.
---- …
=> Update pydna to 5.2.0

recipes/blast/meta.yaml
Updates BLAST from 2.15.0 to 2.16.0.
---- …
=> Update BLAST to 2.16.0

recipes/ntroot/build.sh, recipes/ntroot/meta.yaml
* Adding missing file in install
---- …
=> Bump build for ntroot

recipes/transannot/meta.yaml
Updated TransAnnot after revising its manuscript
---- …
=> update TransAnnot version after the paper revision

recipes/comparem2/meta.yaml
I had an error in my code that I wish to fix for this version.
---- …
=> Update CompareM2 v2.9.1 (increment build number)

recipes/r-gchromvar/build.sh, recipes/r-gchromvar/meta.yaml
Adds [GitHub R package `gchromVAR`](https://github.com/caleblareau/gchromVAR) as `r-gchromvar`. Using version-bumping commit as UID since repository lacks tags ([upstream issue filed](https://github.com/caleblareau/gchromVAR/issues/12)).
---- …
=> add R package `gchromVAR` as `r-gchromvar`

recipes/splitubam/build.sh, recipes/splitubam/meta.yaml
=> Add splitubam

recipes/kallisto/build.sh, recipes/kallisto/meta.yaml
Bump kallisto to v0.51.0. Also attempting to add Apple Silicon (`osx-arm64`) build support.
---- …
=> Update kallisto to v0.51.0

recipes/r-scavenge/build.sh, recipes/r-scavenge/meta.yaml
Adds [the GitHub R package `SCAVENGE`](https://github.com/sankaranlab/SCAVENGE) as `r-scavenge`. Uses commit as UID in lieu of any git tag ([left issue upstream](https://github.com/sankaranlab/SCAVENGE/issues/15)).
----
* Please …
=> Adds R package `SCAVENGE` as `r-scavenge`

recipes/r-redeemr/meta.yaml
=> Add recipe for r-redeemR v1.0.0

recipes/tides-ml/meta.yaml
Updated version requirements/information for main package and dependencies
=> Update package and dependency versions

recipes/staden_io_lib/arm_hwcap.patch, recipes/staden_io_lib/config.patch, recipes/staden_io_lib/meta.yaml
Bump staden_io_lib to 1.15.0 and activate macOS builds.
---- …
=> Bump staden_io_lib to 1.15.0 and activate macOS builds

recipes/zdb/meta.yaml
- Update version pinnings
- Add new maintainer, doc URL and license_family.
=> Update zDB to version 1.3.1 and update recipe.

recipes/kma/build.sh, recipes/kma/meta.yaml
=> kma: add arm64 build

recipes/entrez-direct/meta.yaml
Update `entrez-direct` to 22.4, as well as enabling the `osx-arm64` build (looks to be fully compatible with the dependencies).
---- …
=> Update `entrez-direct` to 22.4

recipes/seacells/meta.yaml
=> Add recipe for SEAcells v0.3.3

recipes/abyss/config.patch, recipes/abyss/meta.yaml
=> Build abyss for osx-arm64

recipes/ctxcore/meta.yaml
=> Add recipe for ctxcore v0.2.0

recipes/polypolish/build.sh, recipes/polypolish/meta.yaml
=> polypolish: add aarch64/arm64 build

recipes/binchicken/meta.yaml
Update binchicken to v0.12.0
---- …
=> Update binchicken to 0.12.0

recipes/narfmap/build.sh, recipes/narfmap/meta.yaml
Follow up to #49189 since it didn't work.
---- …
=> Static link NARFMAP

recipes/eskrim/meta.yaml
=> Add recipe for ESKRIM 

recipes/augur/meta.yaml
Update augur to version 25.2.0 and updates dependencies accordingly to include python-calamine.
Replaces https://github.com/bioconda/bioconda-recipes/pull/49529
---- …
=> Update augur to 25.2.0

recipes/ntsynt/meta.yaml
=> Bump ntsynt build - build for linux-aarch64 and osx-arm64

recipes/arcs/build.sh, recipes/arcs/meta.yaml
=> Bump build for arcs - build for linux-aarch64 and osx-arm64

recipes/binchicken/meta.yaml
=> Update binchicken recipe to fix pins

recipes/binchicken/meta.yaml
=> Update binchicken to v0.12.1

recipes/rcx-tk/meta.yaml
This is a recipe for rcx-tk package, which provides custom tools to process the metadata or alkane files.
----
Conda is …
=> Add recipe for rcx-tk

recipes/links/meta.yaml
=> Bump build for links - builds for linux-aarch64 and osx-arm64

recipes/nthits/meta.yaml
=> Update nthits build - build for linux-aarch64 and osx-arm64

recipes/dapcy/meta.yaml
Initial commit of the dapcy package (0.1.1). 
Linting and build testing seems to work locally/in docker.
----
<details>
<summary>PR instructions</summary> …
=> Add recipe for dapcy

recipes/r-mfassignr/meta.yaml
Initial commit of the MFAssignR package for multi-element molecular formula (MF) assignment of ultrahigh resolution mass spectrometry measurements.
---- …
=> Add MFAssignR

recipes/centrosome/meta.yaml
=> centrosome: add aarch64/arm64 builds

recipes/ntcard/build.sh, recipes/ntcard/meta.yaml
=> Update ntcard build - builds for linux-aarch64 and osx-arm64

recipes/zol/build.sh, recipes/zol/meta.yaml
To Reviewers,
Hi, I am the developer of zol and in this PR just making it so that python 3.10 artifacts are build - because I need this configuration for a separate tool I am developing for which zol will be a dependency - as you can probably see it to me a good bit of tinkering. I hit a strange error related to trying to build artifacts for >3.10 (so also 3.11, 3.12) - which I will look into later. For the moment, can you please approve the changes.
Thank you in advance!!
Rauf 
---- …
=> Upade zol recipe

recipes/bali-phy/meta.yaml
Update bali-phy: 4.0-beta14 -> 4.0-beta15
=> Update bali-phy: 4.0-beta15

recipes/d4tools/meta.yaml
=> d4tools: add aarch64 build

recipes/ntedit/meta.yaml
=> Update ntedit build - add builds for linux-aarch64 and osx-arm64

recipes/bali-phy/meta.yaml
=> bali-phy: add aarch64/arm64 builds

recipes/treesimulator/meta.yaml
Add treesimulator recipe 
-------------------------
Info | Link or Description
-- | --
Recipe | recipes/treesimulator
Summary | Simulation of rooted phylogenetic trees under a given Multitype Birth–Death (MTBD) model.
Home | https://github.com/evolbioinfo/treesimulator
Releases | https://github.com/evolbioinfo/treesimulator/releases
Recipe Maintainer(s) | @annazhukova
=> treesimulator recipe

recipes/unicycler/build.sh, recipes/unicycler/meta.yaml
=> Build Unicycler on macOS

recipes/flye/meta.yaml
=> flye: add arm64 build

recipes/savana/meta.yaml
Additional changes for SAVANA v1.2.0 not picked up in the autobump #49581
---- …
=> Update savana to 1.2.0 - pin versions, cna subcommand test, LICENSE update

recipes/abnumber/meta.yaml
=> Bump up abnumber to 0.3.6

recipes/clair3/meta.yaml
=> update Clair3 to v1.0.10

recipes/cstag/meta.yaml
Removing `wasyprint` because it is not necessary to install it in `cstag` v1.1.0.
---- …
=> Remove wasyprint in cstag

recipes/longshot/build.sh, recipes/longshot/meta.yaml, recipes/longshot/update-rust-htslib.patch
=> longshot: add arm64 build

recipes/pacu_snp/meta.yaml
Updated PACU SNP to version 0.0.4.
Added entry point for the `PACU_galaxy` command.
=> Update pacu_snp to v0.0.4

recipes/btllib/meta.yaml
Making fresh PR because autobump from bot seemed to fail due to transient error?
---- …
=> Update btllib to 1.7.3

recipes/gempipe/meta.yaml
=> add gempipe recipe

recipes/segalign-galaxy/meta.yaml
adding missing requirement (gzip) for segalign
---- …
=> adding missing requirement (gzip) for segalign

recipes/cellprofiler-core/meta.yaml
=> Update cellprofiler-core to 4.2.7

recipes/wfa2-lib/build.sh, recipes/wfa2-lib/meta.yaml
=> wfa2-lib: add arm64 build

recipes/tabixpp/meta.yaml
=> tabixpp: add arm64 build

recipes/scspectra/meta.yaml
=> Add recipe for scspectra v0.2.0

recipes/strangepg/build.sh, recipes/strangepg/meta.yaml
Add strangepg, pangenome-scale interactive graph visualization.
=> add strangepg package

recipes/bio/meta.yaml
=> Add recipe for bio v1.7.1

recipes/python-edlib/meta.yaml
=> python-edlib: add arm64 build

recipes/pyabpoa/meta.yaml
=> pyabpoa: add arm64 build

recipes/pyspoa/meta.yaml
=> pyspoa: add arm64 build

recipes/gempipe/meta.yaml
=> update gempipe to v1.33.1

recipes/diphase/build.sh, recipes/diphase/meta.yaml
=> Add a new repo diphase

recipes/transannot/meta.yaml
update TransAnot version after a new release
---- …
=> update TransAnnot version

recipes/iqtree/build.sh, recipes/iqtree/meta.yaml
=> Disable avx for iqtree for x86-64

recipes/perl-json-xs/meta.yaml
Run ARM builds to `perl-json-xz`, as well as populating the missing `license` field.
---- …
=> Add ARM build to `perl-json-xz`

recipes/rpsbproc/LICENSE, recipes/rpsbproc/build.sh, recipes/rpsbproc/conda_build_config.yaml, recipes/rpsbproc/configurellvm.patch, recipes/rpsbproc/meta.yaml, recipes/rpsbproc/normbase.patch, recipes/rpsbproc/phonehome.patch, recipes/rpsbproc/update_configsub.patch
Add RpsbProc in a separate recipe, as it has to be taken out from the `blast` recipe.
Related to: #49443
----
Conda is …
=> Add RpsbProc

recipes/ucsc-blat/meta.yaml
=> Update ucsc-blat to 468

recipes/bigslice/meta.yaml
=> Add bigslice

recipes/pyrodigal/meta.yaml
=> pyrodigal: add arm64 build

recipes/pyhmmer/meta.yaml
=> pyhmmer: add arm64 build

recipes/espresso/build.sh, recipes/espresso/meta.yaml
v1.5.0 introduces a compiled perl module for a C library
---- …
=> Update espresso to v1.5.0

recipes/perl-json/meta.yaml
=> Fix perl-json dependencies

recipes/parm/meta.yaml
* PARM now checks if the input fasta contains any sequence longer than the L_max
* Added L_max parameters for the tasks, in case of custom models are used for them
* Improved the verbosity and small fixes of the PARM train
*[bioconda] adds pytorch-cuda as a requirement
**Full Changelog**: https://github.com/vansteensellab/PARM/compare/v0.0.5...v0.0.6
=> Update PARM to v0.0.6

recipes/oarfish/build.sh, recipes/oarfish/meta.yaml
=> oarfish: add aarch64/arm64 builds

recipes/genomescope2/meta.yaml
=> genomescope2 update

recipes/pkiss/meta.yaml
=> pkiss: add linux-aarch64 support

recipes/clusty/meta.yaml
=> clusty: add aarch64/arm64 builds

recipes/rnashapes/meta.yaml
=> rnashapes: add linux-aarch64 support

recipes/reduce/meta.yaml
=> reduce: add aarch64/arm64 builds

recipes/orthanq/meta.yaml
Orthanq relies on minimap2 for candidate generation and it's missing in the dependency list.
---- …
=> Update orthanq dependencies

recipes/reduce/meta.yaml
I removed `libboost-python-devel` that is unnecessary dependency to build the package.
ref: https://github.com/rlabduke/reduce/pull/57
---- …
=> Update Reduce v4.14 without libboost-python-devel

recipes/sequencetools/meta.yaml
=> Update sequencetools to v1.5.4.0

recipes/lsabgc/build.sh, recipes/lsabgc/meta.yaml
=> Add lsaBGC

recipes/plasnet/meta.yaml
Adds a recipe for the plasnet package. First one I've done which uses poetry
---- …
=> Add recipe for plasnet

recipes/foldmason/build.sh, recipes/foldmason/meta.yaml
=> Add FoldMason

recipes/filtlong/build.sh, recipes/filtlong/meta.yaml
=> filtlong: add aarch64/arm64 builds

recipes/quicksect/meta.yaml
=> quicksect: add aarch64/arm64 builds

recipes/sanntis/meta.yaml
- Updated `meta.yaml` to pin the scipy dependency. This change addresses compatibility issues causing runtime errors in SanntiS.
- Incremented the build number.
---- …
=> Update SanntiS to ensure compatibility with scipy version

recipes/bam-readcount/build.sh, recipes/bam-readcount/meta.yaml
=> bam-readcount: add linux-aarch64 support

recipes/last/build.sh, recipes/last/meta.yaml
=> Update last to 1550

recipes/tantan/build.sh, recipes/tantan/meta.yaml
=> Update tantan to 50

recipes/iqtree/build.sh, recipes/iqtree/meta.yaml
=> Update iqtree to v2.3.6

recipes/table2asn/build.sh, recipes/table2asn/meta.yaml
=> Update table2asn to 1.28.1111

recipes/centrifuger/meta.yaml
- Add osx-arm64 to the meta.yaml
---- …
=> Add osx-arm64 support to centrifuger

recipes/bam-readcount/build.sh, recipes/bam-readcount/meta.yaml
=> bam-readcount: build on OSX

recipes/umi_tools/meta.yaml
=> umi_tools: add arm64 build

recipes/cite-seq-count/meta.yaml
=> Update cite-seq-count recipe

recipes/cgranges/meta.yaml, recipes/pybedlite/meta.yaml
=> pybedlite & cgranges: add aarch64/arm64 builds

recipes/insurveyor/INSurVeyor-aarch64.patch, recipes/insurveyor/build.sh, recipes/insurveyor/meta.yaml
=> insurveyor: add aarch64/arm64 builds

recipes/metamdbg/0.3/build.sh, recipes/metamdbg/0.3/meta.yaml, recipes/metamdbg/meta.yaml
Update metaMDBG: 0.3 -> 1.0
---- …
=> Update metaMDBG to 1.0

recipes/bioconda-repodata-patches/gen_patch_json.py, recipes/bioconda-repodata-patches/meta.yaml
Bump the patching to account for conda-forge/libdeflate-feedstock#27, which does not change the library's soversion.
---- …
=> Bump bioconda-repodata-patches for new libdeflate release

recipes/graphbin2/meta.yaml, recipes/oarfish/meta.yaml
This PR adds [graphbin2](https://github.com/metagentools/GraphBin2) (GraphBin2: Refined and Overlapped Binning of Metagenomic Contigs Using Assembly Graphs) to bioconda. GraphBin2 is a metagenomic bin-refinement tool and is implemented in Python.
Publications
* 20th International Workshop on Algorithms in Bioinformatics ([WABI 2020](http://algo2020.di.unipi.it/WABI2020/)): [10.4230/LIPIcs.WABI.2020.8](https://doi.org/10.4230/LIPIcs.WABI.2020.8)
* BMC Algorithms for Molecular Biology: [10.1186/s13015-021-00185-6](https://doi.org/10.1186/s13015-021-00185-6)
----
* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the first …
=> Add graphbin2 v1.3.1

recipes/phylodeep_data_bdss/meta.yaml
Add phylodeep_data_bdss recipe 
-------------------------
Info | Link or Description
-- | --
Recipe | recipes/phylodeep_data_bdss
Summary | Package containing data for the [phylodeep](https://github.com/evolbioinfo/phylodeep) package.
Home | https://github.com/evolbioinfo/phylodeep_data_bdss
Recipe Maintainer(s) | @annazhukova
=> phylodeep_data_bdss package (needed for phylodeep)

recipes/phylodeep_data_bdei/meta.yaml
Add phylodeep_data_bdei recipe 
-------------------------
Info | Link or Description
-- | --
Recipe | recipes/phylodeep_data_bdei
Summary | Package containing data for the [phylodeep](https://github.com/evolbioinfo/phylodeep) package.
Home | https://github.com/evolbioinfo/phylodeep_data_bdei
Recipe Maintainer(s) | @annazhukova
=> phylodeep_data_bdei package (needed for phylodeep)

recipes/mpra-data-access-portal/meta.yaml
upgrading mpra-data-access-portal to 0.1.9
---- …
=> Update mpra-data-access-portal to 0.1.9

recipes/pytaxonkit/meta.yaml
TaxonKit version 0.17 has a bugfix for `taxonkit filter`. The test suite for the updated PyTaxonKit bindings will now fail unless the latest version is installed.
---- …
=> Pin taxonkit>=0.17

recipes/gw/meta.yaml
When installing GW on linux from a mini forge/ mamba base bistro, the core dependency tree libs are missing. This PR tries to include missing libs
---- …
=> Update GW - Fixing missing libs for mamba build

recipes/fastool/build.sh, recipes/fastool/meta.yaml
=> fastool: add aarch64/arm64 builds

recipes/cospar/meta.yaml
=> Update cospar to 0.4.1

recipes/sage-proteomics/build.sh, recipes/sage-proteomics/meta.yaml
=> sage-proteomics: add aarch64/arm64 builds

recipes/irfinder/build.sh, recipes/irfinder/meta.yaml
=> irfinder: add aarch64/arm64 builds

recipes/chromap/build.sh, recipes/chromap/chromap-aarch64.patch, recipes/chromap/meta.yaml
- Add arm64 for linux and osx to the meta.yaml file.
---- …
=> Add arm64 support to Chromap

recipes/gw/meta.yaml
This is to try and fix missing EGL libs
---- …
=> GW recipe update

recipes/meme/build.sh, recipes/meme/meta.yaml
=> Update meme to 5.5.6

recipes/yak/build.sh, recipes/yak/meta.yaml, recipes/yak/yak.patch
=> yak: add aarch64/arm64 build

recipes/fastani/build.sh, recipes/fastani/meta.yaml
Update fastani to build osx-arm64
---- …
=> Update fastani to build osx-arm64

recipes/picrust2/meta.yaml, recipes/picrust2/post-link.sh
Update to PICRUSt2 v2.5.3.
---- …
=> Update Picrust2 v2.5.3

recipes/fastme/build.sh, recipes/fastme/meta.yaml
=> fastme: add aarch64/arm64 builds

recipes/nextpolish2/build.sh, recipes/nextpolish2/meta.yaml
=> nextpolish2: add aarch64/arm64 builds

recipes/rust-ncbitaxonomy/build.sh, recipes/rust-ncbitaxonomy/meta.yaml
=> rust-ncbitaxonomy: add aarch64/arm64 builds

build-fail-blacklist, recipes/parafly/build.sh, recipes/parafly/meta.yaml, recipes/parafly/parafly-aarch64.patch
=> parafly: add linux-aarch64 build

recipes/promotercalculator/meta.yaml
Adds the Barrick Lab fork of Promoter-Calculator, a python package for predicting transcription start sites. The original Promoter-Calculator repo is offered as a script and not a package - our fork adds that functionality. Additionally, it adds parallel processing and some filtering to reduce memory usage. This package is a dependency of our upcoming work which depends on ViennaRNA and TranstermHP, so we need to add all other dependencies to enable that work to be installed in one line.
Last PR was not properly branched to exclude my other pending PR for another dependency.
----
* If this PR adds or updates a recipe, use "Add" or "Update" …
=> Add Promoter-Calculator

recipes/rhotermpredict/meta.yaml
Adds the Barrick Lab fork of RhoTermPredict, a python package for predicting the present of Rho-dependent terminators. The original RhoTermPredict repo is offered as a script and not a package - our fork adds that functionality. This package is a dependency of our upcoming work which depends on ViennaRNA and TranstermHP, so we need to add all other dependencies to enable that work to be installed in one line.
---- …
=> Add RhoTermPredict

recipes/commec/meta.yaml
Add the build recipe for the Common Mechanism, commec. DNA screening python toolset.
---- …
=> Add build recipe for commec

recipes/transannot/build.sh, recipes/transannot/meta.yaml
=> use semantic nomenclature for the TransAnnot versions

recipes/bifrost/build.sh, recipes/bifrost/meta.yaml
=> bifrost: add aarch64/arm64 build

recipes/ratatosk/build.sh, recipes/ratatosk/meta.yaml
=> ratatosk: add aarch64 build

recipes/nanoplot/meta.yaml
=> Update NanoPlot to 1.43.0

recipes/comet-ms/meta.yaml
=> Update Comet-ms to version 2024.01.01

recipes/poppunk/meta.yaml
Update poppunk, also add arm support (not 100% sure if necessary but will work this out)
---- …
=> Bump poppunk to v2.7.0

recipes/pdbx/build.sh, recipes/pdbx/meta.yaml
=> Adding pdbx

recipes/cryptkeeper/meta.yaml
CryptKeeper is a negative design tool that supports molecular biologists in identifying and responding to unwanted, cryptic gene expression behind an upcoming manuscript in our lab. Cryptkeeper relies on ViennaRNA (upstream of OSTIR) and TransTermHP, so we need to put it up on conda to enable one command installation.
----
* PRs require reviews prior to being merged. Once your PR is …
=> Add Cryptkeeper

recipes/sdust/build.sh, recipes/sdust/meta.yaml, recipes/sdust/run_test.sh
recipe to install tool sdust
---- …
=> feat: recipe to install tool sdust

recipes/ropebwt3/build.sh, recipes/ropebwt3/meta.yaml
=> Add recipe for ropebwt3 v3.3

recipes/sequali/meta.yaml
setuptools-scm needs to be at `host` in order to be used for the package.
----
Conda is …
=> Sequali: Fix versioning

recipes/matchtigs/meta.yaml
=> matchtigs: add aarch64/arm64 builds

recipes/acms/meta.yaml
=> acms: add linux-aarch64 support

recipes/hairsplitter/build.sh, recipes/hairsplitter/hairsplitter-aarch64.patch, recipes/hairsplitter/meta.yaml, recipes/minigraph/build.sh, recipes/minigraph/meta.yaml, recipes/minigraph/minigraph-aarch64.patch
=> hairsplitter & minigraph: add aarch64/arm64 builds

recipes/rapidnj/build.sh, recipes/rapidnj/meta.yaml, recipes/rapidnj/rapidnj-aarch64.patch
=> rapidnj: add aarch64/arm64 builds

recipes/phyloaln/build.sh, recipes/phyloaln/meta.yaml
Add phyloaln -- a convenient reference-based multiple sequence alignment tool to align sequences and high-throughput reads for phylogeny and evolution in the omic era
---- …
=> Add phyloaln

recipes/pdbx/build.sh, recipes/pdbx/meta.yaml
Updating builds for ARM platforms.
---- …
=> Pdbx v1.0.0 for ARM platforms

recipes/hyphy/meta.yaml
=> Build hyphy for osx-arm64

recipes/cellbender/meta.yaml
=> Update cellbender to 0.3.2

recipes/dna-nn/meta.yaml
=> dna-nn: add linux-aarch64 build

recipes/libsbml/build.sh, recipes/libsbml/meta.yaml
=> libsbml: add aarch64/arm64 builds

recipes/gsearch/meta.yaml
Update gsearch to v0.2.1, new functions added, including ANI/AAI calculation. 
---- …
=> Update gsearch v0.2.1

recipes/vitap/meta.yaml
Bugfix for VITAP. This is the version 1.5. 
Description: Viral Taxonomic Assignment Pipeline (VITAP) is a cutting-edge tool designed to address the growing need for accurate and comprehensive classification of DNA and RNA viral sequences. By integrating alignment-based techniques with graph theory, VITAP achieves high precision in classifying viral sequences, including those as short as 1000 base pairs, down to the genus level.
=> Update VITAP from v.1.1 to v.1.5

recipes/sainsc/meta.yaml
add a recipe for sainsc to bioconda
---- …
=> Add sainsc recipe

recipes/discosnp/meta.yaml, recipes/dsk/build.sh, recipes/dsk/meta.yaml, recipes/short-read-connector/meta.yaml
=> discosnp & dsk & short-read-connector: add linux-aarch64 builds

recipes/unicycler/meta.yaml
=> Build Unicycler on python 3.8

recipes/sainsc/meta.yaml
=> sainsc: add linux-aarch64 build

recipes/sainsc/meta.yaml
Adjust recipe to build for multiple versions of python
---- …
=> Update sainsc: Multiple python versions

recipes/sainsc/meta.yaml
Add support for building on osx
---- …
=> Update sainsc: add osx support

recipes/pasty/meta.yaml
@aliciaaevans this a rebuild related to a failure on the "upload from master" action
Failure is here: https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=66752&view=logs&j=9d4cda30-b5f2-5e95-e642-70fa3f43a691&t=3b24cbaa-a0db-5c6a-6d4a-e4148972f28a
I had another instance where "upload from master" wasn't executed after a merge of a PR (https://github.com/bioconda/bioconda-recipes/pull/50059)
---- …
=> rebuild pasty

recipes/apu-label-propagation/build.sh, recipes/apu-label-propagation/meta.yaml
Add APU labeling propagation from https://github.com/AndMastro/NIAPU
=> Add Bioconda recipe

recipes/idemuxcpp/build.sh, recipes/idemuxcpp/meta.yaml
=> idemuxcpp: add aarch64/arm64 builds

recipes/htsbox/build.sh, recipes/htsbox/meta.yaml
=> htsbox: add aarch64/arm64 build

recipes/beacon2-import/meta.yaml
=> Update beacon-import tool

build-fail-blacklist, recipes/ucsc-subchar/build.sh, recipes/ucsc-subchar/include.patch, recipes/ucsc-subchar/meta.yaml
=> ucsc-subchar: add linux-aarch64 build

recipes/prot-scriber/build.sh, recipes/prot-scriber/meta.yaml
=> prot-scriber: add aarch64 build

recipes/apu-label-propagation/build.sh, recipes/apu-label-propagation/meta.yaml
=> apu-label-propagation: add aarch64/arm64 builds

recipes/msweep/meta.yaml
=> msweep: add linux-aarch64 build

recipes/varfish-server-worker/build.sh, recipes/varfish-server-worker/meta.yaml
=> varfish-server-worker: add linux-aarch64 build

recipes/nedbit-features-calculator/meta.yaml
=> nedbit-features-calculator: add aarch64/arm64 builds

build-fail-blacklist, recipes/ucsc-qactowig/build.sh, recipes/ucsc-qactowig/include.patch, recipes/ucsc-qactowig/meta.yaml
=> ucsc-qactowig: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-pslhisto/build.sh, recipes/ucsc-pslhisto/include.patch, recipes/ucsc-pslhisto/meta.yaml
=> ucsc-pslhisto: add linux-aarch64 build

build-fail-blacklist, recipes/ucsc-pslrecalcmatch/build.sh, recipes/ucsc-pslrecalcmatch/include.patch, recipes/ucsc-pslrecalcmatch/meta.yaml
=> ucsc-pslrecalcmatch: add linux-aarch64 build

recipes/bustools/meta.yaml
=> Build bustools for aarch/arm

recipes/nanocount/meta.yaml
=> Add nanocount

recipes/pipits/meta.yaml
=> Update PIPITS to 3.1

recipes/alen/build.sh, recipes/alen/meta.yaml
This PR adds the [`alen`](https://github.com/jakobnissen/alen) multiple sequence alignment viewer for the terminal.
=> Add `alen`

recipes/last/build.sh, recipes/last/meta.yaml
=> Update last to 1565

recipes/graphbin/meta.yaml
This PR updates [graphbin](https://github.com/metagentools/GraphBin) to version 1.7.4
---- …
=> Update graphbin to v1.7.4

recipes/polap/LICENSE, recipes/polap/build.sh, recipes/polap/meta.yaml
=> Add a recipe for polap v0.2.4

recipes/chromsize/build.sh, recipes/chromsize/meta.yaml
add chromsize bioconda recipe.
---- …
=> add chromsize v.0.0.2 recipe

recipes/plasnet/meta.yaml
To make it build with all required python versions
---- …
=> noarch: generic to python

recipes/segalign-full/meta.yaml, recipes/segalign-galaxy/meta.yaml
changing source repo for segalign
---- …
=> update to latest version of segalign

recipes/r-mspbwt/meta.yaml
=> r-mspbwt: add aarch64 build

recipes/python-bioext/meta.yaml
=> python-bioext: add aarch64/arm64 builds

recipes/xclone/meta.yaml
=> Add recipe for xclone v0.3.8

recipes/sawfish/build.sh, recipes/sawfish/meta.yaml
This PR adds a new recipe for 'sawfish' a new long-read structural variant caller.
---- …
=> Add new recipe for sawfish

recipes/r-quilt/meta.yaml
=> r-quilt: add aarch64 build

recipes/dnaio/meta.yaml
=> Add osx-arm64 build for dnaio

build-fail-blacklist, recipes/ucsc-bigwigmerge/build.sh, recipes/ucsc-bigwigmerge/include.patch, recipes/ucsc-bigwigmerge/meta.yaml
=> ucsc-bigwigmerge: add linux-aarch64 build

recipes/muscle/meta.yaml
=> muscle - enable osx-arm64 builds in meta.yaml

recipes/cutadapt/meta.yaml
=> cutadapt - Update meta.yaml to add build support for osx-arm64

recipes/last/meta.yaml
=> Update last to 1571

recipes/gmwi2/meta.yaml
=> Update GMWI2 package

recipes/bbmix/meta.yaml
=> Add recipe for bbmix v0.2.2

recipes/fast-edit-distance/meta.yaml
=> fast-edit-distance: add aarch64/arm64 build

recipes/mquad/meta.yaml
=> Add recipe for mquad v0.1.8b

recipes/strdust/build.sh, recipes/strdust/meta.yaml
=> update strdust to 0.8.2

recipes/bbmap/build.sh, recipes/bbmap/meta.yaml
=> Update bbmap to 39.08

recipes/multiqc/meta.yaml
=> Update MultiQC to 1.24.1 Patch Release

recipes/prymer/meta.yaml
=> Add new recipe prymer

recipes/biobox_add_taxid/meta.yaml
=> Add biobox_add_taxid recipe

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.24

recipes/abnumber/meta.yaml
=> Update abnumber to 0.3.8

recipes/bwa-aln-interactive/build.sh, recipes/bwa-aln-interactive/meta.yaml
This adds a fork of the `bwa` package called `bwa-aln-interactive`.  It contains additional functionality for the `bwa aln` command:
1. Ability to send queries and receive alignments on standard input/output respectively
2. outputs SAM directly, optionally with the MD in the XA tag
We have used this version heavily over the years for primer design, where we want to use `bwa aln` to find off-target mappings for primers and primer pairs quickly, but want to so by communicating with a single `bwa aln` process interactively.  See [`prymer`](https://github.com/fulcrumgenomics/prymer) and [`fgprimer`](https://github.com/fulcrumgenomics/fgprimer) for Python and Scala wrappers that use this `bwa aln` heavily.  
Many of our users have asked us if we can package this via bioconda, and here we are. …
=> Add new recipe for bwa-aln-interactive

recipes/spatialleiden/meta.yaml
=> Add spatialleiden recipe

recipes/jvarkit/meta.yaml
I'm the author of this jvarkit, bcftools and samtools are the de-facto companions of this tool.
=> Update : adding samtools and bcftools to jvarkit/meta.yaml

recipes/jclusterfunk/build.sh, recipes/jclusterfunk/meta.yaml
Add recipe for https://github.com/snake-flu/jclusterfunk - this is needed for squirrel (being added here: https://github.com/bioconda/bioconda-recipes/pull/50297)
---- …
=> Add recipe for jclusterfunk

recipes/squirrel/meta.yaml
Add recipe for `squirrel` - a tool used in analysing MPXV sequences (see https://github.com/aineniamh/squirrel)
---- …
=> Add recipe for squirrel

recipes/k8/build.sh, recipes/k8/meta.yaml
Needed to build minimap2 #49945.
---- …
=> Build k8 on osx-arm64

recipes/kmertools/build.sh, recipes/kmertools/meta.yaml
This PR updates `kmertools` to v0.1.2.
---- …
=> Update kmertools to v0.1.2

recipes/strangepg/build.sh, recipes/strangepg/meta.yaml
Updates to latest version and fixes missing spec resulting in runtime dependencies
not being pulled.
----
Conda is able …
=> update strangepg and fix runtime dependency spec

recipes/kmertools/meta.yaml
=> Update kmertools recipe

recipes/maegatk/meta.yaml
=> maegatk: update build

recipes/ucsc-addcols/build.sh, recipes/ucsc-addcols/meta.yaml
The changes in this PR are generated by a new version of the scripts at https://github.com/bioconda/bioconda-recipes/tree/master/scripts/ucsc that will be pushed in a following [PR](https://github.com/bioconda/bioconda-recipes/pull/50325).
This PR and few more will be used to test the changes in the scripts before opening the PR for the scripts themselves.
---- …
=> Update ucsc-addCols to v469

recipes/spoa/build.sh, recipes/spoa/meta.yaml
=> spoa: add arm64 build

recipes/meme/build.sh, recipes/meme/meta.yaml
=> Update meme to 5.5.7

recipes/wisecondorx/meta.yaml
=> bump WisecondorX to v1.2.8

recipes/kmertools/build.sh, recipes/kmertools/meta.yaml
Update kmertools to v0.1.3
---- …
=> Update kmertools to v0.1.3

recipes/scoring-matrices/meta.yaml
=> scoring-matrices: add arm64 build

recipes/wisecondorx/meta.yaml
=> Bump wisecondorx to v1.2.9

recipes/gw/build.sh, recipes/gw/fix-context.patch, recipes/gw/fix-linker-issues.patch, recipes/gw/meta.yaml
The patch fixes a bug in opengl context creation api, and adds additional libs
=> GW v1.0.3 patch

recipes/cnmf/meta.yaml
=> Add recipe for cnmf v1.6.0

recipes/kegalign-full/meta.yaml
Adding kegalign-full, where development for segalign-full and segalign-galaxy will continue
---- …
=> Adding kegalign-full, where development for segalign-full and segalign-galaxy will continue

recipes/evidencemodeler/meta.yaml
Hello,
I have a PR in progress to create the wrapper for EVM (https://github.com/galaxyproject/tools-iuc/pull/6163). I have an error indicating that DB_file is missing. I've added it to the conda package. 
Thank you, have a nice day.
=> add perl-db_file to the EVidenceModeler package

recipes/fastahack/build.sh, recipes/fastahack/meta.yaml
=> fastahack: add linux-aarch64 build

recipes/dbcanlight/meta.yaml
Update dbcanlight to v1.1.0 since BiocondaBot was not able to bump it automatically. Might due to we've change the GitHub repo url.
---- …
=> Update dbcanlight to 1.1.0

recipes/lexicmap/build.sh, recipes/lexicmap/meta.yaml
**Add LexicMap,  a tool for efficient sequence alignment against millions of prokaryotic genomes.**
Preprint:
> Wei Shen and Zamin Iqbal.
> (2024) LexicMap: efficient sequence alignment against millions of prokaryotic genomes.
> bioRxiv. [https://doi.org/10.1101/2024.08.30.610459](https://doi.org/10.1101/2024.08.30.610459)
---- …
=> Add LexicMap

recipes/blast2galaxy/meta.yaml
=> Update blast2galaxy to 1.0.0

recipes/last/meta.yaml
=> Update last to 1584

recipes/verkko/build.sh, recipes/verkko/meta.yaml, recipes/verkko/osx_availability.patch, recipes/verkko/run_test.sh
Updating to verkko v2.2 release
=> update to verkko v2.2

recipes/eukulele/meta.yaml
Updating EUKulele package to most recent version
- fix automatic download of databases
- add feature to create fasta of eukaryotic sequences
---- …
=> Update EUKulele to v2.0.9

recipes/poplddecay/build.sh, recipes/poplddecay/meta.yaml
=> Add recipe for PopLDdecay  v3.43

recipes/poplddecay/meta.yaml
=> Update poplddecay recipe

recipes/minute/meta.yaml
=> Update minute to 0.8.0

recipes/binette/meta.yaml
This PR updates Binette recipe to version 1.0.2 !
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Update Binette to 1.0.2

recipes/starcatpy/meta.yaml
=> Add recipe for starcatpy v1.0.8

recipes/gw/meta.yaml
This adds wayland to the GW build
=> Add wayland to GW build

recipes/piawka/build.sh, recipes/piawka/meta.yaml
Add `piawka` package. The build works on my machine... It relies on `bioconda` and `conda-forge` channels afaik.
---- …
=> Add piawka

recipes/strangepg/meta.yaml, recipes/strangepg/run_test.sh
Update to latest and fix requirements.
---- …
=> update strangepg and its requirements

recipes/binchicken/meta.yaml
=> Update binchicken recipe

recipes/eigensoft/build.sh, recipes/eigensoft/meta.yaml
=> eigensoft: add aarch64/arm64 builds

recipes/graphmap/build.sh, recipes/graphmap/graphmap2-aarch64.patch, recipes/graphmap/meta.yaml
=> graphmap: add linux-aarch64 build

recipes/gempipe/meta.yaml
=> Update gempipe v1.35.0 0

recipes/r-stitch/build.sh, recipes/r-stitch/meta.yaml
update r-stitch version and make it auto-bumping for future tagged release.
---- …
=> Update r-stitch to 1.7.1

recipes/nanosim/meta.yaml
Pin lower version for minimap2 to prevent installing very old versions
---- …
=> Update nanosim: bump build

recipes/irescue/meta.yaml
=> Update irescue to 1.1.0

recipes/lib-pod5/LICENSE.md, recipes/lib-pod5/meta.yaml
=> Add recipe for lib-pod5 v0.3.15

recipes/fastlin/meta.yaml
I modified the meta.yaml file to point to the latest version of fastlin
---- …
=> Update to fastlin 0.3.0

recipes/freebayes/build.sh, recipes/freebayes/meta.yaml
=> Update freebayes recipe

recipes/sra-tools/build.sh, recipes/sra-tools/meta.yaml
=> Update sra-tools recipe

recipes/wfa2-lib/build.sh, recipes/wfa2-lib/meta.yaml
=> Update wfa2-lib recipe

recipes/pod5/LICENSE.md, recipes/pod5/meta.yaml
=> Add recipe for pod5 v0.3.15

recipes/moods/build.sh, recipes/moods/meta.yaml
=> moods: add aarch64/arm64 build

recipes/quota_anchor/build.sh, recipes/quota_anchor/meta.yaml
Merge to bulk to build on GHA.
Original PR: https://github.com/bioconda/bioconda-recipes/pull/50528
=> Bulk: Add quota_anchor recipe

recipes/mcl/build.sh, recipes/mcl/meta.yaml
=> mcl: add aarch64 build

recipes/rbpbench/meta.yaml
Update rbpbench recipe to v1.0 
---- …
=> update recipe to v1.0

recipes/schpl/meta.yaml
* Original recipe generated using `grayskull pypi schpl`
* Only edit was to update `newick` to [`python-newick`](https://anaconda.org/bioconda/python-newick)
* Adding scHPL to bioconda because it is bio-related and because python-newick is on bioconda
https://github.com/lcmmichielsen/scHPL
https://pypi.org/project/scHPL/
---- …
=> Add recipe for scHPL

recipes/mgems/build.sh, recipes/mgems/meta.yaml
=> mGEMS: add aarch64/arm64 builds

recipes/f5c/build.sh, recipes/f5c/meta.yaml
=> f5c: add aarch64/arm64 builds

recipes/fastlin/meta.yaml
=> fastlin: add aarch64/arm64 builds

recipes/sam2pairwise/build.sh, recipes/sam2pairwise/meta.yaml, recipes/sam2pairwise/patch.txt
New dependency required for NanoSim
---- …
=> Add sam2pairwise

recipes/nanosim/meta.yaml
- adding missing (and newly added to bioconda) dependency sam2pairwise
---- …
=> Update nanosim build

recipes/auspice/meta.yaml
See changelog on [Auspice release page](https://github.com/nextstrain/auspice/releases/tag/v2.58.0).
---- …
=> Update Auspice version

recipes/anglerfish/meta.yaml, recipes/anglerfish/requirements.txt
After changing the URL on github this one didn't receive an autobump, I hope that this fixes it. Even so, the dependencies needed an update anyway 😀 
---- …
=> Update anglerfish to 0.7.0

recipes/usalign/build.sh, recipes/usalign/meta.yaml
=> Adding US-align v2024.07.30

recipes/srnamapper/meta.yaml
This is an update to srnamapper, which corrects a bug.
---- …
=> Update srnamapper to 1.0.9

recipes/genomad/meta.yaml
This PR changes geNomad's `max_pin` from `"x"` to `None`.
---- …
=> Change geNomad's `run_exports` `max_pin`

recipes/bioconvert/meta.yaml
This PR adds [`goalign`](https://github.com/evolbioinfo/gotree) and [`gotree`](https://github.com/evolbioinfo/gotree) as dependencies for [`bioconvert`](https://github.com/bioconvert/bioconvert)
---- …
=> Add `goalign` and `gotree` as dependencies for `bioconvert`

recipes/hhsuite/build.sh, recipes/hhsuite/meta.yaml, recipes/hhsuite/reformat_pl.patch
This PR updates the installation process to include the `reformat.pl` script, which is provided in a separate directory within the source code. As a result, the script will be added to the user's `PATH`.
----
* Please post …
=> Include `reformat.pl` in the `hhsuite` recipe

recipes/dockq/meta.yaml
I am adding DockQ v2.1.3.
DockQ is a single continuous quality measure for Protein, Nucleic Acids and Small Molecule Docking Models.
---- …
=> Adding DockQ v2.1.3

recipes/afpdb/meta.yaml
Add pypi package Afpdb.
Afpdb is a NumPy-based protein structure manipulation package that provides over 180 methods, enabling users to write concise and high-performance code for protein AI design tasks. The paper for the Afpdb package is currently under review.
Afpdb package comes with a rich tutorial and examples can be run interactively with Google Colab.
=> Add afpdb package

recipes/srnamapper/meta.yaml
=> Update srnaMapper: Put bwa to submodule

recipes/hlafreq/meta.yaml, recipes/ms2pip/meta.yaml, recipes/quota_anchor/build.sh, recipes/quota_anchor/meta.yaml
=> Merge recipes that were uploaded on Bulk to master

recipes/rbpbench/meta.yaml
=> Why has this not been pushed?

recipes/schpl/meta.yaml
Follow-up to https://github.com/bioconda/bioconda-recipes/pull/50613. Adding scHPL developer @lcmmichielsen as recipe maintainer as requested in https://github.com/bioconda/bioconda-recipes/pull/50613#issuecomment-2343638088
---- …
=> [ci skip] Add lcmmichielsen as scHPL maintainer

recipes/pymsaviz/meta.yaml, recipes/pymsaviz/run_test.sh
Update pymsaviz to v0.5.0. Fix autobump PR #50712.
---- …
=> Update pymsaviz to 0.5.0

recipes/srnamapper/build.sh, recipes/srnamapper/meta.yaml
=> Update srnamapper recipe

recipes/vcf-validator/build.sh, recipes/vcf-validator/meta.yaml
Update of vcf-validator to v0.9.7
---- …
=> Update vcf-validator to 0.9.7

recipes/hackgap/meta.yaml
=> Add hackgap recipe

recipes/cnv_facets/build.sh, recipes/cnv_facets/meta.yaml, recipes/r-facets/meta.yaml, recipes/snp-pileup/meta.yaml
=> cnv_facets & snp-pileup: add linux-aarch64 build

recipes/icfree-ml/meta.yaml
=> build(icfree-ml): update

recipes/biophi/meta.yaml
Fix incompatibility of `biophi` package with new `pip` version
=> Fix biophi build

recipes/transanno/build.sh, recipes/transanno/meta.yaml
Despite the similar name to transannot, this is a totally different package. It allows easy and fast creation and application of chain files for translation (liftover) of coordinates between different reference genome coordinates.
---- …
=> Add recipe for transanno

recipes/hylight/build.sh, recipes/hylight/meta.yaml
=> add hylight

recipes/gbintk/meta.yaml
This PR adds [`gbintk`](https://github.com/metagentools/gbintk), GraphBin-Tk that combines assembly graph-based metagenomic bin-refinement and binning techniques [GraphBin](https://github.com/metagentools/GraphBin), [GraphBin2](https://github.com/metagentools/GraphBin2) and [MetaCoAG](https://github.com/metagentools/MetaCoAG) along with support functionality to visualise and evaluate results, into one comprehensive toolkit.
---- …
=> Add gbintk v0.1.0

recipes/vcflib/0006-wfa2-lib.patch, recipes/vcflib/build.sh, recipes/vcflib/meta.yaml, recipes/vcflib/pkg-config.patch
=> update vcflib recipe

recipes/tracy/build.sh, recipes/tracy/meta.yaml
=> Update tracy to 0.7.8

recipes/genomepy/meta.yaml
Applies: https://github.com/vanheeringen-lab/genomepy/pull/250
=> restrict mysql dependency

recipes/repeatmasker/build.sh, recipes/repeatmasker/meta.yaml, recipes/repeatmasker/post-link.sh
=> Update RepeatMasker recipe

recipes/ntjoin/meta.yaml
=> Update ntjoin build

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.25

recipes/jalview/meta.yaml
Update Jalview to 2.11.4.0
---- …
=> Update Jalview to 2.11.4.0

recipes/tr-trimmer/build.sh, recipes/tr-trimmer/meta.yaml
This PR adds `tr-trimmer`, a tool for identification and trimming of terminal repeats in sequences within FASTA files.
---- …
=> Add `tr-trimmer`

recipes/tiberius/build.sh, recipes/tiberius/meta.yaml
Hi, I'm oppening this PR to create the conda package for Tiberius. 
Thank you! Have a good day!
=> add tiberius

recipes/pydamage/meta.yaml
=> dep: add numba and update python

recipes/superdsm/meta.yaml
Update [superdsm](https://bioconda.github.io/recipes/superdsm/README.html): 0.3.0 → 0.4.0
Automatic update failed: https://github.com/bioconda/bioconda-recipes/pull/50815
---- …
=> Update superdsm to 0.4.0

recipes/kraken2/build.sh, recipes/kraken2/meta.yaml
This adds the python `k2` script that is distributed with kraken2 to the `bin` directory.
---- …
=> update kraken2 to add k2 script to PATH

recipes/scarches/meta.yaml
* Original recipe generated using `grayskull pypi scarches`
* Added `run_exports`
* Follow-up to https://github.com/bioconda/bioconda-recipes/pull/50613
https://github.com/theislab/scarches
https://pypi.org/project/scArches/
---- …
=> Add recipe for scArches

recipes/emu/meta.yaml
=> Update Emu to v3.5.0

recipes/fiji/meta.yaml
=> update to fiji 20240614

recipes/prymer/meta.yaml
Closes: https://github.com/fulcrumgenomics/prymer/issues/5
The newly added `prymer` requires that `bwa-aln-interactive` also be installed.
https://bioconda.github.io/recipes/prymer/README.html
https://bioconda.github.io/recipes/bwa-aln-interactive/README.html
---- …
=> Update prymer to depend on bwa-aln-interactive

recipes/blast-legacy/2.2.26/fix-osx-build.patch, recipes/blast-legacy/2.2.26/meta.yaml
Expanding the patch for blast-legacy to allow it to compile under macOS Sequoia
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Also, the bot …
=> Update patch of blast-legacy for macOS Sequoia

recipes/busco_phylogenomics/meta.yaml
This PR adds [BUSCO_phylogenomics](https://github.com/jamiemcg/BUSCO_phylogenomics), a Python pipeline for constructing species phylogenies from BUSCO proteins, with support for supermatrix and supertree methods.
----
* Please …
=> Add BUSCO_phylogenomics
