bioconda/bioconda-recipes

recipes/vclean/meta.yaml
* include db/*.txt file correctly.
=> update to v0.1.5

recipes/fastlin/meta.yaml
update fastlin to 0.4.1 
My previous Pull request failed because of wrong build number in meta.yaml file.
----
Conda is …
=> update fastlin to 0.4.1 [bis]

recipes/hifiasm_meta/meta.yaml
Update hifiasm_meta from v0.3.1 to v0.3.2.
---- …
=> Update hifiasm-meta to v0.3.2

recipes/gsearch/build.sh, recipes/gsearch/meta.yaml
New version of gsearch, add sequence search via BItsliced Genomic Signature Index (BIGSIG)
---- …
=> Update to gsearch v0.2.2

recipes/tooldistillator/meta.yaml
Update to new version
[tooldistillator](https://bioconda.github.io/recipes/tooldistillator/README.html?highlight=tooldistillator#package-package%20'tooldistillator'): 0.9 → 0.9.1
Thanks :smiley: 
---- …
=> Update ToolDistillator from 0.9 to 0.9.1

recipes/earlgrey/meta.yaml
=> Update EarlGrey meta.yaml - Add Samtools

recipes/ppanggolin/meta.yaml
=> ppanggolin: add aarch64 build

recipes/leviosam2/build.sh, recipes/leviosam2/meta.yaml
This is an attempt to fix a zlib-not-found error in https://github.com/bioconda/bioconda-recipes/pull/50870
----
Conda …
=> Update leviosam2 (sub-PR: 0.5.0 build.sh fix)

recipes/derna/build.sh, recipes/derna/meta.yaml
=> derna: add aarch64/arm64 builds

recipes/msisensor-rna/meta.yaml
=> Add recipe for msisensor-rna v0.1.6a

recipes/bbmap/meta.yaml
=> Update bbmap to 39.09

recipes/macs3/meta.yaml
=> Update macs3 to v3.0.2

recipes/squigulator/build.sh, recipes/squigulator/meta.yaml
=> squigulator: add aarch64/arm64 builds

recipes/impg/build.sh, recipes/impg/meta.yaml
=> impg: add aarch64/arm64 builds

recipes/macs3/meta.yaml
=> macs3: add aarch64/arm64 builds

recipes/strangepg/meta.yaml
=> Update strangepg to 0.8.5

recipes/hifiasm_meta/build.sh, recipes/hifiasm_meta/hifiasm_meta-aarch64.patch, recipes/hifiasm_meta/meta.yaml
=> hifiasm_meta: add aarch64/arm64 builds

recipes/r-grain/meta.yaml
=> r-grain: add aarch64/arm64 builds

recipes/kallisto/build.sh, recipes/kallisto/meta.yaml
=> Update kallisto to 0.51.1

recipes/gfastats/meta.yaml
=> gfastats: add aarch64/arm64 builds

recipes/yahs/meta.yaml
=> yahs: add aarch64/arm64 builds

recipes/strangepg/build.sh, recipes/strangepg/meta.yaml
=> strangepg: add linux-aarch64 build

recipes/phyloacc/build.sh, recipes/phyloacc/meta.yaml
=> phyloacc: add aarch64/arm64 builds

recipes/earlgrey/build.sh, recipes/earlgrey/meta.yaml
Modify to add new library construction script to environment bin directory.
---- …
=> Update EarlGrey build.sh

recipes/smudgeplot/meta.yaml
=> smudgeplot: add aarch64/arm64 builds

recipes/abnumber/meta.yaml
=> Bump abnumber package

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.26

recipes/abnumber/meta.yaml
=> Bump abnumber to 0.4.1

recipes/consensify/build.sh, recipes/consensify/meta.yaml
=> consensify: add aarch64/arm64 builds

recipes/searchgui/meta.yaml, recipes/searchgui/searchgui.py
=> Update searchgui to 4.3.11

recipes/peptide-shaker/meta.yaml, recipes/peptide-shaker/peptide-shaker.py
=> Update peptide-shaker to 3.0.11

.circleci/config.yml
The large VM consumes our credits too fast
---- …
=> Use medium VM for Linux ARM64

recipes/hmftools-pave/meta.yaml
Update hmftools-pave recipe to 1.7_beta
---- …
=> Update hmftools-pave to 1.7_beta

recipes/hmftools-virus-interpreter/meta.yaml
Update hmftools-virus-interpreter recipe to 3.7_beta
---- …
=> Update hmftools-virus-interpreter to 3.7_beta

recipes/hmftools-cobalt/meta.yaml
Update hmftools-cobalt recipe to 2.0_beta
---- …
=> Update hmftools-cobalt to 2.0_beta

recipes/hmftools-sage/meta.yaml
Update hmftools-sage recipe to 4.0_beta
---- …
=> Update hmftools-sage to 4.0_beta

recipes/mashmap/build.sh, recipes/mashmap/meta.yaml
=> mashmap: add aarch64 build

recipes/clusty/meta.yaml
=> Update clusty to 1.1.1.

recipes/hmftools-orange/meta.yaml
Update hmftools-orange recipe to 3.7.1_beta
---- …
=> Update hmftools-orange to 3.7.1_beta

recipes/get_mnv/get_mnv-aarch64.patch, recipes/get_mnv/meta.yaml
=> get_mnv: add aarch64/arm64 builds

recipes/hmftools-sage/meta.yaml
=> Update hmftools-sage to 4.0_beta.1

recipes/earlgrey/meta.yaml
Add 2 R packages and heliano to prepare for future release.
---- …
=> Update Earl Grey meta.yaml

recipes/bbmap/meta.yaml
=> Update bbmap to 39.10

recipes/squirrel/meta.yaml
The current squirrel recipe has a pin to mako 1.2 which has a security issue. This pin was inherited from upstream and has now been removed (https://github.com/aineniamh/squirrel/pull/47) so this updates the bioconda recipe to align with the upstream change.
---- …
=> Update squirrel: remove mako pin

recipes/gfastats/meta.yaml
This PR updates the existing recipe of gfastats by replacing the source to tarball 
---- …
=> Updating gfastats tool recipe with tarball source

recipes/cenote-taker3/meta.yaml
Update to Cenote-Taker 3.3.2
---- …
=> Update to Cenote-Taker 3 v3.3.2

recipes/openms-meta/meta.yaml
Follow-up of https://github.com/OpenMS/OpenMS/issues/7614
---- …
=> Bump openms build to expose eigen in libopenms

recipes/thermorawfileparser/meta.yaml
=> thermorawfileparser 1.4.5

recipes/longcallr_nn/meta.yaml
=> Add recipe for longcallr_nn

recipes/snakemake/meta.yaml
Since this was replaced by a graphlib
---- …
=> Update snakemake: remove toposort as dependency

recipes/pneumo-typer/meta.yaml
=> Xiangyang1984 patch 20

recipes/hatchet/meta.yaml
=> Update HATCHeT to 2.1.0

recipes/biobb_cmip/meta.yaml
=> [biobb_cmip] update 5.0.0

recipes/tower-cli/meta.yaml, recipes/tower-cli/tw.sh
=> Update tower-cli version to v0.10.3

recipes/ezcharts/meta.yaml
=> Update ezcharts to v0.11.2

recipes/sainsc/meta.yaml
With the version bump the dependencies have changed and need to be adjusted
---- …
=> Sainsc: adjust dependencies

recipes/fmsi/0002-version.patch, recipes/fmsi/meta.yaml
FMSI is now updated to v0.3.0
Additionally I removed the patch for FMSI version as FMSI's fallback version now correctly tracks the version.
Closes #51568.
---- …
=> Update FMSI to v0.3.0

recipes/auspice/meta.yaml
- Update auspice to new version
- Update list of supported Node.js versions
---- …
=> Update auspice to 2.59.0

recipes/biobb_flexdyn/meta.yaml
=> [biobb_flexdyn] update 5.0.0

recipes/last/meta.yaml
=> Update last to 1595

recipes/tantan/meta.yaml
=> Update tantan to 51

recipes/auspice/meta.yaml
Update auspice to latest version
---- …
=> Update auspice to 2.59.1

recipes/gmap/meta.yaml
=> Update gmap to 2024-10-20

recipes/spaln/meta.yaml
=> Update spaln to 3.0.6b

recipes/ucsc-fatotwobit/build.sh, recipes/ucsc-fatotwobit/meta.yaml
=> Update ucsc-fatotwobit to 472

recipes/ucsc-twobitinfo/build.sh, recipes/ucsc-twobitinfo/include.macos.patch, recipes/ucsc-twobitinfo/meta.yaml
=> Update ucsc-twobitinfo to 472

recipes/ucsc-blat/build.sh, recipes/ucsc-blat/include.macos.patch, recipes/ucsc-blat/meta.yaml
=> Update ucsc-blat to 472

recipes/haystac/meta.yaml
update the biopython dependency for haystac and bump to version 0.4.12
---- …
=> update the biopython dependency for haystac 

recipes/genoflu/meta.yaml
=> genoflu version 1.04

recipes/d4binding/build.sh, recipes/d4binding/meta.yaml
=> d4binding: add aarch64/arm64 builds

recipes/prodigal-gv/build.sh, recipes/prodigal-gv/meta.yaml
=> prodigal-gv: add aarch64/arm64 builds

recipes/miniprot/build.sh, recipes/miniprot/meta.yaml
=> miniprot: add aarch64/arm64 builds

recipes/genoflu/meta.yaml
=> genoflu version 1.05

recipes/isoseq/meta.yaml
Update isoseq version 4.2.0
---- …
=> Update isoseq version 4.2.0

recipes/staden_io_lib/build.sh, recipes/staden_io_lib/meta.yaml
=> Update staden_io_lib recipe

recipes/ampd-up/build.sh, recipes/ampd-up/meta.yaml
De novo antimicrobial peptide sequence generation with recurrent neural networks
---- …
=> add ampd-up v1.0.0

recipes/libgff/meta.yaml
=> Rebuild libgff recipe

recipes/ucsc-wigtobigwig/meta.yaml
=> Rebuild ucsc-wigtobigwig recipe

recipes/ucsc-bedgraphtobigwig/meta.yaml
=> Rebuild ucsc-bedgraphtobigwig recipe

recipes/sainsc/meta.yaml
Due to CI transitions, sainsc didn't get properly uploaded. 
---- …
=> bump sainsc build number

recipes/pbmarkdup/meta.yaml
Update pbmarkdup to 1.1.0
---- …
=> Update pbmarkdup to 1.1.0

recipes/phenograph/meta.yaml
=> Add recipe for phenograph v1.5.7

recipes/fmsi/meta.yaml
=> Update FMSI to 0.3.1

recipes/sgdemux/meta.yaml
This PR adds linux-aarch64 and osx-arm64 for sgdemux
=> Add linux-aarch64 and osx-arm64 as targets for sgdemux

recipes/gcnvkernel/meta.yaml
=> update gcnvkernel to v 0.9

recipes/pbjasmine/build.sh, recipes/pbjasmine/meta.yaml
Update pbjasmine to 2.4.0
---- …
=> Update pbjasmine to 2.4.0

recipes/tirmite/meta.yaml
Removing unused entry point.
---- …
=> Update TIRmite recipe

recipes/taxonkit/meta.yaml
- [TaxonKit v0.18.0](https://github.com/shenwei356/taxonkit/releases/tag/v0.18.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/taxonkit/v0.18.0/total.svg)](https://github.com/shenwei356/taxonkit/releases/tag/v0.18.0)
- `taxonkit reformat`:
- Add a placeholder for rank "realm", "{r}", which is common in Virus taxonomy like [ictv](https://github.com/shenwei356/ictv-taxdump). [#102](https://github.com/shenwei356/taxonkit/issues/102)
- `taxonkit name2taxid`:
- Show warning for names with multiple taxids. [#103](https://github.com/shenwei356/taxonkit/issues/103)
----
* If this PR adds …
=> Update TaxonKit to v0.18.0

recipes/vg/meta.yaml
Update vg to version 1.60.0
---- …
=> Update vg to 1.60.0

recipes/pyrodigal/meta.yaml
This PR updates `pyrodigal` to v3.6.3; the build was changed to use `scikit-build-core` instead of `setuptools` so the requirements needed to be updated there.
Supersedes #51876
---- …
=> Bump `pyrodigal` to v3.6.3

recipes/jarvis3/build.sh, recipes/jarvis3/conda_build_config.yaml, recipes/jarvis3/meta.yaml
Attempted to fix the build.sh file - "JARVIS3.sh --install" executing incorrectly (19:39:07 BIOCONDA INFO (OUT) make[1]: gcc: No such file or directory) and added a necessary test to meta.yaml.
---- …
=> Update JARVIS3 recipe

recipes/mutyper/meta.yaml
=> mutyper: add aarch64/arm64 builds

recipes/ascat/build.sh, recipes/ascat/meta.yaml
=> Update ascat to v3.2.0

recipes/hmftools-redux/meta.yaml
=> Update hmftools-redux jar to fix multithreading synchronisation crash

recipes/eva-sub-cli/meta.yaml
Update dependencies. 
Supersedes #51928
---- …
=> Update eva-sub-cli to 0.4.1

recipes/gaftools/meta.yaml
adding `gaftools` to bioconda
---- …
=> Add gaftools

recipes/pyjess/meta.yaml
This PR adds a recipe for `pyjess`, a Python package providing bindings to the Jess template matching software.
---- …
=> Add recipe for `pyjess` Python package

recipes/bbmap/meta.yaml
=> Update bbmap to 39.11

recipes/phabox/meta.yaml
=> Update PhaBOX to 2.1.4

recipes/biobb_chemistry/meta.yaml
=> [biobb_chemistry] update 5.0.1

recipes/goldrush/meta.yaml
Pinned numpy due to installation of older versions
---- …
=> goldrush: pin numpy

recipes/r-remapenrich/bld.bat, recipes/r-remapenrich/build.sh, recipes/r-remapenrich/meta.yaml
This adds the ReMapEnrich package to the Bioconda repository.
https://github.com/remap-cisreg/ReMapEnrich
> About
> 
> ReMapEnrich is a R-software package to identify significantly enriched regions from ReMap catalogues or user defined catalogues. ReMapEnrich provide functions to import any in-house catalogue, automate and plot the enrichment analysis for genomic regions. 
----
* …
=> Add r-remapenrich to bioconda-recipes

recipes/melon/meta.yaml
=> update melon to 0.2.1 and fix summary

recipes/biobb_amber/meta.yaml
=> [biobb_amber] update 5.0.3 accept lists in different formats in properties

recipes/biobb_analysis/meta.yaml
=> [biobb_analysis] update 5.0.1

recipes/teloscope/build.sh, recipes/teloscope/meta.yaml
=> 24.11.12: Adding teloscope yml/sh

recipes/hmftools-orange/meta.yaml
=> Update hmftools-orange to 3.7.1_beta.3

recipes/beagle/meta.yaml
=> Update beagle to 5.4_29Oct24.c8e

recipes/biobb_dna/meta.yaml
=> [biobb_dna] update 5.0.1

recipes/sfold/build.sh, recipes/sfold/meta.yaml
The previous build did not fix the sfold shebang. Hopefully, this should fix it.
=> fix shebang in sfold

recipes/jaeger-bio/meta.yaml
Upgraded the bioconda recipe to support jaeger 1.1.30
---- …
=> version upgrade for jaeger-bio

recipes/mess/meta.yaml
PR to constrain snakemake-minimal version (between 8.0.0 and 8.24.1) and remove pyyaml
---- …
=> Update mess recipe

recipes/gretl/build.sh, recipes/gretl/meta.yaml
Gretl is a tool for computing statistics on variation graphs in GFA format.
---- …
=> Add new recipe for gretl v0.1.0

recipes/goldrush/meta.yaml
Pin minimap2 to avoid issues where it installed an older version of minimape2 that doesn't have required feature.
---- …
=> Update GoldRush: pin minimap2

recipes/biobb_io/meta.yaml
=> [biobb_io] update 5.0.0

recipes/biobb_model/meta.yaml
=> [biobb_model] update 5.0.0

recipes/sprinter/meta.yaml
=> Add SPRINTER recipe

recipes/psmc/build.sh, recipes/psmc/meta.yaml
=> psmc: add aarch64/arm64 builds

recipes/biobb_pdb_tools/meta.yaml
=> [biobb_pdb_tools] update 5.0.0

recipes/trinity/meta.yaml
Added coreutils to the requirements as it may be needed to use the sort command. Currently, running Trinity results in this being shown repeatedly:
```
BusyBox v1.32.1 (2021-04-13 11:15:36 UTC) multi-call binary.
Usage: sort [-nrugMcszbdfiokt] [-o FILE] [-k start[.offset][opts][,end[.offset][opts]] [-t CHAR] [FILE]...
Sort lines of text
-o FILE    Output to FILE
-c    Check whether input is sorted
-b    Ignore leading blanks
-f    Ignore case
-i    Ignore unprintable characters
-d    Dictionary order (blank or alphanumeric only)
-n    Sort numbers
-g    General numerical sort
-M    Sort month
-V    Sort version
-t CHAR    Field separator
-k N[,M] Sort by Nth field
-r    Reverse sort order
-s    Stable (don't sort ties alphabetically)
-u    Suppress duplicate lines
-z    Lines are …
```
=> Update Trinity requirements

recipes/hmftools-linx/meta.yaml, recipes/hmftools-neo/meta.yaml, recipes/hmftools-orange/meta.yaml, recipes/hmftools-pave/meta.yaml, recipes/hmftools-peach/meta.yaml
=> Enforce openjdk 21, part 3/4 (Linx, Neo, Orange, Pave, Peach)

recipes/hmftools-amber/meta.yaml, recipes/hmftools-bam-tools/meta.yaml, recipes/hmftools-chord/meta.yaml, recipes/hmftools-cobalt/meta.yaml
=> Enforce openjdk 21 for hmftools, part 1/4 (Amber, Bamtools, Chord, Cobalt)

recipes/pgrc/meta.yaml
bumped PgRC recipe revision to 2.0.2
---- …
=> updated pgrc revision to 2.0.2

recipes/polypolish/meta.yaml
Removes unnecessary Python dependency
---- …
=> Update polypolish: remove Python dependency

recipes/biobb_pytorch/meta.yaml
=> [biobb_pytorch] update 5.0.0

recipes/biobb_structure_utils/meta.yaml
=> [biobb_structure_utils] update 5.0.0

recipes/r-stitch/meta.yaml
=> Update r-stitch to v1.7.2

recipes/simug/meta.yaml
This bumps the version to 1.0.1 and adds the dev url to the recipe
---- …
=> Update version, add dev url

recipes/htsinfer/meta.yaml
Update htsinfer to 1.0.0-rc.1
---- …
=> Update htsinfer to 1.0.0-rc.1

recipes/biobb_mem/meta.yaml
=> [biobb_mem] update 5.0.2

recipes/bbmap/meta.yaml
=> Update bbmap to 39.13

recipes/halfdeep/meta.yaml
updating version of required package genodsp to 0.0.10
---- …
=> updating version of required package genodsp to 0.0.10

recipes/dysgu/meta.yaml
=> Update dysgu v1.70

recipes/hifiadapterfilt/build.sh, recipes/hifiadapterfilt/meta.yaml
This pull request adds a new recipe for the hifiadapterfilt package to the Bioconda channel.
----
<details>
<table>
<tr>
</tr>
<tr> …
=> Add recipe hifiadapterfilt

recipes/wipertools/meta.yaml
wipertools use the `split` command and require a minimum version (e.g., >8) that has subcommand (e.g., `--numeric-suffixes`) not included in the base `coreutils`
Modified the `meta.yaml` accordingly.
---- …
=> Update recipe wipertools

recipes/clipp/meta.yaml
=> Add recipe for Clipp v1.3.3

recipes/star/build.sh, recipes/star/meta.yaml, recipes/star/patches/0003-create-simd-dispatch.patch
=> Rebuild star recipe

recipes/cobs/cobs-aarch64.patch, recipes/cobs/meta.yaml
=> cobs: add aarch64/arm64 builds

recipes/agc/meta.yaml
=> Update agc to 3.2

recipes/ucsc-stringify/build.sh, recipes/ucsc-stringify/include.macos.patch, recipes/ucsc-stringify/meta.yaml
=> Update ucsc-stringify to 472

recipes/skani/meta.yaml
Adding osx-arm64 suport for skani. Per issue https://github.com/bluenote-1577/skani/issues/37
---- …
=> Update skani recipe: add osx-arm64 builds

recipes/arvados-python-client/meta.yaml
The latest release of Arvados-python-client resulted in a cleanup of their dependency stack, which was not propagated into the Conda recipe. This PR address that
---- …
=> Update arvados-python-client: fix requirements

recipes/mmseqs2/build.sh, recipes/mmseqs2/meta.yaml
=> Updated MMseqs2 to 16.747c6

recipes/sylph/meta.yaml
Updating the sylph (https://github.com/bluenote-1577/sylph) recipe, which should be able to build for aarch64 and osx arm 64. 
---- …
=> Update sylph recipe for osx-arm64 and linux-aarch64

recipes/r-lisi/meta.yaml
I'm hoping to get `r-lisi` built for macos ARM64; let me know if there are additional changes needed!
----
Conda is …
=> Update r-lisi for arm64

recipes/kmer-db/meta.yaml
=> Update Kmer-db to 2.2.5

recipes/lz-ani/meta.yaml
=> Update lz-ani to 1.2.3

recipes/vclust/meta.yaml
=> Update vclust to 1.2.9

recipes/ninja-nj/0001-Makefile.patch, recipes/ninja-nj/build.sh, recipes/ninja-nj/meta.yaml
=> Update ninja-nj to 1.00

recipes/nseg/build.sh, recipes/nseg/meta.yaml
=> nseg: add aarch64/arm64 build

recipes/trf/build.sh, recipes/trf/meta.yaml
=> trf: add arm64 build

recipes/strelka/meta.yaml
Bump build number and set noarch: generic to enable linux-aarch64.
=> strelka: enable linux-aarch64

recipes/quota_anchor/build.sh, recipes/quota_anchor/meta.yaml
=> Update quota_anchor to v0.0.1b1

recipes/amplisim/build.sh, recipes/amplisim/meta.yaml
=> linux-aarch64 build for amplisim

recipes/jalview/meta.yaml
Update Jalview to 2.11.4.1
---- …
=> Update Jalview to 2.11.4.1

recipes/pegas/meta.yaml
Update for PeGAS. This update features an overhaul of the html report and a few bugfixes.
=> Update for PeGAS

recipes/yacht/meta.yaml
=> yacht: add linux-aarch64 build

recipes/fairy/build.sh, recipes/fairy/meta.yaml
=> fairy: add aarch64/arm64 builds

recipes/bed2gtf/build.sh, recipes/bed2gtf/meta.yaml
=> bed2gtf: add aarch64 builds

recipes/deepfplearn/meta.yaml
=> Bump deepfplearn

recipes/gretl/meta.yaml
=> gretl: add aarch64/arm64 builds

recipes/bali-phy/build.sh, recipes/bali-phy/meta.yaml
Update bali-phy: 4.0-beta15 -> 4.0-beta16
=> bali-phy: 4.0-beta16

recipes/r-lisi/meta.yaml
=> r-lisi: add linux-aarch64 build

recipes/viral_consensus/build.sh, recipes/viral_consensus/meta.yaml
=> viral_consensus: add aarch64/arm64 builds

recipes/hictkpy/conanfile.py.patch, recipes/hictkpy/meta.yaml
=> Update hictkpy v1.1.0

recipes/hatchet/meta.yaml
Adding the `pybedtools` dependency as specified in HATCHeT's `pyproject.toml`.
---- …
=> Update hatchet dependencies

recipes/aligncov/meta.yaml, recipes/baitfisher/meta.yaml
I have tested it, and it looks good for me
---- …
=> linux-aarch64 build for  Baitfisher

recipes/resistify/meta.yaml
New version of resistify has fewer dependency restrictions so updating recipe accordingly
---- …
=> Update resistify dependencies

recipes/gambit/meta.yaml
=> Update gambit to 1.1.0

recipes/gambit/meta.yaml
=> gambit: add aarch64/arm64 builds

recipes/strainge/meta.yaml
=> strainge: add aarch64/arm64 builds

recipes/gubbins/build.sh, recipes/gubbins/meta.yaml
=> gubbins: add aarch64/arm64 builds

recipes/fastp/build.sh, recipes/fastp/meta.yaml
=> Rebuild fastp recipe

recipes/grz-cli/meta.yaml
This PR adds a recipe for `grz-cli`, a tool to submit data to Genomrechenzentren (GRZ) / Genome data centers (GDC), as part of [Modellvorhaben Genomsequenzierung](https://www.bfarm.de/DE/Das-BfArM/Aufgaben/Modellvorhaben-Genomsequenzierung/_node.html).
---- …
=> Add recipe for `grz-cli`

recipes/seqscreen/meta.yaml
Update version of seqscreen to version 4.4
---- …
=> Update seqscreen to v4.4

recipes/quota_anchor/meta.yaml
=> Update quota_anchor to v0.0.1rc

recipes/cadd-scripts/v1.6/build.sh, recipes/cadd-scripts/v1.6/cadd-install-wrapper.sh, recipes/cadd-scripts/v1.6/cadd-wrapper.sh, recipes/cadd-scripts/v1.6/meta.yaml
Update CADD-scripts from v1.6 to v.1.6.1
---- …
=> Update cadd-scripts to v1.6.1

recipes/ms-entropy/meta.yaml
=> ms-entropy: add aarch64/arm64 builds

recipes/rotate/build.sh, recipes/rotate/meta.yaml
=> rotate: add aarch64/arm64 builds

recipes/cramino/build.sh, recipes/cramino/meta.yaml
=> cramino: add linux-aarch64 build

recipes/cadd-scripts/meta.yaml
Updateing min. Snakemake version to be correct.
---- …
=> Update cadd-scripts v1.7.2

recipes/sneakernet-qc/meta.yaml
Updating SneakerNet-qc to v0.27.2. I would like to note that the bioconda bot did not pick up on this for some reason.
---- …
=> Update SneakerNet-qc v0.27.2

recipes/pybigwig/build.sh, recipes/pybigwig/meta.yaml
=> Update pybigwig to v0.3.23

recipes/alignlib-lite/meta.yaml
=> alignlib-lite: add arm64 build

recipes/gambit/meta.yaml
Set Python version range with `skip: True` and preprocessing selector rather than in `requirements` section.
----
Conda …
=> Fix gambit Python version

recipes/parnas/meta.yaml
Add parnas : Representative taxon sampling from phylogenetic trees
---- …
=> Add parnas

recipes/flexsweep/LICENSE, recipes/flexsweep/meta.yaml
Add flexsweep recipe to bioconda
---- …
=> Add flexsweep v1.0

recipes/ncbi-amrfinderplus/build.sh, recipes/ncbi-amrfinderplus/meta.yaml
Add additional-platforms entries.
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Build ncbi-amrfinderplus for linux-aarch64

build-fail-blacklist, recipes/mustang/0001-Makefile.patch, recipes/mustang/build.sh, recipes/mustang/meta.yaml
=> Update mustang to v3.2.4

recipes/metamdbg/1.0/build.sh, recipes/metamdbg/1.0/meta.yaml
Update [metaMDBG](https://bioconda.github.io/recipes/metamdbg/README.html): 1.0 → 1.1
---- …
=> Update metaMDBG to 1.1

recipes/predictosaurus/build.sh, recipes/predictosaurus/meta.yaml
This PR adds a predictosaurus recipe.
---- …
=> Add predictosaurus recipe

recipes/star-fusion/meta.yaml
=> update star-fusion to 1.14.0

recipes/foldmason/meta.yaml
Updated foldmason to version 2-7bd21ed
---- …
=> Update foldmason to 2-7bd21ed

recipes/dysgu/build.sh, recipes/dysgu/meta.yaml
=> dysgu build for osx x64

recipes/mirscore/meta.yaml
Updating recipe for mirscore to add a requirement that was missing from the prior recipe.
=> Update mirscore meta.yaml

recipes/bioconductor-optilcms/meta.yaml, recipes/optilcms/meta.yaml
This pull request adds the recipe for the **OptiLCMS** R package to the Bioconda channel.
**OptiLCMS** is an R package designed to streamline the processing of **Liquid Chromatography-Mass Spectrometry (LC-MS)** raw data. It automatically optimizes parameters for better analysis. See the official documentation [here](https://www.metaboanalyst.ca/resources/vignettes/LCMSMS_Raw_Spectral_Processing.html) and the GitHub repository [here](https://github.com/xia-lab/OptiLCMS).
----
* New recipes not directly relevant to the biological sciences need …
=> Add recipe for OptiLCMS

recipes/tesorter/meta.yaml
=> Update Tesorter - replace blast by rmblast

recipes/ltr_retriever/meta.yaml
=> Update ltr_retriever - unpin repeatmasker pin <4.1.5

recipes/anarci/meta.yaml
Current version of ANARCI is about 3 years old, this updates it to the latest version.
---- …
=> Update ANARCI to the latest version

recipes/gzrt/build.sh, recipes/gzrt/meta.yaml
=> gzrt: add linuxaarch64 builds

recipes/fc/build.sh, recipes/fc/meta.yaml
=> fc: add linux-aarch64 build

recipes/jarvis3/build.sh, recipes/jarvis3/meta.yaml
=> jarvis3: add aarch64/arm64 build

recipes/locityper/meta.yaml
=> locityper: add linux-aarch64 build

build-fail-blacklist, recipes/phylip/build.sh, recipes/phylip/externs.patch, recipes/phylip/meta.yaml
- Add -fsigned-char for Arm architecture builds
- Change URL to new location
- Fix multiple post-C89 errors
- Add meta.yaml linux-aarch64, document broken osx-arm64
This package is required by t-coffee, which is required by perl-bio-db-hts, which is required - or at least a potential part of - sarek pipeline.
---- …
=> phylip: remove from blacklist and enable linux-aarch64

recipes/opticlust/meta.yaml
Opticlust is a python package to identify interesting single cell clustering resolutions (both porting and extending the Clustree R package).
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
<td>Post links to CI-built packages/containers. <br />You can use this to test …
=> Add opticlust

virdig/build.sh, virdig/meta.yaml
=> Add virdig recipes

recipes/emu-pca/meta.yaml
=> emu-pca: add aarch64/arm64 builds

recipes/starfish/meta.yaml
=> Update starfish to v0.3.1

recipes/mmft/build.sh, recipes/mmft/meta.yaml
Initial add of mmft to conda.
---- …
=> Add mmft 0.2.1

recipes/tir-learner/build.sh, recipes/tir-learner/meta.yaml
=> Rebuild tir-learner to depend on rmblast

recipes/augur/meta.yaml
Bump version and update dependencies
---- …
=> Update augur to 27.0.0

recipes/sylph-tax/meta.yaml
This adds the [sylph-tax](https://github.com/bluenote-1577/sylph-tax) program for incorporating taxonomic information into the sylph metagenome profiler. 
---- …
=> Adding sylph-tax recipe 

recipes/annosine2/meta.yaml
=> Rebuild annosine2 recipe

recipes/consan/build.sh, recipes/consan/meta.yaml
=> Build consan on osx

recipes/blast-legacy/2.2.26/build.sh, recipes/blast-legacy/2.2.26/makedis.patch, recipes/blast-legacy/2.2.26/meta.yaml
=> blast-legacy: add aarch64/arm64 builds

recipes/biobb_io/meta.yaml
=> [biobb_io] update 5.0.1

recipes/umi_tools/meta.yaml
=> Update UMI_tools to v1.1.6

recipes/pseqsid/build.sh, recipes/pseqsid/meta.yaml
This PR adds [`pseqsid`](https://github.com/amaurypm/pseqsid).
---- …
=> Add `pseqsid`

recipes/unitig-caller/meta.yaml
=> unitig-caller: add aarch64/arm64 build

recipes/bioconductor-mpra/meta.yaml
Bumbs a new version of bioconducter-mpra
---- …
=> Update to version 1.28.0

recipes/gpatch/meta.yaml
Adds GPatch utility to bioconda recipes.
---- …
=> Add recipe for GPatch

recipes/biobb_mem/meta.yaml
=> [biobb_mem] update 5.0.3

recipes/khmer/0002-remove-m64.patch, recipes/khmer/meta.yaml
Add patch to stop adding '-m64' - is not necessary on x86 in 2024.
---- …
=> khmer: enable linux-aarch64 and osx-arm64 support

recipes/extract-sv-reads/build.sh, recipes/extract-sv-reads/meta.yaml
=> extract-sv-reads: add linux-aarch64 build

recipes/msisensor/build.sh, recipes/msisensor/meta.yaml
=> msisensor: add linux-aarch64 build

recipes/lrez/lrez-aarch64.patch, recipes/lrez/meta.yaml
=> lrez: add aarch64/arm64 builds

recipes/bindashtree/build.sh, recipes/bindashtree/meta.yaml
We recently developed an ultra-fast genome search and comparison called BinDash 2: https://www.biorxiv.org/content/10.1101/2024.03.13.584875v1.abstract. We further combined it with rapid neighbor-joining algorithm to build genome tree. We rewrite the whole idea in pure Rust, which leads to an extremely fast genome tree build program. It is almost 200 to 1000 times faster than mashtree for various testing genome dataset with identical tree topology. Please merge it if you find it useful. Thanks! Jianshu
----
* New …
=> Add bindashtree

recipes/bioconductor-minfi/meta.yaml
Updates bioconductor-minfi recipe to deal with `preprocesscore container error 22` error by pinning openblas=0.3.3 and updating R version. 
---- …
=> Update recipe for bioconductor-minfi

recipes/popins2/build.sh, recipes/popins2/meta.yaml, recipes/popins2/popins2.patch
=> Add a recipe for PopIns2

recipes/pbmm2/meta.yaml
=> Update pbmm2 to v1.16.99

recipes/stringtie/build.sh, recipes/stringtie/meta.yaml, recipes/stringtie/patch
=> Rebuild stringtie on osx

recipes/gsearch/build.sh, recipes/gsearch/meta.yaml
update gsearch to v0.2.3. add several submodules. 
---- …
=> Update gsearch v0.2.3

recipes/genome_updater/meta.yaml
Update genome_updater to 0.6.4
---- …
=> Update genome_updater to 0.6.4

recipes/paf2chain/build.sh, recipes/paf2chain/meta.yaml
Add `paf2chain` to convert sequence alignment from PAF to CHAIN format.
=> add paf2chain

recipes/smcpp/build.sh, recipes/smcpp/conda_build_config.yaml, recipes/smcpp/meta.yaml, recipes/smcpp/run_test.sh
https://github.com/popgenmethods/smcpp/tree/master/conda
---- …
=> Add recipe for smcpp

recipes/last/meta.yaml
=> Update last to 1607

recipes/mhcflurry/meta.yaml
Dependencies in setup.py where not automatically tranferred. Adding missing `tf-keras` introduced here https://github.com/openvax/mhcflurry/commit/dc49ef1f2bd5733911043f48195a6c045a811664
---- …
=> Patch MHCflurry dependencies and bump build

recipes/mcscanx/.gitattributes, recipes/mcscanx/build.sh, recipes/mcscanx/makefile.patch, recipes/mcscanx/meta.yaml
https://github.com/wyp1125/MCScanX
A release/tag is requested at https://github.com/wyp1125/MCScanX/issues/60
---- …
=> Add a recipe for MCScanX

recipes/captus/meta.yaml
Add salmon >=1.10.0 to Captus in preparation for new version
---- …
=> Add salmon to Captus recipe

recipes/chain2paf/build.sh, recipes/chain2paf/meta.yaml
Add `chain2paf` to convert sequence alignment from CHAIN to PAF format.
=> add chain2paf

recipes/makehub/meta.yaml, recipes/makehub/patch
=> Rebuild makehub recipe

recipes/gzrt/0001-Makefile.patch, recipes/gzrt/build.sh, recipes/gzrt/meta.yaml
=> Update gzrt to v0.9.1

recipes/necat/build.sh, recipes/necat/meta.yaml, recipes/necat/simple_align.patch
=> NECAT: add arm64 builds

recipes/seqsizzle/build.sh, recipes/seqsizzle/meta.yaml
=> seqsizzle: add aarch64/arm64 builds

recipes/lexicmap/meta.yaml
Changelog is here: https://github.com/shenwei356/LexicMap/releases/tag/v0.5.0
---- …
=> Update LexicMap to v0.5.0

recipes/captus/meta.yaml
- Another attempt to install Megahit hfbae3c0_0 in OSX and >=1.2.9 in Linux
----
Conda …
=> Try specific megahits for Linux and OSX

recipes/hostile/meta.yaml
Replaces bot PR https://github.com/bioconda/bioconda-recipes/pull/52918, additionally pinning new deps for version 2.0.0
---- …
=> Update hostile to 2.0.0, update pins in recipe

recipes/tinker/build.sh, recipes/tinker/meta.yaml
=> Add recipe for Tinker 8.11.3

recipes/biox/meta.yaml
This is the first official release of BioX, a specialized compression tool for biological sequence data. 
﻿
* High-performance biological sequence compression tool
* Supports FASTA and FASTQ formats
* Handles DNA, RNA, and protein sequences
* Project URL: https://github.com/TianMayCry9/BioX
﻿
* Fully tested on Windows and Linux platforms
* Validated with genomic data from 100+ species and diverse biological sequence types
* Offers rapid processing at low compression levels while maintaining effective compression ratios
* Achieves industry-leading compression strength at high compression levels
﻿
* Compression/decompression tests on various biological sequence formats
---- …
=> Add biox v1.0.0 - A universal biological sequence compressor

recipes/tower-cli/meta.yaml, recipes/tower-cli/tw.sh
=> Remove LC_ALL from tower-cli recipe

recipes/pantools/meta.yaml
=> Update PanTools to v4.3.2

recipes/allhic/meta.yaml
https://github.com/tanghaibao/allhic/pull/27
---- …
=> AllHIC: Update to v0.9.14

recipes/hostile/meta.yaml
Remove redundant lines for noarch package as suggested by @martin-g  https://github.com/bioconda/bioconda-recipes/pull/52921#discussion_r1893668814. No rebuild needed.
---- …
=> hostile: remove additional-platforms

recipes/stripepy-hic/meta.yaml, recipes/stripepy-hic/run_test.sh
Add recipe for stripepy-hic
---- …
=> Add recipe for stripepy-hic

recipes/unicore/meta.yaml
=> unicore: add aarch64/arm64 builds

recipes/fusion-inspector/meta.yaml
I am manually updating FusionInspector to v2.10.0. BiocondaBot was not able to update it automatically due to a change in the URL (`.FULL.tar.gz` vs `.tar.gz`). 
---- …
=> Update `FusionInspector` to 2.10.0

recipes/vamb/meta.yaml
=> retrigger vamb

recipes/isescan/meta.yaml
The `fraggenescan` dependency just released a new version that fixed a segfault on MacOSX that prevented this tool from being used on this platform. This pull request updates that dependency.
---- …
=> Update isescan to use fraggenescan >= 1.32 dependency so it is compatible with MacOSX

recipes/constellations/meta.yaml, recipes/pangolearn/meta.yaml, recipes/snakemake-wrapper-utils/meta.yaml
Found these problems while parsing all meta.yaml with `yq` tool, as `/scripts/check-for-additional-platforms.sh` does
---- …
=> Fix syntax errors related to misusage of quotes in Jinja template

recipes/samstrip/build.sh, recipes/samstrip/meta.yaml
This PR adds [`samstrip`](https://github.com/jakobnissen/samstrip).
---- …
=> Add `samstrip`

recipes/fusion-report/meta.yaml
This PR manually updates `fusion-report` to 3.1.1. The previous URL did not point to the Clinical Genomics repository and therefore versions were not being updated automatically. …
=> Update `fusion-report` version to 3.1.1

build-fail-blacklist, recipes/perl-alien-build/meta.yaml, recipes/perl-alien-libxml2/meta.yaml, recipes/perl-xml-libxml/build.sh, recipes/perl-xml-libxml/meta.yaml
=> perl-alien-build & perl-alien-libxml2 & perl-xml-libxml: add aarch64 build

recipes/phyclone/meta.yaml
This PR updates the PhyClone recipe from version 0.5.1 to 0.6.0
---- …
=> Update phyclone to 0.6.0

recipes/resistify/meta.yaml
Remove biopython as a dependency and add threadpoolctl for future update
---- …
=> Update Resistify meta.yaml

recipes/strangepg/build.sh, recipes/strangepg/meta.yaml
=> Update strangepg to 0.8.17, add OpenGL ES dependency for aarch64

recipes/fasten/build.sh, recipes/fasten/meta.yaml
=> fasten: add aarch64/arm64 builds

recipes/binette/meta.yaml
This PR updates Binette recipe to version 1.0.5 !
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Update Binette to 1.0.5

recipes/mumemto/build.sh, recipes/mumemto/meta.yaml
=> mumemto: add aarch64/arm64 builds

recipes/suchtree/meta.yaml
=> suchtree: add aarch64/arm64 builds

recipes/mashtree/build.sh, recipes/mashtree/meta.yaml
=> Rebuild mashtree

recipes/primalbedtools/meta.yaml
Added the pypi package primalbedtools. Created recipe with greyskull and added pytest.  
---- …
=> Add primalbedtools

recipes/excludonfinder/meta.yaml
**New Package Submission**
Package: ExcludonFinder
Description: An easy to use tool for identifying and analyzing excludons in genomic data using RNA-seq data. From a given RNA-seq data, alignment is performed against reference genome and coverage per nucleotide is calculated. Convergent (-> <-) and divergent (<- ->) pairs of genes are analyzed, and if TUs overlap, this pair is annotated as Excludon.
Repository: https://github.com/Alvarosmb/ExcludonFinder
----
* New recipes not directly relevant to the biological sciences need to be submitted …
=> Add ExcludonFinder recipe with run_exports

recipes/relecov-tools/meta.yaml
Added relecov-tools, a set of helper tools for the assembly of the different elements in the RELECOV platform (Spanish Network for genomic surveillance of SARS-Cov-2) as data download, processing, validation and upload to public databases, as well as analysis runs and database storage.
https://pypi.org/project/relecov-tools/
https://github.com/BU-ISCIII/relecov-tools
----
* PRs …
=> Add new recipe for relecov-tools

recipes/glean-gene/meta.yaml
GLEAN is an unsupervised learning system to integrate disparate sources of gene structure evidence (gene model predictions, EST/protein genomic sequence alignments, SAGE/peptide tags, etc) to produce a consensus gene prediction, without prior training.
---- …
=> Add a recipe for glean-gene

recipes/biobb_mem/meta.yaml
=> [biobb_mem] update 5.0.5

recipes/atlas/meta.yaml
Update atlas to 2.0.0-rc.7:
https://atlaswiki.netlify.app/ …
=> Update atlas to 2.0.0-rc.7

recipes/annembed/meta.yaml
In this update, we add HubNSW, a new HNSW-based nearest neighbor search algorithm for high dimension dataset, which can be more accurate, save more memory and can be faster for building HNSW graph.
---- …
=> Update annembed v0.1.8

recipes/fast2q/meta.yaml
Add the 2FAST2Q Python module to bioconda.
---- …
=> Add 2fast2q V2.7.2

recipes/gffread/Makefile.patch, recipes/gffread/build.sh, recipes/gffread/meta.yaml
=> gffread: add arm64 build

recipes/poppunk/meta.yaml
=> poppunk: add linux-aarch64 build

recipes/dialign-tx/meta.yaml
Use archive of dialign-tx (checksum unchanged); original download link is deceased.
Add linux-aarch64
=> Re-enable broken dialign-tx (dep of t-coffee, dep of pasta), add linux-aarch64

recipes/abricate/meta.yaml, recipes/agat/meta.yaml, recipes/ensembl-vep/meta.yaml, recipes/mirdeep2/meta.yaml, recipes/perl-bio-phylo/meta.yaml, recipes/srax/meta.yaml, recipes/unitas/meta.yaml
Move some recipes from perl-lwp-simple to perl-libwww-perl: perl-lwp-simple recipe is a shim that installs perl-libwww-perl.  
Version mismatch in dependent packages (particularly with specific older versions) causes dependency match breakage when libwww-perl is available/updated but lwp-simple is not: we should lose the complexity of having two recipes. 
This commit is progress to that goal.
---- …
=> Move recipes from perl-lwp-simple to perl-libwww-perl - part 1

recipes/biobb_flexserv/meta.yaml
=> [biobb_flexserv] update 5.0.0

recipes/biobb_godmd/meta.yaml
=> [biobb_godmd] update 5.0.0

recipes/augur/meta.yaml
Bump version and update dependencies
Supercedes and closes #53225
---- …
=> Update augur to 27.1.0

recipes/htstream/build.sh, recipes/htstream/meta.yaml
=> htstream: add aarch64/arm64 builds

recipes/rust-gtars/build.sh, recipes/rust-gtars/meta.yaml
=> rust-gtars: add linux-aarch64 build

recipes/pymethylation_utils/meta.yaml
Update pymethylation_utils to v0.5.2
---- …
=> Update pymethylation_utils to 0.5.2

recipes/geomloss/meta.yaml
This PR adds geomloss to bioconda. It's required for flexynesis 0.2.13
xref: #53263
---- …
=> add geomloss

recipes/r-ukbrapr/meta.yaml
R functions to use in the UK Biobank Research Analysis Platform (RAP).
=> add r-ukbrapr

recipes/bbmap/meta.yaml
=> Update bbmap to 39.15

recipes/last/meta.yaml
=> Update last to 1608

recipes/bioconductor-biostrings/meta.yaml, recipes/bioconductor-iranges/meta.yaml, recipes/bioconductor-s4vectors/meta.yaml, recipes/bioconductor-xvector/meta.yaml, recipes/bioconductor-zlibbioc/meta.yaml
Updating bioconductor-biostrings to include additional platform osx-arm64
---- …
=> Update bioconductor-biostrings for osx-arm64

recipes/octopusv/meta.yaml
Add octopusv v0.1.0
* New package
* A comprehensive toolkit for analyzing, comparing, and standardizing structural variant (SV) calls from multiple SV callers.
* PyPI link: https://pypi.org/project/octopusv/
* License: MIT
---
=> Add octopusv recipe

recipes/nanomotif/meta.yaml
Need this specific version of pymethylation_utils to work
---- …
=> Update nanomotif dependency

recipes/bayescode/meta.yaml
=> bayescode: add aarch64/arm64 builds

recipes/mmseqs2/meta.yaml
=> Update MMseqs2 to 17.b804f

recipes/biobb_morph/meta.yaml
=> [biobb_morph] update 5.0.0

recipes/mmseqs2/meta.yaml
Seems like MMseqs2 is trying to compile against zlib >= 1.3 and wget only supports <1.3. 
`aria2` is sufficient, we don't necessarily need the wget dependency 
---- …
=> Fix zlib dependency conflict in MMseqs2 Release 17

recipes/openms-meta/meta.yaml
Updates OpenMS to version 3.3
---- …
=> update OpenMS to 3.3

recipes/seismic-rna/meta.yaml
Update seismic-rna to v0.22.3
---- …
=> Update seismic-rna to v0.22.3

recipes/biobb_haddock/build.sh, recipes/biobb_haddock/meta.yaml, recipes/biobb_haddock/post-link.sh
=> [biobb_haddock] update 5.0.0

recipes/poseidon-trident/meta.yaml
=> Update poseidon-trident to 1.6.2.1

recipes/nanomotif/meta.yaml
Follow up of https://github.com/bioconda/bioconda-recipes/pull/53334
----
Conda is able …
=> nanomotif: Apply the improvements from https://github.com/bioconda/bioconda-recipes/pull/53334

recipes/openms-meta/meta.yaml
=> Fix OpenMS symlink issue

recipes/igv/meta.yaml
Fix missing glib dependency (https://github.com/bioconda/bioconda-recipes/pull/53301#issuecomment-2602815114)
---- …
=> Update igv to add missing glib dependency

recipes/staden_io_lib/build.sh, recipes/staden_io_lib/meta.yaml
=> Rebuild staden_io_lib recipe

recipes/biobb_amber/meta.yaml
=> [biobb_amber] update 5.0.4

recipes/kbo-cli/meta.yaml
Adds a recipe for the [kbo sequence aligner](https://docs.rs/kbo) command-line interface.
---- …
=> Add kbo-cli v0.1.1

recipes/emu/meta.yaml
=> Update Emu v3.5.1

recipes/grampa/meta.yaml
I've just added a line to the build script that creates a link from `grampa.py` to `grampa` so the program can be called as such once installed.
---- …
=> Update GRAMPA recipe

recipes/auspice/meta.yaml
=> Update auspice to 2.62.0

recipes/openms-meta/meta.yaml
=> update OpenMS 3.3 with mac builds

recipes/ncbi-stxtyper/build.sh, recipes/ncbi-stxtyper/meta.yaml
=> ncbi-stxtyper: add aarch64/arm64 builds

recipes/fastqsplitter/meta.yaml, recipes/rnastructure/build.sh, recipes/rnastructure/meta.yaml
=> fastqsplitter & rnastructure: add aarch64/arm64 builds

recipes/bali-phy/meta.yaml
Update bali-phy: 4.0-beta16 -> 4.0-beta17
=> bali-phy: 4.0-beta17

recipes/autobigs-engine/meta.yaml
Requesting autobigs-engine, a BIGSdb client library in python, to be added to bioconda.
---- …
=> Add autobigs-engine

recipes/amdirt/meta.yaml
=> Update AMDirT to 1.6.5

recipes/pyopenms/meta.yaml
=> Disable mac builds for pyopenms again

recipes/gdc-client/meta.yaml
=> gdc-client: remove pyopenssl pin

recipes/autobigs-engine/meta.yaml
Changed Python version requirement.
---- …
=> Update autobigs-engine to 0.8.0

recipes/seismic-rna/meta.yaml
=> seismic-rna : add aarch64/arm64 builds

recipes/eastr/meta.yaml
Update metadata for eastr
- Adding our official website and docs
=> Update doc metadata for eastr

recipes/biobb_morph/meta.yaml
=> [biobb_morph] update 5.0.1

recipes/miniasm/build.sh, recipes/miniasm/meta.yaml
=> miniasm: add arm64 build

recipes/unicycler/meta.yaml
=> unicycler: add aarch64 build

recipes/poppunk/meta.yaml
Updates PopPUNK to v2.7.5.
---- …
=> Update PopPUNK to v2.7.5

recipes/curves/meta.yaml
=> [curves_biobb] update 3.0.3

recipes/tgsgapcloser/build.sh, recipes/tgsgapcloser/meta.yaml
=> Rebuild tgsgapcloser

recipes/ms2pip/meta.yaml
Update ms2pip recipe to not use `{{ pin_compatible('numpy') }}`. This restricts runtime Numpy to 2.x, while both 1.x and 2.x are supported.
---- …
=> Update ms2pip recipe

recipes/pybigwig/meta.yaml
Changed recipe version to 0.3.24
=> Update pybigwig to 0.3.24

recipes/curves/Makefile.osx.patch, recipes/curves/meta.yaml
=> [curves_biobb] update 3.0.3b1

recipes/abnumber/meta.yaml
=> Bump up abnumber to 0.4.3

recipes/perl-html-parser/meta.yaml
=> perl-html-parser: add linux-aarch64, bump build

recipes/vg/meta.yaml
This updates vg from v1.61.0 to 1.63.1
---- …
=> Update vg to v.1.63.1

recipes/pb-cpg-tools/build.sh, recipes/pb-cpg-tools/meta.yaml
Adding a new recipe for pb-CpG-tools package from https://github.com/PacificBiosciences/pb-CpG-tools
----
Conda is able …
=> Add recipe for pb-CpG-tools

build-fail-blacklist, recipes/perl-libwww-perl/meta.yaml, recipes/perl-lwp-simple/meta.yaml
This PR sets perl-lwp-simple to be same version as perl-libwww-perl.
The package could be removed if ~14 remaining recipes were amended to use perl-libwww-perl, as it essentially is a subset of it.
---- …
=> perl-lwp-simple: bump the version number of perl-libwww-perl to match

recipes/vartrix/LICENSE, recipes/vartrix/meta.yaml
The `vartrix` recipe is vendoring statically-linked binaries, so we can drop all requirements. This should enable `souporcell` users to install this in [the fully-specified environment](https://github.com/wheaton5/souporcell/blob/08d3c2ef34a8d18903c9c544399dcb93af96ce8f/souporcell_env.yaml) that the project provides. Also, including the required LICENSE file.
----
* PRs require …
=> Tidy up `vartrix` recipe

recipes/sequencetools/meta.yaml
=> Updated sequenceTools 

recipes/nbitk/meta.yaml
This version bump is to incorporate newer documentation, updated dependency management, and a new code of conduct.
---- …
=> Update nbitk v0.3.3

recipes/dxpy/meta.yaml
This updates the requirements in the dxpy recipe to reflect those used for pypi; see: 
* https://github.com/dnanexus/dx-toolkit/blob/v0.388.0/src/python/requirements.txt
* https://github.com/dnanexus/dx-toolkit/blob/master/src/python/setup.py
---- …
=> update dxpy requirements of current recipe to reflect dependencies used for pypi

recipes/dxpy/meta.yaml
Update the `dxpy` recipe to comment out optional extra dependencies: pandas, numpy, and xattr since they're somewhat large in size and not required apart from using the `dx extract_dataset` command. A metapackage with these extra dependencies could be added in the future if needed.
---- …
=> Update dxpy: comment out optional extra dependencies

recipes/jbrowse2/meta.yaml, recipes/kmer-jellyfish/1.1.12/build.sh, recipes/kmer-jellyfish/1.1.12/configure.patch, recipes/kmer-jellyfish/1.1.12/meta.yaml, recipes/krakenuniq/conda_build_config.yaml, recipes/krakenuniq/meta.yaml
krakenuniq - add linux-aarch64, set compiler max version for gnu
kmer-jellyfish 1.12.1 (needed by krakenuniq) - add linux-aarch64 and make build again on linux-64
---- …
=> krakenuniq, kmer-jellyfish 1.1.12: enable aarch64, reenable x86

recipes/nafcodec/meta.yaml
Update `nafcodec` to `v0.3.1`, as `setuptools-rust` was replaced by `maturin`.
---- …
=> Update `nafcodec` to `v0.3.1`

recipes/nafcodec/meta.yaml
This PR enables `linux-aarch64` for `nafcodec`.
---- …
=> Enable `linux-aarch64` for `nafcodec`

recipes/nanoplot/meta.yaml
for some reason, need capitalized NanoPlot again in the URL. Not sure what that is about...
---- …
=> Update NanoPlot to v1.44.1

recipes/twopaco/build.sh, recipes/twopaco/meta.yaml
=> twopaco: add aarch64/arm64 builds

recipes/nbitk/meta.yaml
This minor version bump adds clients to certain Galaxy services. In addition, the last BioConda release turned out to be based on an old commit. This is now corrected.
---- …
=> Update nbitk to v0.4.0

recipes/arborator/meta.yaml
We have updated one of the dependencies of the `arborator` package, `genomics_address_service`, to version [0.1.3](https://github.com/bioconda/bioconda-recipes/pull/53618) to fix a bug. While `arborator` will work with older versions of `genomic_address_service`, I would like the container on biocontainers to be updated to include the most recent version of `genomic_address_service`. This PR updates the build number in order to trigger a re-build of the container.
----
* New recipes not directly relevant to the …
=> Update build number of arborator (2->3)

recipes/sylph-tax/meta.yaml
Sylph-tax was implicitly assuming python v3.7 due to the usage of the "required=True" argument in argparse while parsing subcommand. Pinning python >= 3.7. 
---- …
=> Update sylph-tax recipe (fix python versioning)

recipes/hatchet/build.sh, recipes/hatchet/meta.yaml
=> Rebuild hatchet

recipes/ctyper/0001-Makefile.patch, recipes/ctyper/0002-src.patch, recipes/ctyper/build.sh, recipes/ctyper/meta.yaml
=> Add recipe for ctyper v1.0

recipes/esme/COPYRIGHT_NETCDF-C, recipes/esme/COPYRIGHT_NETCDF-FORTRAN, recipes/esme/conda_build_config.yaml, recipes/esme/meta.yaml
Describe your pull request here:
This PR updates the ESME package to enhance compatibility with CESM by relaxing version constraints and adding necessary runtime dependencies: …
=> Update ESME for wider compatibility and version flexibility

recipes/manta/build.sh, recipes/manta/meta.yaml
See https://github.com/bioconda/bioconda-recipes/issues/53639
---- …
=> Update manta - Add back missing scripts

recipes/krbalancing/build.sh, recipes/krbalancing/meta.yaml
=> krbalancing: add arm64 build

recipes/bioconductor-limma/meta.yaml
Updating bioconductor-limma to build on osx-arm64
---- …
=> Updating bioconductor-limma for osx-arm64

recipes/bioconductor-pcamethods/meta.yaml
Updating bioconductor-pcamethods to build on osx-arm64
---- …
=> Updating bioconductor-pcamethods for osx-arm64

recipes/bioconductor-biocparallel/meta.yaml
Updating bioconductor-biocparallel to build on osx-arm64
---- …
=> Updating bioconductor-biocparallel for osx-arm64

recipes/nanocaller/meta.yaml
We need to limit tensorflow version to 2.15.0, as stated in the original project: https://github.com/WGLab/NanoCaller/blob/master/environment.yml
---- …
=> Update meta.yaml for NanoCaller

recipes/tmalign/TMalign.cpp, recipes/tmalign/build.sh, recipes/tmalign/meta.yaml
=> Update tmalign to 20190818

recipes/perl-data-uuid/meta.yaml
=> perl-data-uuid: add aarch64/arm64 builds

recipes/vpt-segmentation-packing/meta.yaml
adds vpt-segmentation-packaging dependency for VPT (#53647)
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Also, the bot watches for comments …
=> add Vpt segmentation packing

recipes/bioconductor-globalancova/meta.yaml, recipes/bioconductor-graph/meta.yaml
Updating bioconductor-globalancova to build on osx-arm64
---- …
=> Updating bioconductor-globalancova for osx-arm64

recipes/bioconductor-genefilter/meta.yaml, recipes/bioconductor-impute/meta.yaml, recipes/bioconductor-preprocesscore/meta.yaml, recipes/bioconductor-rgraphviz/meta.yaml, recipes/bioconductor-sva/meta.yaml
Updating a small collection of bioconductor packages to build on osx-arm64. These are dependencies of a package I need to install.
---- …
=> Updating some bioconductor packages for osx-arm64

recipes/biox/meta.yaml
This PR updates the `biox` package to **v1.2.0**, introducing a new module for **evolutionary distance calculation and sequence clustering**. The update includes:
- Implementation of NCD (Normalized Compression Distance) for sequence comparison
- Hierarchical clustering based on pairwise distance matrices
=> Update biox to 1.2.0

recipes/dendropy/meta.yaml, recipes/learnmsa/meta.yaml
Updating learnMSA recipe to version 2.0.10.
---- …
=> Update learnmsa to 2.0.10

recipes/bioconductor-affy/meta.yaml, recipes/bioconductor-delayedarray/meta.yaml, recipes/bioconductor-genomicranges/meta.yaml, recipes/bioconductor-impute/meta.yaml, recipes/bioconductor-mscoreutils/meta.yaml, recipes/bioconductor-mzr/meta.yaml, recipes/bioconductor-vsn/meta.yaml
Updating bioconductor packages to build on osx-arm64. These packages are dependencies for an R package I need.
---- …
=> Updating bioconductor packages for osx-arm64

recipes/bioconductor-rbgl/meta.yaml
Updating bioconductor-rbgl to build on osx-arm64
---- …
=> Updating bioconductor-rbgl for osx-arm64

recipes/bioconductor-multtest/meta.yaml
Updating bioconductor-multtest to build on osx-arm64
---- …
=> Updating bioconductor-multtest for osx-arm64

recipes/bioconductor-msnbase/meta.yaml
Updating bioconductor-msnbase to build on osx-arm64
---- …
=> Updating bioconductor-msnbase for osx-arm64

recipes/bioconductor-globalancova/meta.yaml
=> Add linux-aarch64 to bioconductor-globalancova

recipes/bioconductor-camera/meta.yaml
Updating bioconductor-camera to build on osx-arm64
---- …
=> Updating bioconductor-camera to build on osx-arm64

recipes/bioconductor-fgsea/meta.yaml
Updating bioconductor-fgsea to build on osx-arm64. Bumping patch version as the previous version wouldn't build.
---- …
=> Updating bioconductor-fgsea for osx-arm64

recipes/adas/build.sh, recipes/adas/meta.yaml
Adas is designed for searching long sequence databases, especially biological sequences. The core idea is from innovative applications of Minimzer, MinHash, Coreset and hierarchical navigable small world graphs (HNSW) algorithms.
Here we simply describe the algorithm:
1. build HNSW graph for all sequences as a database, the underlying algorithm will be Order 2. MinHash, an LSH for Edit distance.
2. Search new sequences against the pre-built database. The same Order MinHash algorithm will be used.
3. For closest sequences to query seqeunces (e.g., top 100), seed-chain-exend and adaptive banded dynamic progrmming will be performed.
----
Please read the [guidelines for Bioconda recipes](https://bioconda.github.io/contributor/guidelines.html) before opening a …
=> Add adas v0.1.2

recipes/seqnado/meta.yaml
Update SeqNado dependencies to be in line with the current PyPi package.
---- …
=> Update seqnado dependencies

recipes/esme/conda_build_config.yaml, recipes/esme/meta.yaml
This PR tried to relax the **run** requirements for the `esme` package.
----
Conda is …
=> Relax run requirements

recipes/nbitk/meta.yaml
In this update, the nbitk toolkit has a parser for DarwinCore taxonomies. No changes otherwise.
---- …
=> Update nbitk v0.5.0

recipes/annembed/meta.yaml
In this release, we have better diffusion map and better command line parsing. Now you can change each HNSW construction factor. 
---- …
=> Update annembed v0.1.9

recipes/tmalign/build.sh, recipes/tmalign/meta.yaml
=> Update tmalign to 20220227

recipes/metabuli/meta.yaml
- Fix errors in v1.0.9
- Custom DB creation became easier
- Improve updateDB command
---- …
=> [Update] Metabuli v1.1.0

recipes/unicore/build.sh, recipes/unicore/meta.yaml
=> update unicore to 1.1.0

recipes/biobb_mem/meta.yaml
=> [biobb_mem] update 5.0.6

recipes/piler-cr/build.sh, recipes/piler-cr/meta.yaml
=> piler-cr: add linux-aarch64

recipes/mashtree/meta.yaml, recipes/perl-aceperl/meta.yaml, recipes/quicktree/build.sh, recipes/quicktree/meta.yaml
=> mashtree & quicktree & perl-aceperl: add aarch64 build

recipes/bakta/meta.yaml
=> Rebuild bakta

recipes/quicktree/build.sh, recipes/quicktree/meta.yaml, recipes/quicktree/patches/0001-Add-rule-to-build-shared-library.patch
=> quicktree: add arm64 build

recipes/cnvnator/meta.yaml
=> cnvnator: add linux-aarch64

recipes/prinseq-plus-plus/meta.yaml
=> prinseq-plus-plus: add linux-aarch64

recipes/rhocall/meta.yaml
=> rhocall: add linux-aarch64

recipes/regtools/build.sh, recipes/regtools/meta.yaml
=> regtools: add linux-aarch64

recipes/pullseq/build.sh, recipes/pullseq/conda_build_config.yaml, recipes/pullseq/implicit.patch, recipes/pullseq/meta.yaml
=> pullseq: add linux-aarch64

recipes/hmmer2/build.sh, recipes/hmmer2/meta.yaml
=> hmmer2: add linux-aarch64

recipes/intarna/meta.yaml
=> intarna - trigger new build with recent viennarna dependency

recipes/randfold/meta.yaml
=> randfold: add linux-aarch64

recipes/mbuffer/build.sh, recipes/mbuffer/meta.yaml
=> mbuffer: add linux-aarch64

recipes/tagbam/build.sh, recipes/tagbam/meta.yaml
=> Add tagbam 0.1.0

recipes/r-metacoder/meta.yaml
=> r-metacoder: add aarch64/arm64 builds

recipes/seismic-rna/meta.yaml
Update seismic-rna to v0.23.1
---- …
=> Update seismic-rna to v0.23.1

recipes/egap/meta.yaml
Updated to attempt sra-toolkit installation
---- …
=> Update meta.yaml 2.6.4

recipes/hitac/meta.yaml
This PR restricts the dependencies that currently work with HiTaC, as the loose versions were generating installation errors.
---- …
=> Update HiTaC dependencies

recipes/pbsim3/build.sh, recipes/pbsim3/meta.yaml
=> pbsim3: add aarch64/arm64 builds

recipes/fastoma/meta.yaml
Adding the recipe for the [fastOMA](https://github.com/DessimozLab/fastoma) package .
=> Add fastoma recipe

recipes/neffy/meta.yaml
=> neffy: add aarch64/arm64 builds

recipes/svaba/build.sh, recipes/svaba/meta.yaml
=> svaba: add aarch64/arm64 builds

recipes/s4pred/build.sh, recipes/s4pred/meta.yaml
=> Add s4pred

recipes/metafx/build.sh, recipes/metafx/meta.yaml
Add metafx recipe
MetaFX (METAgenomic Feature eXtraction) is an open-source library for feature extraction from whole-genome metagenome sequencing data and classification of groups of samples.
---- …
=> Add metafx recipe

recipes/fastahack/0001-Makefile.patch, recipes/fastahack/build.sh, recipes/fastahack/meta.yaml
=> Rebuild fastahack

recipes/genin2/meta.yaml
Genin2 is a lightining-fast bioinformatic tool to predict genotypes for H5 viruses belonging to the European clade 2.3.4.4b
---- …
=> feat: add recipe for genin2

recipes/hmftools-purple/meta.yaml, recipes/hmftools-redux/meta.yaml
=> Update hmftools redux

recipes/hmftools-pave/meta.yaml
=> Update hmftools pave

recipes/hmftools-sage/meta.yaml
=> Update hmftools-sage to 4.0

recipes/hmftools-chord/meta.yaml
=> Update hmftools-chord to 2.1.0

recipes/hmftools-linx/meta.yaml
=> Update hmftools-linx to 2.0

recipes/hmftools-esvee/meta.yaml
=> Update hmftools-esvee to 1.0

recipes/muat/meta.yaml
Update muat package to version 0.1.1.
New Features:
- Training Mutation-Attention on PCAWG data
- Inference Mutation-Attention on PCAWG data
- Preprocessing somAgg Genomics England for MuAt2
---- …
=> Update muat to version 0.1.1

recipes/seqlib/build.sh, recipes/seqlib/bwa-Makefile.patch, recipes/seqlib/fermi-Makefile.patch, recipes/seqlib/meta.yaml
=> Add recipe for SeqLib v1.2.0

recipes/pupmapper/meta.yaml
This PR adds `pupmapper` to bioconda. `pupmapper` is a tool for calculating a metric of sequence uniquness called pileup mappability for input genome/nucleotide sequences. `pupmapper` is implemented in python and depends on `genmap` and `bigtools` for some functionalities. Both of these tools are available from bioconda as well.
----
* PRs require reviews prior to being merged. Once …
=> Add pupmapper v0.0.9

recipes/hmftools-cuppa/meta.yaml
=> Update hmftools-cuppa to 2.3.1

recipes/bbmap/meta.yaml
=> Update bbmap to 39.17

recipes/consent/build.sh, recipes/consent/meta.yaml
=> Rebuild CONSENT

recipes/libssw/build.sh, recipes/libssw/meta.yaml, recipes/libssw/waterman-lib.patch
=> Update libssw to 1.2.5

recipes/vcfexpress/build.sh, recipes/vcfexpress/meta.yaml
=> Add vcfexpress

recipes/hmftools-redux/meta.yaml
=> Add samtools dependency to hmftools-redux

recipes/autobigs-engine/meta.yaml
Updating Bioconda autobigs-engine to 0.12.0
---- …
=> Update autobigs engine to 0.12.0

recipes/mlstdb/meta.yaml
Adds `mlstdb` to bioconda
---- …
=> Add mlstdb package

recipes/vcflib/0001-CMakeLists.patch, recipes/vcflib/build.sh, recipes/vcflib/meta.yaml
=> Rebuild vcflib

recipes/hmftools-orange/meta.yaml
=> Update hmftools orange

recipes/bioconductor-bambu/meta.yaml
Update bambu version to 3.8.3 
Test if the new push fixes the build failures
----
Conda …
=> Update bioconductor-bambu to 3.8.3

recipes/scarap/meta.yaml
Updates the pinned python version to 3.11
---- …
=> Update python pinned version for scarap

recipes/micomplete/meta.yaml
=> Add `micomplete`

recipes/hmftools-neo/meta.yaml
=> Update hmftools-neo to 1.2

recipes/pigpen/meta.yaml
Add pigpen package. See https://github.com/TaliaferroLab/OINC-seq and https://www.biorxiv.org/content/10.1101/2024.11.12.623278v1
---- …
=> Add pigpen

recipes/ensembl-py/meta.yaml
Add the ensembl-pyrepository into bioconda to facilitate its distribution and usage.
---- …
=> Add bioconda recipe for ensembl-py

recipes/ensembl-genomio/meta.yaml
Add the ensembl-genomio repository into bioconda to facilitate its distribution and usage.
---- …
=> Add bioconda recipe for ensembl-genomio

recipes/plink/build.sh, recipes/plink/meta.yaml
=> Re-upload plink

recipes/pigpen/meta.yaml
=> pigpen: add aarch64/arm64 builds

recipes/plink/meta.yaml
Relates to update requested in #54006
=> Update plink to v1.9.0-b.7.7 (2024 release)

recipes/seismic-rna/meta.yaml
Add dependencies jgo, maven, openjdk. Bump numpy and numba requirements.
---- …
=> Update seismic-rna to 0.24.0

recipes/macs3/meta.yaml
=> Update macs3 to v3.0.3

recipes/pantools/meta.yaml
Update PanTools to version v4.3.3
=> Update PanTools to version v4.3.3

recipes/hmftools-virus-interpreter/meta.yaml
=> Update hmftools-virus-interpreter to 1.7

recipes/atol-bpa-datamapper/meta.yaml
=> Add atol-bpa-datamapper

recipes/s4pred/meta.yaml
=> s4pred build version bump to retry creating container

recipes/rnalyze/meta.yaml
**Brief Description**
rnalyze is a Bash-based pipeline for analyzing RNA-Seq data. It supports both single-end and paired-end data, and includes quality control, trimming, alignment, and feature counting. The tool is highly customizable and designed to streamline RNA-Seq data processing for bioinformaticians and researchers.
**Key Features**
- Flexible Alignment: Supports BWA, Bowtie2, and HISAT2 for read mapping.
- Data Acquisition: Handles both SRA downloads and local data directories.
- Quality Control: Uses FastQC and MultiQC for quality assessment.
- Trimming: Integrates Trimmomatic for adapter and quality trimming.
- Feature Quantification: Utilizes FeatureCounts for generating count matrices.
- Scalability: Efficiently utilizes multi-threading for optimized performance.
**Source …
=> Add rnalyze recipe

recipes/cleanifier/meta.yaml
=> Add Cleanifier

recipes/gfviewer/meta.yaml
This is a tool for visualizing the localization of multi-gene families across the genome of a given organism. It is built using python as the sole programming language and configured into a package using all the necessary guidelines for Bioconda.
---- …
=> Added recipe for gfviewer v1.0.4

recipes/minia/conda_build_config.yaml, recipes/minia/meta.yaml
=> minia: add linux-aarch64

build-fail-blacklist, recipes/atol-bpa-datamapper/meta.yaml, recipes/perl-sereal-decoder/meta.yaml
=> perl-sereal-decoder: add linux-aarch64

recipes/radiantkit/meta.yaml, recipes/wakhan/meta.yaml
bump radiantkit and wakhan build and fix radiantkit dependency version
---- …
=> bump radiantkit and wakhan build number

build-fail-blacklist, recipes/star-fusion/meta.yaml
This will thereby enable linux-aarch64 for this package which cannot currently use non-existent old perl-db-file..
---- …
=> Fix star fusion to use perl-db_file which replaces perl-db-file

recipes/gridss/meta.yaml
=> gridss: add linux-aarch64 build

recipes/ont_vbz_hdf_plugin/conda_build_config.yaml, recipes/ont_vbz_hdf_plugin/meta.yaml
=> ont_vbz_hdf_plugin: update to 1.0.12, add linux-aarch64, resolve x86 build fails

build-fail-blacklist, recipes/star-fusion/meta.yaml
package perl-io-gzip doesn't exist - it was renamed to perl-perlio-gzip, this fix gets star-fusion to use it.
---- …
=> Fix star-fusion: rename use of perl-io-gzip to perl-perlio-gzip

recipes/checkm2/meta.yaml
This fixes broken dependencies for checkm2 v1.1.0
---- …
=> update checkm2 dependencies to match version 1.1.0 requirements

recipes/aragorn/meta.yaml
This adds "osx-arm64" as an extra platform for aragorn.
worked like a charm on a github runner running on macos-15.
---- …
=> update aragorn with osx-arm64 build

recipes/gempipe/meta.yaml
=> update gempipe to v1.37.7

recipes/kmcp/meta.yaml
The authors have built osx-arm64 and linux-aarch64 binaries, so this patch uses them
---- …
=> kmcp: add linux-aarch64, osx-arm64 binaries

recipes/hic-straw/meta.yaml
=> hic-straw: add arm64/aarch64 builds

build-fail-blacklist, recipes/bandage/meta.yaml
This fails at the moment on linux-aarch64 with a local build due to missing GL libraries; putting this PR out to see if failing on x86.
---- …
=> bandage: add linux-aarch64

recipes/pairtools/build.sh, recipes/pairtools/meta.yaml
=> Update pairtools to v1.1.3

recipes/kma/build.sh, recipes/kma/meta.yaml
=> Update kma to v1.4.18

recipes/metamdbg/0001-CMakeLists.patch, recipes/metamdbg/ContigPolisher.hpp, recipes/metamdbg/build.sh, recipes/metamdbg/meta.yaml
=> metaMDBG: add osx builds

build-fail-blacklist, recipes/oligoarrayaux/meta.yaml
=> oligoarrayaux: restore package, add linux-aarch64

recipes/ppanggolin/meta.yaml
This adds osx-arm64 build for ppanggolin
---- …
=> update ppanggolin for osx-arm64

recipes/easypqp/meta.yaml
=> Bump easypqp 0.1.51

recipes/funannotate/meta.yaml
See https://github.com/nextgenusfs/funannotate/compare/v1.8.15...v1.8.17
---- …
=> Funannotate: add distro

recipes/autobigs-cli/meta.yaml
Improved general user friendliness. Makes use of autobigs-engine 0.13.*.
---- …
=> Update autobigs-cli bioconda to 0.6.0

recipes/r-shinyngs/meta.yaml
Bumping shinyngs in lieue of functional autobump for this recipe
---- …
=> bump shinyngs version

recipes/raptor/build.sh, recipes/raptor/meta.yaml
=> raptor: add linux-aarch64

recipes/artex/build.sh, recipes/artex/meta.yaml
=> Add artex recipe

recipes/mitorsaw/build.sh, recipes/mitorsaw/meta.yaml
=> Add mitorsaw recipe

recipes/autobigs-cli/meta.yaml
Updates autobigs-cli to 0.6.2: Now supports splitting series of FASTA file paths by comma.
---- …
=> Update autobigs cli 0.6.2

recipes/adas/meta.yaml
We use adas-chain, SAM as output format. add benchmark scripts. 
---- …
=> Update adas v0.1.3

recipes/sepp/build.sh, recipes/sepp/meta.yaml
This PR relates to #54024, where I forgot to smuggle the `bin/` part into the paths to binaries of the generated upp.config file.
---- …
=> update: fix UPP configuration, second attempt

recipes/bali-phy/meta.yaml
Update bali-phy: 4.0-beta17 -> 4.0
=> Update bali-phy to 4.0

recipes/gqlib/meta.yaml
This PR adds a recipe for `gqlib`, a library for gene quantification by @cschu.
---- …
=> Add recipe for `gqlib` Python package

recipes/pymethylation_utils/meta.yaml
Update pymehtylation utils
---- …
=> Update pymethylation_utils to 0.5.3

recipes/poly-qtlseq/meta.yaml
Update poly-qtlseq 1.0.1 to 1.0.2.
Fix autobump PR( #54248)
---- …
=> Update poly-qtlseq to 1.0.2

recipes/pvga/meta.yaml
PVGA is a powerful virus-focused assembler that does both assembly and polishing.
=> pvga 0.1.1

recipes/muat/meta.yaml
New Features:
- Training MuAt1 (single and multi labels)
- Training MuAt2 (pretraining)
=> Update muat to version 0.1.2

recipes/atlas/meta.yaml
=> Update atlas to 2.0.0-rc.8

recipes/reseek/build.sh, recipes/reseek/meta.yaml
=> Update reseek to v2.4

recipes/autocycler/build.sh, recipes/autocycler/meta.yaml
=> Add recipe for Autocycler v0.2.1

recipes/snakemake-storage-plugin-sharepoint/meta.yaml
Add the SharePoint plugin for snakemake
---- …
=> Add snakemake storage plugin for Microsoft SharePoint

recipes/hictk/build.sh, recipes/hictk/conan_profiles/apple-clang, recipes/hictk/conan_profiles/clang, recipes/hictk/conan_profiles/gcc, recipes/hictk/conda_build_config.yaml, recipes/hictk/meta.yaml, recipes/hictk/run_test.sh
=> hictk: fix sigkill on macos

recipes/revoluzer/meta.yaml
=> bump revoluzer to 0.1.7

recipes/vuegen/meta.yaml
👷 Bump the build number to rerun the CI tests and upload vuegen into biocontainers
---- …
=> 👷 Rerun vuegen recipe to test deployment on biocontainers

recipes/snakemake/meta.yaml
=> Remove superfluous datrie dependency from snakemake (has been removed)

recipes/enviroampdesigner/meta.yaml
Adding new package for design of amplicons for environmental sequencing.
=> Add new package EnviroAmpDesigner

recipes/bioconductor-glmgampoi/meta.yaml
=> bioconductor-glmgampoi: add linux-aarch64

recipes/plannotate/meta.yaml
Bumps the minor version of pLannotate.
---
Reference notes below for myself:
=> Update pLannotate to v1.2.3 (patch version bump)

recipes/resistify/meta.yaml
Removing `rich` dependencies as these are no longer used!
---- …
=> Update: Resistify - remove unused dependencies

recipes/bioconductor-dada2/meta.yaml
=> bioconductor-dada2: add linux-aarch64

recipes/hmftools-cuppa/meta.yaml
=> Update hmftools-cuppa to version 2.3.2

recipes/perl-bio-phylo-forest-dbtree/meta.yaml
To this version bump of [perl-bio-phylo-forest-dbtree](https://metacpan.org/dist/Bio-Phylo-Forest-DBTree) an additional file parser is added, which parses [BOLD BCDM data packages](https://bench.boldsystems.org/index.php/datapackages/Latest) to the level of process IDs, resulting in a database tree with >10M tips. The semantic version number (v0.2.1) refers to the CPAN release with the added functionality, the meta.yaml release (0.58) is the version number that is propagated from Bio::Phylo, for which this package is an extension.
----
* New …
=> Update perl-bio-phylo-forest-dbtree to v0.2.1

recipes/r-psminer/meta.yaml
Add recipe for new R package `psminer` hosted on Github (for now).
=> Add r-psminer

recipes/r-signac/1.13.0/build.sh, recipes/r-signac/1.13.0/meta.yaml
For a client, I need the previous version of r-signac (1.13.0) built against the latest R 4.4. It is currently only built for [R 4.3](https://anaconda.org/bioconda/r-signac/files?version=1.13.0).
I purposefully didn't bump the build number because this will be the first build with R 4.4 (and 4.4 is the only r-base version currently [pinned](https://github.com/bioconda/bioconda-utils/blob/0127c7f1605394731d98a177e439370add40de75/bioconda_utils/bioconda_utils-conda_build_config.yaml#L29)).
----
* New recipes not directly relevant to the …
=> Build r-signac 1.13.0 with the latest r-base 4.4

recipes/gmap/0002-genome_sites.patch, recipes/gmap/build.sh, recipes/gmap/meta.yaml
=> gmap: add osx build

recipes/last/meta.yaml
=> Update last to 1611

recipes/longbow/build.sh, recipes/longbow/meta.yaml
=> Add longbow recipe

recipes/danbing-tk/build.sh, recipes/danbing-tk/meta.yaml
=> Add danbing-tk v1.3.2.5

recipes/postmaster/LICENSE, recipes/postmaster/meta.yaml
=> add postmaster

recipes/olivar/meta.yaml
=> Update olivar to 1.3.0

recipes/metafun/build.sh, recipes/metafun/meta.yaml
(otherwise, please submit to [conda-forge](https://conda-forge.org/docs/)).
Description:
metafun is a comprehensive workflow management package designed for metagenomic analysis in bioinformatics.
---- …
=> Add metafun package

recipes/jacusa2/LICENSE, recipes/jacusa2/build.sh, recipes/jacusa2/meta.yaml
Add [JACUSA2](https://github.com/dieterich-lab/JACUSA2)
---- …
=> Add jacusa2

recipes/revoluzer/meta.yaml
=> bump revoluzer to 0.1.8

recipes/perl-cgi/meta.yaml
=> perl-cgi: add linux-aarch64

recipes/binette/meta.yaml
This PR updates Binette recipe to version 1.1.0
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> Update Binette to 1.1.0

recipes/meme/meta.yaml
=> meme: add linux-aarch64

recipes/smallgenomeutilities/meta.yaml
- [Build 1 (by biocondabot)](#54419) missed new dependencies and new scripts
- Adding new dependencies:
- pysam now 	`>= 0.23` (need new "with_cigar" feature)
- more-itertools
- Adding new scripts:
- paired_end_read_merger
- coverage_depth_qc
---- …
=> Update: smallgenomeutilities - fix dependencies

recipes/amiga/meta.yaml
I updated the recipe to address the following:
- Similar to [#30370](https://github.com/bioconda/bioconda-recipes/pull/30370), I removed python version pins and added `skip: True` with selectors instead. 
- Related to [GPy #1079](https://github.com/SheffieldML/GPy/issues/1079), I bumped the version for GPy.
---- …
=> Update amiga recipe

recipes/plasann/meta.yaml
1. Change the scripts so that it can handle input  genbank CDS without translation sequence
2. The pipeline can handle forward and reverse strand better
=> Update PlasAnn to version 1.0.2

recipes/pear/meta.yaml
=> pear: add linux-aarch64

recipes/wgsim/meta.yaml
=> wgsim: add linux-aarch64

recipes/py_fasta_validator/meta.yaml
=> py_fasta_validator: add linux-aarch64

recipes/segemehl/meta.yaml
=> segemehl: add linux-aarch64

recipes/afragmenter/meta.yaml
This PR adds a new recipe for [AFragmenter ](https://github.com/[sverwimp/AFragmenter](https://github.com/sverwimp/AFragmenter)) which is a tuneable method for segmenting AlphaFold protein structures.
----
* Please post …
=> Add AFragmenter

recipes/pilea/meta.yaml
=> add recipe pilea

recipes/easel/conda_build_config.yaml, recipes/easel/meta.yaml
=> easel: add linux-aarch64

recipes/eggnog-mapper/meta.yaml
=> eggnog-mapper: add linux-aarch64

recipes/aviary/meta.yaml
=> Update Aviary to v0.11.1

recipes/perl-list-moreutils-xs/meta.yaml
=> perl-list-moreutils-xs: add osx-arm64

recipes/magneto/meta.yaml
Update magneto version 1.2 to 1.3.
New functionalities and works with a more recent version of snakemake
----
Conda is …
=> Update magneto version 1.2 to 1.3

recipes/namfinder/build.sh, recipes/namfinder/meta.yaml
=> namfinder: add linux-aarch64

recipes/seqkit/meta.yaml
- [SeqKit v2.10.0](https://github.com/shenwei356/seqkit/releases/tag/v2.10.0) - 2025-03-12 [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/seqkit/v2.10.0/total.svg)](https://github.com/shenwei356/seqkit/releases/tag/v2.10.0)
- `seqkit`:
- add a global flag `--skip-file-check`: skip input file checking when given a file list if you believe these files do exist.
It helps to reduce file checking time when given a huge number of sequence files.
- `seqkit split2`:
- fix prefix checking when paired-end files are given. [#512](https://github.com/shenwei356/seqkit/issues/512)
- `seqkit stat`:
- do not compute GC content and N's for protein sequence. [#497](https://github.com/shenwei356/seqkit/issues/497)
- `seqkit grep`:
- add …
=> Update SeqKit to v2.10.0

recipes/caspeak/meta.yaml
=> add requirements of caspeak

recipes/namfinder/build.sh, recipes/plek/build.sh, recipes/plek/meta.yaml
=> plek: add linux-aarch64

recipes/miranda/build.sh, recipes/miranda/meta.yaml
The original URL has gone AWOL - so replaced by an old archive which I found. It has the same sha256sum.  Possibly the last copy of the source on the internet.. it is 2010.  Would be better if bioconda had an archive of these things - but I'm not aware of one - am open to suggestions!
----
* PRs require reviews prior to being merged. Once your PR is …
=> miranda: use replacement URL - and add linux-aarch64

recipes/mtm-align/meta.yaml
=> mtm-align:  use new source URL for download and add linux-aarch64

recipes/python-edlib/meta.yaml, recipes/r-ggbiplot/meta.yaml, recipes/r-lncpipereporter/meta.yaml
=> r-lncpipereporter, r-ggbiplot: add linux-aarch64

recipes/atol-bpa-datamapper/meta.yaml
Update atol-bpa-datamapper dependencies
---- …
=> Update atol-bpa-datamapper dependencies

recipes/commec/meta.yaml
Update the Common Mechanism to version 0.3.1.
----
This way, one can avoid that expectations of a downstream recipe with regards to API, ABI, or CLI are violated by later changes in …
=> Update Commec v0.3.1

recipes/panacus/meta.yaml
Updates panacus to version 0.3.3 that fixes a couple of issues
---- …
=> Update panacus to version 0.3.3

recipes/hippunfold/meta.yaml
=> Add hippunfold

recipes/compleasm/meta.yaml, recipes/rnanorm/2.1.0/meta.yaml, recipes/rnanorm/meta.yaml
The recipe was updated automatically to version 2.2.0. But the dependencies where not updated. I now fixed the deps and added the older version.
---- …
=> Update version 2.2.0 rnanorm and added older version 2.1.0

build-fail-blacklist, recipes/percolator/boost-dynamic.patch, recipes/percolator/build.sh, recipes/percolator/meta.yaml, recipes/xsd/build.sh, recipes/xsd/meta.yaml, recipes/xsd/ostream-include.patch
- also converts percolator to use dynamic boost library
---- …
=> percolator, xsd: add linux-aarch64; restore xsd from compile fail blacklist

recipes/genomic_address_service/meta.yaml
Adjusts Python version requirements for genomic_address_service since the software requires Python >= 3.10 and < 3.13. I added two additional test commands to run (e.g., `gas call -h`) which will fail if using an incorrect Python version.
---- …
=> Update: genomic_address_service python requirements

recipes/metafun/meta.yaml
=> Update metafun to 0.2.0

recipes/perl-io-compress/meta.yaml
=> perl-io-compress: add osx-arm64

recipes/kraken/meta.yaml
=> linux-aarch64 build for kraken

recipes/ena-webin-cli/meta.yaml
Bump openjdk dependency for `ena-webin-cli`. Current version gives class file version incompatibility errror.
Fixes #54547
---- …
=> Update `ena-webin-cli` to use newer openjdk dependency

recipes/formulaic-contrasts/meta.yaml
Add formulaic-contrasts 1.0.0 from https://github.com/scverse/formulaic-contrasts. Adding so I can update pyDESeq2.
=> Add formulaic contrasts

recipes/hmftools-esvee/meta.yaml
=> Update hmftools-esvee to v1.0.2

recipes/lassaseq/meta.yaml
=> Update Lassaseq (v.0.1.2)

recipes/perl-xml-libxslt/meta.yaml
=> perl-xml-libxslt: add linux-aarch64

recipes/cell2cell/meta.yaml, recipes/liana/meta.yaml
- liana - adds linux-aarch64
- cell2cell bump of python is necessary due to conflicting minimum version of python in liana 1.5.1
- remove cylp dependency: this is no longer in liana, optional nor otherwise.
----
* Please post …
=> liana: update to 1.5.1 and add aarch64, bump python max version of cell2cell

recipes/pybwa/meta.yaml
=> chore: add DOI to pybwa

recipes/fgpyo/meta.yaml
=> chore: add doi to fgpyo

recipes/fgsv/meta.yaml
=> chore: add DOI to fgsv

recipes/fgbio/meta.yaml
=> chore: add doi to fgbio

recipes/arborator/meta.yaml
Rebuilds arborator container to use latest versions of genomic_address_service (version `0.1.5`) and profile_dists (version `1.0.3`).
---- …
=> Update: Rebuild of arborator container

recipes/hippunfold-dev/meta.yaml
=> Add hippunfold-dev

recipes/mutserve/build.sh, recipes/mutserve/meta.yaml
Added the recipe of [Mutserve](https://github.com/seppinho/mutserve)
---- …
=> Add Mutserve recipe

recipes/snakemake-storage-plugin-xrootd/meta.yaml
=> Add snakemake-storage-plugin-xrootd

recipes/gubbins/meta.yaml
Gubbins recipe only supports python3.10 max, rebuild for newer python
---- …
=> Rebuild gubbins for newer python versions

recipes/snakemake-executor-plugin-aws-batch/meta.yaml
Add snakemake-executor-plugin-aws-batch
---- …
=> Add snakemake-executor-plugin-aws-batch

recipes/deacon/meta.yaml
Add recipe for the lightweight (host) sequence filtering tool Deacon https://github.com/bede/deacon/
=> Add recipe for deacon

recipes/gencube/meta.yaml
=> Add Gencube version 1.1.0

recipes/bbmap/meta.yaml
=> Update bbmap to 39.19

recipes/last/meta.yaml
=> Update last to 1615

recipes/mysterymaster/build.sh, recipes/mysterymaster/meta.yaml, recipes/mysterymaster/run_test.sh
=> Add mysterymaster

recipes/perl-html-tidy/build.sh, recipes/perl-html-tidy/meta.yaml, recipes/tidyp/build.sh, recipes/tidyp/meta.yaml
=> perl-html-tidy: add linux-aarch64

recipes/muat/meta.yaml
New Features:
- fix bugs GEL somagg
- add benchmark
=> Update muat to version 0.1.6

recipes/gb-io/meta.yaml
This PR updates `gb-io` to `v0.3.5`. The build system was changed from `setuptools` to `maturin` in `v0.3.4`.
---- …
=> Update `gb-io` to `v0.3.5`.

recipes/starfish/meta.yaml
=> Update starfish to v0.3.2

recipes/bioconductor-dropletutils/meta.yaml
=> bioconductor-dropletutils: add linux-aarch64

recipes/bioconductor-ncdfflow/meta.yaml
=> bioconductor-ncdfflow: add linux-aarch64

recipes/bioconductor-oligo/meta.yaml
=> bioconductor-oligo: add linux-aarch64

recipes/bioconductor-cn.mops/meta.yaml
=> bioconductor-cn.mops: add linux-aarch64

recipes/bioconductor-titancna/meta.yaml
=> bioconductor-titancna: add linux-aarch64

recipes/deepvariant/meta.yaml
According to the [main page](https://github.com/google/deepvariant?tab=readme-ov-file#prerequisites), it supports `python 3.10`.
---- …
=> build: Bump python version

recipes/bioconductor-aseb/meta.yaml
=> bioconductor-aseb: add linux-aarch64

recipes/bioconductor-tweedeseq/meta.yaml
=> bioconductor-tweedeseq: add linux-aarch64

recipes/bioconductor-beaddatapackr/meta.yaml
=> bioconductor-beaddatapackr: add linux-aarch64

recipes/bioconductor-deepsnv/meta.yaml
=> bioconductor-deepsnv: add linux-aarch64

recipes/bioconductor-rgadem/meta.yaml
=> bioconductor-rgadem: add linux-aarch64

recipes/snakemake-interface-logger-plugins/meta.yaml
This adds a recipe for the snakemake-interface-logger-plugins package.
---- …
=> add: snakemake-interface-logger-plugins

recipes/binette/meta.yaml
This PR updates Binette recipe to version 1.1.1
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table> …
=> bump binette to v1.1.1

recipes/mi-pimento/meta.yaml
PIMENTO is a toolkit that allows for automatic primer inference in FASTQ sequencing reads using a dual-strategy approach.
---- …
=> Add PIMENTO to bioconda

recipes/fastga/build.sh, recipes/fastga/meta.yaml
=> Add FastGA

recipes/spacedust/3e436173321a2d0365a08bfb3b281108ed9ad414.patch, recipes/spacedust/build.sh, recipes/spacedust/meta.yaml
=> Add spacedust

recipes/pypolca/meta.yaml
=> bump freebayes dependency of pypolca  to v1.3.9

recipes/isotools/meta.yaml
Add recipe for [IsoTools](https://isotools.readthedocs.io/en/latest/), a Python library for long read transcriptome sequencing analysis, by Matthias Lienhard et al.
---- …
=> Add isotools 0.3.4

recipes/hmftools-orange/meta.yaml
=> Update hmftools-orange to v3.8.0

recipes/corona_lineage_dynamics/meta.yaml
The codes in the GitHub repository of the code is updated.
---- …
=> Update corona_lineage_dynamics to version 0.1.7

recipes/bcftools-liftover-plugin/build.sh, recipes/bcftools-liftover-plugin/conda_build_config.yaml, recipes/bcftools-liftover-plugin/meta.yaml
Add `bcftools +liftover` plugin from [this repository](https://github.com/freeseek/score). The recipe mirrors the structure of recipes/bcftools-gtc2vcf-plugin, from the same author. 
---- …
=> Add bcftools +liftover

recipes/alientrimmer/alientrimmer.sh, recipes/alientrimmer/build.sh, recipes/alientrimmer/meta.yaml
Add a recipe for the [AlienTrimmer](https://gitlab.pasteur.fr/GIPhy/AlienTrimmer) tool.
=> Add AlienTrimmer

recipes/bcftools-gtc2vcf-plugin/build.sh, recipes/bcftools-gtc2vcf-plugin/conda_build_config.yaml, recipes/bcftools-gtc2vcf-plugin/meta.yaml
- bcftools-gtc2vcf-plugin builds against bcftools' code base, and was last build against 1.19, so is two releases out of date
- plugin author has posted updated plugin utilities bundled into the gtc2vcf project; those are now packaged here as `+BAFregress` and `+idat2gtc`
---- …
=> Update bcftools-gtc2vcf-plugin for new content and bcftools 1.21

recipes/fastcov/build.sh, recipes/fastcov/meta.yaml
This pullrequest adds fastcov to bioconda. Fastcov is a simple tool to quickly creat coverage plots from indexed bam files.
---- …
=> add fastcov

recipes/graphembed/meta.yaml
We updated dependencies for this release and some minor bug fix.
---- …
=> Update graphembed v0.1.5

recipes/earlgrey/meta.yaml
- change to latest RepeatMasker that works with Dfam 3.9
---- …
=> Update meta.yaml for Earl Grey v6.0.0

recipes/lexicmap/build.sh, recipes/lexicmap/meta.yaml
This version is compatible with indexes created by previous versions (requires a one-time, automatic preprocessing),
but rebuilding the index is recommended for more accurate results on short queries (<500bp).
However, indexes created by this version are not compatible with previous versions when the number of batches is <= 512.
- `lexicmap index`:
- **Change default option values to bring a higher sensitivity for short (<=500, especially <=250) queries,
faster indexing speed, and faster seed-matching speed<s>, at a cost of slightly larger index</s>**.
- `-m/--masks`: 40,000 -> 20,000. 
40k is unnecessary especially for small genomes, where seeds would be very crowded,
with a big proportion of seed distance being between 0-50 bp.
- `-D/--seed-max-desert`: …
=> Update LexicMap to v0.6.0

recipes/spacerextractor/meta.yaml
This is a PR that adds a new tool, spacerextractor, designed to extract CRISPR spacers from metagenome reads at scale. Source code is available at https://code.jgi.doe.gov/SRoux/spacerextractor
----
=> Add spacerextractor

recipes/psauron/meta.yaml
=> Add PSAURON

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.27

recipes/commec/meta.yaml
Small update to meta.yaml to include extra identifier and container information.
---- …
=> commec meta.yaml meta data patch

recipes/slivar/meta.yaml
=> slivar: add linux-aarch64

recipes/r-signac/meta.yaml
=> r-signac: add linux-aarch64

recipes/treesapp/meta.yaml
=> treesapp: add linux-aarch64

recipes/yleaf/build.sh, recipes/yleaf/conda_build_config.yaml, recipes/yleaf/meta.yaml
Add recipe for Yleaf human Y-chromosome haplotyping. The current version of Yleaf as of recipe creation #54887 is 3.2.1 (March 2024).
A. Ralf, et al., Yleaf: software for human Y-chromosomal haplogroup inference from next generation sequencing data (2018).
https://academic.oup.com/mbe/article/35/5/1291/4922696
https://github.com/genid/Yleaf
----
* PRs require reviews prior to being …
=> Add Yleaf @3.2.1
