bioconda/bioconda-recipes

recipes/genmod/meta.yaml
Autobump is failing: https://github.com/bioconda/bioconda-recipes/pull/54783
---- …
=> Update genmod recipe

recipes/scanpy-cli/meta.yaml
scanpy-cli is a python package that should make scanpy more easily accessible in nextflow pipelines
----
Conda is able …
=> Add scanpy-cli recipe

recipes/genotypy/meta.yaml
This adds a recipe for genotypy 0.3.3.
It is a python tool to detect 'genomic barcodes' inserted at specific positions from sequencing data.
---- …
=> add genotypy 0.3.3

recipes/magneto/meta.yaml
Error with snakemake version 7.32.4 if python version is >3.12
---- …
=> Update Magneto meta.yaml

recipes/perl-namespace-autoclean/meta.yaml
=> perl-namespace-autoclean: add linux-aarch64

recipes/hmftools-linx/meta.yaml
=> Update hmftools-linx to v2.0.3

recipes/svtopovz/meta.yaml
Version bump for svtopoz with updated dependencies since the bot couldn't update them
---- …
=> Update svtopovz to v0.2.0

recipes/ncbi-datasets-pyclient/meta.yaml
This PR adds a new recipe for the ncbi-datasets-pyclient library.
---- …
=> Add ncbi-datasets-pyclient

recipes/atlas/meta.yaml
=> Update atlas to 2.0.0-rc.9

recipes/aliceasm/LICENSE, recipes/aliceasm/build.sh, recipes/aliceasm/meta.yaml
=> Add aliceasm

recipes/ngsfetch/meta.yaml
Add a recipe of [ngsfetch](https://github.com/NaotoKubota/ngsfetch), a utility to retrieve fastq files with [ffq](https://github.com/pachterlab/ffq) and [aria2](https://aria2.github.io/). It is designed to be fast and efficient, allowing you to download large datasets quickly and easily.
---- …
=> Add ngsfetch recipe

recipes/lexicmap/meta.yaml
- `lexicmap search`:
- Fix the program hang in the debug mode when no chaining result is returned.
- `lexicmap version`:
- Do not show commit hash by default.
---- …
=> Update LexicMap to v0.6.1

recipes/freyja/meta.yaml
Freyja demix and boot subcommands fail when installing with bioconda because of pyarrow being in a lowe version than required. This PR updates minimum pyarrow version required for this modules to work.
----
* Please post …
=> fix freyja recipe with required minimum version for pyarrow

recipes/ampligone/meta.yaml
Updated the AmpliGone recipe for version 2.0.1
Includes changes to the dependencies, entry-points, and recipe-maintainers list. 
---- …
=> Update AmpliGone recipe for version 2.0.1

recipes/eva-sub-cli/meta.yaml
Update missing dependency in eva-sub-cli  
Supersedes #55013
---- …
=> Update eva-sub-cli to v0.4.6

recipes/stare-abc/meta.yaml
Edit the yaml to include run_exports after autobump failed for the v1.0.5 upate.
---- …
=> Update stare-abc yaml

recipes/frogs/4.2.0/build.sh, recipes/frogs/4.2.0/meta.yaml, recipes/frogs/meta.yaml
=> update FROGS : create intermediate release 4.2.0

recipes/sra-tools/meta.yaml
=> update sra-tools to 3.2.1

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.28

recipes/stacks/meta.yaml
=> stacks: add linux-aarch64

recipes/phyloacc/meta.yaml, recipes/phyloacc/run_test.sh
This is an edit to the [auto-generated PR](https://github.com/bioconda/bioconda-recipes/pull/54895) that failed.
The problem may have been a new dependency needed (mkl). I'm adding this to re-try the build.
----
* Please post …
=> Update phyloacc to 2.4.3

recipes/el_gato/meta.yaml
=> Update el_gato version 1.21.2

recipes/yleaf-pipelines/build.sh, recipes/yleaf-pipelines/meta.yaml
This is a version of Yleaf that has improvements designed to make it
more modular and easily integrated into existing pipelines. This is released at 3.3.0.
---- …
=> Add Yleaf-pipelines at 3.3.0

recipes/pantax/build.sh, recipes/pantax/meta.yaml
=> Update pantax to 1.2.0

recipes/ogtfinder/meta.yaml
With this pull request, I want to add OGTFinder to Bioconda. OGTFinder is a command line tool for optimal growth temperature prediction of prokaryotes using proteome-derived features.
---- …
=> Add OGTFinder

recipes/dysgu/meta.yaml
Added superintervals package to host
---- …
=> Update dysgu recipe

recipes/pysctransform/meta.yaml
adding [pySCTransform](https://github.com/saketkc/pySCTransform.git) by @saketkc
=> add pysctransform

recipes/genome2tree/meta.yaml
- I read the [Bioconda guidelines](https://bioconda.github.io/guidelines.html)
- This PR adds a new recipe (no version bumps)
- No dependencies need to be added to bioconda
- Tested locally with `conda build recipes/genome2tree`
A pipeline to build phylogenetic trees from genome comparisons
=> Add genome2tree v1.0.0

recipes/tirmite/meta.yaml
Manual bump
removes tsplit entrypoints
---- …
=> Update: TIRmite

recipes/elastic-blast/meta.yaml
This pull request updates ElasticBLAST to version 1.4.0
=> Update elastic-blast to 1.4.0

recipes/svync/meta.yaml
=> Svync v0.2.0

recipes/hisat-3n/build.sh, recipes/hisat-3n/meta.yaml, recipes/hisat-3n/simde-mr-c.patch
=> Add hisat-3n

recipes/pilea/meta.yaml
=> update dependencies of recipe pilea

recipes/hictk/build.sh, recipes/hictk/conanfile.Dockerfile.py.patch, recipes/hictk/meta.yaml, recipes/hictk/run_test.sh
Add v2.1.0.
Supersedes https://github.com/bioconda/bioconda-recipes/pull/55027, https://github.com/bioconda/bioconda-recipes/pull/55164, and https://github.com/bioconda/bioconda-recipes/pull/55166.
---- …
=> Update hictk to v2.1.0

recipes/cawlign/build.sh, recipes/cawlign/meta.yaml
Adding a recipe for https://github.com/veg/cawlign, a codon-aware alignment tool
---- …
=> Add cawlign recipe

recipes/mpralib/meta.yaml
Initial commit of MPRAlib a library to analyse, filter and plot MPRA count data.  (Massive Parallel Reporter Assays)
---- …
=> Add MPRAlib

recipes/mimi/meta.yaml
=> install_mimi_1.0.0

recipes/last/meta.yaml
=> Update last to 1639

recipes/ovrlpy/meta.yaml
Add new recipe for ovrlpy package
@sebastiantiesmeyer
---- …
=> Add ovrlpy

recipes/kma/LICENSE, recipes/kma/build.sh, recipes/kma/meta.yaml
=> Update kma to 1.5.0

recipes/mypmfs_py/meta.yaml
Added recipe for MyPMFs_py package which generates statistical potentials for user-inputted pdb sets and scores proteins based generated statistical potentials. Also includes batch download functionality from the protein databank. …
=> Add mypmfs_py package

recipes/gci/build.sh, recipes/gci/meta.yaml
Adding a recipe for https://github.com/yeeus/GCI, a genome assembly QC tool
---- …
=> Add recipe for GCI 

recipes/tooldistillator/meta.yaml
Update to new version
[tooldistillator](https://bioconda.github.io/recipes/tooldistillator/README.html?highlight=tooldistillator#package-package%20'tooldistillator'): 0.9.1 → 0.9.2
Thanks :smiley:
=> Update ToolDistillator from 0.9.1 to 0.9.2

recipes/fusioncatcher/meta.yaml
This PR adds `wget` since it is needed by `fusioncatcher-build.py` to download all the references correctly
----
Conda …
=> Add `wget` to fusioncatcher dependencies

recipes/kbo-cli/meta.yaml
=> Update kbo-cli to v0.2.1.

recipes/ganon/meta.yaml
=> Update ganon to 2.1.1

recipes/fastqtk/meta.yaml
=> fastqtk: add linux-aarch64

recipes/vuegen/meta.yaml
Update  dependencies for vuegen v0.3.2
---- …
=> ➕ Update  dependencies for vuegen v0.3.2

recipes/amulety/meta.yaml
=> Add amulety recipe

recipes/cvanmf/meta.yaml
Add recipe for python package cvanmf, providing implementation of method used for analysis of gut microbiome composition
---- …
=> Add cvanmf recipe

recipes/eider/build.sh, recipes/eider/meta.yaml
=> Add eider recipe

recipes/seqscreen/meta.yaml
=> Update to v4.5

recipes/sentieon/meta.yaml, recipes/sentieon/sentieon_symlinks.patch
=> Update Sentieon recipe to 202503

recipes/dysgu/build.sh, recipes/dysgu/meta.yaml
=> Update recipe for dysgu

recipes/tmscoring/meta.yaml
=> Add tmscoring

recipes/srnamapper/build.sh, recipes/srnamapper/meta.yaml
Update srnaMapper to v1.0.12.
---- …
=> Update srnaMapper to new version

recipes/mimick/meta.yaml, recipes/visor/meta.yaml
This PR adds a recipe for the Mimick linked-read sequencing simulator (formerly XENIA module of VISOR, which is hosted on BioConda)
---- …
=> Add mimick recipe

recipes/searchgui/meta.yaml, recipes/searchgui/searchgui.py
=> Update searchgui to 4.3.14

recipes/fusion-report/meta.yaml, recipes/pybwa/meta.yaml
=> Update fusionreport to 4.0.0

recipes/gmap/meta.yaml
=> Rebuild gmap

recipes/libcifpp/build.sh, recipes/libcifpp/meta.yaml
=> Rebuild libcifpp

recipes/bioconductor-rhtslib/meta.yaml, recipes/bioconductor-rsamtools/meta.yaml
=> osx-arm64 build for bioconductor-rhtslib and bioconductor-rsamtools

recipes/bioconductor-gosemsim/meta.yaml
=> add osx-arm64, bump build number

recipes/bioconductor-s4arrays/meta.yaml, recipes/bioconductor-sparsearray/meta.yaml
=> osx-arm64 for bioconductor-sparsearray and bioconductor-s4arrays

recipes/deepdetails/meta.yaml
Adding DeepDETAILS ver 0.0.1rc1 to bioconda
=> Add DeepDETAILS

recipes/dbcan/meta.yaml
=> Update dbcan to v5.0.3

recipes/muat/meta.yaml
Fix bugs:
- checkpoint compatibility
- resampling replacement
- relative path handler
- download link
- easier execution
=> Update muat to version 0.1.10

recipes/mysterymaster/meta.yaml
=> Update mysterymaster meta.yaml

recipes/cdskit/build.sh, recipes/cdskit/meta.yaml
This PR adds a Bioconda recipe for cdskit, a Python package to process protein-coding DNA sequences.
CDSKIT is a Python program that processes DNA sequences, especially protein-coding sequences. Many functions of this program are designed to handle DNA sequences using codons (sets of three nucleotides) as the unit, and therefore, edits the coding sequences without causing a frameshift. All sequence formats supported by Biopython are available in this tool for both inputs and outputs.
---- …
=> Add cdskit

recipes/kmer2stats/meta.yaml
=> Add kmer2stats recipe

recipes/bioconductor-genomicalignments/meta.yaml, recipes/bioconductor-rtracklayer/meta.yaml, recipes/r-restfulr/meta.yaml
=> add osx builds for rtracklayer, genomicalignments

recipes/bioconductor-deseq2/meta.yaml
=> add osx-arm64 for bioconductor-deseq2

recipes/raxml-ng/build.sh, recipes/raxml-ng/meta.yaml
=> Build raxml-ng for osx-arm64

recipes/ervmancer/meta.yaml
Adding initial release of package ervmancer - v0.0.1
---- …
=> Add ervmancer

recipes/sfld/meta.yaml
=> sfld: add linux-aarch64

recipes/paraclu/meta.yaml
=> paraclu: add linux-aarch64

recipes/r-floral/meta.yaml
Adding r-floral from CRAN
---- …
=> Add r-floral

recipes/delly/build.sh, recipes/delly/meta.yaml
=> delly: add arm64 build

recipes/mimick/meta.yaml
This PR adds `htslib` to the runtime dependencies and increments the build number to `1`. Otherwise, everything else remains unchanged.
---- …
=> Update - add htslib to the run deps

recipes/postmaster/meta.yaml
=> Rebuild postmaster recipe

recipes/lastz/build.sh, recipes/lastz/makefile.patch, recipes/lastz/meta.yaml
=> Rebuild lastz recipe

recipes/aster/build.sh, recipes/aster/meta.yaml
=> aster: add arm64 build

recipes/muat/meta.yaml
Fix bugs:
- WES prediction
- checkpoint deprecation
=> Update muat to version 0.1.11

recipes/libcarna/build.sh, recipes/libcarna/meta.yaml, recipes/libcarna/run_test.sh, recipes/libcarna/test/CMakeLists.txt, recipes/libcarna/test/test.cpp
Source repo: https://github.com/kostrykin/Carna
---- …
=> Add libcarna

recipes/scoring-matrices/meta.yaml
=> Rebuild scoring-matrices recipe

build-fail-blacklist, recipes/gemma/build.sh, recipes/gemma/meta.yaml
This PR updates GEMMA, makes sure that it builds, and fixes lints.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Also, the bot watches for …
=> Update GEMMA to 0.98.5, fix build issues

recipes/codingquarry/meta.yaml
=> Update: Codingquarry add osx-arm64

recipes/gtdbtk/download-db.sh, recipes/gtdbtk/meta.yaml, recipes/gtdbtk/post-link.sh
=> Update GTDB-Tk version to 2.4.1 and external data requirements

recipes/emboss/meta.yaml
=> Update: Emboss add osx-arm64

recipes/hictkpy/meta.yaml
Pin NumPy to  v2+.
This is required to be able to solve environments for packages such as https://github.com/bioconda/bioconda-recipes/pull/55424.
---- …
=> hictkpy: pin numpy version

recipes/esme/conda_build_config.yaml, recipes/esme/meta.yaml
This PR adds MVAPICH version 4.0 support to ESME which, among other things, brings:
• Support for both OFI and UCX 
• Support for 
– Major CPUs (x86-Intel, x86-AMD, and ARM) 
– Major GPUs (NVIDIA, AMD, and Intel) 
– Major HPC interconnects (InfiniBand, Omni-Path, ROCE, Slingshot, OPX, Ethernet/iWARP)
• Support for on-the-fly compression (Allgather, Alltoall, Allreduce, and Reduce_Scatter)
• Optimized designs for converged software stack with next-generation workflows.
----
* New recipes not directly relevant to the biological sciences need to …
=> Add MVAPICH4.0 to ESME

recipes/stripepy-hic/meta.yaml, recipes/stripepy-hic/run_test.sh
Supersedes https://github.com/bioconda/bioconda-recipes/pull/55423.
---- …
=> Update stripepy-hic to 1.0.0

recipes/usalign/meta.yaml
Updated usalign to 20241201 
---- …
=> Update usalign to 20241201

recipes/bioconductor-dada2/meta.yaml
=> bioconductor-dada2: add osx-arm64

recipes/bioconductor-rhdf5filters/meta.yaml
=> bioconductor-rhdf5filters: add osx-arm64

recipes/bioconductor-beachmat/meta.yaml
=> bioconductor-beachmat: add osx-arm64

recipes/bioconductor-shortread/meta.yaml
=> bioconductor-shortread: add osx-arm64

recipes/dmox/meta.yaml
Seems that bioconda bot did not pick my release up. Is it because it's hosted at our lab (gitlab.mbb.cnrs.fr)?
=> Update dmox to 0.2.0

recipes/bioconductor-rhdf5/meta.yaml
=> bioconductor-rhdf5: add osx-arm64

recipes/hmftools-teal/build.sh, recipes/hmftools-teal/meta.yaml, recipes/hmftools-teal/teal.sh
Add recipe for hmftools-teal 1.3.3
---- …
=> Add recipe for hmftools-teal 1.3.3

recipes/hmftools-cider/build.sh, recipes/hmftools-cider/cider.sh, recipes/hmftools-cider/meta.yaml
Add recipe for hmftools-cider 1.0.3
---- …
=> Add recipe for hmftools-cider 1.0.3

recipes/ervmancer/meta.yaml
Updating ervmancer package to v0.0.2 to include small dictionary files for conda package.
---- …
=> Update ervmancer package to 0.0.2

recipes/cogclassifier/meta.yaml, recipes/cogclassifier/run_test.sh
Update cogclassifier to v2.0.0.
---- …
=> Update cogclassifier to 2.0.0

recipes/recon/build.sh, recipes/recon/meta.yaml
=> Update Recon add osx-arm64

recipes/gmap/build.sh, recipes/gmap/meta.yaml
=> Update gmap to 2025-04-18

recipes/nbitk/meta.yaml
This update of nbitk to v0.5.2 has fewer dependencies, making it easier to install and avoid dependency hell. However, the onus is now on users to install separately.
---- …
=> Update nbitk to v0.5.2

recipes/conservation/meta.yaml
This is an initial release of conservation. Conservation is a Python package for evolutionary conservation analysis at the codon and amino acid level. It supports comparative analysis using Pfam domain sequences and CDS datasets across multiple species.
---- …
=> initial release of conservation

recipes/vireosnp/meta.yaml
=> Update vireosnp to 0.5.9

recipes/cligv/meta.yaml
This is an initial release of clIGV - a command line Interactive Genome Viewer. It allows quickly browsing genomes and supports viewing alignments (bam) and variants (vcf) right in the terminal.
---- …
=> Add cligv: command line Interactive Genome Viewer

recipes/panman/CMakeLists.txt, recipes/panman/build.sh, recipes/panman/meta.yaml
Conda package for [PanMAN](https://github.com/TurakhiaLab/panman), currently it contains one software called _panmanUtils_.
PanMAN or Pangenome Mutation-Annotated Network is a novel data representation for pangenomes that improves both representative power and storage efficiency. _panmanUtils_ includes multiple algorithms to construct PanMANs and to support various functionalities to modify and extract useful information from PanMANs.
Please refer to [PanMAN wiki](https://turakhia.ucsd.edu/panman/index.html) for more details.
=> Add PanMAN v0.1.2

recipes/prooverlap/meta.yaml
=> Add prooverlap

recipes/r-easypar/bld.bat, recipes/r-easypar/build.sh, recipes/r-easypar/meta.yaml
Pull request for easypar package
---- …
=> Add r-easypar

recipes/wakhan/meta.yaml
Added a numpy versioning fix for wakhan
=> Fixed wakhan numpy version

recipes/mimick/meta.yaml
remove biopython dep and increment the build number
---- …
=> Update mimick build

recipes/foldmason/meta.yaml
Bumping FoldMason version to release 3-954d202
---- …
=> bump foldmason version to 3-954d202

recipes/bellavista/meta.yaml
pyqt is required by napari.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
<tr>
</tr>
</table>
Also, the bot watches for comments from non-members that include …
=> bellavista, add pyqt

recipes/hyperloglog/LICENSE, recipes/hyperloglog/meta.yaml
=> Add recipe for hyperloglog v0.0.14

recipes/spacerplacer/build.sh, recipes/spacerplacer/meta.yaml
=> Add spacerplacer

recipes/minipileup/build.sh, recipes/minipileup/meta.yaml
This PR will add minipilup. The license is not clear, upstream issue is created.
---- …
=> add minipileup

recipes/vuegen/meta.yaml
Update python version for vuegen because of issues with strenum library in versions <=3.11
---- …
=> 📌 Update python version for vuegen

recipes/melon/meta.yaml
=> add dependency for recipe melon

recipes/barcode-validator/meta.yaml
Updated barcode_validator to v2.0.1
---- …
=> Updated barcode_validator to v2.0.1

recipes/nbitk/meta.yaml
=> Update nbitk to v0.5.3

recipes/phlame/LICENSE.md, recipes/phlame/meta.yaml
This PR adds phlame v.1.0.8 for strain-level profiling of metagenomes
I've tried a couple times to do this right so any help on passing review would be appreciated!
---- …
=> Add phlame v.1.0.8

recipes/freebayes/build.sh, recipes/freebayes/meta.yaml
=> Rebuild freebayes recipe

recipes/taxonkit/build.sh, recipes/taxonkit/meta.yaml
- [TaxonKit v0.20.0](https://github.com/shenwei356/taxonkit/releases/tag/v0.20.0) [![Github Releases (by Release)](https://img.shields.io/github/downloads/shenwei356/taxonkit/v0.20.0/total.svg)](https://github.com/shenwei356/taxonkit/releases/tag/v0.20.0)
This version is mainly for maintaining compatibility with NCBI's recent changes([1](https://ncbiinsights.ncbi.nlm.nih.gov/2025/02/27/new-ranks-ncbi-taxonomy/), [2](https://ncbiinsights.ncbi.nlm.nih.gov/2025/04/25/ncbi-taxonomy-updates-virus-classification-april-2025/)).    
**Please remove the `ranks.txt` file in `~/.taxonkit/` or other directories containing taxdump files (nodes.dmp)**.
- `taxonkit reformat`:
- Tried to make it compatible with NCBI's recent changes but failed.
- **Update doc to recommend …
=> Update TaxonKit to v0.20.0

recipes/gambitcore/meta.yaml
Add *gambitcore*
>  A tool for bacterial species identification and assembly quality assessment. It 
evaluates assemblies by comparing their k-mer profiles against species-specific 
core genome references, providing both taxonomic identification and assembly 
completeness metrics.
----
* PRs require reviews prior to being merged. Once your PR is passing tests and ready to be merged, …
=> Add gambitcore

recipes/crispritz/meta.yaml
=> Crispritz: add linux-aarch64

recipes/savvy/meta.yaml
=> savvy: add linux-aarch64

recipes/superintervals/meta.yaml
=> Added - osx-arm64 to superintervals build

recipes/skder/meta.yaml
=> Update skDER build for osx-arm64 support

recipes/cagecleaner/meta.yaml
=> Add CAGEcleaner to Bioconda

recipes/pasta/build.sh, recipes/pasta/fix_tooldir.patch, recipes/pasta/meta.yaml, recipes/pasta/mpstart.patch
=> Rebuild pasta on arm64

recipes/stripepy-hic/meta.yaml, recipes/stripepy-hic/run_test.sh
=> Update stripepy-hic to 1.1.0

recipes/barcode-validator/meta.yaml
added ete4 run requirement, incremented build number
---- …
=> Update barcode-validator v2.0.1

recipes/antismash/meta.yaml
=> Update antismash to 8.0.0

recipes/busco/build.sh, recipes/busco/meta.yaml
=> Rebuild busco recipe

recipes/amalgkit/meta.yaml
AMALGKIT is a toolkit to integrate RNA-seq data from the NCBI SRA database and from private fastq files to generate unbiased cross-species transcript abundance dataset for a large-scale evolutionary gene expression analysis.
---- …
=> Add Bioconda recipe for amalgkit

recipes/mogaaap/LICENSE, recipes/mogaaap/meta.yaml
Adding bioconda recipe for MoGAAAP with this PR
=> Add recipe for MoGAAAP

recipes/rdeval/meta.yaml
update rdeval to version 0.0.7
---- …
=> updating rdeval

recipes/pipits/meta.yaml
=> Update PIPITS to 4.0 with changes to dependencies

recipes/aniclustermap/meta.yaml, recipes/aniclustermap/run_test.sh
Update aniclustermap to v2.0.1
---- …
=> Update aniclustermap to 2.0.1

recipes/frogs/meta.yaml
=> Update FROGS v5.0.2

recipes/pyani-plus/meta.yaml
Packages pyANI-plus, an application and Python module for whole-genome classification of microbes using Average Nucleotide Identity and similar methods. It is a reimplemented version of pyani (already in BioConda) with support for additional schedulers and methods.
The dependency minimum versions are as per upstream.
This is also on PyPI, https://pypi.org/project/pyani-plus/
----
* …
=> Add pyani-plus

recipes/kernel_density_plots/build.sh, recipes/kernel_density_plots/meta.yaml
=> kernel_density_plots version 0.1

recipes/subread/build.sh, recipes/subread/meta.yaml
=> Update subread to v2.1.1

recipes/kractor/build.sh, recipes/kractor/meta.yaml
Add recipie for [kractor](https://github.com/Sam-Sims/kractor)
---- …
=> Add kractor v1.0.0

recipes/tomm40_wgs/LICENSE, recipes/tomm40_wgs/build.sh, recipes/tomm40_wgs/licenses/ExpansionHunter-LICENCE, recipes/tomm40_wgs/licenses/GangSTR-LICENCE, recipes/tomm40_wgs/licenses/HipSTR-LICENCE, recipes/tomm40_wgs/licenses/TOMM40_WGS-LICENSE-INFO, recipes/tomm40_wgs/meta.yaml
=> recipe for tomm40_wgs

recipes/bbmap/meta.yaml
=> Update bbmap to v39.24

recipes/revbayes/build.sh, recipes/revbayes/meta.yaml
=> Rebuild revbayes recipe

recipes/bwameth/meta.yaml
Add bwa-mem2 dependency as specified in [README](https://github.com/brentp/bwa-meth#dependencies).
----
Conda is able …
=> Update bwa-mem2 dependency

recipes/flye/meta.yaml
Updating to Flye 2.9.6 (not sure why autobump is not working)
---- …
=> Update flye 2.9.6

recipes/bwapy/meta.yaml
=> bwapy: add linux-aarch64

recipes/sunbeamlib/meta.yaml
=> Add sunbeamlib recipe

recipes/quota_anchor/meta.yaml
=>  update version 1.0.0rc

recipes/bioconductor-metmashr/meta.yaml
=> Rebuild bioconductor-metmashr v1.0.0 and include suggests

recipes/flair/meta.yaml
=> Update FLAIR v2.2.0 release

recipes/parasail/build.sh, recipes/parasail/meta.yaml
This pull request adds a new recipe for building and packaging the `parasail` library, a SIMD C library for pairwise sequence alignment. The changes include the addition of a build script and a metadata file to define the package's configuration and dependencies.
* Added `recipes/parasail/build.sh` to handle the build process. The script includes platform-specific modifications for Linux, runs `autoreconf`, configures the build with necessary flags, and completes the build, testing, and installation steps.
----
* New recipes not directly …
=> Adding parasail v2.6.2

recipes/biobb_common/meta.yaml
=> [biobb_common] update 5.0.1

recipes/pyhmmer/meta.yaml
=> Update `pyhmmer` to pin `psutil` and `cython` version

build-fail-blacklist, recipes/pixelator/meta.yaml
Seems to be causing the nightly build on Linux to fail.
---- …
=> temporarily add pixelator to skiplist

recipes/argo/meta.yaml
=> fix dependency for recipe Argo

recipes/taxor/build.sh, recipes/taxor/meta.yaml
Minor bug fix in `taxor profile` occuring when calculating abundances on higher taxonomic ranks
---- …
=> update taxor version to 0.2.1

recipes/quota_anchor/meta.yaml
=> Update quota_anchor to 1.0.0

recipes/snap-aligner/0001-Makefile.patch, recipes/snap-aligner/0002-snap-aligner-aarch64.patch, recipes/snap-aligner/0003-header.patches, recipes/snap-aligner/0004-main.cpp.patch, recipes/snap-aligner/build.sh, recipes/snap-aligner/meta.yaml
=> Rebuild snap-aligner

recipes/bbmap/meta.yaml
=> Update bbmap to v39.25

recipes/gmap/meta.yaml
=> Update gmap to 2025-04-19

recipes/vg/meta.yaml
This updates vg to version 1.65.0
---- …
=> Update vg to v1.65.0

recipes/biophi/meta.yaml
Bump biophi sapiens dependency
=> Bump biophi sapiens dependency

recipes/eukulele/meta.yaml
Update `EUKulele` to v2.1.2.
---- …
=> Update EUKulele to v2.1.2

recipes/r-dndscv/build.sh, recipes/r-dndscv/meta.yaml, recipes/r-mobster/build.sh, recipes/r-mobster/meta.yaml
This PR adds the R package MOBSTER, version 0.1.1. The source code is available here: https://github.com/caravagnalab/mobster.
---- …
=> Add r-mobster

recipes/gene-fetch/meta.yaml
Gene Fetch is a tool designed for high-throughput retrieval of nucleotide and protein sequences from NCBI databases. It enables researchers to efficiently obtain genomic sequences based on taxonomic and genomic criteria. The GitHub repository can be found at https://github.com/bge-barcoding/gene_fetch, and the PyPi package at https://pypi.org/project/gene-fetch/
----
* PRs require …
=> Add gene-fetch v1.0.9

recipes/cdskit/meta.yaml
Added information about cdskit's dependent packages.
---- …
=> Update cdskit to 0.14.4

recipes/muat/meta.yaml
Shorten the CLI command:
- Preprocessing to preprocess
- shorten preprocessed output files
- Benchmark to ensemble
=> Update muat to version 0.1.12

recipes/mysterymaster/meta.yaml
Bug fix when using the -n option with 96 bar codes and multi-threaded.
----
Conda is …
=> Updated meta.yaml

recipes/amalgkit/meta.yaml
We have updated the meta.yaml file, so we will submit another pull request. We apologize for the inconvenience and thank you for your cooperation.
---- …
=> Update: amalgkit 0.12.16 with full dependencies

recipes/cutesv-ol/build.sh, recipes/cutesv-ol/meta.yaml
=> Add recipe for cuteSV-OL

recipes/kanpig/build.sh, recipes/kanpig/meta.yaml
=> Add kanpig recipe

recipes/galaxy-files-full/meta.yaml
=> add galaxy-files-full

recipes/plassembler/meta.yaml
Update plassembler canu dependency to allow for > 2.2.
Tested build locally, no compatibility issues with plassembler=1.6.2 and canu=2.3
---- …
=> Update plassembler canu dependency >=2.2

recipes/openms-meta/meta.yaml
=> Update OpenMS to 3.4.0

recipes/biophi/meta.yaml
=> Use sapiens 1.1.0 in biophi

recipes/cpat/build.sh, recipes/cpat/meta.yaml
=> Rebuild cpat recipe

recipes/singlem/meta.yaml
=> Update singlem: Update to 0.19.0.

recipes/iow/build.sh, recipes/iow/meta.yaml
=> iow: add arm64 build

recipes/rad/build.sh, recipes/rad/meta.yaml
creating a pull request for adding rad, a read agnostic demultiplexer
---- …
=> Add rad v0.6.0 (new recipe)

recipes/blobtk/build.sh, recipes/blobtk/meta.yaml
=> Add blobtk v0.6.5 recipe

recipes/bwa/build.sh, recipes/bwa/meta.yaml
=> Rebuild bwa recipe

recipes/genomepy/meta.yaml
Fix for the MySQL error:
```
mysql.connector.errors.DatabaseError: 2059 (HY000): Authentication plugin 'mysql_native_password' cannot be loaded: /usr/lib/mysql/plugin/mysql_native_password.so: cannot open shared object file: No such file or directory
```
---- …
=> genomepy: fix mysql (again)

recipes/biophi/meta.yaml
=> Bump biophi to 1.0.11

recipes/r-ldweaver/meta.yaml
Attempt to fix the auto bump zlib not found error
---- …
=> LDWeaver v1.5.2

recipes/genotypy/meta.yaml
Update genotypy to 0.3.4: https://gitbio.ens-lyon.fr/LBMC/yvertlab/vortex/plasticity_mutation/colony_rnaseq_bioinformatics/genotypy/-/releases/0.3.4
---- …
=> Update genotypy to 0.3.4

recipes/dmox/meta.yaml
Updates `dmox` to version `0.2.1` and also skips the OSX build (for now) because of the unresolved `zlib-ng` issue in Rust compliation. (Will be fixed in the future)
---- …
=> Update dmox to 0.2.1

recipes/gbdraw/build.sh, recipes/gbdraw/meta.yaml
**Add gbdraw v0.1.0**
This pull request adds a new recipe for gbdraw v0.1.0, a genome diagram generation tool specialized for microbial genomes.
**Homepage**
https://github.com/satoshikawato/gbdraw
**License**
MIT
**Functionality**
Generates publication-quality genome diagrams from GenBank/EMBL/DDBJ-format annotated genomes. Outputs diagrams in SVG, PNG, PDF, EPS, and PS formats.
**Dependencies**
`Python ≥3.10`, `biopython`, `pandas`, `svgwrite`, `CairoSVG`, [`Liberation Fonts`](https://github.com/liberationfonts/liberation-fonts) (bundled; SIL Open Font_License 1.1
**Tests and validations**
Successfully built and linted using bioconda-utils lint and conda-build locally.
**Mainainer**
[satoshikawato](https://github.com/satoshikawato)
Please review and let me know if further adjustments …
=> Add recipe for gbdraw v0.1.0

recipes/fa-lint/build.sh, recipes/fa-lint/meta.yaml
Added fa-lint from https://github.com/GallVp/fa-lint
---- …
=> Added fa-lint

recipes/orthanq/meta.yaml
=> Update vg giraffe version

recipes/splitcode/build.sh, recipes/splitcode/meta.yaml
Update splitcode to add osx-arm64
---- …
=> Update splitcode to add osx-arm64

recipes/bioconda-repodata-patches/meta.yaml
Bump bioconda-repodata-patches version number, which I neglected to do in PR #56197.
---- …
=> Bump bioconda-repodata-patches version number

recipes/multiz/meta.yaml
I've added missing run dependencies.  The code uses the c system(3) function to call the following utilities:
- cat
- cp
- echo
- grep
- mv
- rm
- touch
All except grep are included in the coreutils package.
----
* Please post …
=> updating multiz

recipes/libcarna-python/build.sh, recipes/libcarna-python/meta.yaml
Add recipe for LibCarna-Python (mutually exclusive with https://github.com/bioconda/bioconda-recipes/pull/56187)
---- …
=> Add recipe for LibCarna-Python

recipes/gbdraw/meta.yaml
- No longer crashes when BLAST IDs differ from GenBank accessions, provided the file order matches.
- Embedded labels now align consistently between SVG and PNG outputs.
---- …
=> Update gbdraw to v0.1.1

recipes/meme/build.sh, recipes/meme/meta.yaml
=> Update meme to 5.5.8

recipes/vcflib/0001-CMakeLists.patch, recipes/vcflib/0002-CMakeLists.macos.patch, recipes/vcflib/build.sh, recipes/vcflib/meta.yaml
=> Update vcflib to v1.0.14

recipes/scxmatch/meta.yaml
Initial version of scXMatch, a tool that provides a statistical test that identifies global distribution shifts in single-cell data.
---- …
=> Add meta.yml for scxmatch

recipes/vsnp3/meta.yaml
=> vsnp3 version 3.29

recipes/pcaone/build.sh, recipes/pcaone/meta.yaml
=> fix pcaone recipe

recipes/longbow/meta.yaml
=> Update longbow to 2.3.1

recipes/longcallr/build.sh, recipes/longcallr/meta.yaml
Adds `longcallr`, a Rust-based tool with Python scripts for SNP and allele-specific expression analysis of long-read RNA-seq.
---- …
=> New longcallr

recipes/openms-meta/meta.yaml
=> Update OpenMS to 3.4.1

recipes/abnumber/meta.yaml
=> Bump abnumber to 0.4.4

recipes/radte/build.sh, recipes/radte/meta.yaml
**Package Name:** `radte`  
**Version:** 0.2.3  
**Summary:** Reconciliation-Assisted Divergence Time Estimation for gene families  
**Source:** https://github.com/kfuku52/radte
**Dependencies:**
- R (>= 3.5)
- bioconductor-treeio
- r-ape
- notung
- generax
This package was tested locally and conforms to Bioconda linting rules.
----
* PRs require reviews prior to being merged. Once …
=> Add radte 0.2.3 to bioconda

recipes/juicertools/build.sh, recipes/juicertools/juicer_tools.sh, recipes/juicertools/meta.yaml
Added JuicerTools from https://github.com/aidenlab/Juicebox
---- …
=> Added JuicerTools

recipes/treeswirl/build.sh, recipes/treeswirl/meta.yaml
=> TreeSwirl version 2

recipes/influx_si/meta.yaml
=> Update influx_si for r-nlsic >=1.1.0

recipes/masurca/build.sh, recipes/masurca/meta.yaml
=> Rebuild masurca recipe

recipes/metator/meta.yaml
=> Update metator to 1.3.10

recipes/bio2zarr/meta.yaml
Add myself and @tomwhite to maintainers to get our "bus count" above 1.
I assume you're ok with this @tomwhite?
=> Add maintainers to bio2zarr

recipes/orthologer/meta.yaml
Update to 3.7.1
* fixes in testing
* fixes related to OrthoDB API update
=> update to 3.7.1

recipes/bio2zarr/meta.yaml
Doing this manually because the upgrade to 0.1.6 has a few changes
---- …
=> Update bio2zarr to v0.1.6

recipes/ngs-disambiguate/meta.yaml
Restrict `bamtools` version, or `ngs-disambiguate` gives error:
```
ngs_disambiguate: error while loading shared libraries: libbamtools.so.2.5.2: cannot open shared object file: No such file or directory
```
---- …
=> Update bamtools dependency

recipes/vclust/meta.yaml
=> Update vclust to 1.3.1

build-fail-blacklist, recipes/ratt/build.sh, recipes/ratt/meta.yaml, recipes/ratt/ratt_home.patch
=> Update RATT to v1.1.0

recipes/hictk/conanfile.Dockerfile.py.patch, recipes/hictk/meta.yaml
Supersedes https://github.com/bioconda/bioconda-recipes/pull/56367.
---- …
=> Update hictk to 2.1.2

recipes/openstructure/conda.patch, recipes/openstructure/meta.yaml
This PR updates OpenStructure to 2.10.0.
---- …
=> Update OpenStructure to 2.10.0

recipes/spaln/0001-configure.patch, recipes/spaln/build.sh, recipes/spaln/meta.yaml
=> Update spaln to 3.0.7

recipes/ltr_harvest_parallel/build.sh, recipes/ltr_harvest_parallel/meta.yaml
=> fix LTR_HARVEST_parallel that still does not work as expected

recipes/bbmap/meta.yaml
=> Update bbmap to v39.26

recipes/myloasm/build.sh, recipes/myloasm/meta.yaml
Adding the myloasm long-read metagenome assembler. Github: https://github.com/bluenote-1577/myloasm/
----
Conda is able …
=> Add myloasm recipe

recipes/antismash/meta.yaml
=> Update antismash to 8.0.1

recipes/metabat2/build.sh, recipes/metabat2/cmake-htslib.patch, recipes/metabat2/cmake.patch, recipes/metabat2/meta.yaml
This PR updates the version of MetaBAT 2 to v2.18.
---- …
=> Update metabat2 to v2.18

recipes/mcl/build.sh, recipes/mcl/meta.yaml
=> mcl: add arm64 build

recipes/entrez-direct/build.sh, recipes/entrez-direct/meta.yaml
=> Update entrez-direct to v24.0

recipes/plinder/meta.yaml
Adding [PLINDER](https://github.com/plinder-org/plinder) v0.2.25
---- …
=> Adding PLINDER v0.2.25

recipes/phylopypruner/meta.yaml
=> Add recipe for phylopypruner v1.2.6

recipes/eva-sub-cli/build.sh, recipes/eva-sub-cli/meta.yaml
Supersede https://github.com/bioconda/bioconda-recipes/pull/56422
---- …
=> Update eva-sub-cli to 0.4.7

recipes/bioconductor-decipher/meta.yaml
=> Update bioconductor-decipher: add osx-arm64 build

recipes/hamronization/meta.yaml
- Fix recipe to use correct new pypi path
- Add correct build/arch flags
- Update to hAMRonization v1.9.1
=> Update hAMRonization recipe

recipes/plinder/meta.yaml
This pull request adds a new dependency to the `requirements` section of the `recipes/plinder/meta.yaml` file.
Dependency update:
* [`recipes/plinder/meta.yaml`](diffhunk://#diff-fa3e7caeb4550b0ef8d84cf721e3f9e7c38b3a2c84c3689063e67a996ab076f6R66): Added `mmpdb` to the list of requirements.
---- …
=> plinder: Add `mmpdb` to requirements

recipes/ligand-validation/meta.yaml
This pull request introduces a new recipe for the `ligand-validation` package, defining its metadata, build process, dependencies, and testing procedures.
* **Metadata definition**: The `meta.yaml` file specifies the package name (`ligand-validation`), version (`0.0.1`), source URL, and checksum for downloading the package. It also includes information about the license (`Apache-2.0`) and project details such as its homepage and documentation URL.
* **Build process**: The recipe outlines the build steps, such as using `pip` for installation, defining scripts (`bin/PDBValidation` and `bin/PDBValidationExtract`), and specifying Python as a noarch package.
* **Dependency management**: The `requirements` section lists host dependencies (`python`, `setuptools`, `pip`) and runtime dependencies …
=> Adding ligand-validation v0.0.1

recipes/hmftools-teal/meta.yaml
=> Update hmftools-teal to 1.3.5 and added samtools to requirements

recipes/r-liger/meta.yaml
Enabled linux-aarch64 in extra-platforms.
----
=> Add linux-aarch64 for r-liger

conda_build_config.yaml, recipes/r-cnaqc/build.sh, recipes/r-cnaqc/meta.yaml, recipes/r-peakpick/build.sh, recipes/r-peakpick/meta.yaml
This PR adds the R package CNAqc, version 1.1.1. The source code is available here: https://github.com/caravagnalab/CNAqc. …
=> Add r-cnaqc

recipes/tooldistillator/meta.yaml
Update to new version
[tooldistillator](https://bioconda.github.io/recipes/tooldistillator/README.html?highlight=tooldistillator#package-package%20'tooldistillator'): 0.9.2 → 0.9.3
Thanks :smiley:
=> Update ToolDistillator from 0.9.2 to 0.9.3

recipes/pytwobit/meta.yaml
=> Add recipe for pytwobit v0.3.1

recipes/longtrack/build.sh, recipes/longtrack/meta.yaml
Source: Downloaded from GitHub release LongTrack.v1.0.0.tar.gz (SHA256 verified)
Dependencies: Python 2.7, HTSeq >=0.5.3p9, bowtie2, numpy >=1.7.1, pandas >=0.7.3, matplotlib >=1.0.0, seaborn >=0.5.0
Build:
Copies LongTrack and all scripts in code/ into $PREFIX/bin/ with executable permissions
Test: Local conda build and conda create --use-local completed without errors; upon activation, LongTrack, import HTSeq, and bowtie --version all run successfully
Usage Example:
conda create -n longtrack -c bioconda longtrack
conda activate longtrack
LongTrack --test
----
* If this PR adds or updates a recipe, use "Add" or …
=> Add longtrack 1.0.0 recipe

recipes/r-tinc/build.sh, recipes/r-tinc/meta.yaml
Add TINC R package recipe
---- …
=> Add r-tinc recipe

conda_build_config.yaml
Deleted accidentally committed file in https://github.com/bioconda/bioconda-recipes/pull/55976
Ping @jmarshall @epruesse @vvvirgy
=> Deleted accidentally comitted file

recipes/bowtie2/build.sh, recipes/bowtie2/meta.yaml
=> Rebuild bowtie2 recipe

recipes/diamond/build.sh, recipes/diamond/meta.yaml
=> Rebuild diamond recipe

recipes/pretextsnapshot/meta.yaml
=> PretextSnapshot 0.0.5

recipes/augur/meta.yaml
This version also adds seqkit as a new dependency.
---- …
=> Update augur to 31.2.0

recipes/nbitk/meta.yaml
This update removes the dependency on ete4.
---- …
=> Update nbitk to 0.5.9

recipes/dapcy/meta.yaml
The post release on PyPI adds a missing dependency bed-reader in the pypi dist/wheel. The updated bioconda recipe also adds bio2zarr which was missing from 1.3.0 bioconda recipe (since it wasn't available on bioconda at that point yet).
---- …
=> Update dapcy to 1.3.0.post1

recipes/phynteny_transformer/meta.yaml
This PR adds `phynteny_transformer` to bioconda. Phynteny is a phage genome annotation tool that uses gene order information to predict unknown gene functions in bacteriophage genomes. 
----
* …
=> Add phynteny_transformer v0.1.2

recipes/augur/meta.yaml
=> Fix dependencies for augur to include referencing like the pip pkg

recipes/phylogenize/build.sh, recipes/phylogenize/meta.yaml
Updating phylogenize to v2.0-alpha version after a major overhaul of codebase and addition of new features.
----
Conda …
=> Update Phylogenize to v2.0-alpha

recipes/gfatools/0001-Makefile.patch, recipes/gfatools/0002-asm.c.patch, recipes/gfatools/build.sh, recipes/gfatools/conda_build_config.yaml, recipes/gfatools/meta.yaml
=> gfatools: add aarch64/arm64 builds

recipes/barcodeforge/meta.yaml
Adds barcodeforge tool, which generates pathogen-specific barcodes for the Freyja tool.
---- …
=> Add barcodeforge recipe

recipes/r-bpcells/build.sh, recipes/r-bpcells/meta.yaml, recipes/r-bpcells/patches/0001-fix-libhwy-config.patch
=> r-bpcells: add osx build

recipes/uniqsketch/0001-SequenceUtil.patch, recipes/uniqsketch/build.sh, recipes/uniqsketch/meta.yaml
Adding a bioconda recipe for [UniqSketch](https://github.com/amazon-science/uniqsketch)
---- …
=> Add uniqsketch

recipes/paragone/build.sh, recipes/paragone/meta.yaml
=> Rebuild paragone

recipes/pyvcf3/meta.yaml
=> Update pyvcf3 to v1.0.4

build-fail-blacklist, recipes/mapsplice/build.sh, recipes/mapsplice/conda_build_config.yaml, recipes/mapsplice/meta.yaml, recipes/mapsplice/patches/samtools.patch, recipes/mapsplice/patches/samtools_misc.patch
=> Rebuild mapsplice recipe

build-fail-blacklist, recipes/tagger/0001-makefile.patch, recipes/tagger/0002-tagger.patch, recipes/tagger/build.sh, recipes/tagger/meta.yaml
=> Rebuild tagger recipe

recipes/vcontact3/meta.yaml
Hi Bioconda,
Can you update the "vConTACT3" bioconda package to 3.0.5? This python package is designed to assist in taxonomically classifying viruses from environmental datasets. This update includes several bug fixes and additional user outputs.
bioconda-utils lint and bioconda-utils build completed sucessfully.
Thanks for maintaining and keeping Bioconda alive!
----
* PRs require …
=> Update vcontact3 to 3.0.5

recipes/plannotate/meta.yaml
https://github.com/mmcguffi/pLannotate/pull/52
=> update plannotate to 1.2.4

recipes/mbg/mbg-aarch64.patch, recipes/mbg/meta.yaml, recipes/mbg/osx_availability.patch
Update MBG to version 1.0.17
---- …
=> Update MBG to version 1.0.17

recipes/actc/meta.yaml
=> Update actc to v0.6.1

recipes/lumpy-sv-minimal/meta.yaml
Add arm64 build for lumpy-sv-minimal
---- …
=> Add arm64 build for lumpy-sv-minimal

build-fail-blacklist, recipes/perl-devel-checklib/build.sh, recipes/perl-devel-checklib/meta.yaml
=> Rebuild perl-devel-checklib recipe

recipes/barcodeforge/meta.yaml
Bump BarcodeForge to 1.1.0 and update recipe dependencies.
---- …
=> Update barcodeforge to version 1.1.0

recipes/panacus/meta.yaml
=> Update panacus to v0.4.0

recipes/rdock/0001-RbtTypes.patch, recipes/rdock/build.sh, recipes/rdock/meta.yaml
=> Rebuild rdock recipe

recipes/crocodeel/meta.yaml
=> Update CroCoDeEL to 1.0.7

recipes/galaxy-data/meta.yaml
See https://github.com/ResearchObject/ro-crate-py/issues/139
---- …
=> Update galaxy-data to add rocrate dep now that it exists in conda-forge

recipes/cram-archiver/meta.yaml
Add cram-archiver, a simple script to automatically convert BAM files to CRAM for archival purposes.
----
Conda is able …
=> Add cram-archiver

recipes/haphic/build.sh, recipes/haphic/meta.yaml
=> Added HapHiC

recipes/lotus3/build.sh, recipes/lotus3/meta.yaml, recipes/lotus3/post-link.sh, recipes/lotus3/pre-unlink.sh
Upstream renamed from lotus2 to lotus3.
---- …
=> Add recipe for LotuS3

recipes/barcodeforge/meta.yaml
Bump barcodeforge to version 1.1.1 and remove myself as a recipe maintainer.
---- …
=> Update barcodeforge to version 1.1.1 and update source SHA256

recipes/mi-pimento/meta.yaml
New version of mi-pimento package to replace [this autobump PR](https://github.com/bioconda/bioconda-recipes/pull/56918) since I had to update the cli path
---- …
=> version 1.0.1 of mi-pimento, with updated cli_path

recipes/flexiplex/meta.yaml
This PR updates Flexiplex to v1.02.3
---- …
=> Update Flexiplex to v1.02.3

recipes/learnmsa/meta.yaml
Update [learnmsa](https://bioconda.github.io/recipes/learnmsa/README.html): 2.0.10 → 2.0.11
Supercedes https://github.com/bioconda/bioconda-recipes/pull/56922
=> Update learnmsa to 2.0.11

recipes/mgnify-pipelines-toolkit/meta.yaml
Update recipe to the v1.2.1 release, with some manual changes I had to make compared to the autobump
----
Conda is able …
=> mgnify-pipelines-toolkit v1.2.1

recipes/vcf2pandas/meta.yaml
=> Add recipe for vcf2pandas v0.2.0

recipes/kmc/0001-master.patch, recipes/kmc/0002-cmake.patch, recipes/kmc/build.sh, recipes/kmc/conda_build_config.yaml, recipes/kmc/meta.yaml
=> Build KMC from source

recipes/r-flanders/meta.yaml
Add r-flanders package we developed. See: https://github.com/Biostatistics-Unit-HT/flanders_r.git
---- …
=> Add r-flanders

recipes/heasoft/meta.yaml, recipes/heasoft/post-link.sh
This is meant to fix the description rendering
---- …
=> Fix HEAsoft description rendering - Ready for review

recipes/varlinker/build.sh, recipes/varlinker/meta.yaml
=> Add varlinker version 1.1.0

recipes/howdesbt/0001-Makefile_full.patch, recipes/howdesbt/build.sh, recipes/howdesbt/meta.yaml
=> Rebuild howdesbt

recipes/rtg-core/build.sh, recipes/rtg-core/meta.yaml
RTG Core is a superset of RTG Tools, includes mapping and variant calling algorithms.
I basically adapted this from the existing `rtg-tools` recipe.
Note: The `rtg-tools` recipe currently has an "extra identifier" of `biotools:rtg_core` which I would have thought should be `biotools:rtg_tools`. If so, would you like me to make that change to that recipe in this PR?)
---
* PRs …
=> Add rtg-core package

recipes/perl-alien-build-plugin-download-gitlab/build.sh, recipes/perl-alien-build-plugin-download-gitlab/meta.yaml
=> Add recipe for perl-alien-build-plugin-download-gitlab v0.01

recipes/poppunk/meta.yaml
Updates PopPUNK to version 2.7.6
- updates PopPUNK version 2.7.5 -> 2.7.6
- updates sha256 for tar.gz archive
---- …
=> Update PopPUNK to version 2.7.6

recipes/coreprofiler/meta.yaml
Hello,
This PR adds a new tool CoreProfiler v1.1.1 to bioconda.
Thanks
---- …
=> Add CoreProfiler recipe

recipes/edentity/meta.yaml
=> Update edentity to 1.4.5

recipes/lotus3/meta.yaml
Changed in
https://github.com/hildebra/LotuS3/commit/acde879d5868be8cb4f38a2404bd529a0f561446
---- …
=> Fix LotuS3 license

recipes/easel/build.sh, recipes/easel/meta.yaml
=> easel: add arm64 build

recipes/blastn2dotplots/meta.yaml
=> Add recipe for blastn2dotplots v1.1.2

recipes/libccp4/meta.yaml
This pull request adds metadata to the `recipes/libccp4/meta.yaml` file. Specifically, it introduces a DOI identifier under the `extra` section to enhance the documentation and referencing of the CCP4 software.
* [`recipes/libccp4/meta.yaml`](diffhunk://#diff-fdd5b9dbd2344dec225503603645c00a4482818a6577612ae237b0c6d1951f6aR51-R52): Added a DOI identifier (`doi:10.1107/S0907444994003112`) under the `extra` section to improve metadata and referencing.
----
* New recipes not directly relevant to the biological sciences need to be submitted to the …
=> libccp4: Add DOI identifier

recipes/trinity/build.sh, recipes/trinity/meta.yaml
=> trinity: add arm64 build

recipes/biobb_amber/meta.yaml
=> [biobb_amber] update 5.1.0

recipes/ucsc-fatotwobit/build.sh, recipes/ucsc-fatotwobit/meta.yaml
=> Update ucsc-fatotwobit to v482

recipes/ucsc-twobitinfo/build.sh, recipes/ucsc-twobitinfo/meta.yaml
=> Update ucsc-twobitinfo to v482

recipes/biobb_chemistry/meta.yaml
=> [biobb_chemistry] update 5.1.0

recipes/biobb_cmip/meta.yaml
=> [biobb_cmip] update 5.1.0

recipes/biobb_cp2k/meta.yaml
=> [biobb_cp2k] update 5.1.0

recipes/biobb_dna/meta.yaml
=> [biobb_dna] update 5.1.0

recipes/biobb_flexdyn/meta.yaml
=> [biobb_flexdyn] update 5.1.0

recipes/biobb_flexserv/meta.yaml
=> [biobb_flexserv] update 5.1.0

recipes/pcne/build.sh, recipes/pcne/meta.yaml
Added missing line in build.sh
Change build number to 1
=> Update PCNE v1.0.0

recipes/dendropy/meta.yaml
=> Rebuild dendropy

recipes/biobb_godmd/meta.yaml
=> [biobb_godmd] update 5.1.0

recipes/biobb_io/meta.yaml
=> [biobb_io] update 5.1.0

recipes/biobb_pdb_tools/meta.yaml
=> [biobb_pdb_tools] update 5.1.0

recipes/biobb_model/meta.yaml
=> [biobb_model] update 5.1.0

recipes/biobb_pmx/meta.yaml
=> [biobb_pmx] update 5.1.0

recipes/biobb_structure_utils/meta.yaml
=> [biobb_structure_utils] update 5.1.0

recipes/godmd/meta.yaml
=> gitlab to github

recipes/biobb_vs/meta.yaml
=> [biobb_vs] update 5.1.0

recipes/agat/meta.yaml
Added `samtools` as dependency, since it is needed to run ` agat_convert_minimap2_bam2gff.pl`:
https://github.com/NBISweden/AGAT/blob/1baa1d0d44d44dc2365a5ce9e0c01ad528643523/bin/agat_convert_minimap2_bam2gff.pl#L81-L86
----
* …
=> Update: samtools dependency

recipes/sawfish/meta.yaml
Summary update reflects updated scope since the v2 release
---- …
=> Update sawfish summary

recipes/hmftools-gene-utils/build.sh, recipes/hmftools-gene-utils/gene-utils.sh, recipes/hmftools-gene-utils/meta.yaml
=> Add hmftools-gene-utils

recipes/bioconductor-geometadb/meta.yaml
Update geometadb to 1.68.1 with updated dependencies for Bioconductor 3.20 
---- …
=> Update bioconductor-geometadb to 1.68.1

recipes/ucsc-fatovcf/build.sh, recipes/ucsc-fatovcf/meta.yaml
=> Update ucsc-fatovcf to v482

recipes/ucsc-wigtobigwig/build.sh, recipes/ucsc-wigtobigwig/meta.yaml
=> Update ucsc-wigtobigwig to v482

recipes/ucsc-stringify/build.sh, recipes/ucsc-stringify/meta.yaml
=> ucsc-stringify: ucsc-stringify to v482

recipes/sourmash/meta.yaml
This PR updates the description for sourmash, adds @bluegenes to the author list, and adds the JOSS paper for sourmash v4.0. No code changes.
Ref https://github.com/sourmash-bio/sourmash/issues/3514
---- …
=> Update sourmash metadata: authors & papers

recipes/bioconductor-scmet/meta.yaml
Add `linux-aarch64` and `osx-arm64` platform builds for `bioconductor-scmet`
---- …
=> Update bioconductor-scmet recipe - additional platforms

recipes/bifrost-httr/LICENSE, recipes/bifrost-httr/meta.yaml
Adding recipe for https://pypi.org/project/bifrost-httr/
---- …
=> Add recipe for bifrost-httr 0.1.0

recipes/galaxy-job-config-init/meta.yaml
=> Add recipe for galaxy-job-config-init v0.1.3

recipes/clipper/build.sh, recipes/clipper/clipper-configure-2.patch, recipes/clipper/meta.yaml
This pull request introduces a new recipe for building the `clipper` library, including its dependencies and configuration. The changes focus on adding build scripts, patches, and metadata to support the compilation and packaging of the library. Key updates include the creation of a `build.sh` script, modifications to the `configure` file via a patch, and the addition of a `meta.yaml` file for package metadata.
* [`recipes/clipper/build.sh`](diffhunk://#diff-d537b0df334ed0407b6777110fd8f388f09749a465078469fa1c89875d6bb475R1-R69): Added a build script to compile the `clipper` library and its dependency `fftw2` with specific configuration flags. This includes environment variable adjustments, shared library support, and fixes for pkg-config name mismatches.
* …
=> Adding clipper v2.1.20180802

recipes/blobtoolkit/meta.yaml
=> Add recipe for blobtoolkit v4.4.6

recipes/vbz-h5py-plugin/meta.yaml
=> Add recipe for vbz-h5py-plugin v1.0.1

recipes/haddock_biobb/meta.yaml, recipes/haddock_biobb/post-link.sh
Fixed haddock3 version so it don't install the last version available on the post link.
---- …
=> haddock3 v2025.5.0

recipes/haddock_biobb/meta.yaml
=> [haddock_biobb] v2025.5 build 1

recipes/biobb_gromacs/meta.yaml, recipes/haddock_biobb/meta.yaml
=> [biobb_gromacs] update 5.1.0

recipes/vembrane/meta.yaml
=> fix: set vembrane python dependency to 3.12 (recently changed)

recipes/biobb_haddock/meta.yaml
=> [biobb_haddock] update 5.1.0

recipes/biobb_mem/meta.yaml
=> [biobb_mem] update 5.1.0

recipes/harpy/meta.yaml
This uses a selector to restrict `apptainer` installation to linux platforms only
---- …
=> Update Harpy build

recipes/eklipse/build.sh, recipes/eklipse/meta.yaml, recipes/eklipse/py2to3.patch, recipes/eklipse/py310.patch, recipes/eklipse/syntax.patch
- applied py2to3
- resolved string escaping issues
- resolved string equality check issues
---- …
=> eklipse: migrate from python2 to python3

recipes/quaqc/meta.yaml
Trying to figure out what's breaking the nightly build by building last thing in logs.
---- …
=> build quaqc

recipes/varlociraptor/meta.yaml
The linux build never got uploaded for some reason
---- …
=> varlociraptor: bump build number

recipes/ucsc-matrixclustercolumns/0001-include.patch, recipes/ucsc-matrixclustercolumns/0002-include.linux.patch, recipes/ucsc-matrixclustercolumns/0003-common.mk.patch, recipes/ucsc-matrixclustercolumns/0004-straw.patch, recipes/ucsc-matrixclustercolumns/build.sh, recipes/ucsc-matrixclustercolumns/meta.yaml, recipes/ucsc-matrixclustercolumns/run_test.sh, recipes/ucsc-matrixmarkettotsv/0001-include.patch, recipes/ucsc-matrixmarkettotsv/0002-include.linux.patch, recipes/ucsc-matrixmarkettotsv/0003-common.mk.patch, recipes/ucsc-matrixmarkettotsv/0004-straw.patch, recipes/ucsc-matrixmarkettotsv/build.sh, recipes/ucsc-matrixmarkettotsv/meta.yaml, recipes/ucsc-matrixmarkettotsv/run_test.sh, recipes/ucsc-matrixnormalize/0001-include.patch, recipes/ucsc-matrixnormalize/0002-include.linux.patch, recipes/ucsc-matrixnormalize/0003-common.mk.patch, recipes/ucsc-matrixnormalize/0004-straw.patch, recipes/ucsc-matrixnormalize/build.sh, recipes/ucsc-matrixnormalize/meta.yaml, recipes/ucsc-matrixnormalize/run_test.sh, recipes/ucsc-matrixtobarchartbed/0001-include.patch, recipes/ucsc-matrixtobarchartbed/0002-include.linux.patch, recipes/ucsc-matrixtobarchartbed/0003-common.mk.patch, recipes/ucsc-matrixtobarchartbed/0004-straw.patch, recipes/ucsc-matrixtobarchartbed/build.sh, recipes/ucsc-matrixtobarchartbed/meta.yaml, recipes/ucsc-matrixtobarchartbed/run_test.sh
new packages
- matrixClusterColumnsAdd
- matrixMarketToTsv
- matroxNormalize
- matrixToBarChartBed
----
Conda is able …
=> Add some ucsc matrix tools with v482

recipes/argparse-tui/meta.yaml
=> Add recipe for argparse-tui v0.3.1

recipes/demultiplexer2/meta.yaml
=> Add recipe for demultiplexer2 v1.1.5

recipes/starcode/0001-master.patch, recipes/starcode/build.sh, recipes/starcode/meta.yaml
=> starcode: add arm64 build

build-fail-blacklist
Re-try missMethyl now that IlluminaHumanMethylationEPICv2anno.20a1.hg38 and IlluminaHumanMethylationEPICv2manifest are available
=> Re-try missMethyl

recipes/openstructure/build.sh, recipes/openstructure/meta.yaml, recipes/openstructure/post-link.sh
This pull request updates the build process and metadata for the `openstructure` recipe to improve compatibility and streamline the build configuration. Key changes include adjustments to platform-specific flags, updates to build metadata, and minor corrections in documentation.
* [`recipes/openstructure/build.sh`](diffhunk://#diff-8ec672335bf313841b71fd547851b0c337d524bb7a111ecba8a3d179aef498baL6-R13): Replaced checks for `uname` with `target_platform` to improve platform detection and updated linker flags for Linux and macOS platforms. Additionally, refined the conditional logic for running tests on `linux-aarch64`. [[1]](diffhunk://#diff-8ec672335bf313841b71fd547851b0c337d524bb7a111ecba8a3d179aef498baL6-R13) [[2]](diffhunk://#diff-8ec672335bf313841b71fd547851b0c337d524bb7a111ecba8a3d179 …
=> openstructure: Update documentation in post-link.sh

recipes/phabox/meta.yaml
Added two new packages:
- joblib =1.5.1
- scikit-learn =1.3.2
=> Update PhaBOX environments

build-fail-blacklist, recipes/bioconductor-dmrcate/meta.yaml
enable dmrcate and bump build version
=> enable dmrcate and bump build version

recipes/metadmg/0001-Makefile.patch, recipes/metadmg/build.sh, recipes/metadmg/meta.yaml
Add `extract_reads` binary to recipe, and bump version.
---- …
=> Update: bump metadmg version

recipes/ucsc-overlapselect/build.sh, recipes/ucsc-overlapselect/meta.yaml
=> Update ucsc-overlapselect to v482

recipes/primer3-py/build.sh, recipes/primer3-py/meta.yaml
=> Rebuild primer3-py recipe

recipes/lassaseq/meta.yaml, recipes/lassensus/meta.yaml
=> Add Lassensus

recipes/beast/meta.yaml
This is a pull request to update the recipe for BEAST to the latest version (v10.5.0).
---- …
=> Update meta.yaml for beast recipe to BEAST v10.5.0

recipes/repeatafterme/0001-Makefile.patch, recipes/repeatafterme/0002-dnautil-macOS.patch, recipes/repeatafterme/build.sh, recipes/repeatafterme/meta.yaml
=> Add recipe for RepeatAfterMe v0.0.7

recipes/ultra/build.sh, recipes/ultra/meta.yaml
=> Add recipe for ULTRA v1.1.0

recipes/genome_profiler/meta.yaml
Add `genome_profiler` package recipe.
---- …
=> Add package: genome_profiler

recipes/libcifpp/activate.sh, recipes/libcifpp/build.sh, recipes/libcifpp/deactivate.sh, recipes/libcifpp/meta.yaml
This pull request updates the `libcifpp` recipe to improve compatibility and ensure proper configuration during the build process. The most significant changes include adding new configuration options in the build script, updating dependency versions, and incrementing the build number.
* [`recipes/libcifpp/build.sh`](diffhunk://#diff-ab471fb4a4509cb46ee5fd070ce571d2af5bca97328cdbc31c6c6f34cbfc4a96R16-R25): Added new configuration options `-DCIFPP_DATA_DIR=''` and `-DCIFPP_SHARE_DIR="${PREFIX}/share/libcifpp"` to ensure proper handling of data and share directories.
* [`recipes/libcifpp/meta.yaml`](diffhunk://#diff-c238be9013a67a799fcd58a159cc5b2ac2cd4b8877de1a9d29ded891bddce116L29-R33): Updated the host dependency for `libboost-devel` to version `>=1.86.0,<1.87.0a0` to align with …
=> libcifpp: Update CMake configuration

recipes/bifrost-httr/meta.yaml
I set these pins too strict, relax a bit while we bump versions.
---- …
=> Update bifrost-httr and relax pins

recipes/vcf-validator/build.sh, recipes/vcf-validator/meta.yaml
=> Update vcf-validator to 0.10.1

recipes/matchms/meta.yaml
I updated the deps to be in-line with the python package; I also bumped the build number
---- …
=> Update dependencies of matchms 0.30.2 to fit with pyproject.toml file

recipes/newmap/0001-CMakeLists.patch, recipes/newmap/build.sh, recipes/newmap/meta.yaml, recipes/newmap/run_test.sh
This a new recipe for the  [Newmap tool](https://github.com/hoffmangroup/newmap). A successor to [Umap](https://hoffmanlab.org/proj/bismap/)
---- …
=> Add recipe for newmap

recipes/coot-headless/run_test.py
=> coot-headless: Update `run_exports`

recipes/newmap/meta.yaml
=> Rebuild newmap recipe

recipes/finaletoolkit/meta.yaml
Add FinaleToolkit to the Bioconda channel. 
- FinaleToolkit is a package and standalone program to extract fragmentation features of cell-free DNA from paired-end sequencing data.
----
* Please …
=> ADD: Finaletoolkit 0.10.7

recipes/perl-io-zlib/meta.yaml
=> Fix license for perl IO:Zlib

recipes/stripepy-hic/meta.yaml
Closes https://github.com/bioconda/bioconda-recipes/pull/57597.
---- …
=> Update stripepy-hic to v1.1.1

recipes/seqtk/0001-makefile.patch, recipes/seqtk/build.sh, recipes/seqtk/meta.yaml
=> seqtk: add arm64 build

recipes/slivar/0001-master.patch, recipes/slivar/build.sh, recipes/slivar/meta.yaml
=> Rebuild slivar recipe

recipes/vcfanno/build.sh, recipes/vcfanno/meta.yaml
=> Update vcfanno to 0.3.6

recipes/mosdepth/build.sh, recipes/mosdepth/meta.yaml
=> Update mosdepth to v0.3.11

recipes/ropebwt2/build.sh, recipes/ropebwt2/meta.yaml
=> ropebwt2: add arm64 build

build-fail-blacklist, recipes/fmlrc2/build.sh, recipes/fmlrc2/meta.yaml
=> Update FMLRC2 to v0.1.8

recipes/clair3/meta.yaml
=> Update clair3 to v1.1.2

recipes/muscle/3.8.1551/meta.yaml
=> Add missing license for muscle

recipes/addeam/build.sh, recipes/addeam/meta.yaml
Conda recipe for aDNA tool AdDeam.
=> Add recipe AdDeam

recipes/pyngost/build.sh, recipes/pyngost/meta.yaml
I want to add pyngoST to bioconda.
Tested locally. 
https://github.com/leosanbu/pyngoST
---- …
=> Add pyngost 1.1.3

recipes/svync/meta.yaml
=> Update svync to 0.3.0

recipes/pcangsd/meta.yaml
adds a recipe for `pcangsd`. There's a small chance the build might not work b/c I'm not familiar with where `cython` goes.
---- …
=> Add Pcangsd recipe

recipes/anospp-analysis/meta.yaml
bump blast dep version for osx-arm64 compatibility
---- …
=> update anospp-analysis build

recipes/pytantan/0001-main.patch, recipes/pytantan/meta.yaml
=> Rebuild pytantan

recipes/dbcan/0001-version.patch, recipes/dbcan/meta.yaml
=> Rebuild dbcan package

recipes/minimod/build.sh, recipes/minimod/meta.yaml
Add minimod - a new tool for base modification data in BAM files
---- …
=> Add minimod

recipes/coreprofiler/meta.yaml
=> Bump coreprofiler version

recipes/netmd/build.sh, recipes/netmd/meta.yaml
NetMD is a computational method for identifying consensus behavior across multiple molecular dynamics simulations.
The Python constraints (>=3.10,<=3.12.8) are due to the package Karateclub which seems not installable with other Python versions.
---- …
=> Add NetMD recipe

recipes/cdskit/meta.yaml
- Added support for biopython >=1.77
- Confirmed compatibility up to Python 3.13 (tested with Bio.SeqIO)
Tested locally using `bioconda-utils` and confirmed that the package builds and runs correctly.
----
* Please post …
=> Update cdskit to 0.14.4 with biopython >=1.77 support

recipes/genome-uploader/meta.yaml
=> Add genome-uploader recipe

recipes/amira/meta.yaml
Adds Flye to the dependencies for Amira.
---- …
=> Update: add flye to amira dependencies

recipes/grz-check/build.sh, recipes/grz-check/meta.yaml
This PR adds a recipe for `grz-check`.
=> Add grz-check

recipes/htseq/meta.yaml
=> htseq: add osx-arm64

recipes/bioconductor-hmmcopy/meta.yaml
Update bioconductor-hmmcopy to build on osx-arm64
---- …
=> Update bioconductor-hmmcopy to build on osx-arm64

recipes/bbmap/build.sh, recipes/bbmap/meta.yaml
=> Update bbmap to v39.33

recipes/pantax/build.sh, recipes/pantax/meta.yaml
**Part of the code has been rewritten using Rust and significant bugs have been fixed, requiring a rebuild. PanTax's build requires Gurobi's dynamic library files. I referred to hatchet**
https://github.com/bioconda/bioconda-recipes/blob/31d2941a674b12c94e87be1c35d7c4698068be5e/recipes/hatchet/meta.yaml#L12-L14
----
* PRs require reviews prior to …
=> Rebuild pantax version 2.0.0

recipes/bigwig-nim/build.sh, recipes/bigwig-nim/meta.yaml
=> Add bigwig-nim, from brentp

recipes/svision-pro/meta.yaml
=> Rebuild SVision-pro - pin python to <3.8

recipes/hmftools-chord/meta.yaml
=> Update hmftools-chord to 2.1.2

recipes/svpg/LICENSE, recipes/svpg/build.sh, recipes/svpg/meta.yaml
=> Add svpg recipe

build-fail-blacklist, recipes/cas-offinder/build.sh, recipes/cas-offinder/meta.yaml
=> Update cas-offinder to v2.4.1

recipes/hmftools-wisp/build.sh, recipes/hmftools-wisp/meta.yaml, recipes/hmftools-wisp/wisp.sh
=> Add hmftools-wisp

recipes/stringtie/build.sh, recipes/stringtie/meta.yaml
=> Rebuild stringtie recipe

recipes/pysam/conda_build_config.yaml, recipes/pysam/meta.yaml
=> Build pysam on python 3.13

recipes/mutscan/build.sh, recipes/mutscan/meta.yaml, recipes/mutscan/patch
=> Update MutScan to v1.14.1

recipes/perl-inline-c/meta.yaml
=> Update perl-inline-c to v0.82

recipes/mmseqs2/meta.yaml
=> Update MMseqs2 to 18-8cc5c

recipes/graphaligner/build.sh, recipes/graphaligner/meta.yaml
=> Rebuild GraphAligner recipe

recipes/winnowmap/build.sh, recipes/winnowmap/meta.yaml
=> Winnowmap: add aarch64/arm64 builds

recipes/maker/build.sh, recipes/maker/meta.yaml, recipes/maker/mpi_init.patch
=> Update maker to v3.09.04

recipes/ribotin/build.sh, recipes/ribotin/meta.yaml
Update ribotin to version 1.5
---- …
=> Update ribotin to version 1.5

recipes/readfq/build.sh, recipes/readfq/meta.yaml
=> readfq: add aarch64/arm64 builds

recipes/hmftools-cobalt/meta.yaml, recipes/hmftools-isofox/meta.yaml, recipes/hmftools-pave/meta.yaml
=> Trigger building hmftools containers with fix "Use com.hartwig. to detect class path being provided to java call"

recipes/diamond/meta.yaml
=> diamond: Update to 2.1.13.

recipes/antismash/build.sh, recipes/antismash/meta.yaml
=> Update antismash to v8.0.2

recipes/aliceasm/build.sh, recipes/aliceasm/meta.yaml
=> Update aliceasm to v0.6.41

recipes/smakcr/meta.yaml
=> Add smakcr

recipes/kmer-db/meta.yaml
=> Update kmer-db to v2.3.1

recipes/ciri-full/meta.yaml, recipes/rgi/build.sh, recipes/rgi/meta.yaml, recipes/sspace_basic/build.sh, recipes/sspace_basic/meta.yaml, recipes/trtools/meta.yaml
=> Clean recipes with extraneous additional-platforms sections part 2

recipes/blue-crab/meta.yaml, recipes/jccirc/meta.yaml, recipes/lsabgc/meta.yaml
=> Clean recipes with extraneous additional-platforms sections part 3

recipes/soapdenovo-trans/0001-makefile.patch, recipes/soapdenovo-trans/0002-osx-no-rt-link.patch, recipes/soapdenovo-trans/build.sh, recipes/soapdenovo-trans/meta.yaml
=> Update soapdenovo-trans to v1.0.5

recipes/biobb_adapters/meta.yaml
=> [biobb_adapters] update 5.1.0

recipes/megahit/0001-master.patch, recipes/megahit/build.sh, recipes/megahit/conda_build_config.yaml, recipes/megahit/meta.yaml
=> megahit: add arm64 build

recipes/hapcut2/0001-master.patch, recipes/hapcut2/0002-Makefile.patch, recipes/hapcut2/build.sh, recipes/hapcut2/meta.yaml
=> hapcut2: add aarch64/arm64 builds

recipes/bioemu/meta.yaml
Moving from https://github.com/conda-forge/staged-recipes/pull/30652
---- …
=> Add recipe for bioemu

recipes/seqkit/build.sh, recipes/seqkit/meta.yaml
=> Try building seqkit from source

recipes/samtools/0.1.19/build.sh, recipes/samtools/0.1.19/meta.yaml
=> samtools v0.1.19: add arm64 build

recipes/egap/build.sh, recipes/egap/meta.yaml
Corrected build.sh to install files in the appropriate location
---- …
=> v3.1b Corrected build.sh

recipes/quaqc/meta.yaml
Update quaqc from v1.3d to v1.3e
---- …
=> Update quaqc to v1.3e

recipes/sickle-trim/0001-master-sickle.patch, recipes/sickle-trim/build.sh, recipes/sickle-trim/meta.yaml
=> sickle-trim: add arm64 build

recipes/sentieon/meta.yaml
=> Update Sentieon recipe to 202503.01

recipes/libgenome/build.sh, recipes/libgenome/meta.yaml
=> libgenome: add aarch64/arm64 builds

recipes/agtools/meta.yaml
This PR adds [`agtools`](https://github.com/Vini2/agtools), a toolkit for manipulating assembly graphs for downstream metagenomic applications, with a focus on the [Graphical Fragment Assembly (GFA) format](https://github.com/GFA-spec/GFA-spec). It offers a command-line interface for tasks such as graph format conversion, segment filtering, and component extraction. Supported formats include [GFA](https://github.com/pmelsted/GFA-spec/blob/master/GFA-spec.md), [FASTG](https://web.archive.org/web/20211209213905/http://fastg.sourceforge.net/FASTG_Spec_v1.00.pdf), [ASQG](https://github.com/jts/sga/wiki/ASQG-Format) and [GraphViz DOT](http://www.graphviz.org/content/dot-language). Additionally, it provides a Python package interface that exposes assembler-specific functionality for advanced …
=> Add agtools v0.1.0

recipes/yara/build.sh, recipes/yara/meta.yaml
=> Update yara to 1.0.5

recipes/esme/conda_build_config.yaml, recipes/esme/meta.yaml
This PR updates the version of the packages for ESME MVAPIch variant and also builds for AARCH64 support
----
Conda is …
=> Update ESME MVAPIch packages version and add ARM support

recipes/fastani/meta.yaml, recipes/gtdbtk/meta.yaml, recipes/mash/meta.yaml
* also bumps the builds for fastani and mash - as these were pinned builds to an older version of gsl, and necessary for resolving pplacer (at least on osx-arm64)
---- …
=> gtdbtk - add linux-aarch64, osx-arm64

recipes/dinamo/Makefile.patch, recipes/dinamo/build.sh, recipes/dinamo/meta.yaml
=> Rebuild dinamo recipe

recipes/prosampler/build.sh, recipes/prosampler/meta.yaml
=> prosampler: add arm64 build

recipes/biobb_gromacs/meta.yaml
=> [biobb_gromacs] update 5.1.1

recipes/biobb_analysis/meta.yaml
=> [biobb_analysis] update 5.1.1

recipes/structure-threader/meta.yaml
Update structure-threader recipe to fix interpreter
---- …
=> Update structure-threader recipe to fix interpreter

recipes/graphembed/meta.yaml
in the release, we add python API support for graphembed. Users can use it directly in python and process output in python.
---- …
=> Update graphembed v0.1.8

recipes/phyclone/meta.yaml
Updating PhyClone recipe to version 0.7.1
This PR contains recipe updates not captured in  #58339 
----
<details>
<table>
<tr>
</tr>
<tr>
</tr>
</table>
Also, the bot watches for comments from non-members that include `@bioconda/<team>` and will …
=> Update PhyClone to 0.7.1

recipes/kled/build.sh, recipes/kled/meta.yaml
Update kled to v1.2.10, fixed a bug that would stop kled for output in some devices.
---- …
=> Update kled to v1.2.10.

recipes/vclust/meta.yaml
=> Rebuild vclust

recipes/ucsc-newpythonprog/meta.yaml
=> Rebuild ucsc-newpythonprog

recipes/ucsc-paratestjob/build.sh, recipes/ucsc-paratestjob/meta.yaml
=> Rebuild ucsc-paratestjob

recipes/kallisto/build.sh, recipes/kallisto/meta.yaml
=> Rebuild kallisto recipe

recipes/taxburst/meta.yaml
Adding taxburst, on behalf of the author: https://github.com/taxburst/taxburst/issues/59
---- …
=> Add taxburst

recipes/biofluff/meta.yaml
=> Rebuild biofluff recipe

recipes/proda/0001-Makefile.patch, recipes/proda/build.sh, recipes/proda/file.patch, recipes/proda/meta.yaml
=> proda: add aarch64/arm64 builds

recipes/gvcf2coverage/build.sh, recipes/gvcf2coverage/meta.yaml
=> gvcf2coverage: add arm64 build

recipes/karect/build.sh, recipes/karect/meta.yaml
=> karect: add arm64 build

recipes/gustaf/build.sh, recipes/gustaf/meta.yaml
=> gustaf v1.0.10: add aarch64/arm64 builds

recipes/fgpyo/meta.yaml
Adding `python-zlib-ng` to `fgpyo` since it is a new dependency since:
- https://github.com/fulcrumgenomics/fgpyo/pull/240
---- …
=> Update fgpyo by adding dependency python-zlib-ng

recipes/ligand-validation/build.sh, recipes/ligand-validation/meta.yaml
This pull request updates the build and packaging process for the `ligand-validation` recipe, focusing on standardizing the build script, cleaning up the `meta.yaml`, and improving metadata. The most important changes are grouped below:
**Build and Packaging Process:**
* Added a new `build.sh` script to standardize the build process, using pip for installation and ensuring binaries are installed with correct permissions.
* Removed the explicit `script` and `scripts` fields from `meta.yaml` in favor of the new `build.sh` script, simplifying the build section.
* Cleared the `run_exports` field to prevent unnecessary pinning of dependencies in downstream packages.
**Metadata Improvements:**
* Corrected the `name` and `url` fields in `meta.yaml` to use the original case, ensuring consistency …
=> ligand-validation: Update recipe

recipes/pbsim3/meta.yaml
PR to add samtools as dependency to solve https://github.com/yukiteruono/pbsim3/issues/48
---- …
=> add samtools as dependency

recipes/seqforge/meta.yaml
=> Add seqforge 1.0.0

recipes/perl-dbd-pg/build.sh, recipes/perl-dbd-pg/meta.yaml
=> perl-dbd-pg: add arm64 build

recipes/crunchstat-summary/meta.yaml
=> Add recipe for crunchstat-summary v3.1.2

recipes/perl-bio-bigfile/build.sh, recipes/perl-bio-bigfile/meta.yaml
=> perl-bio-bigfile: add aarch64 build

recipes/intarna/build.sh, recipes/intarna/meta.yaml
=> intarna: add arm64 build

recipes/matam/build.sh, recipes/matam/meta.yaml
=> matam: add aarch64 build

recipes/folddisco/build.sh, recipes/folddisco/meta.yaml
=> Add Folddisco

recipes/heasoft/meta.yaml
heasoft is marked in the nightly build as needing a build number bump due to divergent build strings.
----
Conda is …
=> heasoft: bump build number

.circleci/config.yml, recipes/predictosaurus/meta.yaml
=> Rebuild predictosaurus recipe

recipes/macsyfinder/meta.yaml
MacSyFinder dependencies have changed. Update the recipe.   
----
=> Update macsyfinder recipe

recipes/paml/build.sh, recipes/paml/meta.yaml
=> Rebuild paml recipe

recipes/perl-bio-bigfile/meta.yaml
=> perl-bio-bigfile: add arm64 build

recipes/maaslin3/build.sh, recipes/maaslin3/meta.yaml
=> add MaAsLin3

recipes/btrim/0001-fix-push_back-initializer_list-and-abs-from-uint.patch, recipes/btrim/build.sh, recipes/btrim/meta.yaml
=> Rebuild btrim recipe

recipes/alfred/build.sh, recipes/alfred/meta.yaml
=> Update alfred v0.5.1

recipes/wally/build.sh, recipes/wally/meta.yaml
=> wally: add arm64 build

recipes/macs2/conda_build_config.yaml, recipes/macs2/meta.yaml
=> macs2: add arm64 build

recipes/skesa/build.sh, recipes/skesa/meta.yaml
=> skesa: add arm64 build

recipes/r-seurat-data/meta.yaml
=> Update seurat-data to v0.2.2.9002

recipes/binchicken/meta.yaml
=> Update binchicken dependencies

recipes/artic/meta.yaml
This was left out of pyproject.toml accidentally meaning `--version` would report the incorrect version
----
Conda is …
=> Update artic 1.8.0 version metadata

recipes/allelecodes/build.sh, recipes/allelecodes/meta.yaml
Making an allele codes contribution. This is a basic methodology for genomic epidemiology in foodborne surveillance. Unfortunately even though it is version 2.1, that is not tagged just yet in the source repo. I have made that request.
---- …
=> allelecodes

recipes/r-presto/meta.yaml
r-presto needs a bump per the nightly builds.
---- …
=> bump r-presto

recipes/olivar/meta.yaml
Update sha256 and build number in meta.yaml for Olivar v1.3.3.
---- …
=> Update sha256 and build number for Olivar 1.3.3

recipes/repeatmasker/build.sh, recipes/repeatmasker/meta.yaml
=> Update RepeatMasker to 4.2.1

recipes/vcontact3/meta.yaml
Hi Bioconda,
Can you update the "vConTACT3" bioconda package recipe for 3.1.4? This python package is designed to assist in taxonomically classifying viruses from environmental datasets. This is a _recipe-only_ update that updates the host requirements in order to enable git-tag versioning. The previous build completes successfully, but without setuptools-scm, the git tag is not incorporated into the package version and breaks version-reliant functions within the software.
bioconda-utils lint and bioconda-utils build completed successfully.
Thanks, as always!
----
* If this PR adds or updates a recipe, use "Add" or "Update" appropriately as the …
=> Update vContact3 3.1.4 to R1

recipes/orthofinder/meta.yaml
=> Rebuild orthofinder recipe

recipes/sistem/meta.yaml
=> Update sistem to version 1.0.4

recipes/epimetheus-py/meta.yaml
This adds a dependency to nanomotif to bioconda. Nanomotif is used to find methylated motifs in Nanopore sequences.
---- …
=> Add epimetheus-py recipe

recipes/bioconductor-motifmatchr/build.sh, recipes/bioconductor-motifmatchr/meta.yaml
=> bioconductor-motifmatchr: add arm64 build

recipes/egap/meta.yaml
Updated to allow for DOI Tracking.
Corrected Python issue with bin directory parsing.
Removed meta.yaml to allow for correct sha256 and version alignment.
Full Changelog: v3.1...v3.2
----
* Please …
=> Update EGAP meta.yaml v3.2c

recipes/canu/build.sh, recipes/canu/meta.yaml
=> Rebuild canu recipe

recipes/fastmd5/build.sh, recipes/fastmd5/meta.yaml
=> Add fastmd5

recipes/abawaca/0001-Use-CXX-and-flags.patch, recipes/abawaca/build.sh, recipes/abawaca/meta.yaml
=> abawaca: add arm64 build

recipes/pyopenms/meta.yaml
=> Rebuild pyopenms recipe

recipes/earlgrey/build.sh, recipes/earlgrey/meta.yaml
=> Rebuild earlgrey recipe

recipes/quaqc/meta.yaml
Update quaqc from v1.3g to v1.4
---- …
=> update quaqc to 1.4

recipes/gbdraw/meta.yaml
- Added support for **GFF3** and **FASTA** files as input
- Added support for **label whitelists** (`--label_whitelist` option) for more precise control over which labels are displayed.
- Introduced a **local GUI**, accessible via the new `gbdraw gui` command (requires optional installation of [Streamlit](https://anaconda.org/conda-forge/streamlit)).
**Full Changelog**: https://github.com/satoshikawato/gbdraw/compare/0.4.0...0.5.0
---- …
=> Update gbdraw to v0.5.0

recipes/mmlong2-lite/meta.yaml
This PR includes the update for mmlong2-lite to v1.2.0
---- …
=> Update mmlong2-lite to v1.2.0

recipes/r-chromvarmotifs/build.sh, recipes/r-chromvarmotifs/meta.yaml
=> Rebuild r-chromvarmotifs

recipes/lib-pod5/POD5Version.cmake, recipes/lib-pod5/build.sh, recipes/lib-pod5/meta.yaml
=> Update lib-pod5 to v0.3.33

recipes/phold/meta.yaml, recipes/phu/LICENSE, recipes/phu/meta.yaml
=> Add phu meta.yaml recipe

recipes/mitosalt/download-mitosalt-db.sh, recipes/mitosalt/meta.yaml
Enhanced documentation
Fixed recognition of mitochondrial genome contig name
---- …
=> Update mitosalt (build 2)

recipes/decenttree/build.sh, recipes/decenttree/conda_build_config.yaml, recipes/decenttree/meta.yaml
=> Add decenttree 1.0.0

recipes/pod5/0.3.23/LICENSE.md, recipes/pod5/0.3.23/meta.yaml
=> Add pod5 v0.3.23

recipes/mawk/build.sh, recipes/mawk/meta.yaml
=> mawk: add arm64 build

recipes/atropos/meta.yaml
=> atropos: add arm64 build

recipes/mageck/build.sh, recipes/mageck/meta.yaml
=> mageck: add arm64 build

recipes/gridss/build.sh, recipes/gridss/meta.yaml
=> gridss: add arm64 build

recipes/goleft/build.sh, recipes/goleft/meta.yaml
=> goleft: add arm64 build

recipes/pyrle/meta.yaml
=> pyrle: add arm64 build

recipes/biobb_pdb_tools/meta.yaml
=> [biobb_pdb_tools] update 5.1.1

recipes/jalview/meta.yaml
Update Jalview to 2.11.5.0
---- …
=> Update Jalview to 2.11.5.0

recipes/galah/build.sh, recipes/galah/meta.yaml
=> galah: add aarch64/arm64 builds

recipes/mageck/meta.yaml
=> Rebuild mageck recipe

recipes/gempipe/meta.yaml
=> update gempipe to v1.38.2

recipes/biobb_analysis/meta.yaml
=> [biobb_analysis] update 5.1.2

recipes/groot/build.sh, recipes/groot/meta.yaml
=> groot: add arm64 build

recipes/kaiju/build.sh, recipes/kaiju/meta.yaml
=> kaiju: add arm64 build

recipes/locarna/build.sh, recipes/locarna/meta.yaml
=> locarna: add aarch64/arm64 builds

recipes/svdb/meta.yaml
=> svdb: add arm64 build

recipes/samsum/meta.yaml
=> samsum: add arm64 build

recipes/callerpp/build.sh, recipes/callerpp/meta.yaml
=> callerpp: add arm64 build

recipes/bfc/0001-Makefile-append-LIBS.patch, recipes/bfc/build.sh, recipes/bfc/meta.yaml, recipes/fermi2/build.sh, recipes/fermi2/meta.yaml
=> fermi2 and bfc: add arm64 builds

recipes/pangene/build.sh, recipes/pangene/meta.yaml
=> Add recipe for pangene r231

recipes/longdust/build.sh, recipes/longdust/meta.yaml
=> Add recipe for longdust v1.2

recipes/splicemap/0001-fix-string-array-initializer-assignment.patch, recipes/splicemap/build.sh, recipes/splicemap/meta.yaml
=> splicemap: add aarch64/arm64 builds

recipes/addrg/build.sh, recipes/addrg/meta.yaml
=> addrg: add arm64 build

recipes/bamm/build.sh, recipes/bamm/meta.yaml
=> update bamm and enabled linux-aarch64

recipes/vcf2maf/meta.yaml
Add `bcftools` dependency, as specified in the source code:
https://github.com/mskcc/vcf2maf/blob/bf53e52d32b33867c368206667f94ba4782550c1/vcf2vcf.pl#L18-L22
---- …
=> Update bcftools dependency

recipes/tmb/meta.yaml
Add `pandas` as dependency to fix bioinfo-pf-curie/TMB#32
---- …
=> Update pandas dependency

recipes/gsearch/meta.yaml
=> update  gsearch and enabled linux-aarch64

recipes/x-mapper/build.sh, recipes/x-mapper/meta.yaml, recipes/x-mapper/x-mapper.sh
=> Add x-mapper

recipes/influx_si/meta.yaml
=> added entry point to influx_si

recipes/ppanggolin/meta.yaml
=> Bump ppanggolin recipe

recipes/quick-variants/build.sh, recipes/quick-variants/meta.yaml, recipes/quick-variants/quick-variants.sh
=> Add quick-variants

recipes/elprep/build.sh, recipes/elprep/meta.yaml
=> elprep: add arm64 build

recipes/genepop/build.sh, recipes/genepop/meta.yaml
=> genepop: add arm64 build

recipes/fraggenescan/build.sh, recipes/fraggenescan/meta.yaml
=> fraggenescan: add arm64 build

recipes/phispy/meta.yaml
=> phispy: add arm64 build

recipes/clever-toolkit/build.sh, recipes/clever-toolkit/meta.yaml
=> clever-toolkit: add arm64 build

recipes/genepop/meta.yaml
=> Update genepop to v4.8.4

recipes/ngs-bits/build.sh, recipes/ngs-bits/meta.yaml
=> ngs-bits: add arm64 build

recipes/idba/build.sh, recipes/idba/meta.yaml
=> Rebuild idba recipe

recipes/nonpareil/meta.yaml
=> nonpareil: add arm64 build

recipes/tpmcalculator/build.sh, recipes/tpmcalculator/meta.yaml
=> tpmcalculator: add arm64 build

recipes/dsrc/build.sh, recipes/dsrc/meta.yaml
=> dsrc: add arm64 build

recipes/snap-aligner/build.sh, recipes/snap-aligner/meta.yaml
=> Rebuild snap-aligner recipe

recipes/magneto/meta.yaml
New magneto release 1.4 --> update meta.yaml
---- …
=> Update meta.yaml for magneto 1.4

recipes/biobb_haddock/meta.yaml
Revert change from https://github.com/bioconda/bioconda-recipes/pull/59062
---- …
=> [biobb_haddock] update 5.1.1 build 2

recipes/beagle/meta.yaml
Simple update of beagle from 5.4_29Oct24.c8e -> 5.5_27Feb25.75f
---- …
=> Update beagle to 5.5_27Feb25.75f

recipes/hecatomb/meta.yaml
bump new version; change source to pypi; update dependencies
---- …
=> Update Hecatomb to 1.3.4

recipes/comebin/build.sh, recipes/comebin/meta.yaml
=> Update COMEBin to use the utility script

recipes/snp-dists/0001-Makefile-append-CFLAGS-LIBS.patch, recipes/snp-dists/build.sh, recipes/snp-dists/meta.yaml
=> snp-dists: add arm64 build

recipes/phynder/build.sh, recipes/phynder/meta.yaml
=> phynder: add arm64 build

recipes/genbank/conda_build_config.yaml, recipes/genbank/meta.yaml
Update genbank to support Python 3.13 - first needed before phanotate can be update (sorry for deleting your commits to my repo @mencian  - but once this passes your solution should work for phanotate).
https://github.com/bioconda/bioconda-recipes/pull/59425
---- …
=> Update genbank to support python 3.13

recipes/art_modern/build.sh, recipes/art_modern/meta.yaml
Update art_modern to 1.1.7
---- …
=> Update art_modern to 1.1.7

recipes/rust-gtars/build.sh, recipes/rust-gtars/meta.yaml
This is update of building instructions for gtars package
---- …
=> Update gtars recipe

recipes/stringdecomposer/meta.yaml
=> stringdecomposer: add aarch64 build

recipes/decifer/build.sh, recipes/decifer/meta.yaml
=> decifer: add arm64 build

recipes/survivor/build.sh, recipes/survivor/meta.yaml
=> survivor: add arm64 build

recipes/bigtools/build.sh, recipes/bigtools/meta.yaml
=> bigtools: add arm64 build

recipes/ipk/build.sh, recipes/ipk/meta.yaml, recipes/ipk/run_test.sh
=> Rebuild ipk recipe

recipes/glimmerhmm/build.sh, recipes/glimmerhmm/meta.yaml
=> Rebuild GlimmerHMM recipe

recipes/knotinframe/build.sh, recipes/knotinframe/meta.yaml
=> knotinframe: add arm64 build

recipes/fasta3/build.sh, recipes/fasta3/meta.yaml
=> fasta3: add arm64 build

recipes/r-stitch/build.sh, recipes/r-stitch/meta.yaml
=> r-stitch: add arm64 build

recipes/dsk/build.sh, recipes/dsk/install_paths.patch, recipes/dsk/meta.yaml
=> dsk: add arm64 build

build-fail-blacklist, recipes/dbgraph/build.sh, recipes/dbgraph/meta.yaml
=> dbgraph: add arm64 build

recipes/tophat/0001-configure.ac.patch, recipes/tophat/0002-make_pair.patch, recipes/tophat/0003-tophat.patch, recipes/tophat/0004-Makefile.patch, recipes/tophat/build.sh, recipes/tophat/meta.yaml
=> Update tophat to v2.1.2

recipes/wgsim/0001-Fix-shebang-in-perl-script.patch, recipes/wgsim/build.sh, recipes/wgsim/meta.yaml
=> wgsim: add arm64 build

recipes/vcfsim/meta.yaml
Update the vcfsim recipe to point to its new repository location.
---- …
=> Update vcfsim: migrate repository to samuk-lab

recipes/r-dimsum/meta.yaml
ARM installs fail because r-base==4.0 is incompatible with the latest bioconductor dependencies:
Relaxing to >=4.0
this is a packaging-only change, hence build-number bump
---- …
=> r-dimsum: relax r-base pin (>=4.0); bump build number

recipes/seqwin/meta.yaml
=> Update Seqwin build number

recipes/paraviewer/meta.yaml
Add new recipe for tools to generate visualizations as a downstream analysis step for Paraphase
---- …
=> add paraviewer recipe

recipes/amiga/meta.yaml
=> Rebuild amiga recipe as noarch

build-fail-blacklist, recipes/soapdenovo2-gapcloser/build.sh, recipes/soapdenovo2-gapcloser/meta.yaml
=> Rebuild soapdenovo2-gapcloser recipe

recipes/bgen-cpp/build.sh, recipes/bgen-cpp/meta.yaml
Add [bgen](https://enkre.net/cgi-bin/code/bgen/dir?ci=trunk), the reference implementation of the [BGEN format](http://www.bgenformat.org/), written in C++.
Includes utilities for working with bgen files.
* [`bgenix`](https://enkre.net/cgi-bin/code/bgen/doc/trunk/doc/wiki/bgenix.md) - a tool to index and efficiently retrieve subsets of a BGEN file.
* [`cat-bgen`](https://enkre.net/cgi-bin/code/bgen/doc/trunk/doc/wiki/cat-bgen.md) - a tool to efficiently concatenate BGEN files.
* [`edit-bgen`](https://enkre.net/cgi-bin/code/bgen/doc/trunk/doc/wiki/edit-bgen.md) - a tool to edit BGEN file metadata.
* [`bgen` in conda-forge](https://anaconda.org/conda-forge/bgen) is a Python package for reading BGEN files
* This package was last updated 4-5 years ago. It can be tricky to get compiling …
=> Add bgen-cpp

recipes/kmc/build.sh, recipes/kmc/meta.yaml
=> KMC: Allow python >3.11

recipes/emboss/build.sh, recipes/emboss/meta.yaml
=> Rebuild emboss

recipes/lodei/meta.yaml
=> Update lodei v1.1.0

recipes/lca/build.sh, recipes/lca/meta.yaml
=> lca: add arm64 build

recipes/spaln/0001-configure.patch, recipes/spaln/build.sh, recipes/spaln/meta.yaml
=> Rebuild spaln recipe

recipes/randfold/build.sh, recipes/randfold/meta.yaml
=> randfold: add arm64 build

recipes/spades/0001-change-verbosity-remove-expr.patch, recipes/spades/build.sh, recipes/spades/conda_build_config.yaml, recipes/spades/meta.yaml
=> Rebuild spades recipe

recipes/sccellfie/meta.yaml
[scCellFie](https://github.com/earmingol/scCellFie) is a Python-based tool for analyzing metabolic activity from single-cell and spatial transcriptomic data.
<details>
<table>
<tr>
</tr>
<tr>
</tr>
</table> …
=> add Sccellfie tool

build-fail-blacklist, recipes/sweepfinder2/0001-Use-CC-and-flags.patch, recipes/sweepfinder2/build.sh, recipes/sweepfinder2/meta.yaml
=> Rebuild sweepfinder2 recipe

build-fail-blacklist, recipes/rnacode/build.sh, recipes/rnacode/meta.yaml
=> Update RNAcode to v0.3.1

recipes/rnabridge-align/build.sh, recipes/rnabridge-align/meta.yaml
=> rnabridge-align: add aarch64/arm64 builds

recipes/scallop/build.sh, recipes/scallop/meta.yaml
=> scallop: add aarch64/arm64 builds

recipes/scallop2/build.sh, recipes/scallop2/meta.yaml
=> scallop2: add aarch64/arm64 builds

recipes/trycycler/meta.yaml
=> Update trycycler to v0.5.6

recipes/rainbow/build.sh, recipes/rainbow/meta.yaml
=> rainbow: add aarch64/arm64 builds

recipes/eternafold/build.sh, recipes/eternafold/meta.yaml
=> Rebuild eternafold recipe

recipes/wtdbg/0001-master.patch, recipes/wtdbg/build.sh, recipes/wtdbg/meta.yaml
=> wtdbg: add aarch64 build

recipes/phipack/build.sh, recipes/phipack/conda_build_config.yaml, recipes/phipack/meta.yaml
=> phipack: add arm64 build

recipes/quickmirseq/build.sh, recipes/quickmirseq/meta.yaml, recipes/quickmirseq/patch
=> Add QuickMIRSeq

recipes/macs2/meta.yaml
Verified that the new test here identifies the error reported in #59362; locally at least it seems just a rebuild does the trick.
---- …
=> bump macs2; include better import test

recipes/hictk/build.sh, recipes/hictk/conanfile.py.patch, recipes/hictk/conda_build_config.yaml, recipes/hictk/meta.yaml
Recipe changelog:
- Bump package version
- Bump CXX_STANDARD to C++23 to be inline with the official [Dockerfile](https://github.com/paulsengroup/hictk/blob/b57a35fceccfeba5dd7a4132c37d2a1f30f08a0b/Dockerfile#L27)
- Bump clang version used to compile the project
- Update conanfile.py patch.
Note that for this package release, I am using Conan to download and install fmt as a header-only library.
This is necessary because fmt v12, which comes with some nice performance benefits, is not yet packaged by conda-forge
Closes https://github.com/bioconda/bioconda-recipes/pull/59831
----
* If this PR adds or updates a recipe, use "Add" or "Update" …
=> Update hictk to v2.1.5

recipes/atol-qc-raw-shortread/meta.yaml
=> Add atol-qc-raw-shortread

recipes/last/build.sh, recipes/last/meta.yaml
=> Update last to 1648

recipes/bbmap/meta.yaml
=> Update BBMap to 39.37

recipes/python-msgpack/build.sh, recipes/python-msgpack/meta.yaml
=> python-msgpack: add arm64

recipes/gvcfgenotyper/build.sh, recipes/gvcfgenotyper/meta.yaml
=> gvcfgenotyper: add arm64 build

recipes/funannotate/build.sh, recipes/funannotate/meta.yaml
xref https://github.com/galaxyproject/tools-iuc/issues/7267
---- …
=> try to make funannotate aux_scripts executable
